### ISSUE TITLE
RelatedSel always last one fk

### ISSUE THREAD

**Issue by li76168** [astaxie/beego#1002]
// set relation model to query together.
// it will query relation models and assign to parent model.
func (o querySet) RelatedSel(params ...interface{}) QuerySeter {
    var related []string
    if len(params) == 0 {
        o.relDepth = DefaultRelsDepth
    } else {
        for _, p := range params {
            switch val := p.(type) {
            case string:
                related = append(o.related, val) => related = append(related, val)
            case int:
                o.relDepth = val
            default:
                panic(fmt.Errorf("<QuerySeter.RelatedSel> wrong param kind: %v", val))
            }
        }
    }
    o.related = related
    return &o
}

**Comment by ptman** [comment]
Is this supposed to be a diff? Why not send a pull request instead? Did 0222b8d69336cf9903f0cdb946eb36ba3cbb80cc fix your problem?
