### ISSUE TITLE
insert时为Id赋值

### ISSUE THREAD

**Issue by huhr** [astaxie/beego#1005]
我的model里主键Id，不过在为id赋值了，
insert的时候id还是会从0开始，这个。。
我把model的Id字段改了成了Uid使用
`orm:"pk;column(id)"` 才能正确的把Id
存进去，这个实现不太合理吧

**Comment by lei-cao** [comment]
@huhr Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
