### ISSUE TITLE
api测试

### ISSUE THREAD

**Issue by yanlinpu** [astaxie/beego#1006]
tests/hospital_test.go   

    func init() {
	  _, file, _, _ := runtime.Caller(1)
	  apppath, _ := filepath.Abs(filepath.Dir(filepath.Join(file, ".." + string(filepath.Separator))))
	  beego.TestBeegoInit(apppath)
    }
    func TestHospitalV1Get(t *testing.T) {
	  r, _ := http.NewRequest("GET", "/v1/hospitals/1", nil)
	  w := httptest.NewRecorder()
	  beego.BeeApp.Handlers.ServeHTTP(w, r)
    }
http://localhost:8080/v1/hospitals/1这个接口可以访问  
测试结果如下：（应该怎么写测试用例）

![w hoi 1wfaaqgeud7 f9dss](https://cloud.githubusercontent.com/assets/3785079/5736120/d663d458-9c0c-11e4-94a0-05d5bea5b6de.png)

**Comment by lei-cao** [comment]
@yanlinpu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
