### ISSUE TITLE
beego的MemoryCache这样设计合理吗？

### ISSUE THREAD

**Issue by xdeng** [astaxie/beego#1007]
我用Get函数获取数据，由于超时了所以 beego:interface conversion: interface is nil, not int64 ，查看源码发现是Get的时候也去计算时间了，超时会清空然后返回nil ，  好吧可能是我用的不对 。

改过之后我先 用IsExist判断是否存在，然后再Get获取，坑的是超时了还是返回 nil ，既然存在为什么还返回空？ 再查看源码发现IsExist是没有计算时间的，既然Get是读数据去判断是否超时了， 那为什么IsExist就不去判断呢？

你叫我怎么用？难到要用两次Get？第一次判断nil 第二次获取？  或者先取出interface类型判断是否为nil 再断言类型？

**Comment by wangkechun** [comment]
刚刚才被坑了。结果一来github就看到了这个issue。

**Comment by xdeng** [comment]
@wangkechun 取出interface类型判断是否为nil     再断言类型

**Comment by lei-cao** [comment]
@xdeng Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by xdeng** [comment]
@lei-cao  你可以选择 不看 或者 忽略

**Comment by lei-cao** [comment]
related https://github.com/astaxie/beego/issues/1139

**Comment by lei-cao** [comment]
@astaxie close? duplicated
