### ISSUE TITLE
希望添加功过go generate生成router目录下的路由.go文件

### ISSUE THREAD

**Issue by timesking** [astaxie/beego#1008]
在使用1.4.2版本中，我们不得不提交一个临时生成的.go文件到自己的代码仓库中，否则在一个全新的环境下go build会生成一个没有任何router信息的binary，而且beego框架并没有给出警告，尤其实在runmode=prod的时候。

因此建议通过你过go generate能够生成相关的.go文件

**Comment by simpleton** [comment]
up

**Comment by lei-cao** [comment]
@timesking Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
