### ISSUE TITLE
Redis session handler not working between page requests

### ISSUE THREAD

**Issue by terah** [astaxie/beego#1009]
Hi,

I am creating a toy app for learning Go.  The app is available here: https://github.com/terah/budget-planner-go

I've enabled the redis session handler in the app.conf and go get'd the redis library dependency.  The session handler compiles fine.  The problem I have is that after login, the page redirects to the home page which can't find the session variable in redis which then redirects back to the login screen again.

Everything works fine using the memory session handler.

**Comment by astaxie** [comment]
it should be works
