### ISSUE TITLE
beego模板语法错误误报为找不到模板的bug

### ISSUE THREAD

**Issue by Violam** [astaxie/beego#1011]
看起来是在模板里面里面使用这个/引起的
例如丢一句{{/if}} ，那么就会这么报错：

2015/01/23 18:12:47 [D] parse template err: toolsview/trendcampaign.tpl template: toolsview/trendcampaign.tpl:107: unexpected "/" in command
2015/01/23 18:12:47 [C] the request url is  /tools/trendcampaign
2015/01/23 18:12:47 [C] Handler crashed with error can't find templatefile in the path:toolsview/trendcampaign.tpl

当然，正确写法应该是{{end}}
改正后，模板文件就能找到。

**Comment by lei-cao** [comment]
@Vioiam Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
