### ISSUE TITLE
Error Handling - Override

### ISSUE THREAD

**Issue by Zevran** [astaxie/beego#1012]
Hi,

I am just asking why are you overriding custom handler ?

Let's imagine that I want to handle a 404 error with a json content type, the method Exception in error middleware override json content type with html. 

https://github.com/astaxie/beego/blob/master/middleware/error.go#L322
https://github.com/astaxie/beego/blob/master/middleware/error.go#L323

**Comment by apremalal** [comment]
@astaxie I can confirm this issue.  There's an open issue here https://github.com/astaxie/beego/issues/2207
