### ISSUE TITLE
Swagger 路由2层没有问题 ，3层后提示： Unable to read api 'setting' from path http://127.0.0.1:7002/docs/setting (server returned undefined)

### ISSUE THREAD

**Issue by evilboyjava** [astaxie/beego#1013]
我原来的路由是2层的，swagger 可以显示接口文档，如下 ： 
	ns := beego.NewNamespace("/commservice",
			beego.NSNamespace("/settingdb", beego.NSInclude(&controllers.DbConfigController{})),
			beego.NSNamespace("/settingcloud", beego.NSInclude(&controllers.CloudConfigController{})),
	)
	beego.AddNamespace(ns)

现在路由改成3层后，WEB UI 提示：  Unable to read api 'setting' from path http://127.0.0.1:7002/docs/setting (server returned undefined)
	ns := beego.NewNamespace("/commservice",
		beego.NSNamespace("/setting",
			beego.NSNamespace("/db", beego.NSInclude(&controllers.DbConfigController{})),
			beego.NSNamespace("/cloud", beego.NSInclude(&controllers.CloudConfigController{})),
		),
	)
	beego.AddNamespace(ns)

**Comment by astaxie** [comment]
swagger的UI只支持两层的文档，三层的没办法展示

**Comment by benzsuankularb** [comment]
@evilboyjava 
you could do this in swagger page
`swaggerUi.api.basePath = http://localhost:8080/v0`
