### ISSUE TITLE
go test -v 无法正确执行

### ISSUE THREAD

**Issue by congjunwei** [astaxie/beego#1015]
bee test命令去掉了吗？文档里有，看代码是注释了，不支持了吗？
 go test tests/default_test.go测试用例
首先无法找到配置文件。默认寻找的config文件是指向/tests/conf/app.conf下，但是并不会自动生成，我拷贝了/conf/app.conf到tests下，通过这个坑。
但是
r, _ := http.NewRequest("GET", "/v1.4/user/info?userid=10005&uid=10005", nil)
	w := httptest.NewRecorder()
	beego.BeeApp.Handlers.ServeHTTP(w, r)
	//	beego.Trace("testing", "TestGet", "Code[%d]\n%s", w.Code, w.Body.String())
	beego.Error(w.Body.String())
	Convey("主题：用户信息接口测试\n", t, func() {
		Convey("Http状态码必须是200", func() {
			So(w.Code, ShouldEqual, 200)
		})
		Convey("结果必须不能为空", func() {
			So(w.Body.Len(), ShouldBeGreaterThan, 0)
		})
	})
以上简单的用例无法通过。返回页面内容报错，
Request URL:为空
RemoteAddr:为空

**Comment by astaxie** [comment]
你看看用bee new创建的项目下面的test怎么写的，要调用beego.TestBeegoInit

**Comment by lei-cao** [comment]
@congjunwei Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable? @congjunwei is your issue solved?
