### ISSUE TITLE
Beego ORM doesn't support default for PostgreSQL

### ISSUE THREAD

**Issue by owentran** [astaxie/beego#1017]
According to the docs... http://beego.me/docs/mvc/model/models.md you should be able to define a default value for a columns like so...

```
type User struct {
    ...
    Status int `orm:"default(1)"`
    ...
}
```

However, all that does is add a column called status that is not null, but has no default...

```
table `users` already exists, skip
add column `.../beego/models.User.Status` for table `users`
    ALTER TABLE "users" ADD COLUMN "status" integer NOT NULL
```

Is default not supported anymore? There doesn't seem to be any commits to the ORM project for 5 months. Do you recommend a different ORM?

A workaround for now is just to add the defaults to the column with SQL commands.

**Comment by astaxie** [comment]
in the develop branch support default now. I will release this month.

**Comment by muhammad-asif** [comment]
@astaxie does the support exit for String fields ?
