### ISSUE TITLE
How to use bee bale?

### ISSUE THREAD

**Issue by txchen** [astaxie/beego#1018]
Cannot find the document about this command, can someone share some information since I want to build single binary for my site.

**Comment by txchen** [comment]
Figured out by reading the code, share my finding here in case someone else has the same question.

To use bale, we need to create a 'bee.json' file at your beego project root. Content like:

```
{
  "bale": {
    "dirs": ["static", "views"]
  }
}
```

Next, run `bee bale`, it would generate a bale.go and a bale directory which contains the asset go files.

I found one bug that in bale.go, there is an unnecessary import statement, which would break the build. To workaround, manually remove it.

Next, bee run or build. bale.go is now included in your output binary.

The bale logic is: when app starts, it check if the static files exists in current dir, if not, it will use the assets files to save the static files to disk. 

However, I don't think this solution is perfect because I want "pure single executable" without extracting some files to disk.

**Comment by gucki** [comment]
@txchen Did you find a solution for "pure single executable"?

**Comment by txchen** [comment]
@gucki No. Actually I switched to use other frameworks:)

**Comment by ahmadissa** [comment]
@txchen which framework?

**Comment by ihippik** [comment]
@astaxie why bee bale generates a file is not valid file bale.go? 
import(
	"os"
	"strings"
	"path"

	""
)

**Comment by amrfaissal** [comment]
@ihippik you need to pass the static dirs where your JS and CSS are located. If you're using `bee.json`, you can specify it like this:
```
//...
"bale":{
   "dirs": ["static/js", "static/css"]
}
//...
```
Otherwise it won't work!

**Comment by ihippik** [comment]
@amrfaissal  i use this json:

`{
  "bale": {
    "dirs": ["tmp","swagger"]
  }
}`

**Comment by amrfaissal** [comment]
@ihippik What I noticed when running `bee bale` is that it will read all your static files in the specified dirs (*.js, *.css) and generate a *.go file per static file (something like `static_js_jquery_xxx.go`) inside a `bale` folder.

Check also if you have nested folders inside tmp and swagger. In my case, all my JS and CSS files were inside `static/js` and `static/css`.
