### ISSUE TITLE
NullTime like NullString etc.

### ISSUE THREAD

**Issue by ptman** [astaxie/beego#1019]
Is there an easy way to use a NullTime type in Beego ORM? Or does support need to be added to the ORM? There is at least such types for most popular databases:  http://godoc.org/github.com/lib/pq#NullTime http://godoc.org/github.com/go-sql-driver/mysql#NullTime

**Comment by astaxie** [comment]
how to use this? can you provide some example code.

**Comment by ptman** [comment]
That's what I'm asking. I would like to use a NULLable timestamp in my schema, but Beego ORM makes it very tricky. Beego ORM supports NullString, NullBool, etc. But not NullTime. How would I use NullTime with Beego ORM?

**Comment by ptman** [comment]
I'll have to test if simply specifying the nullable time column as *time.Time helps, but I would like for some NullTime type to exist.

**Comment by ptman** [comment]
struct Foo {
        Id int
        Time *time.Time
    }

results in:
    
    panic: reflect: call of reflect.Value.Interface on zero Value
