### ISSUE TITLE
Router filter is not working for top level path (http://domain.com/)

### ISSUE THREAD

**Issue by 1337hax** [astaxie/beego#1020]
I have following code in router.go:

```go
func init() {
	beego.SetStaticPath("/static", "static")

	beego.Router("/login", &controllers.LoginController{})
	beego.Router("/signoff", &controllers.LoginController{}, "get:SignOff")
	beego.Router("/", &controllers.HomeController{}) // filter is not working for this rule

	beego.Router("/dashboard", &controllers.HomeController{})
	beego.InsertFilter("*", beego.BeforeRouter, infrastructure.FilterAuthenticateRequest)
}
```
Despite inserting filter with `"*"`, which should match all requests according to the documentation, all requests to http://mydomain.com/ are not filtered. My filter handler function `infrastructure.FilterAuthenticateRequest` is not invoked at all for that path. Requests to other paths are filtered properly.
I thought it might be the case that rule `"*"` requires any characters after / in URL to match, so I tried adding filter with empty rule: `beego.InsertFilter("", beego.BeforeRouter, infrastructure.FilterAuthenticateRequest)`, but that results in runtime exception (or "panic", I'm new to Go :) )

**Comment by astaxie** [comment]
what's your beego version. use `bee version`

**Comment by 1337hax** [comment]
My output of `bee version`:
```
bee   :1.2.4
beego :1.4.2
Go    :go version go1.2.1 linux/amd64
```

**Comment by kaixinmao** [comment]
bee   :1.2.4
beego :1.4.3
Go    :go version go1.4.1 windows/amd64

**Comment by metakon555** [comment]
same, request to http://mydomain.com/ not filtered with "*" or with "/" or with "",

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.11.2
├── GoVersion : go1.12.3
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\go_work
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Thursday, 30 May 2019
