### ISSUE TITLE
Multi-module MVC structure in Beego? [with/without model service layer pattern]

### ISSUE THREAD

**Issue by redstrike** [astaxie/beego#1022]
Here are Phalcon MVC's examples: https://github.com/phalcon/mvc

For better code reuse and ease to manage code base, I want to share model / data layer with [backend / frontend / desktop ver. / mobile ver. / API for serving mobile app later].

I wonder is there an idiomatic way to make Beego works with multi-module MVC structures? Or is there a better way to accomplish above requirement?

**Comment by astaxie** [comment]
I have no idea on this problem now.

**Comment by redstrike** [comment]
After the discussion with my friend, I come to the conclusion that multi-module MVC structure (which is shared models) will make our codebase to a state that contains two fat models and highly coupling modules/system. It's not good for medium and large projects in the long term.

So, building a central API is always a better approach.

Thanks for your efforts.
