### ISSUE TITLE
Routing Performance .

### ISSUE THREAD

**Issue by webgini** [astaxie/beego#1029]
Hello beego guys , 

i was going throught routing benchmarks recently and i found some numbers there , i am fan of beego for quite a time now. https://github.com/julienschmidt/go-http-routing-benchmark you can analize numbers , so can you optimize beego to that level , no then why ? thnks in advance for such a great framework.

**Comment by astaxie** [comment]
it's really an old benchmark. but from that benchmark I found some performance issue in the old version route. Now it's really fast. https://github.com/julienschmidt/go-http-routing-benchmark/issues/4#issuecomment-53211679

**Comment by webgini** [comment]
gud to know man. keep up the good work with beego. loved a lot

On Mon, Feb 9, 2015 at 7:26 AM, astaxie <notifications@github.com> wrote:

> it's really an old benchmark. but from that benchmark I found some
> performance issue in the old version route. Now it's really fast. julienschmidt/go-http-routing-benchmark#4
> (comment)
> <https://github.com/julienschmidt/go-http-routing-benchmark/issues/4#issuecomment-53211679>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astaxie/beego/issues/1029#issuecomment-73447141>.
>



-- 

[image: --]

Vijay Bambhaniya
[image: http://]about.me/vbambhaniya
<http://about.me/vbambhaniya?promo=email_sig>
