### ISSUE TITLE
Orm hasMany relation not working

### ISSUE THREAD

**Issue by elyzov** [astaxie/beego#1030]
I have two models: User and Tick.

```
type User struct {
  Id      int
  Name    string    `valid:"MaxSize(64)"`
  Ticks   []*Tick   `orm:"reverse(many)"` // reverse relationship of fk
}

type Tick struct {
  Id        int
  User      *User     `orm:"column(user_id);rel(fk)"`     // RelForeignKey relation
  Title     string    `valid:"Required;MaxSize(64)"`
}
```
But when I try get user.Ticks I always get null:

```
var user *User
o.Read(&user)
fmt.Println(user.Ticks)
```
What I do wrong? Or hasMany relation is absent in BeeGo?

**Comment by theaidem** [comment]
Maybe you should trying [RelatedSel](http://beego.me/docs/mvc/model/query.md#relatedsel) queries

**Comment by elyzov** [comment]
It's work for me, thx! I could not find this doc there.

**Comment by yaninagm** [comment]
Hello, I used LoadRelated, but Ticket list User into himself:

[
    {
        "Id": 1,
        "Name": "prueba",
        "Ticks": [
            {
                "Id": 1,
                "User": {
                    "Id": 1,
                    "Name": "prueba",
                    "Ticks": null
                },
                "Title": "titulo"
            },
            {
                "Id": 1,
                "User":{
                    "Id": 1,
                    "Name": "prueba",
                    "Ticks": null
                },
                "Title": "titulo"
            }
        ]
    }
]
