### ISSUE TITLE
orm的数据库建表功能能不修改表名和字段名吗?

### ISSUE THREAD

**Issue by bronze1man** [astaxie/beego#1031]
我希望某个地方有一个配置,可以控制这个修改表名和字段名的功能是否启用.(大小写和下划线转换)

之前有一个项目用了beego的orm模块,被程序里面的表名和数据库里面的表名搞的迷迷糊糊.

另一个用php的项目,没用orm模块,也没有表名和字段名转换功能,这一块就特别简单和清晰,同一个东西在任何的地方的名字都是一样的.

新项目准备用beego的orm,但是又害怕被这个表名和字段名的自动转换给坑了.

ps: 系统不区分大小写什么的也是个坑,我已经开发了工具在git里面找到并且修复由于系统不区分大小写带来的bug了.

**Comment by astaxie** [comment]
第一下划线这个是潜规则，因为在Go里面采用了驼峰设计，所以很多表的设计就采用这个，转换过去就是`_`, 如果你的字段名和表名是自定义的，ORM完全可以支持。

自定义表名：
http://beego.me/docs/mvc/model/models.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%90%8D

自定义字段名：
http://beego.me/docs/mvc/model/models.md#column

**Comment by bronze1man** [comment]
自定义表名的问题是太麻烦了.
如果你觉得命名转换是小问题的话,那就算了.
我只能fork一个beego orm 改成我想要的样子.

**Comment by LiWenGu** [comment]
能支持下，可以配置是否开启驼峰法吗，比如有的项目数据库就是大写而不是下划线，这样只能给每个字段都加个配置，会麻烦很多

**Comment by bronze1man** [comment]
@LiWenGu 是啊.
命名字符串自动转换功能一定会带来一堆麻烦.(我已经遇到过好多个奇葩库干这种事情了)
最严重的是 grep 工具无效了.以及新手懵逼.(不区分大小写也不行)
最后就变成了每张表都有一个配置.
最佳实践应该是什么不要做.并且可以配置一个回调让使用者随意变换命名.
