### ISSUE TITLE
Access logs disapear in production mode

### ISSUE THREAD

**Issue by joaonrb** [astaxie/beego#1032]
When I turn my app from dev to prod in app.conf the server stops output access logs. I search in documentation and couldn't find any solution. How can I activate the access logs in production?

**Comment by astaxie** [comment]
yea, the access logs only show in the dev. there's no other ways can activate it.

**Comment by rvm2015** [comment]
This should really be a configuration option. If I'm building an app to conform to 12 factor I need to be able to kick these logs out to console.

Where in the source is this configured? I'd like to modify it temporarily for my environment.

**Comment by astaxie** [comment]
it's already fixed. `beego.AccessLogs=true`.

**Comment by rvm2015** [comment]
Thanks, this is working however it only works when set in a controller. You cannot set AccessLogs = true in app.conf.

**Comment by astaxie** [comment]
you can set in app.conf

**Comment by rvm2015** [comment]
This does not appear to be working in master as of now. Testing with a vanilla beego new install. app.conf looks like this

    appname = howihuman/accountapi
    httpport = 8080
    runmode = prod
    AccessLogs = true

    [dev]
    EnableAdmin = true

**Comment by astaxie** [comment]
sorry for the wrong instruction. Yea, it not support app.conf now. but you can set `beego. AccessLogs` in the main.go. not in the controller

**Comment by rvm2015** [comment]
Works for me, thanks much.
