### ISSUE TITLE
Register Model Error

### ISSUE THREAD

**Issue by WanliTian** [astaxie/beego#1035]
>This is my code:

    import (
        "github.com/astaxie/beego/orm"
        _ "github.com/go-sql-driver/mysql"
    )
    
    type TT struct {
        Id       int 
        AccoutId string `orm:"size(64)", json:"account_id"`
        Name     string `orm:"size(64)", json:"name"`
    }
    
    func init() {
        orm.RegisterModel(new(TT))
    }

>And I got this:

    panic: <orm.RegisterModel> cannot use non-ptr model struct `.string`

**Comment by astaxie** [comment]
from you error infomation, I don't think it's come from this code.
