### ISSUE TITLE
Cors Post method issue

### ISSUE THREAD

**Issue by webgini** [astaxie/beego#1037]
Hello astaxie , 
i am having small issue with CORS. according to cors plugin , i have set all things , and all seems working fine. but when i do post request , beego is managing as OPTIONS request, and other thing is i need to explicitly put OPTIONS method then only route is matching. please try to automate this things as without this rest api framework has no meaning. thank you in advance.

**Comment by webgini** [comment]
func main() {

	beego.InsertFilter("*", beego.BeforeRouter, func(ctx *context.Context) {
		if ctx.Input.Method() == "OPTIONS" {
			ctx.Output.Header("Access-Control-Allow-Origin", "*")
			ctx.Output.Header("Access-Control-Allow-Methods", "GET,POST,DELETE,PUT")
			ctx.Output.Header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
			ctx.Abort(200, "Hello")
		}
	})

	if beego.RunMode == "dev" {
		beego.DirectoryIndex = true
		beego.StaticDir["/swagger"] = "swagger"
	}
	beego.Run()
}

**Comment by webgini** [comment]
solved.

**Comment by Ligerlilly** [comment]
What was the solution?

**Comment by hsluoyz** [comment]
What he posted is the solution:

```go
beego.InsertFilter("*", beego.BeforeRouter, func(ctx *context.Context) {
    if ctx.Input.Method() == "OPTIONS" {
        ctx.Output.Header("Access-Control-Allow-Origin", "*")
        ctx.Output.Header("Access-Control-Allow-Methods", "GET,POST,DELETE,PUT")
        ctx.Output.Header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
        ctx.Abort(200, "Hello")
    }
})

if beego.RunMode == "dev" {
    beego.DirectoryIndex = true
    beego.StaticDir["/swagger"] = "swagger"
}
beego.Run()
```
