### ISSUE TITLE
bindInt 不能获取转换的错误

### ISSUE THREAD

**Issue by jsix** [astaxie/beego#1038]
你好，谢大！ 看到有人问orm插入一个不合法的值，对应可以存到db中（类型tinyint,存储值为0)
于是找到了以下代码：

func (input *BeegoInput) bindInt(val string, typ reflect.Type) reflect.Value {
intValue, err := strconv.ParseInt(val, 10, 64)
if err != nil {
return reflect.Zero(typ)
}
pValue := reflect.New(typ)
pValue.Elem().SetInt(intValue)
return pValue.Elem()
}

 外部似乎没有办法知道这个string不是一个可以成功转换的int值

**Comment by astaxie** [comment]
你需要返回获取返回值，判断是否是reflect.Zero值

**Comment by lei-cao** [comment]
@jsix Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable? @jsix  is your issue solved?
