### ISSUE TITLE
migration 命令出错

### ISSUE THREAD

**Issue by Salon-sai** [astaxie/beego#1042]
当我写完migration文件，想试着用用。
然后我就使用文档中的bee migrate [-driver=mysql] [-conn="root:@tcp(127.0.0.1:3306)/test"]命令，结果：
Could not run migration binary: exec: "./m": file does not  exist
难道要编译一个m.exe文件吗？从源码看那个m.exe是我写的migration文件吗？还是怎么说呢？
小弟刚接触golang，请各位大神帮帮忙~谢谢

**Comment by astaxie** [comment]
你是在什么目录执行这个命令的？

**Comment by lei-cao** [comment]
@Salon-sai Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable? @Salon-sai  is your issue solved?
