### ISSUE TITLE
cookie session初始化错误

### ISSUE THREAD

**Issue by kaixinmao** [astaxie/beego#1048]
环境window7 64.bit
go 1.4.1
beego 1.4.2

问题:
加入配置:
```
SessionOn = true
SessionProvider = cookie
SessionName = iotalarm
SessionCookieLifeTime = 86400
```
启动报错:
panic: unexpected end of JSON input

个人定位问题为：
/session/sess_cookie.go  119行 方法：SessionInit 
参数config默认为`""`空字符串
json解析报错

**Comment by lei-cao** [comment]
@kaixinmao Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
