### ISSUE TITLE
Auto redirect to secure port

### ISSUE THREAD

**Issue by Ernie6711** [astaxie/beego#1049]
How to config Beego server so that when a user connects http://mysite, he will be auto redirected to httpS://mysite.

I saw a previous discussion in #401 but with no clear solution.

**Comment by astaxie** [comment]
it doesn't support this feature.

**Comment by Ernie6711** [comment]
That's cool, but "/*" doesn't work well. I did a little modification to make it work properly. Thanks for responding!

    package main
    
    import (
    	"github.com/astaxie/beego"
    	"github.com/astaxie/beego/context"
    )
    
    func main() {
    	beego.InsertFilter("/", beego.BeforeRouter, RedirectHttp)  // for http://mysite
    	beego.InsertFilter("*", beego.BeforeRouter, RedirectHttp)  // for http://mysite/*
    	beego.Run()
    }
    
    var RedirectHttp = func(ctx *context.Context) {
    	if !ctx.Input.IsSecure() {
                // no need for an additional '/' between domain and uri
    		url := "https://" + ctx.Input.Domain() + ctx.Input.Uri()
    		ctx.Redirect(302, url)
    	}
    }
