### ISSUE TITLE
TestBeegoInit()中的 RunMode="test"设置无效

### ISSUE THREAD

**Issue by elvin-lian** [astaxie/beego#1057]
源码
```
// beego: v1.4.3
// beego.go
// line 337
func TestBeegoInit(apppath string) {
	AppPath = apppath
	RunMode = "test"
	AppConfigPath = filepath.Join(AppPath, "conf", "app.conf")
	err := ParseConfig()
	if err != nil && !os.IsNotExist(err) {
		// for init if doesn't have app.conf will not panic
		Info(err)
	}
	os.Chdir(AppPath)
	initBeforeHttpRun()
}
```

这里虽然设置了RunMode = "test"，但是依然是读取 app.conf里的设置的值。

解决：需要将 RunMode = "test"这一行代码，移动到 ParseConfig()后面

**Comment by kyle-wang** [comment]
beego只是支持dev和prod这两个RunMode吧？RunMode是全局变量，PaseConfig()函数会从配置文件中给这些参数赋值，当然会覆盖掉你前面设置的这个值。

**Comment by elvin-lian** [comment]
看 bee api 生成的项目的tests下的测试用例，是调用到 TestBeegoInit()这个方法的。 这方法里面有 RunMode="test"这个环境。

**Comment by lei-cao** [comment]
@elvin-lian Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
