### ISSUE TITLE
兩個莫名的錯誤：（1）QueryRows 無法更新 object 的值 （2） 更新 beego 到最新版後，原來使用到 session 的 code 出現multiple-value GlobalSessions.SessionStart() in single-value context 的錯誤

### ISSUE THREAD

**Issue by WithGJR** [astaxie/beego#1060]
關於第一個問題，我有以下的程式碼：

type Tag struct {
	Id     int64 `orm:"pk;auto"`
	Name   string
	PostId int64
}

var alreadyExistTags []models.Tag
_, err = o.Raw("SELECT name FROM tag WHERE post_id = ?", post_id).QueryRows(&alreadyExistTags)
fmt.Println(alreadyExistTags)
fmt.Println(err)

奇怪的是上面的 SQL 並沒有錯誤（err == nil），然而 alreadyExistTags 的值卻沒有被更新，抓到的都是空 slice ，但是最鬼怪的地方是其他使用 QueryRows 的地方並沒有這個問題，就只有這一個地方出現

至於第二個問題就如同標題所說的一般，原本運行好好的 code 更新到最新版就出現了這個 error

**Comment by lei-cao** [comment]
@WithGJR Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
