### ISSUE TITLE
BeegoHttpRequest.req 支持其他格式（Json）

### ISSUE THREAD

**Issue by fugr** [astaxie/beego#1064]
Request增加支持Json格式的接口

**Comment by fugr** [comment]
func (b *BeegoHttpRequest) Body(data interface{}) *BeegoHttpRequest {}
Body接口不够方便，增加BodyJson()接口

**Comment by kyle-wang** [comment]
增加这个借口意义不大啊，直接将返回值中的body部分取出来解析json就可以了啊
