### ISSUE TITLE
ORM 錯誤：BLOB/TEXT column 'content' can't have a default value

### ISSUE THREAD

**Issue by WithGJR** [astaxie/beego#1072]
我的 model 定義：

type Post struct {
	Id            int64     `orm:"pk;auto"`
	Title         string    
	Path          string   
	Content       string    `orm:"type(text)" `
	Published     bool      `orm:"default(false)"`
	PublishedTime time.Time `orm:"auto_now_add;type(datetime)"`
	Tags          []*Tag    `orm:"reverse(many)"`
}

更新新版之後才出現這個問題。

Google 之後發現這好像是 Mysql 的問題，不過之前orm自動產生的 table 沒這個問題，所以想詢問作者是否這是個 bug ?

**Comment by sunfengqi** [comment]
我也有这个问题，希望作者解决下，一不小心更新下数据库就挂了

**Comment by Comdex** [comment]
这个问题解决了没？我也在更新到1.5后出现这个问题

**Comment by sunfengqi** [comment]
解决了

在 2015-08-13 16:12:17，"Comdex" <notifications@github.com> 写道：


这个问题解决了没？我也在更新到1.5后出现这个问题

**Comment by micln** [comment]
up

**Comment by Comdex** [comment]
怎么解决的？

**Comment by micln** [comment]
我是临时从数据库改的。。

**Comment by Comdex** [comment]
能请问一下怎么改么？把type(text)改成其他的？

**Comment by sunfengqi** [comment]
只要有text类型的 `orm:"type(text);null"` 这样改就可以了。你把数据库的日志打开。在conf.go里面err = orm.RunSyncdb("default", false, true)。就可以找到在什么文件，什么行号里面了

**Comment by Comdex** [comment]
已经解决了，谢谢了

**Comment by lei-cao** [comment]
@WithGJR Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable
