### ISSUE TITLE
Controller定义Error异常

### ISSUE THREAD

**Issue by ElvizLai** [astaxie/beego#1073]
使用1.4.3中新增的错误注册方法，参照官方文档，实践时发送异常，预期结果为展示views目录下的404.html页面，实际运行结果为：将该文件做的下载处理，并未展现页面。

经过排查，conf中EnableGzip = true时错误页面下载，如果未开启该压缩，则正常显示。

http://www.unionspower.com/docs/mvc/controller/errors.md

**Comment by mlgd** [comment]
Exactly. Error controller don't work with Gzip compression enabled

**Comment by ElvizLai** [comment]
@astaxie Is this a beego bug?
