### ISSUE TITLE
beego/logs 自定义log格式输出

### ISSUE THREAD

**Issue by cheney** [astaxie/beego#1075]
有些业务要跟其它项目的log输出格式一样，现有的log不支持自定义log格式的输出，谢大在下一版的时候加个自定义log格式输出方法吧。

**Comment by lei-cao** [comment]
@cheney Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by saturn4er** [comment]
@lei-cao,@cheney said that some users needs to have their own log format, but current version of beego doesn't support it, and it would be nice to add this feature to future versions of beego

**Comment by astaxie** [comment]
works in beego1.6.2

**Comment by CodeJuan** [comment]
@astaxie 请问是要调用哪个接口进行设置？
How to set my own log format? 
Thank you.

**Comment by cafra** [comment]
Our project also encountered such a demand. Multi-module needs to be unified at the beginning of the log and then output to elk via filebeat. However, the style cannot be specified.

beego 1.9.2
