### ISSUE TITLE
Unable to load config files in file scoped variables when testing

### ISSUE THREAD

**Issue by kusold** [astaxie/beego#1076]
I have a test case that is reproducing the issue. https://github.com/Kusold/test-config-issue/commit/f243e8604c8b4fd290b2160420311fc4a5a09617 The test case was generated with `bee new test-config-issue`, then just whatever is in the referenced commit. 

When I run `go test`, the following log message shows up despite the TestBeegoInit:
`[config.go:285] [W] open /home/mike/Development/go/src/github.com/Kusold/test-config-issue/tests/conf/app.conf: no such file or directory`

I've been trying to track this down, and I _think_ the root cause is that beego is trying to load the `app.conf` before the `TestBeegoInit` can run. Moving the variable declaration inside of the `Get()` passes the test case.

**Comment by mewben** [comment]
Having this problem too.. :(

**Comment by ElvizLai** [comment]
+1

**Comment by levilovelock** [comment]
+1

**Comment by ZloiBubr** [comment]
+1

**Comment by astaxie** [comment]
fix in beego 1.7
