### ISSUE TITLE
Failure when generating docs

### ISSUE THREAD

**Issue by twisted1919** [astaxie/beego#1080]
Hey,

i am playing around with generating an api app and inside models folder, i have two files, user.go and user_access_level.go .

In user.go, i have the User struct definition, something like:
```GO
type User struct {
[...]
	AccessLevel AccessLevel `json:"-"`
[...]
}
```

In user_access_level.go, i define a new type:
```GO
// byte is alias for uint8 but we need more, thus uint64
type AccessLevel uint64

```

When i run `bee generate docs`, i get `2015/03/13 17:28:31 can't find the object: models.AccessLevel`
but the app works just fine, it's just this command that complaints.

Any idea why?

Thanks.

**Comment by ericx10ng** [comment]
It only support self-defined type is Struct type.
