### ISSUE TITLE
Mysql, Model, Template

### ISSUE THREAD

**Issue by jniltinho** [astaxie/beego#1088]
View

Howto arithmetic expression in View ?

Example:
{{$v.Quota/1024}}

<table class='data-table table table-bordered' data-pagination-records='5' style='margin-bottom:0;'>
                            <thead>
                              <tr>
                                <th></th>
                                <th>Email</th>
                                <th>Spam</th>
                                <th>Tipo</th>
                                <th>Redir</th>
                                <th>Adm</th>
                                <th>USO Mbytes</th>
                              </tr>
                            </thead>
                            <tbody>
                              {{range $k, $v := .list}}
                              <tr>
                                <td><div class='text-center'><i class='fa fa-edit fa-2x'></i></div></td>
                                <td>{{$v.Email}}</td>
                                <td>12->Retornar</td>
                                <td>user</td>
                                <td>0</td>
                                <td>6</td>
                                <td>{{$v.Quota/1024}}</td>
                              </tr>
                              {{end}}
                            </tbody>
                          </table>

**Comment by stef-k** [comment]
You need to create a template function that takes an int and returns the int/1024 as string, register it in beego and then call it in your template.

This is an example, it is **not tested** but you will get the idea

```go
// template function
func GetQuota(in int)(out string){
    result = in / 1024
   out, _ := strconv.Atoi(result) // or you can check for error
   return out
}

// register the function before Beego's main 
beego.AddFuncMap("quota",GetQuota)
```

in template:

```html
{range $k, $v := .list}} 
    {{ $.Quota | quota}}
{{end}}
```
