### ISSUE TITLE
可否使用beego做CLI程序？

### ISSUE THREAD

**Issue by askie** [astaxie/beego#1089]
用beego做命令行程序，使用参数驱动路由，不知道如何实现！
例如，命令行执行：
./beego -controller=abc -action=ccd -parms=a:1&b:2
会路由到controller=abc，action=ccd执行。
求赐教！

**Comment by astaxie** [comment]
这个我还没有想过呢，但是现在这个好像是不行，而且我觉得命令行的程序可能需要另外的设计吧，没有想过这样的命令行方式

**Comment by askie** [comment]
我感觉，只需要实现可以通过CLI实现目前的路由方式，就可以了。这样beego就可以通吃web开发和CLI开发了。

**Comment by askie** [comment]
另外设计没有必要。一套框架实现绝对完美！上层几乎不用动，只需要指定CLI的路由规则即可。

**Comment by astaxie** [comment]
这个实现倒是可以，但是我还没有想过这个问题

**Comment by lei-cao** [comment]
@askie Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
beego will focus on the http
