### ISSUE TITLE
beego api  postgres 错误 data type timestamp with time zone  not found 

### ISSUE THREAD

**Issue by toplinuxsir** [astaxie/beego#1098]
bee api myapi  -driver=postgres -conn=postgres://user:pass@122.5.13.203/db
create app folder: /Users/lhs/devs/gopath/src/smarterp
create conf: /Users/lhs/devs/gopath/src/smarterp/conf
create controllers: /Users/lhs/devs/gopath/src/smarterp/controllers
create docs: /Users/lhs/devs/gopath/src/smarterp/docs
create tests: /Users/lhs/devs/gopath/src/smarterp/tests
create conf app.conf: /Users/lhs/devs/gopath/src/smarterp/conf/app.conf
create main.go: /Users/lhs/devs/gopath/src/smarterp/main.go
2015/03/27 18:57:53 [INFO] Using 'postgres' as 'driver'
2015/03/27 18:57:53 [INFO] Using 'postgres://user:pass@122.5.13.203/db
' as 'conn'
2015/03/27 18:57:53 [INFO] Using '' as 'tables'
2015/03/27 18:57:53 [INFO] Analyzing database tables...
2015/03/27 18:59:03 [ERRO] data type (timestamp with time zone) not found

**Comment by lei-cao** [comment]
@toplinuxsir Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
