### ISSUE TITLE
自动路由的时候遇到的问题

### ISSUE THREAD

**Issue by xiaocongWang** [astaxie/beego#1099]
使用自动路由的时候遇到的问题，会出现访问不到link进网页的css文件的问题

**Comment by astaxie** [comment]
希望能够描述清楚你的问题，你这样的描述是对你自己的不负责

**Comment by xiaocongWang** [comment]
不好意思，新手小白    在main函数里面有beego.AutoRouter(&controllers.TopicController{})  beego.Router("/topic", &controllers.TopicController{}) 设置了自动路由，
func (this *TopicController) Get() {
	this.TplNames = "topic.html"
}  
func (this *TopicController) Add() {
	this.TplNames = "topic_add.html"
}

在controllers包里定义了这两个方法
topic_add.html 和topic.html  都link了同一个css文件 <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">

然后我在访问localhost:8080/topic的时候，RequestURL:http://localhost:8080/static/css/bootstrap.min.css可以寻找到.css     但是在访问localhost:8080/topic/add的时候，Request URL:http://localhost:8080/topic/static/css/bootstrap.min.css  这个路径就会是这样  就找不到这个css文件了   还请您解答一下   我是照着无闻的视屏写的

**Comment by ElvizLai** [comment]
css引用的问题，你引用的时候css可能使用了相对路径。类似于 ./css/bootstrap.min.css 改成 /static/css/bootstrap.min.css 试试

**Comment by astaxie** [comment]
静态文件：`http://localhost:8080/topic/static/css/bootstrap.min.css` 和 `http://localhost:8080/static/css/bootstrap.min.css` 是两个不一样的URL啊，静态文件只提供在`static`里面的路由，你的这个第一个静态地址`/topic`是你自己加的吗？还是你采用了相对路由地址，请检查一下你的html里面的设置

**Comment by xiaocongWang** [comment]
thank you  问题解决了   路径写错了 static/css/bootstrap.min.css   改成 /static/css/bootstrap.min.css  就对了
