### ISSUE TITLE
How to select module name in {{urlfor}} function inside template

### ISSUE THREAD

**Issue by JuandeParras** [astaxie/beego#1100]
Im working in a beego application with 2 modules, and has a controller with the same name in both modules. When I use {{urlfor}} in template the generated url is linking with the other module name. Im currently use beego 1.4.3

its posible select module name in urlfor function?

**Comment by astaxie** [comment]
urlfor try the `module.controller.method` as the params

**Comment by JuandeParras** [comment]
I try but it doesn't work, i think the problem is how i define modules.
My application folder structure is:
```
 /src
    /app
        modules
            /backend
                /controllers
                    /DashboardController
            /application
                /controllers
                    /DashboardController
```
The routes:
beego.Router("/application/dashboard", &application.DashboardController{}, "get:IndexAction")
beego.Router("/backend/dashboard", &backend.DashboardController{}, "get:IndexAction")

And the template code is:
`{{urlfor "backend.DashboardController.IndexAction"}}`

Actually this code doest render the url. But if i dont specify the module name, always render the url of the first route
`{{urlfor "DashboardController.IndexAction"}}`

Any sugestion?

**Comment by astaxie** [comment]
I just test in my localhost. it works well.

this is my router:

```
func init() {
	beego.Router("/", &controllers.MainController{})
	beego.Router("/application/dashboard", &application.DashboardController{}, "get:IndexAction")
	beego.Router("/backend/dashboard", &backend.DashboardController{}, "get:IndexAction")
}
```

here is my structure:

```
├── btest
├── conf
│   └── app.conf
├── controllers
│   ├── application
│   │   └── DashboardController.go
│   ├── backend
│   │   └── DashboardController.go
│   ├── default.go
│   └── error.go
├── main.go
├── models
│   └── user.go
├── routers
│   └── router.go
├── static
│   ├── css
│   ├── img
│   └── js
├── tests
│   └── default_test.go
└── views
    └── index.tpl
```
`{{urlfor "backend.DashboardController.IndexAction"}}`

get the `/backend/dashboard`

`{{urlfor "application.DashboardController.IndexAction"}}`

get the `/application/dashboard`

**Comment by JuandeParras** [comment]
This works like a charm!!!
I need to change the controllers folder structure like you to do the job.

Many thanks and good work ;)

**Comment by astaxie** [comment]
in your structure, you can try:

`{{urlfor "backend.controllers.DashboardController.IndexAction"}}`
