### ISSUE TITLE
使用自动化文档时提示 [ERRO] the model models.ZDTCustomer.Customer parser.ParseDir error 错误

### ISSUE THREAD

**Issue by doveq** [astaxie/beego#1108]
Hi~
    我在使用自动化文档时遇到错误提示 [ERRO] the model models.ZDTCustomer.Customer parser.ParseDir error 。请问是问题，如何解决？ 谢谢~

**Comment by qgymje** [comment]
我也遇到了

**Comment by lei-cao** [comment]
@doveq Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  can be close @doveq  is your issue solved?
