### ISSUE TITLE
Session保存自定义struct后读取出现 gob: name not registered for interface错误

### ISSUE THREAD

**Issue by cfanboy** [astaxie/beego#1110]
自定义Account如下：
type Account struct {
	Id                 bson.ObjectId `bson:"_id,omitempty" json:"id"`
	LoginName          string        `bson:"loginName" json:"loginName"`
	Password           string        `bson:"password" json:"password"`
	UserName           string        `bson:"userName" json:"userName"`
}

在controller中使用SetSession方法保存登录后的用户，第一次登录没问题，但登录后再次刷新界面或跳转到Login界面，就会出现错误：
[router.go:650] [E] gob: name not registered for interface: "*models.Account" 

清除浏览器端Cookie或删除Session目录中的内容后又可以正常登录

**Comment by astaxie** [comment]
恩，这是一个已知bug，而且目前无法优雅的解决，你可以通过这样的方式解决：

在你的main.go里面，init函数里面使用gob.Register你的自定义的struct

**Comment by cfanboy** [comment]
ok，已经这样注册了，多谢谢大 ^_^

**Comment by lei-cao** [comment]
@cfanboy Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closable

**Comment by JessonChan** [comment]
@astaxie can close this issue

**Comment by godblesshugh** [comment]
wonder if its ok:
when SetSession: convert STRUCT to JSON and save into session.
when GetSession: convert JSON to STRUCT.

**Comment by mytc** [comment]
Anyone can show me how to use gob in main? I am confused. 
I have similar error:

`gob: name not registered for interface: "time.Time"`

The documentation only mention register the gob in init in main, but I really don't know what to register. I didn't struct to store the session. 

Would be better if the documentation give more examples. It's been really hard for golang newbie like me to understand how does this beego work.

**Comment by astaxie** [comment]
@mytc what did you store in session?

**Comment by mytc** [comment]
@astaxie, there were two fields, `name` and `expire` which is both are string. 
I think the problem lays on the `expire` field. 

`this.SetSession("expiry", time.Now().Add(time.Minute*4))`

I thinks should parse the time, right?

**Comment by astaxie** [comment]
`time.Now().Add(time.Minute*4)` return `time.Time`, So actually you save this struct. If you want to save the struct, you need to use the gob to register. `gob. Register(time.Time{})`

**Comment by TeriMoni** [comment]
sessionprovider 改成内存形式就没有这个问题，文件形式会出现，能每次项目重启自动删除本地的session文件么

**Comment by moshuipan** [comment]
好像直接使用gob.Register(interface{})就可以注册所有的了:smile:

**Comment by yingyan003** [comment]
我用的redis存储session，在models下定义了一个session struct{},但并没有进行register注册（因为不需要进行插库操作），然后运行也报这个“gob: name not registered for interface: "*models.Session"”这个错误了。郁闷啊 @astaxie ，期待你们能快点解决这问题。
