### ISSUE TITLE
使用beego自动化文档的时候总是提示go install oplive: build output "docs" already exists and is a directory，咋整。

### ISSUE THREAD

**Issue by cyuxlif** [astaxie/beego#1111]

**Comment by astaxie** [comment]
放个截图上来，然后你运行的命令，你项目的结构

**Comment by yuyuyu101** [comment]
I met the same problem.

$ bee run docs
2015/06/09 17:42:24 [INFO] Uses 'docs' as 'appname'
2015/06/09 17:42:24 [INFO] Initializing watcher...
2015/06/09 17:42:24 [TRAC] Directory(/xxx/controllers)
2015/06/09 17:42:24 [TRAC] Directory(/xxx)
2015/06/09 17:42:24 [TRAC] Directory(/xxx/models)
2015/06/09 17:42:24 [TRAC] Directory(/xxx/routers)
2015/06/09 17:42:24 [TRAC] Directory(/xxx/tasks)
2015/06/09 17:42:24 [TRAC] Directory(/xxx/tests)
2015/06/09 17:42:24 [INFO] Start building...
go install xxx: build output "docs" already exists and is a directory
2015/06/09 17:42:25 [ERRO] ============== Build failed ===================


$ ls
conf		cpu-49442.pprof	main.go		routers		tests
controllers	docs		models		tasks		xxx

It seemed that we already have a fold named "docs" and "bee run docs" will try to compile a exec file named "docs", it will result in the conflicting name

**Comment by lei-cao** [comment]
你为什么要 `bee run docs` 呢

```
 bee run --help                                                                                                                                                                                                                                                       
usage: run [appname] [watchall] [-main=*.go] [-downdoc=true]  [-gendoc=true]
```

**Comment by yuyuyu101** [comment]
sorry, 我不是太熟悉go和beego，我只是follow了http://beego.me/docs/advantage/docs.md 这里的用法

**Comment by lei-cao** [comment]
lol, sorry, the document need to be improved :D 
Now you can use:
First time `bee run -downdoc=true -gendoc=true`  to download the `swagger` and generate the `doc`
And every time after changing the doc related comment, you can do `bee run --gendoc=true`

**Comment by yuyuyu101** [comment]
Thanks!

**Comment by lei-cao** [comment]
@cyuxlif Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable

**Comment by JessonChan** [comment]
@astaxie
