### ISSUE TITLE
beego的路由算法存在bug

### ISSUE THREAD

**Issue by mayf3** [astaxie/beego#1112]
我有两个路由地址：
/table/:table_id:int/information/:information_id:int/edit
/table/:table_id:int/information/create

InformationController里面使用注解路由，将上述两个路由地址路由到同一个函数上
在运行后发现
在/table/4/information/25/edit是可以访问到的
在/table/4/information/create显示是nomatch
我在查看源码后发现，在tree.go文件第337行（match函数）下输出正则表达式（在叶子上存着的），发现
（1）
/table/4/information/25/edit地址显示的是 
^([0-9]+)/([0-9]+)$
而参数是[4 25]，在经过path.Join之后变成4/25是可以通过正则表达式的
（2）
而/table/4/information/create地址显示的是 
^([0-9]+)/$
而参数是[4]，在经过path.Join之后变成4，（缺少了符号/），所以不能通过表达式

**Comment by astaxie** [comment]
你的是什么版本的beego？我好像本地测试没有发现这个问题

```
	beego.Router("/table/:table_id:int/information/:information_id:int/edit", &application.DashboardController{}, "get:IndexAction")
	beego.Router("/table/:table_id:int/information/create", &application.DashboardController{}, "get:IndexAction")
}
```

```
func (c *DashboardController) IndexAction() {
	beego.Info(c.Ctx.Input.Params)
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	c.TplNames = "index.tpl"
}
```

结果图如下：

![qq20150404-1](https://cloud.githubusercontent.com/assets/233907/6992023/5d250a42-dae8-11e4-911a-84abdf2ad22a.png)

**Comment by mayf3** [comment]
版本信息：
>bee 1.2.4
>beego 1.4.3
>go 1.4.2

我用的是注解路由，控制器文件controllers.go:
```
package controllers

import (
	"github.com/astaxie/beego"
)

type TableController struct {
	beego.Controller
}

// @router /create [get]
// @router /:table_id:int/edit [get]
func (c *TableController) Get() {
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	c.TplNames = "index.tpl"
}

type InformationController struct {
	beego.Controller
}

// @router /create [get]
// @router /:information_id:int/edit [get]
func (c *InformationController) Get() {
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	c.TplNames = "index.tpl"
}
```
路由文件router.go：
```
package routers

import (
	"github.com/astaxie/beego"

	"hello/controllers"
)

func init() {
	table := beego.NewNamespace("/table",
		beego.NSInclude(&controllers.TableController{}),
		beego.NSNamespace("/:table_id:int/information",
			beego.NSInclude(&controllers.InformationController{})))
	beego.AddNamespace(table)
}
```
执行情况就如我描述的一样
/table/4/edit
/table/create
都是没有问题的，而
/table/4/information/25/edit
/table/4/information/create
会出现后者访问不到

结果如图：
![2015-04-05-051724_1366x768_scrot_meitu_1](https://cloud.githubusercontent.com/assets/5518571/6992792/e5ac03e8-db10-11e4-927d-9a992ee0b4c5.jpg)

**Comment by astaxie** [comment]
恩，如果是注释路由确实不行，我还需要进一步查找愿意
