### ISSUE TITLE
不能使用闭包作为路由的响应了？

### ISSUE THREAD

**Issue by leetom** [astaxie/beego#1115]
在文档里看到这样的简单路由：

    beego.Get("/",func(ctx *context.Context){
         ctx.Output.Body([]byte("hello world"))
    })

但是我用这个编译通不过，`cannot use func literal (type func(*context.Context)) as type beego.ControllerInterface in argument to beego.Router:func(*context.Context) does not implement beego.ControllerInterface (missing CheckXsrfCookie method)`

go新手，不知道是不是文档过期了。

**Comment by astaxie** [comment]
可以这样使用的啊，http://godoc.org/github.com/astaxie/beego#Get

你的完整的路由是怎么样的？

**Comment by leetom** [comment]
package routers

    import (
        "quickstart/controllers"
        "github.com/astaxie/beego"
        "github.com/astaxie/beego/context"
    )

    func init() {
        beego.Router("/", &controllers.MainController{})

        beego.Router("/hello", func(ctx *context.Context){
            ctx.Output.Body([] byte("hello world"))
        })
    }

就是按照新手教程来的，自己尝试添加路由时就出问题了。

**Comment by astaxie** [comment]
你看看你添加的是beego.Router而不是beego.Get
