### ISSUE TITLE
beego路由设置/*.*时的一点小问题

### ISSUE THREAD

**Issue by zhangyuchen0411** [astaxie/beego#1121]
当设置路由为 `/*.*` 后，`/index.html` 和 `indexhtml` 都是可以匹配的，跟踪代码时发现在<https://github.com/astaxie/beego/blob/master/tree.go#L240> 是将 `*.*` 翻译成 `/([^.]+).(.+)` 的正则，第二个 '.' 换成 '\\.' 或许可以。

when the router is `/*.*`, `/index.html` and `indexhtml` both can be matched. When I was tracking code(<https://github.com/astaxie/beego/blob/master/tree.go#L240> ), I found `*.*` was translated into `/([^.]+).(.+)`, but I suggest `/([^.]+)\.(.+)`

**Comment by lei-cao** [comment]
@zhangyuchen0411

**Comment by JessonChan** [comment]
@astaxie i think it's not a bug.

**Comment by astaxie** [comment]
I think this is a bug. As user expect `*.*`  here  `.` is a fixed char
