### ISSUE TITLE
请问数据库Raw(sql).Values() 数据如何使用？谢谢

### ISSUE THREAD

**Issue by doveq** [astaxie/beego#1122]
在a函数查询数据库获取数据后，在b函数中怎么调用数据？谢谢

fun A ()  (*[]orm.Params, error) {
    var info []orm.Params    
    
    ... 省略 ...

    // 这里可以打印数据
    fmt.print(info[0]["name"]) 
    
    return &info
}

fun b() {
    data := A()
    
    // 这二种方式都取不数据，提示  invalid operation: data[0] (type *[]orm.Params does not support indexing)
    fmt.print(**data[0]["name"])
    fmt.print(*data[0]["name"])
    fmt.print(data[0]["name"]) 
}

**Comment by chinaestone** [comment]
fmt.print((*data)[0]["name"]) 这样就可以了

**Comment by lei-cao** [comment]
@doveq Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by JessonChan** [comment]
@doveq write like this 
`fmt.Print((*data)[0]["name"])`

@astaxie you can close this issue.
