### ISSUE TITLE
beego 应该如何做访问量统计？

### ISSUE THREAD

**Issue by shenyp09** [astaxie/beego#1123]
包括PV和UV，应当如何做？是否有相关的DEMO？

**Comment by yinheli** [comment]
这个和框架无关吧. 你可以选择使用 百度统计. 或者自建统计平台, 比如 piwik

**Comment by xtea** [comment]
如果想使用后台的访问量统计，可以使用toolbox里的 [statistics] ( http://beego.me/docs/module/toolbox.md#statistics)

**Comment by lei-cao** [comment]
@shenyp09 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by JessonChan** [comment]
@astaxie 
the issue is closable
