### ISSUE TITLE
redis session error : gob: name not registered for interface: "time.Time"

### ISSUE THREAD

**Issue by fengcen** [astaxie/beego#1126]
使用 redis session，每一次重启程序的时候都会 “Service Unavailable”，显示错误：gob: name not registered for interface: "time.Tine"，删除 浏览器的 session cookie 后正常，有什么解决方法？

**Comment by astaxie** [comment]
参考 https://github.com/astaxie/beego/issues/1110

**Comment by fengcen** [comment]
谢谢，已解决
