### ISSUE TITLE
beego如何更新部分字段

### ISSUE THREAD

**Issue by leiyinghao** [astaxie/beego#1130]
使用beego的orm更新单条数据库记录，如果只传入单个参数会将其他没传入的字段置空，文档上说可指定更新字段(http://beego.me/docs/mvc/model/object.md)·
```go
// 只更新 Name 
o.Update(&user, "Name") 
// 指定多个字段 
// o.Update(&user, "Field1", "Field2", ...) 
```
controller中通过 c.Ctx.Request.Body 获取的body是 
```javascript
{ 
"aa": "234234", 
"bb": "sdfg", 
"cc": "23423", 
"dd": "sss"
}
```
·
body是struct类型，无法转为json，
现在的问题是：如何获取到更新的字段 field1，field2 ，也就是说如何去获取 aa ，bb，dd 然后将提取的数组作为更新的特定字段
o.Update(&user, "aa", "bb", ...) ,传入的aa，bb等属性个数不是固定的

**Comment by JessonChan** [comment]
body是struct类型，无法转为json  为什么不可以？
先把问题说明一些吧？

**Comment by rubylab** [comment]
body := c.Ctx.Request.Body
fmt.Println("body type is : ", reflect.ValueOf(body).Kind())
用反射获取到的 body类型是  io.ReadCloser

**Comment by rubylab** [comment]
查看了orm 源码中  update 允许传入多个参数
``` 
// update model to database.
// cols set the columns those want to update.
func (o *orm) Update(md interface{}, cols ...string) (int64, error) {
	mi, ind := o.getMiInd(md, true)
	num, err := o.alias.DbBaser.Update(o.db, mi, ind, o.alias.TZ, cols)
	if err != nil {
		return num, err
	}
	return num, nil
}

```
后来找到了slice 不定参数，目前通过一段丑陋的代码解决了问题
```
         body := c.Ctx.Request.Body
        buf := new(bytes.Buffer)
	buf.ReadFrom(body)
	s := buf.String()
	json.Unmarshal([]byte(s), &v)	
	collec := make(map[string]interface{})
	e := json.Unmarshal([]byte(s), &collec)
	if e != nil {
		panic(e)
	}
	k := make([]string, len(collec))
	i := 0
	for s, _ := range collec {
		k[i] = s
		i++
	}
	fmt.Printf("%#v\n", k)
	fmt.Println("------------------------------")
	if err := models.UpdateUsReportsById(&v, k);  
         ……
```

**Comment by lei-cao** [comment]
@leiyinghao Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
