### ISSUE TITLE
[BUG]表名大小写问题

### ISSUE THREAD

**Issue by vincent3i** [astaxie/beego#1134]
首先感谢beego为golang开源做出的贡献

说说表名大小写的一个BUG
现状：
mysql开启大小写敏感，使用beego自身的orm框架时，如果表名不遵循驼峰式写法，在不指定tabllename方法的情况下，默认使用驼峰式写法，这点没问题，问题在于，如果指定了tabllename方法，里面返回一个大小写敏感的字符串，在model_utils.go (line 39)，会原样返回作为表名，但是在查询的时候，因为设定了大小写，直接在QueryTable方法传入string作为参数，但是在orm.go （line 399）会调用snakeString又转成驼峰式

question：
个人认为QueryTable对于直接传入string可以默认caller已经明确知道表名，没有必要在做转换了

**Comment by lei-cao** [comment]
@vincent3i Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
@vincent3i as we need to get the table from cache: `modelCache.get(name)`. And all the other we use the snakeString for table. So we need to keep consistence with that design.

**Comment by vincent3i** [comment]
I know your consideration about table cache in query performance, but when parameter - table name, is already assigned in model, caller must be very clear to know what purpose he/she want for table name, it may be more reasonable to checked if table name has been set in model, rather than transformed by snakestring directly.

**Comment by astaxie** [comment]
@vincent3i IMO, if you want to get the data throw QueryTable with defined tablename. you should pass struct while not the string
