### ISSUE TITLE
cache memory.go IsExist() 有Bug

### ISSUE THREAD

**Issue by yangweng** [astaxie/beego#1139]
原来的是
// check cache exist in memory.
func (bc *MemoryCache) IsExist(name string) bool {
	bc.lock.RLock()
	defer bc.lock.RUnlock()
	_, ok := bc.items[name]
	return ok
}
没有考虑过去去情况，我修改了一下,添加过去考虑
	v, ok := bc.items[name]
	if ok {
		return (time.Now().Unix() - v.Lastaccess.Unix()) < v.expired
	}
        return ok

**Comment by lei-cao** [comment]
@yangweng Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
