### ISSUE TITLE
Panic return http 200

### ISSUE THREAD

**Issue by bclermont** [astaxie/beego#1143]
my controller:

```
func (this *MyController) Get() {
	panic(fmt.Errorf("!"))
}
```
```
$ wget -q -O /dev/null -S http://127.0.0.1:8081/
  HTTP/1.1 200 OK
  Server: beegoServer:1.4.3
  Date: Tue, 05 May 2015 04:18:43 GMT
  Content-Length: 1804
  Content-Type: text/html; charset=utf-8
```

now I can't write reliable API client because I can't assume that ``200`` is really ok

**Comment by favadi** [comment]
I hit the same issue. Our application panic in the middle of execution but still returns `200`, so no one know about it for a nearly a week. My boss is really angry right now, I may get fired today.

:+1: please fix.

**Comment by hvnsweeting** [comment]
:+1:  this's hurt

**Comment by astaxie** [comment]
@favadi I am so sorry for that. :sob: let me check

**Comment by bclermont** [comment]
I tried to fix that myself, and I assumed that this ``SetStatus`` was doing it's job.

I was looking if something else, in an other function, was actually writing the http code before it reach that  line :(

**Comment by bclermont** [comment]
I confirm this is fixed, thanks

**Comment by hyhlinux** [comment]
hi @astaxie , i get the same quession. 
func recoverPanic(ctx *context.Context) {
	if err := recover(); err != nil {
		if err == ErrAbort {
			return
		}
		if !BConfig.RecoverPanic {
			panic(err)
		}
		if BConfig.EnableErrorsShow {
			if _, ok := ErrorMaps[fmt.Sprint(err)]; ok {
				exception(fmt.Sprint(err), ctx)
				return
			}
		}
		var stack string
		logs.Critical("the request url is ", ctx.Input.URL())
		logs.Critical("Handler crashed with error", err)
		for i := 1; ; i++ {
			_, file, line, ok := runtime.Caller(i)
			if !ok {
				break
			}
			logs.Critical(fmt.Sprintf("%s:%d", file, line))
			stack = stack + fmt.Sprintln(fmt.Sprintf("%s:%d", file, line))
		}
		if BConfig.RunMode == DEV && BConfig.EnableErrorsRender {
			showErr(err, ctx, stack)
		}
                  //what about prov mode???  i get 200!!
	}
}
