### ISSUE TITLE
现在beego 还有热升级的功能吗?

### ISSUE THREAD

**Issue by gloomyzerg** [astaxie/beego#1144]
看到作者两年前的blog 里面写了 beego的热升级  http://my.oschina.net/astaxie/blog/136364

但是在文档中没有找到 相关的说明
现在还有这个功能吗

**Comment by GaoJiasheng** [comment]
之前的热升级被谢大在1.3版本下掉了。不过最近谢大又搞了一版，目前已经推到develop分支了。亲测可用。谢大威武。

**Comment by lei-cao** [comment]
@gloomyzerg Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable?
