### ISSUE TITLE
Can not read config in test file

### ISSUE THREAD

**Issue by sicojuy** [astaxie/beego#1145]
app path: /foo/app
test file: /foo/app/tests/app_test.go
conf file: /foo/app/conf/app.conf

when exec "go test tests/app_test.go", the work path is "/foo/app/tests", so beego can not load config file.

**Comment by RealHacker** [comment]
Same problem here. And the config is initialized in init() of beego package, so there is no way to override the config file path.

**Comment by xtea** [comment]
You can init again in test file, like this :
```
	func init() {
		_, file, _, _ := runtime.Caller(1)
		// find app.conf path
		apppath, _ := filepath.Abs(filepath.Dir(filepath.Join(file, ".."+string(filepath.Separator))))
		beego.TestBeegoInit(apppath)
		// recall your init cunstom method 
	}
```

**Comment by sicojuy** [comment]
Oh, thank you very much, I was so careless that I was ignored these code in the default_test.go.

But it is not work in the module init function which I imported in test file.
Example:
foo/app/config/config.go
<pre>
var S string
func init() {
    S = beego.AppConfig.String("foo")
}
</pre>

foo/app/tests/app_test.go
<pre>
func TestMain(t *testing.T) {
        t.Log(config.S)
}
</pre>

It seem that the init function was called after the module imported.

**Comment by sicojuy** [comment]
Oh, thank you very much. I was so careless that I was ignored this code in the default_test.go.

But it is not worked in module init function which I imported in test file.
Example:
foo/app/config/config.go
<pre>
var S string
func init() {
    S = beego.AppConfig.String("Foo")
}
</pre>
foo/app/tests/app_test.go
<pre>
func TestMain(t *testing.T) {
    if config.S == "" {
        t.Error("Failed to read config")    
    }
}
</pre>

It seem that the init function was called after the config module imported.

**Comment by aholic** [comment]
+1

**Comment by aholic** [comment]
I set up a soft link to the conf directory to solve this problem
anyone have better solution please tell me, thx

**Comment by bakanis** [comment]
I create a bash script with content like this:

export BEEGO_APP_CONFIG_FILE="../conf/dev.conf"
goconvey ../test

**Comment by pjoe** [comment]
I have a setup package (under test) that i make sure to import first which does:
```go
func init() {
	_, file, _, _ := runtime.Caller(1)
	apppath, _ := filepath.Abs(filepath.Dir(filepath.Join(file, "../../")))
	beego.TestBeegoInit(apppath)
	// ...
}

```

**Comment by aholic** [comment]
@bakanis  thank you for your reply! but i still want to find a solution in go code
@pjoe   could you explain more about how to make a package being imported before others ? thank you.

**Comment by pjoe** [comment]
@aholic: simply put it's import statement first (or at least before any beego ones) :) If you use gofmt or similar make sure to leave empty lines around it, so it won't get reordered with other imports, e.g.
```go
package tests

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	_ "github.com/someuser/somerepo/tests/setup"

	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"

	"github.com/parnurzeal/gorequest"
	. "github.com/smartystreets/goconvey/convey"
)
```

**Comment by aholic** [comment]
@pjoe  I don't think we can rely on this. I've tried the following code
    
    //main.go
    package main
    import (
	    _ "pk2"

	    "pk1"
    )
    func main() {
	    pk1.Pk1()
    }

    //pk1/pk1.go
    package pk1
    import "fmt"
    func init() {
	    fmt.Println("pk1 init")
    }
    func Pk1() {
	    fmt.Println("Pk1")
    }

    //pk2/pk2.go
    package pk2
    import "fmt"
    func init() {
	    fmt.Println("pk2 init")
    }
    func Pk2() {
	    fmt.Println("Pk2")
    }

the output is as follows:

    pk1 init
    pk2 init
    Pk1

the package pk1 init first, not pk2.
I tried your code with beego, it doesn't work for me, too.

I've search the golang-nuts for "initialisation order", maybe you can have a look.
the link is [here](https://groups.google.com/forum/#!searchin/golang-nuts/initialisation$20order)

**Comment by pjoe** [comment]
@aholic: Hmm i guess you are right and that I have just been lucky or maybe unlucky :D

In my actual code I have a different path, so that may be the reason for different order.

**Comment by aholic** [comment]
:-)

**Comment by aholic** [comment]
@pjoe  :-)
