### ISSUE TITLE
httplib response aren't availble for diagnostic

### ISSUE THREAD

**Issue by bclermont** [astaxie/beego#1146]
I have an API server that reply 404 if a GET call refer to a non-existing resource (pretty standard HTTP stuff).

That API serve JSON, so I'm using httplib ``ToJson``, but it raise an error because the reply is standard 404 and not a fully formed json.

httplib API should let developer the ability to look at the response instance to act accordingly.

**Comment by bclermont** [comment]
I can do a pull request that does that, but it will break httplib API, is this something you can consider @astaxie ?

**Comment by astaxie** [comment]
@bclermont if the return response is not a json format, How can you handle it?

**Comment by bclermont** [comment]
```
switch response.StatusCode {
http.StatusUnauthorized: panic(fmt.Errorf("change user/pass API client")
http.StatusNotFound: blame_data()
http.StatusInternalServerError: blame_server()
http:StatusConflict: prompt_new_username()
}
```
