### ISSUE TITLE
how can i use other var in range in View ?

### ISSUE THREAD

**Issue by ivkean** [astaxie/beego#1149]
Dear beego team,
Ex: i have .s and var .tmp in View, i want to compare .tmp to elements in array s:
{{range $key, $val := .s}}
    {{if compare .tmp $val}}
       // code
    {{end}}
{{end}}

But error, Can you explain it ? Thank you

**Comment by astaxie** [comment]
could you provide the error information?

**Comment by ivkean** [comment]
this is my code:
{{range $k, $segment := .Segments}}
      <option {{if compare .Segment $segment.Id}}selected{{end}} value="{{$segment.Id}}">
           {{$segment.Name}}
      </option>
{{end}}

this is error:
project:template: service/quiz_choose_segment.tpl:47:49: executing "content" at <.Segment>: Segment is not a field of struct type models.Segment

**Comment by ivkean** [comment]
Can you show me how to solve this ?

**Comment by astaxie** [comment]
`c.Data["Segments"] = Segments`.  the Segments come from model? could you provide more information on this?

**Comment by ivkean** [comment]
first, i have model:
type Segment struct {
	Id        int
	Name      string
	CreatedAt time.Time `orm:"auto_now_add;type(datetime)"`
	UpdatedAt time.Time `orm:"auto_now_add;type(datetime)"`
	DeletedAt time.Time `orm:"auto_now_add;type(datetime)"`
}
 Then, i created in controller, i have array :
var Segments []models.Segment

/// i will put some data into this array
// blah blah

// then i put this Segments array into  View
c.Data["Segments"] = Segments

// i create SegmentId
c.Data["SegmentId"] = c.GetSession("SegmentId")

in View template:
{{range $k, $segment := .Segments}}
{{if compare .SegmentId $segment.Id}} selected {{end}}
{{end}}

That's all.

**Comment by ElvizLai** [comment]
I think you'd better check your code in "blah blah".
@astaxie  @ivkean ,I have encountered the problem: orm:"auto_now_add;type(datetime)" did not run as expected. The time can't updated when using advanced query: QuerySeter. That's maybe the key point.

**Comment by Hepri** [comment]
The problem is in template system. When you range over ".Segments" context switched to $segment variable for every loop, and template system try to find ".SegmentId" field inside $segment, but of course there is no such field. Fast approach is extend Segment model and add some "Selected" field, fill it within code and use in that way:

 ```
{{range $k, $segment := .Segments}}
{{if $segment.Selected}} selected {{end}}
{{end}}
```

**Comment by astaxie** [comment]
@Hepri yea, you are right:

another solution is use `$.SegmentId` meaning global variable


```
{{range $k, $segment := .Segments}}
{{if compare $.SegmentId $segment.Id}} selected {{end}}
{{end}}
```

**Comment by ivkean** [comment]
Thank @Hepri and @astaxie , i got it

**Comment by JessonChan** [comment]
@astaxie seems the issue has been solved

**Comment by lijinya** [comment]
tc.Data["Labels"] = strings.Split(topic.Labels, " "),此处tc.Data["Labels"] 是[]string，但是到了模板里面,.Labels却是一个组合好的字符串.请问这是怎么回事?
