### ISSUE TITLE
[ORM] Filter Crashes if Column doesn't exist

### ISSUE THREAD

**Issue by mewben** [astaxie/beego#1150]
This is okay:

```
num, err := qs.Filter("user_name__contains", "e").Count()
```

But, if the column does not exist like this:

```
num, err := qs.Filter("user_namekwqier__contains", "e").Count()
```

it crashes. `Handler crashed with error unknown field/column name 'user_namekwqier__contains'`.

Shouldn't this be handled by the err?

**Comment by bestplay** [comment]
+1

**Comment by flycash** [comment]
I think panic is a not bad choice. This error "column not exist" could be found during developing or testing.
