### ISSUE TITLE
ORM Insert Id autoincrement bug

### ISSUE THREAD

**Issue by ElvizLai** [astaxie/beego#1153]
model:
```
type User struct {
	Id       int64
	Username string `orm:"unique"`
}
```
for example:
```
user:=&User{Username:"elvizlai"}
o:=orm.NewOrm()
o.Insert(user)
```
It's OK, and the data in db looks like:
```
id    username
1    elvizlai
```
After that,I tried to insert the same user 3 times, it all throws `duplicate username err `(These are all as I expected).

Then I insert a new user with name `elvizlai1` that has not exist in db.The db became:
```
id    username
1    elvizlai
5    elvizlai1
```
I think the value of Id should be 2,but not 5(3 failure insertion has counted).

**Comment by francoishill** [comment]
This is not beego, this is probably your DB engine itsself, do you use MySql and InnoDB? Check here: http://stackoverflow.com/questions/2787910/why-does-mysql-autoincrement-increase-on-failed-inserts

**Comment by ElvizLai** [comment]
@francoishill Right, I use Mysql and InnoDB. I confirmed this is not a beegobug, I'll close this issue.
