### ISSUE TITLE
[ORM]使用mysql时出现数据库超出最大链接。

### ISSUE THREAD

**Issue by justay** [astaxie/beego#1154]
请问在orm中如何关闭一个现有的数据库链接？谢谢

**Comment by astaxie** [comment]
orm的连接没有关闭一说，因为采用的默认的database/sql里面的连接池

**Comment by lei-cao** [comment]
@justay Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie close?

**Comment by JessonChan** [comment]
@astaxie 
closable
