### ISSUE TITLE
ctx.Input.Params in the filter function only have :splat key

### ISSUE THREAD

**Issue by ziyel** [astaxie/beego#1155]
For the url pattern `/v1/user/:uname`, we want to get the `:uname` value in the `ctx.Input.Params` of the `filter` functions like below.

    func testFilter(ctx *context.Context) {
        beego.Info(ctx.Input.Params[":uname"])
    }

The feature is used for permission control in our project. The beego has not supported this.

**Comment by astaxie** [comment]
should fix in develop branch
