### ISSUE TITLE
NSBefore do not work with "/' routes

### ISSUE THREAD

**Issue by Hepri** [astaxie/beego#1160]
In case of index route inside namespace the NSBefore function do not work properly. So SomeController.Index function called without filtering
```
test_ns :=
    beego.NewNamespace("/test",
        beego.NSBefore(some_controller.FilterFunc),
        beego.NSRouter("/", &controllers.SomeController{}, "get:Index"),
    )
beego.AddNamespace(test_ns)
```

**Comment by astaxie** [comment]
@Hepri please try develop branch. I fix a bug sometimes ago in the router

**Comment by Hepri** [comment]
@astaxie still same thing

**Comment by benzsuankularb** [comment]
+1
