### ISSUE TITLE
how add custom fields to controller

### ISSUE THREAD

**Issue by haosdent** [astaxie/beego#1162]
hi, how could I add custom fields to controller

**Comment by astaxie** [comment]
```
type MyControlle struct{
    beego.Controller
    Custom string
}
```

**Comment by haosdent** [comment]
Thank you for your reply. But I want to use like this

```
type MyController struct{
    beego.Controller
    Custom string
}
func NewMyController(db models.MockDb) (*MyController) {
    instance := &MyController{}
    instance.db = db
    return instance
}
```

But seems router are use reflect method, could not pass params when construct Controllers. Could use IOC and inject depends to Controllers maybe import, it's helpful when write unit tests. So how to implement this?
