### ISSUE TITLE
How to serve several hosts

### ISSUE THREAD

**Issue by deadkrolik** [astaxie/beego#1164]
Hello

I use nginx as a frontend. I want to know how to make beego-application serve several hosts with different set of routes (and controllers). How can I config it manually or automatically, because I need to serve at least 3 hosts on the same IP? Should I write several applications or it's possible to do in one?

**Comment by astaxie** [comment]
There's 2 solution for this case:

1. writer several applications. **recommend**

    because it's easy to migrate and has less dependence.

2. Write one application, and use Filter to distinct the hosts use the different routers

**Comment by deadkrolik** [comment]
First way is not good-looking for me, because these three domains will have almost the same logic with different templates plus additional specific methods. But their purpose is very similar. And we will add new domains in future. It's like shopwindows with different kinds of goods.

About the second point. I've found only this way of modifing current controller/method:

```go
    var hostManager = func(context *context.Context) {

        if context.Request.Host == "www.domain.local" {
            context.Input.RunController = reflect.TypeOf(controllers.DomainController{})
            context.Input.RunMethod = "Mainpage"
        }

        if context.Request.Host == "www.super.local" {
            context.Input.RunController = reflect.TypeOf(controllers.SuperController{})
            context.Input.RunMethod = "Mainpage"
        }
    }

    beego.InsertFilter("/*", beego.BeforeRouter, hostManager)
```

But in this way I should create own routing function, because I can't replace built-in router. And it's a little tedious. Can I do this easier?

**Comment by ElvizLai** [comment]
Try using nginx to filter req.
