### ISSUE TITLE
custom command line tools

### ISSUE THREAD

**Issue by aacanakin** [astaxie/beego#1165]
Hello,
Is it currently possible or planned to make custom command line tools ?
The reason why I need this is to be able to load web configuration given environment.
For instance, a bee command could generate a sample command in `<project-folder>/commands` package using following;
```
bee <project> command:make HelloCommand
```
Wouldn't it be great to add this feature?
Are there any current solution to load configuration using environment flag?

**Comment by JessonChan** [comment]
@astaxie 
the issue should be closed and move to bee project issues.
