### ISSUE TITLE
Missing dchest/captcha license?

### ISSUE THREAD

**Issue by holys** [astaxie/beego#1170]
https://github.com/dchest/captcha/blob/master/LICENSE

>The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

**Comment by astaxie** [comment]
does beego use https://github.com/dchest/captcha?

**Comment by holys** [comment]
https://github.com/astaxie/beego/blob/master/utils/captcha/image.go
https://github.com/dchest/captcha/blob/master/image.go

even the comments are the same?

**Comment by astaxie** [comment]
@slene have a looks at this code. does it copyed from captcha? if that should add the licence in the top of code.

**Comment by slene** [comment]
@holys Sorry, I have add that LICENSE to repo. plz review.
