### ISSUE TITLE
apiauth插件在使用get方法时的一个bug

### ISSUE THREAD

**Issue by gloomyzerg** [astaxie/beego#1172]
```go
func Signature(appsecret, method string, params url.Values, RequestURI string) (result string)
```
最后一个参数是uri地址 
在获取signature时 因signature还未计算 所以传入的URI 不包含 signature
例如  /api/id=1
使用 get方法调用API  URI地址则为  /api/id=1&signature=xxx
验证则不能通过

还有 ctx.Output.SetStatus(403) 似乎应该改成 ctx.ResponseWriter.WriteHeader(403) 才能成功设置状态码

**Comment by lei-cao** [comment]
@gloomyzerg Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by JessonChan** [comment]
@astaxie 
it looks this is a closable issue.looks 
https://github.com/astaxie/beego/blob/develop/plugins/apiauth/apiauth.go#L139  
and 
https://github.com/astaxie/beego/blob/develop/plugins/apiauth/apiauth.go#L123
