### ISSUE TITLE
Handler crashed with error interface conversion: *beego.responseWriter is not http.Flusher: missing method Flush

### ISSUE THREAD

**Issue by wangzhezhe** [astaxie/beego#1173]
Hi , I'm trying to use the flush function in my controller funcion  like this   o.Ctx.ResponseWriter.(http.Flusher).Flush()  the error message is following:
Handler crashed with error interface conversion: *beego.responseWriter is not http.Flusher: missing method Flush 
Anyone could give me some suggestions ? Thank you!

**Comment by wangzhezhe** [comment]
How to use the function like flush which could send the stream info continuously to the client ?

**Comment by wangzhezhe** [comment]
It seems that ok after I add following code into the beego/router.go 

    func (w *responseWriter) Flush(){
             w.writer.(http.Flusher).Flush()
    }

**Comment by JessonChan** [comment]
@astaxie 
closable,because develop branch has  deprecated responseWriter struct
