### ISSUE TITLE
beego handler 自定义服务的问题

### ISSUE THREAD

**Issue by davylew** [astaxie/beego#1174]
wetalk代码结合socket.io(https://github.com/googollee/go-socket.io)

原本socket.io 会写入一个io = session id的cookie
但是我用beego handler作为入口以后，取得的cookie并没有这个session .
会覆盖成wetalk的cookie.
beego 的handler()会覆盖原本服务中的cookie.？

**Comment by astaxie** [comment]
不会

**Comment by lei-cao** [comment]
@davylew Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie can be closed

**Comment by JessonChan** [comment]
@astaxie  solved
