### ISSUE TITLE
get input field values in beego using global session

### ISSUE THREAD

**Issue by vijayks040** [astaxie/beego#1177]
Hi i am using beego framework for my web application. I want to display the loggedin username in landing page.
login.html

 <form action="/commonDashboard" name="loginForm" method="post" autocomplete="off" id="loginForm" >

            	<input type="text" placeholder="Enter your user name" id="userName" name="userName" taborder="1">

                <input type="password" class="qwerty" placeholder="Enter your password" id="userPassword" name="userPassword" taborder="2">

                <input type="button" value="Login" onclick="validatelogin();" taborder="3">

                <input type="button" value="Clear" onclick="resetForm();" taborder="3">

				<span class="forgot"><a href="#">forgot password ?</a></span>

            

                <span class="virtual"><a href="#" id="passwd" class="tooltip-tipsy" title="Click to open the virtual keyboard">Virtual Keyboard  

				<img  src="../../static/img/keyboard.svg" /></a>

				<div class="code ui-corner-all">

				<pre class="prettyprint lang-js">$('.qwerty:eq(0)')

					.keyboard({

					openOn : null,

					stayOpen : true,

					layout : 'qwerty'

					})

					.addTyping();

					$('#passwd').click(function(){

					var kb = $('.qwerty:eq(0)').getkeyboard();

					// close the keyboard if the keyboard is visible and the button is clicked a second time

					if ( kb.isOpen ) {kb.close();} else {

					kb.reveal();}});

				</pre>

				</div> 

				</span>

            </form>

controller is as follows

type LoginController struct {
	beego.Controller
}

func (c *LoginController) Post() {
	c.TplNames = "common.html"
	fmt.Println("this is dashboard")
	username := c.Input().Get("userName")
	password := c.Input().Get("userPassword")
	fmt.Println("username:" + " " + username)
	fmt.Println("password:" + " " + password)
	}

i am getting the input field values but i am not able to display it in landing page , may be because its local. Can any one have the solution for my problem.
I want to display the input field value in landing page.

**Comment by astaxie** [comment]
which is your landing page? `common.html`? if you want to show that value, you need to assign it to a variable. like `c.Data["username"] = username`. and then you can output the variable in that page

**Comment by vijayks040** [comment]
yup common.html is my landing page
