### ISSUE TITLE
使用orm原生SQL查询时，group by的参数无法正常生效

### ISSUE THREAD

**Issue by linjackson78** [astaxie/beego#1178]
当我使用以下语句时，能得到正确的结果，即maps的长度大于1：
`var maps []orm.Params`
`ormer.Raw("SELECT * FROM table GROUP BY column").Values(&maps)`

但是当我将其改成下面，一直无法得到正确的结果，即maps的长度始终等于1：
`ormer.Raw("SELECT * FROM table GROUP BY ?", "column").Values(&maps)`

**Comment by thomasli-x** [comment]
me too.
本来想追查下。
怀疑是database /  sql 的 go/src/database/sql/sql.go:920
func (db *DB) Query(query string, args ...interface{}) (*Rows, error) {} 
在 go-sql-driver 的实现过程中重载有问题。mark, hope anyone fix it ~~~

// for group by, go-sql-driver works.
<pre>
"database/sql"
_ "github.com/go-sql-driver/mysql"
db, err := sql.Open("mysql", dbuser+":"+dbpass+"@tcp("+dbip+":"+dbport+")/"+dbname+"?charset=utf8&loc=Asia%2FShanghai")
if err != nil {
	panic(err.Error())
}
defer db.Close()
queryStr := "select type from news group by type;"
rows, err := db.Query(queryStr)
if err != nil {
	panic(err.Error())
}
for rows.Next() {
	var x string
	err = rows.Scan(&x)   // WORKS OK.
	...
}
</pre>

**Comment by lei-cao** [comment]
@linjackson78 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
