### ISSUE TITLE
beego中每个工程，只能有一个配置文件么？

### ISSUE THREAD

**Issue by zhengshf** [astaxie/beego#1185]
beego中每个工程，只能有一个配置文件么，我看到beego代码中config.go存储配置文件的路径是个全局变量，难道不支持多个配置文件？如果支持多个配置文件，应该怎样配置呢？

**Comment by lei-cao** [comment]
@zhengshf Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by ysqi** [comment]
@zhengshf  Beego new version 1.6  will support include other config .

**Comment by astaxie** [comment]
beego 1.5 already support the feature

**Comment by astaxie** [comment]
appname = btest
include b.conf
