### ISSUE TITLE
How to forbid to create session tokens for some requests?

### ISSUE THREAD

**Issue by Hepri** [astaxie/beego#1186]
I have website and REST api for it, REST API is executed from mobile application and other services and for every api request beego generates new session token and store it into redis. I have almost unlimited cookie expired time, so it doesn't destroyed. From last 3 weeks I have about 9 millions keys and number is growing. How can I forbid beego to create session tokens for some requests?

**Comment by 29206394** [comment]
why not setting limited expired time for token?

**Comment by ysqi** [comment]
@Hepri  Beego use diffrent parameter to control cookie and session  expired time .  

call `session.NewManager('redis','config')` ,config like this : 
```JSON
{
  "cookieName":"gosessionid",
  "gclifetime":3600,
  "cookieLifeTime": 3600, 
   "ProviderConfig":"127.0.0.1:7070"
}
```
+ gclifetime (s):  session expired time in redis 
+ cookieLifeTime (s) :  sessionId expired time in cookie

> How can I forbid beego to create session tokens for some requests?

Maybe you need  change  expired time .  
+ gclifetime = 3600
+ cookieLifeTime = 0
