### ISSUE TITLE
How to redirect to login page on timeout in beego

### ISSUE THREAD

**Issue by vijayks040** [astaxie/beego#1187]
I had set time-out in my beego application for 5 second .But i am not able to find whether time out has occurred or not . I am setting time-out by this way 
globalSessions, _ = session.NewManager("memory", `{"cookieName":"gosessionid", "enableSetCookie,omitempty": true, "gclifetime":5, "maxLifetime": 5, "secure": false, "sessionIDHashFunc": "sha1", "sessionIDHashKey": "", "cookieLifeTime": 5, "providerConfig": ""}`)
	go globalSessions.GC()
	sess, _ := globalSessions.SessionStart(c.Ctx.ResponseWriter, c.Ctx.Request)
Can any one help me to redirect to login page after session time-out has happened

**Comment by Hepri** [comment]
As I understand, when you do request first time, beego creates some session token and store it in cookies with expired calculated using cookieLifeTime. When cookie is expired browser will not send it with next request, so beego will generate new token.

The idea is match some information like "authorized" with token.

**Comment by vijayks040** [comment]
@Hepri , thank you for answering.... great

**Comment by ysqi** [comment]
@astaxie  close it ?
