### ISSUE TITLE
prod模式下，LOG不记录PANIC，谢大处理下，。谢谢

### ISSUE THREAD

**Issue by bbs3723216** [astaxie/beego#1191]
prod模式下，LOG不记录PANIC，谢大处理下，。谢谢

**Comment by astaxie** [comment]
fix https://github.com/astaxie/beego/commit/364cacf

**Comment by lei-cao** [comment]
@bbs3723216 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie can be closed
