### ISSUE TITLE
Changing httpport in app.conf breaks Swagger docs

### ISSUE THREAD

**Issue by orospakr** [astaxie/beego#1195]
If you look at `./swagger/swagger-1/index.html`, you'll find that the `url:` parameter to the SwaggerUi object is still getting passed `http://localhost:8080` even if you've changed your app's port in `app.conf`.  Seems like 8080 is hardcoded somewhere?  I forced regeneration of the entire swagger directory, to no avail.  This issue can manifest as a CORS issue if you have another service running on 8080.  

Workaround is to manually change it in the green bar when visiting the Swagger pages.

**Comment by astaxie** [comment]
beego1.7 use swagger2.0
