### ISSUE TITLE
Beego: how to create and destroy user-cache in beego golang

### ISSUE THREAD

**Issue by vijayks040** [astaxie/beego#1196]
i have an Beego application which has an global session object created in following way

    var globalSessions *session.Manager
    globalSessions, _ = session.NewManager("memory", `{"cookieName":"gosessionid", "enableSetCookie,omitempty": true, "gclifetime":5, "maxLifetime": 5, "secure": false, "sessionIDHashFunc": "sha1", "sessionIDHashKey": "", "cookieLifeTime": 5, "providerConfig": ""}`)
    	go globalSessions.GC()
    	sess, _ := globalSessions.SessionStart(c.Ctx.ResponseWriter, c.Ctx.Request)
    	defer sess.SessionRelease(c.Ctx.ResponseWriter)

now using this session how to create cache.And upon pressing of logout button i want cache to get cleared.

**Comment by JessonChan** [comment]
http://beego.me/docs/module/session.md  
have a look at the method `Delete(key interface{}) error`

**Comment by ysqi** [comment]
@vijayks040  You can start session after user login , destory session after user logout. 

e.g:

```Go

func (m *MainController) Login() {

	// Save user info after user login.
	m.SetSession("name", "ysqi")
	m.SetSession("email", "devysq@gmail.com")
}

func (m *MainController) Logout() {

	// Destory Session after user logout.
	m.DestroySession()
}
```

If you only use beego session model.
e.g: 
```Go
func login(w http.ResponseWriter, r *http.Request) {
    sess, _ := globalSessions.SessionStart(w, r)
    defer sess.SessionRelease(w)
    username := sess.Get("username")
    if r.Method == "GET" {
        t, _ := template.ParseFiles("login.gtpl")
        t.Execute(w, nil)
    } else {
        sess.Set("username", r.Form["username"])
    }
} 
func logout(w http.ResponseWriter, r *http.Request) {
    sess, _ := globalSessions.SessionStart(w, r)
    defer sess.SessionRelease(w)
    sess.SessionDestroy(w,r)
}

**Comment by JessonChan** [comment]
@ysqi GREAT

@astaxie

**Comment by 3xxx** [comment]
这段代码已经不适合beego1.6.1了，应该是怎样写退出啊？
