### ISSUE TITLE
怎么为https证书配置密码

### ISSUE THREAD

**Issue by ckeyer** [astaxie/beego#1200]
beego文档上只有两个文件的配置项, 没有密码的配置项,我应该在哪里导入密码?

**Comment by astaxie** [comment]
不清楚你说的配置密码是什么

**Comment by ElvizLai** [comment]
@astaxie @ckeyer 这个问题我以前查过，结果是go暂时还不支持这种方式。需要用解密后的密钥。

**Comment by ckeyer** [comment]
@ElvizLai  具体应该怎么解密呢

**Comment by ElvizLai** [comment]
openssl rsa -in server.key -out server.key.unsecure   然后会提示你输入密码，以后用解密的这个文件即可。

**Comment by ckeyer** [comment]
@astaxie @ElvizLai  谢谢,搞定
