### ISSUE TITLE
The behavior of the implements of Cache.Get is inconsistent

### ISSUE THREAD

**Issue by zieckey** [astaxie/beego#1203]
Redis.Get return interface{} which holds **[]byte**
Memcache.Get return interface{} which holds **string**

**Comment by astaxie** [comment]
because redis we can use `redis.Bool` `redis. Bytes` to return the correct values. but memcache driver has no ability to do that.

```
exists, _ := redis.Bool(c.Do("EXISTS", "foo"))
fmt.Printf("%#v\n", exists)

n, _ = redis.Int(c.Do("INCR", "k1"))
fmt.Printf("%#v\n", n)

ints, _ := redis.Ints(c.Do("SMEMBERS", "set_with_integers"))
fmt.Printf("%#v\n", ints)
```
