### ISSUE TITLE
Cannot return JSON with non-200 status code

### ISSUE THREAD

**Issue by natemara** [astaxie/beego#1208]
When the status code is explicitly set, the `Content-Type` header is automatically change to `text/plain`. I would like the ability to send back JSON data for API consistency.

    func (u *UserController) Post() {
        u.Ctx.ResponseWriter.WriteHeader(500)
        u.Data["json"] = map[string]string{"error": "A user with that username already exists"}
        fmt.Println(err)
        u.ServeJson()
    }

The response looks correct at first glance, it is formatted as a JSON object, but the `Content-Type` header is set to `text/plain`, limiting its ability to be used correctly.

**Comment by astaxie** [comment]
```
func (u *UserController) GetAll() {
	users := models.GetAllUsers()
	u.Ctx.Output.SetStatus(300)
	u.Data["json"] = users
	u.ServeJson()
}
```

![qq20150613-1](https://cloud.githubusercontent.com/assets/233907/8142691/359c6fe0-11b8-11e5-88f4-1bbdd58cbb3c.png)

**Comment by natemara** [comment]
Thank you. What is the purpose of the `Controller.Ctx.ResponseWriter.WriteHeader` function if the `Controller.Ctx.Output.SetStatus` works with no side effects?

**Comment by astaxie** [comment]
`Controller.Ctx.ResponseWriter.WriteHeader` will directly write to the client,

while `Controller.Ctx.Output.SetStatus` will cache the status until output the content

**Comment by natemara** [comment]
Thanks
