### ISSUE TITLE
静态文件加载出错，路径对的，但是提示找不到文件！

### ISSUE THREAD

**Issue by qtzheng** [astaxie/beego#1214]
&lt;link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap-theme.mini.css">
	&lt;link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.mini.css">
	&lt;script src="/static/bootstrap/js/bootstrap.min.js" charset="utf-8" async defer></script>
js文件能找到，但是css文件不能找到
出错位置：staticfile.go： 61行

**Comment by astaxie** [comment]
报什么错？

**Comment by qtzheng** [comment]
没有找到匹配的文件或路径

**Comment by astaxie** [comment]
需要你完整的错误信息

**Comment by qtzheng** [comment]
[staticfile.go:61] [W] GetFileAttributesEx \static\bootstrap\css\bootstrap.min.css:The system cannot find the file specified
[staticfile.go:61] [W] GetFileAttributesEx \static\bootstrap\css\bootstrap-theme.min.css:The system cannot find the file specified
这是我在公司电脑上运行的错误，不过环境是win7的

**Comment by astaxie** [comment]
恩，这个之前也有人遇到过，GetFileAttributesEx这个问题我需要深入的追逐一下。看上去像是Go内部的issue

**Comment by astaxie** [comment]
你在win7和Ubuntu下面都遇到这个问题吗？能提供一下你的静态文件打包吗？这样我就可以测试的更详细，我之前没有遇到过这个问题。我现在怀疑是权限设置或者是隐藏文件之类的设置引起的

**Comment by qtzheng** [comment]
静态文件是从bootstarp中文网上下载的，整个项目是用bee 工具创建的

**Comment by astaxie** [comment]
@qtzheng 你更新到最新版本的beego，把出错日志打印出来

**Comment by qtzheng** [comment]
[staticfile.go:61] [W] Can't find the file:static/bootstrap/css/bootstrap.mini.css  GetFileAttributesEx /static/bootstrap/css/bootstrap-theme.min.css:The system cannot find the file specified

**Comment by astaxie** [comment]
这个GetFileAttributesEx 是系统级别的错误，我也没有想法

**Comment by astaxie** [comment]
bootstrap.mini.css 你是不是写错了，应该是bootstrap.min.css

**Comment by qtzheng** [comment]
好大一个乌龙~~~，真是不好意思！
