### ISSUE TITLE
會話cookie

### ISSUE THREAD

**Issue by achatur** [astaxie/beego#1216]
會話cookie無法正常工作。該NewManger結構配置值是不正確的。

**Comment by astaxie** [comment]
无法理解你所描述的时期

**Comment by achatur** [comment]
https://translate.google.com/#auto/zh-TW/Hello%2C%20there's%20a%20bit%20of%20a%20language%20barrier%20here.%20Sorry%20for%20the%20bad%20chinese.%20The%20time%20out%20value%20for%20cookies%20do%20not%20work.%0ADoesn't%20matter%20how%20I%20set%20it%2C%20I%20get%20max%205%20minutes%20cookie%20sessions.%20Can%20you%20give%20some%20advice%20on%20how%20to%20make%20this%20work%3F%20%20I'm%20using%20the%20following%20structure%20for%20config%20file%3A%0A%0A%7B%22EnableSetCookie%22%3Atrue%2C%20%22Secure%22%3Atrue%2C%20%22CookieLifetime%22%3A604800%2C%20%22CookieName%22%3A%22chomp_sessionid%22%2C%22Gclifetime%22%3A604800%2C%22Maxlifetime%22%3A604800%2C%22ProviderConfig%22%3A%22root%40tcp(172.16.0.108%3A3306)%2Fdb_to_use%22%7D.%0A%0ADoc%20says%20gclifetime%2C%20however%20looking%20at%20the%20code%2C%20you're%20using%20'CookieLifeTime'%20on%20line%20152%3A%20https%3A%2F%2Fgithub.com%2Fastaxie%2Fbeego%2Fblob%2Fmaster%2Fsession%2Fsession.go%0A%0AAny%20help%20is%20good.%20%20Thanks.

**Comment by astaxie** [comment]
@achatur are you use beego or the separate session package?

**Comment by achatur** [comment]
separate sessions package

**Comment by achatur** [comment]
to be sure, I'm using the right package:

"github.com/astaxie/beego/session"

So I'm using the newest version of the beego/sessions

**Comment by achatur** [comment]
it looks like the DB entry gets set to 5 minutes, while the cookie may get set properly.  The "session_expiry" filed in the db table that gets created is always 5 minutes from current time in epoch time.

**Comment by achatur** [comment]
This was really strange.  I put some print statements in beego/sessions and saved the file.  It got forced to recompile.  And now sessions are working.  Cookie max-age value gets set.

One thing that doesn't work is the session update.  Meaning if I make a call using the cookie, it doesn't reset the timer from that moment.  Is that by design?  I thought I had read the value gets updated whenever you make a call using the cookie.  Is this not true?  If not, is this something that was considered?

**Comment by lei-cao** [comment]
@achatur Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
