### ISSUE TITLE
部分日志出现log输出无法显示所在文件及行号，而显示log.go

### ISSUE THREAD

**Issue by fatedier** [astaxie/beego#1217]
![11](https://cloud.githubusercontent.com/assets/7346661/8152702/3c1a67ae-1353-11e5-84a0-8ad20ae3d9e6.jpg)

有部分日志会出现这种情况。

**Comment by ElvizLai** [comment]
@fatedier @astaxie  这个问题是因为将log封装到了一个package中，在别的func调用这个package时，会输出log在改package种的行号，而不是调用func的行号。

**Comment by astaxie** [comment]
恩，这个我这两天改进一下

**Comment by fatedier** [comment]
谢谢，那请问目前有什么好的解决方案吗？

**Comment by fatedier** [comment]
@astaxie 看了下代码，好像是因为我用的 BeeLogger的 Warn和Info函数，会再调一次Warning和Informational函数，这样的话有的深度是2层，有的是3层。虽然说1.5.0里会移除，不过考虑到兼容性的问题，最好和其他的log函数统一一下吧。

**Comment by astaxie** [comment]
我打算1.5版本里面继续保持这个短名字的log，https://github.com/astaxie/beego/commit/817650aa3341cf9ce21fa9cc416c6c9cf99118e9

**Comment by fatedier** [comment]
OK，这样最好了:-)
