### ISSUE TITLE
httplib debug in dev branch now can not print

### ISSUE THREAD

**Issue by ElvizLai** [astaxie/beego#1218]
Setting httplib with debug mode now can not print body. There should be adding a log in 
```
if b.setting.ShowDebug {
		dump, err := httputil.DumpRequest(b.req, b.setting.DumpBody)
		if err != nil {
			log.Println(err.Error())
		}
		b.dump = dump
	}
```

**Comment by astaxie** [comment]
as httplib is a common lib, so if we output the body directly. that's will lose the scalability. So I just move the output to the b.dump.

you can get the body information from `DumpRequest`

**Comment by ElvizLai** [comment]
tks
