### ISSUE TITLE
Cannot set static route

### ISSUE THREAD

**Issue by dariusc93** [astaxie/beego#1219]
In frameworks such as martini, it allows you to define where your static assets are at so that when you go to `http://example.com/path/to/asset` you will have access to it, however in beego, whenever I attempt to remove the static route and change it by doing

```
		beego.DelStaticPath("/static")
		beego.SetStaticPath("/", "static")
```

It would not allow it. The code would work just fine, but it would treat the directory as if it doesnt exist when trying to access assets. Any possible workaround for this without having to hack into beego itself so any visit of /* would load the static files located in the folder "static"?

**Comment by astaxie** [comment]
yea, if you set the static as `/`, so when you visit `/*` it will treat these as static path. so if it can't find the file from `/static`.
 
IMO, if you want to remove the static, you need to set the specified path：

```
beego.SetStaticPath("/js", "static/js")
beego.SetStaticPath("/css", "static/css")
beego.SetStaticPath("/fonts", "static/fonts")
```

**Comment by dariusc93** [comment]
Hmm.. Never thought of it that way. I guess I could do it that way too, and probably have some of the other files like robot.txt favicon as a get route. I just thought there was a simple way but maybe when I get time I will look at the beego code closely and get everything to play nicely. Thanks

**Comment by astaxie** [comment]
robot.txt and favicon.ico you can put into the static folder. beego will handle that files

**Comment by ltt1987** [comment]
I just added a sub folder to store the static files which I want display under the / path. 
```
files, _ := ioutil.ReadDir("./static/url_root_files")
for _, f := range files {
	beego.SetStaticPath("/"+f.Name(), "static/url_root_files/"+f.Name())
}
```

**Comment by astaxie** [comment]
it fixed in develop branch
