### ISSUE TITLE
Registering sqlite database with beego

### ISSUE THREAD

**Issue by natemara** [astaxie/beego#1222]
I'm trying to setup my beego app with a sqlite database for development purposes. In my `main.go` file, I have the following `init` function

    func init() {
        orm.RegisterDriver("sqlite3", orm.DR_Sqlite)
        orm.RegisterDataBase("default", "sqlite3", "file:data.db")
    }

This must be swallowing an error somewhere, because when I try to run the app, I get the error 

    must have one register DataBase alias named `default`

What's the problem? Do I need to provide more info?

**Comment by astaxie** [comment]
```
func init() {
    orm.RegisterDriver("sqlite3", orm.DR_Sqlite)
    err:=orm.RegisterDataBase("default", "sqlite3", "file:data.db")
    if err!=nil{
    panic(err)
   }
}
```

**Comment by natemara** [comment]
I am still getting the same error with that `init` function in my `main.go`.

**Comment by natemara** [comment]
It was a problem with import order. Since `init

**Comment by natemara** [comment]
it was a problem with the import order. Since `init` is not called until all imports, I had to do something like this:

```
import (
    "post_db"
    "models"
    "controllers"
    "pre_db"
)
```

**Comment by eoinahern** [comment]
cant get sqlite working with beego either. not sure exactly what the last comment means?

**Comment by thanos** [comment]
use orm.DRSqlite and not orm.DR_Sqlite
