### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by Hepri** [astaxie/beego#1225]
Latest master version

I have a router kind of

    beego.NSNamespace("/api",
        beego.NSNamespace("/web",
            beego.NSNamespace("/drivers",
                    beego.NSRouter("/", &controllers_web.DriverController{}, "get:GetDrivers"),
                    beego.NSRouter("/:id([0-9]+)/enable", &controllers_web.DriverController{}, "*:EnableDriver"),
                    beego.NSRouter("/:id([0-9]+)/disable", &controllers_web.DriverController{}, "*:DisableDriver"),
                ),

When I call /api/web/drivers/1305/disable everything is fine
But when I call /api/web/drivers, I receive 

    the request url is  /api/web/drivers
    Handler crashed with error assignment to entry in nil map
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:401
    /usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:387
    /usr/local/Cellar/go/1.4/libexec/src/runtime/hashmap.go:378
    /.../go/src/github.com/astaxie/beego/router.go:621
    /.../go/src/github.com/astaxie/beego/router.go:718
    /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1703
    /usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1204
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232

Btw, also I have global filter

    beego.InsertFilter("/api/web/*", beego.BeforeExec, controllers_web.FilterApiUser, false)

**Comment by oiooj** [comment]
Already fixed the issue ,  see   https://github.com/astaxie/beego/pull/1227

**Comment by JessonChan** [comment]
@astaxie 
closable
