### ISSUE TITLE
Beego API 文档

### ISSUE THREAD

**Issue by MrXiaoZ** [astaxie/beego#1226]
谢大，您好：
    感觉Beego 的 API部分，http://beego.me/docs/advantage/docs.md 这里的文档写的略显粗糙。最好能加上项目实例，那就更好了，哈哈。望能有所改进！

**Comment by lei-cao** [comment]
@MrXiaoZ Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie should be improved soon. close?
