### ISSUE TITLE
Gzip compression level 

### ISSUE THREAD

**Issue by mlgd** [astaxie/beego#1230]
Add property in config to set Gzip compression level

**Comment by JessonChan** [comment]
thank you for the issue.
we have a plan to support this after the beego1.6 release.

**Comment by mlgd** [comment]
What's about gzip compression level in version 1.6.x ?

**Comment by JessonChan** [comment]
@mlgd maybe 1.6.3

**Comment by JessonChan** [comment]
@mlgd I have add compression level future https://github.com/astaxie/beego/pull/1808
I would appreaciate hearing your thoughts on this.
