### ISSUE TITLE
[Grace Bug]更新到1.5版本后用grace发现一个runtime error

### ISSUE THREAD

**Issue by GaoJiasheng** [astaxie/beego#1232]
谢大，如题，
更新到1.5版本后，使用grace发现没问题，但是一压测就发现这个问题，详细错误栈如下：

panic: sync: negative WaitGroup counter

goroutine 14 [running]:
sync.(*WaitGroup).Add(0xc208296688, 0xffffffffffffffff)
	/home/work/.tools/go/src/sync/waitgroup.go:67 +0x96
sync.(*WaitGroup).Done(0xc208296688)
	/home/work/.tools/go/src/sync/waitgroup.go:85 +0x31
github.com/astaxie/beego/grace.graceConn.Close(0x7fc7c6eaf530, 0xc20829e140, 0xc208296660, 0x0, 0x0)
	/home/work/gopath/src/github.com/astaxie/beego/grace/conn.go:11 +0x46
github.com/astaxie/beego/grace.(*graceConn).Close(0xc2082e2c20, 0x0, 0x0)
	<autogenerated>:22 +0xb3
net/http.(*conn).close(0xc208040fa0)
	/home/work/.tools/go/src/net/http/server.go:1071 +0x50
net/http.func·011()
	/home/work/.tools/go/src/net/http/server.go:1134 +0x27b
net/http.(*conn).serve(0xc208040fa0)
	/home/work/.tools/go/src/net/http/server.go:1217 +0x809
created by net/http.(*Server).Serve
	/home/work/.tools/go/src/net/http/server.go:1751 +0x35e

goroutine 1 [chan receive]:
github.com/astaxie/beego.(*App).Run(0xc20800a780)
	/home/work/gopath/src/github.com/astaxie/beego/app.go:171 +0x363
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/home/work/gopath/src/github.com/astaxie/beego/beego.go:277 +0x17c
main.main()
	/home/work/gopath/src/norns/main.go:11 +0x3f

goroutine 5 [syscall]:
os/signal.loop()
	/home/work/.tools/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/work/.tools/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208288000)
	/home/work/.tools/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/home/work/.tools/go/src/database/sql/sql.go:452 +0x31c

goroutine 7 [chan receive]:
github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc2080b6990)
	/home/work/gopath/src/github.com/astaxie/beego/cache/memory.go:211 +0x6f
created by github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
	/home/work/gopath/src/github.com/astaxie/beego/cache/memory.go:201 +0x399

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc20831f640, 0x72, 0x0, 0x0)
	/home/work/.tools/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20831f640, 0x0, 0x0)
	/home/work/.tools/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20831f5e0, 0x0, 0x7fc7c6ea8cc8, 0xc208295d28)
	/home/work/.tools/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20829e130, 0x7fc7c6eb4990, 0x0, 0x0)
	/home/work/.tools/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/astaxie/beego/grace.(*graceListener).Accept(0xc2083316b0, 0x0, 0x0, 0x0, 0x0)
	/home/work/gopath/src/github.com/astaxie/beego/grace/listener.go:32 +0x83
net/http.(*Server).Serve(0xc20804e0c0, 0x7fc7c6eb49c8, 0xc2083316b0, 0x0, 0x0)
	/home/work/.tools/go/src/net/http/server.go:1728 +0x92
github.com/astaxie/beego/grace.(*graceServer).Serve(0xc208296660, 0x0, 0x0)
	/home/work/gopath/src/github.com/astaxie/beego/grace/server.go:35 +0x62
github.com/astaxie/beego/grace.(*graceServer).ListenAndServe(0xc208296660, 0x0, 0x0)
	/home/work/gopath/src/github.com/astaxie/beego/grace/server.go:74 +0x4e4
github.com/astaxie/beego.func·003()
	/home/work/gopath/src/github.com/astaxie/beego/app.go:109 +0xf8
created by github.com/astaxie/beego.(*App).Run
	/home/work/gopath/src/github.com/astaxie/beego/app.go:115 +0x95c

goroutine 12 [chan receive]:
github.com/astaxie/beego/grace.(*graceServer).handleSignals(0xc208296660)
	/home/work/gopath/src/github.com/astaxie/beego/grace/server.go:172 +0x266
created by github.com/astaxie/beego/grace.(*graceServer).ListenAndServe
	/home/work/gopath/src/github.com/astaxie/beego/grace/server.go:51 +0x9e

goroutine 13 [chan receive]:
github.com/astaxie/beego/grace.func·001()
	/home/work/gopath/src/github.com/astaxie/beego/grace/listener.go:24 +0x5b
created by github.com/astaxie/beego/grace.newGraceListener
	/home/work/gopath/src/github.com/astaxie/beego/grace/listener.go:27 +0x16e

**Comment by lei-cao** [comment]
@GaoJiasheng Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie solved ?

**Comment by astaxie** [comment]
see #1333
