### ISSUE TITLE
Better Hooks

### ISSUE THREAD

**Issue by dariusc93** [astaxie/beego#1233]
I feel that Beego should have better hooks for middleware to allow more of a fluid implementation of various of things, such as templates. For example, `beego-pongo2` is a "middleware" to implement pongo2 into beego, however the way it is used is pretty annoying because you have to call `pongo2.Render` function within every function when youre rendering the page as well as the context which will be used on the template as regards to data, while you do not have too with the template system beego is using (even though it is base on what is built into golang). Almost like how you can develop your own drivers for sessions or caching, there should be something to do the same for something as this. Any suggestions?

**Comment by JessonChan** [comment]
@astaxie

**Comment by astaxie** [comment]
working on the interface for viewer in next version
