### ISSUE TITLE
关于json解析问题，求指教

### ISSUE THREAD

**Issue by oopp1990** [astaxie/beego#1235]
Add   time.Time `orm:"auto_now_add;type(time)" json:"add"`
	End   time.Time `orm:"type(time)" json:"end"`

这是我的moudel里面某个实体的字段， 

返回：	this.Data[JSON] = data
	        this.ServeJson()

现在输出：       "add": "2015-06-30T08:00:00+08:00",
                         "end": "2015-08-30T08:00:00+08:00"

我想要的输出格式：         "add": "毫秒时间戳",
                                         "end": "毫秒时间戳"
请问我该如何才能做到?

**Comment by ElvizLai** [comment]
与beego无关的问题建议不要在这边发issue。
两种方案：
1、在输出前对data进行处理，将其转换为ms
2、输出到页面后，自己添加beego函数来将time转换为ms
