### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vefaliahmet** [astaxie/beego#1236]
I am getting this error when after update user;

at line :35

controllers/user.go
![](http://i.imgur.com/y82NyvJ.png)

![](http://i.imgur.com/gsS4X0m.png)

models/user.go
![](http://i.imgur.com/vmz6jr0.png)

**Comment by JessonChan** [comment]
not enough information.
@astaxie may be you can close it.

**Comment by astaxie** [comment]
@vefaliahmet it looks you set a DebugLog and can't find that log
