### ISSUE TITLE
Save INI config file don't work

### ISSUE THREAD

**Issue by mlgd** [astaxie/beego#1239]
You have added a setting with RunMode section but it don't work for INI config file.

You need to rollback your modifications. Example in Set() function :
func (b *beegoAppConfig) Set(key, val string) error {
	err := b.innerConfig.Set(RunMode+"::"+key, val)
	if err == nil {
		return err
	}
	return b.innerConfig.Set(key, val)
}

**Comment by JessonChan** [comment]
@astaxie 
you can close this issue
