### ISSUE TITLE
Auto API document didn't work

### ISSUE THREAD

**Issue by simpleton** [astaxie/beego#1240]
Access /docs return 404 when enable document generate.

**Comment by simpleton** [comment]
I have found why it didn't work for me.
```go
beego.InsertFilter("*", beego.BeforeRouter, func(ctx *context.Context) {
        ctx.Output.Header("Access-Control-Allow-Origin", "*")
})
```

The parse will match the `/docs` as `*`, because of the insertFilter. The return value `ctx.Input.Param(":splat")` will be `docs`.

```go
if splat := ctx.Input.Param(":splat"); splat == "" {
    obj = GlobalDocApi["Root"]
} else {
    if v, ok := GlobalDocApi[splat]; ok {
         obj = v
	}
    }
    if obj != nil {
        bt, err := json.Marshal(obj)
	if err != nil {
			ctx.Output.SetStatus(504)
			return
		}
		ctx.Output.Header("Content-Type", "application/json;charset=UTF-8")
		ctx.Output.Header("Access-Control-Allow-Origin", "*")
		ctx.Output.Body(bt)
		return
	}
```

**Comment by coseyo** [comment]
Yeah, you are right! Just change it to

beego.InsertFilter("/docs/*", beego.BeforeRouter, func(ctx *context.Context) {
		ctx.Output.Header("Access-Control-Allow-Origin", "*")
	})

**Comment by JessonChan** [comment]
@astaxie 
the issue could be closed
