### ISSUE TITLE
Api crash with optional params

### ISSUE THREAD

**Issue by aperezg** [astaxie/beego#1245]
I don't understand why in the function 'bind' in line 356:(https://github.com/astaxie/beego/blob/master/context/input.go#L356) 

The code is : 
rv := reflect.Zero(reflect.TypeOf(0))

instead of:
rv := reflect.Zero(typ)

This causes when we make API calls expecting a string parameter that does not come in the request that can be optional, the app crash instead of get the default value that is what seems to be attempted if we follow the rest of the code.

**Comment by aperezg** [comment]
Perfect thank you!

**Comment by JessonChan** [comment]
@astaxie 
closable
