### ISSUE TITLE
filter插入后路由的参数解析失败

### ISSUE THREAD

**Issue by lvshuchengyin** [astaxie/beego#1251]
beego.InsertFilter("/*", beego.BeforeExec, BeforeExecFilter) 插入一个filter后，ctx.Input.Params里面就会为空了，这是什么原因？

**Comment by oiooj** [comment]
你用的是什么版本？把你的代码贴下

**Comment by lvshuchengyin** [comment]
func BeforeExecFilter(ctx *context.Context) {
	ctx.Input.Data["_MetricsStartTime"] = time.Now().UnixNano()
}

VERSION = "1.4.2"

**Comment by eddielin** [comment]
正确描述应该是在filter里面获取不到，在controller里面还是可以的

我最后变成在prepare里做动作了，不知道是不是设计就是如此

**Comment by oiooj** [comment]
试试新版本 1.5.0 ,已经修复了这个问题

**Comment by lei-cao** [comment]
@lvshuchengyin Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie close?

**Comment by JessonChan** [comment]
@astaxie 
solved

**Comment by iamzhout** [comment]
@oiooj @lei-cao @astaxie I want to know more detail about this issue, would you please give the commit url that resolves this issue?  
Thanks!

/Tao

**Comment by iamzhout** [comment]
I have found the commit resolving this issue: https://github.com/astaxie/beego/commit/491238ce7d698f7a0ab65b8d820edb11339bcd3f
