### ISSUE TITLE
How to recover panic with a panic which throw by a corountine

### ISSUE THREAD

**Issue by simpleton** [astaxie/beego#1254]
I've set the `recoverPanic` flag to true in `conf/app.conf`.It only works when the panic which throw by the controller. If a panic happened in a corountine, the whole app will crash.

Is there any method to avoid that.

PS:I use `sentry` to upload my error stack, is there any callback to do that.

**Comment by astaxie** [comment]
@simpleton Maybe I can add a recoverfunc for the application

```
package main

import "github.com/astaxie/beego"

func main() {
   defer beego.Recover()
    beego.Run()
}
```
