### ISSUE TITLE
Golint and Id

### ISSUE THREAD

**Issue by ptman** [astaxie/beego#1257]
[Golint](https://github.com/golang/lint) would like `Id` fields to be named `ID` instead. beego/orm thinks the column name for a field called `ID` is `i_d`. I'm not sure that I agree with golint, but to get golint to shut up about:

    struct {
        Id int
        ...
    }

I have to do the following:

    struct {
        ID int `orm:"pk;auto;column(id)"`
        ...
    }

PS. is the golint-"fixed" version equivalent to the first? Or are there some subtle differences?

**Comment by astaxie** [comment]
@ptman I think beego/ORM can make a compatible with golint

**Comment by zainul-ma** [comment]
Just ask the conversation above
So , how to make bee tools generated Id should be ID ?
maybe we can set config first at the project and make bee tools generate ID rather than Id ..

Thanks
