### ISSUE TITLE
ORM:RelatedSel unable to load one-to-many records.

### ISSUE THREAD

**Issue by ljia310** [astaxie/beego#1258]
I have this:

type TimeItem struct {
	Id      int      `orm:pk;"default(1)"`
	BegTime string   `orm:size(64);00:00`
	EndTime string   `orm:size(64);00:00`
	TimeSeg *TimeSeg `orm:"rel(fk)"`
}

type TimeSeg struct {
	Id       int         `orm:pk;"default(1)"`
	Name     string      `orm:size(64);null`
	TimeItem []*TimeItem `orm:"reverse(many)"`
}
As I run this:

func TimeSeg_GetAll() orm.QuerySeter {
	o := orm.NewOrm()
	o.Using("default") 
	return o.QueryTable(new(TimeSeg)).RelatedSel()
}
It returns an array of TimeSeg but TimeItem inside each record is null.

[
  {
    "Id": 2,
    "Name": "test1",
    "TimeItem": null
  },
  {
    "Id": 3,
    "Name": "test2",
    "TimeItem": null
  }
]

How to load all the related TimeItem? Please help.

**Comment by Hepri** [comment]
You need to manually call LoadRelated for each record

e.g.

    o := orm.NewOrm()
    for _, el := range arr {
        o.LoadRelated(el, "TimeItem")
    }
