### ISSUE TITLE
cache模块

### ISSUE THREAD

**Issue by lifeibo** [astaxie/beego#1260]
每次NewCache出来的，都是返回同一个memory cache，然后再启一下gc的goroutine，然后就会出现两个goroutine同时range一个map，然后就有可能会coredump掉。然后在NewCache的时候，传入的参数还有啥，用处么？
建议每次NewCache的时候，创建一个新的出来，而不是返回已有的。

**Comment by lei-cao** [comment]
@lifeibo Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by JessonChan** [comment]
thanks for your issue.
the cache module now works with a new instance instead of use the previous.
@astaxie 
this issue is closable.
