### ISSUE TITLE
生成文档时提示该错误，具体是什么原因呢

### ISSUE THREAD

**Issue by mohong122** [astaxie/beego#1261]
panic: runtime error: index out of range

goroutine 1 [running]:
main.getModel(0xc082206340, 0xb, 0xc082206340, 0x6, 0xc082206347, 0x4, 0xc08230d370, 0x4, 0x0, 0x0, ...)
        E:/wwwroot/Go/src/github.com/beego/bee/g_docs.go:574 +0x1050
main.parserComments(0xc0820ea4a0, 0xc0820e85ad, 0x3, 0xc082217e70, 0xe, 0xc082005761, 0x1a, 0x0, 0x0)
        E:/wwwroot/Go/src/github.com/beego/bee/g_docs.go:406 +0x13e6
main.analisyscontrollerPkg(0xc082005761, 0x1a)
        E:/wwwroot/Go/src/github.com/beego/bee/g_docs.go:308 +0xa03
main.generateDocs(0xc082059530, 0x20)
        E:/wwwroot/Go/src/github.com/beego/bee/g_docs.go:152 +0x54d
main.generateCode(0xb98980, 0xc082003ee0, 0x1, 0x1, 0x0)
        E:/wwwroot/Go/src/github.com/beego/bee/g.go:125 +0xcdf
main.main()
        E:/wwwroot/Go/src/github.com/beego/bee/bee.go:113 +0x3af

---
程序运行没有问题，就是生成文档时报错，不知道是什么原因呢

**Comment by lei-cao** [comment]
@mohong122 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by JessonChan** [comment]
@astaxie 
this issue can be closed.
