### ISSUE TITLE
orm 外键类型 varchar(0)

### ISSUE THREAD

**Issue by micln** [astaxie/beego#1262]
结构体定义：

```go
type User struct{
	...
}

type Article struct{
	...
	User	*User	`orm:"rel(fk)"`
}
```

模型注册：

```go
orm.RegisterModel(new(User), new(Article))
```

控制台信息：

```go
create table `article`
    -- --------------------------------------------------
    --  Table Structure for `Article`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `article` (
    	...
        `user_id` varchar(0) NOT NULL,
        ...
    );
```

User注册正常，Article其他字段正常

**Comment by Hepri** [comment]
Do you have int primary key in User table?

**Comment by micln** [comment]
有的。。可也不该转成0char吧

你是指必须在tag中标明吗?

```go
type User struct{
    Id int
}
```

**Comment by Hepri** [comment]
I guess that beego ORM think that there is no primary key in User struct so use some default wrong implementation - varchar(0)

I'm using ORM this way, and haven't any problems:
    
    type User struct {
        Id              int         `orm:"auto"`
        Login           string      `orm:"size(50);unique"`
        Password        string      `orm:"size(100)"`
    }

P.S. I don't recommend beego sql generator. It hasn't migrations, so cannot alter tables. For my project I'm using liquibase, and it works fine

**Comment by micln** [comment]
thanks
