### ISSUE TITLE
httplib:为什么要使用log.Fatal?

### ISSUE THREAD

**Issue by fugr** [astaxie/beego#1268]
`httplib` two functions used `log.Fatal`,
func NewBeegoRequest(rawurl, method string) *BeegoHttpRequest
func (b *BeegoHttpRequest) buildUrl(paramBody string)

program exit when called log.Fatal.

**Comment by astaxie** [comment]
恩，这个需要改进一下，lib里面不应该有fatal，需要返回err才是正确的处理方式

**Comment by lei-cao** [comment]
@fugr Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
