### ISSUE TITLE
beego有开发user authentication相关模块的计划么？

### ISSUE THREAD

**Issue by tonyzhu** [astaxie/beego#1272]
如题

**Comment by lei-cao** [comment]
@tonyzhu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  close?
duplicated https://github.com/astaxie/beego/issues/432

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like MAC, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

In fact, a light-weight project named [pybbs-go](https://github.com/tomoya92/pybbs-go) which is based on Beego already integrates casbin.

So please consider using casbin when beego implements RBAC security. Also let me know if there's any question:)
