### ISSUE TITLE
http.Handler support for access logging

### ISSUE THREAD

**Issue by jcaustin98** [astaxie/beego#1277]
I need apache2 style access logging in my beego api application.

1) is there an existing way to do this with beego?

2) I have found that the gorilla/handlers has the logger that will work for this and it says it can be used in any framework that supports http.Handler.  It does not look like the filters will work for this.  How would I go about integrating this package with Beego?

**Comment by astaxie** [comment]
beego current use the own style access log, if you want use the apache2 style, you need to writer the plugins to implement that
