### ISSUE TITLE
控制器中redirect跳转一次后再次点击该链接该方法无法执行

### ISSUE THREAD

**Issue by jesusslim** [astaxie/beego#1278]
例如在控制器的A方法中判断登陆态 未登录则跳转到登录页 使用时第一次点击会跳转到登录页 登陆成功以后 再次点击该链接 仍会去登录页 并且不进入A方法 是否beego对路由做了缓存? 这样登陆后都没法去正确的这个链接了 如何避免这种问题 ？

**Comment by ElvizLai** [comment]
预估是代码问题。上代码吧
我们整个网站都是这套流程下来都没有问题。。。

**Comment by tomoya92** [comment]
@jesusslim 你是不是用了301重定向？我也碰到这样的问题了

**Comment by tomoya92** [comment]
我测试发现，302重定向就不会出现第一次生效之后都失效的问题，求解答 @elvizlai @astaxie

**Comment by tomoya92** [comment]
@jesusslim 我解决了，原来是浏览器自己缓存的，把浏览器的缓存清理一下就可以了

**Comment by elvizlai** [comment]
301是永久重定向，浏览器会缓存。建议查阅下http status code
