### ISSUE TITLE
Add a way to specific a different config file

### ISSUE THREAD

**Issue by ColorFuzzy** [astaxie/beego#1280]
I feel that dev-mode is not that convenient for a big project with many developers and many environments(local/staging/production).

I'd like to add a config file environment variable to beego, and send a pull request.

I don't know whether the beego team needs this feature, and I think it's good to start a proposal before coding.

**Comment by astaxie** [comment]
@ColorFuzzy Look at current config for the beego. If you have any good idea please let us know.https://github.com/astaxie/beego/blob/develop/config.go#L28-L41

**Comment by ColorFuzzy** [comment]
OK, current config works good.
