### ISSUE TITLE
orm在执行read的时候报错

### ISSUE THREAD

**Issue by pchenghao** [astaxie/beego#1281]
model的代码如下：
// blog.go
package models

import (
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
	"time"
)

const(
	PAGE_SIZE = 10
)

type BlogContent struct{
	Id 				int			`orm:"auto"`
	User			*User 		`orm:"rel(fk);null;on_delete(set_null)"` //外键对应值删除时，些记录不删除，设置为null
	Title			string
	Type 			string		`orm:"null"`
	Label			string		`orm:"null"`
	Content			string		`orm:"null;type(text)"`
	Top				string		`orm:"null"`
	PublicTime		time.Time	`orm:"null;auto_now_add;type(datetime)"` //第一次保存时设置时间
	LastModifyTime	time.Time	`orm:"null;auto_now;type(datetime)"` //每次保存时自动更新时间
	State			int			`orm:"default(1)"`
}

type User struct {
	Id				int			`orm:"auto"`
	Username		string
	Password		string
	Level			int			`orm:"default(0)"`
}

var o orm.Ormer

func init(){
	//注册模型
	orm.RegisterModel(new(BlogContent), new(User))
	//初始化Orm
	orm.RegisterDataBase("default", "mysql", "root:123456@/blog?charset=utf8")
	orm.RunSyncdb("default", false, true)
	//初始化Orm对象
	o = orm.NewOrm()
}

//分布查询博客
func GetBlogsByPage(pageNo int) (blogs []*BlogContent,err error){
	if pageNo == 0 {
		pageNo = 1
	}
	from := (pageNo - 1) * PAGE_SIZE + 1
	to := pageNo * PAGE_SIZE
	_,err = o.QueryTable("blog_content").Filter("state", 1).OrderBy("top", "-lastmodifytime").Limit(to, from).All(&blogs)
	return
}

//根据Id查询博客
func GetBlogById(id int) (blog *BlogContent, err error){
	blog = &BlogContent{Id: id}
	err = o.Read(&blog) //这里会报错
	return
}

调用GetBlogById函数时会报错：Handler crashed with error <Ormer> table: `.` not found, maybe not RegisterModel 
在init中已经注册过BlogContent，并且在使用GetBlogsByPage函数时正常。
求大神帮忙看一下，谢谢。

**Comment by jinguoliang** [comment]
blog = &BlogContent{Id: id}
err = o.Read(&blog) //这里会报错
应该是err = o.Read(&blog)吧? blog已经是BlogContent的指针了

**Comment by pchenghao** [comment]
感谢你的帮助，已经解决。
顺便请教下，是不是一般传对象的时候传指针？这样会更节省内存吗？之前是做java的，对指针不太理解，望简单指教下什么情况下用指针。我知道的有需要改变对象内部值的时候会传指针。

**Comment by jinguoliang** [comment]
我也是做java的, 正在学习go, 根据<<learn go>>的理解: 一般传指针, 不仅节省内存而且效率高, 但是有些地方为了防止修改需要穿值, 而且对于一些基本类型, 如果不要求修改它的值就不要传指针了, 否则没有好处,不会省内存

**Comment by pchenghao** [comment]
感谢你的帮助。刚刚又遇到个问题，就在这里再请教一下了。
我在BlogContent中添加了一个表示博客评论的结构体引用，博客评论结构体定义如下：
//博客评论
type BlogComment struct {
	Id				int				`orm:"auto"`
	Blog			*BlogContent	`orm:"rel(fk);null;on_delete(set_null);column(blog_id)"`
	User			*WeiboUserinfo	`orm:"rel(fk);null;on_delete(set_null);column(user_id)"`
	ParentId		int				`orm:"default(0)"`
	Content			string			`orm:"type(text)"`
}
添加引用后的BlogContent内容如下：
//博客内容
type BlogContent struct{
	Id 				int				`orm:"auto"`
	User			*User 			`orm:"rel(fk);null;on_delete(set_null)"` //外键对应值删除时，些记录不删除，设置为null
	Title			string
	Type 			string			`orm:"null"`
	Label			string			`orm:"null"`
	Content			string			`orm:"null;type(text)"`
	Top				string			`orm:"null"`
	PublicTime		time.Time		`orm:"null;auto_now_add;type(datetime)"` //第一次保存时设置时间
	LastModifyTime	time.Time		`orm:"null;auto_now;type(datetime)"` //每次保存时自动更新时间
	State			int				`orm:"default(1)"`
	Comment			[]*BlogComment	`orm:"reverse(many)"`
}
，本来自己建的表blog_comment，但读取时取不到值。然后把表名改了，系统重启后日志里显示创建了表blog_comment，但查看数据库时发现没有blog_comment表，代码中查到的BlogContent对象中的Comment中还是空的，，请帮我分析一下哈，万分感谢。

**Comment by pchenghao** [comment]
重新启动应用后，日志中又打印了创建表的语句，但数据库中刷新还是没有表...
创建表日志如下：
create table `blog_comment` 
    -- --------------------------------------------------
    --  Table Structure for `beeBlog/models.BlogComment`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `blog_comment` (
        `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
        `blog_id` integer,
        `user_id` integer,
        `parent_id` integer NOT NULL DEFAULT '0' ,
        `content` longtext NOT NULL DEFAULT '' 
    ) ENGINE=InnoDB;
