### ISSUE TITLE
Environment variables in config

### ISSUE THREAD

**Issue by byrnedo** [astaxie/beego#1283]
Would be nice if the config could support environment variables (Removing need for the current BEEGO_RUNMODE env ).

Maybe by running the file/each line through https://golang.org/pkg/os/#ExpandEnv?

I would be happy to implement, just wondering on thoughts. I'm against coding environment variables into my app as these are hard to maintain and easy to leave undocumented.

My quick attempt:
https://github.com/byrnedo/beego/commit/d353c7cdd9ca18bda085a3d66638a8c3dd7f6361

Perhaps better ( in case of json and yaml ) to just parse and replace in the whole file.

**Comment by astaxie** [comment]
yea, that's what I am think these days. @smallfish is also want this features.

**Comment by csharris** [comment]
+1

**Comment by vvelikodny** [comment]
+1
