### ISSUE TITLE
建立restful api以后，一般的页面渲染就失败了

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [astaxie/beego#1287]
根据知道，restful的api需要做以下设置
autorender = false
copyrequestbody = true

这样的话，默认的模板就没有返回，如果不设置这两个属性，restful会提示模板未设置，有没有什么办法两者兼容？

**Comment by ElvizLai** [comment]
既然混合式的rest api，autorender不需要设置（默认为true），需要页面展示的部分，通过template返回页面，不设置模板的部分肯定是有json或xml返回数据的啊，并不存在你说的那个问题。

**Comment by astaxie** [comment]
你说的问题是页面和API共存的一个例子，有几个方案供你参考：

1. 继续以API为主，设置`autorender=false`，然后在你要渲染的逻辑函数里面直接显示的调用`c.Render()`

2. 以Web为主，设置`autorender=ture`，然后在你的API逻辑Controller里面设置`c.EnableRender=false`

我个人推荐你用第一种方式，可能更好的控制显示还是不显示页面

**Comment by ziyouchutuwenwu** [comment]
谢谢大大。
