### ISSUE TITLE
toolbox.Task增加运行判断

### ISSUE THREAD

**Issue by tnextday** [astaxie/beego#1288]
`toolbox.StartTask` 会在 AdminApp启动的时候调用一次，但是`StartTask`中并没有判断是否已经运行的逻辑，这样就会有个问题，在使用 Task 模块时需要判断是否打开了 Admin 模块，否则会造成重复运行的问题

**Comment by lei-cao** [comment]
@tnextday Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
