### ISSUE TITLE
API 文档问题

### ISSUE THREAD

**Issue by tnextday** [astaxie/beego#1290]
bee generate docs生成 docs.go 的 init 函数中没有判断`beego.GlobalDocApi`，这样会导致无法使用配置文件开关 api 文档功能，因为打开 api 文档要import _ "docs"，如果配置EnableDocs为 false，`beego.GlobalDocApi` 为 nil, 导致应用崩溃

解决办法：`bee generate docs` 的模板文件中加入EnableDocs条件判断

**Comment by lei-cao** [comment]
@tnextday Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
