### ISSUE TITLE
beego能动态注册路由吗？

### ISSUE THREAD

**Issue by chuangyou** [astaxie/beego#1291]
RT，我把路由的正则，所用控制器，操作方法写在配置文件里动态注册行不？

**Comment by astaxie** [comment]
你可以动态的读取数据，然后写一个plugin放在BeforeRouter
然后再你的plugin里面赋值给这个就可以了，你就可以控制执行什么Controller和method
 context.Input.RunMethod
 context.Input.RunController你可以动态的读取数据，然后写一个plugin放在BeforeRouter
然后再你的plugin里面赋值给这个就可以了，你就可以控制执行什么Controller和method
``` 
context.Input.RunMethod
context.Input.RunController
```
