### ISSUE TITLE
为什么 Filter 中的匹配规则（pattern）要修改 context.Input.Params 

### ISSUE THREAD

**Issue by tnextday** [astaxie/beego#1293]
问题是这样的
项目里面添加了

    beego.InsertFilter("*", beego.BeforeRouter, someFilter)

结果发现 api 文档（/docs）不能用了

查看beego代码发现在处理 filter 时自动把 filter 匹配到的参数添加到`Input.Params `中了，这样导致的结果是

	Get("/docs", serverDocs)
	Get("/docs/*", serverDocs)
	
这样的代码，当访问`/docs`时会有`:splat`这个错误的参数

有点想不通为啥要在 Filter 中修改 Input 参数

**Comment by astaxie** [comment]
FIlter里面匹配的参数赋值给param里面不会有错，这个方便catch所有的过滤器的路由信息，至于你这个错误，应该来说/doc/*这个里面的`:splat`覆盖FIlter里面的才对

**Comment by zhaorong** [comment]
请问下在添加filter之后,该如何使得api文档（/docs）还能正常工作啊

**Comment by zhaorong** [comment]
if ctx.Input.Param(":splat") == "docs" {
			ctx.Input.Params[":splat"] = ""
		}
在过滤器里面在了以上代码可以正常工作了

**Comment by lei-cao** [comment]
@zhaorong Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@tnextday Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
