### ISSUE TITLE
Cors problems 

### ISSUE THREAD

**Issue by peterpalace** [astaxie/beego#1294]
I have a problem with cors and beego. 
This is my code:
```go
func main(){
beego.InsertFilter("*", beego.BeforeRouter,cors.Allow(&cors.Options{
        AllowAllOrigins: true,
        AllowMethods: []string{"GET", "DELETE", "PUT", "PATCH", "OPTIONS"},
        AllowHeaders: []string{"Origin", "Access-Control-Allow-Origin"},
        ExposeHeaders: []string{"Content-Length", "Access-Control-Allow-Origin"},
        AllowCredentials: true,
    }))
beego.Run()
}
```
I receive this answer:
"XMLHttpRequest cannot load http://localhost:8080/. No 'Access-Control-Allow-Origin' header is present on the requested resource"

I can't figure it out. Do you have any ideas?
Thanks for any help.

**Comment by bakanis** [comment]
Try this: instead AllowAllOrigins: true put AllowOrigins:     []string{"*"},

**Comment by peterpalace** [comment]
It doesn't resolve the problem...

**Comment by astaxie** [comment]
@peterpalace could you open your chrome inspect to check when you send a ajax request, what's the response you got

**Comment by peterpalace** [comment]
this is the response header:
```shell
HTTP/1.1 200 OK
Content-Length: 2510080
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.5.0
```
and this is the answer
```shell
XMLHttpRequest cannot load http://localhost:8080/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
```
Thanks for the help

**Comment by bakanis** [comment]
As far as I know browsers do not support cors from localhost. Give them ip, eg. 192.168.xx.xx

**Comment by peterpalace** [comment]
do you mean put them in two different machines? because if I use the ip(192.168.1.x) instead of "localhost", It still doesn't work because it finds the same ip.
I've also tried with "google-chrome --disable-web-security" flag

**Comment by bakanis** [comment]
I'm new to API's but a couple days ago I had the same difficulties trying to create a jwt based login from aurelia spa. I set up beego config to httpaddr = "192.168.1.108" httpport = 8080 and aurelia app on nodejs on the same ip but 9000 port.

**Comment by peterpalace** [comment]
Also with the ip it doesn't work. In the header of the response there isn't "Access-Control-Allow-Origin: *" as I put in the code.
a sample fix is to use chromium with some flags
```shell
chromium-browser --disable-web-security –allow-file-access-from-files
```
but if I want to access the site from another machine in the same network (without all the flags) it doesn't work.

**Comment by bakanis** [comment]
I tried this to check and the headers appeared..
package filters

import (
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/context"
	"github.com/astaxie/beego/plugins/cors"
)

func init() {

	beego.Debug("Filters init...")

	// CORS for https://foo.* origins, allowing:
	// - PUT and PATCH methods
	// - Origin header
	// - Credentials share

	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
		AllowCredentials: true,
	}))
}
![screenshot](https://cloud.githubusercontent.com/assets/1028446/9023801/b76cc74a-38b4-11e5-85ce-4ba8ca4264bb.png)

**Comment by peterpalace** [comment]
It is strange. For me with your example, my response headers is: 
``` shell
HTTP/1.1 200 OK
Content-Length: 267
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.5.0
Date: Mon, 03 Aug 2015 08:11:10 GMT
```
I have a main.go with only "beego.Run()" and router.go with all your example and 
" beego.Router("/", &controllers.MainController{}) "

I don't understand.

**Comment by peterpalace** [comment]
With another framework it works and therefore is not the client app. I don't know what I'm doing wrong

**Comment by astaxie** [comment]
I have no idea now. it looks it not execute the filter. what's your beego version?

**Comment by peterpalace** [comment]
The version is 1.5.0. It is inside beego.go

**Comment by Hepri** [comment]
This worked for me with cors

    this.Ctx.ResponseWriter.Header().Add("Access-Control-Allow-Origin", "*")
    this.Ctx.ResponseWriter.Header().Add("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")

**Comment by peterpalace** [comment]
you are right.
it works with this:
```go
func (this *MainController) Get() {
	this.Ctx.ResponseWriter.Header().Add("Access-Control-Allow-Origin", "*")
	this.Ctx.ResponseWriter.Header().Add("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
/* all your code */
this.ServeJson()
}
```

Thank you.

**Comment by astaxie** [comment]
@peterpalace but that still not make sense why the fliter not works.

```
beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
    AllowOrigins:     []string{"*"},
    AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
    AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
    ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
    AllowCredentials: true,
}))beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
    AllowOrigins:     []string{"*"},
    AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
    AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
    ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
    AllowCredentials: true,
}))
```

**Comment by Hepri** [comment]
@peterpalace do you have any filter functions before CORS? I've just found same problem, but problem was in filter that triggered before, and cors code just don't initialized

And using
    AllowAllOrigins: true
instead of
    AllowOrigins:     []string{"*"},
looks more convinient

Please write down routers.go and main.go code

**Comment by Hepri** [comment]
Btw, have you defined InsertFilter in main.go? Try to move this code to router.go

**Comment by peterpalace** [comment]
my code:
main.go
```go
func main() {
beego.Run()
}
```
router.go
```go
func init() {
    beego.Debug("Filters init...")
    beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
        AllowAllOrigins: true,
        AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
        AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
        ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
        AllowCredentials: true,
    }))
    beego.Router("/", &controllers.MainController{})
}
```
@astaxie I know that it doesn't resolve the problem with beego.insertFilter but it does resolve the problem with cors+beego.

**Comment by Hepri** [comment]
@peterpalace try to put InsertFilter after Router method

**Comment by peterpalace** [comment]
it doesn't work.
I still can't see the correct header in the request.
```go
func init() {
    beego.Debug("Filters init...")
    beego.Router("/", &controllers.MainController{})
    beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
        AllowAllOrigins: true,
        AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
        AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
        ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
    }))
```
the point is that if I comment the lines with beego.InsertFilter and I insert the lines:
 ```go
this.Ctx.ResponseWriter.Header().Add("Access-Control-Allow-Origin", "*")
this.Ctx.ResponseWriter.Header().Add("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
```
inside the controller, it works.

**Comment by Hepri** [comment]
I have no more ideas, looks like filter func just do not execute...

**Comment by Hepri** [comment]
Btw, this method is preferable

    beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
        AllowAllOrigins: true,
        AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
        AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
        ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
    }))

It properly handle OPTIONS request

**Comment by hlily2005** [comment]
beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin", "Content-Type"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin"},
		AllowCredentials: true,
	}))

it works for me.
