### ISSUE TITLE
default http HEAD with GET

### ISSUE THREAD

**Issue by Zverushko** [astaxie/beego#1295]
hello
now if i use GET method HEAD return 405 error

can you return 200 OK if there is a GET by default?

**Comment by bakanis** [comment]
http://stackoverflow.com/questions/26035962/golang-beego-framework-to-set-the-status-code
c.Ctx.ResponseWriter.WriteHeader(405)

**Comment by JessonChan** [comment]
@astaxie 
a closable issue
