### ISSUE TITLE
beego write test problem 

### ISSUE THREAD

**Issue by farmerworking** [astaxie/beego#1296]
package test_test

    import (
        "encoding/json"
        "net/http"
        "net/http/httptest"
        "github.com/astaxie/beego"
        "github.com/stretchr/testify/assert"
        "testing"
        "path/filepath"
        "runtime"
        _ "tae-ops-agent/routers"
        "tae-ops-agent/models/resp"
    )

    func init() {
        _, file, _, _ := runtime.Caller(1)
        apppath, _ := filepath.Abs(filepath.Dir(filepath.Join(file, ".."+string(filepath.Separator))))
        beego.TestBeegoInit(apppath)
        beego.CopyRequestBody=true
    }

    func TestStopContainer1(t *testing.T){
        r, _ := http.NewRequest("POST", "/container/stop", nil)
        w := httptest.NewRecorder()
        beego.BeeApp.Handlers.ServeHTTP(w, r)

        beego.Trace("testing", "TestGet", "Code[%d]\n%s", w.Code, w.Body.String())
        result := &resp.CodeResult{}
        json.Unmarshal(w.Body.Bytes(), &result)

        assert.Equal(t, 200, 200)
        assert.Equal(t, w.Code, 200)
    }

This problem is wired. once you comment `assert.Equal(t, w.Code, 200)` it works fine.

If you uncomment ` assert.Equal(t, w.Code, 200)`. It will report:

    beego:runtime error: invalid memory address or nil pointer dereference

then if you comment `beego.CopyRequestBody=true`. It will work fine again!

**Comment by dariusc93** [comment]
@farmerworking could you provide the whole exception you get?
