### ISSUE TITLE
求助duplicate column name

### ISSUE THREAD

**Issue by hakur** [astaxie/beego#1297]
```
type Article struct {
	Id      int64 
	Title   string
	Ctime   int
	Content string
	Etime   int
	Thumb   string
	AdminId     int64
	Type    int
	ColumnId int64  //就是这个字段如果定义就要报错
	Column *Column `orm:"null;rel(fk)"`
}
type Column struct {
	Id         int64 `orm:"pk"`
	Name       string
	Pid        int64
	Type       int
	Url        string
	Sort       int
	Background string
	Article []*Article `orm:"reverse(many)"`
}
```
beego版本 1.5

这两个结构体 Article代表文章Column代表栏目  Article中的ColumnId对应表里面的column_id 表示所属栏目，
但是我如果在Article结构体中写了ColumnId就会提示：field: models.Article.Column, duplicate column name: column_id
如果去掉了就不会报错
不过我在用 ParseForm 来自动解析到结构体然后保存   如果没有ColumnId这个字段我将无法保存表单上选择的栏目  select的name属性是ColumnId

我也试过  写成这样  ColId `orm:"column(column_id)"`依然会报错

还是说有其他的方法在form表单select name属性来表示article表的column_id字段？

Thanks！

**Comment by hakur** [comment]
articleModel.Column.Id = 1
在代码中这样写反倒是可以保存article表的column_id
不过parseForm的时候html表单name属性怎么写呢

**Comment by Hepri** [comment]
Am I understand right, that you added ColumnId just for ParseForm method, and do not use it anywhere? And want to fill it manually from db?

In this case you could refer to documentation and ignore this field from ORM http://beego.me/docs/mvc/model/models.md#ignore-field

**Comment by hakur** [comment]
@Hepri   I tried write   ColumnId int64 `orm:"-"` ,  ParseForm worked. But  Save to DB failed.
Now, I use articleModel.Column.Id = 1 instead, temporarily.

**Comment by lei-cao** [comment]
@hakur Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
@hakur that's the only way can fix this.
