### ISSUE TITLE
问下，如果需要在restful协议里面需要添加版本号，该怎么弄？

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [astaxie/beego#1299]
如题，需求如果是类似这样
api.domain.com/v1.1/users

需要映射到controller类似controllers/v1/users.php
应该怎么做？或者说，暂时还不支持？

**Comment by Hepri** [comment]
Something like that
    
    api_ns :=
        beego.NewNamespace("/v.1.1",
            beego.NSRouter("/login", &UsersController{}, "get:Users"),
        ),
    beego.AddNamespace(api_ns)

**Comment by ziyouchutuwenwu** [comment]
restful的路由似乎通不过啊
beego.RESTRouter("/object", &controllers.ObjectController{})

报错
routers/router.go:13: cannot use beego.RESTRouter("/object", &controllers.ObjectController literal) (type *beego.App) as type beego.innnerNamespace in argument to beego.NewNamespace
