### ISSUE TITLE
orm时区设置

### ISSUE THREAD

**Issue by pchenghao** [astaxie/beego#1303]
tag为orm:"null;auto_now_add;type(datetime)的字段，在做insert操作时，自动添加的时间总是比正常时间少8小时，时区似乎不对应？请问这个需要怎么自定义为当前的时区？

**Comment by pchenghao** [comment]
抱歉，已在记录中搜索到相同的问题，在数据库url中设置loc后解决。

**Comment by pchenghao** [comment]
抱歉，已在记录中搜索到相同的问题，在数据库url中设置loc后解决。

**Comment by xtea** [comment]
同样遇到过这个问题，这个应该在文档部分重点说明下

**Comment by astaxie** [comment]
@xtea http://beego.me/docs/mvc/model/orm.md#%E6%97%B6%E5%8C%BA%E8%AE%BE%E7%BD%AE
