### ISSUE TITLE
beego有没有类似laravel和rails的xxx_path函数

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [astaxie/beego#1306]
如题，我定义了一个route，希望有alias别名
在模版里面直接用这个别名，编译以后看到的就是路由连接

伪代码类似
route("admin/login","loginPath")

模版里面{{loginPath}}就可以拿到admin/login这个相对路径

**Comment by astaxie** [comment]
目前没有这个功能

**Comment by ziyouchutuwenwu** [comment]
好吧，谢谢
