### ISSUE TITLE
还是那个restful路由外面添加namespace的问题

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [astaxie/beego#1312]
其实是https://github.com/astaxie/beego/issues/1299
问题的延伸，之前没继续跟进测试，今天准备做项目的时候，发现在外面包了namespace以后，restfulRoute不能使用，RestfulRoute编译就错误，而普通的NSRoute在controller里面拿不到:objectId，直接贴代码吧

```
func init() {
	api_ns := beego.NewNamespace("/v1",
		beego.NSNamespace("/ios",
			//			beego.NSRouter("/object", &controllers.ObjectController{}, "get:GetObjects"),
			beego.NSRouter("/object", &controllers.ObjectController{}),
		),
	)
	beego.AddNamespace(api_ns)

	beego.RESTRouter("/aa", &controllers.ObjectController{})
}
```

```
func (this *ObjectController) Get() {
	params := this.Ctx.Input.Params
	for key, value := range params {
		info := fmt.Sprintf("%s: %s\n", key, value)
		this.Ctx.WriteString(info)
	}
}
```

访问http://127.0.0.1:8080/aa/asdasd 可以看到:objectId: asdasd
访问http://127.0.0.1:8080/v1/ios/object/asdadsadsasd 显示404

**Comment by astaxie** [comment]
RESTRouter和NSRoute完全不一样的注册方式，如果你想在namspace里面也支持这一的话你需要这样注册：

```
 api_ns := beego.NewNamespace("/v1",
        beego.NSNamespace("/ios",
            //          beego.NSRouter("/object", &controllers.ObjectController{}, "get:GetObjects"),
            beego.NSRouter("/object", &controllers.ObjectController{}),
            beego.NSRouter("/object/:objectId", &controllers.ObjectController{}),
        ),
    )
```

为什么RESTRouter不需要是因为它内部帮你注册了`:objectId`. 请看这个代码：https://github.com/astaxie/beego/blob/master/beego.go#L101-L105

**Comment by ziyouchutuwenwu** [comment]
明白了，不过不知道谢大有没有考虑直接封装一个restful直接映射到的是更加人性化一点的方法，比如/objects直接对应GetList方法，object/:objectId对应show方法等等，现在的都是Get，Post，Put等；
当然这个只是个人看法，不知道谢大有没有类似的计划和考虑？

**Comment by astaxie** [comment]
Get Post Put是RESTFul的处理方式，那种对应不符合啊

**Comment by ziyouchutuwenwu** [comment]
可能是我表述的有问题，在rails里面定义一个resources，然后rake routes，可以看到基于restful的路由可以直接映射到控制器里面的函数，希望在beego里面也能看到直接映射到默认定义

beego目前默认映射是到相应的get，put，post等方法，如果需要对应到业务相关的方法，比如GetUserList, UpdateUser, ShowUser, DeleteUser等等，得自己写，要么直接在后面添加映射方法，类似
```
beego.NSRouter("/users", &controllers.UserController{}, "get: GetUserList"),
```

要么在控制器里面获取参数以后自己显式调用，感觉略烦琐一些
```
func (this *UserController) Get() {
	this.GetUserList()
}
```

不知道我这么描述，是不是说清楚了？

**Comment by astaxie** [comment]
>在rails里面定义一个resources，然后rake routes，可以看到基于restful的路由可以直接映射到控制器里面的函数

这个还是不大明白啊，怎么restful的路由映射啊？需要在resources里面写特殊的字符什么的吗？

**Comment by ziyouchutuwenwu** [comment]
公司网速太渣了，重新配置ruby，rvm环境都下不下来，我只能借用rails中文指南的来说明了
http://guides.ruby-china.org/routing.html

比如创建一个restful的路由，在rails里面这样配置
resources :photos

会创建七个不同的路由，全部映射到 Photos 控制器上：

HTTP 方法	             路径	                 控制器#动作	                  作用
GET	                             /photos	         photos#index	                  显示所有图片
GET	                             /photos/new	 photos#new	                  显示新建图片的表单
POST	                     /photos	         photos#create	                  新建图片
GET	                             /photos/:id	         photos#show	                  显示指定的图片
GET	                             /photos/:id/edit	 photos#edit	                  显示编辑图片的表单
PATCH/PUT	             /photos/:id	         photos#update	          更新指定的图片
DELETE	                     /photos/:id	         photos#destroy	           删除指定的图片

希望get /photos/12345这样的url能直接映射到PhotoController的Show方法，其他的类似，不知道这样，是不是大概说清楚了，rails里面，rake routes，就能看到类似上面的表一样的输出，

只是在左边还有有个prefix，这个prefix相当于路由url的别名，这个暂时不重要了

**Comment by alex-lx** [comment]
谢大有没有计划实现这个需求呢？

**Comment by lei-cao** [comment]
@ziyouchutuwenwu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
