### ISSUE TITLE
orm struct中包含其它struct

### ISSUE THREAD

**Issue by pchenghao** [astaxie/beego#1315]
请问如何在一个添加到orm中的struct中引用其它的struct，并且映射的表中包含被引用的struct的所有字段？可以实现吗？
比如：
```go
type WechatWeareprogramersMsgLog struct {
	Id			int				`orm:"auto"`
	weixinmp.Request			
	MsgTime		time.Time		`orm:"null;auto_now_add;type(datatime)"`
}
```
该struct中引用了weixinmp.Request，将它添加到orm中，启动应用会报错。
请问可以实现类似的功能吗？

**Comment by lei-cao** [comment]
@pchenghao Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
see #1389
