### ISSUE TITLE
EnableGzip memory overhead

### ISSUE THREAD

**Issue by Hepri** [astaxie/beego#1317]
I've found strange behavior. With enabled "EnableGzip", beego alloc about 1.2 - 1.5 mb to run gzip compression for each request. So every request, even with tiny json response, lead to enormous memory usage and GC overhead.

**Comment by Hepri** [comment]
I found topic that explain the situation https://groups.google.com/forum/#!topic/golang-nuts/IS_nVbGSuig
Looks like you need to reuse gzip writer

**Comment by JessonChan** [comment]
Thanks for your advise.
We beego team has rewrite the compress module and use a sync.Pool to reuse the gzip writer.

**Comment by JessonChan** [comment]
@astaxie 
you can close this issue.
