### ISSUE TITLE
app.conf中存在带有空格的空行时, 导致启动程序时报空指针错误.

### ISSUE THREAD

**Issue by yougg** [astaxie/beego#1319]
自身程序中通过beego获取配置:
```go
beego.AppConfig.String("xxx")
```

编译后, 执行启动时报错:
```
panic: assignment to entry in nil map
```

在源文件 https://github.com/astaxie/beego/blob/master/config/ini.go 中第89行:
```go
line = bytes.TrimSpace(line)
```
Trim了空格之后, 应该再判断一下是否为空行, 而不是继续执行, 直到报错.
  
  
并且在 https://github.com/astaxie/beego/blob/master/config.go 文件第309行:
```go
err = ParseConfig()
```
拿到错误后,没有报错出来.

**Comment by lei-cao** [comment]
@yougg Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
