### ISSUE TITLE
reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by fly3q** [astaxie/beego#1327]
m *CmdInfo
调用
orm.QueryTable(m.TableName()).All(cmds)
返回
reflect: call of reflect.Value.Type on zero Value

Stack
/usr/local/go/src/runtime/asm_amd64.s:437
/usr/local/go/src/runtime/panic.go:423
/usr/local/go/src/reflect/value.go:1664
/data/zelus/go/src/github.com/astaxie/beego/orm/db.go:748
/data/zelus/go/src/github.com/astaxie/beego/orm/orm_queryset.go:174
/data/zelus/go/src/go-wx-proj/models/wx_config.go:73

请问怎么解决？使用read一条数据没有问题

**Comment by deadkrolik** [comment]
I think you should initialize pointer before use

```go
var m *CmdInfo
m = new(CmdInfo)
orm.QueryTable(m.TableName()).All(cmds)
```

**Comment by Piasy** [comment]
@deadkrolik Yes, initialize the pointer kill the error, but the [official document example](http://beego.me/docs/mvc/model/query.md#all) doesn't do that, which misleads us.

**Comment by miraclesu** [comment]
@Piasy I think `cmds` is defined like this: `var cmds *[]*CmdInfo`, is it? If yes, the cmds is a nil pointer, it will case the panic.

the [official document example](http://beego.me/docs/mvc/model/query.md#all):
```
var users []*User
num, err := o.QueryTable("user").Filter("name", "slene").All(&users)
```

the `&users` is a pointer for the slice([]*User, 0), not a nil pointer.

**Comment by Piasy** [comment]
@miraclesu What a mistake I have made! I use the `All` query in this way:
```golang
var users *[]User
users = new([]User)
num, err := o.QueryTable("user").Filter("name", "slene").All(users)
```
The `users` is of course `nil` if not initialised, declaring in the way of `var users []*User` and query as `All(&users)` will work perfectly.

The difference is a little bit subtle :)

**Comment by miraclesu** [comment]
@astaxie close?
