### ISSUE TITLE
如何创建一个unique的字段而且用orm insert的时候能默认是null的？

### ISSUE THREAD

**Issue by Jam-Lin** [astaxie/beego#1330]
我有一个字段需要初始的时候为null，然后会有程序自动填充这个值，但是每次我用orm 做insert操作的时候它都会变成字符串空值传进去，而不是null。请问怎么修改成null值传进去。

**Comment by ElvizLai** [comment]
要养成阅读文档的好习惯。
http://beego.me/docs/mvc/model/models.md

**Comment by Jam-Lin** [comment]
好的，谢谢。已解决。
