### ISSUE TITLE
有计划支持命令行设置参数不？

### ISSUE THREAD

**Issue by yanyiwu** [astaxie/beego#1332]
因为现在默认的是读取 conf/app.conf 配置文件。
但是一般 conf/app.conf 文件是在git管理下，临时想改一下 httpport参数，比如从8080改成9090，
不想改动被git管理的文件。

其他开源项目一般是通过命令行参数来设置：

比如像这个 seaweedfs(https://github.com/chrislusf/seaweedfs) 项目:

```
weed volume -dir="/tmp/data1" -max=5  -mserver="localhost:9333" -port=8080
```

**Comment by lei-cao** [comment]
@yanyiwu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
