### ISSUE TITLE
beego1.5启用graceful后，引起panic问题

### ISSUE THREAD

**Issue by alvin-li** [astaxie/beego#1333]
环境及版本：
<pre>
    bee   :1.3.0
    beego :1.5.0
    Go    :go version go1.5 linux/amd64
</pre>
问题：graceful模式下，出现panic，导致服务崩溃
QPS：1000左右
执行命令：
<pre>kill -HUP pid</pre>
服务在接收到hup信号后，执行了大概5秒钟左右，然后就出现以下错误
<pre>
2015/09/01 10:38:03 [router.go:879] [C] the request url is  /api/getdata 
2015/09/01 10:38:03 [router.go:880] [C] Handler crashed with error sync: negative WaitGroup counter 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/runtime/asm_amd64.s:437 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/runtime/panic.go:423 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/sync/waitgroup.go:70 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/sync/waitgroup.go:95 
2015/09/01 10:38:03 [router.go:886] [C] /home/webroot/test/src/github.com/astaxie/beego/grace/conn.go:11 
2015/09/01 10:38:03 [router.go:886] [C] <autogenerated>:22 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/net/http/server.go:279 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/bufio/bufio.go:594 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/net/http/server.go:1140 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/net/http/server.go:1112 
2015/09/01 10:38:03 [router.go:886] [C] /home/webroot/test/src/github.com/astaxie/beego/router.go:914 
2015/09/01 10:38:03 [router.go:886] [C] /home/webroot/test/src/github.com/astaxie/beego/context/output.go:88 
2015/09/01 10:38:03 [router.go:886] [C] /home/webroot/test/src/github.com/astaxie/beego/controller.go:185 
2015/09/01 10:38:03 [router.go:886] [C] /home/webroot/test/src/github.com/astaxie/beego/router.go:810 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/net/http/server.go:1862 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/net/http/server.go:1361 
2015/09/01 10:38:03 [router.go:886] [C] /usr/local/go/src/runtime/asm_amd64.s:1696 
2015/09/01 10:38:03 http: multiple response.WriteHeader calls
panic: sync: negative WaitGroup counter

goroutine 30775 [running]:
sync.(*WaitGroup).Add(0xc82001d228, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:70 +0xd0
sync.(*WaitGroup).Done(0xc82001d228)
	/usr/local/go/src/sync/waitgroup.go:95 +0x2a
github.com/astaxie/beego/grace.graceConn.Close(0x7fce54c9c8b0, 0xc821146698, 0xc82001d200, 0x0, 0x0)
	/home/webroot/test/src/github.com/astaxie/beego/grace/conn.go:11 +0x39
github.com/astaxie/beego/grace.(*graceConn).Close(0xc8203742e0, 0x0, 0x0)
	<autogenerated>:22 +0xad
net/http.(*conn).close(0xc8218480b0)
	/usr/local/go/src/net/http/server.go:1228 +0x4c
net/http.(*conn).serve.func1(0xc8218480b0, 0x7fce54c9c910, 0xc8203742e0)
	/usr/local/go/src/net/http/server.go:1291 +0x294
net/http.(*conn).serve(0xc8218480b0)
	/usr/local/go/src/net/http/server.go:1374 +0x884
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 1 [chan receive, 1 minutes]:
github.com/astaxie/beego.(*App).Run(0xc82000f580)
	/home/webroot/test/src/github.com/astaxie/beego/app.go:171 +0x33d
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/home/webroot/test/src/github.com/astaxie/beego/beego.go:277 +0x17d
main.main()
	/home/webroot/test/src/test/main.go:9 +0x28

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc8201245d0)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8201245c0)
	/usr/local/go/src/sync/cond.go:62 +0x9b
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc820014200, 0x0)
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe5
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc820014200)
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

goroutine 7 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc820124750)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc820124740)
	/usr/local/go/src/sync/cond.go:62 +0x9b
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc820014300, 0x0)
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe5
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc820014300)
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

goroutine 76 [select, 1 minutes, locked to thread]:
runtime.gopark(0xb244d0, 0xc820029728, 0xa243c8, 0x6, 0x100000018, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820029728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820029728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7fce54c9c780, 0x72, 0xc82000e190)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82026e530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026e530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82026e4d0, 0x0, 0x7fce54cbb5d8, 0xc820d65800)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002a2d0, 0xc820e21388, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/astaxie/beego/grace.(*graceListener).Accept(0xc82026cb10, 0x0, 0x0, 0x0, 0x0)
	/home/webroot/test/src/github.com/astaxie/beego/grace/listener.go:32 +0x70
net/http.(*Server).Serve(0xc82001c480, 0x7fce54c9c878, 0xc82026cb10, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/astaxie/beego/grace.(*graceServer).Serve(0xc82001d200, 0x0, 0x0)
	/home/webroot/test/src/github.com/astaxie/beego/grace/server.go:35 +0x62
github.com/astaxie/beego/grace.(*graceServer).ListenAndServe(0xc82001d200, 0x0, 0x0)
	/home/webroot/test/src/github.com/astaxie/beego/grace/server.go:74 +0x507
github.com/astaxie/beego.(*App).Run.func2(0xc82020f520, 0xc82000f580, 0xc82026e460)
	/home/webroot/test/src/github.com/astaxie/beego/app.go:109 +0xcf
created by github.com/astaxie/beego.(*App).Run
	/home/webroot/test/src/github.com/astaxie/beego/app.go:115 +0x823

goroutine 12 [chan receive, 1 minutes]:
github.com/astaxie/beego/grace.(*graceServer).handleSignals(0xc82001d200)
	/home/webroot/test/src/github.com/astaxie/beego/grace/server.go:172 +0x2b1
created by github.com/astaxie/beego/grace.(*graceServer).ListenAndServe
	/home/webroot/test/src/github.com/astaxie/beego/grace/server.go:51 +0x9e

goroutine 13 [chan receive, 1 minutes]:
github.com/astaxie/beego/grace.newGraceListener.func1(0xc82002a2d8)
	/home/webroot/test/src/github.com/astaxie/beego/grace/listener.go:24 +0x4e
created by github.com/astaxie/beego/grace.newGraceListener
	/home/webroot/test/src/github.com/astaxie/beego/grace/listener.go:27 +0x119

goroutine 42455 [runnable]:
text/template/parse.lexText(0xc820015d80, 0xb24340)
	/usr/local/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc820015d80)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 42450 [runnable]:
sync.runtime_Syncsemacquire(0xc821c9eed0)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc821c9eec0)
	/usr/local/go/src/sync/cond.go:62 +0x9b
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc820015300, 0xb24300)
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe5
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc820015300)
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/webroot/test/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

goroutine 42454 [runnable]:
text/template/parse.lexText(0xc820015d00, 0xb24340)
	/usr/local/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc820015d00)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 42456 [runnable]:
text/template/parse.lexText(0xc820015e00, 0xb24750)
	/usr/local/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc820015e00)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 33935 [IO wait]:
net.runtime_pollWait(0x7fce54c9d578, 0x72, 0xc82000e190)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82026e840, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026e840, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82026e7e0, 0xc820f3a000, 0x1000, 0x1000, 0x0, 0x7fce54c92050, 0xc82000e190)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82122e638, 0xc820f3a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/astaxie/beego/grace.(*graceConn).Read(0xc82071d0a0, 0xc820f3a000, 0x1000, 0x1000, 0xa14600, 0x0, 0x0)
	<autogenerated>:16 +0x82
net/http.(*liveSwitchReader).Read(0xc820e03228, 0xc820f3a000, 0x1000, 0x1000, 0x1513, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82071d0c0, 0xc820f3a000, 0x1000, 0x1000, 0xa1cca0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc82127e4e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82127e4e0, 0xc81ffcf70a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc82127e4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8201ec000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8201ec000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc82127e4e0, 0xc820611420, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820e031e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820e031e0)
	/usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 30776 [IO wait]:
net.runtime_pollWait(0x7fce54222000, 0x72, 0xc82000e190)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820fda530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820fda530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820fda4d0, 0xc820772000, 0x1000, 0x1000, 0x0, 0x7fce54c92050, 0xc82000e190)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8211466a0, 0xc820772000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/astaxie/beego/grace.(*graceConn).Read(0xc820374320, 0xc820772000, 0x1000, 0x1000, 0xa14600, 0x0, 0x0)
	<autogenerated>:16 +0x82
net/http.(*liveSwitchReader).Read(0xc8218481a8, 0xc820772000, 0x1000, 0x1000, 0x1513, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc820374340, 0xc820772000, 0x1000, 0x1000, 0xa1cca0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8210edda0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8210edda0, 0xc81ff9ce0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8210edda0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8214403c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8214403c0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc8210edda0, 0xc820c62e00, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc821848160, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc821848160)
	/usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 42451 [runnable]:
text/template/parse.lexText(0xc820015480, 0xb24340)
	/usr/local/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc820015480)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 42452 [runnable]:
text/template/parse.lexText(0xc820014100, 0xb24340)
	/usr/local/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc820014100)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 40124 [IO wait]:
net.runtime_pollWait(0x7fce54c9fc20, 0x72, 0xc82000e190)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820e155d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820e155d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820e15570, 0xc820bc0000, 0x1000, 0x1000, 0x0, 0x7fce54c92050, 0xc82000e190)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82122e9b0, 0xc820bc0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/astaxie/beego/grace.(*graceConn).Read(0xc821deade0, 0xc820bc0000, 0x1000, 0x1000, 0xc81ff308e9, 0x0, 0x0)
	<autogenerated>:16 +0x82
net/http.(*liveSwitchReader).Read(0xc8219ee1a8, 0xc820bc0000, 0x1000, 0x1000, 0xb0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc821deae00, 0xc820bc0000, 0x1000, 0x1000, 0xa1cca0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc821a8f860)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc821a8f860, 0xc81ff9ce0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc821a8f860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc82101ffb0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc82101ffb0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc821a8f860, 0xc820c63260, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8219ee160, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8219ee160)
	/usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
</pre>

在并发量很低的时候不会出现这个问题，麻烦作者看下这个问题。

**Comment by ElvizLai** [comment]
+1 不过这个问题好像是因为wg导致的。hup的时候，wg的计数异常了。我也遇到过，但是暂时没时间排查这个问题。就暂时弃用graceful了。

**Comment by lipengfeihb** [comment]
自己写热升级？还是采用什么方式？

**Comment by lipengfeihb** [comment]
@ElvizLai 那你采用什么方式来实现热升级？

**Comment by ElvizLai** [comment]
@astaxie 这个bug难道是由 http: multiple response.WriteHeader calls 导致的？

**Comment by astaxie** [comment]
看不出来问题在哪里，我这边测试了最简单的bee api bapi，我压测都没问题

**Comment by lipengfeihb** [comment]
@astaxie 会不会跟我用了第三方的包有关系，比如seelog？

**Comment by Icedroid** [comment]
+1

```
panic: ./restful flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc820018540, 0x7f4733cbdaf8, 0x1182a25, 0xd673b0, 0x8, 0xe1a1e0, 0x21)
	/usr/local/go/src/flag/flag.go:776 +0x46b
flag.BoolVar(0x1182a25, 0xd673b0, 0x8, 0x0, 0xe1a1e0, 0x21)
	/usr/local/go/src/flag/flag.go:555 +0x8a
project/restful/Godeps/_workspace/src/github.com/astaxie/beego/grace.init.1()
	/home/ice/Dropbox/mygo/src/project/restful/Godeps/_workspace/src/github.com/astaxie/beego/grace/grace.go:82 +0x86
project/restful/Godeps/_workspace/src/github.com/astaxie/beego/grace.init()
	/home/ice/Dropbox/mygo/src/project/restful/Godeps/_workspace/src/github.com/astaxie/beego/grace/server.go:292 +0x7c
project/restful/Godeps/_workspace/src/github.com/astaxie/beego.init()
	/home/ice/Dropbox/mygo/src/project/restful/Godeps/_workspace/src/github.com/astaxie/beego/tree.go:554 +0x6a
main.init()
	/home/ice/Dropbox/mygo/src/project/restful/main.go:80 +0x54

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

```

**Comment by astaxie** [comment]
@Icedroid 你的问题核这个有关系吗？好像你的报错和这个没关系啊。 你的错误是`flag redefined: graceful`

**Comment by Icedroid** [comment]
@astaxie 我这个应该是跟Godeps的依赖有关，我删除Godeps目录后，再用bee run运行就没这个问题了。

**Comment by coseyo** [comment]
+1

```
panic: sync: negative WaitGroup counter

goroutine 207 [running]:
sync.(*WaitGroup).Add(0xc2080baf28, 0xffffffffffffffff)
        c:/go/src/sync/waitgroup.go:67 +0x96
sync.(*WaitGroup).Done(0xc2080baf28)
        c:/go/src/sync/waitgroup.go:85 +0x31
github.com/astaxie/beego/grace.graceConn.Close(0x7f31dbcf0670, 0xc20809a018, 0xc2080baf00, 0x0, 0x0)
        F:/gopath/src/github.com/astaxie/beego/grace/conn.go:11 +0x46
github.com/astaxie/beego/grace.(*graceConn).Close(0xc20819e000, 0x0, 0x0)
        <autogenerated>:22 +0xb3
net/http.(*conn).close(0xc20805e140)
        c:/go/src/net/http/server.go:1071 +0x50
net/http.func路011()
        c:/go/src/net/http/server.go:1134 +0x27b
net/http.(*conn).serve(0xc20805e140)
        c:/go/src/net/http/server.go:1217 +0x809
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1751 +0x35e

goroutine 1 [chan receive, 14387 minutes]:
github.com/astaxie/beego.(*App).Run(0xc20800a4b0)
        F:/gopath/src/github.com/astaxie/beego/app.go:171 +0x363
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
        F:/gopath/src/github.com/astaxie/beego/beego.go:277 +0x17c
main.main()
        F:/wps_web/goapp/doc88_preview/trunk/src/doc88_preview/main.go:14 +0x138

goroutine 5 [syscall, 14389 minutes]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init路1
        c:/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [IO wait, 5 minutes]:
net.(*pollDesc).Wait(0xc20815c060, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20815c060, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20815c000, 0x0, 0x7f31dbcefe30, 0xc20816ca30)
        c:/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20809a000, 0x7f31dbcf8b08, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/astaxie/beego/grace.(*graceListener).Accept(0xc20815e180, 0x0, 0x0, 0x0, 0x0)
        F:/gopath/src/github.com/astaxie/beego/grace/listener.go:32 +0x83
net/http.(*Server).Serve(0xc2080ba0c0, 0x7f31dbcf8b40, 0xc20815e180, 0x0, 0x0)
        c:/go/src/net/http/server.go:1728 +0x92
github.com/astaxie/beego/grace.(*graceServer).Serve(0xc2080baf00, 0x0, 0x0)
        F:/gopath/src/github.com/astaxie/beego/grace/server.go:35 +0x62
github.com/astaxie/beego/grace.(*graceServer).ListenAndServe(0xc2080baf00, 0x0, 0x0)
        F:/gopath/src/github.com/astaxie/beego/grace/server.go:74 +0x4e4
github.com/astaxie/beego.func路003()
        F:/gopath/src/github.com/astaxie/beego/app.go:109 +0xf8
created by github.com/astaxie/beego.(*App).Run
        F:/gopath/src/github.com/astaxie/beego/app.go:115 +0x95c
```

**Comment by grsmv** [comment]
Just investigated and fixed this issue locally. Cause of the problem (in my case) - Godep. It can save dependencies to `Godeps` folder and overwrite `import` block. So I had two types of links to `beego` lib - placed in Godeps and in standard place for Go libs. And I've catch this issue as long as beego lib was in separate places. `godep save -r ./...` fixed an issue

**Comment by lei-cao** [comment]
@lipengfeihb Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
@alvin-li @ElvizLai when will that happen? after run `kill -HUP pid`?  As there's two wg.Done()

1. https://github.com/astaxie/beego/blob/master/grace/server.go#L242
2. https://github.com/astaxie/beego/blob/master/grace/conn.go#L11

So if there's conn it looks like still server for the timeout connection.
