### ISSUE TITLE
smtp 日志 配置解析

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [astaxie/beego#1337]
![fa1o g4_mmrm3 qqy1 ulmb](https://cloud.githubusercontent.com/assets/1595118/9611693/b0d100e6-5113-11e5-84df-1dcdd5497961.jpg)
看图说话

![19bc0ad842db14ba64c898614017ec49](https://cloud.githubusercontent.com/assets/1595118/9611793/5110458a-5114-11e5-829d-8ffd57533d70.png)
配置了subject和tos没用，邮件详情里看不到。。。但是我还是收到邮件了。。。好奇怪

**Comment by lei-cao** [comment]
@Mint-Zhao-Chiu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
fix in develop branch
