### ISSUE TITLE
utils的smtp中文乱码

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [astaxie/beego#1338]
两个问题：
from的地址解析：“xxx <aa@bb.com>”，其中 xxx 不能是中文，否则直接出错

subject 不能有中文，否则乱码

上图：
![a7fe7294b25c8e489473489630af6eb0](https://cloud.githubusercontent.com/assets/1595118/9611912/1d4b1c92-5115-11e5-87e8-8679f5563876.png)

**Comment by lei-cao** [comment]
@Mint-Zhao-Chiu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by miraclesu** [comment]
@Mint-Zhao-Chiu 你说的标题有中文就会出现乱码这个问题我这边重现不了，你能提供一个能重现这个问题的代码，并说明你使用的系统平台，go 版本？
谢谢

**Comment by astaxie** [comment]
@miraclesu I think this is the title fixed. https://gist.github.com/andelf/5004821
