### ISSUE TITLE
orm的default问题

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [astaxie/beego#1339]
我设置了一个字段类型：text，未设置default
报错：Error 1101: BLOB/TEXT column 'xxx' can't have a default value

**Comment by roryblucky** [comment]
遇到同样问题 'orm:type(text)' mysql

**Comment by lei-cao** [comment]
@Mint-Zhao-Chiu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@roryblucky  @Mint-Zhao-Chiu  does this solve your issue ?
https://github.com/astaxie/beego/issues/1313

@astaxie  duplicated

**Comment by roryblucky** [comment]
@lei-cao Thanks for your response, I have solved this issue as I checked the #1313 issue. Thanks.
