### ISSUE TITLE
1.4.2版本内存一直涨

### ISSUE THREAD

**Issue by lvshuchengyin** [astaxie/beego#1346]
VERSION = "1.4.2"

压力测试时发现内存一直涨，然后直接在controller里面Get方法的开头直接return，然后用压力测试工具去访问，结果发现内存一直涨，停了压力测试工具，内存也没有降下来，请问是否是这个版本的bug？

**Comment by astaxie** [comment]
内存一直涨你看看是不是你的代码里面内存泄露了？或者你使用go pprof查看一下内存使用量

**Comment by lvshuchengyin** [comment]
@astaxie 
代码里面已经精简到只有一个controller，里面的Get方法直接return，没有其它多余代码了

**Comment by astaxie** [comment]
压力测试的情况下内存增长肯定是正确的，只是你说的内存没有降下来，在Go内部是不会立马释放的，同时最好看一下go pprof看一下是不是有内存泄露

**Comment by lvshuchengyin** [comment]
是因为之前配置那里添加了memory的session，去掉后内存就不会中涨了，非常感谢

**Comment by astaxie** [comment]
解决了就好，赞
