### ISSUE TITLE
ORM time.Time read value does not match what's written before

### ISSUE THREAD

**Issue by kr15h** [astaxie/beego#1352]
I have a model definition that looks like the following.

```
type MyModel struct {
    MyTime time.Time
}
```

I prepare the model for insertion into the database.

```
mm := MyModel{}
mm.MyTime = time.Now()
```

I then write it to the database using `orm.Insert(&mm)`. When I read it back using `orm.Read()`, I got different `MyTime` value.

```
MyTime before: 2015-09-09 00:00:00 +0000 UTC
MyTime after: 2015-09-09 00:00:00 +0200 CEST
```

In the database the `my_time` field value is `2015-09-09 00:00:00`. Am I doing something wrong?

**Comment by Hepri** [comment]
Is your column type in database is timestamp with timezone? I have a feeling that database lose timezone information, and when you retrieve record, some local timezone assigned.

**Comment by kr15h** [comment]
Thanks for your answer, @Hepri ! I have a datetime field. And probably without timezone.

**Comment by kr15h** [comment]
It actually happens when using timestamp as database field type. Does MySQL have a timestamp with timezone as field type?

**Comment by Hepri** [comment]
No, it stores timestamp without zone information, but convert timestamp in UTC. Try to change database global timezone to UTC, could help

**Comment by kr15h** [comment]
That could work...

**Comment by astaxie** [comment]
http://beego.me/docs/mvc/model/orm.md#%E6%97%B6%E5%8C%BA%E8%AE%BE%E7%BD%AE

**Comment by astaxie** [comment]
When use go-sql-driver driver，please attention your DSN config.
From a version of go-sql-driver default use utc timezone not local. So if you use another timezone, please set it.
eg: root:root@/orm_test?charset=utf8&loc=Asia%2FShanghai
ref: loc / parseTime

**Comment by kr15h** [comment]
Thanks @astaxie

**Comment by kr15h** [comment]
Yes, this works. For me go did complain about the `%2F` part. The following workaround worked:

```
// Get the correct query escape string
loc := url.QueryEscape("Europe/Berlin")
mysqlConnString := fmt.Sprintf("root:root@/orm_test?charset=utf8&loc=%s", loc)
// And then later
orm.RegisterDataBase("default", "mysql", mysqlConnString)
```
