### ISSUE TITLE
panic: interface conversion: ast.Expr is *ast.Ident, not *ast.StarExpr

### ISSUE THREAD

**Issue by dvwallin** [astaxie/beego#1353]
Suddenly, out of no where this error occurred. It all worked last night and now, without me changing anything, it wont run anymore. Complains about row 80 in the parser. Got a project launch on monday so getting desperate here.

formservice_git.1 | panic: interface conversion: ast.Expr is *ast.Ident, not *ast.StarExpr
formservice_git.1 | 
formservice_git.1 | goroutine 1 [running]:
formservice_git.1 | github.com/astaxie/beego.parserPkg(0xc208086690, 0x43, 0xb495b0, 0x37, 0x0, 0x0)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/parser.go:80 +0x613
formservice_git.1 | github.com/astaxie/beego.(*ControllerRegistor).Include(0xc2080546e0, 0xc20800b620, 0x1, 0x1)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/parser.go:80 +0x613                                                                                                                                                                                 [67/1925]
formservice_git.1 | github.com/astaxie/beego.(*ControllerRegistor).Include(0xc2080546e0, 0xc20800b620, 0x1, 0x1)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/router.go:224 +0x5bb
formservice_git.1 | github.com/astaxie/beego.(*Namespace).Include(0xc208054700, 0xc20800b620, 0x1, 0x1, 0xc208054700)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/namespace.go:185 +0x4a
formservice_git.1 | github.com/astaxie/beego.func·010(0xc208054700)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/namespace.go:302 +0x3a
formservice_git.1 | github.com/astaxie/beego.NewNamespace(0xa4fc30, 0x6, 0xc208056090, 0x1, 0x1, 0x40e319)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/namespace.go:41 +0x1b1
formservice_git.1 | github.com/astaxie/beego.func·022(0xc2080546c0)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/namespace.go:386 +0x43
formservice_git.1 | github.com/astaxie/beego.NewNamespace(0xa4fbb0, 0x7, 0xc20815ff48, 0x7, 0x7, 0x1)
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/namespace.go:41 +0x1b1
formservice_git.1 | bitbucket.org/GX/formservice.git/routers.init·2()
formservice_git.1 |       /gopath/src/bitbucket.org/GX/formservice.git/routers/router.go:40 +0xa23
formservice_git.1 | bitbucket.org/GX/formservice.git/routers.init()
formservice_git.1 |       /gopath/src/bitbucket.org/GX/formservice.git/routers/router.go:48 +0x60
formservice_git.1 | main.init()
formservice_git.1 |       /gopath/src/bitbucket.org/GX/formservice.git/main.go:41 +0x47
formservice_git.1 | 
formservice_git.1 | goroutine 5 [syscall]:
formservice_git.1 | os/signal.loop()
formservice_git.1 |       /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
formservice_git.1 | created by os/signal.init·1
formservice_git.1 |       /usr/local/go/src/os/signal/signal_unix.go:27 +0x35
formservice_git.1 | 
formservice_git.1 | goroutine 6 [sleep]:
formservice_git.1 | gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc2080c8000)
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/cluster.go:366 +0x291
formservice_git.1 | created by gopkg.in/mgo%2ev2.newCluster
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/cluster.go:76 +0x20b
formservice_git.1 | 
formservice_git.1 | goroutine 7 [IO wait]:
formservice_git.1 | net.(*pollDesc).Wait(0xc208010300, 0x72, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
formservice_git.1 | net.(*pollDesc).WaitRead(0xc208010300, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc2080102a0, 0xc2080840c0, 0x24, 0x24, 0x0, 0x7feb27cc6e50, 0xc2080b6ca8)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208056038, 0xc2080840c0, 0x24, 0x24, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | gopkg.in/mgo%2ev2.fill(0x7feb27cc8868, 0xc208056038, 0xc2080840c0, 0x24, 0x24, 0x0, 0x0)
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/socket.go:504 +0x75
formservice_git.1 | gopkg.in/mgo%2ev2.(*mongoSocket).readLoop(0xc2080502a0)
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/socket.go:521 +0x126
formservice_git.1 | created by gopkg.in/mgo%2ev2.newSocket
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/socket.go:168 +0x3d3
formservice_git.1 | 
formservice_git.1 | goroutine 49 [syscall, locked to thread]:
formservice_git.1 | runtime.goexit()
formservice_git.1 |       /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
formservice_git.1 | 
formservice_git.1 | goroutine 18 [sleep]:
formservice_git.1 | gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc2080500e0, 0x1)
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/server.go:297 +0x169
formservice_git.1 | created by gopkg.in/mgo%2ev2.newServer
formservice_git.1 |       /gopath/src/gopkg.in/mgo.v2/server.go:90 +0x196
formservice_git.1 | 
formservice_git.1 | goroutine 9 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).deliverMsgs(0xc20815a000, 0xc2081105a0)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:968 +0xa6
formservice_git.1 | created by github.com/apcera/nats.(*Conn).subscribe
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1282 +0x291
formservice_git.1 | 
formservice_git.1 | goroutine 35 [IO wait]:
formservice_git.1 | net.(*pollDesc).Wait(0xc208162060, 0x72, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
formservice_git.1 | net.(*pollDesc).WaitRead(0xc208162060, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*pollDesc).WaitRead(0xc208162060, 0x0, 0x0)                                                                                                                                                                                                [0/1925]
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc208162000, 0xc208180000, 0x8000, 0x8000, 0x0, 0x7feb27cc6e50, 0xc20813c000)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208056020, 0xc208180000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | github.com/apcera/nats.(*Conn).readLoop(0xc208063000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:941 +0x292
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:464 +0x6a
formservice_git.1 | 
formservice_git.1 | goroutine 36 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).flusher(0xc208063000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1063 +0x7b
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:465 +0x84
formservice_git.1 | 
formservice_git.1 | goroutine 54 [select]:
formservice_git.1 | github.com/astaxie/beego/toolbox.run()
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/toolbox/task.go:413 +0x697
formservice_git.1 | created by github.com/astaxie/beego/toolbox.StartTask
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/toolbox/task.go:393 +0x2c
formservice_git.1 | 
formservice_git.1 | goroutine 52 [IO wait]:
formservice_git.1 | net.(*pollDesc).Wait(0xc2081400d0, 0x72, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
formservice_git.1 | net.(*pollDesc).WaitRead(0xc2081400d0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc208140070, 0xcformservice_git.1 | net.(*pollDesc).WaitRead(0xc208162060, 0x0, 0x0)                                                                                                                                                                                                [0/1925]
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc208162000, 0xc208180000, 0x8000, 0x8000, 0x0, 0x7feb27cc6e50, 0xc20813c000)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208056020, 0xc208180000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | github.com/apcera/nats.(*Conn).readLoop(0xc208063000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:941 +0x292
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:464 +0x6a
formservice_git.1 | 
formservice_git.1 | goroutine 36 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).flusher(0xc208063000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1063 +0x7b
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:465 +0x84
formservice_git.1 | 
formservice_git.1 | goroutine 54 [select]:
formservice_git.1 | github.com/astaxie/beego/toolbox.run()
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/toolbox/task.go:413 +0x697
formservice_git.1 | created by github.com/astaxie/beego/toolbox.StartTask
formservice_git.1 |       /gopath/src/github.com/astaxie/beego/toolbox/task.go:393 +0x2c
formservice_git.1 | 
formservice_git.1 | goroutine 52 [IO wait]:
formservice_git.1 | net.(*pollDesc).Wait(0xc2081400d0, 0x72, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
formservice_git.1 | net.(*pollDesc).WaitRead(0xc2081400d0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc208140070, 0xc20819e000, 0x8000, 0x8000, 0x0, 0x7feb27cc6e50, 0xc20813c6a0)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208112018, 0xc20819e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | github.com/apcera/nats.(*Conn).readLoop(0xc20815a000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:941 +0x292
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:464 +0x6a
formservice_git.1 | 
formservice_git.1 | goroutine 53 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).flusher(0xc20815a000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1063 +0x7b
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:465 +0x84
formservice_git.1 | 
formservice_git.1 | goroutine 37 [IO wait]:
formservice_git.1 | net.(*pollDesc).Wait(0xc208140370, 0x72, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
formservice_git.1 | net.(*pollDesc).WaitRead(0xc208140370, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc208140310, 0xc20822e000, 0x8000, 0x8000, 0x0, 0x7feb27cc6e50, 0xc20800a740)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208112030, 0xc20822e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | github.com/apcera/nats.(*Conn).readLoop(0xc20815a400)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:941 +0x292
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:464 +0x6a
formservice_git.1 | 
formservice_git.1 | goroutine 38 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).flusher(0xc20815a400)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1063 +0x7b
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:465 +0x84
20819e000, 0x8000, 0x8000, 0x0, 0x7feb27cc6e50, 0xc20813c6a0)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208112018, 0xc20819e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | github.com/apcera/nats.(*Conn).readLoop(0xc20815a000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:941 +0x292
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:464 +0x6a
formservice_git.1 | 
formservice_git.1 | goroutine 53 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).flusher(0xc20815a000)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1063 +0x7b
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:465 +0x84
formservice_git.1 | 
formservice_git.1 | goroutine 37 [IO wait]:
formservice_git.1 | net.(*pollDesc).Wait(0xc208140370, 0x72, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
formservice_git.1 | net.(*pollDesc).WaitRead(0xc208140370, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
formservice_git.1 | net.(*netFD).Read(0xc208140310, 0xc20822e000, 0x8000, 0x8000, 0x0, 0x7feb27cc6e50, 0xc20800a740)
formservice_git.1 |       /usr/local/go/src/net/fd_unix.go:242 +0x40f
formservice_git.1 | net.(*conn).Read(0xc208112030, 0xc20822e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
formservice_git.1 |       /usr/local/go/src/net/net.go:121 +0xdc
formservice_git.1 | github.com/apcera/nats.(*Conn).readLoop(0xc20815a400)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:941 +0x292
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:464 +0x6a
formservice_git.1 | 
formservice_git.1 | goroutine 38 [chan receive]:
formservice_git.1 | github.com/apcera/nats.(*Conn).flusher(0xc20815a400)
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:1063 +0x7b
formservice_git.1 | created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
formservice_git.1 |       /gopath/src/github.com/apcera/nats/nats.go:465 +0x84

**Comment by astaxie** [comment]
fixed in develop branch
