### ISSUE TITLE
parserPkg can cause runtime panic.

### ISSUE THREAD

**Issue by e-dard** [astaxie/beego#1354]
[parserPkg](https://github.com/astaxie/beego/blob/8f7246e17b504c858592a28a87e96fa7537a5aaf/parser.go#L80) has a nasty call in it, where it's both failing to do a length check on `List`, and also not using the `v, ok :=` idiom for a type assertion on `specDecl.Recv.List[0].Type`.

According to [this comment](https://github.com/golang/go/issues/11271#issuecomment-113279206), it's the responsibility of callers to check the length of slices when consuming an AST.

**Comment by astaxie** [comment]
already fixed in develop branch.

**Comment by astaxie** [comment]
https://github.com/astaxie/beego/blob/develop/parser.go#L80-L83
