### ISSUE TITLE
bee无法执行的问题

### ISSUE THREAD

**Issue by daotianya** [astaxie/beego#1358]
go bee 在mac（ /Users/apple PS 当时我在go get 的时候就是在这个目录进行的）目录能访问,但是在gopath下no found bee
当我在/Users/apple 路径下执行 bee，是有Bee is a tool for managing beego framework.这个信息的；
当我执行go的时候是有Go is a tool for managing Go source code.相关安装信息的；
当我执行go env的信息是
apples-MacBook-Pro:~ carlos$ go env
GOARCH="amd64"
GOBIN="$/usr/local/go/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/Documents/gostud"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
TERM="dumb"
CC="clang"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fno-common"
CXX="clang++"
CGO_ENABLED="1"
但是根据教程我要cd $GOPATH/src 下面去创建第一个helloworld程序的时候；-bash: $/usr/local/go/bin/bee: No such file or directory;
很疑惑为什么会提示我bin下面的been呢？然后我cd到/usr/local/go/bin目录下，发现没有bee的目录；
这时候我执行 bee version
bee :1.3.0
beego :you don't install beego,install first: github.com/astaxie/beego
Go :go version go1.2.1 darwin/amd64
系统提示我没有安装beego，很贱的一个动作，我刚刚删除了这个目录！
于是我在/Users/apple目录下执行 go git github.com/astaxie/beego
成功安装了
bee :1.3.0
beego :1.5.0
Go :go version go1.2.1 darwin/amd64
我抱着可能会成功的希望 cd $GOPATH/src 开始执行 bee new helloworld
-bash: $/usr/local/go/bin/bee: No such file or directory
为什么会出现这种问题？
还有个疑问，go git 下来的代码 怎么影藏的这么深呀，是不是这样照成的问题？ /Users/apple/Documents/gostud/src/github.com/astaxie/beego

**Comment by astaxie** [comment]
go get就是获取到了`/Users/apple/Documents/gostud/`下面，bee应该是在`/Users/apple/Documents/gostud/bin`下面，你是不是把这个目录加入到了PATH里面？

**Comment by daotianya** [comment]
谢谢，这个问题已经得到解决，多谢谢大大

**Comment by recalling** [comment]
安装完beego和bee后，但是无法使用bee ，具体信息如下
Bee - v. 1.62 - Bluesoft (2013-2017) - GPL - All rights reserved
usage: bee <options> module:action <parameters>
Options:
 -c <file>   config file
 -d <dir>    bee files directory
Modules:
         schema
         data
         dbchange
         dbseed
         upgrade


求帮忙
