### ISSUE TITLE
beego框架有缺陷???

### ISSUE THREAD

**Issue by zhuimengzhe** [astaxie/beego#1359]
appledeiMac:beeapi apple$ bee run
2015/09/14 16:56:55 [INFO] Uses 'beeapi' as 'appname'
2015/09/14 16:56:55 [INFO] Initializing watcher...
2015/09/14 16:56:55 [TRAC] Directory(/Users/apple/gowork/src/beeapi/controllers)
2015/09/14 16:56:55 [TRAC] Directory(/Users/apple/gowork/src/beeapi)
2015/09/14 16:56:55 [TRAC] Directory(/Users/apple/gowork/src/beeapi/routers)
2015/09/14 16:56:55 [TRAC] Directory(/Users/apple/gowork/src/beeapi/tests)
2015/09/14 16:56:55 [INFO] Start building...
# github.com/astaxie/beego
../github.com/astaxie/beego/router.go:141: not enough arguments in call to reflect.Indirect

这是个什么问题?报错能再详细点吗?

**Comment by yinheli** [comment]
是你的路由配置有问题好么? 贴出来

**Comment by zhuimengzhe** [comment]
我按教程来的使用bee new beeapi,然后进入到cd beeapi,再运行bee run

**Comment by astaxie** [comment]
你的beego很老版本了吧。

bee version看看
