### ISSUE TITLE
关于同时支持http和https的问题

### ISSUE THREAD

**Issue by shuimu98** [astaxie/beego#1362]
我有个一api服务器，想实现部分api使用https，一部分api使用http，请问该怎么设置，我试着搞了下，但是好像只能是：要么全部https，要么所有api都走https和http。有没有满足我需求的更灵活的设置？

**Comment by astaxie** [comment]
这个只能全部开https和http，然后你对应的写一个FIlter，https的api如果访问到了http就跳转过来，同理http的api也是这样跳转

**Comment by shuimu98** [comment]
今天尝试了下，然后想了另外一个方法，可以用beego写两个server，一个专门处理https的api，一个用来处理http的api，不知道是否可行，或者说有没有这种做法？
