### ISSUE TITLE
func (w *FileLogWriter) DoRotate() error

### ISSUE THREAD

**Issue by funnywwh** [astaxie/beego#1363]
当日志文件满后，重命名日志文件会返回，文件正在打开中！
估计如下函数没有加锁导致！
// destroy file logger, close file writer.
func (w *FileLogWriter) Destroy() {
	w.mw.fd.Close()
}

// flush file logger.
// there are no buffering messages in file logger in memory.
// flush file means sync file from disk.
func (w *FileLogWriter) Flush() {
	w.mw.fd.Sync()
}

**Comment by astaxie** [comment]
什么系统？我在Linux和Mac下面没有问题

**Comment by funnywwh** [comment]
window2008.我更新到最新的代码看一下有没有此问题。换了代码后在window7上测试还没有遇到。
我再多测试！有问题再说。谢谢您的支持。
