### ISSUE TITLE
Cannot set response header in Errorhandler func?

### ISSUE THREAD

**Issue by lon-yang** [astaxie/beego#1370]
func ErrorHandler(rw http.ResponseWriter, r *http.Request) {	
		obj := map[string]interface{}{
			"statusCode": context.Get(r, "statusCode"),
			"error":      context.Get(r, "error"),
		}
		objStr, _ := json.Marshal(obj)
		rw.Header().Set("Content-Type", "application/json")
		rw.Write(objStr)
	}

I had used `rw.Header().Set()`.But the real response's content type is text/plain.How should i do?

**Comment by astaxie** [comment]
what's your beego version?

**Comment by lon-yang** [comment]
The lastest version.

**Comment by astaxie** [comment]
bee version

**Comment by lon-yang** [comment]
I don's use this tool

**Comment by astaxie** [comment]
how did you use the `ErrorHandler`?

**Comment by lon-yang** [comment]
like this `beego.Errorhandler("error", errorHandler)`.  And use `this.Abort("error")` in controller.

**Comment by lon-yang** [comment]
I use my notebook to run the same code and the result is correct. I think it's my computer's problem with my company. I will try it in tuesday.Thanks a lot.

**Comment by astaxie** [comment]
Maybe the beego version is 1.4.2 in your company

**Comment by lon-yang** [comment]
I will check it.
