### ISSUE TITLE
orm查询相关的问题

### ISSUE THREAD

**Issue by qAison** [astaxie/beego#1371]
感谢 谢大 开发的 beego 框架，反馈几个使用上遇到的问题

问题1： 使用 orm.NewOrm().Raw 原生 SQL 查询时，外键 字段 无值，为 nil
例如：下面两张表
type App struct {
    Id         uint      `orm:"auto;pk"`
    Name       string    `orm:"size(100);unique"`
    CreateTime time.Time `orm:"auto_now_add;type(datetime)"`
}

type AppPerm struct {
    Id         uint      `orm:"auto;pk"`
    App        *App      `orm:"column(app_id);rel(fk)"`
    Name       string    `orm:"size(100)"`
    CreateTime time.Time `orm:"auto_now_add;type(datetime)"`
}

perm := AppPerm{}
orm.NewOrm().Raw("SELECT * FROM app_perm WHERE id=?", 1).QueryRow(&perm)
查询后 perm.App 为 nil 值，不正常

而使用 QueryTable 查询却正常
orm.NewOrm(). QueryTable(perm).Filter("id", 1).One(&perm)

源码里是否没对 struct 类型字段设值
orm/orm_raw.go   344 行 QueryRow 函数 | 481 行 QueryRows 函数 , 里的
342 if fi := sMi.fields.GetByColumn(col); fi != nil {
343     value := reflect.ValueOf(columnsMp[col]).Elem().Interface()
344    o.setFieldValue(ind.FieldByIndex([]int{fi.fieldIndex}), value)
345 }

临时解决：
if fi := sMi.fields.GetByColumn(col); fi != nil {
    value := reflect.ValueOf(columnsMp[col]).Elem().Interface()
    field := ind.FieldByIndex([]int{fi.fieldIndex})
    if fi.fieldType&IsRelField > 0 { // field is struct
        mf := reflect.New(fi.relModelInfo.addrField.Elem().Type())    // make field value
        field.Set(mf)                                                 // set new value
        field = mf.Elem().Field(fi.relModelInfo.fields.pk.fieldIndex) // get real field
    }
    o.setFieldValue(field, value)
}

问题2：QueryTable 查询条件为 时间 类型时格式化的问题
orm/db_utils.go    75 行  getFlatParams 函数 case 逻辑部分，对时间类型字段查询做了相应的处理
那么这样查询时，时间将会被填充格式化为 %2015-03-01 00:00:00%
orm.NewOrm().QueryTable(perm).Filter("create_time__icontains", "2015-03-01 15").Limit(1).One(&perm)

无法跟使用 原生 SQL 查询达到一致
orm.NewOrm().Raw("SELECT * FROM app_perm WHERE create_time LIKE ? limit 1", "%2015-03-01 15%").QueryRow(&perm)

**Comment by lei-cao** [comment]
@qAison Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
