### ISSUE TITLE
静态文件处理 index.html 的问题

### ISSUE THREAD

**Issue by qAison** [astaxie/beego#1372]
例如，设置 beego.SetStaticPath("/ui", "ui") 后
访问 /ui/index.html 后会被 301 跳转，然后 403 

源码 beego\staticfile.go 75 行 if 逻辑部分
76    file := path.Join(staticDir, requestPath) // 路径连接有问题
77    if utils.FileExists(file) {
78        http.ServeFile(ctx.ResponseWriter, ctx.Request, file)  // http.ServeFile 处理 index.html 后缀的请求会被 Redirect 到 ./
79        return
80    }

临时解决：
if oFile, err := os.Open(file); err != nil {
    if RunMode == "dev" {
        Warn("Can't open the file:", file, err)
    }
    http.NotFound(ctx.ResponseWriter, ctx.Request)
} else {
    defer oFile.Close()
    http.ServeContent(ctx.ResponseWriter, ctx.Request, file, finfo.ModTime(), oFile)
}
return

**Comment by qAison** [comment]
更正下
访问 /ui/index.html 后会被 301 跳转，然后 403

**Comment by lei-cao** [comment]
@aAison Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
