### ISSUE TITLE
Windows 下 静态目录 未处理 ..\ 导致安全问题

### ISSUE THREAD

**Issue by qAison** [astaxie/beego#1373]
Windows 下 静态目录 未处理 ..\ 导致安全问题

例如，设置 这样的静态目录后
beego.SetStaticPath("/ui", "ui")

能读取任意目录文件，将导致数据泄露
curl  "http://127.0.0.1/ui/1212/../..\conf\app.conf"

默认 static 是开启的，意味着没设置静态目录的也有问题的
curl "http://127.0.0.1/static/xxx/../..\conf\app.conf"

**Comment by astaxie** [comment]
已经fix
