### ISSUE TITLE
Session丢失的问题

### ISSUE THREAD

**Issue by qzyuanmu** [astaxie/beego#1374]
beego.SessionProvider = "file"
beego.SessionSavePath = "./tmp"
如上配置，页面多刷新几次，session就丢失了

**Comment by astaxie** [comment]
我也是这样配置啊，bee new创建，没有出现这种情况啊

**Comment by qzyuanmu** [comment]
v ,ok:=   ctx.Input.Session("UserName").(string)
    fmt.Printf("v:------",v)
如上代码获取，出现下图错误
![12](https://cloud.githubusercontent.com/assets/10859110/9983705/cbc5177c-6039-11e5-9a3a-f09807e344fb.png)

**Comment by astaxie** [comment]
你的beego什么版本啊？看上去好像是静态文件请求引起了session失效

**Comment by qzyuanmu** [comment]
![11](https://cloud.githubusercontent.com/assets/10859110/9986412/d7ea1482-606e-11e5-83b1-8791274191bb.jpg)

**Comment by astaxie** [comment]
这个看上去好像是IE里面的cookie没有设置成功引起的。不是很清楚root cause

**Comment by lei-cao** [comment]
@qzyuanmu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by qzyuanmu** [comment]
我认为普及一下中文也是极好的
