### ISSUE TITLE
cache 内存缓存 判断是否存在的bug

### ISSUE THREAD

**Issue by mohong122** [astaxie/beego#1375]
是用IsExist返回的结果为true，但通过Get获取的数据为空

cache.NewCache("memory", `{"interval":60}`)

大概出现空数据为60秒

**Comment by astaxie** [comment]
没看明白你的描述信息

**Comment by mohong122** [comment]
```go
bm,_:= cache.NewCache("memory",{"interval":60})
str := ""
if !bm.IsExist("Cache"){
    str ="Cache"
    bm.Put("Cache",str,10)
}else{
    str=bm.Get("Cache")
}


str 会循环出现为空的情况,周期时长为60s

**Comment by nkbai** [comment]
这个问题我也提了,不应该在get的时候清理cache,这样给人的误导太明显了!

**Comment by lei-cao** [comment]
@mohong122 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie close? duplicated https://github.com/astaxie/beego/issues/1375
