### ISSUE TITLE
使用bee创建工程时配置添加注释

### ISSUE THREAD

**Issue by JessonChan** [astaxie/beego#1377]
在使用bee创建工程时，对于创建的app.conf文件，可以尝试添加默认的配置的注释，能更容易的看懂的配置文件，比如nginx等工程的配置。
下图为zsh的配置  
![image](https://cloud.githubusercontent.com/assets/707691/10011968/0d5a2b54-6135-11e5-9af9-ad4be0cfd846.png)

**Comment by astaxie** [comment]
这个应该是bee的改进，应该提到bee的issue里面去
