### ISSUE TITLE
orm运行update, insert 函数的时候， 有没有选项可以不实际操作，只生成相应的sql？

### ISSUE THREAD

**Issue by flyingfoxlee** [astaxie/beego#1380]
如题，不知道这个可不可以有

**Comment by JessonChan** [comment]
这个需求是什么背景？

**Comment by flyingfoxlee** [comment]
可以把所有sql操作集合到一起来处理

**Comment by JessonChan** [comment]
不太明白，只是想不手动写sql?

**Comment by mikeqian** [comment]
要sql,直接用工具生成就好了，什么curd,abcd一键搞定，干这个框架啥事？

**Comment by lei-cao** [comment]
@flyingfoxlee Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
