### ISSUE TITLE
过滤器的需求

### ISSUE THREAD

**Issue by qzyuanmu** [astaxie/beego#1382]
type FilterFunc func(*context.Context)
是不是传入controller比较好点，因为过滤以后不仅要对客户请求进行操作，有时候也需要对服务端进行操作，如根据过滤器设置相应的session值。

**Comment by astaxie** [comment]
context可以操作session啊

**Comment by qzyuanmu** [comment]
不能设置的吧？

**Comment by qzyuanmu** [comment]
哦，找到了，ctx.Input.CruSession.Set
