### ISSUE TITLE
how do you handle Maps are not safe for concurrent use

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1383]
I read this on https://blog.golang.org/go-maps-in-action

Maps are not safe for concurrent use: it's not defined what happens when you read and write to them simultaneously. If you need to read from and write to a map from concurrently executing goroutines, the accesses must be mediated by some kind of synchronization mechanism. One common way to protect maps is with sync.RWMutex.

but I think beego use it as object to render in view / json. can you explain how to handle this issue in beego?

**Comment by astaxie** [comment]
every request use the init map
