### ISSUE TITLE
vendor directory should be excluded from watching

### ISSUE THREAD

**Issue by AlekSi** [astaxie/beego#1386]
```
[ERRO] Fail to watch directory[too many open files]
```
Happens during `bee run` with `GO15VENDOREXPERIMENT` enabled, with vendored beego and other dependencies.
Probably `bee run` should not watch for changes in `vendor/` when experiment is enabled.

**Comment by AlekSi** [comment]
In other words, `vendor/` should be excluded by default, just like `Godeps/`.

**Comment by astaxie** [comment]
https://github.com/beego/bee/commit/60e4f1b872255d3b78fa6ac08af419a85177c9b1
