### ISSUE TITLE
executeError方法中，是否应该取消WriteHeader？

### ISSUE THREAD

**Issue by tudyzhb** [astaxie/beego#1387]
https://github.com/astaxie/beego/blob/master/error.go#L456
后面的err.handler可能是用户自定义的，而WriteHeader只能运行一次，这直接导致了用户的errHandler无法改写header status code。建议将error.go#L456的WriteHeader移入默认的404,401,403,500 and 503.处理中。

从开发者角度来说，既然我主动注册了Errorhandler，WriteHeader那点操作还是知道的。

**Comment by astaxie** [comment]
develop 分支已经修复这个问题了https://github.com/astaxie/beego/blob/develop/error.go#L414-L418
