### ISSUE TITLE
swagger解析不了struct

### ISSUE THREAD

**Issue by soyking** [astaxie/beego#1390]
我的post参数里面有一条是：
// @Param	body		body 	models.Moment	true		"The moment content"
然后这个Moment一直没有解析出来，就是Data Type中只显示了“Moment”，没有其json形式

但是！如果我在get方法里面的返回这样写：
// @Success 200 {object} models.Moment
那么get返回那里，以及post参数那里就都解析出来了

非常奇怪

**Comment by cartersun** [comment]
我也遇到同样的问题

**Comment by astaxie** [comment]
恩，已知bug

**Comment by lei-cao** [comment]
@soyking Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
