### ISSUE TITLE
I don't see any documentation and tutorial for recursive relationship?

### ISSUE THREAD

**Issue by kyawmyintthein** [astaxie/beego#1391]

**Comment by kyawmyintthein** [comment]
I can't find any direct documentation for "Recursive Relationship". I tried follow code. But, I am not sure for ORM Query.
type Category struct {
	Id          int64  `orm:"auto"`
	Name        string `orm:"size(128)"`
	Description string `orm:"size(128)"`
	Category  *Category `orm:"rel(fk);column(category_id);null"`
        Categories  []*Category `orm:"reverse(many)"`
}

**Comment by astaxie** [comment]
you can try turn on Orm.Debug=true

**Comment by ljesus** [comment]
@astaxie I don't think you answered his question. How can we perform recursive relationships on Beego ORM? I'm having the same issue. Basically I need to specify the name of the column of the FK, but how can I do this? Thank you.
