### ISSUE TITLE
orm.Update问题

### ISSUE THREAD

**Issue by guoxf** [astaxie/beego#1392]
type TestUnique struct {
		Id   int    `orm:"column(Indexid);pk"`
		Ids  int    `orm:"column(id);"`
		Name string `orm:"column(name);size(45)"`
	}
调用orm.Update时，不会更新数据库中id这个字段的值，通过查看源代码发现只要修改orm/models_info_f.go这个文件中有一个GetByAny方法，就可以更新id这个字段（修改后的代码在下面）。想请教下，把GetByAny改成下面这样会不会有其他问题。
	
       // get field info by string, name is prior
	func (f *fields) GetByAny(name string) (*fieldInfo, bool) {
		if fi, ok := f.columns[name]; ok {//这个原来在最下面
			return fi, ok
		}
		if fi, ok := f.fields[name]; ok {
			return fi, ok
		}
		if fi, ok := f.fieldsLow[strings.ToLower(name)]; ok {
			return fi, ok
		}
		return nil, false
	}

**Comment by astaxie** [comment]
因为你Id和哪个column(id)一样了，这样设计的原因是什么？因为默认是fields里面先找到

**Comment by guoxf** [comment]
旧程序的数据库表设计成了这样，为了兼容，所以没改字段名。
