### ISSUE TITLE
FinishRouter and AfterExec do not work

### ISSUE THREAD

**Issue by Rmanolis** [astaxie/beego#1393]
Hi, 

I have a problem with FinishRouter and AfterExec.
They do not execute anything , for any URL
I use go 1.5

**Comment by astaxie** [comment]
can you post you code here or gist. I have no idea on your comments.

**Comment by Rmanolis** [comment]
It does not print after executing the url http://127.0.0.1:8080/
package routers

import (
       "beegorecipes/controllers"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/context"
	"log"
)

func check(ctx *context.Context) {
	log.Println("AAA")
}

func init() {
	beego.InsertFilter("/*", beego.AfterExec, check)
	beego.InsertFilter("/", beego.AfterExec, check)
        beego.Router("/", &controllers.MainCtrl{})
}

**Comment by mikeqian** [comment]
not work +1

**Comment by mikeqian** [comment]
<pre>
// defined filter function
	do_filter := func(pos int) (started bool) {
		if p.enableFilter {
			if l, ok := p.filters[pos]; ok {
				for _, filterR := range l {
					if filterR.returnOnOutput && w.started {
					    return true  // here first check
					}
					if ok, params := filterR.ValidRouter(urlPath); ok {
						for k, v := range params {
							if context.Input.Params == nil {
								context.Input.Params = make(map[string]string)
							}
							context.Input.Params[k] = v
						}
						filterR.filterFunc(context)
					}
					if filterR.returnOnOutput && w.started {
						return true
					}
				}
			}
		}
		return false
	}
</pre>

I check the code and find it just return for the first check before the filterFunc.

**Comment by astaxie** [comment]
beego.InsertFilter("/", beego.AfterExec, check, false)

**Comment by saltab** [comment]
@astaxie can we update the beego documentation what the optional parameters do for the `InsertFilter` method ? please let me know which repo and i can send a PR for the same! thanks 👍

**Comment by astaxie** [comment]
@saltab https://github.com/beego/beedoc
