### ISSUE TITLE
prod模式下，如何不重启程序的情况下重新缓存模板

### ISSUE THREAD

**Issue by anzw** [astaxie/beego#1394]
dev模式下，模板是不做缓存处理的，但在prod模式下做了缓存处理，有没有一种通知机制能够让程序自动加载更新过的模板，或者通过比较文件的修改时间自动重新缓存模板？

**Comment by astaxie** [comment]
目前还没有，因为BeeTemplates是一个map，如果动态更新的话会引起并发的问题，除非加一个锁，但是在dev模式下没有问题是因为只有开发，不会引起错误
