### ISSUE TITLE
how to set unlimited expiry for redis cache

### ISSUE THREAD

**Issue by 29206394** [astaxie/beego#1396]
hi,
set timeout to 0 is valid for memory, file and memcache; but for redis， SETEX is not allowed to set timeout to 0;

Waiting for your comments
Best

**Comment by astaxie** [comment]
redis is not avaiable for unlimited

**Comment by 29206394** [comment]
If only use set, do not set ex, Is equivalent to the effect of unlimited？

**Comment by yadavparveen** [comment]
https://stackoverflow.com/questions/33115325/how-to-set-redis-max-memory
