### ISSUE TITLE
api 自动生成的代码总提示404

### ISSUE THREAD

**Issue by nwaycn** [astaxie/beego#1399]
环境
fedora20
go 1.5.1
beego 1.5
在  bee api abc后，直接用bee build main.go后运行./abc,或用  bee run abc -downdoc=true -docgen=true

 http server Running on 0.0.0.0:8080

然后在另一个窗口中调用 

添加一个对象：

curl -X POST -d '{"Score":1337,"PlayerName":"Sean Plott"}' http://127.0.0.1:8080/object

curl -X GET http://127.0.0.1:8080/object

或
curl -X GET http://127.0.0.1:8080/user

时，全返回为404

**Comment by jacobxk** [comment]
I countered the same issue after upgrade to EI Capitan.

**Comment by astaxie** [comment]
bee build main.go是错误的做法

**Comment by nwaycn** [comment]
bee run abc -downdoc=true -docgen=true  ,这是看的oschina blog上的运行方式，结果也是一样的

**Comment by zhangjie123** [comment]
发生一样的问题，楼主解决了没？全都是404

**Comment by leftwukaixing** [comment]
发生一样的问题，楼主解决了没？全都是404 +1

**Comment by CoderPoet** [comment]
+1

**Comment by atfa** [comment]
一样的问题，还是没解决吗？

**Comment by BigbigY** [comment]
+1

**Comment by yybmsrs** [comment]
bee run一次routers目录下会生成commentsRouter_controllers.go，停止再执行一次就可以了

**Comment by songkang1993** [comment]
![image](https://user-images.githubusercontent.com/38366752/102074862-5af88e80-3e40-11eb-822a-ccf0126af7da.png)
还是404呀。。。
