### ISSUE TITLE
BeeTemplates查找模板方式导致的一个can't find template误报

### ISSUE THREAD

**Issue by Violam** [astaxie/beego#1400]
beego的controller是根据BeeTemplates的map中是否有模板文件来判断。
但貌似模板文件如果有严重的解析错误，是不会被放进BeeTemplates的。（没有仔细去确认代码，所以说貌似）
例如 {{if}}{{end}} ，如果{{end}}没有写上，就会出现问题。
于是，明明目录路径正确，文件名也正确，可是一直报can't find template的错误。
模板复制改名后也是一样，而其他模板却正确无误。
最后发现是模板内容里面一个{{end}}忘了关上。
这个can't find template的panic有够迷惑的。
（补充一下，我用的是layout的方式，没有去测试不用layout有没问题，看代码也是同样用map查找）

**Comment by lei-cao** [comment]
@Violam Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
@Violam in dev mode, there has a warning information about the parse template error.
