### ISSUE TITLE
我在一个应用里，需要多个app实例，各个实例监听不同端口使用不同静态文件路劲，该如何使用？

### ISSUE THREAD

**Issue by JohnSmithX** [astaxie/beego#1405]
beego版本1.5.0使用了一个BeeApp的初始变量，beego接口大部分都是为它服务的。是不是beego1.5.0不再支持多实例应用了

**Comment by astaxie** [comment]
你启动的时候可以传参数，例如
./app -config=app1config
./app -config=app2config
./app -config=app3config

然后在你的app里面解析这个config，用这个config来作为你的服务启动的配置

**Comment by lei-cao** [comment]
@JohnSmithX Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie close? @JohnSmithX is your issue solved?
