### ISSUE TITLE
beego 的 Router 可以识别$符号吗

### ISSUE THREAD

**Issue by zaang** [astaxie/beego#1407]
现在想实现 restapi，但是 url 中的参数如果有 $ 符号就返回 404 了。请问怎么解决呢？

比如：
beego.Router("/restapi/:modelName:string/:entityId:string", &controllers.RestApiController{}, "get:RetrievEntity")

entityId 中有 $ 就取不到了。

**Comment by astaxie** [comment]
`beego.Router("/restapi/:modelName:string/:entityId(.*)", &controllers.RestApiController{}, "get:RetrievEntity")`

**Comment by zaang** [comment]
Thanks!
