### ISSUE TITLE
Models not parse in swagger

### ISSUE THREAD

**Issue by imantung** [astaxie/beego#1408]
models.UserRequest is not generate

```go
// @Title createUser
// @Description create users
// @Param	body		body 	models.UserRequest	true		"body for user content"
// @Success 200 {int} models.UserRequest
// @Failure 403 body is empty
// @router / [post]
func (u *UserController) Post() {

}
```
<img width="962" alt="screen shot 2015-10-27 at 1 20 36 pm" src="https://cloud.githubusercontent.com/assets/570264/10750972/7015e6ae-7cae-11e5-9df3-6b26ec8cb33a.png">

but below code can generate models

```go
// @Title createUser
// @Description create users
// @Param	body		body 	models.UserRequest	true		"body for user content"
// @Success 200 {object} models.UserRequest
// @Failure 403 body is empty
// @router / [post]
func (u *UserController) Post() {

}
```
<img width="960" alt="screen shot 2015-10-27 at 1 22 56 pm" src="https://cloud.githubusercontent.com/assets/570264/10750973/7018d7b0-7cae-11e5-8b7e-2b9fcffeec6b.png">

**Comment by astaxie** [comment]
// @Success 200 {int} models.UserRequest

// @Success 200 {object} models.UserRequest

**Comment by imantung** [comment]
Sorry maybe my issue is not clear. I want different model at @Param and @Success. Model not parse at param. I expect model will be parse like  @Success 200 {object} models.UserRequest.
