### ISSUE TITLE
detect closed the connection

### ISSUE THREAD

**Issue by gebv** [astaxie/beego#1410]
how to detect the client has closed the connection?

**Comment by astaxie** [comment]
ping-pong

**Comment by gebv** [comment]
have a controller with a heavy procedure. i want to receive a notification that the client closed the connection. then I can stop the procedure.
you mean keep-alive timeout?

**Comment by gebv** [comment]
So, my previous post was not competent

``` golang
notify := c.Ctx.ResponseWriter.(http.CloseNotifier).CloseNotify()

	select {
	case <-closeNotify:
		beego.Debug("Client closed request")
		c.Ctx.Output.SetStatus(499)
	case <-time.After(time.Second * 2):
		time.Sleep(time.Second * 2)
		c.Data["json"] = "ok"
		c.ServeJson()
	}
```

i have error

Handler crashed with error interface conversion: *beego.responseWriter is not http.CloseNotifier: missing method CloseNotify

**Comment by gebv** [comment]
https://github.com/astaxie/beego/blob/a89f14d80dab442927bdc11d641aa1250ab8ad71/router.go#L898

Why not use embedding (http.ResponseWriter)?

**Comment by astaxie** [comment]
@gebv good point. I will improve it

**Comment by gebv** [comment]
thx

**Comment by astaxie** [comment]
@gebv I will merged develop branch into master in next two weeks.
