### ISSUE TITLE
能配置监控目录吗? [ERRO] Fail to watch directory[too many open files]

### ISSUE THREAD

**Issue by brainqi1991** [astaxie/beego#1412]
项目依赖包管理,用的Godep,因为Godeps目录的存在,监控说打开的文件太多了,能将Watcher改成可配置的吗?
 mc git:(master) bee run
2015/10/31 15:58:28 [INFO] Uses 'mc' as 'appname'
2015/10/31 15:58:28 [INFO] Initializing watcher...
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/cache)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/cache/memcache)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/cache/redis)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/config)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/config/xml)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/config/yaml)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/context)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/example/beeapi/controllers)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/example/beeapi)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/example/beeapi/models)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/example/chat/controllers)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/example/chat)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/grace)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/httplib)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/logs)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/logs/es)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/middleware)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/migration)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/orm)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/plugins/apiauth)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/plugins/auth)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/plugins/cors)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session/couchbase)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session/ledis)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session/memcache)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session/mysql)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session/postgres)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session/redis)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/session)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/swagger)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/testing)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/toolbox)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/utils)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/utils/captcha)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/utils/pagination)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/astaxie/beego/validation)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/brainqi1991/go-libs/crypto)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/brainqi1991/go.uuid)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/brainqi1991/redis)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/brainqi1991/redis/tools)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/go-sql-driver/mysql)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/go-xorm/core)
2015/10/31 15:58:28 [TRAC] Directory(/Users/brain/projects/go/src/mc/Godeps/_workspace/src/github.com/go-xorm/xorm)
2015/10/31 15:58:28 [ERRO] Fail to watch directory[too many open files]

**Comment by astaxie** [comment]
可以啊，bee help run

bee help run
usage: bee run [appname] [watchall] [-main=*.go] [-downdoc=true]  [-gendoc=true]  [-e=Godeps -e=folderToExclude]

Run command will supervise the file system of the beego project using inotify,
it will recompile and restart the app after any modifications.

**Comment by brainqi1991** [comment]
OK,thanks.

**Comment by qsfty** [comment]
能监控指定的目录下的非go文件吗？比如json, xml

**Comment by pawatzaza** [comment]
hi

**Comment by astaxie** [comment]
@pawatzaza What the fuck are you doing?

**Comment by astaxie** [comment]
@qsfty 可以的，你需要自己配置一个bee.json文件. 详细的格式请参考 https://github.com/beego/bee/blob/master/bee.json

**Comment by pawatzaza** [comment]
false

**Comment by pawatzaza** [comment]
hello

**Comment by pawatzaza** [comment]
bee.json

{
	"version": 0,
	"gopm": {
		"enable": false,
		"install": false
	},
	"go_install": false,
	"watch_ext": [],
	"dir_structure": {
		"watch_all": false,
		"controllers": "",
		"models": "",
		"others": []
	},
	"cmd_args": [],
	"envs": [],
	"database": {
		"driver": "mysql"
	}
}
 Desktop version
