### ISSUE TITLE
cache模块memory.go存在bug

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1420]
以shorturl 为例
if urlcache.IsExist(urlmd5) {
		result.UrlShort = urlcache.Get(urlmd5).(string)
	}
这是一种很平常的用法先检测key存在不,如果存在就获取.
但是这里的设计是在get的时候将过期的key删掉, 导致的结果就是IsExist返回true,但是调用Get的时候得到一个nil.
如果需要删除,在IsExits中删除要合理的多!

**Comment by nkbai** [comment]
建议要么删除IsExist接口,因为get返回空就是不存在,不空就是存在
要么在IsExist里面进行清理工作,减少误解

**Comment by JessonChan** [comment]
@nkbai 
这个建议是没有必要的。
这个函数本身没有必要是线程安全的。

**Comment by lei-cao** [comment]
@nkbai Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie close ? duplicated https://github.com/astaxie/beego/issues/1139
