### ISSUE TITLE
webim 例子中waitingList等全局变量存在潜在冲突问题

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1425]
虽然只是例子,但是希望完善一下,不要误导了初学者,并且错误了还找不到原因.
chatroom.go 中的
	// Long polling waiting list.
	waitingList = list.New()
	subscribers = list.New()
longpolling.go中的
        // Wait for new message(s).
	ch := make(chan bool)
	waitingList.PushBack(ch)
	
这里的PushBack明显存在竞争访问问题,建议对于waitingList以及subscribers访问加锁

**Comment by lei-cao** [comment]
@nkbai Thank you for supporting beego. please update or submit your issue in English For a better international user friendly communication.

**Comment by astaxie** [comment]
webim should move this issue to https://github.com/beego/samples
