### ISSUE TITLE
内存 session 模块，新数据放入链表位置错误

### ISSUE THREAD

**Issue by qAison** [astaxie/beego#1427]
session/sess_mem.go
105 行 SessionRead 函数 和 139 行 SessionRegenerate 函数
element := pder.list.PushBack(newsess)
新数据应该放在链表头部的，因为GC函数是从尾部检查起的，会导致前面过期的Session无法释放
element := pder.list.PushFront(newsess)

https://github.com/astaxie/beego/blob/master/session/sess_mem.go#L105
https://github.com/astaxie/beego/blob/master/session/sess_mem.go#L139
![105](https://cloud.githubusercontent.com/assets/2263875/11148005/f44ea682-8a54-11e5-90da-8a1e245c2a1c.png)
![139](https://cloud.githubusercontent.com/assets/2263875/11148006/f4a077aa-8a54-11e5-872e-1fbd43f3cab0.png)
![162](https://cloud.githubusercontent.com/assets/2263875/11148036/30c5453a-8a55-11e5-87a2-6466573ff0af.png)

**Comment by lei-cao** [comment]
Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
