### ISSUE TITLE
Is Beego still actively being worked on?

### ISSUE THREAD

**Issue by rashthedude** [astaxie/beego#1428]
I was wondering if this project is still well and alive and/or has a future?

**Comment by pjoe** [comment]
Well, I've at least got a couple of PRs merged recently :) Not sure what the plan is for when next release will be done, but the develop branch is very active: https://github.com/astaxie/beego/commits/develop

**Comment by rashthedude** [comment]
thanks @pjoe

**Comment by astaxie** [comment]
it should be very active. :smiley:
