### ISSUE TITLE
Is beego/orm planed to support oracle driver?

### ISSUE THREAD

**Issue by liuhewei** [astaxie/beego#1429]
I've just found this old issue tracker: https://github.com/astaxie/beego/issues/294

Seems mattn's oracle sql driver is good enough now (https://github.com/mattn/go-oci8), I wonder if beego/orm will support oracle in near future, since oracle is very common in production environment.

We are using a simple oracle support implementation with Beego 1.4.2 since last year. Now we are considering to upgrade it if the upstream plans to support oracle officially. We are also happy to commit our simple implementation as an initial version if needed.

**Comment by goldalworming** [comment]
I need this too

**Comment by astaxie** [comment]
@liuhewei As I have no test environment to test the oracal driver. We appreciate if you can send a PR to support this.

**Comment by liuhewei** [comment]
@astaxie Thanks. We'll submit the PR.
cc @tsjsdbd @magicwang-cn

**Comment by goldalworming** [comment]
+1

**Comment by astaxie** [comment]
@liuhewei any updated on this issue? we will release beego 1.6 this week.

**Comment by liuhewei** [comment]
@astaxie Sorry for the late. We're busy on internal project works recently, so I'm afraid this oracle-driver couldn't catch up with beego 1.6. We'll submit as soon as possible. @magicwang-cn

**Comment by TheCrott** [comment]
@astaxie (y)

**Comment by ElvizLai** [comment]
+1

**Comment by astaxie** [comment]
it's already support in beego1.6.1 now

**Comment by giorgiootto** [comment]
Hi , How is the connection with oracle
