### ISSUE TITLE
EnableDocs 设置永远无效问题

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1432]
docs.go 中 EnableDocs ，由于是在init中进行的GlobalDocApi 初始化，导致的结果就是enabledocs这个变量设置其实没有任何意义，无论是我在配置文件中进行的enabledocs设置还是main函数，都是无效的

**Comment by nkbai** [comment]
建议将GlobalDocApi的初始化放在serverDocs中，使用once进行初始化

**Comment by astaxie** [comment]
下个版本可能直接就生成json文件就好了，所有的swagger文件当做静态来做访问

**Comment by lei-cao** [comment]
@nkbai Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
