### ISSUE TITLE
memFileInfo.Name，Mode，IsDir几个 函数自己递归自己问题

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1433]
// Name returns the compressed filename.
func (fi *memFileInfo) Name() string {
	return fi.Name()
}

这个明显是一个错误，要么直接删掉此函数定义，要么改为return fi.FileInfo.Name()

**Comment by lei-cao** [comment]
@nkbai Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@nkbai  is this fixed in https://github.com/astaxie/beego/pull/1440 ?
@astaxie close?
