### ISSUE TITLE
mysql 原生SQL查询总感觉有问题

### ISSUE THREAD

**Issue by 10045125** [astaxie/beego#1435]
.Raw("select id,revision,JSON_EXTRACT(svn_msg_json,'$.REVIEWURL') as reviewurl from svn_log limit ?,?", 2, 20).QueryRows(&reviewURLForDB)

在加上limit后面跟两个参数，这个查寻不到数据，打印err为nil，num＝0，但是当我
.Raw("select id,revision,JSON_EXTRACT(svn_msg_json,'$.REVIEWURL') as reviewurl from svn_log limit 2,20").QueryRows(&reviewURLForDB)
这样就能够查询到数据，beego不能在这么简单的问题的出错吧！望解答。

**Comment by 10045125** [comment]
我目前的解决方法是fmt.Sprintf("select id,revision,JSON_EXTRACT(svn_msg_json,'$.REVIEWURL') as reviewurl from svn_log limit %d,%d", 16, 20)，代替Raw的转换功能。不知道这是不是bug。

**Comment by lei-cao** [comment]
@10045125 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
