### ISSUE TITLE
API doc does not update

### ISSUE THREAD

**Issue by kyawmyintthein** [astaxie/beego#1436]
I use "bee run -gendoc=true" command to run API app. But, it does not update the docs.go file. I trace error in g_docs.go file, I found because of this code.

getModel
ColorLog("can't find the object: %v", str)
os.Exit(1)

When I change the code os.Exit(1) to return. Error fixed. I don't know the exact error. why?

**Comment by astaxie** [comment]
As you have a comment object, and it can't find that object
