### ISSUE TITLE
使用httplib访问服务器，服务器里对提交的beegosessionID每次都变化

### ISSUE THREAD

**Issue by xaseven** [astaxie/beego#1443]
如题，哪里设置不对？
（服务器和客户端都是 用beego，服务器是 RestFUL API Server，客户端是网站）

**Comment by xaseven** [comment]
req.Header("Accept-Encoding", "gzip,deflate,sdch")
				req.Header("Host", "beego.me")
				req.Header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36")

**Comment by lei-cao** [comment]
@xaseven Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
SessionID will be generated everytime when the request has no cookie for beegosessionID. b/s the server side will use this sessionID to fetch the data
