### ISSUE TITLE
该项目目前是否active？

### ISSUE THREAD

**Issue by quchunguang** [astaxie/beego#1444]
好像代码和视频教程很久没有更新了，希望作者继续做下去。
目前是否开发仍然active？
ps：视频教程第一课的百度云链接已经失效，可否更新以下？

**Comment by astaxie** [comment]
请看develop分支，很活跃的更新中

**Comment by astaxie** [comment]
视频我觉得还需要时间来规划，因为我现在又改进了很多东西
