### ISSUE TITLE
使用orm.NewOrm().Raw(...).QueryRows(...)时出现的问题

### ISSUE THREAD

**Issue by sheng** [astaxie/beego#1445]
是这样，我在[beego开发文档](http://beego.me/docs/mvc/model/rawsql.md)的例子中看到beego在使用原生SQL语句的时候拿“?”来做占位符，于是我写了下面两种（已知数据库里有许多`name`字段中包含“王”）：
```go
...
o := orm.NewOrm()
var users, users2 []User

num, _ := o.Raw("select * from user where name like '%王%'").QueryRows(&users)
num2, _ := o.Raw("select * from user where name like'%?%'", "王").QueryRows(&users2)

println(num, num2)
...
```
执行后，`num`不为0，但`num2`为0

**Comment by 10045125** [comment]
原理很简单，用占位符，如果占位符是一个string，然而实际的sql就不是string
people = "eddd"
num2, _ := o.Raw("select * from user where name = ?",people).QueryRows(&users2)
这样的sql就变成 select * from user where name = eddd 这样的语法在sql是错误的。
正确的语法应该是select * from user where name = 'eddd'

我是用这个去解决的
num2, _ := o.Raw(fmt.Sprintf("select * from user where name ='%v'",people)).QueryRows(&users2)

不知道你的问题是不是这个

**Comment by lei-cao** [comment]
@sheng  Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@sheng  is @10045125 's solution work for you?

**Comment by sheng** [comment]
@lei-cao is not working.
