### ISSUE TITLE
orm not process the type `serial` of postgresql

### ISSUE THREAD

**Issue by quchunguang** [astaxie/beego#1447]
I found this issue when i inspect the code `bee api` generated.

I got following error when i POST recode to postgresql with swagger.

```
Response Body
"pq: duplicate key value violates unique constraint \"users_pkey\""
```

I am not given the item with `serial` type in the body of POST, and expect it auto-increased when insert into db.

**Comment by astaxie** [comment]
from the error information, it looks `duplicate key value`
