### ISSUE TITLE
force beego  to re-render template in production

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1448]
hi, I have  beego in production. and I cannot  re-render template without restart beego service. how to  force beego to re render the  page without restart service?

**Comment by nkbai** [comment]
call beego.BuildTemplate(beego.ViewsPath, "index.tpl")

**Comment by goldalworming** [comment]
I got this error
controllers/default.go:40: too many arguments in call to beego.BuildTemplate

then I change it to 
func (c *MainController) Rerender() {
    beego.BuildTemplate(beego.ViewsPath)
    c.Redirect("/", 302)
}

and it doesn't refresh the template

**Comment by goldalworming** [comment]
it have already work. thanks.

**Comment by nkbai** [comment]
how to resolve this problem?
tell me the way

**Comment by goldalworming** [comment]
this code works

func (c *MainController) Rerender() {
    beego.BuildTemplate(beego.ViewsPath)
    c.Redirect("/", 302)        
}
