### ISSUE TITLE
No way to use sentinel for session stored in redis

### ISSUE THREAD

**Issue by RealHacker** [astaxie/beego#1453]
Beego's configuration of redis store only supports connection string, so there is no way to use sentinel to connect to a redis cluster, without modifying Beego source code.

**Comment by astaxie** [comment]
@RealHacker you mean want to support this? https://github.com/chasex/redis-go-cluster

**Comment by RealHacker** [comment]
Never mind. Beego is flexible enough for me to implement my own session store based on sentinel. :)

**Comment by astaxie** [comment]
cool. if you have any good idea or already implement a new provider. We would appreciate if you can  send the PR
