### ISSUE TITLE
监听https会出现端口被占用的问题

### ISSUE THREAD

**Issue by williamzhang2013** [astaxie/beego#1456]
beego能支持http和https的监听，在实际使用中，设置了如下参数：
EnableHttpTLS = true
HttpsPort = 8888
HttpCertFile = ./server.crt
HttpKeyFile = ./server.key

运行时发现，第一次是可以的，后面自动编译后就会出现：
[C] ListenAndServeTLS: %!(EXTRA *net.OpError=listen tcp :8888: bind: address already in use)
这样的错误，不知应该如何解决？

**Comment by astaxie** [comment]
8888端口被占用啊，输出错误里面已经显示了

**Comment by williamzhang2013** [comment]
@astaxie ，应该是同时设置了监听http和https的原因。
后来调试中发现关闭对于http的监听后，这个就会消失。

不知是否还有需要设置的地方

**Comment by gobet8** [comment]
http用8080
https用443 啊

**Comment by lei-cao** [comment]
@williamzhang2013 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@williamzhang2013 is your issue solved?

**Comment by lei-cao** [comment]
@astaxie close?

**Comment by williamzhang2013** [comment]
@lei-cao ,sorry for later reply. 
The issue is solved.
Thank you

**Comment by haophper** [comment]
在配置文件中添加EnableMutualHTTPS=true可以解决这个问题
