### ISSUE TITLE
Issue still exists: "http: multiple response.WriteHeader calls" when call this.Abort

### ISSUE THREAD

**Issue by zfc09** [astaxie/beego#1458]
I'm using beego by go get, and the version is 1.5

I know there's a related closed issue #912, but seems the issue still exists.

When I call this.Abort("404") for example in a custom controller, the warning will occur:
2015/11/28 09:05:42 http: multiple response.WriteHeader calls

I debugged this and follow the call stack, then found if without the following line:
https://github.com/astaxie/beego/blob/master/controller.go#L281

it will be OK and the response is also correct.

The error status has already been set in executeError, and seems that line should be moved to L286.

**Comment by astaxie** [comment]
try develop branch. I have fix a lot in the new version

**Comment by zfc09** [comment]
oh, thanks! but when will it be merged to the master ?
