### ISSUE TITLE
graceful的init 函数可否延后执行

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1460]
实际上如果没有使用graceful启动,这些init的工作完全没用
当然其他模块也应该存在这样的工作,比如session中的sess_utils.go中的init工作
不知这种做法能否得到大家的认可
相关代码我在#1455 提交了修改

**Comment by lei-cao** [comment]
@nkbai Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
is this fixed in #1455 ?

**Comment by lei-cao** [comment]
@astaxie  close ?
