### ISSUE TITLE
windows下静态文件映射找不到问题

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1461]
windows下/static目录下的文件是找不到的,
相关问题我已经在#1455进行了修正.

**Comment by lei-cao** [comment]
@nkbai Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@nkbai  is this solved in #1455 ?

**Comment by lei-cao** [comment]
@astaxie close ?
