### ISSUE TITLE
orm中的model定义能不能实现继承

### ISSUE THREAD

**Issue by doujia** [astaxie/beego#1462]
例如定义如下struct
type BaseModel struct {
	Created         time.Time `orm:"auto_now_add;index"`
	Updated         time.Time `orm:"auto_now;index"`
	Sort int64  `orm:"default(100)"`
	Memo string `orm:"default("");type(text)"`
}

然后别的model中继承这个model，自动能获得相应的字段
这个需求主要是在修改所有表的共同字段的时候简单点，也不会有漏的

**Comment by githubvip1207** [comment]
同问，我的场景是：
struct都是thrift生成的，逻辑层需要在struct的基础上增加几个字段用作排序。最终返回的字段又不能包含这几个用作排序的字段；
我能想到的两个方案都都不太好用：
1、想要在base struct里直接直接排序的字段，只能修改thrift协议。但协议层又不愿意返回这几个字段。坑~
2、单独写一个包含base struct和排序字段的struct，排完序后再遍历将数据赋值到base struct。这办法实在是太傻了，但我不得不这么用。

**Comment by lei-cao** [comment]
@doujia Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by yijunjun** [comment]
这个需求也有遇到，非常希望能尽快加入

**Comment by astaxie** [comment]
#1723
