### ISSUE TITLE
orm.RunSyncdb create varchar field instead of json or jsonb

### ISSUE THREAD

**Issue by fereidani** [astaxie/beego#1466]
Hi ,
i'm trying to make a postgres jsonb column with beego orm.RunSyncdb but orm create field as varchar(255) instead .
```
type Users struct {
	Id     int
	Birthday     time.Time
	Name         string `orm:"size(50)"`
	Metadata	string `orm:"type(jsonb)"`
}
```
i only need to add column to database as jsonb and retrieve it as string for further processing ...
is this a bug ?

**Comment by astaxie** [comment]
it's not support jsonb now

**Comment by fereidani** [comment]
thank you for your answer
isn't it better to make type as developer input tags instead of forced type selection?
for example i just want make json column type and seeing it as string is enough for me .
as i know pq support this behavior (retrieving json value as string).

**Comment by astaxie** [comment]
@fereidani we will add this proposal into our next version planning

**Comment by fereidani** [comment]
it will be great , thank you , let me know if i can provide any help ...

**Comment by mailbaoer** [comment]
wo, happy to see this answer！:star2:

**Comment by astaxie** [comment]
support in beego1.7.0 now
