### ISSUE TITLE
控制器函数调用

### ISSUE THREAD

**Issue by qzyuanmu** [astaxie/beego#1471]
可以从一个控制器的函数里调用另外一个控制器的函数吗？不用URL重定向的方式？
顺便求解？

**Comment by goldalworming** [comment]
I translated to english so I'm sorry if I misunderstood

this is to redirect 
c.Redirect("/", 302)

and calling another function of controller, just call it. it should be work.

**Comment by lei-cao** [comment]
@qzyuanmu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
