### ISSUE TITLE
how to know how beego server crash/stop

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1472]
Hi, 
what is proper way to log beego server crash. I got my server stop but I don't know why
I have beego log and nohup log. but I don't know why it stop

	2015/12/04 08:29:37 [1;34m[router.go:849] [D] | GET        | /listregister                            | 626.816µs        | match      | /listregister                            | [0m
	2015/12/04 08:30:53 [1;34m[router.go:849] [D] | GET        | /                                        | 307.031µs        | match      | /                                        | [0m
	2015/12/04 08:33:54 exit status 1

this is my last 3 log..how do I know why server stop?

**Comment by astaxie** [comment]
I don't know how can you got the error. it looks receive signal and exit the application

**Comment by goldalworming** [comment]
do you have any suggestion to run beego web application as backup
I run 8081 and 8082 beego web app and the 8082 always stop as above

**Comment by astaxie** [comment]
@goldalworming try docker and haproxy
