### ISSUE TITLE
SessionProvider会存储无用session

### ISSUE THREAD

**Issue by zhaoyibo** [astaxie/beego#1473]
首先感谢一下谢大，我是通过谢大的书接触的golang。

最近用begoo尝试写了一个小项目，使用session的过程中发现好像有这么一个问题：登出时调用了`c.DestroySession()`，但是发现provider中的原sessionid还在。
先简单贴下测试代码，除了再配置俩路由，别的都是`bee new`自动生成的，
```
// default.go
func (c *MainController) Login() {
	c.SetSession("user", 1)
	c.TplNames = "index.tpl"
}
func (c *MainController) Logout() {
	c.DestroySession()
	c.TplNames = "index.tpl"
}

// main.go
func main() {
	beego.SessionOn = true
	beego.SessionProvider = "redis"
	beego.SessionSavePath = "192.168.99.100:6379"
	beego.Run()
}
```
`/login`的时候会往 redis 里写入，redis 中内容如下
```
172.17.0.3:6379> get 3cf26e016ba4c3c15695bc7831ca4408
"\x0e\xff\x81\x04\x01\x02\xff\x82\x00\x01\x10\x01\x10\x00\x00\x1b\xff\x82\x00\x01\x06string\x0c\x06\x00\x04user\x03int\x04\x02\x00\x02"
172.17.0.3:6379> ttl 3cf26e016ba4c3c15695bc7831ca4408
(integer) 3587
```

`/logout`之后，再次查询 redis，
```
172.17.0.3:6379> get 3cf26e016ba4c3c15695bc7831ca4408
"\x0e\xff\x81\x04\x01\x02\xff\x82\x00\x01\x10\x01\x10\x00\x00\x04\xff\x82\x00\x00"
172.17.0.3:6379> ttl 3cf26e016ba4c3c15695bc7831ca4408
(integer) 3594
```

看了一下源码，当`/logout`的时候，会先从provider中把对应的session移除，因为又要移除客户端的cookie，调用了`http.SetCookie`。
开启 session 时，每次路由的时候都会先调用`GlobalSessions.SessionStart(w, r)`获取`session.SessionStore`，然后
`defer session.SessionStore.SessionRelease(w)`，`sess_redis.go`的实现：
```
func (rs *RedisSessionStore) SessionRelease(w http.ResponseWriter) {
	c := rs.p.Get()
	defer c.Close()
	b, err := session.EncodeGob(rs.values)
	if err != nil {
		return
	}
	c.Do("SETEX", rs.sid, rs.maxlifetime, string(b))
}
```
`/logout`后会获取到一个sid为上次登录时的sessionid、values为空map的`RedisSessionStore`。对一个空map进行`EncodeGob`时`err==nil`，所以最后又存到redis中了一个空map。不知对于保存这样的空session 是否是有什么考虑？

另外，https://github.com/astaxie/beego/blob/master/session/session.go#L233 这里的`&&`应该是笔误吧。

**Comment by lei-cao** [comment]
@zhaoyibo Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by ysqi** [comment]
because  SETEX command will and new key-value if key not exist。 function SessionRelease should be updated but not new session values, I will fix it.

**Comment by ysqi** [comment]
@astaxie  close it ?
