### ISSUE TITLE
migration/migration.go中的addOrUpdateRecord()方法不支持postgresql

### ISSUE THREAD

**Issue by diabloneo** [astaxie/beego#1475]
下面这个代码中，列名使用反引号包围，这个语句在postgresql中无法执行，提示是语法错误。

```
func (m *Migration) addOrUpdateRecord(name, status string) error {
        ...
	} else {
		status = "update"
		p, err := o.Raw("insert into migrations(`name`, `created_at`, `statements`, `status`) values(?,?,?,?)").Prepare()
```

如果改成

```
                p, err := o.Raw(`insert into migrations("name", "created_at", "statements", "status") values(?, ?, ?, ?)`).Prepare()
```

则能够成功（只是随便改一下）。

问题是：为啥要用反引号呢？

**Comment by astaxie** [comment]
已经在develop版本改好了

**Comment by lei-cao** [comment]
@diabloneo Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by diabloneo** [comment]
@lei-cao  I will using English next time.

**Comment by lei-cao** [comment]
@diabloneo great. thank you so much.

**Comment by lei-cao** [comment]
@astaxie  close now or after next release ?
