### ISSUE TITLE
how to run, update and restart without downtime

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1476]
Hi, I have application in production but I want to update it and restart without downtime.
is there any apps for golang / beego to do it?
in node.js we had pm2, I hope go has similiar application

**Comment by astaxie** [comment]
please refer to https://godoc.org/github.com/astaxie/beego/grace

**Comment by goldalworming** [comment]
I still don't understand how to use it 
and combine it with beego

**Comment by astaxie** [comment]
set `grace=true` in the conf/app.conf.
