### ISSUE TITLE
beego框架单机并发量有多少，我测试不进行数据业务处理，只测试beego web的并发

### ISSUE THREAD

**Issue by 10045125** [astaxie/beego#1477]
我的是macbook pro 15 低配，用jmeter测试beego的最大并发吞吐量，最高最能到432，请问这个有没有你们的官方测试数据。
![image](https://cloud.githubusercontent.com/assets/2945098/11736188/18ba19e0-a006-11e5-89e3-ac70e8dbb08e.png)

**Comment by astaxie** [comment]
https://www.techempower.com/benchmarks/#section=data-r11&hw=i7&test=json&l=cn4&f=zik0zj-zik0zj-zik0zi-zik0zj-hra0hr
