### ISSUE TITLE
orm执行的sql语句是否太多了?

### ISSUE THREAD

**Issue by nkbai** [astaxie/beego#1479]
num, err = qs.Filter("user_name__in", "testing1", "testing2").Delete()
我在orm_test.go 测试的时候发现这条语句对应的sql语句居然有下面这么多条. 感觉颇为浪费.
           88 Prepare	SELECT T0.`id` FROM `user` T0 WHERE T0.`user_name` IN (?, ?)
	   88 Execute	SELECT T0.`id` FROM `user` T0 WHERE T0.`user_name` IN ('testing1', 'testing2')
	   88 Close stmt
	   88 Prepare	DELETE FROM `user` WHERE `id` IN (?, ?)
	   88 Execute	DELETE FROM `user` WHERE `id` IN (22, 23)
	   88 Close stmt
	   88 Prepare	SELECT T0.`id` FROM `post` T0 WHERE T0.`user_id` IN (?, ?)
	   88 Execute	SELECT T0.`id` FROM `post` T0 WHERE T0.`user_id` IN (22, 23)

**Comment by astaxie** [comment]
Prepare和Execute是同一句语句

**Comment by nkbai** [comment]
本来一条语句可以完成的,为什么要搞成三条语句呢

**Comment by astaxie** [comment]
http://go-database-sql.org/prepared.html

**Comment by nkbai** [comment]
我知道你说的prepare什么意思,我意思是那对应一条语句delete from where username in (testing1,testing2)就行了啊
为什么先要select id,然后delete from id in
然后再select 呢
