### ISSUE TITLE
beego orm not support primary-sql batch operation

### ISSUE THREAD

**Issue by zld406504302** [astaxie/beego#1480]
orm Raw function not supports batch operation,e.g. batch insert or batch update

**Comment by lei-cao** [comment]
@zld406504302 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by ysqi** [comment]
you can  parepare  raw sql ,and  change parameter to batch exec. e.g: 
```golang
p, err := o.Raw("UPDATE user SET name = ? WHERE name = ?").Prepare()
if err!=nil {
  // error
}
defer p.close()
res, err := p.Exec("testing", "slene");
if err!=nil{
   //error
}
res, err  = p.Exec("testing", "astaxie")
if err!=nil{
   //error
}
...
... 
```

**Comment by zld406504302** [comment]
you seem to not understand MySQL batch update operation, your example just reuse  the update statement, but it is still execute  N times ; Batch-Update should be execute once and effected more row data, and the result is a result set, rather than a result.

e.g:

INSERT INTO tbl_name (col_name1,col_name2,...)
VALUES(col_value1,col_value2,...), (col_value1,col_value2,...)
ON DUPLICATE KEY UPDATE userName=VALUES(userName)

INSERT INTO tbl_name (col_name1,col_name2,...)
VALUES (col_value1,col_value2,...), (col_value1,col_value2,...) ,...

**Comment by ysqi** [comment]
you can batch insert ,see:http://beego.me/docs/mvc/model/object.md#insertmulti 
but  It does not support update  many records in on time.

**Comment by zld406504302** [comment]
thanks for your patience, but I'm going to perform an 'insert ignore into ' operation, so 'Insertmulti' can't meet my needs.

**Comment by zhxiaom5** [comment]
why this issue close？  Insertmulti have any options to perform insert ignore int？

**Comment by EnochZg** [comment]
why this issue close？
