### ISSUE TITLE
Ordering issue in LayoutSections

### ISSUE THREAD

**Issue by bep** [astaxie/beego#1485]
Nested `LayoutSections` works almost all the time, which suggests an order dependency in the `LayoutSections` rendering.

```
c.LayoutSections["Main"] = "main.html"
c.LayoutSections["Inner"] = "inner.html"
```

`main.html`:

```
Inner: {{ .Inner }}
```

Sometimes the `.Inner` is empty.

**Comment by ysqi** [comment]
Because  when  iterating over the  **LayoutSections map**   with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next, So  ExecuteTemplate can't get **.Inner** html all time.

**Comment by astaxie** [comment]
@ysqi is it possible to fetch by name while not range loop

**Comment by ysqi** [comment]
@astaxie slightly tricky , you can't known the template need use var.

**Comment by bep** [comment]
What if you could somehow render the sections lazily...

**Comment by ysqi** [comment]
Sections need use in your  layout template.  You can work like this: http://beego.me/docs/mvc/view/view.md#layoutsection
