### ISSUE TITLE
orm，MySQL使用type(text)时建表失败

### ISSUE THREAD

**Issue by siren93** [astaxie/beego#1491]
如题，手动导出语句去建表，text属性的列出现can't have a default  value 的错误，貌似是生成的语句中在text属性的列后面默认加了 default ''，Google查到可修改配置将mysql设为非strict mode解决，但是我想问一些下，为什么我没有手动添加default注解，但是还是默认生成了default约束了呢？这样合理吗？

**Comment by lei-cao** [comment]
@siren93 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@siren93  does this solve your issue ?
https://github.com/astaxie/beego/issues/1313
@astaxie duplicated

**Comment by lei-cao** [comment]
@siren93 does #1313 fix the issue for you?

**Comment by siren93** [comment]
Thanks, It solved the issue, forgive my poor English.

**Comment by astaxie** [comment]
@siren93 cool.
