### ISSUE TITLE
Why always add `T0.` in sql which be generated by ORM

### ISSUE THREAD

**Issue by simpleton** [astaxie/beego#1495]
Why always add T0 before every parameter in sql.
```sql
UPDATE `t_invite_code` T0 SET T0.`f_used_count` = T0.`f_used_count` + ? 
```

**Comment by astaxie** [comment]
The purpose is for join

**Comment by simpleton** [comment]
@astaxie Thanks for your quick feedback.
Could you supply some more detail? I'm feel a little consume about that.

**Comment by RCooLeR** [comment]
For example if u have few tables with same column names (updated_at etc.) 
In query, generated for these tables joined, might be issues.
It's common practice for all orms to use table aliases.

**Comment by simpleton** [comment]
@RCooLeR Thanks for your explanation.
