### ISSUE TITLE
主页有错别字

### ISSUE THREAD

**Issue by xiongtoto0526** [astaxie/beego#1499]
http://beego.me/docs/install/bee.md 此页面--version 命令章节--

提到：
这个命令是动态获取bee、beego和Go的版本，这样一旦用户出现错误，可以通过改命令来查看当前的...

应该修改为：

这个命令是动态获取bee、beego和Go的版本，这样一旦用户出现错误，可以通过---该---命令来查看当前的...

**Comment by lei-cao** [comment]
@xiongtoto0526 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@xiongtoto0526 don't you want to PR to https://github.com/beego/beedoc and fix it? Thank you

**Comment by lei-cao** [comment]
@astaxie  close ?

**Comment by lei-cao** [comment]
@xiongtoto0526 I ported the issue https://github.com/beego/beedoc/issues/331
