### ISSUE TITLE
validation ,使用match时,出错

### ISSUE THREAD

**Issue by xw43230855** [astaxie/beego#1500]
使用match时,匹配这个正则时 , /^(?![^a-zA-Z]+$)(?!\\D+$).{6,20}$/,
出现 error parsing regexp: invalid or unsupported Perl syntax: `(?!`  错误

**Comment by reasonerjt** [comment]
?! is not supported in golang regexp

http://stackoverflow.com/questions/26771592/negative-look-ahead-go-regular-expressions

**Comment by lei-cao** [comment]
@xw43230855 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@xw43230855 does reasonerjt solve your issue ?

**Comment by lei-cao** [comment]
@astaxie close ?
