### ISSUE TITLE
tree.go&splitSegment() possible error

### ISSUE THREAD

**Issue by markman101** [astaxie/beego#1502]
beego版本是 1.5.0  golang 1.4.2

直接执行tree.go 里的splitSegment()
func splitSegment(key string) (bool, []string, string) {
//code...
}
func main() {
	ret,param,seg:=splitSegment("cms_:id_:page.html")
	fmt.Println(ret,param,seg);
}
输出是：true [:id_ :page] cms_(.+)(.+).html

跟beego里 样例 
"cms_:id_:page.html" -> true, [:id :page], cms_(.+)_(.+).html 不一样

**Comment by ysqi** [comment]
确实和注释中描述的不一致但是执行结果是合理的。

返回结果`true [:id_ :page] cms_(.+)(.+).html`
中第一个参数为`id_`这是合理的，因为`_`   (还有字母数字)是被定义合法的参数名，如`:Tag_id` 。

如果你期望结果是：` true, [:id :page], cms_(.+)_(.+).html ` 则添加 范围限定稍微修改即可：
```
cms_:id(.+)_:page.html
```
