### ISSUE TITLE
static/ueditor/index.html 这样的html页面打开 

### ISSUE THREAD

**Issue by fireflyhoo** [astaxie/beego#1508]
![20151223114512](https://cloud.githubusercontent.com/assets/3061324/11970696/b0b0ff6c-a96a-11e5-8bef-3a5d003b4faa.jpg)
会有错误

![20151223114614](https://cloud.githubusercontent.com/assets/3061324/11970709/cff1a4f8-a96a-11e5-8512-05d6c4419a82.jpg)
文件路径如上.

**Comment by lei-cao** [comment]
@fireflyhoo Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by ysqi** [comment]
你所访问的是静态文件自然，必需是全路径访问，既然静态文件路径是`/static/ueditor/index.html` 则访问是也必须完整路径：`http://127.0.0.1:8080/static/ueditor/index.html` 而不应该缺少**`/index.html`**

**Comment by astaxie** [comment]
I have tried https://github.com/hogenwang/beego-ueditor. and it works in develop branch now. http://localhost:8082/static/editor/ueditor
![snip20160103_1](https://cloud.githubusercontent.com/assets/233907/12078898/df79a6f8-b25e-11e5-86d6-bb018af9723b.png)

**Comment by fireflyhoo** [comment]
i I have tried https://github.com/hogenwang/beego-ueditor. in my window 7 64bit system ,  problem still exists.

**Comment by astaxie** [comment]
develop branch
