### ISSUE TITLE
是否可以调整下输出日志的文件权限

### ISSUE THREAD

**Issue by sunyuantao** [astaxie/beego#1510]
我们目前场景是：
由于安全的原因，系统上线的用户和查看日志的用户不是同一个，造成日志文件无权限查看，能否把0660权限升级到0666？谢谢！
func (w *FileLogWriter) createLogFile() (*os.File, error) {
	// Open the log file
	fd, err := os.OpenFile(w.Filename, os.O_WRONLY|os.O_APPEND|os.O_CREATE, 0660)
	return fd, err
}

**Comment by astaxie** [comment]
这个可以增加一个参数配置权限。

**Comment by sunyuantao** [comment]
谢 谢大 支持！
另外，看beego代码中关于文件日志的输出，只能设置一个文件，是否可以扩展下像java里log4j的方式，不同的日志输出到不同文件中。

**Comment by lei-cao** [comment]
@sunyuantao Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by astaxie** [comment]
I have checked the code. it's already supported. you can set the config like this:

```
{
  "filename": "logs/beego.log",
  "maxlines": 10000,
  "maxsize": 1<<30,
  "daily": true,
  "maxdays": 15,
  "rotate": true,
  "perm": 0666
}
```

**Comment by sunyuantao** [comment]
3q

**Comment by being23** [comment]
hey @astaxie, the config you gave above doesn't work for me, one such case is here:http://play.golang.org/p/bM2a7HR1G7. Do i make something wrong?
