### ISSUE TITLE
url match problem, bug in tree.go?

### ISSUE THREAD

**Issue by reasonerjt** [astaxie/beego#1511]
/api/projects/1/members/  does not match /api/projects/:pid/members/?:mid

Maybe there's some issue in "match" func of leafInfo?

I tried to update the line 413, from "return false, nil" to "break" and things worked.

**Comment by reasonerjt** [comment]
well maybe I should update line 412,

if len(wildcardValues) <= j to if len(wildcardValues) < j

**Comment by astaxie** [comment]
I have add the router in tree_test.go. it works well. https://github.com/astaxie/beego/commit/92d157736b041307ccfddc69ec2c6cf54178063a

**Comment by reasonerjt** [comment]
@astaxie  Thanks for the reply, I found the this is fixed on develop branch, but the test would fail in master branch, is there a target release date that the change in tree.go will be merged to master?

**Comment by astaxie** [comment]
@reasonerjt our team still working on the issues list. I think should be released in two weeks.
