### ISSUE TITLE
Is beego.me down?

### ISSUE THREAD

**Issue by rock59** [astaxie/beego#1513]
I cant access beego.me!! Is the website down?

**Comment by qzyuanmu** [comment]
中国境内表示可以访问

**Comment by rock59** [comment]
The site is hosted in China !!!!
wooooow ... No one able to access it through the Great Firewall ...
This is madness

**Comment by fuxiaohei** [comment]
beego,me is hosted in linode in Japan.

you can try zh.beego.me in HongKong.

**Comment by rock59** [comment]
I dont live in China.. I cant access the website even with US and European proxies and VPN services.. 
I can visit the website with zh.beego.me now.. 
Thanks for implementing such an awesome framework.. :-)
