### ISSUE TITLE
InsertFilter BeforeRouter not work

### ISSUE THREAD

**Issue by benzsuankularb** [astaxie/beego#1514]
from [issue 1294](https://github.com/astaxie/beego/issues/1294)

`beego.InsertFilter("*", beego.BeforeRouter, func(ctx *context.Context) {})`

This work when I test with POSTMAN

But in fetch/ajax library (chrome) this not work.

I have to move my form InsertFilter to NSBefore then it's work.

Guess, Maybe It's related to some CORS problems.

**Comment by ysqi** [comment]
Are you test with " http://a.com/" ?  Beego can't use `*` match path `/`
e.g:
+ http://localhost:8080
+ http://localhost:8080/
+ http://localhost:8080?par
+ ....

**Comment by astaxie** [comment]
Ajax always related to CORS problem
