### ISSUE TITLE
supporting stream processing of big files

### ISSUE THREAD

**Issue by IllegalWalker** [astaxie/beego#1518]
I have some big files, which need to be uploaded to beego server by HTTP  multipart/form-data content type， at the server side, I need to process these files streamingly(such as proxy it to another  server, chunk by chunk).  But when I try to use net.http.Reqeust.MultipartReader() in controller, I got errors

```go
func (this *TestController) Post() {
	reader, err := this.Ctx.Request.MultipartReader()
	if err != nil {
		beego.Error(err)
	}
	// TODO: streaming process multipart data
}
```
error message：
2015/12/29 12:32:16 [test.go:52] [E] http: multipart handled by ParseMultipartForm 

It seems that :  beego has already invoked net.http.Request.ParseMutlpartForm()   to produce controller.Ctx.Request.MultipleForm,  when my controller got executed, the whole file has uploaded to the  server already, So I have no way to process these files streamingly.
Is there any way to work around or configurations that may help ?

**Comment by lei-cao** [comment]
@IllegalWalker  Thank you for supporting beego. please update or submit your issue in English For a better international user friendly communication.

**Comment by astaxie** [comment]
yea, beego will autoparse in current implement. beego want to compatible with the unsupported PUT and DELETE method. I will improve it in the new version. As most case we don't need to do that.

```
if httpMethod == "POST" && context.Input.Query("_method") == "PUT" {
	httpMethod = "PUT"
}
if httpMethod == "POST" && context.Input.Query("_method") == "DELETE" {
	httpMethod = "DELETE"
}
```

**Comment by astaxie** [comment]
fix in https://github.com/astaxie/beego/commit/6585e66f97af69548cb2e4dbe594b99c1406372f

**Comment by apremalal** [comment]
Seems this issue still exists.  I'm trying to achieve the  same stream processing however it returns 
` http: multipart handled by ParseMultipartForm`

**Comment by alexkrts** [comment]
> Seems this issue still exists. I'm trying to achieve the same stream processing however it returns
> ` http: multipart handled by ParseMultipartForm`

The same. Problem still exists.

**Comment by ahgeyu2** [comment]
> > Seems this issue still exists. I'm trying to achieve the same stream processing however it returns
> > ` http: multipart handled by ParseMultipartForm`
> 
> The same. Problem still exists.

The same. Problem still exists.
