### ISSUE TITLE
Let's keep tickets on English

### ISSUE THREAD

**Issue by vvelikodny** [astaxie/beego#1520]
Hi everyone, let's do all issues on English, others want to know what happens)

**Comment by astaxie** [comment]
make sense. I will try to translate all the chinese issue.

**Comment by karantan** [comment]
:thumbsup:

**Comment by astaxie** [comment]
@lei-cao please add comments in every exist chinese issues. First of all ask the author translate to english. if has no response in 2 days please help to translate all the chinese to english. That will be helpful

**Comment by lei-cao** [comment]
yup

**Comment by vvelikodny** [comment]
thanks guys)

**Comment by lei-cao** [comment]
@astaxie I just pinged all open issues's authors. And I saw quite some issues can be close or updated already. please have a look of them. I will also help to reply some.

**Comment by bakanis** [comment]
Well, google translate does the job pretty well, imho.

**Comment by lei-cao** [comment]
@bakanis yes, it works when there are no other choices. But for the further growth of beego, using English in  issues is very important.
