### ISSUE TITLE
Beego API Request Header parm

### ISSUE THREAD

**Issue by kyawmyintthein** [astaxie/beego#1522]
I use param_name in request header for beego API.  It work on dev mode. But, it does not work on production. Beego try to convert param-name to Param-name. Is it normal?

**Comment by lei-cao** [comment]
is it because of underscore is not allowed. http://stackoverflow.com/questions/22856136/why-underscores-are-forbidden-in-http-header-names ?

**Comment by kyawmyintthein** [comment]
It is not allow on production mode. right? I can use dev mode.

**Comment by astaxie** [comment]
it's not related to dev or prod. As the only difference between dev and prod is:

1.  compile template every request in dev
2.  output request log in console in dev
3. output json or xml with format in dev. compress in prod
4. output header Server with beego version in dev.
5. encounter the panic error will show the stack in dev. 
6. show some system error in dev. like can't find file, can't compile template

**Comment by vvelikodny** [comment]
@astaxie good snippet for documentation)

**Comment by kyawmyintthein** [comment]
@astaxie thanks
