### ISSUE TITLE
【我是中文】建议：生成ORM定义的工具--方便旧工程迁移。

### ISSUE THREAD

**Issue by toontong** [astaxie/beego#1523]
一大堆表定义ORM的struct要写tags，建议提供一个工具生成  type xxx struct定义代码

本人迁移到beego时，使用python写的工具
https://gist.github.com/toontong/6287266b91f3b41f7ab9

由于py与贵团队使用golang格格不入，我就只提个issues好了，并不想提交golang版代码。
就如我用中文提issues，也有点格格不入。

**Comment by astaxie** [comment]
I will close the chinese issues

**Comment by toontong** [comment]
呵呵

**Comment by toontong** [comment]
hehe

**Comment by siddontang** [comment]
:-)
