### ISSUE TITLE
Seek for best pratise for orm.NewOrm

### ISSUE THREAD

**Issue by Yuhang** [astaxie/beego#1524]
as mentioned, can I do o := orm.NewOrm() every time when I want to exec any sql?

if so, any performance problems introduced?

thanks!

**Comment by ysqi** [comment]
`orm.NewOrm()` only new a db helper instance , any other about db is global, e.g: db connection pool

**Comment by astaxie** [comment]
@Yuhang yea, you can `o := orm.NewOrm()` in every exec. actually inside beego/ORM we cached the sql.DB. and sql.DB will use the connection pool to do the exec. So there's no extral performance.
