### ISSUE TITLE
How to ignore a field when insert but read for select?

### ISSUE THREAD

**Issue by Yuhang** [astaxie/beego#1528]
eg. I have User { Id int, ctime time.Time, utime time.Time }

now I can code like     ctime time.Time `orm:"-"`    to ignore ctime.

but this happens for all cases. I want to insert with db's create time, not my logic server's mechine timestamp. And get this value when o.Read(&User).

What shall I do then?

**Comment by astaxie** [comment]
no, you can't

**Comment by Yuhang** [comment]
well...

any further support?

or u have a plan for this?

It's a general use case...

**Comment by astaxie** [comment]
I have no idea on these case. For me this is not a general case. `orm: -` meaning you want to ignore this field but will used for as purpose. like json marshal.

**Comment by Yuhang** [comment]
ok

any reference for my patch?

I want a "+" for my own use. like `orm:"+"` for case I mentioned. ignore when insert but used for select.

**Comment by astaxie** [comment]
It looks too complicated. let's discuss in our develop team first.

**Comment by Yuhang** [comment]
diff --git a/orm/db.go b/orm/db.go
index 20dc80f..150a4b5 100644
--- a/orm/db.go
+++ b/orm/db.go
@@ -84,7 +84,7 @@ func (d *dbBase) collectValues(mi *modelInfo, ind reflect.Value, cols []string,
 		} else {
 			panic(fmt.Errorf("wrong db field/column name `%s` for model `%s`", column, mi.fullName))
 		}
-		if fi.dbcol == false || fi.auto && skipAuto {
+		if fi.dbcol == false || fi.auto && skipAuto || (fi.insert_ignore && insert) {
 			continue
 		}
 		value, err := d.collectFieldValue(mi, fi, ind, insert, tz)
diff --git a/orm/models_info_f.go b/orm/models_info_f.go
index 84a0c02..bd9ff4a 100644
--- a/orm/models_info_f.go
+++ b/orm/models_info_f.go
@@ -121,6 +121,7 @@ type fieldInfo struct {
 	size                int
 	auto_now            bool
 	auto_now_add        bool
+	insert_ignore       bool
 	rel                 bool
 	reverse             bool
 	reverseField        string
@@ -280,6 +281,7 @@ checkType:
 	fi.auto = attrs["auto"]
 	fi.pk = attrs["pk"]
 	fi.unique = attrs["unique"]
+	fi.insert_ignore = attrs["insert_ignore"]
 
 	// Mark object property if there is attribute "default" in the orm configuration
 	if _, ok := tags["default"]; ok {

**Comment by Yuhang** [comment]
done :)

**Comment by astaxie** [comment]
:cool:

**Comment by astaxie** [comment]
@Yuhang could you create a PR to develop branch for it?

**Comment by astaxie** [comment]
http://beego.me/docs/mvc/model/models.md#auto_now-%2F-auto_now_add
