### ISSUE TITLE
cache interface: Put(k, v, timeout) the time should the type of time.Duration

### ISSUE THREAD

**Issue by toontong** [astaxie/beego#1530]
RT

**Comment by ysqi** [comment]
@toontong  The Parameter **timeout**  mean timeout in **seconds**, not nanosecond。

**Comment by ysqi** [comment]
@astaxie  can close it .

**Comment by astaxie** [comment]
I am still thinking about this requirement. whether `time.Duration` is good than int?

@toontong can you list the benefit from this?

**Comment by toontong** [comment]
作为 强类型语言，一个时间参数，竟不明确单位。
一个变量timeout，谁知道 作者你单位值是秒？
1无文档，2单词带岐义；
timeoutSecond will be better.


还有一个时间变量命名为lastAccess -- 明明含义是cache的创建时间，却用access。看代码就理解成每次访问（使用）此cache就会更新此access 时间

**Comment by JessonChan** [comment]
@astaxie i like time.Duration,more precise and readable.

**Comment by astaxie** [comment]
@JessonChan yea, that's a good suggestion.do you want to take it?

**Comment by youngsterxyf** [comment]
@astaxie Have someone taken this issue?

**Comment by astaxie** [comment]
@youngsterxyf not yet. you want to try it?

**Comment by youngsterxyf** [comment]
@astaxie Yes! （但我有点担心自己完成的质量 :smile: ）

**Comment by astaxie** [comment]
@youngsterxyf 😄go for it. don't worry.

**Comment by youngsterxyf** [comment]
@astaxie OK, Thanks!

**Comment by JessonChan** [comment]
@youngsterxyf i will review your pr 😄

**Comment by toontong** [comment]
pls add define beego.GlobalCache = nil

**Comment by astaxie** [comment]
why need beego.GlobalCache?

**Comment by youngsterxyf** [comment]
@toontong for convenience when developer use beego？

**Comment by toontong** [comment]
yes，for convenience

**Comment by youngsterxyf** [comment]
@toontong @astaxie I think it's not just one case，it need IoC，maybe

**Comment by astaxie** [comment]
NO. It should be handler by the caller.
