### ISSUE TITLE
Where is the Chinese freeback？

### ISSUE THREAD

**Issue by toontong** [astaxie/beego#1531]
Your want use EN in github.com, ok.
But, 能顾下CH人的感受么。人家openresty的春哥中文邮件组做得多好。
像工程 github.com主页上的En文档连接不也是中文，啪啪~~
Like the openresty

**Comment by astaxie** [comment]
@toontong 😄we are working on the wetalk which is a community.

if you want to solve the problem instantly. please join QQ group: 258969317

**Comment by toontong** [comment]
看源码，基本上能解释我的问题。Q群信息太杂乱无章，并没看到哪个技术Q群能活得好好的。
中文开源技术社区-，只有openresty的google邮件组做得好，检索问题简单快捷。
春哥无不一一回答，人家一个人肉翻墙的技术大牛，妥妥地用中文回馈国内社区。
beego要达到openresty的高度，考虑下吧。

**Comment by astaxie** [comment]
yea, I can totally understand your consideration. That's why I want to setup the wetalk community.
