### ISSUE TITLE
Params bind with a default zero value of 0 instead of it's own type

### ISSUE THREAD

**Issue by foreversmart** [astaxie/beego#1534]
This problem cause a panic when the params's type is not int and  the param's value is a zero value(like string type with "")

in the source code: https://github.com/astaxie/beego/blob/master/context/input.go line:356
i think it is better to use
```go
rv := reflect.Zero(typ)
```
instead of
```go
rv := reflect.Zero(reflect.TypeOf(0))
```

**Comment by foreversmart** [comment]
https://github.com/astaxie/beego/pull/1535

**Comment by astaxie** [comment]
It's already fixed in develop branch

**Comment by foreversmart** [comment]
ok
