### ISSUE TITLE
orm运行时如何创建表格

### ISSUE THREAD

**Issue by williamzhang2013** [astaxie/beego#1541]
beego中orm一般在init里面就会设置好一切，建好表格，这样后面的数据只需要写入即可。

我遇到的问题是：数据来的很多，一段时间（比如一个月）后就会很大，所以这时候就希望再建出一张表格来，和前一张表里面字段一样，但是表的名字会有微小区别。后面再过来的数据就写入新表，而不是旧表了

尝试了蛮久，没有能够成功，想请教这个功能应该如何实现呢？

**Comment by astaxie** [comment]
I think it's not related with beego's ORM. you should think about how to do the database sharding
