### ISSUE TITLE
Excluding subfolder from watching

### ISSUE THREAD

**Issue by grsmv** [astaxie/beego#1552]
Right now it's impossible to exclude subfolder (for example `static/node_modules`) with `--exclude` flag in development mode. 

This tested on 
```json
{
    "Comment": "v1.5.0-9-gfb7314f",
    "Rev": "fb7314f8ac86b83ccd34386518d97cf2363e2ae5"
}
```

Please help me define is this a bug or a feature. Thank you

**Comment by astaxie** [comment]
usage: bee run [appname] [watchall] [-main=*.go] [-downdoc=true]  [-gendoc=true]  [-e=Godeps -e=folderToExclude]

-e

**Comment by grsmv** [comment]
OK, thank you for fast reply, but maybe I'm explaining not really clear - right now Beego don't allow to use **SUB**folders for exclusion. `-e folder_a -e folder_b` works perfectly, `-e folder_a/folder_b` not working at all.

**Comment by astaxie** [comment]
@grsmv thanks for the explaining. I got it. I will improve bee later.

**Comment by youngsterxyf** [comment]
@astaxie I have submit a pr in bee project, see: https://github.com/beego/bee/pull/159
