### ISSUE TITLE
Hour decreasing

### ISSUE THREAD

**Issue by ljesus** [astaxie/beego#1558]
When a model with a time.Time (created_at, updated_at, and other fields) is loaded from the DB and then updated, the hour is decreasing. This may due to the fact that my timezone and my database's timezone is different, but how should I proceed? Shouldn't the ORM store the date according to the timezone? Thanks.

**Comment by astaxie** [comment]
I think you are using MySQL. Hope this two links can solve your problem

https://github.com/go-sql-driver/mysql#loc
http://beego.me/docs/mvc/model/orm.md#timezone-config
