### ISSUE TITLE
How to insert binary data into database?

### ISSUE THREAD

**Issue by busyluo** [astaxie/beego#1569]
```
type File struct {
	Id     int
	Fid    int
	Size   int
	Needle int
	Data   string `orm:"content;type(text);null"`
}
```
pq: 无效的 "UTF8" 编码字节顺序: 0x90

**Comment by astaxie** [comment]
it looks like the data before insert is not UTF8. http://stackoverflow.com/questions/4867272/invalid-byte-sequence-for-encoding-utf8

**Comment by busyluo** [comment]
is there a way to store []byte  ？
