### ISSUE TITLE
Redis session not work in beego 1.6.0

### ISSUE THREAD

**Issue by gwduan** [astaxie/beego#1572]
The function is OK in beego 1.5.0.

I found a commit in session/redis/sess_redis.go on Jan 7, 2016: https://github.com/astaxie/beego/commit/58e2a7c0999697ea8866236ecf83a3a7d57b8541

It adds the judgement:
```
if existed, err := redis.Bool(c.Do("EXISTS", rs.sid)); existed || err != nil {
```

When I delete the judgement, the function works again.

Maybe this is the cause of the problem.

Thanks for any suggestion.

**Comment by astaxie** [comment]
@gwduan what's the problem? can't save new session or can't read session

**Comment by ysqi** [comment]
hi, gwduan,  Fixed  is not perfect!   need save session on first read

**Comment by gwduan** [comment]
Thanks for reply.

Can't save new session.

When called SetSession(), I run `redis-cli`, thers is not any session items created.

**Comment by astaxie** [comment]
@gwduan yea, I have found the problem. I fix it here. will merge into master soon. https://github.com/astaxie/beego/commit/fa8f6e5a53bb229e1cf2b6b14d2719f4ab9ead49

**Comment by astaxie** [comment]
@gwduan merge into the master.please update the beego and try again. thanks
