### ISSUE TITLE
Is any changes in 1.6

### ISSUE THREAD

**Issue by veenutanwar** [astaxie/beego#1576]
Show me error 
1 serverJson : serverJSON
2. input.params[":id"] = input.param("id")
3. beego.AppName not support in main.go
how can i use beego.AppName in main.go
or EnableGzip or CopyRequestBody

**Comment by astaxie** [comment]
yea, there's a lot change in beego1.6.0.

please upgrade bee with `go get -u github.com/beego/bee` and then run `bee fix`

**Comment by veenutanwar** [comment]
Love You
