### ISSUE TITLE
Blatant Const Name Changes Without Backward Compatibility

### ISSUE THREAD

**Issue by r0lodex** [astaxie/beego#1577]
First of all I would like to thank you for this wonderful framework.

Secondly I would like to say that you changed variable names and stuff without warning. Even though there is the feature `bee fix` to fix the current version to the latest version, you should've warn us developers earlier.

Took us a while to get things running, y'know.

**Comment by astaxie** [comment]
@r0lodex yea, the Compatibility is not good for old applications.
