### ISSUE TITLE
Get status code in FinishRouter filter

### ISSUE THREAD

**Issue by zycbobby** [astaxie/beego#1584]
I run the simple code under go1.5, beego 1.5.0, however I can not get the status code in FinishRouter filter.

```go
package main

import (
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/context"
	"fmt"
	"unisdk/unisdkserver/sdkserver/define"
)

func init() {

}

func main() {

	beego.Get("/versions",func(ctx *context.Context){
		ctx.Output.SetStatus(define.StatusOK);
		ctx.Output.Body([]byte("hello world"))
	})

	beego.InsertFilter("/*", beego.FinishRouter, func(ctx *context.Context) {
		fmt.Println(ctx.Output.Status)
	}, false)

	// By default, Go programs run with GOMAXPROCS set to the number of cores available; in prior releases it defaulted to 1.
	beego.Run()
}

```

It turns out to be

```
╰─$ go run main2.go 
2016/01/19 10:53:37 [proc.go:111] [I] ntProtocol run in dev mode
2016/01/19 10:53:37 [asm_amd64.s:1696] [I] http server Running on :9393
2016/01/19 10:53:37 [asm_amd64.s:1696] [I] Admin server Running on 127.0.0.1:8088
0
2016/01/19 10:53:44 [router.go:854] [D] | GET        | /versions                                | 110.024µs        | match      | /versions                                | 

```

I have tried to switch the order of calling SetStatus and Body and it does well. But I cannot figure out why it happens.

**Comment by JessonChan** [comment]
@zycbobby if you just want get the status code you should use 'ctx.ResponseWriter.Status' instead of 'ctx.Output.Status' after router finished.

**Comment by zycbobby** [comment]
@JessonChan Could you tell me which version of beego are you using? I cannot see Status in ResponseWriter under beego 1.5. Actually ResponseWriter is type of http.ResponseWriter. I dont think we can get status code from it.

**Comment by JessonChan** [comment]
@zycbobby the latest version of beego(v1.6.0) 
https://github.com/astaxie/beego/blob/master/context/context.go#L176

**Comment by zycbobby** [comment]
You are right

**Comment by JessonChan** [comment]
#1822
