### ISSUE TITLE
Layout templating broken in 1.6

### ISSUE THREAD

**Issue by bep** [astaxie/beego#1585]
Pretty standard set up with a layout and some sections. Broken when doing a `go get` for 1.6:

```
2016/01/19 11:02:09 [router.go:854][C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2016/01/19 11:02:09 [router.go:860][C] /usr/local/go/src/runtime/asm_amd64.s:437
2016/01/19 11:02:09 [router.go:860][C] /usr/local/go/src/runtime/panic.go:423
2016/01/19 11:02:09 [router.go:860][C] /usr/local/go/src/runtime/panic.go:42
2016/01/19 11:02:09 [router.go:860][C] /usr/local/go/src/runtime/sigpanic_unix.go:24
2016/01/19 11:02:09 [router.go:860][C] /usr/local/go/src/html/template/template.go:125
2016/01/19 11:02:09 [router.go:860][C] /usr/local/go/src/html/template/template.go:114
2016/01/19 11:02:09 [router.go:860][C] /Users/bep/go/src/github.com/astaxie/beego/controller.go:248
2016/01/19 11:02:09 [router.go:860][C] /Users/bep/go/src/github.com/astaxie/beego/controller.go:183
```

**Comment by astaxie** [comment]
@bep could you provide the example code. so we can reproduce it

**Comment by bep** [comment]
It's a closed project (and I ripped at the layout usage to get it up and running), but the main gist of it is:

1. autoRender = false
2. Have a controller c with c.Layout="foo.html" where foo.html exists in /views ... then some sections.
3. Do a c.Render() -> panic as foo.html isn't in the template map.

**Comment by astaxie** [comment]
@bep yea, Now if the autoRender is set to false. you need to run `BuildTemplate(BConfig.WebConfig.ViewsPath)` by yourself.

**Comment by bep** [comment]
... that seems like a strange change? The `c.TplName` is still auto-added ...

**Comment by astaxie** [comment]
@bep yea, I will change it back
