### ISSUE TITLE
关于正则路由 带括号问题

### ISSUE THREAD

**Issue by cjsky** [astaxie/beego#1586]
正则路由里面配置// @router /:app((a|b|c)) [get]

发现编译多几次后~

golang会报错

panic: regexp: Compile(`^(([a|b|c])(([a|b|c]))$`): error parsing regexp: missing closing ): `^((a|b|c)((a|b|c))$`

如果正则需要带括号该怎么办呢？

**Comment by ysqi** [comment]
hi cjsky ,  beego's problem . it convert   `\((a|b|c)\)`  to  `\((a|b|c)\((a|b|c))`

**Comment by cjsky** [comment]
@ysqi yes i know ,so i can't use "()" ?

**Comment by ysqi** [comment]
You can't

**Comment by ysqi** [comment]
@cjsky  Develop branch supoort `()` ,see  #1615
