### ISSUE TITLE
orm的语义和标准库有点差异

### ISSUE THREAD

**Issue by ericx10ng** [astaxie/beego#1590]
谢大，用database/sql语句能正常执行，改成beego 1.6.0 orm后出错了，好像是处理空值有问题
用的是这个方法：.Raw().Exec()

panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 23 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:877 +0x90
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:872 +0x53
github.com/astaxie/beego/orm.getFlatParams(0x0, 0xc208064400, 0x10, 0x10, 0xbeaa80, 0xc208064500, 0xb, 0x10)
        /vagrant/go/src/github.com/astaxie/beego/orm/db_utils.go:70 +0x312
github.com/astaxie/beego/orm.(*rawSet).Exec(0xc2080de660, 0x0, 0x0, 0x0, 0x0)
        /vagrant/go/src/github.com/astaxie/beego/orm/orm_raw.go:82 +0x11d

**Comment by ericx10ng** [comment]
还有个问题， 用database/sql执行没有问题，同样用Raw(....).Exec, 遇到这个错误：

sql: expected 12 arguments, got 10

**Comment by miraclesu** [comment]
@ericx10ng could you give me some beego orm cannot execute sqls?

**Comment by ericx10ng** [comment]
就是sql.Exec支持的格式：Exec("insert into test(a,b,c) values(?,?,?)", a, b, c)

**Comment by miraclesu** [comment]
@ericx10ng 没有重现到你的错误，麻烦提供一个完整的例子，以便好定位问题，谢谢

**Comment by jackXJ** [comment]
我用1.6.2版本go 没问题，换到1.7版本的出现这个问题了

**Comment by jemygraw** [comment]
是不是遇到了外键的field，没有加 rel(fk),比如
```
Account                  *user.Account `orm:"column(account_id);size(40);rel(fk)"`
```
