### ISSUE TITLE
路由有问题

### ISSUE THREAD

**Issue by zhanxj** [astaxie/beego#1595]
如果定义了两个路由 /xxx/:id     /xxx  访问/xxx 会进去第一个定义的路由/xxx/:id

**Comment by astaxie** [comment]
can you provide the reproduct code?

**Comment by ysqi** [comment]
Hi zanxj , I'm work well. my code:
```go
package routers

import (
	"github.com/astaxie/beego"
)

func init() {
	beego.Router("/users/:id", &MyController{}, "*:Single")
	beego.Router("/users/", &MyController{}, "*:Users")
}

type MyController struct {
	beego.Controller
}

func (m *MyController) Users() {
	m.Data["json"] = "{user:[]}"
	m.ServeJson()
}

func (m *MyController) Single() {
	m.Data["json"] = "{user_id:123}"
	m.ServeJson()
}
```
# log info
```shell
2016/01/22 09:19:49 [router.go:854] [D] | GET    | /users/    | 0   | match      | /users/
2016/01/22 09:20:05 [router.go:854] [D] | GET    | /users/34  | 0   | match      | /users/:id
```

**Comment by zhanxj** [comment]
Hi，this is my demo :

package controllers

import (
    "github.com/astaxie/beego"
)

type MainController struct {
    beego.Controller
}

// test001
// @router /info/:id [get]
func (c *MainController) Test1() {
    id := c.GetString(":id")
    c.Data["json"] = map[string]interface{}{
        "code": 200,
        "msg":  "hello22" + id,
    }
    c.ServeJSON()
    return
}

// test002
// @router /info [get]
func (c *MainController) Test2() {
    ids := c.GetString("ids")
    c.Data["json"] = map[string]interface{}{
        "code": 200,
        "msg":  "hello11" + ids,
    }
    c.ServeJSON()
    return
}


====================
package routers



import (

    "github.com/astaxie/beego"

    "hoki.com.cn/hello/controllers"

)



func init() {

    ns := beego.NewNamespace("/v1",

        beego.NSNamespace("/test",

            beego.NSInclude(

                &controllers.MainController{},

            ),

        ),

    )

    beego.AddNamespace(ns)

}

==================
auto generate code:
package routers



import (

    "github.com/astaxie/beego"

)



func init() {



    beego.GlobalControllerRouter["hoki.com.cn/hello/controllers:MainController"] = append(beego.GlobalControllerRouter["hoki.com.cn/hello/controllers:MainController"],

        beego.ControllerComments{

            "Test1",

            `/info/:id`,

            []string{"get"},

            nil})



    beego.GlobalControllerRouter["hoki.com.cn/hello/controllers:MainController"] = append(beego.GlobalControllerRouter["hoki.com.cn/hello/controllers:MainController"],

        beego.ControllerComments{

            "Test2",

            `/info`,

            []string{"get"},

            nil})



}

======================
log

**Comment by huncent** [comment]
升级到1.6.0后，官方wetalk这个项目里
｀｀｀golang
        login := new(auth.LoginRouter)
	beego.Router("/login", login, "get:Get;post:Login")
	beego.Router("/logout", login, "get:Logout")

	beego.InsertFilter("/login/*/access", beego.BeforeRouter, auth.OAuthAccess)
	beego.InsertFilter("/login/*", beego.BeforeRouter, auth.OAuthRedirect)
｀｀｀
上面的/login无效了，直接进到下面，然后进入死循环

**Comment by ysqi** [comment]
@huncent   It is bug , you can change the order in your demo code:

first:
```go
// test002
// @router /info [get]
func (c *MainController) Test2() {
     //...
}
```
then:
```go
// test001
// @router /info/:id [get]
func (c *MainController) Test1() {
    //...
}
```
