### ISSUE TITLE
代码覆盖安装beego1.6出错

### ISSUE THREAD

**Issue by huangyuCN** [astaxie/beego#1596]
$ go install  github.com/astaxie/beego    
# github.com/astaxie/beego/context
github.com/astaxie/beego/context/input.go:44: undefined: session.Store

**Comment by astaxie** [comment]
```
go get -u github.com/beego/bee
go get -u github.com/astaxie/beego
```

**Comment by huangyuCN** [comment]
谢谢，谢老师
