### ISSUE TITLE
新建的 hello 项目，只在 main.go 加了一个 Notice 日志，beego.Notice("Networthicense is Correct!") 似乎没有输出任何内容

### ISSUE THREAD

**Issue by linux-mac** [astaxie/beego#1597]
新建的 hello 项目，只在 main.go 加了一个 Notice 日志
```
beego.Notice("Networthicense is Correct!") 
```
似乎没有输出任何内容
```
[root@git hello]# bee version
bee   :1.4.1
beego :1.6.0
Go    :go version go1.5.3 linux/amd64
```

好像 beego 1.5.0 是会输出的，不知道我错过了什么%...

![snip20160121_1](https://cloud.githubusercontent.com/assets/6309187/12480186/7ad41816-c07b-11e5-8e66-fa95f54d4c5a.png)

**Comment by astaxie** [comment]
yea, init the log in the beego.Run

**Comment by linux-mac** [comment]
sorry, I don't know what shoud i do?

**Comment by ysqi** [comment]
hi linux-mac, You need exec bee.Run before use everythings about beego.
But you can use other way:
1. use fmt.Println('')
2. create  yourself logger , see :http://beego.me/docs/module/logs.md
```

**Comment by astaxie** [comment]
@linux-mac it looks like beego's problem. we will fix in 1.6.1

**Comment by linux-mac** [comment]
I am looking forward to the release of the 1.6.1 version.

**Comment by youngsterxyf** [comment]
@astaxie Can I try this ?

**Comment by astaxie** [comment]
@youngsterxyf yea, Go for it

**Comment by linux-mac** [comment]
@youngsterxyf yea! You fixed it.

**Comment by linux-mac** [comment]
![www1](https://cloud.githubusercontent.com/assets/6309187/12528591/2d98d6ac-c1d6-11e5-941d-b05d957c1ccd.jpg)
