### ISSUE TITLE
beego 1.6 中 beego.AppConfig 的BUG

### ISSUE THREAD

**Issue by lisijie** [astaxie/beego#1601]
在 main 函数里面 beego.AppConfig.Set("version", "1.0")，然后在控制器 beego.AppConfig.String("version") 取不到。config 的 map 相关的key不见了。

**Comment by youngsterxyf** [comment]
@astaxie I think this may be a bug。

![image](https://cloud.githubusercontent.com/assets/834231/12519299/036cb78e-c179-11e5-953d-97b36c54da92.png)

this line will drop the config set in main function using  `beego.AppConfig.Set`
