### ISSUE TITLE
Context.Abort acts weird.

### ISSUE THREAD

**Issue by boombuler** [astaxie/beego#1617]
Hi,

when I call Context.Abort, the status code is ignored, then it panics with the body, which may contain a status code as string, which then will be converted to the corresponding error page, which is send to the client with status code 200. 
I was expecting the same behavior as Controller.CustomAbort

**Comment by osleg** [comment]
+1

**Comment by youngsterxyf** [comment]
@astaxie When the runmode is not dev,  After handling Context.Abort, the http response status code is 200, maybe this is wrong, i think it should be 500

**Comment by boombuler** [comment]
@youngsterxyf it should return the statuscode passed as argument...
if i call:

```go
Ctx.Abort(http.StatusBadRequest, "")
```

I would expect the client to recieve a message with 400... Not 500 and not 200... 
And having a different behavior in dev mode don't make it any better...

**Comment by youngsterxyf** [comment]
@boombuler Yes, I have fix it.

![image](https://cloud.githubusercontent.com/assets/834231/12678009/85871436-c6d7-11e5-9761-519bbf966d86.png)

**Comment by boombuler** [comment]
@youngsterxyf I've seen it, thats why I deleted my last comment. Thanks for this ;)

**Comment by xionglun** [comment]
Does it still not fixed yet?

**Comment by astaxie** [comment]
fixed in beego1.7
