### ISSUE TITLE
现在run的时候只能是http协议，建议新增tcp协议

### ISSUE THREAD

**Issue by lchjczw** [astaxie/beego#1618]
http协议作为后端或者api已经够了，但是如果一个client只支持tcp，那么beego的就不能监听tcp端口，比如作为物联网的设备服务器，设备联网，只支持tcp协议，都是二进制的数据，这些tcp协议的应用场景，能支持就好了
1、新增tcp监听端口
2、同时支持监听http和tcp最好，对有些应用场景，将不用一个额外的通讯，开发更加简单
3、同时支持监听http和tcp，beego将能够成为大部分服务端的开发工作，以后如果新增mqtt等协议的支持，就是100个赞都不够啊
4、也就是说能够继承beego的可扩展性，如果beego在目前使用的http协议，只是其中一种而已，能够轻松的定制其他协议，将给beego带来更广阔的遐想空间

希望谢大思考下我的建议，目前beego大部分只是用在web或者一些后端，基本都是基于http协议的，如果扩展到物联网等大部分通过tcp进行数据传输的行业，基本上就不会选用beego了

**Comment by fuxiaohei** [comment]
beego专注的是web方面的开发

web 是基于 http 协议的体系，有规范化的传输协议格式。

如果要基于 tcp 的话，需要自己定义传输内容格式。或者使用别的定义好的协议规范比如thrift hprose

这个是完全不同的两个领域，很难做到支持。

推荐使用 hprose 来做协议规范的支持

**Comment by Think-Jumper** [comment]
如果我想用beego来做总服，管理各个分服，进行负载均衡，这个时候我就需要beego做的总服跟各个分服进行数据验证联通，要用tcp来弄，我需要肿么办呢？
