### ISSUE TITLE
this.Ctx.Input.Params()

### ISSUE THREAD

**Issue by waterem** [astaxie/beego#1620]
看了源文件这个函数
func (input *BeegoInput) Params() map[string]string {
	m := make(map[string]string)
	for i, v := range input.pnames {
		if i <= len(input.pvalues) {
			m[v] = input.pvalues[i]
		}
	}
	return m
}
意思是，返回所有的GET参数值列表，但在调用
	for k, v := range this.Ctx.Input.Params() {
		fmt.Print(k, v)
	}
却没有任何显示
测试URL
?id=123&ik=1&ip=33&name=water&domain=test.com&alias=abc.com,tac.com
是我哪里错了吗？

**Comment by astaxie** [comment]
params means url param, like /:id/:user/aaa

if you want get the get params, please use `Context.Request.Form`
