### ISSUE TITLE
Error when try to install BEEGO

### ISSUE THREAD

**Issue by drexplos** [astaxie/beego#1623]
I am very new with GO, and when I tried to install the framwork beego on my Windows 8 Desktop or in a VirtualBox with Debian8 I had the same error:

sergi@odoo:~$ go get github.com/astaxie/beego

github.com/astaxie/beego
work/src/github.com/astaxie/beego/tree.go:144: syntax error: unexpected range, expecting { work/src/github.com/astaxie/beego/tree.go:155: syntax error: unexpected else, expecting semicolon or newline work/src/github.com/astaxie/beego/tree.go:157: non-declaration statement outside function body work/src/github.com/astaxie/beego/tree.go:158: non-declaration statement outside function body work/src/github.com/astaxie/beego/tree.go:159: non-declaration statement outside function body work/src/github.com/astaxie/beego/tree.go:160: syntax error: unexpected } work/src/github.com/astaxie/beego/tree.go:257: syntax error: unexpected range, expecting { work/src/github.com/astaxie/beego/tree.go:267: syntax error: unexpected else, expecting semicolon or newline or } work/src/github.com/astaxie/beego/tree.go:283: syntax error: unexpected }

**Comment by astaxie** [comment]
what's your go version? 

it looks we use the new feature from Go 1.4

**Comment by youngsterxyf** [comment]
https://golang.org/doc/go1.4#language

![image](https://cloud.githubusercontent.com/assets/834231/12552676/2a574ef4-c3ae-11e5-83af-2886fb2ef8b0.png)

**Comment by astaxie** [comment]
yea, I will remove this dependency. beego should be works from Go1.3 which support sync.Pool

**Comment by youngsterxyf** [comment]
@astaxie :+1:

**Comment by ysqi** [comment]
@astaxie  Maybe all build and test need run  all Go1.3+  version .

**Comment by astaxie** [comment]
@ysqi yes, I already add Go1.3.3 1.4.3 1.5.3 in develop branch.

**Comment by tobegit3hub** [comment]
Thanks @astaxie . It works well in `1.4` but not in `1.3.3`.
