### ISSUE TITLE
How to make model around view?

### ISSUE THREAD

**Issue by Hepri** [astaxie/beego#1624]
I have model like

    type A struct {
       // some fields
    }

    func (this *A) TableName() string {
        return "a"
    }

also I have view inside my db defined this way:

    create view b as select * from a where foo = 'qwe'

So how can I use view B inside beego code without fully structure duplicate? Something like that do not work

    type B struct {
        A
    }
    
    func (this *B) TableName() string {
        return "b"
    }
 
Also quering by table "b" into slice of structure A do not work

    var arr_a []*A
    o.QueryTable("b").All(&arr_a)

**Comment by astaxie** [comment]
it's not support now
