### ISSUE TITLE
通过继承MainController 去取request中的参数出现问题

### ISSUE THREAD

**Issue by huangjiasingle** [astaxie/beego#1628]
通过继承MainController 去取request中的参数出现问题：
当request中的参数经过编码之后，在编码之后的参数中有符号：如 + 号，拿到的数据会忽略掉+号。
从而导致拿到的参数值不正确。比如：msg=562+5ZCN5qCh6aqM5aSx6LSl，而后台拿到的值却是：
562 5ZCN5qCh6aqM5aSx6LSl

**Comment by huangjiasingle** [comment]
希望得到回复

**Comment by astaxie** [comment]
please create the issue in English

**Comment by astaxie** [comment]
http://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20
