### ISSUE TITLE
value for create_captcha not a function

### ISSUE THREAD

**Issue by funnywwh** [astaxie/beego#1630]
azone:value for create_captcha not a function
Request Method:	GET
Request URL:	/
RemoteAddr:	127.0.0.1
Stack
D:/tools/go1.5.src/go/src/runtime/asm_amd64.s:437
D:/tools/go1.5.src/go/src/runtime/panic.go:423
D:/tools/go1.5.src/go/src/text/template/funcs.go:63
D:/tools/go1.5.src/go/src/text/template/template.go:171
D:/tools/go1.5.src/go/src/html/template/template.go:302
D:/weforpay/yibugps/code/yibugps-cheanbao/servercode/yibugps/src/github.com/astaxie/beego/template.go:200
D:/weforpay/yibugps/code/yibugps-cheanbao/servercode/yibugps/src/github.com/astaxie/beego/template.go:149
D:/weforpay/yibugps/code/yibugps-cheanbao/servercode/yibugps/src/github.com/astaxie/beego/controller.go:259
D:/weforpay/yibugps/code/yibugps-cheanbao/servercode/yibugps/src/github.com/astaxie/beego/controller.go:183
D:/weforpay/yibugps/code/yibugps-cheanbao/servercode/yibugps/src/app/controllers/server/api.go:46
D:/weforpay/yibugps/code/yibugps-cheanbao/servercode/yibugps/src/github.com/astaxie/beego/router.go:789
D:/tools/go1.5.src/go/src/net/http/server.go:1862
D:/tools/go1.5.src/go/src/net/http/server.go:1361
D:/tools/go1.5.src/go/src/runtime/asm_amd64.s:1696
beego 1.6.0 (beego framework)
golang version: go1.5

**Comment by astaxie** [comment]
@funnywwh please upgrade the beego latest master. it's a critical issue. So already hotfix it

**Comment by funnywwh** [comment]
@astaxie thank you
