### ISSUE TITLE
some log records are missing with beego

### ISSUE THREAD

**Issue by zjiash** [astaxie/beego#1635]
My codes are as follows:
```
beego.Info("test start")
// do some call
if test {
  beego.Info("test yes")
} else {
  beego.Info("test no")
}
```

In my log file, I can find  `test start` be logged, but sometimes I cannot find `test yes` or `test no` be logged (both cannot be found and there is no error in log file), which means some log records are missing in beego.
Is there anybody can help me? Thanks.

**Comment by astaxie** [comment]
what's your beego version?

**Comment by zjiash** [comment]
My beego version is 1.5.0

**Comment by astaxie** [comment]
did you use asyn or sync mode?

**Comment by zjiash** [comment]
I use `beego.BeeLogger = logs.NewLogger(1)` and set no async or sync parameter. I think use the default mode.

**Comment by astaxie** [comment]
try beego1.6 now. I have no idea on 1.5 now. As beego log default use async to output logs

**Comment by zjiash** [comment]
I find the reason and there is a panic of http.Client in `// do some call` codes. It is strange that there is no any tips for the panic with beego. Is there any solution for this cases.
many thanks for your help.
