### ISSUE TITLE
Flash functionality doesn't work as expected

### ISSUE THREAD

**Issue by artuross** [astaxie/beego#1642]
It looks like flash functionality in Beego does not work as expected.

When setting a flash

```go
flash := beego.ReadFromRequest(&c.Controller)

// ...

flash.Error("Error")
flash.Store(&c.Controller)
```

Cookie is then send to browser with Max-Age = 0 (below stripped response from Chrome Developer Console):

```
HTTP/1.1 302 Found
Location: /
Set-Cookie: BEEGO_FLASH=%00error%23BEEGOFLASH%23Error%00; Max-Age=0; Path=/
```

Next request does not contains new cookie:

```
GET / HTTP/1.1
Cookie: beegosessionID=381708642eb9dfbaa5ece91dfc14d178
```

**Comment by youngsterxyf** [comment]
@artuross Yes, i think you are right! Thanks!
