### ISSUE TITLE
orm.Raw()方法查询，如果表中包涵datetime类型的字段就会报错

### ISSUE THREAD

**Issue by adamwuyu** [astaxie/beego#1646]
beego里用sql查询：
_, err := o.Raw("select * from test").ValuesList(&maps, "id", "name")

如果表里有datetime类型就会报错：
sql: Scan error on column index 2: unsupported driver -> Scan pair: time.Time -> *string

**Comment by adamwuyu** [comment]
补充说明：用QueryRows()方法替换ValueList方法，则无此问题

**Comment by youngsterxyf** [comment]
@adamwuyu Maybe you can see this issue： #1547

**Comment by astaxie** [comment]
please use english to create issue
