### ISSUE TITLE
处理多文件上传时的bug。

### ISSUE THREAD

**Issue by yesidi** [astaxie/beego#1654]
func (c *Controller) GetFiles(key string) ([]*multipart.FileHeader, error) {
	if files, ok := c.Ctx.Request.MultipartForm.File[key]; ok {
		return files, nil
	}
	return nil, http.ErrMissingFile
}

当我使用上面这个方法的时候，如果stream流没有设置上传同时key又有值的话，c.Ctx.Request.MultipartForm.File[key] 这一句会直接提示 Handler crashed with error runtime error: invalid memory address or nil pointer dereference 

crash掉。。。这个问题有解决的方法？

**Comment by jemygraw** [comment]
You may just give your file a name :-P

**Comment by astaxie** [comment]
please use english to create issues
