### ISSUE TITLE
context module's CopyBody function fails with DELETE api call containing nil request body

### ISSUE THREAD

**Issue by calvinchengx** [astaxie/beego#1656]
// This causes a handler panic and failure. 
	r, _ := http.NewRequest("DELETE", url, nil)

	// Sending in an empty byte works
	data := []byte("")
	requestBody := bytes.NewBuffer(data)
	r, _ := http.NewRequest("DELETE", url, requestBody)

The error message (caused by a `nil` request body in our DELETE rest api call), shows:

```
2016/02/02 20:03:26 [router.go:854][C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:437
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:423
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/io/ioutil/ioutil.go:30
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:437
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:423
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:42
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/runtime/sigpanic_unix.go:24
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/io/io.go:427
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/bytes/buffer.go:173
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/io/ioutil/ioutil.go:33
2016/02/02 20:03:26 [router.go:860][C] /usr/local/Cellar/go/1.5.3/libexec/src/io/ioutil/ioutil.go:42
2016/02/02 20:03:26 [router.go:860][C] /Users/calvin/work/myproject/src/github.com/astaxie/beego/context/input.go:330
2016/02/02 20:03:26 [router.go:860][C] /Users/calvin/work/myproject/src/github.com/astaxie/beego/router.go:645
```

**Comment by jemygraw** [comment]
It seems I can not replay this error.

Fire:

```
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
)

func main() {
	r, err := http.NewRequest("DELETE", "http://localhost:8080/", nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	resp, err := http.DefaultClient.Do(r)
	if err != nil {
		fmt.Println(err)
		return
	}

	defer resp.Body.Close()

	io.Copy(os.Stdout, resp.Body)
}
```

Server Side:

```
beego.Router("/", &controllers.MainController{}, "delete:DeleteSomething")
```

Controller:

```
func (this *MainController) DeleteSomething() {
	beego.Debug(this.Ctx.Input.Method)
	this.Data["json"] = &struct {
		Name string
	}{
		"jemy",
	}
	this.ServeJson()
}
```

Would you please update to the latest version of beego and try again?

**Comment by calvinchengx** [comment]
I am using the latest version of beego (1.6).
And this is an issue in beego 1.5.0 as well.

This bug surfaces when `CopyRequestBody = true` in `app.conf`.  If `CopyRequestBody = false` in `app.conf`, nil request body for DELETE works.

nil request body for GET works whether CopyRequestBody is true or false.

**Comment by calvinchengx** [comment]
This is definitely the problem.

In fact, if I specifically, dynamically see my beego's server's CopyRequestBody setting to false before the DELETE with nil request body is sent to beego server, the DELETE with nil request body call will work without errors.

This works:-

	r, _ := http.NewRequest("DELETE", url, nil)

       // reads "true" because I want to be able to unmarshal my POST's request body
       // to my struct in my POST controller
	beego.Info(beego.BConfig.CopyRequestBody)  
	beego.BConfig.CopyRequestBody = false // dynamically set it to false
	beego.BeeApp.Handlers.ServeHTTP(w, r)

If I do not add in the `beego.BConfig.CopyRequestBody = false` line, the above-mentioned error occurs.

**Comment by calvinchengx** [comment]
Alternatively, adding in `&& r.Method != "DELETE"` in `github.com/astaxie/beego/router.go` line 643 works too.

	if r.Method != "GET" && r.Method != "HEAD" && r.Method != "DELETE" {
		if BConfig.CopyRequestBody && !context.Input.IsUpload() {
			context.Input.CopyBody(BConfig.MaxMemory)
		}
		context.Input.ParseFormOrMulitForm(BConfig.MaxMemory)
	}

**Comment by youngsterxyf** [comment]
I also don't replay this error. @calvinchengx 

I have add the config item `CopyRequestBody = true`，and add debug code：

![image](https://cloud.githubusercontent.com/assets/834231/12775839/106367fa-ca8c-11e5-9bb3-54cd0fbb98f0.png)

the output is:

![image](https://cloud.githubusercontent.com/assets/834231/12775850/22ae2eea-ca8c-11e5-91fd-94adae8e1a92.png)

no panic

**Comment by calvinchengx** [comment]
I am using NameSpace urls. Not sure if this is an issue.

**Comment by calvinchengx** [comment]
And I am using `beego.BeeApp.Handlers.ServeHTTP(w, r)` to serve the handlers.

If I run beego normally, it appears to work.

`beego.BeeApp.Handlers.ServeHTTP(w, r)` on the other hand does not handle this well unless I explicitly add in `CopyRequestBody = false`.

**Comment by youngsterxyf** [comment]
what is the `r`  in `ServeHTTP(w, r)`?

**Comment by youngsterxyf** [comment]
I think the way you use beego is wrong

**Comment by calvinchengx** [comment]
This is executed in the context of my url endpoint tests.

That is why I use `beego.BeeApp.Handlers.ServeHTTP(w, r)`.

Meaning that if I run "beego" normally, DELETE call works.
If I use `beego.BeeApp.Handlers.ServerHTTP(w, r)` where `r, _ := http.NewRequest("DELETE", url, nil)`, I get a panic unless I explicitly add in `beego.BConfig.CopyRequestBody = false // dynamically set it to false` before I call my beego test app (i.e. `beego.BeeApp.Handlers.ServerHTTP(w, r)`).

**Comment by youngsterxyf** [comment]
Oh, i know the reason. the `r` in `r, _ := http.NewRequest("DELETE", url, nil)` is the "request" at client side, not at the server side. the source code of `http.NewRequest` is：

![image](https://cloud.githubusercontent.com/assets/834231/12776732/73850a76-ca93-11e5-8790-e90e93034d78.png)

So the Body of `r` is just `nil`

**Comment by calvinchengx** [comment]
Yes - that's correct. I agree. 

But why does the test-initialised beego server `beego.BeeApp.Handlers.ServerHTTP(w, r)` not know how to handle this request `r` from client-side?

**Comment by youngsterxyf** [comment]
Maybe that is the design problem of `Request` type from `net/http`. the type of `request` at client side is same as the type of `request` at server side

**Comment by youngsterxyf** [comment]
So for testing, you can manually set the request `Body`

**Comment by calvinchengx** [comment]
Right. Like what I did:-

	// Sending in an empty byte works
	data := []byte("")
	requestBody := bytes.NewBuffer(data)
	r2, _ := http.NewRequest("DELETE", url, requestBody)

?

**Comment by youngsterxyf** [comment]
YES

**Comment by youngsterxyf** [comment]
But i think we can check `r.Body == nil` in `ServeHTTP` method before handling `r` to avoid this problem

**Comment by calvinchengx** [comment]
But what I don't understand is why

    beego.BeeApp.Handlers.ServeHTTP(w, r)

can't be updated to handle this?

And why does beego running normally exhibits no panic - everything works well with a normal, initialized beego server app.

**Comment by calvinchengx** [comment]
But i think we can check r.Body == nil in ServeHTTP method before handling r to avoid this problem
   
Right.

**Comment by youngsterxyf** [comment]
At server side, `net/http` call `ReadRequest` method to init `Request`

**Comment by youngsterxyf** [comment]
you can read the source code:

![image](https://cloud.githubusercontent.com/assets/834231/12777297/04fbcc26-ca97-11e5-9a55-53e024d533e2.png)

so the `Body` can not be `nil`
