### ISSUE TITLE
problem with router in 1.6.0

### ISSUE THREAD

**Issue by argentmoon** [astaxie/beego#1661]
1. beego.Handler("/captcha/*.png", ....)
2. beego.Router("/captcha/get", ...)

can't match the 2rd controller,
when change the line order, it works.

**Comment by youngsterxyf** [comment]
please give the target URL you test

**Comment by argentmoon** [comment]
`
package main

import (
	_ "code.taobao.org/wstc875/test/routers"
	"github.com/astaxie/beego"
)

// png controller
type PngController struct {
	beego.Controller
}

func (c *PngController) Get() {
	c.Ctx.WriteString("png called!")
}

// captcha controller
type CaptchaController struct {
	beego.Controller
}

func (c *CaptchaController) Get() {
	c.Ctx.WriteString("captcha called!")
}

func main() {
	beego.Router("/captcha/*.png", &PngController{})
	beego.Router("/captcha/get", &CaptchaController{})

	beego.Run()

	// visit http://127.0.0.1:8080/captcha/get?captcha_id=HT8tzXXdCNIGq8
	// will print png called!
}
`

this is test code

**Comment by argentmoon** [comment]
// png controller
type PngController struct {
	beego.Controller
}

func (c *PngController) Get() {
	c.Ctx.WriteString("png called!")
}

// captcha controller
type CaptchaController struct {
	beego.Controller
}

func (c *CaptchaController) Get() {
	c.Ctx.WriteString("captcha called!")
}

func main() {
	beego.Router("/captcha/*.png", &PngController{})
	beego.Router("/captcha/get", &CaptchaController{})

	beego.Run()

	// visit http://127.0.0.1:8080/captcha/get?captcha_id=HT8tzXXdCNIGq8
	// will print png called!
}

this is the test code

**Comment by argentmoon** [comment]
`
// png controller
type PngController struct {
	beego.Controller
}

func (c *PngController) Get() {
	c.Ctx.WriteString("png called!")
}

// captcha controller
type CaptchaController struct {
	beego.Controller
}

func (c *CaptchaController) Get() {
	c.Ctx.WriteString("captcha called!")
}

func main() {
	beego.Router("/captcha/*.png", &PngController{})
	beego.Router("/captcha/get", &CaptchaController{})

	beego.Run()

	// visit http://127.0.0.1:8080/captcha/get?captcha_id=HT8tzXXdCNIGq8
	// will print png called!
}
`

this is the test code

**Comment by youngsterxyf** [comment]
Thanks, I will try to check the problem

**Comment by youngsterxyf** [comment]
@argentmoon Maybe it's not a bug. You use the RESTful router, bug your urls are not RESTful

**Comment by argentmoon** [comment]
@youngsterxyf Thanks, I will go to learn more

**Comment by shenboran** [comment]
import /Users/shenboran/Documents/workspace/pkg/darwin_amd64/github.com/astaxie/beego.a: object is [darwin amd64 go1.5.2 X:none] expected [darwin amd64 go1.4.2 X:precisestack] 是不是 版本不兼容啊
