### ISSUE TITLE
Transaction handling for generated models

### ISSUE THREAD

**Issue by pjoe** [astaxie/beego#1662]
When generating models with the bee command, it will create functions for basic CRUD operations. These are also used from generated controllers. However because they always create a new orm, it is impossible to use these with transactions.

As an example of what is generated:
```go
func AddMyObject(m *MyObject) (id int64, err error) {
	o := orm.NewOrm()
	id, err = o.Insert(m)
	return
}
```

I've been manually changing these to something like:
```go
func AddMyObject(m *MyObject, orms ...orm.Ormer) (id int64, err error) {
	var o orm.Ormer
	if len(orms) > 0 {
		o = orms[0]
	} else {
		o = orm.NewOrm()
	}
	id, err = o.Insert(m)
	return
}
```

This allows to optionally pass in an orm that is part of a transaction.

It would be great however to have a better standard handling of transactions in generated models (and controllers)

**Comment by astaxie** [comment]
@pjoe I think the generate is only for 90% case cover. Also I think the transaction pass orm should handle by the user
