### ISSUE TITLE
Config EnableHTTPS should be renamed to HTTPSEnable

### ISSUE THREAD

**Issue by steamonimo** [astaxie/beego#1663]
To be consistent with "HTTPEnable" the parameter "EnableHTTPS" in the configuration should be renamed to "HTTPSEnable". This way it will also be consistent with "HTTPSCertFile" and "HTTPSKeyFile".

For this beego fix must be adjusted too.

BTW: In your current beego/config.go you still use "EnableHTTP" but according to bee fix this should be "HTTPEnable". Which makes more sense to me.

**Comment by youngsterxyf** [comment]
Rename `EnableHTTP` to `HTTPEnable` , `EnableHTTPS` to `HTTPSEnable` ? I think it don't need to

**Comment by youngsterxyf** [comment]
@steamonimo Maybe it's a problem of `bee`, not `beego`

**Comment by steamonimo** [comment]
But from the logic of the parameter naming it should be obvious that ALL parameters related to HTTP should start with HTTP and all related to HTTPS should start with HTTPS. EnableHTTP and EnableHTTPS do not follow this convention and because EnableHTTP was already renamed to HTTPEnable in bee fix I think it makes sense to make the transition to HTTPEnable and HTTPSEnable. So the mistake is not in bee but in the current naming.

**Comment by astaxie** [comment]
beego always use `Enable` as the prefix. like `EnableDocs`, `EnableAdmin`, `EnableFcgi`,`EnableErrorsShow`
