### ISSUE TITLE
SetSession can cause null pointer exception 

### ISSUE THREAD

**Issue by steamonimo** [astaxie/beego#1664]
If parameter SessionOn=false the call to SetSession will cause a null pointer exception. Perhaps this can be handled in a more friendly way like beego.trace without causing an exception.

**Comment by youngsterxyf** [comment]
More details please，such as panic stack

**Comment by steamonimo** [comment]
2016/02/05 12:00:51 [router.go:854][C] Handler crashed with error runtime error:
 invalid memory address or nil pointer dereference
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/runtime/asm_amd64.s:437
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/runtime/panic.go:423
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/runtime/panic.go:42
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/runtime/signal_windows.go:161
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/runtime/asm_amd64.s:437
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/reflect/value.go:432
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/reflect/value.go:300
2016/02/05 12:00:51 [router.go:860][C] .../router.go:777
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/net/http/server.go:1862
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/net/http/server.go:1361
2016/02/05 12:00:51 [router.go:860][C] c:/go/src/runtime/asm_amd64.s:1721

**Comment by ysqi** [comment]
@steamonimo  it is bug , I will fix it.

**Comment by astaxie** [comment]
I don't think we need to panic the error if it's not start the session.
