### ISSUE TITLE
请问 beego 可以和 react-router 配合使用吗?

### ISSUE THREAD

**Issue by oldfeel** [astaxie/beego#1665]
我想用 beego 框架写一个单页app,前端用到了 react-router,但是 beego 的路由覆盖了 react-router 路由,请问有什么办法可以关闭 beego 的部分路由吗?因为还要用 beego 写接口,所以还要保留一部分路由功能.

**Comment by youngsterxyf** [comment]
@oldfeel issue is for bug/feature, not for usage question. And using English is better. Thanks.
