### ISSUE TITLE
我遇到了一个程序端与数据库端时区不一致的问题，是BUG吗？

### ISSUE THREAD

**Issue by sheng** [astaxie/beego#1666]
是这样，在我更新数据库条目信息的时候发现本来在程序里是UTC+8时区的time.Time变量写进数据库的时候却是按照的UTC时区，也就是说写进数据库的时间比程序里的时间差了8个小时。

代码片段是这样：
```go
...
u.RegisterDatetime = time.Now()
fmt.Println(u.RegisterDatetime)
o.Update(&u)
...
```
终端输出的时间是：`2016-02-05 21:35:32`
而查询数据库时却发现写入的时间变成了：`2016-02-05 13:35:32`

数据库配置方面已经检查过了，确定时区时UTC+8没错，用数据库自带的`now()`函数插入的时间是正常的。

我的解决办法是：
```go
...
u.RegisterDatetime = time.Now().Add(8 * time.Hour)
o.Update(&u)
...
```
这样虽然写进数据库的时间正确了，但是程序里的时间却多出了8个小时。😔

```
OS X 10.11.3
Go 1.5.3
MySQL 5.7.10
Beego 1.6.0
```

**Comment by ysqi** [comment]
你好，@sheng 。这是因为时区问题，beego 默认使用的是 UTC 时间，具体参见: [文档](http://beego.me/docs/mvc/model/orm.md#%E6%97%B6%E5%8C%BA%E8%AE%BE%E7%BD%AE) 。

MySQL DB 可以在初始化时设置时区：
````
root:root@/orm_test?charset=utf8&loc=Asia%2FShanghai
```

**Comment by sheng** [comment]
@ysqi 已解决！多谢！😁
