### ISSUE TITLE
redis connect

### ISSUE THREAD

**Issue by zolter** [astaxie/beego#1667]
Hi,

I can use "gopkg.in/redis.v3" or "go-redis" from me controllers. Where should I place "redis connect"? 
I want to have 1 permanent redis connect (in all controllers/routes). How I can implement this in beego? 

Example, 

```
    redisclient := redis.NewClient(&redis.Options{
        Addr: "111.111.111.111:6379",
        Password: "", // no password set
        DB:       0,  // use default DB
    })
```

How I can use "redisclient" variable in all controller methods?

**Comment by kyawmyintthein** [comment]
HI @zolter, I don't know why you use redis for. But, you can create specific package for redis connection. may be in model folder or controller. for example, 

`package redispackage
import redis
func connect(){
  redis.connect(')
}`

Then, you can import that package to the controller where you want to use.

**Comment by zolter** [comment]
I use in redis sadd, smembers and other methods. I do not use redis to cache. 

I need have 1 connect to redis from backend application. If I create redis.connect() in method - all user request to this method create new connection to redis server. I do not want to have an excessive number of connections.

**Comment by pjoe** [comment]
@zolter: i think I would try using `beego.AddAPPStartHook`, maybe something like:
```go
...
var client redis.Client

func init() {
    beego.AddAPPStartHook(func() error {
        client = redis.NewClient(...)
        return nil
    })
}
```

**Comment by zolter** [comment]
Where I can read info about "AddAPPStartHook"? If I use your example (main.go), how I can access to "client" variable in controller methods? I'm sorry for disturbing you, but I realy don't find any information/examples about AddAPPStartHook or "hooks"

**Comment by pjoe** [comment]
@zolter Check godocs (or use the source Luke): https://godoc.org/github.com/astaxie/beego#AddAPPStartHook

If you do this in your own package you can export that var and then access everywhere, e.g.:

somepath/redisclient/init.go
```go
var Client redis.Client
...
```
somepath/controllers/somecontroller.go:
```go
import "somepath/redisclient"

func someControllerFunc() {
    redisclient.Client.someMethod(bleh, bleh, bleh)
}
```
