### ISSUE TITLE
<Ormer> table: `.int` not found, maybe not RegisterModel

### ISSUE THREAD

**Issue by playaer** [astaxie/beego#1672]
Hi
my models:
```
type Room struct {
	Id   int
	Name string `orm:"size(100)"`
	Desks []*Desk `orm:"reverse(many)"`
}

func (this *Room) TableName() string {
	return "room"
}
```
--------------------
```
type Desk struct {
	Id   int
	Name string `orm:"size(100)"`
	Room *Room  `orm:"rel(fk)"`
}

func (this *Desk) TableName() string {
	return "desk"
}
```

and my code:
```
	var rooms []models.Room
	o.QueryTable("room").RelatedSel().All(&rooms)

	for room := range rooms {
		o.LoadRelated(&room, "Desks")
	}
```

after run I have that error
`<Ormer> table: `.int` not found, maybe not RegisterModel`
when `o.LoadRelated(&room, "Desks")` called

**Comment by ysqi** [comment]
hi @playaer Are you register model ? such as like:
```go
func init() { 
    orm.RegisterModel(new(Room), new(Desk))
}
```

**Comment by playaer** [comment]
:)
Model registered
`func InitModels() {
//	orm.Debug = true
	orm.RegisterDataBase("default", "sqlite3", "data.sqlite")

	orm.RegisterModel(new(Desk))
	orm.RegisterModel(new(Room))
       .......
}`

**Comment by miraclesu** [comment]
@playaer 

```
    var rooms []models.Room
    o.QueryTable("room").RelatedSel().All(&rooms)

    for room := range rooms {
        o.LoadRelated(&room, "Desks")
    }
```

This code is wrong, ` for room := range rooms` the var `room` is the index of the slice `rooms`, not the object.

The right code is: `for _, room := range rooms`.
:)

**Comment by rsvijay2807** [comment]
Handler crashed with error <Ormer> table: `.` not found, make sure it was registered with `RegisterModel()`

I have the below code in my model

```
func (u *User) AddUser() int64 {
	db := orm.NewOrm()
	pk, _ := db.Insert(u)
	log.Println(u.UID)
	return pk
}

```
