### ISSUE TITLE
How to set a variable number of router parameters ?

### ISSUE THREAD

**Issue by SvSerg** [astaxie/beego#1678]
I'm sorry, this is not a bug or feedback
but I do not know where to ask.

I have a router in a variable number of parameters

```
/women/page:page([0-9]+)
/women/clothes/page:page([0-9]+)
/women/clothes/dresses/page:page([0-9]+)
/women/clothes/dresses/bright/.../etc/page:page([0-9]+)
```
Tell me please
How to make a parameter which could contain slashes,
then to be divided by a function Split?

I did so but did not work
```
/:categories([0-9a-zA-Z-/]+)/page:page([0-9]+) // [0-9a-zA-Z-/]+ does not work
categories := c.Ctx.Input.Param(":categories") // /women/clothes/dresses/bright
slice := string.Split("/women/clothes/dresses/bright", "/")
```

**Comment by youngsterxyf** [comment]
@SvSerg Maybe you can use URL encoding/decoding

**Comment by SvSerg** [comment]
@youngsterxyf 
I need to have a category in the segment of the path
must first be a dynamic number of categories then will parameters prefixed 
```
/:categories([0-9a-zA-Z-/]+)/page:page([0-9]+)
/:categories([0-9a-zA-Z-/]+)/brand-:brand([0-9a-zA-Z-]+)/page:page([0-9]+)
/:categories([0-9a-zA-Z-/]+)/brand-:brand([0-9a-zA-Z-]+)/size-:size([0-9a-zA-Z-]+)/page:page([0-9]+)
```

**Comment by ysqi** [comment]
@SvSerg  use  internal parameter `:splat` . such as :
```go

// PageDetail
// @router /*/page:page([0-9]+) [get]
// Match http://localhost:8080/women/clothes/dresses/bright/page234
func (m *MainController) PageDetail() {
	c := m.Ctx.Input.Param(":splat")
	p := m.Ctx.Input.Param(":page")
}

```
**Rule**
` /login/*/access` match `/login/2009/11/access`

**Comment by SvSerg** [comment]
@ysqi 
This is what me need :+1:
Thank you so much
I did not carefully read the documentation :flushed:
