### ISSUE TITLE
running beego in system.d no longer using httpport in conf ?

### ISSUE THREAD

**Issue by lundin** [astaxie/beego#1685]
Hi!

For some reason (and i really dont understand the correlation between them) i fail to run my beego app  1.6 with the specified httpport 80 in conf file, it always defaults to 8080. Running the main binary from console worked but never with the startup script in centos 7.

Reverted back to beego 1.5 and it started to work again. Checked many time if something already listen on port 80 but it didn't.

Very strange!

**Comment by IniZio** [comment]
try putting the line beego.BConfig.Listen.HTTPPort="80" in main.go?

**Comment by ysqi** [comment]
hi @lundin  please tell me your config info.

**Comment by astaxie** [comment]
@lundin here is my systemd config for gopherchina:

```
[Unit]
Description=gopherchina web initialization

[Service]
PIDFile=/tmp/gopherchina.pid
User=root
Group=root
WorkingDirectory=/var/www/gopath/src/github.com/gopherchina/2016
ExecStart=/bin/bash -c '/var/www/gopath/src/github.com/gopherchina/2016/2016'

[Install]
WantedBy=multi-user.target
```

I think you forget to set `WorkingDirectory`

**Comment by lundin** [comment]
Thanks guys, it seems to work now using the supplied config by astaxie, at least on this machine i am on right now. Will close for now and re-open if it surface again!
