### ISSUE TITLE
Tests fail due to magic

### ISSUE THREAD

**Issue by dlsniper** [astaxie/beego#1689]
Hi,

I'm currently very frustrated after losing two hours of trying to understand the following error:
```
2016/02/14 22:14:11 [router.go:854][C] Handler crashed with error can't find templatefile in the path:index.html 
```

It occurs here: https://circleci.com/gh/tobegit3hub/seagull/60

Please explain what's wrong with the code, why does it fail, where? How? What's the path that I'm supposed to use? Is it `<project-root>/views/index.html`? If so then where's the mistake as I'm using that exact path.

**Comment by dlsniper** [comment]
If I remove the call to the render function then nothing gets returned instead. But at least the template is loading

**Comment by tobegit3hub** [comment]
It seems not the problem of `templatefile` but the change of new API in beego 1.6.0. And I have fixed the syntax issue in https://github.com/tobegit3hub/seagull/issues/61

**Comment by dlsniper** [comment]
Ok, but still, I would prefer to have a more meaningful error message than a relative path.
