### ISSUE TITLE
panic: dial tcp: missing address

### ISSUE THREAD

**Issue by liuhong1happy** [astaxie/beego#1690]
panic: dial tcp: missing address

goroutine 1 [running]:
github.com/astaxie/beego.initBeforeHTTPRun()
	/Users/liuhong/gopath/src/github.com/astaxie/beego/beego.go:96 +0x64b
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/Users/liuhong/gopath/src/github.com/astaxie/beego/beego.go:55 +0x1c
main.main()
	/Users/liuhong/gopath/src/github.com/liuhong1happy/logistics-workflow/api/main.go:29 +0xf7

**Comment by JessonChan** [comment]
check your httpport filed in configure file
