### ISSUE TITLE
Collision between EnableGZip and Controller.Abort()

### ISSUE THREAD

**Issue by mlgd** [astaxie/beego#1693]
Usage of Controller.Abort() don't worked correcly when GZip is enabled and customs errors controllers are defined. 
Console send :
http: multiple response.WriteHeader calls

Sample controller :
```
func (this *MyController) Get() {
	this.Abort("401")
}
```

The only way, disable GZip in custom ErrorController :
```
func (this *ErrorController) Prepare() {
	this.Ctx.Output.EnableGzip = false
}
```

**Comment by JessonChan** [comment]
i can't repeat this bug on my bee new project,can you paste your bee version output and have a test a mini project?

**Comment by mlgd** [comment]
Download the project here : [http://dl.free.fr/jpiNLaBZx](http://dl.free.fr/jpiNLaBZx)
Run main.go
Access to http://localhost:8080/

Uncomment line 10 in controllers/errors.go
Run and access again

**Comment by JessonChan** [comment]
@mlgd  thanks for your demo ,i have find the bug and will fixed it soon.The bug is hidden in this line https://github.com/astaxie/beego/blob/master/controller.go#L289
