### ISSUE TITLE
Incorrect return value from BeegoInput.Session

### ISSUE THREAD

**Issue by mmindenhall** [astaxie/beego#1695]
The godoc for BeegoInput.Session says (input.go:321):

```go
// Session returns current session item value by a given key.
// if non-existed, return empty string.
```

However, all of the implementations of the `session.Store` interface return `nil` when a key is not found instead of an empty string.

I'm not sure whether this is a documentation error and nil is the intended value, or if the implementations need to be changed to return `""` instead of `nil`.

**Comment by ysqi** [comment]
hi @mmindenhall  all session provider return nil when a key is not found.  Need update documentation.
