### ISSUE TITLE
跨模版文件读取$变量？

### ISSUE THREAD

**Issue by xdxiaodong** [astaxie/beego#1697]
假设：  
模版文件A文件名为index.tpl  
模版文件B文件名为foot.tpl  
我在模版A内定义变量{{$x := "beego"}}  {{template "foot.tpl" .}}
然后在模版B内输出模版A内定义的变量{{print $x}}，编译的时候就会提示模版文件编译错误，找不到变量$x  
如果我是在模版A内输出{{print $x}}就不会报错，可以正常输出  
**是不支持这样使用，还是我用法不对呢？这个问题困扰我好几天了**

**Comment by youngsterxyf** [comment]
@xdxiaodong You can see my demo code:

**main.go**

```go
package main

import (
	"fmt"
	"html/template"
	"os"
)

func main() {
	t, err := template.ParseFiles("index.tpl", "foot.tpl")
	if err != nil {
		fmt.Println(err)
		return
	}
	err = t.Execute(os.Stdout, map[string]string{})
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

**index.tpl**

```
{{$x := "beego"}}
{{print .}}
{{template "foot.tpl" .}}
```

**foot.tpl**

```
{{print .x}}
```

To run this programe, the output is:

```
map[]
&lt;nil&gt;
```

**Comment by youngsterxyf** [comment]
@xdxiaodong submit new issue in English is better, thanks! :smile:
