### ISSUE TITLE
Why I could use http requset in https port and get a confusing page?

### ISSUE THREAD

**Issue by AG3** [astaxie/beego#1702]
I set http disable and https enable.
I'm using "bee run", the result is "listening to https port 10443",it's correct.
But, when I try to visit http://127.0.0.1:10443, beego returns a confusing page, which only have a few bytes of data, and have no meaning. I tried to use hex viewer to find out what is it, but seems like their really have no meaning.
Also, I can visit https://127.0.0.1:10443 correctly, only the crf file is not be trusted(I generated it myself).

What's that page's mean? Could I redirect every http request to https?

I'm using beego 1.6 and the latest bee. Ubuntu 15.04, and latest Firefox.

Thanks!

**Comment by astaxie** [comment]
@youngsterxyf could you please help to check it

**Comment by Rushit** [comment]
I am ready to fix it, If someone can point me what areas I should start looking for change.

**Comment by astaxie** [comment]
If you pipe the output into od, curl -k -3 http://localhost:10443 | od -A n -t x1, you get the following sequence of bytes 15  03  01  00  02  02  0a which is rendered/handled by the browser.

Which, according to https://code.google.com/p/go/issues/detail?id=2253, is TLS for "I didn't understand what you said."


http://stackoverflow.com/questions/23494082/golang-listenandservetls-returns-data-when-not-using-https-in-the-browser
