### ISSUE TITLE
一个基于Beego的Yar RPC框架的实现

### ISSUE THREAD

**Issue by imiskolee** [astaxie/beego#1704]
https://github.com/weixinhost/beego-yar

yar 框架是一个轻量的rpc框架。由PHP核心开发者[laruence](http://www.laruence.com)开发。
当前社区有以下语言支持：
1. PHP
2. C语言
3. Nginx模块
4. Java
5. Go

如果你的项目中有Yar，并且想迁往Golang的
如果你正在选择一款RPC框架的
可以关注一下这个

**Comment by astaxie** [comment]
crazy idea
