### ISSUE TITLE
template problem in 1.6 version

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1706]
I have two project folder, the one is working 1.5 (v1) and others is bee 1.6 generated file (v2)
both return different error while compiling and it's confusing
v1 return this error
I got this runtime error
2016/02/22 11:01:16 [router.go:853][C] the request url is  / 
2016/02/22 11:01:16 [router.go:854][C] Handler crashed with error can't find templatefile in the path:index.tpl 

v2 run successfully

and I have another controller that receive post
v1 return value in c.Ctx.Input.RequestBody
v2 return empty in c.Ctx.Input.RequestBody so return error

both have exactly same code and config, I have compared both in meld

**Comment by ysqi** [comment]
hi @goldalworming  can you give me detail code ?

**Comment by goldalworming** [comment]
this is first example
    func (c *MainController) Get() {

        c.Data["Domain"] = c.Ctx.Input.Domain()
        c.TplName  = "users.tpl"

        c.Layout = ""
        c.Render()
    }

and this is the second code
	func (c *AuthController) Login() {

		var data models.User
		fmt.Println(c.Ctx.Input.RequestBody)
		if err := json.Unmarshal(c.Ctx.Input.RequestBody, &data); err != nil {
			fmt.Println(err)
			c.Ctx.Output.SetStatus(400)
			c.Ctx.Output.Body([]byte("empty title"))
			return
		}
		...

this is 1.6 generated code print empty array, but the same code I have code in 1.5.1 works fine and print byte array

**Comment by ysqi** [comment]
hi @goldalworming ,  I can't reproduce the problem.  print reqeust body is emtpy in 1.5.0 .
my test code
```html
<form method="post" action="/login">
          <input type="text" name="username"></input>
          <input type="password" name="password"></input>
          <button type="submit" value="">Login</button>
</form>
```
```go

func init() {
	beego.Router(`/`, &MyController{}, "*:Get")
	beego.Router(`/login`, &MyController{}, "*:Login")
}

type MyController struct {
	beego.Controller
}

func (m *MyController) Get() {
	m.TplNames = "index.tpl"
	m.Render()
}

func (c *MyController) Login() {
	  fmt.Println(c.Ctx.Input.RequestBody)
	 c.Ctx.WriteString(fmt.Sprintf("Action is %s, Get Request Body %q \n",
		c.Ctx.Input.Method(),
		c.Ctx.Input.RequestBody,
	))
}
```
Output:`Action is POST, Get Request Body "" `

**Comment by goldalworming** [comment]
I test it with curl
curl -X POST -H "content-type: application/json" localhost:8080/login -d '{"username" : "admin123", "password":"admin123"}'

return 
[123 34 117 115 101 114 110 97 109 101 34 32 58 32 34 97 100 109 105 110 49 50 51 34 44 32 34 112 97 115 115 119 111 114 100 34 58 34 97 100 109 105 110 49 50 51 34 125] in 1.5

and [] in 1.6

**Comment by ysqi** [comment]
I test again, Show your environmental information.
```
C:\Users\Think>bee version
bee   :1.3.0
beego :1.5.0
Go    :go version go1.5.1 windows/amd64

C:\Users\Think>curl -X POST -H "content-type: application/json" localhost:8081/login -d '{"username" : "admin123", "password":"admin123"}'
empty title
```

**Comment by goldalworming** [comment]
lmvm@lm17 ~/go/src/github.com/goldalworming/data$ bee version
bee   :1.4.1
beego :1.6.0
Go    :go version go1.5.3 linux/amd64

I just upgrade last sunday

**Comment by ysqi** [comment]
Oh my God !  I get empty value from body of request  in v1.5.0 & v1.6.0 . Are you sure it isn't empty in v1.5.0? Show my test code again.
```go
func init() { 
    beego.Router(`/login`, &MyController{}, "*:Login")
}

type MyController struct {
    beego.Controller
}
 
func (c *MyController) Login() { 
     c.Ctx.WriteString(fmt.Sprintf("Action is %s, Get Request Body %q \n",
        c.Ctx.Input.Method(),
        c.Ctx.Input.RequestBody,
    ))
}
```

**Comment by goldalworming** [comment]
I got different result, in version 1.5 it works fine and empty result in 1.6, but I don't understand what is the different..

**Comment by ysqi** [comment]
hey @goldalworming  , I hope you will be able to provide a streamlined project code problems found .
