### ISSUE TITLE
1.6版urlfor问题

### ISSUE THREAD

**Issue by jilili** [astaxie/beego#1710]
在1.6中出现了以下问题：

规则注册为：(1.6之前是好的，不知道规则是否有改变，吧第一条规则去掉就是可以的，1.4版本中是先匹配的静态规则。)
`beego.Router("/customers/:customerid/contact/", &customer.CustomerContactController{})`
`beego.Router("/customers/:customerid/contact/:contactid", &customer.CustomerContactController{})`

页面中如下使用：
`<a href="{{ urlfor "CustomerContactController.Get" ":customerid" $.Customer.Id ":contactid" .Contact.Id }}">修改</a>`

得到的结果是：
`http://127.0.0.1:12080/customers/a2d94bb9-ebdf-438d-b777-9f1045f605e4/contact?:contactid=fdc762b3-c425-437b-89b3-e80eb567eca9`

正确的结果应该是：
`http://127.0.0.1:12080/customers/a2d94bb9-ebdf-438d-b777-9f1045f605e4/contact/fdc762b3-c425-437b-89b3-e80eb567eca9`

**Comment by astaxie** [comment]
@ysqi could you help to check this issue

**Comment by ysqi** [comment]
@astaxie  ok.

**Comment by ysqi** [comment]
hi @jilili  it fixed by PR #1680 . You can pull Beego and use develop branch to check it.

**Comment by jilili** [comment]
develop版本现在没问题了。
