### ISSUE TITLE
在centos 7版本下编译beego程序，会报has no field or method ServeJson

### ISSUE THREAD

**Issue by w2m** [astaxie/beego#1711]
在controller中使用到ServeJson函数来返回json数据。在本地的 windows环境中编译没有问题，一上传到centos7环境中编译就会报不存在这个函数。

**Comment by JessonChan** [comment]
this method has been removed since beego 1.6,you need update your beego to the latest version

**Comment by Billgo** [comment]
@w2m ServeJson 改名为 ServeJSON 啦。你是不是没有更新这个方法呢？可以下载最新版本的 bee 工具，然后运行 bee fix 命令来修复一下。

**Comment by w2m** [comment]
@Billgo 谢谢，使用ServeJSON替换ServeJson后编译成功了。
