### ISSUE TITLE
Error on Travis CI for pull request

### ISSUE THREAD

**Issue by mlgd** [astaxie/beego#1715]
A recent change has been maded in go-couchbase project and that generate an error on Travis CI.
Test with Go 1.3.3 doesn't work : https://travis-ci.org/astaxie/beego/builds/110949040
The code below return a syntax error on Go 1.3.3 :
```
for range vsm.ServerList {
    gs := <-ch
    rv[gs.Server] = gs
}
```

**Comment by tleyden** [comment]
I'm one of the maintainers of go-couchbase -- do you guys have a hard requirement to run on go 1.3?

If not, can you just remove 1.3 from the .travis.yml file?

REF: https://github.com/couchbase/go-couchbase/issues/73

**Comment by astaxie** [comment]
@tleyden As many OSs still use the Go1.3 as the default version(yum install go). So it's better to compatible with Go1.3.

**Comment by tleyden** [comment]
I don't know the solution here.  I'm tempted to ask the go-nuts mailing list to ask for "best practices" around this .. I have a feeling their answer will be that OSs need to upgrade their Go version.
