### ISSUE TITLE
got  a error when updating

### ISSUE THREAD

**Issue by ykrl089** [astaxie/beego#1717]
astaxie go get -u github.com/astaxie/beego
# github.com/astaxie/beego
beego/tree.go:144: syntax error: unexpected range, expecting {
beego/tree.go:155: syntax error: unexpected else, expecting semicolon or newline
beego/tree.go:157: non-declaration statement outside function body
beego/tree.go:158: non-declaration statement outside function body
beego/tree.go:159: non-declaration statement outside function body
beego/tree.go:160: syntax error: unexpected }
beego/tree.go:257: syntax error: unexpected range, expecting {
beego/tree.go:267: syntax error: unexpected else, expecting semicolon or newline or }
beego/tree.go:283: syntax error: unexpected }

show message like above.

**Comment by JessonChan** [comment]
@ykrl089 update your go version first.
the beego master branch will be happy with go1.4.2 or above,or you can set your beego to develop branch.

**Comment by ykrl089** [comment]
go version v1.6

**Comment by JessonChan** [comment]
use `go get -v -x -u github.com/astaxie/beego` to get more detail

**Comment by ykrl089** [comment]
Ok，the golang was not update currectly

**Comment by JessonChan** [comment]
@astaxie this pr is closable.
