### ISSUE TITLE
api getOne return not found but status code Status Code:200 OK

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1720]
I have problem while requesting to api, the Status Code:200 OK but return  no row found
that confusing because value is not json but status code return 200

I hope you create consistent result, if status code 403, it's no problem to return non json value but status code 200 should return json

![screenshot from 2016-02-24 14 55 10](https://cloud.githubusercontent.com/assets/440256/13278958/efb68d76-db06-11e5-8083-4eba3154670c.png)

**Comment by astaxie** [comment]
is it related to your own logic code?
