### ISSUE TITLE
beego 1.6 file log issues

### ISSUE THREAD

**Issue by zjiash** [astaxie/beego#1734]
After upgrade from 1.3 to 1.6, the log is output to `./log` instead of `./logs/logs.log`.
The `./log` is redirect from console, but the file log set by `logs/logs.log` doesn't work after upgrade.
My code is as follows:
```
    beego.BeeLogger = logs.NewLogger(1)
	beego.SetLogger("file", `{"filename":"logs/logs.log", "level":0}`)
	beego.SetLogger("console", `{"level":0}`)
```
Thanks.

**Comment by zjiash** [comment]
And in dev mode, all logs are printed twice.

```
2016/03/02 19:49:53 [asm_amd64.s:1998][I] http server Running on :8888
2016/03/02 19:49:53 [asm_amd64.s:1998][I] http server Running on :8888
2016/03/02 19:49:53 [asm_amd64.s:1998][I] Admin server Running on :9999
2016/03/02 19:49:53 [asm_amd64.s:1998][I] Admin server Running on :9999
```

**Comment by JessonChan** [comment]
hi @zjiash ,i can't repeat this bug,so i need more detail,thanks.

**Comment by zjiash** [comment]
@JessonChan, I debug and find that,
`"level":0` will set the level LevelEmergency and the `WriteMsg` will return since `level > w.Level`.

**Comment by zjiash** [comment]
Same issue: https://github.com/astaxie/beego/issues/1078

**Comment by zjiash** [comment]
I think there is a default console logger.  The follow codes work well.
```
    beego.BeeLogger = logs.NewLogger(1)
    // beego.SetLogger("file", `{"filename":"logs/logs.log", "level":0}`)
    // beego.SetLogger("console", `{"level":0}`)
    beego.SetLogger("file", `{"filename":"logs/logs.log"}`)
```

**Comment by JessonChan** [comment]
@zjiash 
`"level":0` means the highest level,but why logs are printed twice?
