### ISSUE TITLE
设置多个Task在运行的时候经常会有每个任务重复执行两次

### ISSUE THREAD

**Issue by lmxliumingxiao** [astaxie/beego#1743]
有没有人遇到过这种问题。 
![image](https://cloud.githubusercontent.com/assets/13584205/13482530/d01bc5ee-e128-11e5-948e-78fbeb5a7c00.png)
![image](https://cloud.githubusercontent.com/assets/13584205/13482541/e6e8266e-e128-11e5-9a0b-d218ef696a9d.png)

**Comment by F0ur** [comment]
我刚想说。。。我也发生了这个问题
而且并不是每次都能重现
`
bee   :1.4.1
beego :1.6.0
Go    :go version go1.6 darwin/amd64
`

**Comment by F0ur** [comment]
in the admin.go
```go
if len(toolbox.AdminTaskList) > 0 {
    toolbox.StartTask()
}
```
so the  tasks  sometimes  run  twice

**Comment by astaxie** [comment]
Thanks for the update @F0ur
