### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by wei193** [astaxie/beego#1745]
goroutine 116 [running]:
runtime.throw(0x876ae40, 0x15)
	/opt/go/src/runtime/panic.go:530 +0x7f fp=0x190938a0 sp=0x19093894
runtime.mapassign1(0x85e5540, 0x18cf8980, 0x19093990, 0x1909393c)
	/opt/go/src/runtime/hashmap.go:445 +0x8b fp=0x19093900 sp=0x190938a0
github.com/astaxie/beego.BuildTemplate(0x8710c08, 0x5, 0x19093aac, 0x1, 0x1, 0x0, 0x0)
	/opt/GOPATH/src/github.com/astaxie/beego/template.go:153 +0x698 fp=0x19093a1c sp=0x19093900
github.com/astaxie/beego.(*Controller).RenderBytes(0x18f0ba40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/GOPATH/src/github.com/astaxie/beego/controller.go:259 +0x131d fp=0x19093b60 sp=0x19093a1c
github.com/astaxie/beego.(*Controller).Render(0x18f0ba40, 0x0, 0x0)
	/opt/GOPATH/src/github.com/astaxie/beego/controller.go:183 +0x46 fp=0x19093b90 sp=0x19093b60
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0x18cf8a20, 0xb5b32bd8, 0x191b4380, 0x18f99260)
	/opt/GOPATH/src/github.com/astaxie/beego/router.go:784 +0x1905 fp=0x19093d6c sp=0x19093b90
net/http.serverHandler.ServeHTTP(0x18c763c0, 0xb5b32bd8, 0x191b4380, 0x18f99260)
	/opt/go/src/net/http/server.go:2081 +0x156 fp=0x19093d9c sp=0x19093d6c
net/http.(*conn).serve(0x18e71c40)
	/opt/go/src/net/http/server.go:1472 +0xed8 fp=0x19093fc8 sp=0x19093d9c
runtime.goexit()
	/opt/go/src/runtime/asm_386.s:1585 +0x1 fp=0x19093fcc sp=0x19093fc8
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2137 +0x39

**Comment by JessonChan** [comment]
fixed at https://github.com/astaxie/beego/pull/1727
