### ISSUE TITLE
loading configuration will fail

### ISSUE THREAD

**Issue by steamonimo** [astaxie/beego#1746]
We use our beego app on linux as a service. In the previous release of beego we just called the executable and it worked. Now this executable complains that it will not find its configuration in ../conf/xy.ini anymore.

If we change the current directory to the directory of the beego app it will work again. But this is no option for our service scenario.

Please revert to the previous loading procedure of the conf file.

This loading behaviour is also responsible for our problem with bee in our development process - as described [here](https://github.com/beego/bee/issues/166).

**Comment by JessonChan** [comment]
@steamonimo this bug has bee fixed at develop branch,you can wait for the beego1.6.1 or change your beego to develop
