### ISSUE TITLE
并发时异常退出。

### ISSUE THREAD

**Issue by zhangchun** [astaxie/beego#1748]
程序是bee new的一个test工程。
单用户浏览没有问题，用ab压下就出异常了。
`2016/03/04 10:12:14 [asm_amd64.s:1998][I] http server Running on :8200
2016/03/04 10:12:15 [router.go:828][D] | GET        | /                                        | 1.302665ms       | match      | /                                        |
2016/03/04 10:12:15 [router.go:828][D] | GET        | /                                        | 1.708893ms       | match      | /                                        |
2016/03/04 10:12:15 [router.go:828][D] | GET        | /                                        | 751.649µs        | match      | /                                        |
2016/03/04 10:12:15 [router.go:828][D] | GET        | /                                        | 1.628675ms       | match      | /                                        |
2016/03/04 10:12:15 [router.go:828][D] | GET        | /                                        | 1.988417ms       | match      | /                                        |
2016/03/04 10:12:15 [router.go:828][D] | GET        | /                                        | 687.008µs        | match      | /                                        |
fatal error: concurrent map read and map write

goroutine 9 [running]:
runtime.throw(0xaa50a0, 0x21)
        /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8204b7478 sp=0xc8204b7460
runtime.mapaccess1_faststr(0x87a5c0, 0xc82014e150, 0xa2e860, 0x9, 0xc820123a88)
        /usr/local/go/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc8204b74d8 sp=0xc8204b7478
github.com/astaxie/beego.(*Controller).RenderBytes(0xc8204340d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/gowork/src/github.com/astaxie/beego/controller.go:265 +0x1893 fp=0xc8204b7760 sp=0xc8204b74d8
github.com/astaxie/beego.(*Controller).Render(0xc8204340d0, 0x0, 0x0)
        /home/gowork/src/github.com/astaxie/beego/controller.go:183 +0x4e fp=0xc8204b77c0 sp=0xc8204b7760
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc82014e240, 0x7f2fb7500130, 0xc820434000, 0xc8203fa000)
        /home/gowork/src/github.com/astaxie/beego/router.go:784 +0x1d7c fp=0xc8204b7b60 sp=0xc8204b77c0
net/http.serverHandler.ServeHTTP(0xc82009a180, 0x7f2fb7500130, 0xc820434000, 0xc8203fa000)
        /usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc8204b7bc0 sp=0xc8204b7b60
net/http.(*conn).serve(0xc82009ab00)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc8204b7f88 sp=0xc8204b7bc0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204b7f90 sp=0xc8204b7f88
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [chan receive]:
github.com/astaxie/beego.(*App).Run(0xc82000b590)
        /home/gowork/src/github.com/astaxie/beego/app.go:182 +0xabb
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
        /home/gowork/src/github.com/astaxie/beego/beego.go:67 +0x163
main.main()
        /home/gowork/src/test/main.go:9 +0x28

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [IO wait]:
net.runtime_pollWait(0x7f2fb7549be0, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202180d0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202180d0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820218070, 0x0, 0x7f2fb7549cd8, 0xc8203388e0)
        /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820038150, 0x453df0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820038150, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc82009a180, 0x7f2fb7549ca0, 0xc820038150, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc82009a180, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2098 +0x136
github.com/astaxie/beego.(*App).Run.func4(0xc82000b590, 0xc8201e6c78, 0x5, 0xc820218000)
        /home/gowork/src/github.com/astaxie/beego/app.go:174 +0x476
created by github.com/astaxie/beego.(*App).Run
        /home/gowork/src/github.com/astaxie/beego/app.go:180 +0xa98

goroutine 51 [chan send]:
text/template/parse.lexLeftDelim(0xc820464380, 0xb1da90)
        /usr/local/go/src/text/template/parse/lex.go:313 +0x25f
text/template/parse.(*lexer).run(0xc820464380)
        /usr/local/go/src/text/template/parse/lex.go:223 +0x52
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:216 +0x162

goroutine 8 [runnable]:
html/template.contextAfterText(0x0, 0x0, 0xc820320497, 0x14a, 0x169, 0x0, 0x0, 0x1)
        /usr/local/go/src/html/template/escape.go:664
html/template.(*escaper).escapeText(0xc8204c2100, 0x0, 0x0, 0xc82035a330, 0x0, 0x0)
        /usr/local/go/src/html/template/escape.go:598 +0x189
html/template.(*escaper).escape(0xc8204c2100, 0x0, 0x0, 0x7f2fb7548ae8, 0xc82035a330, 0x0, 0x0)
        /usr/local/go/src/html/template/escape.go:129 +0x31a
html/template.(*escaper).escapeList(0xc8204c2100, 0x0, 0x0, 0xc82035a300, 0x0, 0x0)
        /usr/local/go/src/html/template/escape.go:442 +0x1c6
html/template.(*escaper).escapeListConditionally(0xc8204bb380, 0x0, 0x0, 0xc82035a300, 0xc8204bafc8, 0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/escape.go:457 +0x4af
html/template.(*escaper).escapeTemplateBody(0xc8204bb380, 0x0, 0x0, 0xc8203461c0, 0x0, 0x0, 0xf)
        /usr/local/go/src/html/template/escape.go:575 +0x1e1
html/template.(*escaper).computeOutCtx(0xc8204bb380, 0x0, 0x0, 0xc8203461c0, 0x0, 0x0)
        /usr/local/go/src/html/template/escape.go:536 +0xc6
html/template.(*escaper).escapeTree(0xc8204bb380, 0x0, 0x0, 0x7f2fb7549d28, 0xc82035a300, 0xa2e860, 0x9, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/html/template/escape.go:529 +0x7a0
html/template.escapeTemplate(0xc82035a2a0, 0x7f2fb7549d28, 0xc82035a300, 0xa2e860, 0x9, 0x0, 0x0)
        /usr/local/go/src/html/template/escape.go:23 +0x2a5
html/template.(*Template).lookupAndEscapeTemplate(0xc82035a2a0, 0xa2e860, 0x9, 0xc82035a2a0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:141 +0x43d
html/template.(*Template).ExecuteTemplate(0xc82035a2a0, 0x7f2fb7549d00, 0xc8203ea070, 0xa2e860, 0x9, 0x8790c0, 0xc82035a0f0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:114 +0x4b
github.com/astaxie/beego.(*Controller).RenderBytes(0xc8203920d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/gowork/src/github.com/astaxie/beego/controller.go:265 +0x193f
github.com/astaxie/beego.(*Controller).Render(0xc8203920d0, 0x0, 0x0)
        /home/gowork/src/github.com/astaxie/beego/controller.go:183 +0x4e
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc82014e240, 0x7f2fb7500130, 0xc820392000, 0xc820360000)
        /home/gowork/src/github.com/astaxie/beego/router.go:784 +0x1d7c
net/http.serverHandler.ServeHTTP(0xc82009a180, 0x7f2fb7500130, 0xc820392000, 0xc820360000)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82009aa80)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e`

**Comment by JessonChan** [comment]
can you set your runmode to prod and have a test?

**Comment by zhangchun** [comment]
prod模式下没这个问题。

**Comment by JessonChan** [comment]
@zhangchun 
i have solve  this problem at #1752

**Comment by zhangchun** [comment]
好的，谢谢
