### ISSUE TITLE
test should FAIL but it always PASS

### ISSUE THREAD

**Issue by spartacusX** [astaxie/beego#1754]
In my folder tests/, there's one test file default_test.go generated by beego, here's the source:
`package test

import (
	_ "github.com/spartacusX/amRest/routers"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/astaxie/beego"
	. "github.com/smartystreets/goconvey/convey"
)

func init() {
	_, file, _, _ := runtime.Caller(1)
	apppath, _ := filepath.Abs(filepath.Dir(filepath.Join(file, ".."+string(filepath.Separator))))
	beego.TestBeegoInit(apppath)
}

// TestMain is a sample to run an endpoint test
func TestMain(t *testing.T) {
	r, _ := http.NewRequest("GET", "/v1/", nil)
	w := httptest.NewRecorder()
	beego.BeeApp.Handlers.ServeHTTP(w, r)

	beego.Trace("testing", "TestMain", "Code[%d]\n%s", w.Code, w.Body.String())

	Convey("Subject: Test Station Endpoint\n", t, func() {
		Convey("Status Code Should Be 200", func() {
			So(w.Code, ShouldEqual, 200)
		})
		Convey("The Result Should Not Be Empty", func() {
			So(w.Body.Len(), ShouldBeGreaterThan, 0)
		})
	})
}`
when run 'go test', it always show PASS, which should be FAIL, here's the result:
2016/03/04 16:50:51 [default_test.go:27][D] testing TestMain Code[%d]
%s 200
`<!DOCTYPE html>
<html lang="en">
        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                <title>Not Found</title>
                <style type="text/css">
                        * {
                                margin:0;
                                padding:0;
                        }

                        body {
                                background-color:#EFEFEF;
                                font: .9em "Lucida Sans Unicode", "Lucida Grande", sans-serif;
                        }

                        #wrapper{
                                width:600px;
                                margin:40px auto 0;
                                text-align:center;
                                -moz-box-shadow: 5px 5px 10px rgba(0,0,0,0.3);
                                -webkit-box-shadow: 5px 5px 10px rgba(0,0,0,0.3);
                                box-shadow: 5px 5px 10px rgba(0,0,0,0.3);
                        }

                        #wrapper h1{
                                color:#FFF;
                                text-align:center;
                                margin-bottom:20px;
                        }

                        #wrapper a{
                                display:block;
                                font-size:.9em;
                                padding-top:20px;
                                color:#FFF;
                                text-decoration:none;
                                text-align:center;
                        }

                        #container {
                                width:600px;
                                padding-bottom:15px;
                                background-color:#FFFFFF;
                        }

                        .navtop{
                                height:40px;
                                background-color:#24B2EB;
                                padding:13px;
                        }

                        .content {
                                padding:10px 10px 25px;
                                background: #FFFFFF;
                                margin:;
                                color:#333;
                        }

                        a.button{
                                color:white;
                                padding:15px 20px;
                                text-shadow:1px 1px 0 #00A5FF;
                                font-weight:bold;
                                text-align:center;
                                border:1px solid #24B2EB;
                                margin:0px 200px;
                                clear:both;
                                background-color: #24B2EB;
                                border-radius:100px;
                                -moz-border-radius:100px;
                                -webkit-border-radius:100px;
                        }

                        a.button:hover{
                                text-decoration:none;
                                background-color: #24B2EB;
                        }

                </style>
        </head>
        <body>
                <div id="wrapper">
                        <div id="container">
                                <div class="navtop">
                                        <h1>Not Found</h1>
                                </div>
                                <div id="content">
                                        <br>The page you have requested has flown the coop.<br>Perhaps you are here because:<br><br><ul><br>The page has moved<br>The page no longer exists<br>You were looking for your puppy and got lost<br>You like 404 pages</ul>
                                        <a href="/" title="Home" class="button">Go Home</a><br />

                                        <br>Powered by beego 1.6.0
                                </div>
                        </div>
                </div>
        </body>
</html>`

..
2 total assertions

PASS
ok      github.com/spartacusX/amRest/tests      0.360s

Anybody can help? Or any doc for writing tests with beego? Thanks

**Comment by JessonChan** [comment]
@spartacusX can you format your text first?
