### ISSUE TITLE
session的file引擎，出现取值为nil的情况

### ISSUE THREAD

**Issue by try876** [astaxie/beego#1769]
beego版本1.6，win和linux均会出现

代码片段：
uname := c.GetSession("uname")
if uname == nil {

}

具体现象就是在一段连续的时间内，uname有时能取到，有时为nil
11110111110111101111011111
上面1表示取到，0表示取值为nil

配置文件session片段:
SessionOn = true
SessionProvider = file
SessionName = abcssxx
SessionProviderConfig = ./tmp

**Comment by astaxie** [comment]
@ysqi @youngsterxyf  please follow up this weird problem. I don't know whether you can reproduce in local

**Comment by ysqi** [comment]
hey @astaxie  I can't reproduce  in local.

**Comment by ysqi** [comment]
hi @try876 ,能否提供个可测试的精简代码，因为我不确定你获取和设置Session的时机。

**Comment by try876** [comment]
我弄了个精简的，一开始测试没问题，我加了并发后，问题就来了，代码怎么上传？贴出来？

**Comment by try876** [comment]
先贴个主要代码吧
主页面：

<!DOCTYPE html>

<html>
<head>
  <title>Beego</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
a2();
setInterval("a2()",1000);
})

function a2(){
  //同时来两个，getSession就出现取值为nil的现象了
  a();
  a();
}
  function a(){
  $.ajax({
    url: "/json",
    success: function(data) {
      var d = eval("(" + data + ")");
      if(d.ok != 1){
        alert(d.msg)
        return
      }
    }
  });
}

  </script>
</head>

<body>
  <header>
    <h1 class="logo">Welcome to Beego</h1>
    <div class="description">
      Beego is a simple & powerful Go web framework which is inspired by tornado and sinatra.
    </div>
  </header>
  <footer>
    <div class="author">
     wait
    </div>
  </footer>
  <div class="backdrop"></div>
</body>
</html>

子页面的服务端代码
package controllers

import (
	"encoding/json"
	"github.com/astaxie/beego"
)

type JsonController struct {
	beego.Controller
}

func (c *JsonController) Get() {
	uname := c.GetSession("uname")

	if uname == nil {
		c.Ctx.WriteString(`{"ok":0,"msg":"未登录或未授权，请尝试重新登录"}`)
		return
	}

	type f3 struct {
		Ok int `json:"ok"`
	}
	var f = f3{
		1,
	}

	b, _ := json.Marshal(&f)
	c.Ctx.WriteString(string(b))
}

**Comment by youngsterxyf** [comment]
@try876 什么地方写的session?

**Comment by try876** [comment]
登录页面写的
```
package controllers

import (
	"encoding/json"

	"github.com/astaxie/beego"
)

type LoginController struct {
	beego.Controller
}

func (c *LoginController) Get() {
	logout := c.GetString("logout")
	if logout != "" {
		c.DelSession("uname")
	}

	c.TplName = "login.html"
}

func CheckUser(user, password string) bool {
	if user == "test" && password == "123" {
		return true
	}

	return false
}

func (c *LoginController) Post() {
	u := c.GetString("u")
	p := c.GetString("p")

	type ret struct {
		Code int
		Msg  string
	}

	var r ret

	if CheckUser(u, p) {
		c.SetSession("uname", u)
		r.Code = 1
	} else {
		r.Code = 0
		r.Msg = "用户密码错误"
	}
	b, _ := json.Marshal(&r)
	c.Ctx.WriteString(string(b))

}

```

**Comment by youngsterxyf** [comment]
@try876 我也没重现问题。

**Comment by ysqi** [comment]
hi @try876  我使用你的代码，尚未重新环境。我的运行环境：Mac + Go1.5beta1 + Beego 1.6.1 
测试代码： [issue.zip](https://github.com/astaxie/beego/files/170306/issue.zip)

**Comment by try876** [comment]
我下载了你打包的，确实无法重现。
但是把下边这句
document.getElementById("author").innerHTML +=d.ok;
改成
if(d.ok != 1){
        alert(d.ok + d.msg)
        return
}
过一会儿就弹出错误提示了

**Comment by try876** [comment]
尝试调试了一下，未得出结论，供大家参考

1、修改了代码：
// Get value from file session
func (fs *FileSessionStore) Get(key interface{}) interface{} {
	fs.lock.RLock()
	defer fs.lock.RUnlock()
	fmt.Println("AAAAAAAAAAA", key, fs.sid)
	if v, ok := fs.values[key]; ok {
		return v
	}
	fmt.Println("NNNNNNNNNNN", key, fs.sid)
	fmt.Println(fs.values)
	return nil
}

2、输出的内容：
2016/03/18 18:11:46 [1;34m[router.go:829][D] | POST       | /login
                      | 2.0001ms         | match      | /login
                 | [0m
2016/03/18 18:11:55 [1;34m[router.go:829][D] | GET        | /
                      | 5.0003ms         | match      | /
                 | [0m
AAAAAAAAAAA uname 344915d658b4ec3ade9da60860233b34
2016/03/18 18:11:55 [1;34m[router.go:829][D] | GET        | /json
                      | 1.0001ms         | match      | /json
                 | [0m
AAAAAAAAAAA uname 344915d658b4ec3ade9da60860233b34
2016/03/18 18:11:55 [1;34m[router.go:829][D] | GET        | /json
                      | 1.0001ms         | match      | /json
                 | [0m
AAAAAAAAAAA uname 344915d658b4ec3ade9da60860233b34
2016/03/18 18:11:55 [1;34m[router.go:829][D] | GET        | /json
                      | 2.0001ms         | match      | /json
                 | [0m
AAAAAAAAAAA uname 344915d658b4ec3ade9da60860233b34
2016/03/18 18:11:56 [1;34m[router.go:829][D] | GET        | /json
                      | 2.0001ms         | match      | /json
                 | [0m
AAAAAAAAAAA uname 344915d658b4ec3ade9da60860233b34
NNNNNNNNNNN uname 344915d658b4ec3ade9da60860233b34
map[]
2016/03/18 18:11:56 [1;34m[router.go:829][D] | GET        | /json
                      | 2.0001ms         | match      | /json
                 | [0m
AAAAAAAAAAA uname 344915d658b4ec3ade9da60860233b34
NNNNNNNNNNN uname 344915d658b4ec3ade9da60860233b34
map[]

**Comment by ysqi** [comment]
hey @try876 我修改成如下代码，运行半小时也未复现你所说的情况。按理你这种本机测试，1秒访问2次，不属于压力测试，应该是不会出现锁等待或者丢失 Session 情况。
```go
if(d.ok != 1){
alert(d.ok + d.msg)
return
}
```
