### ISSUE TITLE
how to convert model struct object to json when i develop api?

### ISSUE THREAD

**Issue by Jamlee** [astaxie/beego#1770]
![image](https://cloud.githubusercontent.com/assets/5196641/13633411/c067570c-e629-11e5-87de-c5c0426279f8.png)

By default, json will contain all field names of model containing password,. So i must create a new struct for it.

Have any better method ?

**Comment by JessonChan** [comment]
@Jamlee use json ignore "-"  tag on the password field

**Comment by Jamlee** [comment]
@JessonChan Oh, if i add a ignore "-" tag ,when creating table, password field will be ignored too

**Comment by JessonChan** [comment]
In my opinion,json tag is only be used by encode/json package.
