### ISSUE TITLE
For runmode problem

### ISSUE THREAD

**Issue by dylanlyu** [astaxie/beego#1772]
i change runmode dev to prod in app.conf  but error:

panic: you are in dev mode. So please set gopath
goroutine 1 [running]:
panic(0x84112e0, 0x1890a770)
	/usr/local/opt/go/libexec/src/runtime/panic.go:464 +0x326
github.com/astaxie/beego.(*ControllerRegister).Include(0x189deec0, 0x1890a760, 0x1, 0x1)

I doing wrong?

bee   :1.4.1
beego :1.6.0
Go    :go version go1.6 darwin/amd64

**Comment by astaxie** [comment]
this panic only happen in dev runmode if gopath not setting. but I can't get why this happen for you

**Comment by DylanLyu** [comment]
On the development machine has been set GOPATH but I have to run in a formal Server.
app.conf runmode is prod.
This error is generated in the official server
On the official server is not installed beego and golang
I doing wrong?

**Comment by ysqi** [comment]
hi @DylanLyu  Did you hava the `BEEGO_RUNMODE` environment variable ？

**Comment by DylanLyu** [comment]
Yes!
But beego 1.6.1 not tested.

**Comment by ysqi** [comment]
hey @DylanLyu  Beego will priority use the  BEEGO_RUNMODE environment variable if that is not empty. but not use app.config item runmode.

You can do like this :  
1. Set $BEEGO_RUNMODE = prod .
2. Delete $BEEGO_RUNMODE and  set runmode = prod in app.config.

**Comment by kumarsiva07** [comment]
@ysqi I am also getting same error. I am trying to run a beego app in eclipse. How do i set BEEGO_RUNMODE in eclipse?

**Comment by ysqi** [comment]
@kumarsiva07  why don't set run mode config in app.conf ? and I don't use eclipse , set GOPATH like this??
![image](https://cloud.githubusercontent.com/assets/2821085/15096488/b8473466-152c-11e6-90bf-42ad380dd129.png)

**Comment by xuesongbj** [comment]
App.conf set prod mode, reported the same error

**Comment by blackhu** [comment]
I had the same problem. But I've solved it.
Don‘t Use "GOOS=linux GOARCH=amd64 go build" .
The correct pack command is："bee pack -be=GOOS=linux -be=GOARCH=amd64", The resulting zip file contains a conf file that needs to be modified runmode（runmode = prod）.

**Comment by qizhelongdeyang** [comment]
@dylanlyu @xuesongbj so do me. Have you resolved this problem

**Comment by Soleilhao** [comment]
How to host Beego API on IIS10?
With the introduction at https://medium.com/@mossila/running-go-behind-iis-ce1a610116df
I can host beego api on iis by set the mode to "prod", BUT while i'm trying to test the api,  404 page was returned always... 

eg: 
	http://localhost:8080/v1/user/login?username=astaxie&password=11111    test success
	http://localhost/gapi/v1/user/login?username=astaxie&password=11111    got 404 page
