### ISSUE TITLE
beego1.6 alipay callback failed

### ISSUE THREAD

**Issue by damonchen** [astaxie/beego#1773]
when app use alipay app to pay the product, the alipay server will callback to my server, which contain a content-type of 'application/x-www-form-urlencoded; text/html; charset=UTF-8'. The content-type in golang is invalid. so the beego start session error.

you could check the in the play.golang.org with the follow code:

```  
package main

import "fmt"
import "mime"

func main() {
	c:="application/x-www-form-urlencoded; text/html; charset=UTF-8"
	
	c, _, err := mime.ParseMediaType(c)
	fmt.Println(err)
	fmt.Println(c)
}
```

**Comment by astaxie** [comment]
what can we do? it looks alipay use a wrong content-type

**Comment by damonchen** [comment]
yes, alipay use the wrong content-type, but I could not understand that why beego parse the form when geting session id.

session id should come from the cookie。https://www.owasp.org/index.php/Session_Management_Cheat_Sheet

**Comment by astaxie** [comment]
sessionID can come from cookie or form
