### ISSUE TITLE
当使用https启动服务器的时候，拿到不请求的header

### ISSUE THREAD

**Issue by kakazuo** [astaxie/beego#1774]
当我使用https启动服务器的时候，我在代码里面拿不到请求的header，我所使用的版本是：
bee   :1.4.1
beego :1.6.0
Go    :go version go1.6 darwin/amd64
拿header的代码是：
	email := ctx.Input.Header("AUTH_EMAIL")
	token := ctx.Input.Header("AUTH_TOKEN")
请问这个问题怎么解决，我最近一次升级了beego包，是不是新的包的bug？

**Comment by astaxie** [comment]
I can't get you

**Comment by kakazuo** [comment]
when I start server with https protocol, and listen on port 8443, I can not get request header in my app, the version I use is:
bee :1.4.1
beego :1.6.0
Go :go version go1.6 darwin/amd64

the code I get request header is:
email := ctx.Input.Header("AUTH_EMAIL")
token := ctx.Input.Header("AUTH_TOKEN")

my os version is : os x 10.11.3

protocol configuration:
#HTTPPort = 8080
EnableHTTP = false
EnableHTTPS = true
HTTPSCertFile = cert_files/server.crt
HTTPSPort = 8443
HTTPSKeyFile = cert_files/server.key

btw: if I start server with http protocol,  I can get request header

**Comment by damonchen** [comment]
you'd better replace _ to - in header name.

AUTH_EMAIL to AUTH-EMAIL
AUTH_TOKEN to AUTH-TOKEN

some http front(eg, nginx) may ignore name with _ .

**Comment by astaxie** [comment]
@damonchen good call. 

http://stackoverflow.com/questions/22856136/why-underscores-are-forbidden-in-http-header-names

**Comment by JessonChan** [comment]
@kakazuo it's a bug of go 1.6. the go author will make "_" be valid in next go version(may be 1.7)
and brandfitz has fixed this days 
https://github.com/golang/go/commit/b24c6fbfb3303f994ea8adfdf68436d95d2f841b
