### ISSUE TITLE
beego.BeeLogger.DelLogger("console")  Not Working

### ISSUE THREAD

**Issue by lon-yang** [astaxie/beego#1775]
I had deleted the log adapter of `console`, but it still running.
This is my codes:
`beego.SetLogger("file", `{"filename":"logs/test.log"}`)`
`beego.BeeLogger.DelLogger("console")`
`beego.Run()`

And I find that:
[https://github.com/astaxie/beego/blob/master/beego.go#L77](https://github.com/astaxie/beego/blob/master/beego.go#L77)
`initBeforeHTTPRun()` will add the `console` adapter again.

What can i do?

> Beego Version : 1.6.0

**Comment by astaxie** [comment]
fix in develop branch
