### ISSUE TITLE
v1.6.1在压力测试下出现这个错误。

### ISSUE THREAD

**Issue by zhangchun** [astaxie/beego#1783]
2016/03/11 18:08:32 [router.go:854][C] the request url is  /
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:472
2016/03/11 18:08:32 [router.go:855][C] Handler crashed with error write tcp 127.0.0.1:8080->127.0.0.1:50411: write: broken pipe
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/runtime/panic.go:426
2016/03/11 18:08:32 [router.go:861][C] /home/gowork/src/github.com/astaxie/beego/router.go:786
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/net/http/server.go:2081
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/net/http/server.go:1472
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:1998
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:472
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/runtime/panic.go:426
2016/03/11 18:08:32 [router.go:861][C] /home/gowork/src/github.com/astaxie/beego/router.go:786
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/net/http/server.go:2081
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/net/http/server.go:1472
2016/03/11 18:08:32 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:1998

**Comment by JessonChan** [comment]
look here: https://github.com/golang/go/issues/12931
it's not a bug of beego.

**Comment by zhangchun** [comment]
那同样的代码，我回到1.6去编译再测试并没有那个错误，你可以试试。

**Comment by JessonChan** [comment]
@zhangchun can you paste a demo project？

**Comment by zhangchun** [comment]
@JessonChan 就是bee new test一个测试工程,昨天用web bench测试的每次都出现，今天用ab试了下要多测试几次才有可能出现。

**Comment by astaxie** [comment]
@zhangchun could you tesing this code in you local with webbench and ab:

```
package main

import (
	"io"
	"net/http"
	"log"
)

// hello world, the web server
func HelloServer(w http.ResponseWriter, req *http.Request) {
	io.WriteString(w, "hello, world!\n")
}

func main() {
	http.HandleFunc("/hello", HelloServer)
	log.Fatal(http.ListenAndServe(":12345", nil))
}
```

from the error stack I don't think it's related to beego.

Under POSIX systems when a process received a signal and there is no signal handler or signal block mask exists for it, decision made by the kernel according to signal's default action.

**Comment by zhangchun** [comment]
@astaxie 这段代码测试是没问题的,没出现任何异常，奇怪的是同样的代码我在两台机测试都是1.6.1出现错误，1.6.0并没有出现。你可以按我的去测1.6.1跟1.6.0, bee new test 并改成prod模式再用webbench压500 10秒绝对会出异常，1.6.0下不会。之前我以前是自己的机器问题，后来在公司服务器上测试一样出问题。

**Comment by astaxie** [comment]
@JessonChan @youngsterxyf @ysqi could you reproduce this issue? i can't

**Comment by youngsterxyf** [comment]
@zhangchun @astaxie Sorry, i also can't reproduce it

**Comment by zhangchun** [comment]
@astaxie  @youngsterxyf 这么奇怪，你们用的什么系统，我在debian 64跟centos 64都测出同样的异常。
我弄了个阿里云测试环境你们看看，我在上面是能测出异常的，其它机都是这样。配置debian 64, 测试代码跟工具都在/root下。
ssh:112.74.125.17
user:root
pwd:Test12345

**Comment by youngsterxyf** [comment]
@zhangchun Thanks, maybe i have found the cause, i will try to fix.

**Comment by zhangchun** [comment]
@youngsterxyf ok,那我删除测试云了。

**Comment by youngsterxyf** [comment]
@zhangchun The cause is that sometimes benchmark tool will close the network connection before server fully sending response content. In this case, golang `net/http` package will return an error, beego before version 1.6.1 will ignore this error, but in 1.6.1, this error will raise a panic, and the panic will be recoverd to print a log.

**Comment by youngsterxyf** [comment]
@zhangchun we will talk about how to fix it.

**Comment by astaxie** [comment]
It looks beego start with a strict mode. It catch every error. As @youngsterxyf mentioned the benmark tool close the client connection. While beego will catch that and panic. I think we can ignore this error. But whether we need to show this error in our log. I still have no idea now. Just ignore now
