### ISSUE TITLE
beego:can't find templatefile in the path:index.tpl

### ISSUE THREAD

**Issue by intohole** [astaxie/beego#1786]
cd $GOPATH
bee new hello
cd hello 
go run main.go 
发生如题目的错误，麻烦谁知道 ；
ps：
     win7系统

**Comment by youngsterxyf** [comment]
@intohole Don't use `go run` to run beego app.

**Comment by intohole** [comment]
very thanks ! but i want to know why, can you explain it ?

2016-03-13 0:26 GMT+08:00 夏永锋 <notifications@github.com>:

**Comment by JessonChan** [comment]
go run will build a temporary executable file in your system $temp and run it,but the tpl files are not there.That's why.

**Comment by JessonChan** [comment]
Farther to say,your beego executable file and templates should in the same directory

**Comment by intohole** [comment]
thanks for your explain ,  i test my code  , it's can run ;
