### ISSUE TITLE
beego1.6.1 SetStaticPath有改变吗？

### ISSUE THREAD

**Issue by 3xxx** [astaxie/beego#1787]
升级到1.6版之前，我用beego.SetStaticPath("/m", "models")
进入路径127.0.0.1/m，可以看到文件，再点文件，进入127.0.0.1/m/文件名称
可是新版之后，可以看到文件，再点文件，路径中少了/m，变成127.0.0.1/文件名称

**Comment by youngsterxyf** [comment]
@3xxx @astaxie I have found out the cause, and will try to fix it.

**Comment by 3xxx** [comment]
Thank you.
