### ISSUE TITLE
While running tests, beego.AppConfig isn't set correctly 1.6.1

### ISSUE THREAD

**Issue by rahal** [astaxie/beego#1789]
Hello, 
After an upgrade to 1.6.1, my tests started to fail, as the config isn't loaded correctly anymore.
I have an app.conf in the directory  tests/conf  , before the upgrade my config was loaded correctly, now it seems that I have a "fakeConfigContainer" in my beego.AppConfig.
It was ok using 1.6.0.

here is a simple test that should not fail, but fails

`// TestMain is a sample to run an endpoint test
func TestConfig(t *testing.T) {
	Convey("Config AppName should not be empty\n", t, func() {
		So(beego.AppConfig.String("AppName"), ShouldNotBeEmpty)
	})
}
`
Am I missing something?

Thank you

**Comment by youngsterxyf** [comment]
@rahal Please give us the structure of your project. Thanks

**Comment by rahal** [comment]
@youngsterxyf , I have a regular beego project with all my tests inside a tests/  directory.
I use godep to keep beego source in my project repository.

I tryied to debug the issue and I'm getting here :  beego/config.go  ( 188 ) 
```go	
AppPath, _ = filepath.Abs(filepath.Dir(os.Args[0]))
......
appConfigPath = filepath.Join(AppPath, "conf", "app.conf")
if !utils.FileExists(appConfigPath) {
	AppConfig = &beegoAppConfig{innerConfig: config.NewFakeConfig()}
	return
}
``` 

What I think is happening, AppPath has a value like /var/folders/m1/9pmkm3416wzck67lymj_t93r0000gn/T/go-build327250791/_/Users/rahal/WORKSPACE/..../project/tests/_test   and therefore , it can't locate the configfile , and starts a  fakeconfig.

in 1.6.0 , the config parsing was done using ParseConfig()   
```go	
if AppConfigPath == "" {
	if utils.FileExists(filepath.Join("conf", "app.conf")) {
		AppConfigPath = filepath.Join("conf", "app.conf")
	} else {
		AppConfig = &beegoAppConfig{config.NewFakeConfig()}
		return
	}
}
AppConfig, err = newAppConfig(AppConfigProvider, AppConfigPath)
``` 
The config here was loaded from  conf/app.conf  or using AppConfigPath which was initialised in TestBeegoInit() 
So before, I had my config present  in tests/conf/app.conf  and the config was initialised correctly.

Ps : the problem is only present in while testing, it works correctly when I run the application.

Thank you.

**Comment by youngsterxyf** [comment]
@rahal @astaxie Sorry，i see，this is a bug，i will try to fix it.

**Comment by youngsterxyf** [comment]
@rahal @astaxie Two cause relates to this issue：

1. In file `config.go`, the `init()` function will change the current dir to working dir:

```go
func init() {
	AppPath, _ = filepath.Abs(filepath.Dir(os.Args[0]))

	os.Chdir(AppPath)
        ...
}
```

then in test mode, it dose not find the `conf/app.conf`.

2. In file `beego.go`, the `TestBeegoInit` function does not load config explicitly, but it may change the current dir back.

**Comment by rahal** [comment]
@youngsterxyf , @astaxie 
Sorry for my late reply, the fix : https://github.com/astaxie/beego/pull/1794/commits/549a39c4787afe9ab377d3373a271f94da3ba33a  , looks ok. But we still need to explicitly beego.TestBeegoInit . My problem is that I have some packages ( that are imported in my testcases , models for example) that depend on beego.AppConfig in the init phase, this will fail as my testcase's init function is run after my package's init.
This is who I fixed the issue ( I simply try to read the config from a relative path , in my case, it will be tests/conf/app.conf ) , and the config will be ready for my packages: 
 
```diff
diff --git a/config.go b/config.go
index 2761e7c..a62f779 100644
--- a/config.go
+++ b/config.go
@@ -117,7 +117,7 @@ var (
 func init() {
 	AppPath, _ = filepath.Abs(filepath.Dir(os.Args[0]))
 
-	os.Chdir(AppPath)
+	//os.Chdir(AppPath)
 
 	BConfig = &Config{
 		AppName:             "beego",
@@ -181,8 +181,13 @@ func init() {
 
 	appConfigPath = filepath.Join(AppPath, "conf", "app.conf")
 	if !utils.FileExists(appConfigPath) {
-		AppConfig = &beegoAppConfig{innerConfig: config.NewFakeConfig()}
-		return
+		// relative path
+		if utils.FileExists(filepath.Join("conf", "app.conf")) {
+			appConfigPath = filepath.Join("conf", "app.conf")
+		} else {
+			AppConfig = &beegoAppConfig{innerConfig: config.NewFakeConfig()}
+			return
+		}
 	}
 
 	if err := parseConfig(appConfigPath); err != nil {
```
Thank you for reviewing this patch.
