### ISSUE TITLE
set up beego in docker image

### ISSUE THREAD

**Issue by jy03189211** [astaxie/beego#1793]
<img width="569" alt="screenshot 2016-03-13 21 29 57" src="https://cloud.githubusercontent.com/assets/1472221/13730884/e5b27436-e964-11e5-974c-a258a2637b85.png">
<img width="1042" alt="screenshot 2016-03-13 21 31 48" src="https://cloud.githubusercontent.com/assets/1472221/13730886/ed6db6d6-e964-11e5-852f-1cbcfead18f5.png">
<img width="772" alt="screenshot 2016-03-13 21 33 42" src="https://cloud.githubusercontent.com/assets/1472221/13730888/f62d6ca8-e964-11e5-8b30-920000f4a978.png">

我在docker上运行了beego web服务器并映射端口8080到主机8006 为什么主机浏览器无法正常显示

**Comment by astaxie** [comment]
I have no idea
