### ISSUE TITLE
基于querystr的路由设置应该怎么定义

### ISSUE THREAD

**Issue by imiskolee** [astaxie/beego#1795]
在PHP框架中，都支持以querystr的方式进行路由定义。通常的为?controller=xxx&action=xxx

beego中该如何支持

**Comment by astaxie** [comment]
not support. There's no controller and action params. In beego you need to define the router like this:

http://beego.me/docs/mvc/controller/router.md

**Comment by imiskolee** [comment]
@astaxie  restful style only?

**Comment by astaxie** [comment]
no. all the normal style also support
