### ISSUE TITLE
Can I set max log files number when Maxsize is set?

### ISSUE THREAD

**Issue by fatedier** [astaxie/beego#1796]
It seems that logs module only remove old log files by MaxDays when Daily = true.

**Comment by ysqi** [comment]
So sorry. Not support  Max files number.

**Comment by JessonChan** [comment]
@fatedier yes,if you set the Daily=true,it only rotate by day.I would like to know what do you think about this.

**Comment by fatedier** [comment]
@JessonChan I only want to rotate files by filesize not daily and just reserve serveral files.However, there are so many log files when i set Daily=false, Maxsize=100MB.

**Comment by JessonChan** [comment]
@fatedier I'am not sure about your problem.There is a demo 

```
package main

import "github.com/astaxie/beego/logs"

func main() {
	log := logs.NewLogger(1e3)
	log.SetLogger("file", `{"filename":"test.log","maxsize":1024}`)
	bs := [1e3]byte{}
	for f := 0; f < 3; f++ {
		for i := 0; i < len(bs); i++ {
			bs[i] = 'A'
		}
		log.Debug(string(bs[0:]))
	}
	log.Debug("file 3")
}
```
![image](https://cloud.githubusercontent.com/assets/707691/13766446/e2448e0e-ea9c-11e5-8c0e-0a70dd539c54.png)

**Comment by fatedier** [comment]
@JessonChan
just like

```go
log.SetLogger("file", `{"filename":"test.log", "maxsize":1024, "maxnum":3, "daily":false}`)
```
and the log files will always be

```
test.log
test.001.log
test.002.log
```

**Comment by JessonChan** [comment]
@fatedier  may be you can update your beego first?
`go get -u github.com/astaxie/beego`
maxnum is not a config field in latest beego.

**Comment by fatedier** [comment]
yes, i know.That is what i want.

**Comment by JessonChan** [comment]
@fatedier ok, finally I understand your point :grimacing: 
I think we should not limit the max file number but limit the maximum of keeping file.

**Comment by fatedier** [comment]
yes...
