### ISSUE TITLE
ReadOrCreate error when primary key is uint32

### ISSUE THREAD

**Issue by philipdac** [astaxie/beego#1797]
Running the code _, _, err := o.ReadOrCreate(&varName, "Id") when Id type is uint32 on Beego 1.6.1 will generate an error:

2016/03/14 18:22:12 [router.go:855][C] Handler crashed with error reflect: call of reflect.Value.Int on uint32 Value 
2016/03/14 18:22:12 [router.go:861][C] /usr/local/go/src/runtime/asm_386.s:442 
2016/03/14 18:22:12 [router.go:861][C] /usr/local/go/src/runtime/panic.go:423 
2016/03/14 18:22:12 [router.go:861][C] /usr/local/go/src/reflect/value.go:884 
2016/03/14 18:22:12 [router.go:861][C] /media/sf_gopath/src/github.com/astaxie/beego/orm/orm.go:143
...

It is because in file "orm/orm.go", row 143, Beego ORM try to cast an uint32 type to integer:
row 143 ==> return false, ind.FieldByIndex(mi.fields.pk.fieldIndex).Int(), err

Please suggest how to fix it. Thanks.

**Comment by miraclesu** [comment]
@philipdac could you provide the varName struct?

**Comment by philipdac** [comment]
Hi MiracleSu. Below are the codes that created error that I reported:

MySQL table:
CREATE TABLE `test_table` (
  `Id` int(10) unsigned NOT NULL,
  `Name` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

Router:
beego.Router("/test1/:id:int", &controllers.Test1Controller{})

Model:
type Test1 struct {
    Id   uint32 `orm:"pk"`
    Name string
}

Controller:
func (ctrl *Test1Controller) Get() {

	o := orm.NewOrm()
	id, _ := ctrl.GetInt(":id")

	records := models.Test1{Id: uint32(id)}
	if _, _, err := o.ReadOrCreate(&records, "Id"); err != nil { // This is line 20. Error occurred here.
		println("Test1 id", id, "not found: ", err.Error())
		ctrl.Abort("500")
		return
	}

	ctrl.Data["records"] = records
	ctrl.TplName = "index.html"
}

Error:
2016/03/22 11:58:09 [router.go:854][C] the request url is  /test1/1 
2016/03/22 11:58:09 [router.go:855][C] Handler crashed with error reflect: call of reflect.Value.Int on uint32 Value 
2016/03/22 11:58:09 [router.go:861][C] /usr/local/go/src/runtime/asm_386.s:442 
2016/03/22 11:58:09 [router.go:861][C] /usr/local/go/src/runtime/panic.go:423 
2016/03/22 11:58:09 [router.go:861][C] /usr/local/go/src/reflect/value.go:884 
2016/03/22 11:58:09 [router.go:861][C] /media/sf_gopath/src/github.com/astaxie/beego/orm/orm.go:143 
2016/03/22 11:58:09 [router.go:861][C] /media/sf_gopath/src/blms/controllers/test1.go:20 
2016/03/22 11:58:09 [router.go:861][C] /media/sf_gopath/src/github.com/astaxie/beego/router.go:761 
2016/03/22 11:58:09 [router.go:861][C] /usr/local/go/src/net/http/server.go:1862 
2016/03/22 11:58:09 [router.go:861][C] /usr/local/go/src/net/http/server.go:1361 
2016/03/22 11:58:09 [router.go:861][C] /usr/local/go/src/runtime/asm_386.s:1662 

Hope you can re-create this err in your machine. Thanks.
