### ISSUE TITLE
oracle驱动QueryRows后无法自动解析

### ISSUE THREAD

**Issue by bigpear0201** [astaxie/beego#1800]
尝试使用oracle驱动,QueryRows后不能自动解析到struct中

`orm.RegisterDriver("oci8", orm.DROracle)`
`orm.RegisterDataBase("default", "oci8", "test/test@TESTDB")`
`nums, err := o.Raw("select name,type from table1").QueryRows(&res)`
返回的res中没有内容

导致此问题原因在于执行oracle查询后返回的columnname为大写，而框架中的snakeString方法返回的值为小写，导致columnsMp[col]无法匹配。

**Comment by miraclesu** [comment]
@bigpear0201 You can use column for a special field. Doc for column usage: http://beego.me/docs/mvc/model/models.md#column

@astaxie can close
