### ISSUE TITLE
bee api doc swagger相关问题 

### ISSUE THREAD

**Issue by ChongyuE** [astaxie/beego#1801]
问题一 ：beego 通过数据库自动创建的api项目 swagger 接口测试功能无法使用
创建方法如下 
![image](https://cloud.githubusercontent.com/assets/10123859/13807898/8bac6f82-eb9e-11e5-811d-b97fe1636f05.png)
具体症状如下
![image](https://cloud.githubusercontent.com/assets/10123859/13807919/a23ad5f4-eb9e-11e5-85b8-f8ab8c98d846.png)
相关代码 如下
![image](https://cloud.githubusercontent.com/assets/10123859/13807946/be02e8c6-eb9e-11e5-94dc-8c7a618accc5.png)
问题二 ：beego自动化文档 （不是根据数据库生成的项目）无法显示详细的data type

![image](https://cloud.githubusercontent.com/assets/10123859/13808007/ffe078a8-eb9e-11e5-851f-fb22611a1e06.png)
正常情况应该如下
![image](https://cloud.githubusercontent.com/assets/10123859/13808016/0938464c-eb9f-11e5-8242-ee546d582359.png)

求解决方案。

**Comment by lenye** [comment]
same problem, "try it out!" http request not "POST", it is "OPTIONS", WHY?
## request:
OPTIONS /v1/Todo/ HTTP/1.1
Host: 127.0.0.1:8080
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.116 Chrome/48.0.2564.116 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://localhost:8080/swagger/swagger-1/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8

## response:
HTTP/1.1 404 Not Found
Server: beegoServer:1.6.1
Date: Fri, 18 Mar 2016 09:00:32 GMT
Content-Length: 2000
Content-Type: text/html; charset=utf-8

##  configure:
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 linux/amd64

**Comment by oalpha** [comment]
same question~

**Comment by oalpha** [comment]
在开发文档->api自动化文档 最下面有说明
http://beego.me/docs/advantage/docs.md#%E5%8F%AF%E8%83%BD%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by oalpha** [comment]
你还需要检查下
你输入的网址是**localhost:8080 **还是**127.0.0.1:8080**，如果是前者，response content 里面的内容为no centent，输入127.0.0.1:8080会得到正确结果

**Comment by ChongyuE** [comment]
@oalpha  确实是这样。多谢 最下面的说明原本有看到 改了127.0.0.1 以后问题就解决了

**Comment by Jackwang520** [comment]
beego swagger生成的url，访问出现404
