### ISSUE TITLE
The method orm.Delete() can not delete data except for ID

### ISSUE THREAD

**Issue by huayi** [astaxie/beego#1802]
I think the method orm.Delete() could delete the data what according to my condition
This like the method orm.Read():
`err = o.Read(&user, "Name")`

**Comment by miraclesu** [comment]
@huayi yes, `orm.Delete()` can delete data only for primary key. It has not supported other field yet.
@astaxie improve?

**Comment by astaxie** [comment]
@miraclesu go for it. appreciate
