### ISSUE TITLE
CustomAbort whit custom text dose not set the provided error code

### ISSUE THREAD

**Issue by KilledKenny** [astaxie/beego#1804]
It appears that custom aborts no longer sets the provided status code.

This can be reproduced by creating a new project and replace the `controllers/default.go` `Get()` function whit:

```go
func (c *MainController) Get() {
     //c.CustomAbort(500, "500") // This will produce a 500 and a default page
     c.CustomAbort(500, "This wont produce a 500 code")
}
```

```
$ curl -k "127.0.0.1:8888" -i
HTTP/1.1 200 OK
Server: beegoServer:1.6.1
Date: Wed, 16 Mar 2016 15:53:55 GMT
Content-Length: 28
Content-Type: text/plain; charset=utf-8

This wont produce a 500 code
```

I traced it back to this change: https://github.com/astaxie/beego/commit/9a2696d216c3c873690c72dc301d4686eed265a4#diff-e30be89bfd41a0c219178028b9971a32L288
Changing it back worked for me however I have not verify it that would brake or reintroduce any previous bugs.

**Comment by JessonChan** [comment]
@KilledKenny we fix this bug and you can have a test on beego develop branch
