### ISSUE TITLE
orm.read() 在模型中主键为负数时，调用返回错误missed pk value？

### ISSUE THREAD

**Issue by zuoruochen** [astaxie/beego#1807]
type Channel struct {
	ChannelId	int	`orm:"pk";"column(channel_id)"`
	Abc		float64	`orm:"column(Abc)"`
}

channel := Channel{ChannelId:-777}
err := o.Read(&channel)
会返回missed pk value，将-777改为正数就没问题

**Comment by miraclesu** [comment]
It is a bug, we will fix it soon.
Thank you for your feedback :)
@astaxie
