### ISSUE TITLE
TestBeegoInit cant's read app cinfig

### ISSUE THREAD

**Issue by tingin** [astaxie/beego#1809]
conf/app.conf

[test]
sqldebug = false
dbdriver = sqlite3
dbconn = db/data.db

in unit test code
```golang
_, file, _, _ := runtime.Caller(1)
apppath, _ := filepath.Abs(filepath.Dir(filepath.Join(file, ".."+string(filepath.Separator))))
beego.TestBeegoInit(apppath)
fmt.Println(beego.AppConfig.String("AppName"))
```
but beego.AppConfig.String("AppName") is ""

**Comment by youngsterxyf** [comment]
@tingin this issue duplicate with issue #1789 , and the pr is https://github.com/astaxie/beego/pull/1794
