### ISSUE TITLE
Ctx.Output.Download not work 

### ISSUE THREAD

**Issue by mrcuix** [astaxie/beego#1815]
it will output "export" file name,match the router's name "export" !
 

 
 Router :
```
beego.Router("/export", &controllers.ExportController{})
```

In Controller :
```
type ExportController struct {
	beego.Controller
}
func (this *ExportController) Get() {
    this.Ctx.Output.Download("MyXLSXFile.xlsx","somefile.xlsx")
}
```

**Comment by youngsterxyf** [comment]
which version of beego do you use?

**Comment by mrcuix** [comment]
yes!  in beego 1.6.1 

go version go1.6 windows/amd64

**Comment by ysqi** [comment]
hey @mrcuix   It didn't print error info when file is not exist. It's not better.  You can check  whether a file exists before download file.
