### ISSUE TITLE
生成数据库表失败没有提示

### ISSUE THREAD

**Issue by milkbobo** [astaxie/beego#1817]
```go
type User struct {
	Id     string `orm:"pk"`
	Nick   string
	Info   string `orm:"null"`
	Hobby  string `orm:"null"`
	Email  string `orm:"unique"`
	Avator string `orm:"null"`
	Url    string `orm:"null"`

	Posts int

	Followers int
	Following int

	Regtime time.Time `orm:"auto_now_add"`

	Password string
	Private  int
}
```
 在生成这个数据库模型后，只是弹出没有建立表失败，也还有继续生成下一张表。所以希望能完善一下，如果生成表失败了，就抛出一个错误。

create table `user`
    -- --------------------------------------------------
    --  Table Structure for `jikeblog/models/class.User`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `user` (
        `id` varchar(3) NOT NULL PRIMARY KEY,
        `nick` varchar(255) NOT NULL DEFAULT '' ,
        `info` varchar(255),
        `hobby` varchar(255),
        `email` varchar(255) NOT NULL DEFAULT ''  UNIQUE,
        `avator` varchar(255),
        `url` varchar(255),
        `posts` integer NOT NULL DEFAULT 0 ,
        `followers` integer NOT NULL DEFAULT 0 ,
        `following` integer NOT NULL DEFAULT 0 ,
        `regtime` datetime NOT NULL,
        `password` varchar(255) NOT NULL DEFAULT '' ,
        `private` integer NOT NULL DEFAULT 0
    ) ENGINE=MyISAM;
2016/03/20 16:09:18 [asm_amd64.s:1998][I] http server Running on :8080

在数据库执行这个语句就显示了这个出错
Specified key was too long; max key length is 1000 bytes

主要希望在运行bee run的时候能显示失败原因

**Comment by astaxie** [comment]
please move this issue to bee
