### ISSUE TITLE
no console output when go run *.go

### ISSUE THREAD

**Issue by cch123** [astaxie/beego#1818]
beego ver 1.6.1
go ver 1.5.3

when i use go run *.go to start app，there is no console output
and after i run go build and start，it can output logs correctly

also，on go run*go mode，post data like annoymous array cannot be correctly fetched by ctx.input.requestbody

**Comment by JessonChan** [comment]
https://github.com/astaxie/beego/issues/1786
use `bee run`

**Comment by JessonChan** [comment]
when load config file failed,beego will load a fake configuration without any data https://github.com/astaxie/beego/blob/master/config.go#L183
