### ISSUE TITLE
router give wrong param value

### ISSUE THREAD

**Issue by tienthanh1993** [astaxie/beego#1819]
i have router like this
beego.Router("/category/:slug.:id, &MainController{}, "get:Category")

when visit /category/test.18 

in controller using c.GetInt64(":id") will receive 8.

i'm not sure if a bug or my wrong usage

**Comment by astaxie** [comment]
@youngsterxyf @ysqi please help to reproduce this issue

**Comment by ysqi** [comment]
@tienthanh1993  You can try like this, Need tell Beego `.` is not a special character.
```go
beego.Router("/category/:slug\\.:id", &MainController{}, "get:Category")
```
Math url `http://localhost:8080/category/test.18` the param list:
+ :slug = test
+ :id =18

**Comment by tienthanh1993** [comment]
@ysqi it's work correct. i found another way but this so strange i have never meet problem like this with others 

beego.Router("/category/:slug([A-z0-9-]+).:id([0-9]+)", &MainController{}, "get:Category")

**Comment by ysqi** [comment]
@tienthanh1993   you are right. But sometime i don't think more about it.  You only need to write the right code for you work.

**Comment by tienthanh1993** [comment]
hi @ysqi,
i found problem when using 
`beego.Router("/category/:slug\\.:id", &MainController{}, "get:Category")`
urlfor will generate wrong url like this 
` /category/one-two-three\.21`
