### ISSUE TITLE
How do i set up session to last until browser is closed?

### ISSUE THREAD

**Issue by artuross** [astaxie/beego#1820]
Hello,

I'd like to allow users of my application to login only for one session. That is, once they close the browser, they have to authenticate again. How can I accomplish this with Beego session module? I do not see to me able to locate such option.

**Comment by youngsterxyf** [comment]
@artuross Maybe you can use "Session cookie", you can refer to https://en.wikipedia.org/wiki/HTTP_cookie,

> A session cookie, also known as an in-memory cookie or transient cookie, exists only in temporary memory while the user navigates the website.[13] Web browsers normally delete session cookies when the user closes the browser.[14] Unlike other cookies, session cookies do not have an expiration date assigned to them, which is how the browser knows to treat them as session cookies.

**Comment by artuross** [comment]
@youngsterxyf Yes, this is the approach that I would love to use. I was just counting on built in flag that wouldn't set expiration date on beego.Controller.StartSession :)

**Comment by youngsterxyf** [comment]
@artuross you can set config item `SessionCookieLifeTime` to do that.
