### ISSUE TITLE
BeeLogger may lose message when shutting down application

### ISSUE THREAD

**Issue by fwang2002** [astaxie/beego#1825]
It may still happen on some machines even when Close is called.
It's better to wait for the internal go routine to finish when Close.

**Comment by JessonChan** [comment]
you logger is on asynchronous mode?

**Comment by fwang2002** [comment]
yes

**Comment by fwang2002** [comment]
It happens on one machine that go 1.5 is fine, but go 1.6 is not, when logged to console with async mode.

**Comment by youngsterxyf** [comment]
@fwang2002 which version of beego you are using?

**Comment by youngsterxyf** [comment]
@fwang2002 @JessonChan In version 1.6.1, i have submit a related pr https://github.com/astaxie/beego/pull/1639
