### ISSUE TITLE
UrlFor give wrong url

### ISSUE THREAD

**Issue by tienthanh1993** [astaxie/beego#1829]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.61

2. What operating system and processor architecture are you using (`go env`)?
darwin_amd64

3. What did you do?
my router
```
beego.Router("/admin/:model(user)/:id(list)", &admin.AdminUserController{}, "get:List")
beego.AutoRouter(&admin.AdminUserController{})
```
when using 
`beego.URLFor("AdminUserController.List")`

4. What did you expect to see?
/admin/user/list

5. What did you see instead?
/adminuser/list

**Comment by tienthanh1993** [comment]
i found another problem 

when using UrlFor multi times it will give url randomly like this 

```
beego.Router("/category/:slug\\.:id([0-9]+)", &MainController{}, "get:Category")
beego.AutoRouter(&MainController{})


fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
fmt.Printf("%v\n",beego.URLFor("MainController.Category",":slug",112233,":id",123))
```

// result 
/main/category?:id=123&:slug=112233
/main/category?:slug=112233&:id=123
/main/category?:slug=112233&:id=123
/category/112233\.123
/main/category?:slug=112233&:id=123
/main/category?:slug=112233&:id=123
/main/category?:slug=112233&:id=123

**Comment by saturn4er** [comment]
@tienthanh1993, I think the reason of your problem is that you use beego.AutoRouter which create route
/main/category. Beego stores routes in map, where order is not same each time when we iterate through it, that's why you get random url.

**Comment by astaxie** [comment]
As you define same endpoint to the one Function, `"MainController.Category"`. That would be correct IMO
