### ISSUE TITLE
Ctx.Input.RequestBody not converted from an JSON in the structure

### ISSUE THREAD

**Issue by SvSerg** [astaxie/beego#1830]
Maybe I'm doing something wrong?

```
bee   :1.4.1
beego :1.6.0
Go    :go version go1.6 linux/amd64
```

app.conf
```
appname = shop
httpport = 8282
runmode = dev
mysqluser = "root"
mysqlpass = "root"
mysqlurls = "127.0.0.1"
mysqldb = "shop"
copyrequestbody = true
```
Router:
```
beego.Router("/get-count-goods", &frontend.GoodController{}, "post:GetCountGoods")
```

Controller:
```
type MyStruct struct {
	Count int
}

func (c *GoodController) GetCountGoods() {

	spew.Dump("↓↓↓↓↓↓↓↓↓↓↓↓↓↓ c.Ctx.Input.RequestBody ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓", c.Ctx.Input.RequestBody)
	var response MyStruct
	json.Unmarshal(c.Ctx.Input.RequestBody, &response)
	spew.Dump("↓↓↓↓↓↓↓↓↓↓↓↓↓↓ JSON ↓↓↓↓↓↓↓↓↓↓↓↓↓↓", response)

	if c.IsAjax() {
		c.Data["json"] = &response
		c.ServeJSON()
	}
}
```

JavaScript:
```
data = {"Count": 123};
console.log(data);
$.ajax({
    type: "POST",
    dataType: "json",
    url: "/get-count-goods",
    data: data
}).done(function (response) {
    console.log(response);
});
```

Console:
```
"↓↓↓↓↓↓↓↓↓↓↓↓↓↓ c.Ctx.Input.RequestBody ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓"
([]uint8) (len=9 cap=512) {
 00000000  43 6f 75 6e 74 3d 31 32  33        |Count=123|
}
"↓↓↓↓↓↓↓↓↓↓↓↓↓↓ JSON ↓↓↓↓↓↓↓↓↓↓↓↓↓↓"
(frontend.MyStruct) {
 Count: (int) 0
}
2016/03/24 10:55:32 [router.go:828][D] | POST  | /get-count-goods | 27.891057ms | match | /get-count-goods | 
```
![beego_issue](https://cloud.githubusercontent.com/assets/5438422/14008829/d4d2241a-f1af-11e5-8f9c-64d75ea48224.png)

![beego_issue1](https://cloud.githubusercontent.com/assets/5438422/14008937/f10b6abe-f1b0-11e5-96c3-0768ab457195.png)

**Comment by tamoshius** [comment]
I might be wrong but did you try creating a MyStruct object MyStruct{}?

**Comment by SvSerg** [comment]
> I might be wrong but did you try creating a MyStruct object MyStruct{}?
```
response := MyStruct{}
```
so, too, does not work

**Comment by astaxie** [comment]
@SvSerg you need to post raw data. could you add add err check with the `json.Unmarshal(c.Ctx.Input.RequestBody, &response)`. I think there's some error happen

**Comment by SvSerg** [comment]
https://github.com/astaxie

Code:
```
type MyStruct struct {
	Count int
}

func (c *GoodController) GetCountGoods() {

	spew.Dump("↓↓↓↓↓↓↓↓↓↓↓↓↓↓ c.Ctx.Input.RequestBody ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓", c.Ctx.Input.RequestBody)

	response := MyStruct{}

	err := json.Unmarshal(c.Ctx.Input.RequestBody, &response)
	if err != nil {
		spew.Dump("******** ERROR ********", err)
	}

	spew.Dump("↓↓↓↓↓↓↓↓↓↓↓↓↓↓ JSON ↓↓↓↓↓↓↓↓↓↓↓↓↓↓", response)

	if c.IsAjax() {
		c.Data["json"] = &response
		c.ServeJSON()
	}
}
```

Log:
```
(string) (len=112) "↓↓↓↓↓↓↓↓↓↓↓↓↓↓ c.Ctx.Input.RequestBody ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓"
([]uint8) (len=9 cap=512) {
     00000000  43 6f 75 6e 74 3d 31 32  33                       |Count=123|
}

(string) (len=23) "******** ERROR ********"
(*json.SyntaxError)(0xc8203e6120)(invalid character 'C' looking for beginning of value)

(string) (len=90) "↓↓↓↓↓↓↓↓↓↓↓↓↓↓ JSON ↓↓↓↓↓↓↓↓↓↓↓↓↓↓"
(frontend.MyStruct) {
 Count: (int) 0
}
2016/03/24 13:25:55 [router.go:828][D] | POST | /get-count-goods  | 9.055003ms | match | /get-count-goods  | 
```

**Comment by astaxie** [comment]
@SvSerg please check your post data. 

invalid character 'C' looking for beginning of value

**Comment by SvSerg** [comment]
@astaxie 

Renamed field

JS:
```
data = {"Number": "123"};

$.ajax({
    type: "POST",
    dataType: "json",
    url: "/get-count-goods",
    data: data
}).done(function (response) {
    console.log(response);
});
```

Go:
```
	Number string
}

func (c *GoodController) GetCountGoods() {

	spew.Dump("↓↓↓↓↓↓↓↓↓↓↓↓↓↓ c.Ctx.Input.RequestBody ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓", c.Ctx.Input.RequestBody)

	response := MyStruct{}

	err := json.Unmarshal(c.Ctx.Input.RequestBody, &response)
	if err != nil {
		spew.Dump("******** ERROR ********", err)
	}
	spew.Dump("↓↓↓↓↓↓↓↓↓↓↓↓↓↓ JSON ↓↓↓↓↓↓↓↓↓↓↓↓↓↓", response)

	if c.IsAjax() {
		c.Data["json"] = &response
		c.ServeJSON()
	}
}
```

Log:
```
"↓↓↓↓↓↓↓↓↓↓↓↓↓↓ c.Ctx.Input.RequestBody ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓"
([]uint8) (len=10 cap=512) {
 00000000  4e 75 6d 62 65 72 3d 31  32 33                    |Number=123|
}
"******** ERROR ********"
(*json.SyntaxError)(0xc8202f2140)(invalid character 'N' looking for beginning of value)
 "↓↓↓↓↓↓↓↓↓↓↓↓↓↓ JSON ↓↓↓↓↓↓↓↓↓↓↓↓↓↓"
(frontend.MyStruct) {
 Number: (string) ""
}
```

**Comment by astaxie** [comment]
gbk to utf8?

**Comment by astaxie** [comment]
also please print the `c.Ctx.Input.RequestBody` with convert to string

**Comment by tamoshius** [comment]
I got running. You need to add CopyRequestBody = true to your app.conf

package controllers

import (
	"encoding/json"

	"github.com/astaxie/beego"
)

type MainController struct {
	beego.Controller
}

func (c *MainController) Get() {
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	c.TplName = "index.tpl"
}

type MyStruct struct {
	Count int `json:"count"`
}

func (c *MainController) GetCountGoods() {

	var err error

	var response MyStruct
	// response.Count = 123
	err = json.Unmarshal(c.Ctx.Input.RequestBody, &response)
	if err == nil {
		beego.Debug(response)
		c.Data["json"] = response
		c.ServeJSON()
	} else {
		beego.Debug("error: ", err)
	}
}

**Comment by astaxie** [comment]
@SvSerg could you try with curl:

```
curl -X POST http://localhost/get-count-goods -d  '{"Number": "123"}'
```

**Comment by goldalworming** [comment]
CopyRequestBody never go anywhere...beego 1.6.1 cannot read all my app.conf value include port
![screenshot from 2016-03-24 14 46 51](https://cloud.githubusercontent.com/assets/440256/14011227/82241456-f1cf-11e5-8377-9f8087307b95.png)

**Comment by tamoshius** [comment]
I got it ok. But I have beego built from dev branch
![screenshot-1](https://cloud.githubusercontent.com/assets/17831020/14011276/0974b4b2-f1a6-11e5-978d-945b00cf3cb7.png)

**Comment by SvSerg** [comment]
@astaxie 

how to set up the encoding `gbk to utf8` ?

via curl work

`url -X POST http://localhost:8282/get-count-goods -d  '{"Number": 123"}'`

Log:
```
(frontend.MyStruct) {
 Number: (string) (len=3) "123"
}
```
```
// c.Ctx.Input.RequestBody to string
"string(c.Ctx.Input.RequestBody)"
(string) (len=10) "Number=123"
```

**Comment by SvSerg** [comment]
As I understood from the browser come invalid characters ?

**Comment by astaxie** [comment]
you can track the string information from ajax.

**Comment by tamoshius** [comment]
you need to JSON.stringify
  <script>
var mystruct = {
  "count": 123
};

$.ajax({
    type: "POST",
    dataType: "json",
    url: "/get-count-goods",
    data: JSON.stringify(mystruct)
}).done(function (response) {
    console.log(response);
});

  </script>

**Comment by SvSerg** [comment]
@tamoshius 
Thank you, it works
I'll keep it on mind

**Comment by tamoshius** [comment]
You're welcome,Серж. I'm learning too :)

**Comment by SvSerg** [comment]
@tamoshius 
Thx!
I'm used to the dynamic languages, where it does not bother :)
