### ISSUE TITLE
multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by kevin-lv** [astaxie/beego#1834]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.6,beego1.61

2. What operating system and processor architecture are you using (`go env`)?
ubuntu14.04
win7

3. What did you do?
When i keep  F5 key pressed,the app crashed.
win7 test log ouput like this:

2016/03/27 19:56:44 [router.go:854][C] the request url is  / 
2016/03/27 19:56:44 [router.go:855][C] Handler crashed with error write tcp 127.0.0.1:9001->127.0.0.1:51816: wsasend: An established connection was aborted by the software in your host machine. 
2016/03/27 19:56:44 [router.go:861][C] D:/go/src/runtime/asm_amd64.s:472 
2016/03/27 19:56:44 [router.go:861][C] D:/go/src/runtime/panic.go:426 
2016/03/27 19:56:44 [router.go:861][C] E:/workspace/go/src/github.com/astaxie/beego/router.go:786 
2016/03/27 19:56:44 [router.go:861][C] D:/go/src/net/http/server.go:2081 
2016/03/27 19:56:44 [router.go:861][C] D:/go/src/net/http/server.go:1472 
2016/03/27 19:56:44 [router.go:861][C] D:/go/src/runtime/asm_amd64.s:1998 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 17.001ms         | match      | /                                        | 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 20.0011ms        | match      | /                                        | 
2016/03/27 19:56:44 http: multiple response.WriteHeader calls
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 21.0012ms        | match      | /                                        | 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 12.0007ms        | match      | /                                        | 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 19.0011ms        | match      | /                                        | 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 23.0013ms        | match      | /                                        | 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 18.001ms         | match      | /                                        | 
2016/03/27 19:56:44 [router.go:829][D] | GET        | /                                        | 26.0015ms        | match      | /                                        | 
panic: sync: negative WaitGroup counter

goroutine 5 [running]:
panic(0x88b680, 0xc082284bc0)
	D:/go/src/runtime/panic.go:464 +0x3f4
sync.(*WaitGroup).Add(0xc08227c8c8, 0x1)
	D:/go/src/sync/waitgroup.go:71 +0xd7
github.com/astaxie/beego/grace.(*graceListener).Accept(0xc0822c98c0, 0x375428, 0xc08225e480, 0x0, 0x0)
	E:/workspace/go/src/github.com/astaxie/beego/grace/listener.go:45 +0x1a1
net/http.(*Server).Serve(0xc08221b580, 0x375390, 0xc0822c98c0, 0x0, 0x0)
	D:/go/src/net/http/server.go:2117 +0x130
github.com/astaxie/beego/grace.(*Server).Serve(0xc08227c8a0, 0x0, 0x0)
	E:/workspace/go/src/github.com/astaxie/beego/grace/server.go:36 +0x69
github.com/astaxie/beego/grace.(*Server).ListenAndServe(0xc08227c8a0, 0x0, 0x0)
	E:/workspace/go/src/github.com/astaxie/beego/grace/server.go:75 +0x50e
github.com/astaxie/beego.(*App).Run.func2(0xc082285b90, 0xe, 0xc0820333c0, 0xc0822cb730)
	E:/workspace/go/src/github.com/astaxie/beego/app.go:128 +0xe0
created by github.com/astaxie/beego.(*App).Run
	E:/workspace/go/src/github.com/astaxie/beego/app.go:133 +0x9a9

ubuntu test log plese see attach

**Comment by kevin-lv** [comment]
![error](https://cloud.githubusercontent.com/assets/15275703/14065368/4c81f30e-f459-11e5-9797-544466fc4228.jpg)

**Comment by JessonChan** [comment]
response.WriteHeader calls is related to #1822

**Comment by kevin-lv** [comment]
I found if i set Graceful = true and keep F5 pressed, the app crashed.

**Comment by astaxie** [comment]
fixed in beego1.7.0
