### ISSUE TITLE
some puzzled

### ISSUE THREAD

**Issue by BPing** [astaxie/beego#1836]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
  1.6.1

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\workplace\library\gopath;F:\workplace\www\gowork
set GORACE=
set GOROOT=F:\workplace\resources\Go
set GOTOOLDIR=F:\workplace\resources\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```
3. What did you do?

beego changes go's currently running path  with the dir of "os.Args[0]"
```go
AppPath, _ = filepath.Abs(filepath.Dir(os.Args[0]))
os.Chdir(AppPath)
```
the value of os.Args[0] :
C:\Users\DREAM-~1\AppData\Local\Temp\go-build364476898\command-line-arguments\_obj\exe\main.exe

but my workplace‘s path is :F:\workplace\www\gowork\src

so i can't open the file with relative path,
like:"app/conf/app.conf"(F:\workplace\www\gowork\src\app\conf\app.conf)

i don't want to modify the source code .

**Comment by JessonChan** [comment]
https://github.com/astaxie/beego/issues/1789

**Comment by BPing** [comment]
the problem is  present  when I run the application,not for testing

**Comment by BPing** [comment]
it will have the same problem,even if I build a .exe file to my working directory,

**Comment by JessonChan** [comment]
@BPing go build will be ok and this has been fixed on develop branch
