### ISSUE TITLE
ini文件大小写敏感问题

### ISSUE THREAD

**Issue by Orefa** [astaxie/beego#1845]
beego version：1.6.1
Win7 SP1 64bit OS

app.conf内容
[LargeSystemCacheold]
Name=LargeSystemCache

执行如下语句后：

var iniconf, _ = config.NewConfig("ini", "app.conf")
iniconf.set("LargeSystemCacheold::Name","LargeSystemCache")
iniconf.SaveConfigFile("app.conf")

变成app.conf文件变成了如下内容：
[LargeSystemCacheold]
Name=LargeSystemCache

[largesystemcacheold]
name=LargeSystemCache
期望结果是：

[LargeSystemCacheold]
Name=LargeSystemCache

经查看ini.go文件：
ini.go的第108行出现如下语句
section = strings.ToLower(string(line[1 : len(line)-1])) // section name case insensitive
125行：key = strings.ToLower(key)

但400行的Set方法中，并不存在section 和key 的   ToLower行为

**Comment by ysqi** [comment]
@Orefa  你是否可PR修改？
