### ISSUE TITLE
"go run " no longer works

### ISSUE THREAD

**Issue by fireboy1919** [astaxie/beego#1846]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.5.3 darwin/amd64

Note that this isn't a problem for 1.6.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/rusty/golang/server/.godeps/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rusty/golang/server/.godeps:/Users/rusty/golang/server"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
Run "go run main.go" from a beego 1.6.1 generated source that has not been in any way modified, or use a 1.6.0 generated source and you'll get the same results.

A complete runnable program is good.

4. What did you expect to see?
I expected it to run.

5. What did you see instead?
It exits immediately without logging any errors.

Note that in order to use the annotation router, we have to generate those annotations by using "go run."  So this isn't simply a request in order to be able to debug; significant functionality has actually been removed.

**Comment by astaxie** [comment]
@fireboy1919 it should be fixed in develop branch
