### ISSUE TITLE
distinct different request information in log file

### ISSUE THREAD

**Issue by damonchen** [astaxie/beego#1847]
now, beego log all information to the console or file, but it doest not distinct the different request from the client.

when system get the lots of the requests from client, and the log could know which request come from, so it not easy to fix problem with the log.

plz, add the distinct information if you could.

**Comment by astaxie** [comment]
1. generate uuid in filter:

```
beego.InsertFilter("*", beego.BeforeExec, func(ctx *context.Context){
      ctx.Input.Data["requestid"] = UUID() // generate uuid
})
```

2. print the requestid in the log

```
beego.Info(ctx.Input.Data["requestid"], xxx)
```

**Comment by damonchen** [comment]
I need send request id to the log every time, it is ugly to solve the problem.

**Comment by astaxie** [comment]
The only thing can be done with this way. Look at the official blog http://blog.golang.org/context. It also need to pass the context to all the functions

**Comment by jaki2012** [comment]
still not so elegant to handler this issue.

logs.Info() specifies that the first parameter must be `format` interface{}, which really constrains us that, to preserved a position for the requestID.
