### ISSUE TITLE
Flash Message problem with Chrome and Firefox?

### ISSUE THREAD

**Issue by TomTom86** [astaxie/beego#1849]
** What version of Go and beego are you using (`bee version`)?**

_I using beego: 1.6.0 and Go 1.6_

**What operating system and processor architecture are you using (`go env`)?**

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\code
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**What did you do?**

I have some problem with flash message in this project

https://github.com/horrido/acme3

For exemple:

```
func (this *MainController) Register() {
	this.activeContent("user/register")

	if this.Ctx.Input.Method() == "POST" {
		flash := beego.NewFlash()
		u := user1{}
		if err := this.ParseForm(&u); err != nil {
			fmt.Println("cannot parse form")
			return
		}
		this.Data["User"] = u
		valid := validation.Validation{}
		if b, _ := valid.Valid(&u); !b {
			this.Data["Errors"] = valid.ErrorsMap
			return
		}
		if u.Password != u.Confirm {
			flash.Error("Passwords don't match")
			flash.Store(&this.Controller)
			return
		}
		h := pk.HashPassword(u.Password)

		//******** Save user info to database
		o := orm.NewOrm()
		o.Using("default")

		user := models.AuthUser{First: u.First, Last: u.Last, Email: u.Email}

		// Convert password hash to string
		user.Password = hex.EncodeToString(h.Hash) + hex.EncodeToString(h.Salt)

		// Add user to database with new uuid and send verification email
		key := uuid.NewV4()
		user.Reg_key = key.String()
		_, err := o.Insert(&user)
		if err != nil {
			flash.Error(u.Email + " already registered")
			flash.Store(&this.Controller)
			return
		}

		domainname := this.Data["domainname"]
		if !sendVerification(u.Email, key.String(), domainname.(string)) {
			flash.Error("Unable to send verification email")
			flash.Store(&this.Controller)
			return
		}
		flash.Notice("Your account has been created. You must verify the account in your email.")
		flash.Store(&this.Controller)
		this.Redirect("/notice", 302)
	}
```

```
func (this *MainController) Notice() {
	this.activeContent("notice")

	flash := beego.ReadFromRequest(&this.Controller)
	if n, ok := flash.Data["notice"]; ok {
		this.Data["notice"] = n
	}
}

```

Notice.tpl:

```
`<div id="content">
<p><font size="5">{{.notice}}</font></p>
</div>`
```

**What did you expect to see?**

_When i register an user I expect to see in notice page the flash Notice "Your account has been created. You must verify the account in your email."_

**What did you see instead?**

_It's work only with IE11, if i use Chrome or Firefox notice message is empty and i can't understand why. The issue exist only if i redirect the page (is it a cookie flash problem?), infact if i don't redirect to the notice page and i insert the flash.notice in the register page flash message works fine._

**Comment by astaxie** [comment]
@TomTom86 please update to beego1.6.1. it's a bug in 1.6.0 with the cookie problem. sorry for that.

**Comment by astaxie** [comment]
@TomTom86 did you still have the problem after upgrade beego to new version?
