### ISSUE TITLE
PostgreSQL `text` instead of `varchar(255)`

### ISSUE THREAD

**Issue by slava-vishnyakov** [astaxie/beego#1851]
Hi!

The docs say that by default beego ORM creates `varchar(255)` for strings on PostgreSQL

http://beego.me/docs/mvc/model/models.md
> string - default size 255	varchar(size)

This is not optimal. For PostgreSQL there is no difference between `text` and `varchar`, under the hood it's the same type.

See here, for ex.: http://stackoverflow.com/questions/4848964/postgresql-difference-between-text-and-varchar-character-varying

But, golang's strings can be of any size, like PostgreSQL's `text` field, on the other hand `varchar(255)` would raise a database error if string is longer than 255 chars.

So, golang's `string` is much more like `text`, than `varchar`. 

For PostgreSQL the performance of `text` and `varchar(255)` is the same.

Can we make the default on PostgreSQL for `string` to be `text` instead of `varchar`?

`gorm` actually implemented this recently https://github.com/jinzhu/gorm/issues/910

Thanks!

**Comment by astaxie** [comment]
@miraclesu please follow up this requirement
