### ISSUE TITLE
Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by slava-vishnyakov** [astaxie/beego#1852]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 darwin/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```go
package main

import (
	"log"

	"github.com/astaxie/beego/orm"
	_ "github.com/mattn/go-sqlite3"
)

type Something struct {
	Id    int
	Name  string
	// Name2 string
}

func main() {
	orm.RegisterDriver("sqlite3", orm.DRSqlite)
	orm.RegisterDataBase("default", "sqlite3", "test.sqlite3")
	orm.RegisterModel(new(Something))

	err := orm.RunSyncdb("default", false, true)
	if err != nil {
		log.Fatal(err)
	}
}
```

then I run `go run main.go`

It's OK:

```sql
create table `something`
    -- --------------------------------------------------
    --  Table Structure for `main.Something`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `something` (
        `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        `name` text NOT NULL
    );
```

Then I uncomment the `Name2` and try to run `go run main.go` again:

```go
....
type Something struct {
	Id    int
	Name  string
	Name2 string
}
....
```

Well, this fails:
```sql
add column `main.Something.Name2` for table `something`
    ALTER TABLE `something` ADD COLUMN `name2` text NOT NULL
2016/04/02 17:49:50 Cannot add a NOT NULL column with default value NULL
```

4. What did you expect to see?

Column `Name2` being created without an error

5. What did you see instead?

see above

**Comment by miraclesu** [comment]
@slava-vishnyakov I think there is something wrong in your environment, beego had added default value from `v1.4.2`, see the [commint](https://github.com/astaxie/beego/commit/4cae7af3f93b47807cfc3b7bd17562873f31f030).

So, your program should output like:
```
create table `something` 
    -- --------------------------------------------------
    --  Table Structure for `main.Something`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `something` (
        `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        `name` varchar(255) NOT NULL DEFAULT '' 
    );

table `something` already exists, skip
add column `main.Something.Name2` for table `something`
    ALTER TABLE `something` ADD COLUMN `name2` varchar(255) NOT NULL  DEFAULT '' 
```

It contains `DEFAULT '' `.

You can try:
1. `cd $GOPATH/src/github.com/astaxie/beego/orm && go install`, then run the program again.
2. `go get -u github.com/astaxie/beego/orm`, then run the program again.

**Comment by slava-vishnyakov** [comment]
Yep, it works after update. Thanks!
