### ISSUE TITLE
Beego logger in init function

### ISSUE THREAD

**Issue by saturn4er** [astaxie/beego#1855]
Hi, there is a problem while using bee logger in the `init` function. I see you fixed nil-reference in the commit 
#76db5cded4e7e1e63b3da2751f6c463cf0cc4e75, but there is a problem, it doesn't output anything, because(I think) register of outputs is also in init function `func init() {
	Register("console", NewConsole)
}
` and it happens after my init function

I can fix it, but I don't know how to do it correctly

**Comment by youngsterxyf** [comment]
@saturn4er I think you should create a new issue using beego issue template.

**Comment by youngsterxyf** [comment]
@saturn4er and which `init` function do you mean?

**Comment by youngsterxyf** [comment]
![qq20160404-0 2x](https://cloud.githubusercontent.com/assets/834231/14236253/0bb4500a-fa45-11e5-87a6-7202507348ff.png)

is it the feature you want to get?

Version details:

```
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 darwin/amd64
```

**Comment by saturn4er** [comment]
I run beego through `go run`
![image](https://cloud.githubusercontent.com/assets/11644585/14248082/3c3361e0-fa7b-11e5-952b-bffe549f63bb.png)

**Comment by youngsterxyf** [comment]
@saturn4er Oh, i see , you can see this pr :https://github.com/astaxie/beego/pull/1840

**Comment by saturn4er** [comment]
@youngsterxyf strange, how the absence of configs affects the logs?

**Comment by youngsterxyf** [comment]
@saturn4er you can try to build and run，not using `go run`, or wait for next release of beego.
