### ISSUE TITLE
get the httprequest vaules is always  ""

### ISSUE THREAD

**Issue by huangjiasingle** [astaxie/beego#1860]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

when I use the Controller's GetString to get the httprequest params ,it's always "" ,only the http method is Get then can get the param's value. but if I use Controller.Ctx.input.RequestBody, I can get the params's  []byte.  

4. What did you expect to see?
I want to konw the reason of this problem

5. What did you see instead?

**Comment by astaxie** [comment]
did you turn on the `beego.BConfig.CopyRequestBody=true`

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by huangjiasingle** [comment]
yes，l do it this.   first l think this problem of  my code . so l use the  bee new command to create a new web app. it has the same problem.

**Comment by astaxie** [comment]
show me the code and how did you run the application?

**Comment by huangjiasingle** [comment]
the router is : 
beego.Router("/api/v1", &controllers.MainController{}, "POST:Post")
the controller is : 
func (c *MainController) Post() {
	c.GetString("telephone")
	log.Printf("the request string=%v", c.GetString("telephone"))
	c.Data["json"] = c.GetString("telephone")
	c.ServeJSON()
}
the config is : 
appname = test
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true

the result is : 

the request string=

the httpresponse is：
""

it's a new web app create by bee new command just now ;

**Comment by astaxie** [comment]
you never can get the telephone by c.GetString("telephone")

**Comment by huangjiasingle** [comment]
why? how to get the telephone's value?

**Comment by huangjiasingle** [comment]
@astaxie why? how to get the telephone's value?

**Comment by astaxie** [comment]
you need to unmarshal by yourself.

**Comment by huangjiasingle** [comment]
@astaxie 
only this way? 
but in another web app before i did , i can use GetString method to get the http post or put or delete's params .  this is why?

**Comment by astaxie** [comment]
please google the difference between raw body and form value.

**Comment by huangjiasingle** [comment]
@astaxie 
ok,thks !
