### ISSUE TITLE
XSRF bug

### ISSUE THREAD

**Issue by uniqueque** [astaxie/beego#1862]
英文不好，就用中文写吧。
不知道是哪个beego版本开始，就直接说1.6.1版本的吧。
1.6.1中使用了sync.Pool来存储context，取出context的时候，未将context中_xsrfToken初始化，将_xsrfToken公用了，导致一个gc时间内就重复的那几个（刚gc之后，并发访问会有多个，否则就一个），gc之后会生成新的_xsrfToken，提交请求的时候，会将老的_xsrfToken与新生成的_xsrfToken对比，不通过

**Comment by astaxie** [comment]
@JessonChan please follow up this issue

**Comment by uniqueque** [comment]
表达不好，见谅。总之呢 未将_xsrfToken初始化，导致context中的_xsrfToken公用了。

**Comment by JessonChan** [comment]
i will fix it
