### ISSUE TITLE
cache immediately expired

### ISSUE THREAD

**Issue by ykrl089** [astaxie/beego#1867]
I find there is cache immediately expired bug @ v1.6.0
in  this function
func (mi *MemoryItem) isExpire() bool {
	// 0 means forever
	if mi.lifespan == 0 {
		return false
	}
	return time.Now().Sub(mi.createdTime) > mi.lifespan
}
in Put function, the timeout interface is time.Duration,I put 3600 means 3.6us
by created a object time.Now().Sub(mi.createdTime) append to value at 2.1ms which is alway larger than mi.lifespan

**Comment by youngsterxyf** [comment]
@ykrl089 Sorry, i can't understand your problem. Why do you set lifespan to 3600? why not bigger?

**Comment by ykrl089** [comment]
in your manual , the function Put(key string, val interface{}, timeout int64) has param timeout（value type shoud be second），
but in your code it is time.Duration
so if i use like this
Put("aaa", l, 3600)，
which will expired in 3.6us not 3600 s

**Comment by youngsterxyf** [comment]
Oh, the document isn't updated following the code. you can use it like this `Put("aaa", I, 3600 * time.Second)`

**Comment by youngsterxyf** [comment]
@ykrl089 I will send a pr to https://github.com/beego/beedoc
