### ISSUE TITLE
template rendering issue

### ISSUE THREAD

**Issue by Geoferry** [astaxie/beego#1868]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 1.6.1 (beego framework)
golang version: go1.6

2. What operating system and processor architecture are you using (`go env`)?
Mac OS X 10.11.4

I was confused since I always get this error: 
   `beego:can't` find templatefile in the path:index/index.html`

Here's the code : 
`
func (this *IndexController) Index() {
	this.TplName = "index/index.html"
}
`

And the file architecture:

ProjectRoot
- views
  - index
    - index.html
    

Could you help me solved this ? Thanks!

**Comment by youngsterxyf** [comment]
@Geoferry Do you run your app by `go run` ?

**Comment by Geoferry** [comment]
@youngsterxyf  Yes. Is it wrong?

**Comment by youngsterxyf** [comment]
@Geoferry Beego 1.6 or 1.6.1 dose not support `go run`, it is a bug, and has been fixed, will be released in next version. So, now, you can build app and run it.

**Comment by Geoferry** [comment]
@youngsterxyf Thanks, it works.

**Comment by astaxie** [comment]
fixed in beego1.7.0
