### ISSUE TITLE
CustomAbort always returns 200 status code in master (1.6.1)

### ISSUE THREAD

**Issue by mmindenhall** [astaxie/beego#1869]
I just updated from 1.6.0 to latest (1.6.1), and some of my tests started to fail with 200 status code being returned when a different status code was expected.  All of these tests are calling c.CustomAbort with status (400, 401, 404, 500), but the response is always coming back as 200.

It looks like the problem in master (calling `c.Ctx.ResponseWriter.Write([]byte(body))` without first calling `c.Ctx.ResponseWriter.WriteHeader(status)` has been fixed in the develop branch.  Can that fix get merged?

Thanks!

**Comment by youngsterxyf** [comment]
Duplicate issue #1617

**Comment by xionglun** [comment]
@youngsterxyf  @astaxie 
I don't think it 's duplicate with #1617, it may be caused by #1719 .
