### ISSUE TITLE
ORM 多对多关系。

### ISSUE THREAD

**Issue by ZhangTingkuo** [astaxie/beego#1872]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/Users/dewdrop/Workspace/Golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dewdrop/Workspace/Golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

最近在做一个项目，在使用orm创建数据库是发现了一些问题。

一个user表，其中由两个字段，followers和following，类型也都是User

type User struct {
	Id           int64        `orm:"pk;auto"`
……
	Followers    []*User 
	Following    []*User 
……
}

这种情况 应该怎么设置orm的tag呢。

4. What did you expect to see?

5. What did you see instead?

**Comment by Xingchen-L** [comment]
路过，表示这个应该不是多对多关系吧，应该是one-many关系

**Comment by ZhangTingkuo** [comment]
按照一对多设置，编译不过。

**Comment by Xingchen-L** [comment]
好像我之前理解有点错误，你是不是要设置 User对象和User的多对多关系？我的想法是自定义中间表，然后用SQL查询，不知道还有么有其他更好的办法
