### ISSUE TITLE
Annotation Routes not created/updated

### ISSUE THREAD

**Issue by steamonimo** [astaxie/beego#1876]
For me the Annocation Routes are not created anymore. Any changes to Annotation Routes will not update the commentsRouter file. I thought that the root cause is in bee as I have reported [here](https://github.com/beego/bee/issues/186). But I am not that sure anymore.

What could cause that the Routes are not updated? Usually the Annotations have been interpreted to create the commentsRouter file in the second compilation step of bee.

bee: 1.4.1
beego: 1.6.1
go: 1.6 windows/amd64

**Comment by astaxie** [comment]
what's your mode? is it dev?

**Comment by stef-k** [comment]
The same thing happens on my routes too. I've deleted lastupdate.tmp multiple times with no luck.

Beego ver:

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.1

├── Beego     : 1.7.0
├── GoVersion : go1.7
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/stef/projects/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Wednesday, 9 Nov 2016

OS ver:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
