### ISSUE TITLE
how to filter between date?

### ISSUE THREAD

**Issue by goldalworming** [astaxie/beego#1884]
how to filter between date in beego orm
do I have to user o.Raw or beego orm already have the operator?
SELECT *
FROM `mytable`
WHERE (date_field BETWEEN '2016-01-30 00:00:00' AND '2016-04-28 09:00:00')

**Comment by youngsterxyf** [comment]
Maybe you can transform date to timestamp，then use Filter ？

**Comment by youngsterxyf** [comment]
@goldalworming Beego ORM supports date and datetime，So，i think maybe you can transform `'2016-01-30 00:00:00'` to a `Time` object, also `'2016-04-28 09:00:00'`, then use `Filter("date_field__gte", xxx).Filter("date_field__lte", yyy)`
