### ISSUE TITLE
load many to many value error

### ISSUE THREAD

**Issue by ykrl089** [astaxie/beego#1885]
i have two models,the relation between them are many to many.
```go
type Group struct {
	Id         int64
	Name       string   `orm:"size(256)" form:"Name" `                 //组名称
	Members    []*User  `orm:"null;rel(m2m);on_delete(set_null)"`      //成员
	LastUpdate int64
	CreatedAt  int64 //创建时间
}
type User struct {
	Id          int64
	Username    string `orm:"unique;size(32)" form:"Username"  valid:"Required;MaxSize(20);MinSize(5)"`
	Password    string `orm:"size(32)" form:"Password" valid:"Required;MaxSize(20);MinSize(6)"`
	Nickname    string `orm:"unique;size(32)" form:"Nickname" valid:"Required;MaxSize(20);MinSize(2)"`
	Groups      []*Group    `orm:"null;reverse(many)"`
}
```
i used o.LoadRelated(usr , "Groups") to load Groups in User models,it is working, however if i use o.LoadRelated(group, "Members") to load Members in Group model ,it cause a non-pointer error.

following the error msg, i found out that , the value(fi.reverseFieldInfoM2M orm.go line 390) will be nil in this case.

is that a bug or i make some mistake in models

**Comment by miraclesu** [comment]
@ykrl089 Is it `group` a pointer, if not, it will cause the non-pointer error.

I have tried your code with latest beego and there was not such error, you can update beego and try again.

**Comment by astaxie** [comment]
beego 1.7 should cover this issue
