### ISSUE TITLE
beego 1.5切换到1.6后的session问题

### ISSUE THREAD

**Issue by py-samsung** [astaxie/beego#1886]
1.最近升级到1.6，发现sessionsavepath 不起作用了，在file的模式下，不能将session存储到指定目录了，官网的文档貌似也没跟上。
2.还有些根session为空的情况，正在确认。

**Comment by py-samsung** [comment]
配置文件没写对。抱歉

**Comment by raptium** [comment]
我也遇到了这个问题。`SessionSavePath` 已经改成了 `SessionProviderConfig`，但是文档里没有改。
