### ISSUE TITLE
error  "invalid character 'XXX' looking for beginning of value"

### ISSUE THREAD

**Issue by kc87654321** [astaxie/beego#1887]
beego-1.6.1+Bee
beego is good ider.
bee api myapi-conn="1:1@tcp(127.0.0.1:3306)/ttt"
bee generate docs
I get program "myapi"

curl -X DELETE http://127.0.0.1:8082//v1/shengfen/50  ---is OK

curl  -X POST -d "Shenfengname=Sean11Plott" "http://127.0.0.1:8082/v1/shengfen/"
curl  -X PUT -d '{'Shenfengname':'Sean11Plott'}' http://127.0.0.1:8082/v1/shengfen/51
curl -X POST -d 'Shenfengname":1337' http://127.0.0.1:8082/v1/shengfen/
i get error  "invalid character 'S' looking for beginning of value"

**Comment by kc87654321** [comment]
POST AND GET get erro
&{POST /v1/shengfen/ HTTP/1.1 1 1 map[Accept:[*/*] Content-Length:[24] Content-Type:[application/x-www-form-urlencoded] User-Agent:[curl/7.20.0 (i386-pc-win32) libcurl/7.20.0 OpenSSL/0.9.8n zlib/1.2.3 libidn/1.8 libssh2/1.2.4]] {} 24 [] false 127.0.0.1:8082 map[Shenfengname:[Sean11Plott]] map[Shenfengname:[Sean11Plott]] <nil> map[] 127.0.0.1:16460 /v1/shengfen/ <nil> <nil>}

**Comment by youngsterxyf** [comment]
@kc87654321 Sorry， i don't understand what your problem is. do you use curl in a wrong way？

**Comment by astaxie** [comment]
you need to send the request like 

```
curl -X POST -d `{"Shenfengname":"Sean11Plott"}` "http://127.0.0.1:8082/v1/shengfen/"
curl -X PUT -d '{"Shenfengname":"Sean11Plott"}' http://127.0.0.1:8082/v1/shengfen/51
curl -X POST -d '{"Shenfengname":1337}' http://127.0.0.1:8082/v1/shengfen/
```
