### ISSUE TITLE
orm.RunSyncdb must have one register DataBase alias named `default`

### ISSUE THREAD

**Issue by kyawmyintthein** [astaxie/beego#1888]
When I use orm.RunSyncdb, I got following error
         " must have one register DataBase alias named `default`"

       If I remove follow code from from modes_boot.go, it is work.
	if dataBaseCache.getDefault() == nil {
	 	err = fmt.Errorf("must have one register DataBase alias named `default`")
	 	goto end
	 }
        

        It should be remove or any other way to solve this problem? 
       My database connection code is
       orm.RegisterDataBase(name, "mysql", connectionString, maxIdle, maxConn)

**Comment by youngsterxyf** [comment]
@kyawmyintthein Maybe you can refer to http://beego.me/docs/mvc/model/orm.md#registerdatabase

**Comment by kyawmyintthein** [comment]
Thanks @youngsterxyf .I see the problem.

**Comment by SKHuangModamao** [comment]
mysqld --skip-grant-tables 试试
