### ISSUE TITLE
Trying to integrate go-socket.io into beego

### ISSUE THREAD

**Issue by csrgxtu** [astaxie/beego#1889]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
client socket can connect to the server, but cant when emit, server cant receive it

5. What did you see instead?
nothing

**Comment by csrgxtu** [comment]
actually, i am trying to make go-socket.io work with beego, and go-socket.io have a little example, but not workable in beego.
[https://github.com/googollee/go-socket.io](https://github.com/googollee/go-socket.io)

**Comment by youngsterxyf** [comment]
@csrgxtu How do you make go-socket.io work with beego?

**Comment by csrgxtu** [comment]
@youngsterxyf , socket.io worked with beego. following link give me inspiration:
http://beego.me/docs/mvc/controller/router.md
https://github.com/googollee/go-socket.io

**Comment by youngsterxyf** [comment]
@csrgxtu yes, just add router for socket.io
