### ISSUE TITLE
[bug]Why override chdir and without save old os.Getwd()

### ISSUE THREAD

**Issue by fishedee** [astaxie/beego#1892]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.6.1

2. What operating system and processor architecture are you using (`go env`)?

ubuntu 14.04

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

when I import beego library, it will override system working dir which is modify in github.com/astaxie/beego/config.go,oh my god，you can override the working path, but you should save the old working path first,so i can't get the old working path

4. What did you expect to see?

5. What did you see instead?

**Comment by youngsterxyf** [comment]
@fishedee refer to issue https://github.com/astaxie/beego/issues/1836 , has been fixed, will release in next version.
