### ISSUE TITLE
after set CORS InsertFilter, swagger stop working

### ISSUE THREAD

**Issue by cch123** [astaxie/beego#1893]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.0
Go    :go version go1.5.1 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Xargin/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
i have insert cors settings to support cors requests, 
in main.go
```
 beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
          
          AllowOrigins:     []string{"*"},
          AllowCredentials: true,
      }))
 
     if beego.BConfig.RunMode == "dev" {
          beego.BConfig.WebConfig.DirectoryIndex = true
          beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
      }
```

when open 127.0.0.1:8080/swagger/swagger-1
I get the following message：
Can't read swagger JSON from http://127.0.0.1:8080/docs

If I delete the cors settings, everything is ok

**Comment by youngsterxyf** [comment]
@cch123 Maybe you can refer to this issue https://github.com/astaxie/beego/issues/1857

**Comment by cch123** [comment]
@youngsterxyf ，
after I change beego.BeforeRouter to beego.BeforeExec
swagger still cannot work.

**Comment by youngsterxyf** [comment]
@cch123 the relative url is "/docs", not "/swagger"?

**Comment by cch123** [comment]
@youngsterxyf 
the swagger page is
```
http://127.0.0.1:8080/swagger/swagger-1
```
it requests the url
```
http://127.0.0.1:8080/docs
```

the swagger page can be correctly loaded,

but the /docs url returns 404
though the log shows match。

**Comment by youngsterxyf** [comment]
@cch123 http://beego.me/docs/advantage/docs.md

**Comment by youngsterxyf** [comment]
@cch123 Do you run app with `bee run -gendoc=true -downdoc=true` ?

**Comment by cch123** [comment]
ok, I checked the InsertFilter function
and solve this by insert the cors filter by:
```
 beego.InsertFilter("*", beego.FinishRouter, cors.Allow(&cors.Options{
         AllowOrigins: []string{"*"},
 }))
```

change beego.BeforeRouter -> beego.FinishRouter

Maybe the former filter execution point is not correct.
Thx all the same.

**Comment by benzsuankularb** [comment]
+1

I also got this

**Comment by astaxie** [comment]
the new version swagger2.0 totally don't need any server now. just generate the swagger.json

**Comment by ihippik** [comment]
Today I downloaded swagger2.0 (https://github.com/beego/swagger/releases), but all the same, instead of PUT / POST request, it sends OPTIONS.
I need to update the framework?

**Comment by astaxie** [comment]
@ihippik yea, you need to upgrade to bee and beego

go get -u github.com/beego/bee

**Comment by ihippik** [comment]
remove swagger folder, run`bee run -downdoc=true -gendoc=true`
download new v2 swagger version :+1: , but i got `
docs/docs.go:17: undefined: swagger.ResourceListing
docs/docs.go:18: undefined: swagger.APIDeclaration
docs/docs.go:30: undefined: beego.GlobalDocAPI
docs/docs.go:37: undefined: beego.GlobalDocAPI
`

**Comment by ihippik** [comment]
Got it - changed the structure.
Now the files are not needed. JSON generated on a different principle
Many thanks!
