### ISSUE TITLE
app.json

### ISSUE THREAD

**Issue by cristian-sima** [astaxie/beego#1896]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.4.1

2. What operating system and processor architecture are you using (`go env`)?

go version go1.6 windows/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I change the app.conf to app.json and I started the server.

The server does not starts: 

![image](https://cloud.githubusercontent.com/assets/12199042/14684884/aa124bec-073a-11e6-91ae-e8d4d6cc3685.png)

4. What did you expect to see?

To work with json file as configuration, because it is easier to manipulate.

5. What did you see instead?

It does not work

**Comment by youngsterxyf** [comment]
@cristian-sima If you don't use default `ini` config file, then you should explicitly load config file for your app using `beego.LoadAppConfig("json", "path/to/app.json")`

**Comment by cristian-sima** [comment]
Tx

**Comment by xmapst** [comment]
Can you show me your app.json

**Comment by xmapst** [comment]
Can you tell me your app.json, my app.json doesn't work
@cristian-sima
