### ISSUE TITLE
redis cache doubt

### ISSUE THREAD

**Issue by gitchs** [astaxie/beego#1899]
1. beego redis module will cache all keys created by beego, so function [ClearAll](https://github.com/astaxie/beego/blob/d7aaf2ebeb4775cf2d2b6d0323fe100acf52d52a/cache/redis/redis.go#L160-L173) could delete them all.
2. But redis support command [FlushDB](http://redis.io/commands/flushdb), this command will flush all keys in specific redis database.
3. I don't think different programs should share same redis index, so beego does not need to execute two redis commands in functions such as [Put](https://github.com/astaxie/beego/blob/d7aaf2ebeb4775cf2d2b6d0323fe100acf52d52a/cache/redis/redis.go#L111-L122)

@astaxie If you want to close this issue, I would like to update beego's redis document. The first time I saw redis configure `{"key":"collectionName","conn":":6039","dbNum":"0","password":"thePassWord"}`, I think _collectionName_ is something to do with redis.

**Comment by gitchs** [comment]
Two more questions
Functions like [Get](https://github.com/astaxie/beego/blob/master/cache%2Fredis%2Fredis.go#L71-L76) does not return error, so nobody know if the function success or not?
> 1. key does not exists will return nil
> 2. database error will return nil

Since functions like Get return interface, so if I want to convert it to the correct type I want, I have to import [github.com/garyburd/redigo/redis](https://github.com/garyburd/redigo/blob/master/redis/reply.go), and call helper functions.

**Comment by astaxie** [comment]
@gitchs sorry for the later reply. I think your suggestion is great. If you have good ideas please just send the pull request.

**Comment by gitchs** [comment]
@astaxie maybe I will work on this issue later, busy for business nowadays.

**Comment by astaxie** [comment]
@gitchs cool

**Comment by ansiz** [comment]
@gitchs @astaxie 
Is this problem solved? I think the key in the configuration should be a prefix of the cache key, the methods Put,Get,Delete... operate the combined key, for example:
```
rc.key = "beego:cache"
Put("bar", 1, time.Second * 100)
// the equivalent of redisConn.Do("SETEX","beego:cache:bar", 100, 1)

// ClearAll Should be implemented as:
keys,err := redis.Strings(rc.do("KEYS", "beego:cache:*")
range and deletes the keys
```
 I'd like to help with the modification if you agree

**Comment by gitchs** [comment]
@astaxie I work for a startup company since 09/2016, so I don't believe I have enough time for this issue. Maybe @ansiz could work on it.

**Comment by astaxie** [comment]
@ansiz please help work on it.

**Comment by ansiz** [comment]
@astaxie ok, I'm not quite understand gitchs's requirement, I created a pull request https://github.com/astaxie/beego/pull/2659 , I can do some modification if it necessary . I will modify document after this issue closed.
