### ISSUE TITLE
panic: dial tcp: missing address

### ISSUE THREAD

**Issue by luodaihong** [astaxie/beego#1901]
If I add the following code into app.cnf, I will get an error:panic: dial tcp: missing address.
sessionprovider = redis
sessionsavepath = 127.0.0.1:6380

Remove these two lines, everything works well.I have import github.com/astaxie/beego/session/redis in main.go

why?
More:
How to use redis or memcache as session provider?  I have did as doc, But it nerver works.

**Comment by luodaihong** [comment]
My project is here:https://github.com/luodaihong/studyBeego

**Comment by gwduan** [comment]
Change sessionsavepath to sessionproviderconfig.

**Comment by luodaihong** [comment]
Thank you! 
It does work.
I really hope that the doc would be updated in time.

**Comment by luodaihong** [comment]
sessionon = true
sessionproviderconfig.sessionprovider = redis
sessionproviderconfig.sessionsavepath = 127.0.0.1:6380

When I stop redis, session works well.If redis is running, I found no data written inti redis.Beego does not really use redis.
@gwduan Is there anything wrong in my app.cnf?

**Comment by gwduan** [comment]
My app.cnf:
```
sessionon = true
sessionprovider = redis
sessionproviderconfig = 127.0.0.1:6379
```

**Comment by luodaihong** [comment]
Thanks! Your cnf is right.

I was disappointed at beego doc.

**Comment by astaxie** [comment]
@luodaihong I am sorry for that. We are trying to fix all the documents.
