### ISSUE TITLE
LoadRelated error 

### ISSUE THREAD

**Issue by yaotian** [astaxie/beego#1905]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go1.5
beego1.5.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
-----> model
type Card struct {
	Id       int
	AvaImage  *Image `orm:"rel(fk);"` 
	Images   []*Image  `orm:"rel(m2m)"`
}

---->call
orm.NewOrm().LoadRelated(&card, "Images")

---->error
2016/04/26 09:39:07 [router.go:879] [C] the request url is  /2271449025140/card/edit/1 
2016/04/26 09:39:07 [router.go:880] [C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/Downloads/go/src/runtime/asm_amd64.s:437 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/Downloads/go/src/runtime/panic.go:423 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/Downloads/go/src/runtime/panic.go:42 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/Downloads/go/src/runtime/sigpanic_unix.go:24 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/projects/new_go_projects/src/github.com/astaxie/beego/orm/orm.go:385 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/projects/new_go_projects/src/github.com/astaxie/beego/orm/orm.go:337 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/projects/new_go_projects/src/github.com/astaxie/beego/orm/orm.go:248 
2016/04/26 09:39:07 [router.go:886] [C] /Users/yaotian/projects/new_go_projects/src/bitbucket.org/yaotian/dady/modules/models/card.go:58 

4. What did you expect to see?

5. What did you see instead?

**Comment by yaotian** [comment]
这个问题比较严重，因为使用场景很多。比如，User 有一个头像，一个相册，model了就有一个外键的Image, 一个多对多的Images。我项目中已经有多个这样的场景.希望引起重视

**Comment by astaxie** [comment]
@miraclesu please help to check this issue.

**Comment by miraclesu** [comment]
@yaotian your models define is wrong, please try:
```
 type Image struct {
     Id    int
     Cards []*Card `orm:"rel(m2m)"`
 }
  
 type Card struct {
     Id       int
     AvaImage *Image   `orm:"rel(fk);"`
     Images   []*Image `orm:"reverse(many)"`
 }
```

**Comment by yaotian** [comment]
@miraclesu  感谢回复。颠倒了顺序就没有问题了？那个有两个问题：
1.`orm:"rel(m2m)"` 与 `orm:"reverse(many)"` 必须同时出现在两个model中吗？
2. 怎么决定，`orm:"rel(m2m)"`应该放在哪个model中？

**Comment by zplzpl** [comment]
2022 年, 仍有一些项目用旧版本，会遇到这个错误。
