### ISSUE TITLE
config.go 个人觉得几个不合理的地方

### ISSUE THREAD

**Issue by qinguoan** [astaxie/beego#1910]
1、os.Args[0] 查看路径可能存在问题，如果用相对路径执行的时候。应该用 https://github.com/kardianos/osext 里面的方式更安全。

2、go run 做测试时候，由于可执行文件在临时目录，此时app.conf完全找不到，导致直接return 后面不会执行parseConfig 也就没有 init log的操作了。建议是否干脆取消app.conf(目前个人感觉用处也不算大)全部参数在调beego.run()之前自己修改。

**Comment by ysqi** [comment]
你好，已在优化中
            在2016年04月26日 22:16，qinguoan 写道:1、os.Args[0] 查看路径可能存在问题，如果用相对路径执行的时候。应该用 https://github.com/kardianos/osext 里面的方式更安全。

2、go run 做测试时候，由于可执行文件在临时目录，此时app.conf完全找不到，导致直接return 后面不会执行parseConfig 也就没有 init log的操作了。建议是否干脆取消app.conf(目前个人感觉用处也不算大)全部参数在调beego.run()之前自己修改。

**Comment by xuhuan** [comment]
@ysqi  appConfigProvider 默认是ini，但是看代码配置文件应该是还支持其他格式的，能否让这个参数可以自行配置？
