### ISSUE TITLE
Bee new project can't work

### ISSUE THREAD

**Issue by thathappiness** [astaxie/beego#1914]
This is my first try of beego, and I started as the fast start doc says:

bee new hello
cd hello
bee run hello

and then it gave me the error like this:

can't load package: /usr/local/go/src/hello/main.go:5:2: non-standard import "github.com/astaxie/beego" in standard package "hello"
/usr/local/go/src/hello/controllers/default.go:4:2: non-standard import "github.com/astaxie/beego" in standard package "hello/controllers"
/usr/local/go/src/hello/routers/router.go:5:2: non-standard import "github.com/astaxie/beego" in standard package "hello/routers"
2016/04/30 03:56:50 [ERRO] ============== Build failed ===================

what's the reason ? can anybody help me?by the way,my go version is go1.6.

**Comment by youngsterxyf** [comment]
@thathappiness What's your GOPATH?
