### ISSUE TITLE
Handler crashed with error interface conversion

### ISSUE THREAD

**Issue by u007** [astaxie/beego#1916]
hi, please review below:

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/james/www/gowork"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="/usr/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

bm, err := cache.NewCache("redis", `{"conn":":6379"}`)  
name := "file_somewhere:somewhere:file.jpg"
bm.Put(name,"8888|2016-10-10 01:01:01|new_file.jpg", timeout)
bm.Get(name).(string)

4. What did you expect to see?
expected to return same value as requested 
8888|2016-10-10 01:01:01|new_file.jpg

5. What did you see instead?
 throws Handler crashed with error interface conversion: interface is []uint8, not string on bm.Get

**Comment by youngsterxyf** [comment]
@u007 

```go
package main

import (
	"fmt"
	"time"

	"github.com/astaxie/beego/cache"
	_ "github.com/astaxie/beego/cache/redis"

	"github.com/garyburd/redigo/redis"
)

func main() {

	bm, err := cache.NewCache("redis", `{"conn":":6379"}`)
	if err != nil {
		fmt.Println(err)
		return
	}
	name := "file_somewhere:somewhere:file.jpg"
	bm.Put(name, "8888|2016-10-10 01:01:01|new_file.jpg", 60*time.Second)
	fmt.Printf("%v\n", string(bm.Get(name).([]byte)))

	v, err := redis.String(bm.Get(name), nil)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("%v\n", v)
}
```

**Comment by u007** [comment]
hi,

thank you for your fix 👍 
i'am currently using fmt.printf('%s'...) to fix it.. lol

but this means the data is very dependent on the cache adaptor..
is there a way to wrap it over every adaptor?
maybe another Type struct for .Get(name).String()

i think that will be cool :)

**Comment by u007** [comment]
Or GetString(name)

**Comment by youngsterxyf** [comment]
@u007 Perhaps you can make a wrapper using type switch. Yes, maybe beego's cache module can be more friendly.
