### ISSUE TITLE
DirectoryIndex = false not working

### ISSUE THREAD

**Issue by u007** [astaxie/beego#1921]
hi, ive set

conf/app.conf
DirectoryIndex = false

but when i visit /static/css/, it shows directory listing.
is this the right config file?

**Comment by JessonChan** [comment]
@u007 default is false.but it works on my test project
![image](https://cloud.githubusercontent.com/assets/707691/15034970/9a1dea28-12ae-11e6-9c52-6eb1a2d33bde.png)

**Comment by u007** [comment]
o sorry, its my main file set without noticing
