### ISSUE TITLE
Cannot get beego on MacOS

### ISSUE THREAD

**Issue by pcman-zhang** [astaxie/beego#1922]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
[~/dev/gopath] $ go version
go version go1.3.3 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/freeman/dev/gopath"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.3.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.3.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
$ go get github.com/astaxie/beego
# github.com/astaxie/beego
src/github.com/astaxie/beego/tree.go:144: syntax error: unexpected range, expecting {
src/github.com/astaxie/beego/tree.go:155: syntax error: unexpected else, expecting semicolon or newline
src/github.com/astaxie/beego/tree.go:157: non-declaration statement outside function body
src/github.com/astaxie/beego/tree.go:158: non-declaration statement outside function body
src/github.com/astaxie/beego/tree.go:159: non-declaration statement outside function body
src/github.com/astaxie/beego/tree.go:160: syntax error: unexpected }
src/github.com/astaxie/beego/tree.go:257: syntax error: unexpected range, expecting {
src/github.com/astaxie/beego/tree.go:267: syntax error: unexpected else, expecting semicolon or newline or }
src/github.com/astaxie/beego/tree.go:282: syntax error: unexpected }

4. What did you expect to see?
No error appears

5. What did you see instead?
golang syntax error

**Comment by astaxie** [comment]
please upgrade your go version

**Comment by pcman-zhang** [comment]
It works, Thanks a lot.
