### ISSUE TITLE
beego 支持的http状态码太少

### ISSUE THREAD

**Issue by xuxiangyang** [astaxie/beego#1923]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxy/Documents/go_project"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="0"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

问题如下：
1. 使用beego.Abort("400") 时，返回的状态码为200
2. 使用beego.CustomAbort(403, "limit") 返回状态码为200

这个感觉好奇怪。。。Abort为什么是个string的输入值~我想要的就是立刻停止非200的请求，不需要返回其他内容。感觉这个是不是更普遍的需求？

**Comment by JessonChan** [comment]
返回非200已经修复
可以使用以下的方法
```
ctx.ResponseWriter.ResponseWriter.WriteHeader(400)
controller.StopRun()
```
临时修复你的问题
关于Abort函数，已经在谈论优化的问题

**Comment by xuxiangyang** [comment]
Thx，下一版预计会什么时候发呢？感觉会修复好多问题~
