### ISSUE TITLE
A question about “log file daily rotate”

### ISSUE THREAD

**Issue by yaodd** [astaxie/beego#1925]
1. What version of Go and beego are you using (`bee version`)?

beego:1.6.1
go:1.5.1

    2. What operating system and processor architecture are you using (`go env`)?

linux

Hi, I read the source code of /logs/file.go and found the time to daily rotate log file is when write a new log. My app has more then one kind logs at different file every day. Some logs is few so that maybe It's a long time between tow lines in a log file. Now, I am going to write a app to analyze those logs daily, so I hope the logs file has been rotated daily when the app analyze the logs, but I don't know if the daily rotate is finished because I don't know when the first log come today. I feel The daily rotate is not the really "daily rotate". 

Finaly, my qeustion is  Why not daily rotate log file at a  regular time?

Please , thank!

**Comment by JessonChan** [comment]
@yaodd thanks for your issue,i think you are right,and i will make the daily rotate be the really "daily rotate"!
