### ISSUE TITLE
str2html无法在<script>标签里无法正确输出

### ISSUE THREAD

**Issue by snowlov** [astaxie/beego#1930]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.6.1
2. What operating system and processor architecture are you using (`go env`)?
goenv
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

str2html在<script>标签内能正确数出html编码
5. What did you see instead?

**Comment by greatbsky** [comment]
?
