### ISSUE TITLE
How can i only use https,not http?

### ISSUE THREAD

**Issue by xaseven** [astaxie/beego#1932]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.4 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
http server Running on :8080
https server Running on :1026
ListenAndServeTLS: %!(EXTRA *net.OpError=listen tcp :1026: bind: address already in use)

4. What did you expect to see?
https server Running on :1026

5. What did you see instead?
http server Running on :8080
https server Running on :1026
ListenAndServeTLS: %!(EXTRA *net.OpError=listen tcp :1026: bind: address already in use)

**Comment by astaxie** [comment]
`beego.BConfig.Listen.EnableHTTP = false`

**Comment by haanyip** [comment]
> `beego.BConfig.Listen.EnableHTTP = false`

i want to use beego for a grpc server not http server, it works for me, thanks!
