### ISSUE TITLE
安装beego出错

### ISSUE THREAD

**Issue by lyb124553153** [astaxie/beego#1935]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go 1.6
2. What operating system and processor architecture are you using (`go env`)?
go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andin/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/lib/gccgo/tool"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
I input 
"go get github.com/astaxie/beego"
A complete runnable program is good.

# github.com/astaxie/beego/utils
/home/andin/go/src/github.com/astaxie/beego/utils/mail.go:405:20: error: reference to undefined identifier 'sync.Pool'
 var bufPool = sync.Pool{
                    ^
/home/andin/go/src/github.com/astaxie/beego/utils/mail.go:405:24: error: expected ';' or newline after top level declaration
 var bufPool = sync.Pool{
                        ^
/home/andin/go/src/github.com/astaxie/beego/utils/mail.go:408:2: error: expected declaration
  },
  ^

4. What did you expect to see?
想要安装成功

5. What did you see instead?
# github.com/astaxie/beego/utils
/home/andin/go/src/github.com/astaxie/beego/utils/mail.go:405:20: error: reference to undefined identifier 'sync.Pool'
 var bufPool = sync.Pool{
                    ^
/home/andin/go/src/github.com/astaxie/beego/utils/mail.go:405:24: error: expected ';' or newline after top level declaration
 var bufPool = sync.Pool{
                        ^
/home/andin/go/src/github.com/astaxie/beego/utils/mail.go:408:2: error: expected declaration
  },
  ^

**Comment by JessonChan** [comment]
看上去是go 版本太低，你go vesion出来的也是go 1.6？
