### ISSUE TITLE
Distinct does not affect qs.Values/ValuesList/ValuesFlat

### ISSUE THREAD

**Issue by wincss** [astaxie/beego#1936]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
N/A
与环境无关

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

        type Train struct {
            Id         int64
            TrainNo    string         `orm:"size(30)"`
            Origin     string         `orm:"size(10);index"`
            Dest       string         `orm:"size(10);index"`
        }

        orm.Debug = true
        var maps []orm.Params
        num, _ := o.QueryTable("Train").Distinct().Limit(-1).Values(&maps, "Origin", "Dest")
        fmt.Println("num1=", num)
        num, _ = o.QueryTable("Train").Limit(-1).Values(&maps, "Origin", "Dest")
        fmt.Println("num2=", num)

    Train表示一个火车车次和发到站，想要查询出唯一的发到站组合

4. What did you expect to see?

        [ORM] - 2016-05-10 16:21:25 - [Queries/default] - [  OK /    db.Query /     0.3ms] - [SELECT DISTINCT T0.`origin` `Origin`, T0.`dest` `Dest` FROM `train` T0 ]
        num1= 20
        [ORM] - 2016-05-10 16:21:25 - [Queries/default] - [  OK /    db.Query /     0.5ms] - [SELECT T0.`origin` `Origin`, T0.`dest` `Dest` FROM `train` T0 ]
        num2= 50

    First query has DISTINCT keyword, and second doesn't. num1 < num2.
    第一个查询有DISTINCT关键字，有DISTINCT的查询结果数量比不带的少（取决于数据，上述20、50为举例说明）

5. What did you see instead?

        [ORM] - 2016-05-10 16:21:25 - [Queries/default] - [  OK /    db.Query /     0.3ms] - [SELECT T0.`origin` `Origin`, T0.`dest` `Dest` FROM `train` T0 ]
        num1= 50
        [ORM] - 2016-05-10 16:21:25 - [Queries/default] - [  OK /    db.Query /     0.5ms] - [SELECT T0.`origin` `Origin`, T0.`dest` `Dest` FROM `train` T0 ]
        num2= 50

    Both queries doesn't have DISTINCT keyword, and return same result.

**Comment by StayYouth1993** [comment]
how to user distinct in QueryBuilder ?
