### ISSUE TITLE
import router on main package causing error - must register database alias named "default"

### ISSUE THREAD

**Issue by oybektoirov** [astaxie/beego#1939]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

Go is 1.6
Bee 1.4.1
Beego 1.6.1

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nimda/beego-project"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```go
##### main.go #####
package main

import (
	"fmt"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	_ "github.com/lib/pq"
	_ "b1/docs"
	_ "b1/routers"
	
)

func init() {
	appconfig := beego.AppConfig.String
    orm.RegisterDriver(appconfig("drivername"), orm.DRPostgres)

    dburl := fmt.Sprintf("%s://%s:%s@%s/%s?port=%s&sslmode=disable", 
    	appconfig("drivername"), appconfig("dbuser"), 
    	appconfig("dbpassword"), appconfig("dbhost"), 
    	appconfig("dbname"), appconfig("dbport"))
    
    beego.Info(dburl)

    orm.RegisterDataBase(appconfig("dbalias"), appconfig("drivername"), dburl)
}

func main() {
	beego.Run()
}

##### router.go #####
package routers

import (
	"b1/controllers"

	"github.com/astaxie/beego"
)

func init() {
	ns := beego.NewNamespace("/v1",
		beego.NSNamespace("/user",
			beego.NSInclude(
				&controllers.UserController{},
			),
		),
	)
	beego.AddNamespace(ns)
}


##### models.go #####
package models

import (
	"time"
	"github.com/astaxie/beego/orm"
	_ "github.com/lib/pq"
)

var o orm.Ormer

func init() {
    orm.RegisterModel(new(User))
    o = orm.NewOrm()
}

type User struct {
	Id int
	Username string `orm:"size(30)"`
	Password string 
	Email string `orm:"unique"`
}

##### app.conf #####
appname = b1
httpaddr = "127.0.0.1"
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
EnableAdmin = true

[dev]
drivername = "postgres"
dbhost = "localhost"
dbport = "5432"
dbname = "b1dbdev"
dbuser = "b1user"
dbpassword = "euMDW3bVfYEchrck"
dbalias = "default"
```

4. What did you expect to see?
I'm trying to run the application - main.go

5. What did you see instead?
must have one register DataBase alias named `default`

The app is launching succesfully after removing o = orm.NewOrm() from init() of models.go or if you remove import _ "b1/routers" from main.go

**Comment by astaxie** [comment]
@oybektoirov As your models's init running before the main init. You should move these code to the mode's init

```
appconfig := beego.AppConfig.String
    orm.RegisterDriver(appconfig("drivername"), orm.DRPostgres)
```
