### ISSUE TITLE
Controller ParseForm can't do

### ISSUE THREAD

**Issue by sunnyregion** [astaxie/beego#1943]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 1.6.1

2. What operating system and processor architecture are you using (`go env`)?
Linux
3. What did you do?
I want to post a form to func.
<form id="user" action="/login" method="post">
                <label name="lab_username">username:</label>
<input type="text" name="username" value="" />
                <label name="lab_pwd">password:</label>
<input type="password" name="pwd" value="" />
                <input type="submit" name="login" value="Login" />
        </form>

type Cmsuser struct {
        Username string `form:"username"`
        Pwd     string  `form:"pwd"`
}

func (this *LoginController) Post(){
      
        beego.Info( this.Input().Get("username"))  //This line is well done
        u := Cmsuser{}
    
        if err := this.ParseForm(&u);err !=nil{
                this.Ctx.WriteString(u.Username+u.Pwd) 
        }else{
                beego.Info(err)  //It will give me a message that is nil
        }
        this.Ctx.WriteString("ssss")
}

**Comment by JessonChan** [comment]
this.Ctx.WriteString(u.Username+u.Pwd) 
should be in else {}

**Comment by sunnyregion** [comment]
thx a lot
