### ISSUE TITLE
How to get controllerName and actionName

### ISSUE THREAD

**Issue by sunnyregion** [astaxie/beego#1950]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
windows

I wan to create a BaseController.It cant to get controllerName and actionName.
So I could do some power judge.

package controllers

import (
	"strings"

	"github.com/astaxie/beego"
)

type BaseController struct {
	beego.Controller
	ControllerName string
	ActionName     string
	TplNames       string
}

func (self *BaseController) Prepare() {
	sess_username, _ := self.GetSession("username").(string)
	if sess_username == "" {
		self.TplNames = "login.html"
		self.Render()
	} else {
		self.Ctx.Redirect(302, "/")
	}
}

**Comment by sunnyregion** [comment]
I wrote a func
func (this *BaseController) Html(str string) {
	this.Ctx.WriteString(strings.ToLower(this.controllerName) + strings.ToLower(this.actionName) + str)
}

so so so error:
this.controllerName undefined (type *BaseController has no field or method controllerName, but does have ControllerName)
this.actionName undefined (type *BaseController has no field or method actionName, but does have ActionName)

**Comment by sunnyregion** [comment]
// Controller defines some basic http request handler operations, such as
// http context, template and view, session and xsrf.
type Controller struct {
	// context data
	Ctx  *context.Context
	Data map[interface{}]interface{}

	// route controller info
	controllerName string
	actionName     string
	methodMapping  map[string]func() //method:routertree
	gotofunc       string
	AppController  interface{}

	// template data
	TplName        string
	Layout         string
	LayoutSections map[string]string // the key is the section name and the value is the template name
	TplExt         string
	EnableRender   bool

	// xsrf data
	_xsrfToken string
	XSRFExpire int
	EnableXSRF bool

	// session
	CruSession session.Store
}

**Comment by JessonChan** [comment]
self.GetControllerAndAction()
