### ISSUE TITLE
urlfor in template parse error

### ISSUE THREAD

**Issue by QiiSyhx** [astaxie/beego#1957]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
win7 64bit

3. What did you do?
#router.go
beego.Router("group/delete",&controllers.GroupController{},"get:Delete")
#html
{{urlfor "GroupController.Delete" "id" .Id}}

4. What did you expect to see?
/group/delete/123

5. What did you see instead?
/group/delete?id=123
/group?id=123

two url appear in a range

**Comment by astaxie** [comment]
beego.Router("group/delete/:id",&controllers.GroupController{},"get:Delete")
