### ISSUE TITLE
some problem about orm.read

### ISSUE THREAD

**Issue by L-Angel** [astaxie/beego#1960]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
osx

3. What did you do?
```go
func GetUserByUsername(name string)(v *User,err error){
	o:=orm.NewOrm()
	v = &User{Username:name}
	if err := o.Read(v);err == nil{
		return v,nil
	}
	return nil,err
}
```
this code has two return value,both them are nil.
The read default query param is pk,i think it will return err like orm.ErrNoRow or others.

**Comment by astaxie** [comment]
@L-Angel Could you provide the database data. I check the code https://github.com/astaxie/beego/blob/master/orm/db.go#L355-L360 if there's error during Read, it will return the error
