### ISSUE TITLE
SaveJson() expect 

### ISSUE THREAD

**Issue by mo0feng** [astaxie/beego#1961]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
bee   :1.4.1
beego :1.6.1
```

2. What operating system and processor architecture are you using (`go env`)?
windows 10 64bit
```go version go1.6.2 windows/amd64```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

Want to increase a serialized method of time
```SaveJson() ```add format 
or ```SaveJsonSerializedTime()```

**Comment by astaxie** [comment]
```
type JSONTime time.Time

func (t JSONTime)MarshalJSON() ([]byte, error) {
    //do your serializing here
    stamp := fmt.Sprintf("\"%s\"", time.Time(t).Format("Mon Jan _2"))
    return []byte(stamp), nil
}
```

```
type Document struct {
    Name        string
    Content     string
    Stamp       JSONTime
    Author      string
}
```

**Comment by astaxie** [comment]
http://choly.ca/post/go-json-marshalling/

**Comment by mo0feng** [comment]
xie manito! accept my knees.
