### ISSUE TITLE
If I haven't choose file in multipart form,"GetFile" does not return error 

### ISSUE THREAD

**Issue by zhuscat** [astaxie/beego#1962]
If I don't choose file in multipart form,"GetFile" does not return error.
Here is my code:

```
f, h, err := self.GetFile("avatar")
defer f.Close()
```

If I don't choose file, It will have error:
runtime error: invalid memory address or nil pointer dereference

How to solve this problem?

**Comment by ysqi** [comment]
hi @zhuscat  By default will return `ErrMissingFile = errors.New("http: no such file")`  if file not upload.
you need check err before close file , such as like this:
```go
f,h,err:=self.GetFile("avatar")
if err != nil {
    //some code
}
defer f.Close()
```

**Comment by zhuscat** [comment]
@ysqi 
Thanks! This can solve my problem.
But I'm wondering why the following code(from [beego.me](http://beego.me/docs/mvc/controller/params.md)) can't work(put `defer f.Close` to the front):

```
func (c *FormController) Post() {
    f, h, err := c.GetFile("uploadname")
    defer f.Close()
    if err != nil {
        fmt.Println("getfile err ", err)
    } else {
        c.SaveToFile("uploadname", "/www/"+h.Filename)
    }
}
```
If I don't choose a file, It will have an error:
runtime error: invalid memory address or nil pointer dereference

**Comment by astaxie** [comment]
as you can the `f.Close()`, while `f` is nil.

**Comment by zhuscat** [comment]
Oh! I get the point!

**Comment by zhuscat** [comment]
Oh! I get the point!
