### ISSUE TITLE
set log file perm error

### ISSUE THREAD

**Issue by coseyo** [astaxie/beego#1965]
go version: 1.6.1
beego 1.6.1
os centos6

set log file perm error
as below:

log.SetLogger("file", `{"filename":"test3.log","maxlines":4,"perm":0600}`)

run test show the error:
logs.BeeLogger.SetLogger: invalid character '6' after object key:value pair

**Comment by JessonChan** [comment]
this is a bug in set perm of file log https://github.com/astaxie/beego/pull/1948

**Comment by coseyo** [comment]
had fixed
