### ISSUE TITLE
The problem about beego API

### ISSUE THREAD

**Issue by pathbox** [astaxie/beego#1970]
Today I try to use beego api to build a project。
when I import  "github.com/astaxie/beego/plugins/auth" and add this “beego.InsertFilter("*", beego.BeforeRouter, auth.Basic("admin", "admin"))” in main.go according to the beego API document.
The basic http auth works, but "127.0.0.1:8080/docs" page don't get the response json. And "127.0.0.1/swagger/swagger-1" page  shows 

>  "Can't read swagger JSON from http://127.0.0.1:8080/docs"

When I don't add auth module, The swagger document works. I don't know what is the problem about this.  So I ask for a solution please.

**Comment by astaxie** [comment]
beego 1.7.0 use swagger 2.0, should solved these problem
