### ISSUE TITLE
Request aborts while updating a record in MYSQL

### ISSUE THREAD

**Issue by priyankaNav** [astaxie/beego#1975]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by priyankaNav** [comment]
1.4.1
go


i was trying to update a row in MYSQL db  using beego ORM and the request doesn't get served
it keeps running n finally says request time out. I had two small updates in my scenerio .

This is the code i wrote

func RemoveEmployee(employeeId string) (map[string]interface{}, error) {
	fmt.Println("**************************Employee*****************************")

	o := orm.NewOrm()
	errTrans := o.Begin()
	var Response map[string]interface{} = make(map[string]interface{})

	var employee Employee
	employee.EmpId = employeeId
	err := o.Read(&employee, "emp_id")
	if err == orm.ErrNoRows {
		return Response, errors.New("ER1004: " + util.ER1004)
	}
	if err != nil {
		return Response, errors.New(util.DBError)
	}
	fmt.Println(employee)
	if employee.IsActive == util.Active {
		//if employee.Role.Id == util.MANAGER{}
		employeesUnderGivenEmpId, employeeErr := GetEmployeesUnderMe(employee.Id)
		if employeeErr != nil {
			return Response, employeeErr
		}
		//var EmployeesList []
		if len(employeesUnderGivenEmpId) > 0 {
			Response[util.MESSAGE] = util.ErrorEmployeesReportingToManager
			Response[util.REPORTING_EMPLOYEE_LIST] = employeesUnderGivenEmpId
			return Response, nil
		}
		//close an active review of the employee
		var review Review
		review.Employee = &employee
		review.IsActive = util.Active
		reviewErr := o.Read(&review, "Employee", "IsActive")
		if reviewErr != nil {
			employee.IsActive = util.NotActive
			// num1, notRemoved := o.Update(&employee)
			num1, notRemoved := o.QueryTable("employee").Filter("emp_id", employeeId).Update(orm.Params{"is_active": util.NotActive})
			if notRemoved != nil || num1 == 0 {
				return Response, errors.New(util.RemoveEmployeeFailed)
			}
		} else {
			fmt.Println("review",review)
			fmt.Println("Iam here")
			review.IsActive = 2
			_, err1 := o.Update(&review)
			if err1 != nil {
				fmt.Println("err1", err1)
				return Response, errors.New(util.ErrorEmployeeActiveReviewNotClosed)
			}
			// num, updateErr := o.QueryTable("review").Filter("id", reviewInfo.Id).Update(orm.Params{"is_active": util.Completed})
			// if updateErr != nil || num == 0 {
			// 	return Response, errors.New(util.ErrorEmployeeActiveReviewNotClosed)
			// }
			fmt.Println("Iam here")
			employee.IsActive = 2
			_, err := o.Update(&employee, "IsActive")
			if err != nil {
				fmt.Println("err", err)
				return Response, errors.New(util.RemoveEmployeeFailed)
			}
			// num1, notRemoved := o.QueryTable("employee").Filter("emp_id", employeeId).Update(orm.Params{"is_active": util.NotActive})
			// if notRemoved != nil || num1 == 0 {
			// 	return Response, errors.New(util.RemoveEmployeeFailed)
			// }
		}
	}
	if errTrans != nil {
		errTrans = o.Rollback()
		fmt.Println("rollback error ", errTrans)
		return Response, errors.New(util.RemoveEmployeeFailed)
	} else {
		o.Commit()
	}

	Response[util.MESSAGE] = util.EmployeeRemovedSuccessfully
	Response[util.REPORTING_EMPLOYEE_LIST] = make([]map[string]interface{}, 0)
	return Response, nil
}




here employee and review are two different tables both have is active field and i was trying to update is_active field

**Comment by priyankaNav** [comment]
And one more important thing is that  it some times works all fine, the same code.. and sometimes it doesn't . I really don know. In my current project i have at least 10 updates and they are working fine but  when used two updates back to back even one doesn't work. I had a situation where i had 4 Updates in a API it was aborting so i had to break it down into three separate tasks to make it work. But this one i can't break into two APIs as i want it to be updated on deleting an employee. Please help me with this.

**Comment by ysqi** [comment]
You can try use  Struct Filed but not the db table column, I'm not sure it  work well.
```go
o.QueryTable("employee").Filter("emp_id", employeeId).Update(orm.Params{"is_active": util.NotActive})
```
change:
```go
o.QueryTable("employee").Filter("EmpId", employeeId).Update(orm.Params{"IsActive": util.NotActive})
```

I find your code id not same  in block `if-else`
