### ISSUE TITLE
Fail to retrieve params when the allowed method is set to "delete"

### ISSUE THREAD

**Issue by Atlis** [astaxie/beego#1977]
Hi,

Here is something that I did not expect:

Go and Beego version:
```
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64
```

Operating system and processor architecture:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH= hidden
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

The following works perfectly when the allowed method is set to `post`:
```
beego.Router("/api/user", &controllers.MainController{}, "post:DeleteUser")
```
The controller is able to retrieve the parameters passed into the body of the request.
But when the allowed method is switched to `delete`:
```
beego.Router("/api/user", &controllers.MainController{}, "delete:DeleteUser")
```
the controller is unable to retrieve the parameters passed into the body, returning an empty string instead of the correct value, such that:
```
type deleteUserForm struct {
	Password string `form:"Password" valid:"Required"`
}

// DeleteUser permanently deletes the user account.
func (c *MainController) DeleteUser() {
	...

	f := &deleteUserForm{}
	v, err := c.ValidateForm(f)
	if !v || err != nil {
		return
	}

	...
}
```
returns the error `Password: Can not be empty` only when the allowed method is set to `delete`. When trying to access the value directly with `c.GetString("Password")`, an empty string is returned.

Thank you!

**Comment by JessonChan** [comment]
delete is like get,the param's should be in url

**Comment by Atlis** [comment]
Ok, you're right, I just learned something. In this specific case however, the parameter is a password and I don't think passing it in the url is a good idea, even on https. I'll switch to `put`. Thanks!
