### ISSUE TITLE
orm foreign key question

### ISSUE THREAD

**Issue by Larqus** [astaxie/beego#1978]
Go 1.6
beego 1.6

Hi everyone. I've got a question about tables relations (foreign key)
I am totally rookie. I was trying solve that problem but ... 

`type Post struct {
    Id    int
    Title string
    User  *User  `orm:"rel(fk)"`
}

type User struct {
    Id    int
    Name  string
    Posts []*Post `orm:"reverse(many)"`
}
` 
Tables structure show us
user_id  - field in Post table. 
How can I realize Insert and Update functions in that case.
Thanks.

**Comment by ysqi** [comment]
hi @Larqus  You can study form beego document ,see[ here](http://beego.me/docs/mvc/model/query.md#post-and-user-are-manytoone-relation.-i.e.%3A-foreignkey-is-user)

And let me know about the result.

**Comment by Larqus** [comment]
http://beego.me/docs/mvc/model/query.md#user-and-profile-is-ontoone-relation - 
idea came from this example - problem solved.
