### ISSUE TITLE
Insert Rows a null field ,return error 1062

### ISSUE THREAD

**Issue by lyb124553153** [astaxie/beego#1982]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go1.6
beego 1.4
mysql 5.6
2. What operating system and processor architecture are you using (`go env`)?
ubuntu 14.0

3. What did you do?
I try to set a field can be null and unique
```

type SomeperInfo struct {
	Id            int64
	Rermark   string  `orm:"size(100);null;unique" form:"Info"  valid:"Required"`
	Status        int       `orm:"default(2)" form:"Status" valid:"Range(1,2)"`
     ....
}

func(){
	o := orm.NewOrm()
	info:= new(SomeperInfo )
	info.Status        = 1
	id,err :=  o.Insert(machine)
}

```
After I try to Insert a row,even I don't set the value of the field ‘Reemark’ ,it well set info.Remark to a empty string,not a null field.
then the next time,I try to Insert rows,then mysql will return a error 1062

5. What did you see instead?
 how can I set can be null  and be unique at the same time

**Comment by astaxie** [comment]
not support string unique
