### ISSUE TITLE
自动化api

### ISSUE THREAD

**Issue by qifanrui** [astaxie/beego#1983]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

beego 1.6.1  bee 1.4.1
2. What operating system and processor architecture are you using (`go env`)?

win10 x86
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

自动化api中  // @Param TerminalInfo body models.TerminalInfo true " "不能解析
type TerminalInfo struct {
	AppKey string        `json:"appkey"`
	Data   string        `json:"data"`
	Tag    string        `json:"tag"`
}
4. What did you expect to see?
在swagger中可以显示TerminalInfo的解析结果
5. What did you see instead?
就是TerminalInfo的字符串

**Comment by davidstack** [comment]
@qifanrui  我也遇到相同的问题，你解决了吗？

**Comment by astaxie** [comment]
fixed in beego1.7
