### ISSUE TITLE
Access file error 403 Forbidden

### ISSUE THREAD

**Issue by jonathandion** [astaxie/beego#1985]
Hi,

I would like to work with this library for my socket app : https://github.com/googollee/go-socket.io

I added the library and added my path like this ```beego.SetStaticPath("/socket.io/", "socket.io")```

When I go http://localhost:9000/socket.io/socket.js it's working but when I try http://localhost:9000/

I have an error 403 Forbidden

It's possible to allow this file on http://localhost:9000/ ? 

Thanks.

**Comment by astaxie** [comment]
`beego.SetStaticPath("/", "socket.io")` then you can access `http://localhost:9000/socket.js`
