### ISSUE TITLE
Beego Scaffold and migration Problem

### ISSUE THREAD

**Issue by zmingshi** [astaxie/beego#1986]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
`bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64`

2. What operating system and processor architecture are you using (`go env`)?
`GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zm/workspace/gowork"
GORACE=""
GOROOT="/home/zm/local/go"
GOTOOLDIR="/home/zm/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"`

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I create a new project,  `bee new hello`, then i use scaffold generate code, the command is like this:
`bee generate scaffold user --fields="name:string, bio:text" -driver=mysql -conn="root:*@tcp(127.0.0.1:3306)/test"`
it helps to generate controller, model and migrate the database. The user model struct is like this:
```
type User struct {
	Id   int64  `orm:"auto"`
	Name string `orm:"size(128)"`
	Bio  string `orm:"type(longtext)"`
}
```
After i config the database, i add a router like this:
`beego.Router("/user/:id", &controllers.UserController{}, "get:GetOne")`
and manually insert a line to the table user. Finally, I start the application like this:  
`bee run hello`
I access the url :  http://localhost:8080/user/1, 
access log is as bellows
```
2016/06/09 16:34:58 [SUCC] Build was successful
2016/06/09 16:34:58 [INFO] Restarting hello ...
2016/06/09 16:34:58 [INFO] ./hello is running...
2016/06/09 16:34:58 [asm_amd64.s:1998][I] http server Running on :8080
[ORM] - 2016-06-09 16:35:06 - [Queries/default] - [  OK / db.QueryRow /     0.2ms] - [SELECT `id`, `name`, `bio` FROM `user` WHERE `id` = ?] - `1`
2016/06/09 16:35:06 [router.go:829][D] | GET        | /user/1                                  | 455.072µs        | match      | /user/:id                                | 
```
but I get Error message:   **"Error 1054: Unknown column 'bio' in 'field list'"**.  I took a long time but I did not solve this problem. Please help to solve this, many thanks !

**Today, I drop the "bio" column by chance and add the column manually using sql, I find everything is all right**. But when I refresh the table like this 
`bee migrate refresh -driver=mysql -conn="root:*@tcp(127.0.0.1:3306)/test"`
the proble above bob up again!  Please help to solve this problem.

4. What did you expect to see?
Someone can help to explain and solve this problem.

5. What did you see instead?

**Comment by nanohard** [comment]
Check the column name in the database. I don't think beego/orm formats the name of the field correctly; at least, I didn't see anything in the docs about how it formats the column name. You might want this:

```
type User struct {
    Id   int64  `orm:"auto"`
    Name string `orm:"size(128)"`
    Bio  string `orm:"column(bio);type(longtext)"`
}
```
http://beego.me/docs/mvc/model/models.md

**Comment by astaxie** [comment]
it looks like a bee migration problem.

**Comment by astaxie** [comment]
moving to beego/bee
