### ISSUE TITLE
can't find templatefile in the path when run via executable

### ISSUE THREAD

**Issue by brayanph** [astaxie/beego#1989]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
amd64, windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

- create new project
`bee new myproject`
- build an executable
`go get -v myproject`
- run the executable from bin
`cd bin/myproject.exe`

4. What did you expect to see?

the welcome to beego page

5. What did you see instead?

beego error page
beego:can't find templatefile in the path:index.tpl

**Comment by astaxie** [comment]
please use the `bee run` as `go get` install the binary into the `gopath/bin`, while the static file still in the `gopath/src/myproject`
