### ISSUE TITLE
htttplib DELETE how to send parameters

### ISSUE THREAD

**Issue by xkeyideal** [astaxie/beego#1990]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
not support delete with params

**Comment by xkeyideal** [comment]
Thanks, I had rewrited your code to support for my requirement

**Comment by astaxie** [comment]
👍
