### ISSUE TITLE
BeeTemplates scope

### ISSUE THREAD

**Issue by thanzen** [astaxie/beego#1991]
@JessonChan , I noticed that in one of the [commits](https://github.com/astaxie/beego/commit/3da28535fe5aae6f0515cfb8c13b13041ac2d1d6) you have changed the scope of the BeeTemplates to internal use only, this will make template related functionalities totally hidden from outside,  which you may have good reason.
However, I have one use case is that I need to get rendered template(it is located under view folder) content and send it as email. As I am not able to get the Template through BeeTemplates[path] any more, how would you archive this goal now?
Thanks

**Comment by astaxie** [comment]
as from Go1.6, if the map read/write in concurrency, the program will crash. That's why we hidden the BeeTemplates. If you want to get the Template through BeeTemplates[path].


```
out:=bytes.NewBuffer()
beego.ExecuteTemplate(out, path, data)
```
