### ISSUE TITLE
安装 beego 出错

### ISSUE THREAD

**Issue by yuezhaoxuan** [astaxie/beego#1992]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go 1.6.2  ，beego  使用命令：go get github.com/astaxie/beego 不知道version。
2. What operating system and processor architecture are you using (`go env`)?
Ubuntu intel 4 核

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by yuezhaoxuan** [comment]
root@bogon:/goobject# go get github.com/astaxie/beego
# github.com/astaxie/beego/utils
src/github.com/astaxie/beego/utils/mail.go:405:20: error: reference to undefined identifier ‘sync.Pool’
 var bufPool = sync.Pool{
                    ^
src/github.com/astaxie/beego/utils/mail.go:405:24: error: expected ‘;’ or newline after top level declaration
 var bufPool = sync.Pool{
                        ^
src/github.com/astaxie/beego/utils/mail.go:408:2: error: expected declaration
  },
  ^
# github.com/astaxie/beego/logs
src/github.com/astaxie/beego/logs/log.go:117:17: error: reference to undefined identifier ‘sync.Pool’
 var logMsgPool *sync.Pool
                 ^
src/github.com/astaxie/beego/logs/log.go:134:21: error: reference to undefined identifier ‘sync.Pool’
  logMsgPool = &sync.Pool{
                     ^
src/github.com/astaxie/beego/logs/log.go:134:25: error: expected ‘;’ or ‘}’ or newline
  logMsgPool = &sync.Pool{
                         ^
src/github.com/astaxie/beego/logs/log.go:135:27: error: expected ‘;’ or newline after top level declaration
   New: func() interface{} {
                           ^
src/github.com/astaxie/beego/logs/log.go:137:3: error: expected declaration
   },
   ^
src/github.com/astaxie/beego/logs/log.go:139:2: error: expected declaration
  bl.wg.Add(1)
  ^
src/github.com/astaxie/beego/logs/log.go:140:2: error: expected declaration
  go bl.startLogger()
  ^
src/github.com/astaxie/beego/logs/log.go:141:2: error: expected declaration
  return bl
  ^
src/github.com/astaxie/beego/logs/log.go:142:1: error: expected declaration
 }
 ^
src/github.com/astaxie/beego/logs/log.go:135:25: error: missing return at end of function
   New: func() interface{} {
                         ^

**Comment by syang** [comment]
@astaxie @JessonChan @yuezhaoxuan 看看是不是和https://github.com/astaxie/beego/issues/1995一个问题

**Comment by astaxie** [comment]
please update your go version
