### ISSUE TITLE
使用 bee 工具新建项目时生成的 import 用的是绝对路径

### ISSUE THREAD

**Issue by godblesshugh** [astaxie/beego#1994]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.0
Go    :go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
使用 bee new TestProject
在 main.go router.go default.go 里面，import 当前项目的方式是绝对路径（OS X）：
_ "Users/test/Projects/Go/workspace/src/WordFilter/routers"
"Users/test/Projects/Go/workspace/src/WordFilter/controllers"
会报错说找不到引入的 package，应该是引入当前目录所匹配的 GOPATH 才对吧？并且去掉重复的路径：
_ "WordFilter/routers"
_ "WordFilter/controllers"

以上

**Comment by ysqi** [comment]
Go env not contains `GOPATH`

**Comment by godblesshugh** [comment]
![image](https://cloud.githubusercontent.com/assets/7351942/16367158/3afcb3f2-3c53-11e6-834b-02688fee1136.png)

**Comment by astaxie** [comment]
@godblesshugh please paste the full path.

**Comment by godblesshugh** [comment]
GOPATH="/Users/hugh/Development/Go_Package:/Users/hugh/Projects/Feeling_Code/Go/Feeling-KeywordFilter:/Users/hugh/Projects/Feeling_Code/Go/sego:/Users/hugh/Projects/Feeling_Code/Go/workspace"

**Comment by astaxie** [comment]
@godblesshugh does all the gopath exist in your system?

**Comment by godblesshugh** [comment]
@astaxie yes, one for all packages and three other workspaces
