### ISSUE TITLE
CI fails on master branch

### ISSUE THREAD

**Issue by syang** [astaxie/beego#1995]
As of today (6/16/2016), it shows the master branch fails on the CI https://github.com/astaxie/beego/branches.
(目前master branch的CI状态是failed的）

We can see the same from this link as well https://github.com/astaxie/beego, where it shows "build:fail" in the CI tag.
(代码首页的CI tag处也显示同样信息)

I am a starter of using Golang to build API services, and liked Beego very well. I am doing internal advocate of beego. But it would be great if the project is better managed so that this can become the 'Rails for Golang community'.
(我刚刚开始用Golang写一些API service，挺喜欢Beego，上手很快。我也在试图在内部团队里推荐Beego，但是我建议owner想个办法思考一下如何管理项目，把它成长为Golang界的Rails)

**Comment by astaxie** [comment]
because the master branch still use the go vet. but the go team remove that `go get golang.org/x/tools/cmd/vet`. it already fix in develop branch.
