### ISSUE TITLE
router work on local machine but fail on VPS

### ISSUE THREAD

**Issue by ACChe** [astaxie/beego#1996]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
ubuntu 14

------
index.html
`<li><a href="/test"><font color="red">test</font></a></li>`

Router.go
`beego.Router("/test", &controllers.TestController{})`

在本地机器上点击，链接跳转正常
2016/06/17 17:10:40 [router.go:829][D] | GET        | /test                                | 2.794976344s     | match      | /test                                |

丢到服务器上后点击，链接跳转失败
2016/06/17 05:21:09 [router.go:829][D] | GET        | /test                               | 10.042694ms      | notmatch   |

应该怎样去查找原因？

**Comment by ysqi** [comment]
Your VPS sever loss  automatic generated file in dir `routers` ,Pls copy file to VPS from localhost ,and add  automatic generated files to git .
