### ISSUE TITLE
关于不同控制器间的forward

### ISSUE THREAD

**Issue by gloomyzerg** [astaxie/beego#1998]
同一控制器之间可以使用 
```
func (this *TestContoller) A (){
  this.B()
}
func (this *TestContoller) B (){
   xxxx
}
```
不同控制器之间呢 怎么调用其他控制器的方法并保持上下文的传递?

**Comment by astaxie** [comment]
it's your design problem. if that's the common you need to move to a function which you can also pass context to the function
