### ISSUE TITLE
how to user distinct in QueryBuilder ?

### ISSUE THREAD

**Issue by StayYouth1993** [astaxie/beego#2000]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by ysqi** [comment]
@StayYouth1993  Try : 
```go
qb, _ := orm.NewQueryBuilder("mysql")

//query
qb.Select(" distinct id","name").From("user")

sql:=qb.String()
```
