### ISSUE TITLE
ini 配置文件如果包含include，在windows下解析失败

### ISSUE THREAD

**Issue by gaokewoo** [astaxie/beego#2001]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.5 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\work\code\gerrit\go-base-lib;E:\work\code\gerrit\DispatchingSystem\app
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
在conf目录下有两个配置文件：app.conf和dispatch.conf, 其中 app.conf 包含 dispatch.conf
app.conf中的文件内容：
appname = app
httpaddr = "127.0.0.1"
httpport = 8090
runmode = dev

include "dispatch.conf"

在windows下会解析失败，会报找不到 dispatch.conf这个文件，将include内容改为：
include "conf/dispatch.conf" 
可以解析成功。

问题原因：
通过查看ini.go源代码，发现在处理include配置文件时，程序使用了以下代码：
otherfile = path.Join(path.Dir(name), otherfile)
其中的path.Dir函数，在处理windows路径时会直接返回"."，而不是预期的相对路径。

尝试的解决办法：
引入 path/filepath 包，将path.Dir修改为 filepath.Dir就可以正确解析。

**Comment by ysqi** [comment]
include 使用的是 相对路径，Window下是相对于exe的路径的

**Comment by gaokewoo** [comment]
恩，但这样会造成在windows和Linux下会有两种不同的使用体验。
我这边的工作方式是在windows下开发，然后部署在Linux上，因为这个区别，每次上线前都要做一次修改。
如果使用 filepath.Dir 的方式，可以保证在Linux和Windows下都有同样的体验，这样会不会好一些？
