### ISSUE TITLE
How to create a custom recover?

### ISSUE THREAD

**Issue by trietphm** [astaxie/beego#2004]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
Create an admin website

====

How to override Beego's recoverPanic? I have set `recoverpanic = false` and write my own recover but have no luck
 ```
func main() {
	defer recoverPanic()
	beego.Run()
}

func recoverPanic() {
    if err := recover(); err != nil {
        fmt.Println("Panic should go there")
    }
}
```

**Comment by astaxie** [comment]
Beego's recoverPanic has a lot logic inside. why you want to overwrite it? what do you want to solve? Do you want to define the error page? If that the case please reference to http://beego.me/docs/mvc/controller/errors.md

**Comment by windyzboy** [comment]
Hi @astaxie 
I want to catch all unexpected error, e.g. `nil pointer`. And do some stuff such as send email to our maintainers.

**Comment by windyzboy** [comment]
Example, an unexpected nil pointer error
```
	var t *Campaign
	log.Println(t.ID)
	log.Println("Can you go there?")
```

In console, it showed 
```
2016/06/24 11:53:03 [router.go:854][C] the request url is  /campaign 
2016/06/24 11:53:03 [router.go:855][C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:472 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/runtime/panic.go:426 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/runtime/panic.go:45 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/runtime/sigpanic_unix.go:24 
2016/06/24 11:53:03 [router.go:861][C] /home/windyzboy/go/src/waudio-server/admin/controllers/campaign_controller.go:25 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:472 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/reflect/value.go:435 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/reflect/value.go:303 
2016/06/24 11:53:03 [router.go:861][C] /home/windyzboy/go/src/github.com/astaxie/beego/router.go:778 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/net/http/server.go:2081 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/net/http/server.go:1472 
2016/06/24 11:53:03 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:1998 
```

I want to custom this page and send email to our maintainers. 

![image](https://cloud.githubusercontent.com/assets/4161828/16328193/cda9efe8-3a01-11e6-9504-525adba7cffa.png)

**Comment by astaxie** [comment]
We didn't support that now. But that's a good example to support a recover hook
