### ISSUE TITLE
model tag "auto_now_add" not work

### ISSUE THREAD

**Issue by pikeszfish** [astaxie/beego#2010]
1. What version of Go and beego are you using (`bee version`)?
   bee   :1.4.1
   beego :1.6.1
   Go    :go version go1.6.2 darwin/amd64

I have a model

```
import "time"
type A struct {
    Id int
    Distance int `orm:"default(0)"`
    CreateTime time.Time `orm:"auto_now_add;type(datetime)" json:"createTime"`
}
func UpdateAWithA(a *A) error {
    o := orm.NewOrm()
    log.Printf("%+v \n", a)
    _, err := o.Update(a)
    return err
}
```

When update a model (Id=7 Distance=123 CreateTime=nil) with `func UpdateAWithA` , beego logs out with 

```
&{Id:7 Distance:123 CreateTime:0001-01-01 00:00:00 +0000 UTC }
[ORM] - 2016-06-24 10:30:31 - [Queries/default] - [  OK /     db.Exec /     1.8ms] - [UPDATE `a` SET `distance` = ?, `create_time` = ? WHERE `id` = ?] - `123`, `<nil>`, `7`
```

And then in my database the `create_time` of id = 7 was be changed to `0000-00-00 00:00:00`
I think I have set CreateTime's tag with `auto_now_add`, so it cannot be updated when I exec an `update` query.

**Comment by astaxie** [comment]
NO, it only works on add
