### ISSUE TITLE
Serve one static file from root dir

### ISSUE THREAD

**Issue by jonathandion** [astaxie/beego#2012]
Hi, I would like to have access to a text file located in the root of my beego app.

Like this :
www.mysite.com/myfile.txt

I tried :
beego.SetStaticPath("/","/static/myfile.txt")
beego.SetStaticPath("/","/myfile.txt")

None of the examples has worked.

Thanks.

**Comment by youngsterxyf** [comment]
You use `SetStaticPath ` in a wrong way, and you may need to add a specific router to fulfill your requirement.

**Comment by ysqi** [comment]
hi @jonathandion , you can try use two ways 
```go
beego.SetStaticPath("/myfile.txt", "/dev/golang/src/mybeego/server/myfile.txt")
``` 
```go
beego.SetStaticPath("/myfile.txt", "/static/myfile.txt")
```
