### ISSUE TITLE
beego swagger api

### ISSUE THREAD

**Issue by twogoods** [astaxie/beego#2016]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 1.6.1 bee 1.4.1

2. What operating system and processor architecture are you using (`go env`)?
OS X 11

3. What did you do?
`@Success 200 {object} models.User` this annotation will show in api, if i am not use model `models.User` in `@Success` annotation, only use model in `@Param body body models.User true` 
requestbody part is empty
![](https://segmentfault.com/img/bVyzxK)

4. What did you expect to see?
i want to see like this ![](https://segmentfault.com/img/bVyzxF)

5. What did you see instead?
![](https://segmentfault.com/img/bVyzxK)

**Comment by davidstack** [comment]
i have the same problem.do you solve this problem?

**Comment by astaxie** [comment]
fix in new version
