### ISSUE TITLE
download static file at same time with more than 2 goroutine  will get error

### ISSUE THREAD

**Issue by leemoncn** [astaxie/beego#2019]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/limeng/GO:/Users/limeng/Desktop/GoProduct:/Users/limeng/Desktop/SlotServer/SlotServer:/Users/limeng/Desktop/SlotSimulator"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
download static file with more than 2 goroutine at same time, ioutil.RealAll will get unexpected EOF error.
I change my code use golang http.FileServer,then it run right.
is there a bug in beego static file server?

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
should be fixed in beego1.7
