### ISSUE TITLE
缺少cookie相关的文档

### ISSUE THREAD

**Issue by marswj** [astaxie/beego#2022]
session的有，cookie的没有写。

**Comment by marswj** [comment]
直接关掉，是无视的意思吗？我看文档也没变化。还是说cookie的用法根本不重要？

**Comment by linux-mac** [comment]
你应该先打牢自己的基础，或者换个角度思考问题就可以了

**Comment by marswj** [comment]
cookie在特定场景下，是会用到的。想找个用法，还要去翻源码？要什么样的基础，请指教？

**Comment by fuxiaohei** [comment]
https://godoc.org/github.com/astaxie/beego/context#BeegoInput.Cookie
https://godoc.org/github.com/astaxie/beego/context#BeegoOutput.Cookie
https://godoc.org/github.com/astaxie/beego/context#Context.GetCookie
https://godoc.org/github.com/astaxie/beego/context#Context.SetCookie

**Comment by marswj** [comment]
这个我已经翻过源码，找到用法了。我的意思是这种应该写在文档里面，毕竟小白很多。当然你们认为这种没必要的话，当我没说。

**Comment by linux-mac** [comment]
开源的是靠大家维护的，你可以提交 pr

**Comment by astaxie** [comment]
please create the document related to beego/beedoc

**Comment by jinleileiking** [comment]
@linux-mac 你说的没错。但我没见过哪个国外项目提个issue就直接关了的。。。

**Comment by marswj** [comment]
“please create the document related to beego/beedoc”   这句话写上，然后再去关闭，我想我会花点时间去弄个pr。提交bug，无非就是只会简单使用，如果要写成可以给别人阅读的文档，要花费一番功夫。如果就是写代码的人，分分钟就能搞定。如果没时间的话，我也能凑合弄个，然后你再在基础上修改。不过简单粗暴的关闭，啥都不说，不好意思，我对此没有什么好的印象。有这个时间，还不如多陪陪小孩。

**Comment by mrkt** [comment]
Submit format specification text.
It would be a big problem if everyone would submit it.
