### ISSUE TITLE
ORM模块可否设置关闭prepared模式

### ISSUE THREAD

**Issue by DavadDi** [astaxie/beego#2025]
由于采用了mysql中间件采用了Atlas中间件，在使用ORM模块进行相关数据查询时，会报错：

> [ORM] - 2016-07-04 16:36:53 - [Queries/default] - [FAIL /    db.Query /     1.1ms] - [SELECT T0.`id`, T0.`name`, T0.`desc`, T0.`app_id` FROM `role` T0 INNER JOIN `user_roles` T1 ON T1.`role_id` = T0.`id` WHERE T1.`user_id` = ? LIMIT 1000] - `15001387978` - Error 1243: Unknown prepared statement handler (1313) given to mysqld_stmt_execute

ORM模块是否有相关的参数可以设置，以避免使用server端prepared？多谢！

**Comment by jack0liu** [comment]
碰到类似问题，怎么解决的？

**Comment by jack0liu** [comment]
@astaxie

**Comment by jack0liu** [comment]
已经解决

**Comment by Jiang-Le** [comment]
@jack0liu  您好，请问您当时是怎么解决的？大概的原因是啥呀？

**Comment by tonyttz** [comment]
> @jack0liu 您好，请问您当时是怎么解决的？大概的原因是啥呀？

昨天碰到这个问题, 解决方法是指定连接参数 interpolateParams=true , 如下,
`%s:%s@tcp(%s:%s)/%s?charset=utf8&interpolateParams=true`
解决方法来源: https://github.com/go-sql-driver/mysql/issues/455
golang  mysql 预编译及 InterpolateParams 说明:   https://blog.csdn.net/qq_39384184/article/details/108144309

**Comment by Cbxyf** [comment]
@tonyttz 从 https://blog.csdn.net/qq_39384184/article/details/108144309 这个文章里可以看到 interpolateParams 这个参数 是 直接作用在go-sql-driver/mysql下的connection.go 中的 Query 函数， 会影响到database/sql中的 func (db *DB) Query和QueryRow 。而 beego orm ， 虽然底层orm 的 DB 也继承了 database/sql中的 DB，但是其核心函数 没有 直接调用 database/sql的 Query和QueryRow ，而都是 先 做 prepare stmt  。  所以 beego orm 应该是 都使用了 prepare stmt， 不会因为 设置 interpolateParams = ture 就关闭 prepare 吧？

**Comment by Cbxyf** [comment]
> [<img alt="@astaxie" width="20" height="20" src="https://avatars.githubusercontent.com/u/233907?s=60&amp;v=4">](/astaxie) [astaxie](/astaxie) closed this [on 6 Jul 2016](#event-713758913)

您好，请问怎么解决的呢？
