### ISSUE TITLE
cannot pass go vet and lint tools

### ISSUE THREAD

**Issue by ShevYan** [astaxie/beego#2026]
As I know, many go projects require code pass go vet and go lint. However, I find beego cannot pass. Is it possible to enhance this part so that we can use these tools for entire projects which is generated by bee tool?

**Comment by astaxie** [comment]
@ShevYan Beego already use go vet and go lint? which version are you used?

**Comment by ShevYan** [comment]
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64

**Comment by ShevYan** [comment]
Hi,

I submit a PR - https://github.com/astaxie/beego/pull/2029

Could you please take a look?

Shev.
