### ISSUE TITLE
how to validate map[string]interface{}

### ISSUE THREAD

**Issue by skadilover** [astaxie/beego#2028]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
linux

3. What did you do?
this validate package can not validate map[string]interface{}.

4. What did you expect to see?

how about merge this https://github.com/skadilover/easykit/blob/master/validate/main_test.go
5. What did you see instead?

**Comment by astaxie** [comment]
@skadilover could you create a PR to valid the map. From you test case I have no idea on `Property`

**Comment by skadilover** [comment]
"obj" in code is a map[string]interface{}, and "dict" is a map[string]Property which define the schema of json. I use dict to validate obj.

I change my work,and a little busy recently, so PR may be a little later.

**Comment by astaxie** [comment]
fix in beego 1.7
