### ISSUE TITLE
beegoAppConfig.Strings will cause panic

### ISSUE THREAD

**Issue by suwey** [astaxie/beego#2031]
You can fix this in config.go.

```
func (b *beegoAppConfig) Strings(key string) []string {
	if v := b.innerConfig.Strings(BConfig.RunMode + "::" + key); v[0] != "" {
		return v
	}
	return b.innerConfig.Strings(key)
}
```

The code above works fine in older version, but will cause panic after updated. 
The reason is now `b.innerConfig.Strings` will not return `string[]` when empty but will return `nil`, and this nil will cause panic when it run into `v[0] != ""`.

**Comment by youngsterxyf** [comment]
@suwey duplicate issue，refer to issue#2027

**Comment by pawatzaza** [comment]
i tank
