### ISSUE TITLE
Use bee tools to generate new application on windows, find some question.

### ISSUE THREAD

**Issue by nikxliu** [astaxie/beego#2033]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.7beta1 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\tools\Go\bin;D:\tools\workspace\go;E:\worktools\wassupport\WASAUTO\go;D:\tools\workspace\revel
set GORACE=
set GOROOT=D:\tools\Go
set GOTOOLDIR=D:\tools\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
I use the bee tools to generate a new application. It's name is testWeb.on the path D:\tools\workspace\beego\src. 
when I change the directory to D:\tools\workspace\beego\src\testWeb
type the cmd: bee run

there were some problem.

so I check the files 
D:\tools\workspace\beego\src\testWeb\main.go
D:\tools\workspace\beego\src\testWeb\routers\router.go

i found the code in the import stanza like this 
_ ":/tools/workspace/beego/src/testWeb/routers"
":/tools/workspace/beego/src/testWeb/controllers"

I modify the code to 
_ "testWeb/routers"
"testWeb/controllers"

the cmd "bee run"
It worked.
A complete runnable program is good.

4. What did you expect to see?

Can you tell me this is a bug or the problem occured because my mistake.

thanks for your help.

5. What did you see instead?

**Comment by astaxie** [comment]
it looks like the bee generate code has some problem with the GOPATH. could you move this issue to beego/bee.
