### ISSUE TITLE
Way to retrieve config underlying data

### ISSUE THREAD

**Issue by stormherz** [astaxie/beego#2036]
I'm writing small debugging module for beego and I was wondering is there a way to retrieve underlying data object from beego config instance (list of key-value pairs or more complex implementation, depending on configuration type).

I don't see any public methods for this, which is leading to reflection solution, but maybe I'm missing something.

Thanks.

**Comment by astaxie** [comment]
beego.AppConfig

**Comment by Stormherz** [comment]
@astaxie I'm not talking about access to application config, I'm talking about getting ALL name-value pairs of underlying configuration (JSON, INI, or whatever is used by application), not just some of the values.

I'd like to represent loaded config just like it is done in admin module (`/listconf`), but I can't access unexported parts of beego core. Is there plans of making all config params available as a map, for example?

**Comment by astaxie** [comment]
I don't think that's my initial idea. Export more data will make the config out of control

**Comment by Stormherz** [comment]
@astaxie that's true, though it might be helpful from time to time to retrieve all of the configuration fields. Would you accept PR with an additional `GetAll` method of configuration interface, which will be implemented to return all stored key-values of a loaded configuration?

**Comment by astaxie** [comment]
@Stormherz are you suggest to add a function into `config.Configer`? if that's the case, please create a PR. That make sense
