### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by zzs258** [astaxie/beego#2037]
**go get github.com/astaxie/beego**
import cycle not allowed
package github.com/astaxie/beego
        imports bytes
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports unsafe
        imports runtime
import cycle not allowed
package github.com/astaxie/beego
        imports github.com/astaxie/beego/context
        imports github.com/astaxie/beego/session
        imports github.com/astaxie/beego/utils
        imports mime/multipart
        imports net/textproto
        imports net
        imports runtime/cgo
        imports runtime/cgo

**go version**
go version go1.6.1 linux/amd64

是go的版本问题吗?
Is the go version of the problem?

**Comment by zzs258** [comment]
已经修复

**Comment by phppan** [comment]
请问下如何修复的？我升级bee到v1.6.0也出现同样的问题
