### ISSUE TITLE
I want use beego at openshift

### ISSUE THREAD

**Issue by kirigayakazushin** [astaxie/beego#2038]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
GO 1.5

2. What operating system and processor architecture are you using (`go env`)?
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
I want use beego at openshift

5. What did you see instead?
not run.openshift not go get,but like martini is ok.

**Comment by ysqi** [comment]
see https://github.com/dz1984/openshift-beego

**Comment by amrfaissal** [comment]
How is this an issue?! To be closed. /cc @astaxie

**Comment by kirigayakazushin** [comment]
@ysqi  this repo cannot use.  https://github.com/dz1984/openshift-beego

**Comment by bakanis** [comment]
Openshift is a linux container and beego compiles to binary so there is no need to upload source files except view templates. Create a DIY container and put your compiled program binary, conf, views, logs, static there. Then put start and stop bash scripts to .openshift/action_hooks directory They might look like the attached examples

[start.sh.txt](https://github.com/astaxie/beego/files/401019/start.sh.txt)
[stop.sh.txt](https://github.com/astaxie/beego/files/401018/stop.sh.txt)

**Comment by ysqi** [comment]
@kirigayakazushin  so sorry  I find that repo work with beego ,so...
