### ISSUE TITLE
How to bind url parms in format key[0][foo]=bar

### ISSUE THREAD

**Issue by udondan** [astaxie/beego#2039]
1. What version of Go and beego are you using (`bee version`)?

    ```
    bee   :1.4.1
    beego :1.6.1
    Go    :go version go1.6 darwin/amd64
    ```

2. What operating system and processor architecture are you using (`go env`)?

    macOS 10.11.5

    ```
    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    GOPATH="/Users/udondan/go"
    GORACE=""
    GOROOT="/usr/local/Cellar/go/1.6/libexec"
    GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
    GO15VENDOREXPERIMENT="1"
    CC="clang"
    GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
    CXX="clang++"
    CGO_ENABLED="1"
    ```

3. What did you do?

    I'm trying to map url parameters with `ctx.Input.Bind` as documented [here](http://beego.me/docs/mvc/controller/params.md#data-bind). 

    Here is an excerpt of my controller action:

    ```
    func (this *MyController) Foo() {

      type column struct{
        Data string
      }

      columns := []column{}

      if err := this.Ctx.Input.Bind(&columns, "columns"); err != nil {
        log.Fatal(err)
      } else {
        log.Println("OK, got:", columns)
      }

    }
    ```

    And this is my URL:

    ```
    /controller/action?columns[0][data]=foo&columns[1][data]=bar&columns[2][data]=baz
    ```

    To be clear, the documented way works:

    ```
    /controller/action?columns[0].Data=foo&columns[1].Data=bar&columns[2].Data=baz
    ```

    But I can not change how those `columns` objects are passed, the object key is lowercase and in brackets. The request is generated by [DataTables](https://datatables.net/manual/server-side#Sent-parameters).

    How can I map this url to my slice of structs?

4. What did you expect to see?

    ```
    OK, got: [{foo} {bar} {baz}]
    ```

5. What did you see instead?

    ```
    OK, got: [{} {} {}]
    ```

**Comment by tyoldwu** [comment]
the object key is lowercase and in brackets，How to solve this problem?

**Comment by flycash** [comment]
What do you mean?
