### ISSUE TITLE
[Proposal]   实现orm InsertOrUpdate方法

### ISSUE THREAD

**Issue by fudali113** [astaxie/beego#2041]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
mac osx

3. What did you do?
方法体：InsertOrUpdate(md interface{}, args ...string) (int64, error)
实现原理：mysql -> ON DUPLICATE KEY UPDATE
                  postgres -> ON CONFLICT DO UPDATE SET
作用：当主键或者唯一键冲突，执行update 数值或者自增操作
列如：
    mysql：r, e := db.InsertOrUpdate(all, "step=step+1")
当冲突时，step列执行+1自增操作，其他列执行all中数据对应update操作
    postgres：r, e := db.InsertOrUpdate(all, "conflictColumn","step=step+1")
操作postgres数据库时，必须显示制定其冲突列名，且必须为args第一个参数，其他与mysql一致
当不需要自增功能时，mysql只需传入model，postgres传入model和冲突列名

4. What did you expect to see?
我希望看到我的issue能被认同，因为我觉得还是有一部分项目需要这个功能

5. What did you see instead?
我就是在开发需要这个功能，所以决定实现并想传播给有这个需求的同行

**Comment by pawatzaza** [comment]
ok
