### ISSUE TITLE
设置time.local，使用orm的update操作导致时间偏差。

### ISSUE THREAD

**Issue by mashupeng** [astaxie/beego#2055]
表中字段 id，name，createtime。createtime为datetime类型。
设置orm.DefaultTimeLoc = time.Local。

o.QueryTable(obj).Filter("id", Id).One(obj)
obj.Name = “123”
manager.Update(obj)

使用以上类似操作，更新完数据后会导致createtime的值向前移动8小时。比如创建的时候createtime值为2016-07-13 14:53:55，更新完后变成了2016-07-13 06:53:55，这个怎么解决？

**Comment by ChongyuE** [comment]
connect string username:password@tcp(192.168.1.20:3306)/db?charset=utf8&loc=Asia%2FShanghai
