### ISSUE TITLE
ParseForm不能处理匿名struct中的字段，Valid也不行

### ISSUE THREAD

**Issue by zlywq** [astaxie/beego#2056]
ParseForm不能处理匿名struct中的字段。我已经在另一个分支有修改，可以参考https://github.com/zlywq/beego 上面的提交(SHA-1: 6f55504e9b7814bcdd2a54884682bd08ee268138)

**Comment by zlywq** [comment]
valid不能处理匿名struct中的字段。我已经在另一个分支有修改，可以参考https://github.com/zlywq/beego 上面的提交(SHA-1: 5ff461b70b1941ef13fe389a3e3bc537fa273ba6)

**Comment by astaxie** [comment]
please create the PR
