### ISSUE TITLE
模板文件 error calling eq: invalid type for comparison

### ISSUE THREAD

**Issue by crazyvv** [astaxie/beego#2058]
beego 1.6.1 (beego framework)

$ go version

> go version go1.7rc2 windows/amd64

$ go env

> set GOARCH=amd64
> set GOBIN=
> set GOEXE=.exe
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOOS=windows
> set GOPATH=E:\project_code\go\
> set GORACE=
> set GOROOT=D:\Go
> set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
> set CC=gcc
> set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxxx\AppData\Local\Temp\go-build161558054=/tmp/go-build -gno-record-gcc-switches
> set CXX=g++
> set CGO_ENABLED=1

**Lot数据结构**
```
type Lot struct {
    Id     int32     `orm:"auto;column(id);pk"`
    Lot    string    `orm:"column(lot)"`
    Time   time.Time `orm:"type(datetime)"`
    PortIp []*PortIp `orm:"column(port_id);reverse(many)"`
    IpPort []*IpPort `orm:"column(ip_port);reverse(many)"`
}
```

**用到的函数如下**：
################################################
```
func listlot() []models.Lot {
    o := orm.NewOrm()
    var lots []models.Lot
    o.QueryTable("Lot").All(&lots)
    return lots
}

type ApiController struct {
    beego.Controller
}

func (test *ApiController) ComparePost() {
    cll, _ := test.GetInt32("currentlot")
    pll, _ := test.GetInt32("prelot")

    cl := models.Lot{Id: cll}
    pl := models.Lot{Id: pll}

    test.Data["cl"] = cl  //直接int32(cll),然后模板里使用$.cll也同样的错
    test.Data["pl"] = pl   //直接int32(pll),然后模板里使用$.pll也同样的错

    lots := listlot()
    test.Data["lots"] = lots

    test.Data["css"] = compareresult(cll, pll)
    test.TplName = "compare.tpl"
}
```
################################################

**模板内容**
################################################
```
<form id="lot" method="post">
    基准批次标记：<select name="currentlot">
        {{range $num,$lot := .lots }}
          <option value="{{$lot.Id}}" {{if eq $.cl.Id $lot.Id}}selected="selected"{{end}}>{{$lot.Id}}-{{$lot.Lot}}-{{$lot.Time}}</option>
        {{end}}
    </select> 
    对比批次选择：<select name="prelot">
        {{range $num,$lot := .lots }}
          <option value="{{$lot.Id}}" {{if eq $.pl.Id $lot.Id}}selected="selected"{{end}}>{{$lot.Id}}-{{$lot.Lot}}-{{$lot.Time}}</option>
        {{end}}
    </select>
    <input type="submit" value="提交" />
</form>
```
################################################

################################################
**问题及描述**
完整的代码可以编译通过

报错内容
PortScaner:template: compare.tpl:12:59: executing "compare.tpl" at <eq $.cl.Id $lot.Id>: error calling eq: invalid type for comparison

Request Method: GET
Request URL:    /api/compare
RemoteAddr: 127.0.0.1
Stack
D:/Go/src/runtime/asm_amd64.s:479
D:/Go/src/runtime/panic.go:458
E:/project_code/go/src/github.com/astaxie/beego/router.go:786
D:/Go/src/net/http/server.go:2203
D:/Go/src/net/http/server.go:1580
D:/Go/src/runtime/asm_amd64.s:2086

其中第12行即为

`<option value="{{$lot.Id}}" {{if eq $.cl.Id $lot.Id}}selected="selected"{{end}}>{{$lot.Id}}-{{$lot.Lot}}-{{$lot.Time}}</option>`

如果将{{if eq $.cl.Id $lot.Id}} 中的 $.cl.Id  以及后面的$.pl.Id 直接替换为整数数字，比如4，则不会报错。

问题

1. 使用reflect.TypeOf()检查对应的变量，类型是一致的，为什么会报invalid type for comparison这个错？
2. 当把$.cl.Id   $.pl.Id改为直接的整数数字后，刷新页面不报错，然后再改会变量的方式，不刷新页面，直接post，不会报错，而一旦刷新页面又会报错。

感觉是个BUG.....

**Comment by astaxie** [comment]
It's a beego's bug. we only support int now. https://github.com/astaxie/beego/blob/88c5dfa6ead42e624c2e7d9e04eab6cb2d07412a/templatefunc.go#L570

**Comment by astaxie** [comment]
@crazyvv I just double check the code in beego. it looks not the beego's bug. could you print out the  reflect.TypeOf()?

**Comment by crazyvv** [comment]
在ComparePost() add  code:
```
	fmt.Println("cll", reflect.TypeOf(cll), "pll:", reflect.TypeOf(pll))
	fmt.Println("cl:", reflect.TypeOf(cl), "pl:", reflect.TypeOf(pl))
	fmt.Println("cl.Id:", reflect.TypeOf(cl.Id), "pl.Id:", reflect.TypeOf(pl.Id))
	fmt.Println("lots:", reflect.TypeOf(lots))

	for k, v := range lots {
		fmt.Println(k, v)
		fmt.Println("v.Id:", reflect.TypeOf(v.Id))
	}

```

output:
> cll int32            pll: int32
> cl: models.Lot   pl: models.Lot
> cl.Id: int32        pl.Id: int32
> lots: []models.Lot
> 0 {4 test 2016-07-13 01:31:57 +0800 CST [] []}
> v.Id: int32
> 1 {5 port 2016-07-13 01:31:57 +0800 CST [] []}
> v.Id: int32

**Comment by crazyvv** [comment]
sorry,我想我找到问题了，不是beego 的bug，是我自己逻辑的问题，
一个post方法，一个get方法，get方法未给test.Data["cl"]赋值，导致test.Data["cl"]为空，所以类型不对，
这正好也解释了我的问题2，为什么直接改模板post可以，而刷新不可以，因为刷新了以后是get方法。所以报错，而不刷新页面，直接提交，是用的post方法。

**Comment by astaxie** [comment]
make sense
