### ISSUE TITLE
路由匹配问题

### ISSUE THREAD

**Issue by isunimp** [astaxie/beego#2059]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

`1.6.1`
2. What operating system and processor architecture are you using (`go env`)?

`osx`
3. What did you do?

> 使用`bee api`创建了一个新的api项目，`bee run` 运行，浏览器输入 `http://127.0.0.1:8080/v1/user/hhh` ,看日志输出 | match      | /v1/user/:uid 

4. What did you expect to see?

我尝试去router.go文件中去查看路由设置，发现只注册了两个namespace路由（user object），那么是如何将hhh赋值到变量uid的，能否更改为其他变量名 如id

5. What did you see instead?

**Comment by astaxie** [comment]
please check the controler's comments.
