### ISSUE TITLE
我就不明白了，提了issue，直接给关了 ，是什么意思？

### ISSUE THREAD

**Issue by jinleileiking** [astaxie/beego#2060]
哎。。

**Comment by mrkt** [comment]
session是独立的模块

**Comment by marswj** [comment]
是蛮粗暴的。有问题可以讨论，不是每个人都是大神，小白要成长。直接关掉，那么一点点开源热情，一泡尿浇灭了。

**Comment by fuxiaohei** [comment]
1. 提交issue请填写好基本的模板信息

```
Please answer these questions before submitting your issue. Thanks!

What version of Go and beego are you using (bee version)?

What operating system and processor architecture are you using (go env)?

What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

What did you expect to see?

What did you see instead?
```

2. 提交之前请先查询文档和godoc的API，如果没有找到资料再来填写issue

3. 如果是需要做新的功能，请详细叙述功能要求和期望的改进方式，不要简单一句话

**Comment by astaxie** [comment]
@jinleileiking @marswj 你们说的都很对，但是你们换位思考一下我，要维护一个开源项目每天收到20-30个notifications，然后还说的不明不白的issue，我需要花费很长的时间才能去猜对这样的实际存在的问题，所以才会有了issue模板，然而你们提问的时候都无视了，issue变成了一个你们问小白问题的地方，issue是为了能够复现一个问题或者新需求的地方，只要有问题就提issue那么很多时候就会变成很低效的地方，所以我现在的做法就是不遵循issue规则的就直接close，这是我最后一次这里解释了，希望大家能够理解。
