### ISSUE TITLE
Router path parameter problem

### ISSUE THREAD

**Issue by benzsuankularb** [astaxie/beego#2061]
Please answer these questions before submitting your issue. Thanks!

 1. What version of Go and beego are you using (`bee version`)?

My Local Server & Deployment Server
beego 1.4.1
bee 1.6.1

 2. What operating system and processor architecture are you using (`go env`)?

My Local Server & Deployment Server
arch = amd64
goos = darwin

 3. What did you do?
I set my route to /api/user/:userId like so.

```
// @Title XXX
// @Param user_id	path string false 	"user id"
// @router /user/:user_id [get]
```

 4. What did you expect to see?

I expected to see the same both Local Server & Deployment Server
When route to /user/123, This should work fine.
When route to /user, This should work find with :user_id = "".

 5. What did you see instead?

In Local Server
I route to /user/123, This work fine.
I route to /user, This work fine with :user_id = "".

In Deployment Server
I route to /user/123, This work fine.
I route to /user, This route not found.

**Comment by astaxie** [comment]
@benzsuankularb how did you deployment? in which mode? did you build the generated router into that files?
