### ISSUE TITLE
how to config static file http cache-control header 

### ISSUE THREAD

**Issue by imiskolee** [astaxie/beego#2068]
how to config static file http cache-control header ?

**Comment by astaxie** [comment]
I think you can use the plugins for all the static request. add you own header into context

**Comment by ysqi** [comment]
@imiskolee  ,You can use router filter to do somethings for the matched url , the [doc](http://beego.me/docs/mvc/controller/filter.md) didn't contains anyting for the filter `BeforeStatic` ,but that suported ,see [code](https://github.com/astaxie/beego/blob/master/router.go#L37) ,  such as like this:
```go
beego.InsertFilter("/static/*", beego.BeforeStatic, func(ctx *context.Context) { 
		ctx.Output.Header("Cache-control", "max-age=5")
})
```
