### ISSUE TITLE
How to modify the directory structure of beego

### ISSUE THREAD

**Issue by thorad** [astaxie/beego#2070]
Please answer these questions before submitting your issue. Thanks!

bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.3 windows/amd64

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoSites
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

I moved the controllers, models, static, and views directories into a new directory 'app' in order to clean up the directory structure, this caused a number of routing and file path errors.

How do I modify the project to account for the changing of the directory structure without causing errors?

**Comment by astaxie** [comment]
try use these command https://github.com/golang/tools/tree/master/cmd/gomvpkg
