### ISSUE TITLE
run quickstart(bee run) error: fork/exec /usr/local/bin/go: exec format error

### ISSUE THREAD

**Issue by xumeng** [astaxie/beego#2073]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
**bee   :1.4.1
beego :1.6.1
go version go1.5.2 darwin/amd64**

2. What operating system and processor architecture are you using (`go env`)?
**GOHOSTARCH="amd64"
GOHOSTOS="darwin"**

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
**/src/quickstart git:(master) ✗>bee run
bee   :1.4.1
beego :1.6.1
fork/exec /usr/local/bin/go: exec format error**

4. What did you expect to see?

5. What did you see instead?

Cannot using 'bee run', and it show error as above.

**Comment by astaxie** [comment]
@xumeng please move the bee issue to github.com/beego/bee thanks
