### ISSUE TITLE
API doc dos't escape the "`" character

### ISSUE THREAD

**Issue by tnextday** [astaxie/beego#2074]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

`bee generate docs`  need  escape  string  when the API doc contains the ` character

**Comment by astaxie** [comment]
@tnextday please move the bee issue to https://github.com/beego/bee
