### ISSUE TITLE
添加路由之后，不执行路由里面的方法

### ISSUE THREAD

**Issue by VesperHan** [astaxie/beego#2076]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee bersion 1.4.1

2. What operating system and processor architecture are you using (`go env`)?
go1.6.2

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

- 已经存在的工程，但没有使用bee api现在集成
- 使用bee工具生成api demo工程
- 添加一个测试路由和function 使用demo样式添加，自动生成文档的样式
- 但是无法访问我路由的方法，如果替换成demo的方法就可以执行，我自己写的方法就不执行
- 已经注释了一行 @ router /  [post] 就写了这一行
- 为什么 我把 app.conf删除之后也会跑起来，感觉app.conf干脆就是没用读取
4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
下次要学会怎么提issue，你自己先读一遍这个issue，看看是不是可以从你的文字里面让我读懂
