### ISSUE TITLE
添加路由之后，不自动更新commentsRouter

### ISSUE THREAD

**Issue by VesperHan** [astaxie/beego#2078]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by ysqi** [comment]
You need exec `bee run`  for rebuild comment router
