### ISSUE TITLE
nginx proxy beego service, get request return 405 Method Not Allowed

### ISSUE THREAD

**Issue by wednesdaysunny** [astaxie/beego#2080]
我的beego项目，当我使用bee run 运行项目的时候， 我访问 http://localhost:8090/example (8090是我service的端口)， 是没有问题的，当我使用nginx作为代理的时候，我访问http://localhost/example 的时候，返回 405 Method Not Allowed，但不是 每次都是405， 大概会两次请求返回一次405， 请帮忙看下是什么问题， 谢谢

@astaxie

**Comment by astaxie** [comment]
405 Method Not Allowed

please make sure all the request is correctly proxy to the service

**Comment by jinyuli** [comment]
我也遇到了同意的问题了，但后台不是beego，而是java，看起来是我们配置的转发有问题，你找到原因了吗？
