### ISSUE TITLE
501 but  text of 504's status

### ISSUE THREAD

**Issue by BPing** [astaxie/beego#2081]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
        
      beego 1.6+

file：beego/error.log
![image](https://cloud.githubusercontent.com/assets/5970097/17356701/806b4c82-598b-11e6-8e06-3ffc19a3e85c.png)

**Comment by amrfaissal** [comment]
@BPing This error is fixed in `develop` branch. @astaxie maybe you want to hotfix this in `master`.

**Comment by astaxie** [comment]
@amrfaissal I will release beego next week. So just let it go now. 🙈

**Comment by BPing** [comment]
@astaxie @amrfaissal   I see ,ths!
