### ISSUE TITLE
如何使静态目录static也支持cors跨域访问呢？

### ISSUE THREAD

**Issue by csrgxtu** [astaxie/beego#2087]
我在static下面的img目录有大量的图片，如何允许跨域访问这些图片。

**Comment by astaxie** [comment]
https://godoc.org/github.com/astaxie/beego/plugins/cors

**Comment by xuange306** [comment]
我这里设置了同样的内容, 我抓包查看发现, 静态文件没有走cors

**Comment by flycash** [comment]
如果我没看错，这个是没有效果的。因为静态资源文件还没到 `BeforeRouter`就已经返回响应了。尝试修改为 `BeforeStatic`，可能有效果。

**Comment by flycash** [comment]
不行你就自己写一个 filter，把 cors 的复制出来，然后用 `filter chain`的方法，在 http method 是`Option` 的时候直接设置好各种 header。
