### ISSUE TITLE
orm更新mysql长文本失败

### ISSUE THREAD

**Issue by cqspirit** [astaxie/beego#2088]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee 1.4.1 
beego 1.6.1
go 1.6.3

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\golang\work
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
func (t *TaskHistory) Update(fields ...string) error {
	if _, err := orm.NewOrm().Update(t, fields...); err != nil {
		return err
	}
	return nil
}
taskHis, _ := models.TaskHistoryGetById(thId)
.......
taskHis.Result = data
uerr := taskHis.Update("result")
```
4. What did you expect to see?
mysql字段格式为longtext
update 某一行，更新2M的长文本到result字段

5. What did you see instead?
短文本可以正常更新，长文本（2M）更新失败，

**Comment by cqspirit** [comment]
文本格式为json

**Comment by astaxie** [comment]
@cqspirit could you post the error detail? is it the drive limit or the ORM limit? or the MySQL limit?

You can turn on the debug to check the SQL

**Comment by cqspirit** [comment]
现在可以了，数据结构修改为mediumblob格式就可以了，string会自动转化为byte数组存入，就不存在编码问题了，获取的时候也会自动处理成string
