### ISSUE TITLE
beego log 行数显示的不对

### ISSUE THREAD

**Issue by jinleileiking** [astaxie/beego#2089]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jinlei1/ksyun/"
GORACE=""
GOROOT="/home/jinlei1/os/go"
GOTOOLDIR="/home/jinlei1/os/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
68 ▸   ▸   beego.BeeLogger.Debug("aaaa")¬
```

4. What did you expect to see?

输出行号68

5. What did you see instead?

输出42.

感觉是内联了，但是加了-l也不行

**Comment by astaxie** [comment]
I don't have this issue. Could you provide a mini runnable program?

**Comment by jinleileiking** [comment]
我有空搞搞。
