### ISSUE TITLE
Beego orm went wrong when insert a row into a table with only one id column

### ISSUE THREAD

**Issue by chendx79** [astaxie/beego#2091]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
MacOS 10.11.6

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
create a table with only one id column(pk, auto)
insert one row in it with orm.Insert

4. What did you expect to see?
insert successfully.

5. What did you see instead?

......
2016/08/09 09:48:29 [router.go:855][C] Handler crashed with error runtime error: integer divide by zero
2016/08/09 09:48:29 [router.go:861][C] /usr/local/go/src/runtime/asm_amd64.s:472
2016/08/09 09:48:29 [router.go:861][C] /usr/local/go/src/runtime/panic.go:426
2016/08/09 09:48:29 [router.go:861][C] /usr/local/go/src/runtime/panic.go:27
2016/08/09 09:48:29 [router.go:861][C] /usr/local/go/src/runtime/sigpanic_unix.go:31
2016/08/09 09:48:29 [router.go:861][C] /Users/.../Go/src/github.com/astaxie/beego/orm/db.go:432
2016/08/09 09:48:29 [router.go:861][C] /Users/.../Go/src/github.com/astaxie/beego/orm/db.go:358
2016/08/09 09:48:29 [router.go:861][C] /Users/.../Go/src/github.com/astaxie/beego/orm/orm.go:149
......

**Comment by astaxie** [comment]
fix in beego1.7

**Comment by stefantalpalaru** [comment]
This bug is still present in 2.3.8: https://github.com/beego/beego/blob/8fd113aa0937a11c45eb41cbf147f33df7e9fb6f/client/orm/db.go#L508

For a table with just an ID, there are no "names" and no "values" in `InsertValueSQL()`.
