### ISSUE TITLE
How to use session mysql engineer?

### ISSUE THREAD

**Issue by sinmaystar** [astaxie/beego#2093]
runtime environment:
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 darwin/amd64
operating system: mac osx
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

I want to use mysql as session engineer, but always failed.
In my controllers.go file, I have do this before:

import (
    _ "github.com/astaxie/beego/session/mysql"
    "github.com/astaxie/beego/session"
)
var globalSessions *session.Manager
func init() {
    globalSessions, _ = session.NewManager("mysql", 
        `{
            "cookieName":"gosessionid", 
            "enableSetCookie,omitempty": true, 
            "gclifetime":3600, 
            "maxLifetime": 3600, 
            "secure": false, 
            "sessionIDHashFunc": "sha1", 
            "sessionIDHashKey": "", 
            "cookieLifeTime": 3600, 
            "providerConfig": "root:password@/my_db"}`)
    go globalSessions.GC()    
}

In Login function I have use Set function to set sessions:

sess, err := globalSessions.SessionStart(c.Ctx.ResponseWriter, c.Ctx.Request)
sess.Set("user_id", user.Id)
sess.Set("user_name", user.Name)
fmt.Println("After Set Session", sess)

the output is: After Set Session &{093aa3357527c689a5df73e9d7bb9b72 {63606433087 92634844 0xa41420} map[user_id:1 user_name:chenjiaming] {{0 0} 0 0 0 0}}

In another function I can use Get to fetch "user_id", "user_name" session information,but it not saved in mysql but in memory.
I have create session table manually, in app.conf I have set: sessionon = true && sessionprovider = mysql and create session table manually

//	CREATE TABLE `session` (
//	`session_key` char(64) NOT NULL,
//	`session_data` blob,
//	`session_expiry` int(11) unsigned NOT NULL,
//	PRIMARY KEY (`session_key`)
//	) ENGINE=MyISAM DEFAULT CHARSET=utf8;

how can I use Mysql as session engineer? is there have any example?

**Comment by caslino** [comment]
Were you able to figure out a solution for this? 
Creating the table manually solves the issue?
