### ISSUE TITLE
orm查询键值首字母大写问题

### ISSUE THREAD

**Issue by enjoydiy** [astaxie/beego#2095]
type User struct {
Id int
Name string
Phone string
}

我习惯用下面方式去查询并以json方式返回给客户端
o := orm.NewOrm()
var maps []orm.Params
o.QueryTable(new(User)).Filter("id", 1).Values(&maps, "id", "name")

这样生成的json键值首字母都是大写的,比如:
{"Id": 1, "Name": "John"}

有没有办法生成键值首字母小写的,如:
{"id": 1, "name": "John"}

用values查询可以比较方便控制需要哪个字段的信息

**Comment by astaxie** [comment]
@enjoydiy you need to define these in you model:

```
type User struct{
  Id         int         `json:"id"`
  Name  string    `json:"name"`
}

```
