### ISSUE TITLE
更新后不能够自动生成model，controller??

### ISSUE THREAD

**Issue by kcl2430** [astaxie/beego#2101]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go版本1.6.2   Bee版本1.5.0

2. What operating system and processor architecture are you using (`go env`)?

windows/386

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
我希望输入这个命令后 bee api  php34api  -driver=mysql -conn=root:@tcp\(127.0.0.1:3306\)/php34
生成model，controller

5. What did you see instead?
![image](https://cloud.githubusercontent.com/assets/14937225/17796983/8952c654-65f7-11e6-9e77-c3a4e48c7e60.png)

**Comment by astaxie** [comment]
please update the bee again, it's bug.

go get -u github.com/beego/bee

**Comment by kcl2430** [comment]
非常感谢
