### ISSUE TITLE
我更新到1.7.0之后路由匹配出现问题

### ISSUE THREAD

**Issue by wednesdaysunny** [astaxie/beego#2110]
beego.Router("/api/:api_route", &controllers.ApiController{}, "*****")
当我更新beego到1.7.0之后，http://localhost:8081/api/et_news 这个url 就不能被正确匹配了，
请问这是因为什么，我看到官网文档上面还没有更新，
请帮忙看一下

Please answer these questions before submitting your issue. Thanks!

├── Beego     : 1.7.0
├── GoVersion : go1.6
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/judy19931213/GoWorkspace
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Tuesday, 23 Aug 2016

2. What operating system and processor architecture are you using (`go env`)?
mac

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by xjjrocker** [comment]
go怎么不更新到1.7呀，beego1.7也是依赖go1.7的呀。

**Comment by astaxie** [comment]
@xjjrocker no, beego1.7 rely on the Go 1.4

@wednesdaysunny I can't reproduce the problem in my local. It works

**Comment by xjjrocker** [comment]
god，一直以为是和go版本同步的！不过这次的升级体验很不好，诸多问题，不如上次升级到1.6.1顺利。

**Comment by astaxie** [comment]
@xjjrocker 这一次什么体验不好？

**Comment by Michael2008S** [comment]
@wednesdaysunny 
找到原因，不知怎么fix：
所有出现下划线的参数如（:country_city） 都路由不了（404）。
我出现的问题和你一样。

**Comment by astaxie** [comment]
dup with #2117
