### ISSUE TITLE
beego1.6如何读取自定义的配置文件？

### ISSUE THREAD

**Issue by qiangmzsx** [astaxie/beego#2113]
文档中有表述：
AppConfigPath
配置文件路径，默认是应用程序对应的目录下的 conf/app.conf，用户可以在程序代码中修改该值配置自己的配置文件
beego.AppConfigPath = "conf/app2.conf"

但是我看了代码：config.go
var (
	// BConfig is the default config for Application
	BConfig *Config
	// AppConfig is the instance of Config, store the config information from file
	AppConfig *beegoAppConfig
	// AppPath is the absolute path to the app
	AppPath string
	// GlobalSessions is the instance for the session manager
	GlobalSessions *session.Manager

	// appConfigPath is the path to the config files
	appConfigPath string
	// appConfigProvider is the provider for the config, default is ini
	appConfigProvider = "ini"
)
appConfigPath为首字母小写了？还如何配置呢？

**Comment by qiangmzsx** [comment]
I see。
cnf, _ := config.NewConfig("ini", "conf/app2.conf")

**Comment by astaxie** [comment]
@qiangmzsx cool. If you solve the problem please close the issue.
