### ISSUE TITLE
如何对资源文件（下载）进行访问保护，不允许直接通过直链下载，需要授权

### ISSUE THREAD

**Issue by cmlanche** [astaxie/beego#2119]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   1.7
2. What operating system and processor architecture are you using (`go env`)?
   Windows
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
4. What did you expect to see?
   可以对资源文件进行访问保护
5. What did you see instead?
   没有看到相关的功能或者文档

**Comment by gitchs** [comment]
+ try [nginx's secure download module](https://www.nginx.com/resources/wiki/modules/secure_download/), easy and painless
+ To do it with beego
```go
package main

import (
        "net/http"

        "github.com/astaxie/beego"
        "github.com/astaxie/beego/context"
)

var dlAuthenticationSwitch bool

func dlAuthentication(ctx *context.Context) {
        dlAuthenticationSwitch = !dlAuthenticationSwitch
        if dlAuthenticationSwitch {
                return
        } else {
                ctx.Abort(http.StatusUnauthorized, "Unauthorized")
        }
}

func main() {
        beego.SetStaticPath("/files/", "./")
        beego.InsertFilter("/files/*", 0, dlAuthentication)
        beego.Run()
}

```
