### ISSUE TITLE
Beego中有权限验证吗

### ISSUE THREAD

**Issue by cmlanche** [astaxie/beego#2120]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.7

2. What operating system and processor architecture are you using (`go env`)?
Windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
Beego中有权限验证吗

5. What did you see instead?
Beego中有权限验证吗

**Comment by fuxiaohei** [comment]
没有，根据自己的情况来做
