### ISSUE TITLE
beego include配置文件出错

### ISSUE THREAD

**Issue by heyuanchao** [astaxie/beego#2121]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?

Beego     : 1.7.0
GoVersion : go1.6.3 
GOOS      : windows
GOARCH    : amd64
NumCPU    : 4
GOPATH    : E:\hyc\go
GOROOT    : C:\Go\
Compiler  : gc
Date      : Friday, 26 Aug 2016
1. What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=E:\hyc\go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\hyc\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
1. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

在conf下新建app2.conf，内容为空，打开conf/app.conf，添加内容 include app2.conf，以下是app.conf的内容：

appname = qing
httpport = 8080
runmode = dev

include app2.conf

运行之后报错：
panic: open app2.conf: The system cannot find the file specified.
1. What did you expect to see?

期望解决上述问题
1. What did you see instead?

暂无

**Comment by qiangmzsx** [comment]
include "system.conf"别漏了引号

**Comment by astaxie** [comment]
@qiangmzsx 这个应该和是否有引号没有关系，因为这个及时加了也是过滤掉的，https://github.com/astaxie/beego/blob/master/config/ini.go#L134

**Comment by xjliao** [comment]
@heyuanchao   
beego 1.7.1  windows  
# include conf/app2.conf

**Comment by astaxie** [comment]
这个应该已经在最新的develop分支修复了
