### ISSUE TITLE
获取的requestbody始终是空的

### ISSUE THREAD

**Issue by StayYouth1993** [astaxie/beego#2122]
fmt.Println(c.Ctx.Input.RequestBody)
这个打印出来的一直是空的，已经开启了copyrequestbody = true
以下版本是bee工具打印出来的：
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.3 windows/amd64

**Comment by astaxie** [comment]
@StayYouth1993 make sure you already read the config correct. please check whether the CopyRequestBody is true?

**Comment by StayYouth1993** [comment]
fmt.Println(c.Ctx.Input.RequestBody) //[]
	fmt.Println(beego.BConfig.CopyRequestBody)//true
CopyRequestBody 读取的是true。这个问题该怎么解决呢？

**Comment by astaxie** [comment]
please provide the minimize example to reproduct the issue

**Comment by StayYouth1993** [comment]
已经解决了，我是跨域测试的，不知道是被拒绝了还是怎么回事。多谢谢大啦！
