### ISSUE TITLE
ORM更新时间字段，程序崩了

### ISSUE THREAD

**Issue by happyEgg** [astaxie/beego#2125]
bee:1.4.1
beego:1.7
更新数据库操作d.Orm().Raw("UPDATE user_login"+table+" SET last_login_time = ? WHERE uid=?", time.Now(), id).Exec()

报错信息：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x7839be]

goroutine 21 [running]:
panic(0xc26260, 0xc82000a180)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/astaxie/beego/orm.getFlatParams(0x0, 0xc8201bdb00, 0x2, 0x2, 0xc82006c9c0, 0x0, 0x0, 0x0)
	/home/wen/workspace/monking_server_tables/src/github.com/astaxie/beego/orm/db_utils.go:148 +0x112e
github.com/astaxie/beego/orm.(*rawSet).Exec(0xc8203d79b0, 0x0, 0x0, 0x0, 0x0)

**Comment by happyEgg** [comment]
struct{}格式：LastLoginTime time.Time `orm:"auto_now;type(datetime)"`

**Comment by happyEgg** [comment]
问题解决了

**Comment by happyEgg** [comment]
@astaxie

**Comment by jackXJ** [comment]
@happyEgg  求问，你这个是怎么解决的

**Comment by happyEgg** [comment]
@jackXJ 谢大改完源码就好了呀，你的是什么问题，贴代码

**Comment by astaxie** [comment]
@jackXJ still in develop branch
