### ISSUE TITLE
beego升级为1.7后出现错误

### ISSUE THREAD

**Issue by qau** [astaxie/beego#2129]
1. bee的版本为1.5.1，go1.7下编译

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\godev
set GORACE=
set GOROOT=D:\go\go1.7.0
set GOTOOLDIR=D:\go\go1.7.0\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\cygwin64\tmp\go-build149626086=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. 一个beegoweb工程，运行 go run main.go或者bee run 时，均出现如下错误：
vendor\github.com\astaxie\beego\admin.go:390: undefined: logs.Info
vendor\github.com\astaxie\beego\admin.go:399: undefined: logs.Critical
vendor\github.com\astaxie\beego\app.go:72: undefined: logs.Info
vendor\github.com\astaxie\beego\app.go:74: undefined: logs.Critical
vendor\github.com\astaxie\beego\app.go:88: undefined: logs.Critical
vendor\github.com\astaxie\beego\app.go:91: undefined: logs.Critical
vendor\github.com\astaxie\beego\app.go:99: undefined: logs.GetLogger
vendor\github.com\astaxie\beego\app.go:116: undefined: logs.Critical
vendor\github.com\astaxie\beego\app.go:131: undefined: logs.Critical
vendor\github.com\astaxie\beego\log.go:36: undefined: logs.GetBeeLogger
vendor\github.com\astaxie\beego\app.go:131: too many errors

4. 不知道什么原因？希望正常工程能够正常启动

**Comment by astaxie** [comment]
it looks your gopath has old version beego, while here you use the vendor. Go is confuse now. please make sure use the correct beego

**Comment by qau** [comment]
我使用了vendor，vendor内的beego也升级到1.7.0了，才出现以上错误，回滚到1.6版本，错误就没有了。

**Comment by astaxie** [comment]
but from you error I don't think it's beego's problem. 

https://godoc.org/github.com/astaxie/beego/logs#Critical
https://godoc.org/github.com/astaxie/beego/logs#Info
https://godoc.org/github.com/astaxie/beego/logs#GetBeeLogger

**Comment by qau** [comment]
我找到原因了，我把beego整个工程拷贝到vendor目录下就可以了。我用govendor命令生成vendor目录下的内容是，不会把真个工程拷贝到vendor目录下，看来只拷贝依赖 不全面。

**Comment by astaxie** [comment]
cool. I recommend `godep`. AFAIK it works for all our project
