### ISSUE TITLE
beego.Error 打印错误行号 有误

### ISSUE THREAD

**Issue by ChongyuE** [astaxie/beego#2135]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 最新版本
golang 1.6.3

2. What operating system and processor architecture are you using (`go env`)?
windows 7

打印行号问题 升级为最新版的beego 打印的结果为github.com/astaxie/beego/log.go的行号 
将beego版本退回 问题消失。

**Comment by astaxie** [comment]
@ChongyuE please check your local beego. it should be fixed in https://github.com/astaxie/beego/commit/227678c2ef1af94ca55fde610fe862e346f5bde7

**Comment by ChongyuE** [comment]
tks

**Comment by astaxie** [comment]
you can use `go get -u github.com/astaxie/beego` to update the beego
