### ISSUE TITLE
orm为什么没有ping数据库这个功能啊

### ISSUE THREAD

**Issue by happyEgg** [astaxie/beego#2136]
beego 1.6

database/sql 包有ping这个接口，而beego的orm也引入了这个包，为什么在orm里找不到ping这个功能呢？

**Comment by happyEgg** [comment]
因为有时候数据库会超时连接断开，mysql默认的是8个小时。该怎么解决呀

**Comment by astaxie** [comment]
https://github.com/go-sql-driver/mysql/issues/82#issuecomment-18295777
