### ISSUE TITLE
Can not run old projects now

### ISSUE THREAD

**Issue by adamwuyu** [astaxie/beego#2137]
We have an api project create by bee api command. It was created last week, but it come up with these problems when I "bee run":

docs/docs.go:17: undefined: swagger.ResourceListing
docs/docs.go:18: undefined: swagger.APIDeclaration
docs/docs.go:30: undefined: beego.GlobalDocAPI
docs/docs.go:37: undefined: beego.GlobalDocAPI
2016/09/02 18:04:24 [ERRO] ============== Build failed ===================

**Comment by adamwuyu** [comment]
BTW: "bee generate docs" can not create docs folder anymore...

**Comment by adamwuyu** [comment]
I already executed :
go get -u github.com/beego/bee
go get -u github.com/astaxie/beego
bee fix

**Comment by astaxie** [comment]
@adamwuyu remove the docs folder. As now the new documents is not rely on these go. It will generate swagger.json in swagger folder

**Comment by adamwuyu** [comment]
@astaxie I tried to delete docs folder, it cause other error. I will try later again.
BTW, I found if I switch the beego version back to March of 2016, there will be no problem at all.

**Comment by astaxie** [comment]
beego 1.7 upgrade swagger to 2.
