### ISSUE TITLE
apply for authorization 

### ISSUE THREAD

**Issue by gislu** [astaxie/beego#2139]
环境
go version: 1.7
beego version: 1.6.1

我最近刚在beego的基础上开发了一个微信公共号/企业号服务器框架，经过测试强度应该可以放到实际应用，我现在想把这个开源框架推广一下（I'm a master student in NY, do it not for profit），因为是在beego的基础上开发的，请问需要获得beego的授权吗？

**Comment by astaxie** [comment]
@gislu thanks for the apply. beego is based on apache licence v2. So it can use in any business application and also you can modify the code by yourself.
