### ISSUE TITLE
目前RegisterModel和RegisterModelWithPrefix只能在init中， 满足不了动态业务需求，比如动态建表

### ISSUE THREAD

**Issue by koalacxr** [astaxie/beego#2140]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.5

2. What operating system and processor architecture are you using (`go env`)?
centos7.2 64 

3. What did you do?
目前RegisterModel和RegisterModelWithPrefix只能在init中使用， 满足不了动态业务需求，比如动态建表等

4. What did you expect to see?
RegisterModel和RegisterModelWithPrefix 可以在需要时都可以调用

5. What did you see instead?

**Comment by koalacxr** [comment]
再增加一个函数RegisterModelWithSuffix，kingshard是后缀的

**Comment by astaxie** [comment]
dynamic RegisterModel need to make sure the Map access add mutex. That would be slow down all the other normal CRUD. We need another function to get the table name. 

1. Add a new function RegisterModelDynamicTable()
2. add a field for the model `dynamic bool`
3. change all the m.table to if m.dynamic {getTableName(m)}

**Comment by astaxie** [comment]
add RegisterModelWithSuffix
