### ISSUE TITLE
CustomAbort返回自定义错误终止运行后,错误无法显示至控制台和admin模块

### ISSUE THREAD

**Issue by gloomyzerg** [astaxie/beego#2141]
beego 1.7.0

在控制器中使用 
`CustomAbort`
终止后,错误能被正确返回
但无法在bee run 中看到debug信息
也无法在admin模块(http://{adminip}/qps)中看到访问日志 

查看源码发现
```
func (c *Controller) CustomAbort(status int, body string) {
    // first panic from ErrorMaps, it is user defined error functions.
    if _, ok := ErrorMaps[body]; ok {
    c.Ctx.Output.Status = status
    panic(body)
    }
    // last panic user string
    c.Ctx.ResponseWriter.WriteHeader(status)
    c.Ctx.ResponseWriter.Write([]byte(body))
    panic(ErrAbort)
}
```
看样子这里的ErrorMaps是为Abort设计的 只能支持Error404这样去定义错误 CustomAbort 第二个参数传入的是具体错误信息,无法通过 ErrorXXX 这样去捕获

最后的 `panic(ErrAbort)`

在此处
```
func (p *ControllerRegister) recoverPanic(context *beecontext.Context) {
	if err := recover(); err != nil {
		if err == ErrAbort {
			return
		}
		...
	}
}
```
被recover
现在我的需求是在不改动框架代码的前提下 去收集CustomAbort中自定义的错误和状态码 有什么好的建议吗

**Comment by astaxie** [comment]
I suggest you use the controller to define the error. http://beego.me/docs/mvc/controller/errors.md#controller%E5%AE%9A%E4%B9%89error


```
func (c *ErrorController) ErrorDb() {
    c.Data["content"] = "database is now down"
    c.TplName = "dberror.tpl"
}
```
like the above example, you can call `CustomAbort(404, "Db")`

**Comment by gloomyzerg** [comment]
Thanks,I got it.
But i do like this, I have to define errors respectively. 
Is there a way to just define the errors once? That's what I wanna do.

**Comment by astaxie** [comment]
please provide your really case, I don't think that's reasonable.

**Comment by gloomyzerg** [comment]
I use CustomAbort() as a restful response.

like the below example
```
	valid := validation.Validation{}
	valid.Required(creator, "Creator")
	valid.Numeric(creator, "Creator")
	valid.Required(username, "Username")
	valid.Required(password, "Password")
	valid.Required(email, "Email")
	valid.Email(email, "Email")
	valid.Required(mobile, "Mobile")
	valid.Mobile(mobile, "Mobile")
	valid.Required(remark, "Remark")
	if valid.HasErrors() {
		for _, err := range valid.Errors {
			this.CustomAbort(400, err.Key+" "+err.Message)
		}
	}
```

I wanna record these response of the request.
well i know this is not the best way.
That's my situation.I can't rewrite these code,because I have finished most of the code in my project.

**Comment by astaxie** [comment]
> I can't rewrite these code,because I have finished most of the code in my project

if it's in the wrong way, you need to make it right. 😃 

```
if valid.HasErrors() {
        for _, err := range valid.Errors {
             c.Ctx.Output.Status = 400 
             this.Data["json"] = struct{error string}{err.Key+" "+err.Message}
            this.ServeJSON()
        }
    }
```

**Comment by gloomyzerg** [comment]
ok :) 
thx very much!
