### ISSUE TITLE
Support for Mongo?

### ISSUE THREAD

**Issue by dltmd6262** [astaxie/beego#2144]
This is a great project! But allowing only SQL dbs is a pretty big restriction IMHO.
Are you planning on adding NoSQL dbs like Mongo, or at least provide a way to add other dbs to beego?
Thanks!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

Go: 1.7, Beego: 1.7.0

2. What operating system and processor architecture are you using (`go env`)?

Mac OS X, arch: amd64

3. What did you do?

Trying to use mongo

**Comment by astaxie** [comment]
beego are not limit mongo,you can use mgo and integrated into beego. Please look throught this project. Mongo Web Admin powered by beego

https://github.com/29392964/mgweb
