### ISSUE TITLE
bee api project issue.

### ISSUE THREAD

**Issue by leochan007** [astaxie/beego#2145]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.7   bee 1.5.1 beego 1.7.0

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\dev_env\Golang\GoPath
set GORACE=
set GOROOT=D:\dev_env\Golang\Go
set GOTOOLDIR=D:\dev_env\Golang\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build418259302=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
bee api [aproject]      ------------the project is host in github.
 
the route.go seems strange.

import (
	"github.com\leochan007\cert-api/controllers"            -----------this maybe cause the error.

	"github.com/astaxie/beego"
)

coz of win10?   the file separator is \ not /.

bee generate docs get error:   2016/09/07 13:30:39 [ERRO] parse router.go error

4. What did you expect to see?

5. What did you see instead?

**Comment by leochan007** [comment]
"github.com\leochan007\cert-api/controllers"

	"github.com/astaxie/beego"

**Comment by astaxie** [comment]
dups https://github.com/beego/bee/issues/270

**Comment by leochan007** [comment]
ok 要手工改路径 在手工build 才能generate closed！
