### ISSUE TITLE
树莓派成功编译beego，外网无法访问

### ISSUE THREAD

**Issue by golwei** [astaxie/beego#2148]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.1

├── Beego     : 1.7.0
├── GoVersion : go1.6.2
├── GOOS      : linux
├── GOARCH    : arm
├── NumCPU    : 4
├── GOPATH    : /root/work
├── GOROOT    : /usr/lib/go-1.6
├── Compiler  : gc
└── Date      : Wednesday, 7 Sep 2016

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_arm"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
$ bee new app1
$ bee run app1

If possible, provide a recipe for reproducing the error.
server:-->2016/09/07 15:04:42 [I] [asm_arm.s:990] http server Running on http://:8080
client: http://xxxxxx.wicp.net:8080/
can't display anything.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
I have no idea on this. it's already started, but you can't access from outside. maybe it's related to network.
