### ISSUE TITLE
ORM模块使用原生方式执行SQL时存在问题

### ISSUE THREAD

**Issue by kangqing2008** [astaxie/beego#2149]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 1.7

2. What operating system and processor architecture are you using (`go env`)?
go version go1.7rc2 windows/386

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

调用orm.Raw().Exec()方法，参数中有time.Time类型的参数时
db_utils.go文件中的第148行，执行到这里如果fi为nil会报异常
`
if fi != nil && fi.fieldType == TypeDateField {
   					    arg = v.In(tz).Format(formatDate)
				} else if fi.fieldType == TypeDateTimeField {
					      arg = v.In(tz).Format(formatDateTime)
				} else {
      					arg = v.In(tz).Format(formatTime)
				}
`
4. What did you expect to see?
增加fi!=nil的判断就可以了
在fi为nil的情况下默认的格式化方式是只保留时分秒，这个是刻意这样的吗？日常使用的时候，基本上格式化为年月日时分秒的情况比较多。
希望能够讲默认的时间格式修改为：formatDateTime
5. What did you see instead?
不修改

**Comment by astaxie** [comment]
it's fixed in develop https://github.com/astaxie/beego/blob/develop/orm/db_utils.go#L148
