### ISSUE TITLE
support `SELECT FOR UPDATE`?

### ISSUE THREAD

**Issue by simpleelegant** [astaxie/beego#2157]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

```
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

(not need)

4. What did you expect to see?

It seems not support `SELECT FOR UPDATE` for MySQL (and others). Did have any plan for it?

May I create a PR what add `Ormer.ReadForUpdate()` and `QueryBuilder.ForUpdate()` ?

5. What did you see instead?

nothing.

**Comment by astaxie** [comment]
@simpleelegant please create a PR
