### ISSUE TITLE
php://input相当于beego的哪一个操作

### ISSUE THREAD

**Issue by qiangmzsx** [astaxie/beego#2159]
因为业务需要使用beego重写一遍之前的PHP代码，其中有一段是需要使用php://input获取json数据，这是未经过POST处理的。但是我尝试使用beego处理使用遇到input.Context.Request.Body为nil。
但是Ctx.Request.ContentLength不为零。

**Comment by astaxie** [comment]
yea, you need to set `beego.BConfig.CopyRequestBody = true`
