### ISSUE TITLE
beego命令只能在GOPATH中创建和运行项目吗？实际中很不方便。

### ISSUE THREAD

**Issue by roylone** [astaxie/beego#2160]
如题所述。
即使设置多个GOPATH，bee new 项目后也只会将项目创建在第一个路径下。
但是实际项目中，GOPATH设置的路径一般用来放第三方包，而希望bee命令的相关项目能在自己的工作目录中创建。
这样整个项目层次结构清晰。也方便管理。
不知道这方面有什么好建议么？

**Comment by roylone** [comment]
目前卡在这一步之上了，各位是怎么解决这个问题的呢？
不能好好的解决工程环境问题，这边项目都不能好好开始了。求大神帮忙提供建议。

**Comment by astaxie** [comment]
@roylone 你应该不是进入到你设置的第二个GOPATH/src下面执行bee new项目，如果你不在GOAPTH目录创建的话就会创建新的项目到第一个GOPATH目录，应该当你在执行bee的时候有很详细的提示

**Comment by roylone** [comment]
@astaxie 非常感谢回复，我是在windows平台上执行的命令。刚才按照你所述测试后可以执行了。
但仍有一个问题，我是使用goclipse进行开发的，在自己的工作目录下，是以项目来组织的，各个项目下另有单独的SRC等目录，这样的话要使用bee，gopath设置会很为难。
作为一个建议，如果bee创建以及执行可以指定搜索目录就方便灵活很多了

**Comment by astaxie** [comment]
我不建议直接在goclipse来进行bee的调用，bee new本身就是执行一次的，为什么要在编辑器里面做呢？

**Comment by roylone** [comment]
这样说也有道理，我只是是为了开发方便。
