### ISSUE TITLE
升級新版本后 最基本的編譯都不通過

### ISSUE THREAD

**Issue by GreenAppleOne** [astaxie/beego#2164]
1.7 version
bee run -gendoc=true

2016/09/17 20:50:13 ============== generate docs ===================
# resAPI/docs
docs/docs.go:17: undefined: swagger.ResourceListing
docs/docs.go:18: undefined: swagger.APIDeclaration
docs/docs.go:30: undefined: beego.GlobalDocAPI
docs/docs.go:37: undefined: beego.GlobalDocAPI
2016/09/17 20:50:15 [ERRO] ============== Build failed ===================

**Comment by astaxie** [comment]
please remove the docs folder. As the new swagger will not rely on these go files
