### ISSUE TITLE
ORM 支持自定义自增ID的值 问题

### ISSUE THREAD

**Issue by mylady** [astaxie/beego#2165]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go:1.6.2

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

  服务端简单的rest路由post请求创建postgresql数据库记录,id为serial类型

4. What did you expect to see?
  前端使用extjs时,每次新建的model提交后必然有id字段会传递上来,原来在
  beego1.6的时候如果Id字段声明为pk;auto,不会在sql语句中插入id

5. What did you see instead?

  升级到1.7后,同样的代码会直接把id插入到表中,导致主键重复

  查过1.7的改进:
  **ORM PK支持负数 #1810
  ORM 支持自定义自增ID的值 #1826**
  原因应该是第四条,如果不需要手动设置自增的id,如何设置id的值?或者是否可以通过配置文件关闭这个       功能?

**Comment by mylady** [comment]
@astaxie 谢大,求解啊~

**Comment by astaxie** [comment]
我觉得这个是你这边的问题吧，为什么你的id每次是新建，但是前台传id进来吗？

**Comment by mylady** [comment]
你的意思是前台在创建的时候不要指定id的值,后台在解析json的时候id=0就可以使用数据库里的自增了是吗?
我去试试一下
extjs的model在post新增的时候都会带着id过来,所以是这样-.-

**Comment by mylady** [comment]
可以了,只要是0可以使用自增了:)
