### ISSUE TITLE
Log Module error : "unknown adaptername "smtp" (forgotten Register?)"

### ISSUE THREAD

**Issue by He-aD** [astaxie/beego#2172]
After updating to the latest version of beego : I had the following error on this code : 

code : 
        user := beego.AppConfig.String("email_sender_username")
	pass := beego.AppConfig.String("email_sender_pass")
	host := beego.AppConfig.String("smtp_server")
	port := beego.AppConfig.String("smtp_port")
	to := beego.AppConfig.String("email_error_critical")
	lvl := strconv.Itoa(beego.LevelCritical)
	if err := beego.SetLogger("smtp", `{"username":"` + user + `","password":"` + pass + `","host":"` + host + `:` + port + `","sendTos":["` + to + `"],"subject":"airmob.link critical error","level":` + lvl + `}`); err != nil {
		panic(seterError{err, LOGGER_SETER})
	}

error : "unknown adaptername "smtp" (forgotten Register?)"

it was working really fine with previous version. 

Is it deprecated ? (I didn't see the note on website)

**Comment by astaxie** [comment]
@He-aD I suggest you use `logs.AdapterMail` to replace `smtp`. As it's a typo for the smtp. I think it maybe need to rename to `stmp`.

**Comment by He-aD** [comment]
It works. 

I found the example here -> http://beego.me/docs/module/logs.md. May be remove it as it's not working anymore.

Thanks for fast answering

**Comment by astaxie** [comment]
@He-aD I just updated the documents. Thanks to report the issue.
