### ISSUE TITLE
beego在生产环境下，是不是会对页面进行缓存处理？为什么我直接改页面不生效呢

### ISSUE THREAD

**Issue by bjut-hz** [astaxie/beego#2174]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hz/GO"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
不会

**Comment by astaxie** [comment]
你如果在prod模式下的话，修改页面不会产生效果，因为模板解析以及全部在启动的时候放在map里面了

**Comment by bjut-hz** [comment]
那我更改了页面，只能重启才能生效么？？？

**Comment by astaxie** [comment]
是的

**Comment by bjut-hz** [comment]
谢谢谢老师~~~~~
