### ISSUE TITLE
Does QueryRows do type casting when map query results to container

### ISSUE THREAD

**Issue by ScorpioCPH** [astaxie/beego#2177]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
$ bee version
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.3 darwin/amd64
```
2. What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cenph/code/workspace"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.3/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
3. What did you do?

 As code show below, id in table is `int64`, and i use a `string array` as container to get query result, is this code properly?
  Does QueryRows do type casting when map query results to container?
```
o := GetOrmer()
sql := "select id from table where name = foo"

var ids []string
count, err := o.Raw(sql).QueryRows(&ids)
```

4. What did you expect to see?

  String array `ids` get properly query result.

5. What did you see instead?

 After run this code, the answer is `YES` (QueryRows do type casting), i just want to make sure about it, thanks!

**Comment by astaxie** [comment]
I wiil give you a big **YES** 😆
