### ISSUE TITLE
xsrf token always same when i request many times.

### ISSUE THREAD

**Issue by ZhenyangZhao** [astaxie/beego#2178]
1. What version of Go and beego are you using (`bee version`)?
go version: 1.6.3
beego version: 1.7.1

2. What operating system and processor architecture are you using (`go env`)?
windows
amd64

3. What did you do?
i have set xsrf when bee go startup. and set xsrfexpire = 1
but everytime i get an url like "/login"
the xsrf token response the same value.
i think it should be different when i request everytime.

4. What did you expect to see?
different xsrf token

![image](https://cloud.githubusercontent.com/assets/7477708/18778752/712b9944-81a8-11e6-9e79-24a151ee7317.png)

**Comment by ZhenyangZhao** [comment]
i found mistake.
beego doc write xsrfexpire=3600 //过期时间，默认60秒
but xsrfexpire=3600 actual is 1hour
please update the doc.
thks

**Comment by astaxie** [comment]
thx, fix the docs
