### ISSUE TITLE
plugin cors can't handle static folder

### ISSUE THREAD

**Issue by yaotian** [astaxie/beego#2179]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.0
├── GoVersion : go1.7
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yaotian/projects/go_projects"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_5/f9yt9lkj1zn7kwnltfktffv40000gp/T/go-build648027297=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I want to add "Access-Control-Allow-Origin' header. So in the main file i add following:
`
beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowAllOrigins: true,
}))

beego.Run()
`

4. What did you expect to see?

I expect to see all this site can be with "Access-Control-Allow-Origin" header including  css and js files 

5. What did you see instead?

No “Access-Control-Allow-Origin' header for css,js static files, but do have the header for router request.

**Comment by astaxie** [comment]
if you want it work for static. you need to add the plugin into `beego.BeforeStatic`
