### ISSUE TITLE
beego 有没有cli模式 或者后续考虑添加

### ISSUE THREAD

**Issue by githubzhaoqian** [astaxie/beego#2181]
希望能有cli模式,比如导数据批量修改数据之类的功能很需要，在一个语言或者一个框架下实现会放方便很多中小公司

**Comment by astaxie** [comment]
这个你不是可以直接在main.go里面自己去实现啊，框架里面添加这个cli支持不合适啊

**Comment by githubzhaoqian** [comment]
我这是惯性思维，phper, pythoner,勿怪。

**Comment by astaxie** [comment]
cli的库你可以直接用这个呢，然后run的时候调用beego.Run就可以很容易实现了https://github.com/spf13/cobra

**Comment by githubzhaoqian** [comment]
s k y
