### ISSUE TITLE
bee run &之后运行起来了，但是关闭shell之后就会断掉

### ISSUE THREAD

**Issue by GanWenPeng** [astaxie/beego#2185]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.0
├── GoVersion : go1.6.3
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 1
├── GOPATH    : /home/golang
├── GOROOT    : /usr/lib/golang
├── Compiler  : gc
└── Date      : Wednesday, 28 Sep 2016

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/golang"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
bee run 一切正常，热编译也OK，但是正是部署的时候bee run &虽然可以运行起来，但是只要已退出shell立马就断掉，线程死掉，这是为什么？该如何解决？求指点

4. What did you expect to see?
希望获得一个正确部署的方法，不会断掉shell就挂掉

5. What did you see instead?

**Comment by astaxie** [comment]
bee run不是为了部署开发的，当然你如果想部署的最好采用systemd之类的来保证服务一直运行，当然你的问题的我可以给你一个解决方案是`nohup bee run &`
