### ISSUE TITLE
自动文档title不显示

### ISSUE THREAD

**Issue by Fengxq2014** [astaxie/beego#2186]
文档注释：
```
// @Title 交易
// @Description 转账交易
// @Param	body		body 	controllers.Transreq	true		"The object content"
// @Success 200 {string} 
// @Failure 403 body is empty
// @router / [post]
```
最终显示：
![image](https://cloud.githubusercontent.com/assets/8519834/18899945/5b86a848-856f-11e6-9f19-7ddfc7cccc01.png)

**Comment by astaxie** [comment]
你生成的swagger.json能上传上来吗？

**Comment by Fengxq2014** [comment]
[swagger.txt](https://github.com/astaxie/beego/files/497159/swagger.txt)
@astaxie

**Comment by astaxie** [comment]
`bee version`输出是什么？

**Comment by Fengxq2014** [comment]
![image](https://cloud.githubusercontent.com/assets/8519834/18901472/d51603a8-857d-11e6-8cab-5b39ccce99af.png)

**Comment by astaxie** [comment]
"operationId": "TransController.交易",

**Comment by astaxie** [comment]
你说的title显示在哪里？请参考这个http://petstore.swagger.io/#/pet

**Comment by Fengxq2014** [comment]
应该是红框圈出来的部分吧
![image](https://cloud.githubusercontent.com/assets/8519834/18901547/87deec02-857e-11e6-88d7-ba8c7626d0ec.png)

**Comment by astaxie** [comment]
这个是description啊，你需要设置

```
@Summary  交易
```

**Comment by Fengxq2014** [comment]
啊，这样可以的，那请问下，这里的Title是什么作用

**Comment by astaxie** [comment]
这个title是用来设置唯一标示的

**Comment by Fengxq2014** [comment]
一个controller里面不能有重复吗？

**Comment by astaxie** [comment]
是的

**Comment by Fengxq2014** [comment]
好的，明白了，thanks
