### ISSUE TITLE
beego新建的工程把端口改为80，无法执行路由，路由器上打开首页无效果

### ISSUE THREAD

**Issue by cmlanche** [astaxie/beego#2188]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
please answer all questions
