### ISSUE TITLE
sessionProvider 为文件时，多读取几次，session就丢失

### ISSUE THREAD

**Issue by tegger** [astaxie/beego#2191]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   1.7
2. What operating system and processor architecture are you using (`go env`)?

win7
1. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
   sessionProvider 为文件时，多读取几次，session就丢失，算是一个大bug 如果是memory是没有问题的
   ，算是一个大bug 如果sessionProvider memory是没有问题的
2. What did you expect to see?
3. What did you see instead?

**Comment by astaxie** [comment]
可以重现吗？我在mac下面没有重现过

**Comment by sicojuy** [comment]
@astaxie 跟https://github.com/astaxie/beego/issues/2666 重复
