### ISSUE TITLE
使用beego orm如何实现分表进而实现分库

### ISSUE THREAD

**Issue by youhq97** [astaxie/beego#2192]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.7
2. What operating system and processor architecture are you using (`go env`)?
windows7 64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
使用beego orm

4. What did you expect to see?
能够提供分表进而分库的解决方案

5. What did you see instead?
no

使用beego orm 是否有分库分表的解决方案

**Comment by astaxie** [comment]
不在beego的ORM开发计划中

**Comment by axetroy** [comment]
@astaxie 

按理来说，ORM不应该做这个事情.

但是分表需要自助创建表，而 ORM本身不对外提供创建表的API。

除了 ``orm.RegisterModel(new(User))`` 这个不正统的接口外。

所以希望可以支持创建表单的接口, 和 Union 和 Join 的函数调用
