### ISSUE TITLE
beego orm的反射获取匿名字段的功能

### ISSUE THREAD

**Issue by haroldTlan** [astaxie/beego#2194]
今天下午看文档的时候，发现有“表关系设置”这种功能，
但是尝试了很多次它都只继承了主键

```
type Disks struct { 
        Uuid      string `orm:"pk"`
        Health    string
  }

type Disk struct {
        Uid       int    `orm:"pk"`
        Disks     *Disks `orm:"rel(fk)"`
}
```
文档中的RelOneToOne、RelManyToMany的意思很难懂（新手）
所以如何能够实现继承

when I used
```
var d []Disk
_, err = o.QueryTable(“disks”).All(&d)
```

The Debug said ：[INSERT INTO `disk` (`uid`, `disks_id`)]
"Disk" just get the PRI KEY from "Disks"  or nothing(use `orm:"-"`)

Please help me

ps：类似问题
https://segmentfault.com/q/1010000005118241

**Comment by astaxie** [comment]
你先把你的关系理清楚嘛，orm里面定义了"-"，同时有定义orm:rel(fk)，完全没搞懂你要干什么

**Comment by haroldTlan** [comment]
抱歉抱歉，修改了一下，文档里面的表关系设置实在看不懂，
我的本意是想让Disk拥有（Uid，Uuid，Health）这三种，

我看到以前beedb有这种用法


Nesting Models (inline)

```
type SQLModel struct {
    Id       int       `beedb:"PK" sql:"id"`
    Created  time.Time `sql:"created"`
    Modified time.Time `sql:"modified"`
}
type User struct {
    SQLModel `sql:",inline"`
    Name     string `sql:"name" tname:"fn_group"`
    Auth     int    `sql:"auth"`
}
// the SQL table has the columns: id, name, auth, created, modified
// They are marshalled and unmarshalled automatically because of the inline keyword
```

想请问一下在beego要怎么实现

**Comment by haroldTlan** [comment]
已解决，
https://segmentfault.com/q/1010000007042070/a-1020000007049756

**Comment by astaxie** [comment]
👍
