### ISSUE TITLE
Beego and https

### ISSUE THREAD

**Issue by danielc007** [astaxie/beego#2195]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.7 windows/amd64, Beego 1.7.0 (or whatever the latest on 28Sep2016, have done a go get -u , Bee 1.5.2

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\golangwk
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Tried to set up https, as described here: https://github.com/astaxie/beego/issues/401 and got this in the logs:
2016/09/28 14:05:34 [I] [asm_amd64.s:2086] https server Running on https://127.0.0.1:10443
2016/09/28 14:05:37 [server.go:2315] [HTTP] http: TLS handshake error from 127.0.0.1:65365: tls: first record does not look like a TLS handshake

4. What did you expect to see?
Expected to be able to process a very simple Get request that do work on http.

5. What did you see instead?
2016/09/28 14:05:34 [I] [asm_amd64.s:2086] https server Running on https://127.0.0.1:10443
2016/09/28 14:05:37 [server.go:2315] [HTTP] http: TLS handshake error from 127.0.0.1:65365: tls: first record does not look like a TLS handshake

**Comment by danielc007** [comment]
The error was related to the client used. I was using Chrome and Postman. It turns out it works in MS Edge.

**Comment by xuange306** [comment]
请问解决了吗?我用bee run 跑, 同时开http和https一直报https端口被占用, 我可以肯定端口没有被占用
