### ISSUE TITLE
查询的时候怎么获取结果字段名

### ISSUE THREAD

**Issue by mimzychou** [astaxie/beego#2196]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.6 and 1.7
2. What operating system and processor architecture are you using (`go env`)?
win10 i5

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
a sample web application

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
先学习一下怎么提问
