### ISSUE TITLE
{{template "xxx"}}，xxx怎样引用其他目录下的模板？

### ISSUE THREAD

**Issue by GanWenPeng** [astaxie/beego#2208]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.0
├── GoVersion : go1.6.3
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 1
├── GOPATH    : /home/golang
├── GOROOT    : /usr/lib/golang
├── Compiler  : gc
└── Date      : Thursday, 6 Oct 2016

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/golang"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
我需要引用其他目录下的template，但是直接引用会报错，no such template "xxx"，我应该怎么做？有办法实现吗

**Comment by astaxie** [comment]
http://beego.me/docs/mvc/view/view.md
