### ISSUE TITLE
postgresql  DB timestamp变量查询结果出错

### ISSUE THREAD

**Issue by dkkxhn** [astaxie/beego#2210]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go1.6 
beego :1.6.1

2. What operating system and processor architecture are you using (`go env`)?
windows/amd64

3. What did you do?

postgresql  DB timestamp变量查询出来结果比实际时间快8小时。

o := orm.NewOrm()
o.Using("postgres")
var tm time.Time
err := o.Raw("SELECT gathertime FROM recent_geo WHERE deviceid = ?", deviceid).QueryRow(&tm)

4. What did you expect to see?
数据库直接赋值运行该语句得到：2016-08-26 11:22:56

5. What did you see instead?
程序运行得到：2016-08-26 19:22:56 +0800 CST

**Comment by astaxie** [comment]
what's `gathertime` type? `TIMESTAMP WITHOUT TIME ZONE` or `TIMESTAMP WITH TIME ZONE`

http://www.hydrogen18.com/blog/time-zones-and-databases-dont-mix.html

**Comment by dkkxhn** [comment]
之前gathertime的类型是TIMESTAMP WITHOUT TIME ZONE，但插入时没用CURRENT_TIMESTAMP at time zone 'utc'，如果现在改为用这个插入的话，之前的数据是不是要全部清空

**Comment by astaxie** [comment]
```
UPDATE recent_geo
SET 
gathertime = subquery. gathertime
FROM ( select gathertime AT TIME ZONE 'Asia/ShangHai' AT TIME ZONE 'UTC' from recent_geo) AS subquery
```

**Comment by dkkxhn** [comment]
为什么mysql不存在这个问题，想要数据库可视化工具显示的时间跟系统时间对应上要做怎么样的处理。
func detectTZ(al *alias) {
	// orm timezone system match database
	// default use Local
	al.TZ = time.Local

	if al.DriverName == "sphinx" {
		return
	}

	switch al.Driver {
	case DRMySQL:
		row := al.DB.QueryRow("SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP)")
		var tz string
		row.Scan(&tz)
		if len(tz) >= 8 {
			if tz[0] != '-' {
				tz = "+" + tz
			}
			t, err := time.Parse("-07:00:00", tz)
			if err == nil {
				al.TZ = t.Location()
			} else {
				DebugLog.Printf("Detect DB timezone: %s %s\n", tz, err.Error())
			}
		}

		// get default engine from current database
		row = al.DB.QueryRow("SELECT ENGINE, TRANSACTIONS FROM information_schema.engines WHERE SUPPORT = 'DEFAULT'")
		var engine string
		var tx bool
		row.Scan(&engine, &tx)

		if engine != "" {
			al.Engine = engine
		} else {
			al.Engine = "INNODB"
		}

	case DRSqlite, DROracle:
		al.TZ = time.UTC

	case DRPostgres:
		row := al.DB.QueryRow("SELECT current_setting('TIMEZONE')")
		var tz string
		row.Scan(&tz)
		loc, err := time.LoadLocation(tz)
		if err == nil {
			al.TZ = loc
		} else {
			DebugLog.Printf("Detect DB timezone: %s %s\n", tz, err.Error())
		}
	}
}
