### ISSUE TITLE
delete方法取不到对应的参数 

### ISSUE THREAD

**Issue by anpufeng** [astaxie/beego#2212]
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.2

├── Beego     : 1.7.1
├── GoVersion : go1.6.3
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/ethan/go
├── GOROOT    : /usr/local/Cellar/go/1.6.3/libexec
├── Compiler  : gc
└── Date      : Sunday, 9 Oct 2016

              $.ajax({
					type: "post",
					url: "api/sections",
					data: { 'name': 'some name' },
					dataType: "json",
					success: function(response) {
						//do something you want
					}
					});
我在前端用ajax发起一个delete方法，后端通过name := this.GetString("name")取不到参数，同样的请求我只将delete改为post则可以取到参数，不明白为什么？ 如何解决delete取不到参数的问题?

**Comment by astaxie** [comment]
http://stackoverflow.com/questions/2539394/rest-http-delete-and-parameters
