### ISSUE TITLE
beego 日志里时间由9月直接跳到11月

### ISSUE THREAD

**Issue by xlon3** [astaxie/beego#2222]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
bee   :1.4.1
beego :1.6.1
Go    :go version go1.5.1 linux/amd64
```
2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/home/***/mygo"
GORACE=""
GOROOT="/home/work/env/golang/default"
GOTOOLDIR="/home/work/env/golang/default/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

测试环境bee run运行的后台服务，9月前一直运行至今，使用beego自带日志模块进行日志记录，orm开启了debug模式

日志时间由 2016/09/30 23:59:59 直接过渡到 2016/11/01 00:00:00 
但orm日志中时间正常，日志每日滚动生成的文件名也正常，所用的阿里云服务器系统时间正常

以下为测试环境应用日志相关配置：
```
### logger file
[logger_file]
# if not set, default use "log/{appname}.log" instead
#filename = ""

# if not set, default value 1,000,000
#maxlines = 1000000

# if not set, default value 256 MB
#maxsize = 256 

# if not set, default true
#daily = true

# if not set, default 7
#maxdays = 7 

# if not set, default true
#rotate = true

# if not set, default Debug
# Emergency
# Alert
# Critical
# Error
# Warning
# Notice
# Informational
# Debug
#level = "Debug"
log_func_call_enable=false
```

**Comment by astaxie** [comment]
@xlon3 I am very sorry for this issue. It's a bug. We already fix in lastest version. please update your local beego.
