### ISSUE TITLE
大神问个知识

### ISSUE THREAD

**Issue by githubzhaoqian** [astaxie/beego#2224]
makefile中的
GOFLAGS ?= $(GOFLAGS:)
这句的 GOFLAGS: 是什么意思？
build:
	go build $(GOFLAGS) ./...
./...  这个是表示当前目录下的全部文件么？
或者这些知识能在哪里查到哈？
希望大神指点！

**Comment by astaxie** [comment]
如果有问题请到gocn.io提问，这里是beego的issue汇报
