### ISSUE TITLE
File descriptors leak Cloudflare.

### ISSUE THREAD

**Issue by He-aD** [astaxie/beego#2226]
Hi,

I run a website on a ovh Ubuntu environment using Beego for 3 months now. I have a problem with file descriptors leak. It seems it is with Cloudflare's connexion only. 

As it is a known issue with golang server library, they made an article [here ](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/)to explain how to avoid the leak. 

I don't know if the problem is coming from my configuration or the framework.

Any help appreciated on this subject, it's quite annoying to restart the application every month.

Thanks.

**Comment by astaxie** [comment]
@He-aD Could you check the file descriptors on the server, like `/proc/3170/fd`. where is the fd leaked? socket or other file open?

**Comment by He-aD** [comment]
@astaxie the fd leaked is from socket.
![descriptorfileleak](https://cloud.githubusercontent.com/assets/17404065/19433632/c981c192-9461-11e6-9f20-6e2fe2c25b5c.png)

**Comment by astaxie** [comment]
how many file descriptors did you set?  `ulimit -a`

And also to collect how many TIME_WAIT on your server `netstat -nat`

**Comment by He-aD** [comment]
ulimit : 1024

no TIME_WAIT, the connexion stays with statut ESTABLISHED (keep-alive problem ?). In the cloudflare article they talk about Time out.

**Comment by astaxie** [comment]
@He-aD I think you need to set the limit to 10240. 1024 is default value and it's always too small.

>several connexions with the same IP

Did you use the proxy?

**Comment by He-aD** [comment]
Yes I'm using it. 

I'll update the limit and observe if the number opened stop growing.

**Comment by astaxie** [comment]
@He-aD As you use the proxy, that's why has the same IP. 1024 is always too small for production. I always set this to 65535

```
open files                      (-n) 65535
```

**Comment by He-aD** [comment]
@astaxie thanks for your help. May be we can close the issue. 

If I reach the limit again I'll re-open it.

Btw very good job for the Framework, it's really simple and quick to develop with.

Thanks for your help, I'll keep you in touch.
