### ISSUE TITLE
Beego Endpoint Testing - Empty Request URI

### ISSUE THREAD

**Issue by guptachirag** [astaxie/beego#2227]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
centos 6

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

**Code**
func (o *MyController) Get() {
    uri := o.Ctx.Input.URI()
    beego.Trace(uri)
}
Now if i make a request to the corresponding endpoint for example "http://localhost:8081/path?key=value", i get the correct value for uri

But if i test it with following code

func TestGet(t *testing.T) {
    Convey("valid request case", t, func() {
        w := httptest.NewRecorder()
        uri := "/path?key=value"
        r, _ := http.NewRequest("GET", uri, nil)
        beego.BeeApp.Handlers.ServeHTTP(w, r)
        So(w.Code, ShouldEqual, 200)
    })
}
uri in controller is empty string

However, o.Ctx.Request.URL.Path has correct value i.e. '/path'

4. What did you expect to see?
uri = "/path?key=value"

5. What did you see instead?
uri = ""

**Comment by chirag-applift** [comment]
This is not a beego issue, we can close this.

According to docs https://golang.org/pkg/net/http/#NewRequest

NewRequest returns a Request suitable for use with Client.Do or Transport.RoundTrip. To create a request for use with testing a Server Handler use either ReadRequest or manually update the Request fields.
For golang 1.7, following method should be used for creating request for testing https://golang.org/pkg/net/http/httptest/#NewRequest

NewRequest returns a new incoming server Request, suitable for passing to an http.Handler for testing.

**Comment by guptachirag** [comment]
This is not a beego issue. From golang docs

According to docs https://golang.org/pkg/net/http/#NewRequest

NewRequest returns a Request suitable for use with Client.Do or Transport.RoundTrip. To create a request for use with testing a Server Handler use either ReadRequest or manually update the Request fields.
For golang 1.7, following method should be used for creating request for testing https://golang.org/pkg/net/http/httptest/#NewRequest

NewRequest returns a new incoming server Request, suitable for passing to an http.Handler for testing.

This can be closed.

**Comment by astaxie** [comment]
@guptachirag Thanks for the update
