### ISSUE TITLE
output date format is wrong

### ISSUE THREAD

**Issue by newyangyang** [astaxie/beego#2232]
1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1      beego :1.6.1     Go    :go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

3. What did you do?
build a executable with `bee run`, kill the process, then start  with `nohup ./myprogram &`

4. What did you expect to see?
Problem ONE:
The proper request would be `http://localhost:8098/geta?name=abc&callback=123` this returns a jsonp. But panic info is cause by a request like `http://localhost:8098/geta`.  This is weird, because I do proper handling of parameter missing in my controller code, but apparently, my code is not reached, beego throws panic. 
Problem TWO:
 if it have to panic, right date format should be shown, today is October 19, 2016, thus `2016/10/19` is expected.

5. What did you see instead?
log is from Windows, but  same on Linux server.

> 2016/11/19 09:18:01 [router.go:854][C] the request url is  /geta
> 2016/11/19 09:18:01 [router.go:855][C] Handler crashed with error can't find templatefile in the path:maincontroller/geta.tpl
> 2016/11/19 09:18:01 [router.go:861][C] D:/software/Go/src/runtime/asm_amd64.s:472
> 2016/11/19 09:18:01 [router.go:861][C] D:/software/Go/src/runtime/panic.go:443
> 2016/11/19 09:18:01 [router.go:861][C] E:/goPath/src/github.com/astaxie/beego/template.go:53
> 2016/11/19 09:18:01 [router.go:861][C] E:/goPath/src/github.com/astaxie/beego/controller.go:245
> 2016/11/19 09:18:01 [router.go:861][C] E:/goPath/src/github.com/astaxie/beego/controller.go:199
> 2016/11/19 09:18:01 [router.go:861][C] E:/goPath/src/github.com/astaxie/beego/controller.go:183
> 2016/11/19 09:18:01 [router.go:861][C] E:/goPath/src/github.com/astaxie/beego/router.go:785
> 2016/11/19 09:18:01 [router.go:861][C] D:/software/Go/src/net/http/server.go:2081
> 2016/11/19 09:18:01 [router.go:861][C] D:/software/Go/src/net/http/server.go:1472
> 2016/11/19 09:18:01 [router.go:861][C] D:/software/Go/src/runtime/asm_amd64.s:1998

**Comment by newyangyang** [comment]
no one have the same problem?

**Comment by astaxie** [comment]
1. beego will auto find the template if you didn't set the `beego.BConfig.WebConfig.AutoRender = false`

2. it's a bug. already fixed in beego1.7
