### ISSUE TITLE
orm:datetime的默认时间不成功

### ISSUE THREAD

**Issue by happyEgg** [astaxie/beego#2238]
beego1.7.1

created time.Time `orm:"default('0000-00-00 00:00:00')"`
这个默认值不起作用呀

**Comment by happyEgg** [comment]
why

**Comment by maphybao** [comment]
因为这是个非法的时间，公元0年是不存在的。公元是一个时间“点”，也就是神话中耶稣出生的日子。所以有公元前1年，公元后一年，但是公元是个点，没有公元0年

**Comment by godblesshugh** [comment]
但是好像这样设置默认值也是没用的啊
`Birthday       time.Time `orm:"default('2010-01-01 01:01:01');type(datetime)"``
转换成的数据库键表语句是这样：
`birthday datetime NOT NULL,`
没有默认值
