### ISSUE TITLE
内置的日志格式不支持占位符

### ISSUE THREAD

**Issue by kira8565** [astaxie/beego#2239]
beego.Info("当前用户尚未登录，跳转至登录页,IP为：%s", ctx.Request.RemoteAddr)

输出为：

2016/10/23 20:37:36 [I] [main.go:23] 当前用户尚未登录，跳转至登录页,IP为：%s 127.0.0.1:64444

建议支持占位符的功能

**Comment by raphael10241024** [comment]
因为beego的输出是可以直接把后面的参数连接到一起的，所以暂时不支持这个功能。

**Comment by kira8565** [comment]
但是感觉有格式化输出的话，连在一起的功能就显得不是那么必要了

**Comment by raphael10241024** [comment]
Sprintf本身是带占位符的，beego输出也是用的Sprintf ("%v %v %v",.......) 为了方便所以转成这样

**Comment by xiaoqiang0** [comment]
我也感觉支持比较好，毕竟 beego/logs也支持，可以增加*F类参数支持占位格式参数。
