### ISSUE TITLE
the transaction of orm

### ISSUE THREAD

**Issue by wangping886** [astaxie/beego#2242]
![2ba62768-e5a3-48c2-9799-50b62ff2bfd7](https://cloud.githubusercontent.com/assets/22444729/19640175/1f413958-9a0e-11e6-9a82-4d7c07e333a6.png)
<img width="448" alt="62e6a564-5b05-45da-b1b4-16e7e809261f" src="https://cloud.githubusercontent.com/assets/22444729/19640174/1f40a0b0-9a0e-11e6-8cf6-e14928423aa0.png">

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.7

2. What operating system and processor architecture are you using (`go env`)?
go env

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by wangping886** [comment]
i use orm to control transaction.   db log seems right .  but the data of mysql lost .my english is poor.  can I use chenese?

**Comment by astaxie** [comment]
@wangping886 Actually MySQL's drop database will cause an implicit commit http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by wangping886** [comment]
@astaxie   i thought it was beego/orm go-code to control auto-commit or false.   for  mysql i'm a newbie . thanks to your reply.
