### ISSUE TITLE
<新需求>希望Beego框架能提供从运行环境中获取变量的功能

### ISSUE THREAD

**Issue by CHCP** [astaxie/beego#2245]
Beego版本1.7

需求描述：在不同的运行环境（dev、test、prod）中定义环境变量，如数据库访问地址URL，赋值不同。Beego启动后根据conf/app.conf中的定义查找运行环境的变量，如果存在则使用运行环境的变量值替换原有定义，以达到访问不同数据库的目的。类似Java的框架SpringFramework的功能。

**Comment by astaxie** [comment]
`xxx = ${ENV_VAR||root}`

已经支持这样的语法，默认从环境变量`ENV_VAR`, 不存在就默认值`root`

**Comment by xuchengithub** [comment]
> `xxx = ${ENV_VAR||root}`
> 
> 已经支持这样的语法，默认从环境变量`ENV_VAR`, 不存在就默认值`root`
 beego version 1.11.1
这样使用好像并无效果   bee  run -runmode=prod
