### ISSUE TITLE
beego如何处理悲观锁(how to deal with the pessimistic lock in beego)

### ISSUE THREAD

**Issue by xuzhiping7** [astaxie/beego#2246]
因为业务需要，两个进程同时访问同一个数据库。经常会造成：

driver: bad connection 
packets.go:405: busy buffer

等相应错误，导致卡死其中一个进程，我想知道这种情况在BEEGO该如何处理？

求教！
----------------

we want  two process to visit a same database ,but when  they running  would cause the error such like :

driver: bad connection 
packets.go:405: busy buffer

etc.

then error  process will break down ,so i want to know how can i deal with that problem , how can i do it in beego is better ?

thanks

**Comment by astaxie** [comment]
I think you need `sync.Mutex`

**Comment by xuzhiping7** [comment]
sync.Mutex works multi-thread by defining a global value, but how can it work between two process ?

i couldn't define a global value to them ..

**Comment by astaxie** [comment]
两个进程同时访问同一个数据库，这个不是应该数据库处理的吗？

**Comment by xuzhiping7** [comment]
我们用的mysql ,没有以前相关处理经验，不知道怎么查资料

**Comment by sioncheng** [comment]
看看这个blog http://wangletong.tumblr.com/post/67030419325/go-mysql-drive%E7%9A%84%E4%B8%80%E4%B8%AA%E5%9D%91

运行出错：
wangzheng@backtest12:~/Workshop/Go/Demo$ bin/dbupdate 
Test MySQL …
[MySQL] 2013/11/15 12:23:22 packets.go:381: Busy buffer
panic: driver: bad connection

后来发现Query后的结果集必须清空才能再次执行：

**Comment by xuzhiping7** [comment]
我的问题估计是和sioncheng提到的一样，我先自己排查一下。

**Comment by astaxie** [comment]
这个好像和beego没啥关系吧

**Comment by xuzhiping7** [comment]
OK～我改下，加错误保护。
