### ISSUE TITLE
beego.orm 不支持UnRegisterDataBase如何实现数据库重连

### ISSUE THREAD

**Issue by xiaoqiang0** [astaxie/beego#2253]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?

1.7.1
1. What operating system and processor architecture are you using (`go env`)?

linux centos7
1. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

go的服务中db的链接都是长连接，一旦运行中链接异常，如何恢复，最简单的重新调用下RegisterDataBase，但是不允许对已经存在的db删除或更新，如何做呢？
谢谢
4. What did you expect to see?
1. What did you see instead?

**Comment by fuxiaohei** [comment]
go的sql.DB不是一个长连接，是一个连接池。。当运行中连接异常一般是打印日志然后立刻重连重新操作。如果还是失败会返回错误。所以没有必要对连接池做关掉重开的操作

**Comment by haroldTlan** [comment]
@fuxiaohei 
请问一个问题，假若我经常使用远程连接数据库，会经常解除跟重新注册，然而beego没有UnRegisterDataBase，所以每次RegisterDataBase都会出现
[ORM]2016/12/28 17:04:36 DataBase alias name remote1921682149 already registered, cannot reuse

现阶段只能忽略这个错误，请问还有什么办法解决吗

**Comment by One2r** [comment]
我也觉得UnRegisterDataBase还是要的

**Comment by flycash** [comment]
使用`NewOrmWithDB` 这个方法将不会缓存DB，也就不会带来重名冲突的问题。
