### ISSUE TITLE
[新需求]希望能提供类似flyway自动进行数据库表升级的功能

### ISSUE THREAD

**Issue by CHCP** [astaxie/beego#2258]
Beego Version 1.7.2

版本发布时都有数据库SQL语句的更改，手工维护非常麻烦。flyway可以实现数据库SQL的版本维护，实现自动升级。希望Beego也能提供这一功能。谢谢。

flyway官网：https://flywaydb.org/

非常看好Beego的发展。

**Comment by astaxie** [comment]
bee migration
