### ISSUE TITLE
how to custom session id ?

### ISSUE THREAD

**Issue by imiskolee** [astaxie/beego#2259]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

beego 1.7.1

how to custom settings session id ? 
sometime,i will use system user id for session id.

**Comment by raphael10241024** [comment]
did you mean the session id that in cookie ?
It changes rarely in fact, you can set it at   
session.NewManager("memory", `{"cookieName":"gosessionid",....
you cant set it only  when it's init.

**Comment by imiskolee** [comment]
@raphael10241024  

tanks for u.

i think  second param of session custructor (`session.NewManager` ) is a configure struct.
i can change the field `cookieName ` to any string ,and the real cookies is a default value only ?

**Comment by astaxie** [comment]
it not allowed

**Comment by raphael10241024** [comment]
you can use a secret number in your post form , APIs don't use cookie to do this at all.
if you can server get requests only ,you can add it to you url too, like xxx.com?secert_code=??
