### ISSUE TITLE
Orm rollback

### ISSUE THREAD

**Issue by mobilemindtec** [astaxie/beego#2273]
Hi,

I'm starting with beego, and in my project I implemented a default controller to handle database's transactions.. but when a no handled error happens I do not know where to call rollback.
Is there any filter or default finally method that I can use?

For now I changed my router.go to recover before the call to controller method and call Finally:

```
defer func() {      
    if r := recover(); r != nil{
        errorMethodName := "Finally"
        ctrlType := reflect.TypeOf(vc.Interface())        
        if _, ok := ctrlType.MethodByName(errorMethodName); ok {
            method := vc.MethodByName(errorMethodName)          
            var in []reflect.Value    
            method.Call(in)         
        }
    }
}
```

Is there a better way?

**Comment by astaxie** [comment]
@mobilemindtec why you need to recover outsite the controller handler?

```
type  AController struct{
     beego.Controller
}

func(a *AController) Get(){
         o := orm.NewOrm()
         // logic
         if err!=nil{
              o.Rollback()
         }
        o.Commit()
}
```

if you have concern on the no handlerd error happen, I think you can catch the error insite the Get method.

**Comment by mobilemindtec** [comment]
Hi,

 I want to control transactions on the BaseController, transparently in regard to the controller's logic.

The steps are:

1 - At Prepare method I do Begin transaction
2 - At Finish methid I do Commit transaction
3 - At Finally method I do Rollback, if there were errors

I do not want to control transactions into the specific controller methods.Most of the web frameworks have this transactional handling. This is my BaseController transactions logic:

```
type BaseController struct {
  beego.Controller 
  Db orm.Ormer
}

func (this *BaseController) Prepare() {
  this.Begin()
}

func (this *BaseController) Finish() {  
  this.Commit()
}

func (this *BaseController) Finally(){
  this.Rollback()
}

func (this *BaseController) Begin() {  
  this.Db = orm.NewOrm()
  this.Db.Using("default")    
  err := this.Db.Begin()
  if err != nil {
    panic(err)
  }
}

func (this *BaseController) Commit() {
  if this.Db != nil{
    err := this.Db.Commit()
    if err != nil {
      this.Rollback()
      panic(err)
    }
    this.Db = nil
  }
}

func (this *BaseController) Rollback() {
  if this.Db != nil{
    err := this.Db.Rollback() 
    if err != nil {
      beego.Error("## db rollback error", err.Error())
      panic(err)
    }
    this.Db = nil
  }
}
```

And if I change beego router, when not handled errors happen, transactions are not pending.
