### ISSUE TITLE
Data cannot be recognized in template file

### ISSUE THREAD

**Issue by terrylai** [astaxie/beego#2275]
Hello,

I am using go 1.7.3 and beego 1.7.1

I am using ubuntu and amd64 processor

My "go env" is:

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ttt/project-go"
GORACE=""
GOROOT="/home/ttt/go"
GOTOOLDIR="/home/ttt/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build402461836=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

What I am doing is just writing a script in the template:

<select name="reader_name">
{{range $k, $v := .Readers}}
<option value="{{$v.Name}}" {{if eq .ReaderName $v.Name}}selected{{end}}>{{$v.Name}}</option>
{{end}}
</select>

I get an error

 [E] [server.go:2202] template: provision.tpl:45:22: executing "provision.tpl" at <.ReaderName>: can't evaluate field ReaderName in type models.Reader

The ReaderName data is defined and can be seen by just typing {{.ReaderName}} in another position of the template.

Please help!

BR,
Terry

**Comment by astaxie** [comment]
you need to use `$.ReaderName`
