### ISSUE TITLE
用beego.Info打印日志到文件，日志文件日期错误。

### ISSUE THREAD

**Issue by kztxt** [astaxie/beego#2281]
bee   :1.4.1
beego :1.7.1
Go    :go version go1.7 linux/amd64

用beego.Info打印日志到文件，刚开始运行时正常，过段时间日志文件日期错误，如下：
2016/12/15 16:41:00 [TelController.go:48][I] |intf|
2016/12/15 16:41:06 [UserFilterController.go:77][I] |USERFILTER|INSRT|
2016/12/15 16:41:14 [TelController.go:48][I] |intf|

重启服务无效。

**Comment by astaxie** [comment]
有没有可以复现的代码？我本机刚测试了都是正常的，你说的过段时间是指多久呢？

**Comment by kztxt** [comment]
项目8月份开始运行跑的，10月1日之前都正常，之后就这样了：  

 tail -n2 logs/intf.2016-10-01.001.log 
2016/09/30 23:59:38 [SmsController.go:30][I] |intf|
2016/09/30 23:59:41 [SmsController.go:30][I] |intf|S
[-1447048202613-82 interface]$ head  -n2 logs/intf.2016-10-02.001.log 
2016/11/01 00:13:48 [SmsController.go:30][I] |intf|S
2016/11/01 00:29:43 [SmsController.go:30][I] |intf|S


日志配置   {"filename":"logs/intf.log","daily":true,"maxdays":30}

**Comment by astaxie** [comment]
@kztxt 那么你的线上的beego不是最新版本1.7.1，是1.6版本有这个bug，你上报的是错误的版本号

**Comment by kztxt** [comment]
哦，谢谢，我检查下。
