### ISSUE TITLE
!!!紧急，sessinon被串改，莫名其妙的登录了别人的账户 

### ISSUE THREAD

**Issue by bnulee** [astaxie/beego#2289]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.7.1 
beego source code is licensed under the Apache Licence, Version 2.0
2. What operating system and processor architecture are you using (`go env`)?
window，limux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

![image](https://cloud.githubusercontent.com/assets/75080/20509187/eaff68e0-b0a1-11e6-8224-3267d08b0bea.png)

以上是session配置，访问网站，如果登录信息就变成另一个人的了。不知道怎么重现。
4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
以上是session配置，访问网站，如果登录信息就变成另一个人的了。不知道怎么重现。

登陆之后变成另一个人，这个好像和session没关系吧

**Comment by bnulee** [comment]
@astaxie 我的domai设置的是顶级域名。有两个api应用公用一个数据库session表。这种情况，有没可能发生session_key，被串改，重置的情况？

**Comment by astaxie** [comment]
照理来说应该是不会的，第一，sessionID是不会存在重复的情况，第二session_key被串改是什么意思啊？

**Comment by bnulee** [comment]
@astaxie  犯了一个低级错误。数据库的session_key类型为int了！所以1abcde和1wieurq的key都存了1。。。感谢耐心解答，好作者。赞一个

**Comment by astaxie** [comment]
🙈
