### ISSUE TITLE
beego可以支持API自动化文档，我想问一下beego能自动生成swagger.json文件吗？怎么生成？

### ISSUE THREAD

**Issue by xiawenji** [astaxie/beego#2290]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
`bee run -gendoc=true`
