### ISSUE TITLE
map_get error

### ISSUE THREAD

**Issue by h3llowor1d** [astaxie/beego#2295]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.7 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/gopath:/Users/me/work/go:/Users/me/gostudy"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/4zsp9t3d3s9bglpj7_9l3p_00000gn/T/go-build701581005=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
3. What did you do?
c.Data["m"] = map[string]interface{}{
		"5":0,
		"4":1,
	}

{{ map_get .m "5" }}

runtime error: invalid memory address or nil pointer dereference

**Comment by astaxie** [comment]
controller:
```
func (c *MainController) Get() {
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	c.Data["m"] = map[string]int{
		"5": 1,
		"4": 1,
	}
	c.TplName = "index.tpl"
}
```
template:
```
{{ map_get .m "5"}}
```

output
```
1
```

**Comment by h3llowor1d** [comment]
@astaxie map_get 用在循环中报错 在循坏外正常

**Comment by astaxie** [comment]
你应该先去学习一下模板的变量范围概念：https://beego.me/docs/mvc/view/tutorial.md
