### ISSUE TITLE
关于beego架构性能的问题，可以通过对哪些配置参数进行修改，可以提高RESTFUL API对http请求的响应速度

### ISSUE THREAD

**Issue by xiawenji** [astaxie/beego#2297]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
你说的是横向扩展的问题？

**Comment by xiawenji** [comment]
@astaxie 比如说起一个单进程的程序，一秒钟能处理多少条http请求，怎样加快处理的速度。我做一个测试让程序接收到http请求之后直接返回一个“Hello World”，使用mux框架每秒钟处理大约30000条消息，而beego大约处理15000条，效率只有mux的一半。想请教下怎么提高beego的处理效率

**Comment by Mxxim** [comment]
同问

**Comment by welemon** [comment]
QPS for web server > 1K is already good enough for most cases, in most of time, your business logic or other implementation cause much slower than web framework itself.  Such "hello world" benchmark can tell some difference between frameworks,  it does not matter too much in reality. There are lots of other framework or languages slower than this, but success with rich feature, easy integration, well support and widely adoption etc.
