### ISSUE TITLE
从redis取出来的缓存数据经过base64处理了

### ISSUE THREAD

**Issue by BigKuCha** [astaxie/beego#2298]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.7.3 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bigkucha/Project/Go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gm/ctnr5jv12qg5hnclxf245f180000gn/T/go-build565934120=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?

分别用redis和file缓存引擎存储数据

4. What did you expect to see?

不同的引擎取出来的数据格式一致

5. What did you see instead?
redis引擎取出来的数据经过base64加密了,或者说file引擎取出来的数据没有经过加密。

**Comment by ansiz** [comment]
确切的说是因为从redis中取出的数据是[]byte,  你应该是直接取出来之后放到了c.Data["json"]中然后调用c.ServeJSON()， 而c.ServeJSON()中会将interface{}进行一次json.Marshal()处理，根据golang文档说明，[]byte会被处理成base64字符串

> https://golang.org/pkg/encoding/json/#Marshal
Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.
