### ISSUE TITLE
关于beego使用原生插入时间的错误问题

### ISSUE THREAD

**Issue by happyEgg** [astaxie/beego#2300]
bego:1.7.1
go:1.7.1

我的created在数据库是date格式，updated在数据库的是datetime格式，执行下面操作时出错
o.Raw("INSERT INTO test(id,created,updated) values(?,?,?)",1,time.now(),time.now()).Exec()

*mysql.MySQLError=Error 1292: Incorrect date value: '00:00:00' for column 'created' at row 1)
 *mysql.MySQLError=Error 1292: Incorrect datetime value: '18:21:08' for column 'updated' at row 1)
@astaxie

**Comment by happyEgg** [comment]
为啥没人理我？

**Comment by yhua123** [comment]
在我的环境里也遇到同样的错误:
Error 1292: Incorrect datetime value: '09:32:17' for column 'op_time' at row 1

Beego:1.7.1

`OpTime time.Time `orm:"column(op_time)" json:"op_time"``

`sql := "insert into  access_log (user_id , op_time) "
o.Raw(sql, username, time.Now())`

在Beego 1.6.1没有出错，升级1.7.1出错
