### ISSUE TITLE
can we transfer data between two web application created using beego

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2321]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go version:1.6
Beego Version:1.7.1

2. What operating system and processor architecture are you using (`go env`)?
Windows and amd64

I would like to send and receive data(JWT token) between the two different web application created using beego.
Can u please give me some example of how to do this.Thanks

**Comment by araufdogan** [comment]
You can use redis publish/subscribe functions. You can send and receive data between all redis connected applications. I don't know is there any example, check go-redis.

**Comment by RajeshKumar1990** [comment]
The problem is i have these application in two different servers.So is there any way to do this.Thanks
