### ISSUE TITLE
commentsRouter_controller.go always changes back to original version

### ISSUE THREAD

**Issue by mjniuz** [astaxie/beego#2322]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.5.2

2. What operating system and processor architecture are you using (`go env`)?
Windows 64bit, Intel core

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Updated manually the commentsRouter_controller.go

4. What did you expect to see?
Running namespace URL by changed commentsRouter_controller.go

5. What did you see instead?
commentsRouter_controller.go always revert back to original version after rebuild automatically 

6. IDE
Jetbrain PHPStorm 2016.1

**Comment by astaxie** [comment]
you can't change commentsRouter_controller.go as it's auto generated by beego
