### ISSUE TITLE
beego拦截器里的权限控制

### ISSUE THREAD

**Issue by victor-u** [astaxie/beego#2330]
1：想在beego的拦截器里面，获取controller信息来做一个全局的方法：
     来判断调用者的权限（method对应的开发者、管理员的调用权限）

2：接口调用的权限信息在一个配置文件里面，指定特定方法的是开发者，还是开发者以上权限才能调用
3：目前发现beego有一个方法：routerInfo, find := beego.BeeApp.Handlers.FindRouter(ctx)
      但是获取到的routerInfo没法导出信息，一些URL是正则表达式，所以用requestUri不是很合适

不知道使用beego现有的方法和流程，能否实现这个功能，期盼大牛们的回复

**Comment by zjxpcyc** [comment]
问题1,  我目前也在学习beego，我学习到的可能你说的还不太好做。我理解，你的切入点应该是在 Controller 存在，但是还没有执行的状态，这个应该是 Prepare 的点。但是这个点，在 Filter 里没有。
你可以换到 Prepare 里面去做，当前的Controller 应该可以使用 AppController

**Comment by astaxie** [comment]
这个是Prepare里面要去做的，至于怎么获取controller和method 参考这个方法 https://github.com/astaxie/beego/blob/master/controller.go#L638-L640

**Comment by victor-u** [comment]
非常感谢2位，通过controller的Prepare搞定了，得到astaxie 的回复真happy^^
