### ISSUE TITLE
请问，使用orm.RegisterDataBase注册一个别名为“default”的数据库，那么之后怎么注销这个“default”数据库呢，

### ISSUE THREAD

**Issue by xiawenji** [astaxie/beego#2333]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
为什么要注销呢？

**Comment by haroldTlan** [comment]
[ORM]2016/12/28 17:04:36 DataBase alias name `remote1921682149` already registered, cannot reuse

由于需要使用固定格式注册远程database，虽然出现这种问题不会影响使用，但还是希望有个方法可以注销

**Comment by astaxie** [comment]
这个用法我还真是第一次遇到呢，我考虑一下是不是需要支持

**Comment by xiawenji** [comment]
@astaxie@haroldTlan 我就是这种情况，要以固定的格式多次注册远程的database（如err = orm.RegisterDataBase(aliasName, "mysql", conn) ，aliasName相同，conn不同），但是多次重复注册会提示错误。为了避免错误只能注册多个数据库（多个aliasName对应多个conn）

**Comment by One2r** [comment]
@astaxie 我也要这个需求

**Comment by minnao** [comment]
@xiawenji  我恰恰相反我想知道怎么注册别名。。
报错信息：[ORM]2017/05/07 21:32:02 register db Ping `default`, Error 1049: Unknown database 'beeblog'
must have one register DataBase alias named `default`

**Comment by Q14** [comment]
同问

**Comment by Ydcool** [comment]
同样的问题，由于别名冲突的原因，导致无法执行单元测试。

**Comment by ouqunfu** [comment]
@xiawenji @haroldTlan 我也遇到了这个问题，我这是这样处理的，使用GetDB从已注册的数据库返回 *sql.DB 对象，如果alias name 没有注册，会报错 DataBase of alias name `XXX` not found，
代码如下：
_, err := orm.GetDB(dbName)
	if err != nil {
		log.Println(err)
		orm.RegisterDataBase(dbName, "mysql", conn)
	}

**Comment by flycash** [comment]
其实这种重复注册出现的场景是，多租户模式。也就是用户只有一个应用，但是对标多个数据库。有些客户要求数据隔离，所以会有单独的数据库。在这种情况下，从代码层面而言，逻辑上的数据库名字可能是同一个，但是对于不同客户来说，真实的数据库是不同的，即意味着连接信息不同。

重复注册会有一个问题：并发问题与业务隔离的问题。如果一个请求在处理过程中，原本 default 指向的是 a:3386。执行到一半的时候，再次创建orm，然后就变成指向 b:3386。从这个角度来讲，开发人员很难把握当前的orm究竟指向哪个真实的数据库。

而销毁，则会面临另外一个问题，就是销毁的时候并不知道，是否还有人在用这个DB实例。

这就是我们最近重构ORM时候纠结的问题。

**Comment by flycash** [comment]
我感觉你们可以考虑使用
```go
func NewOrmWithDB(driverName, aliasName string, db *sql.DB) (Ormer, error) {}
```
这个方法并不会导致alias冲突。

我们考虑的是，如果一个aliasName对应的DB都需要经常修改，那么它不应该被我们缓存下来，换言之，使用这个方法的话，可以重复注册。
