### ISSUE TITLE
Session Control using Redis will crash the application

### ISSUE THREAD

**Issue by WUMUXIAN** [astaxie/beego#2337]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.5.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I use the ORM module and Session Control functionality in my app, to use ORM, I have defined a one-to-many relationship like this:

type User struct {
	Email            string         `orm:"pk;size(45)" json:"email"`
	Profile   *Profile       ` orm:"reverse(one)" json:"-"`
}

type Profile struct {
	ID          int      `orm:"pk;auto" json:"-"`
	User        *User    `orm:"rel(fk)" json:"user"`
}

Now when I use the session function to save an instance of a user, say:

o.SetSession("user", user)

It will have problem. Because beego session using redis actually uses gob to do serialisation of the struct, however, gob doesn't support recursive struct.

How do we solve this problem?

**Comment by astaxie** [comment]
please look at the documents here :https://beego.me/docs/mvc/controller/session.md#note%3A

>Session uses gob to register objects. If you are using a session engine other than memory, please register the objects you use in session before using them. You can use gob.Register() to register them in init() function.

**Comment by WUMUXIAN** [comment]
I did use gob register to register the objects in session before using, the issue is that when you have a cross reference in the object, such that 
type User struct {
Email string orm:"pk;size(45)" json:"email"
Profile *Profile orm:"reverse(one)" json:"-"
}

type Profile struct {
ID int orm:"pk;auto" json:"-"
User *User orm:"rel(fk)" json:"user"
}

It seems that it's not supported by Gob, because it always crashed when calling GetSession.

**Comment by WUMUXIAN** [comment]
I have found out that the crash is caused by a reference loop. where user -> Profile and profile -> User. It's resolved by avoiding the endless loop.
