### ISSUE TITLE
orm datetime

### ISSUE THREAD

**Issue by araufdogan** [astaxie/beego#2340]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.1
├── GoVersion : go1.7.1
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\Users\ARD\Desktop\Project532
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Thursday, 22 Dec 2016

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64

3. What did you do?
I set the computer's timezone to utc, mysql installed on this computer. I am making test write and read datetime to mysql database. I create simple model named Test and i did following steps.

```
orm.DefaultTimeLoc = time.Local
t := time.Now()

test := models.Test{ Date: t }
test.Id, _ = db.Insert(&test)

fmt.Println("Date2: ", test.Date)

test2 := models.Test{ Id: test.Id }
db.Read(&test2, "Id")

fmt.Println("Date3: ", test2.Date)
```
results should be same test2.Date and test.Date but it has 2 hours time difference.

```
Date2:  2016-12-22 22:37:30.2640354 +0000 GMT
Date3:  2016-12-22 20:37:30 +0000 GMT
```

When i change DefaultTimeLoc to time.UTC. Computer's date is still utc,

```
Date2:  2016-12-22 22:51:23.0970354 +0000 GMT
Date3:  2016-12-22 20:51:23 +0000 UTC
```

When i change computer date to utc+3,

```
Date2:  2016-12-23 01:54:49.8710354 +0300 EET
Date3:  2016-12-22 20:54:50 +0000 UTC
```

I want to insert and read (same) utc date independent of the local timezone, how can i do this?

**Comment by araufdogan** [comment]
I added following lines to my.ini and it works now. (I am using mysql 5.7)

```
explicit_defaults_for_timestamp = 1
default_time_zone='+00:00'
```

**Comment by fathimashaibal** [comment]
What about the same in postgres??
