### ISSUE TITLE
是否可以在 httplib 模块增加失败重试次数功能

### ISSUE THREAD

**Issue by lunux2008** [astaxie/beego#2354]
比如增加 Retry(失败次数参数) 
resp, err := httplib.Get(url).SetTimeout(0.3 * time.Second, 0.3 * time.Second).Retry(1).Response()

**Comment by lunux2008** [comment]
或者可以再加个回调函数参数默认可以不传，比如增加 Retry(失败次数参数, 回调函数)
resp, err := httplib.Get(url).SetTimeout(0.3 * time.Second, 0.3 * time.Second).Retry(1, func (err) {}).Response()

**Comment by astaxie** [comment]
https://github.com/astaxie/beego/commit/61e694f388c9ad3b81585a17c8fbdef18859411e
