### ISSUE TITLE
Redirect  from API to another application view page is not working

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2355]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego:1.6.2
Golang:1.7.1

2. What operating system and processor architecture are you using (`go env`)?
Windows Operating system
amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I would like to redirect from API to another application view page.So i did the following

```
func (this *MainController) Get() {
this.Redirect("http://localhost:8080/index.html",400)
}

```
4. What did you expect to see?
I would like to redirect to the index page of localhost :8080

5. What did you see instead?
Nothing happens

**Comment by antony66** [comment]
Redirect() needs 2 parameters:

1. Destination url
2. HTTP status code

HTTP status codes for redirects are 301 and 302. You send HTTP status code 400 which is "Bad Request". See http://www.restapitutorial.com/httpstatuscodes.html
