### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by sokoow** [astaxie/beego#2356]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
git head

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I'm trying to use VMWare harbor with mariadb getting this:

[ORM]register db Ping `default`, Error 1251: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
panic: register db Ping `default`, Error 1251: Client does not support authentication protocol requested by server; consider upgrading MariaDB client

4. What did you expect to see?

Something working

5. What did you see instead?

**Comment by sokoow** [comment]
it might be related to this: https://github.com/go-sql-driver/mysql/issues/330

**Comment by antony66** [comment]
MariaDB works just fine with beego. I use it with 10.0.27 on MacOS and 10.1.19 on Linux (Debian jessie). You need to check your server settings.

**Comment by sokoow** [comment]
Ok, I think it's harbor specific issue, amd64 behaves the same with default ubuntu mariadb install: https://github.com/vmware/harbor/issues/1272
