### ISSUE TITLE
Space character can be used to get passed `Required` validation

### ISSUE THREAD

**Issue by chesedo** [astaxie/beego#2361]
#### bee version
Beego     : 1.7.2
GoVersion : go1.7.3
GOOS      : linux
GOARCH    : amd64
NumCPU    : 2
GOPATH    : /home/chesedo/go-code
GOROOT    : /home/chesedo/go
Compiler  : gc
Date      : Wednesday, 4 Jan 2017

#### go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chesedo/go-code"
GORACE=""
GOROOT="/home/chesedo/go"
GOTOOLDIR="/home/chesedo/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build049135941=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

#### What I did
When one creates a validation element with the `Required` validation it will pass when the value is only spaces. Eg:
```go
type Test struct {
	Field string `form:"Required"`
}

func main() {
	// Create test with empty `Field`
	test := Test{}
	valid := validation.Validation{}

	v := valid.Required(test.Field, "field")
	fmt.Printf("Validation has error '%s' as expected for missing value\n", v.Error.Message)

	// Make `Field` a space value
	test.Field = " "
	v = valid.Required(test.Field, "field")
	fmt.Printf("Validation has error '%v' which is unexpected for space value\n", v.Error)

	// Output:
	// Validation has error 'Can not be empty' as expected for missing value
	// Validation has error '' which is unexpected for space value
}
```

#### Expected
I expected the validation to also fail when the value was just spaces

#### Results
When the value was just spaces it passed the validation

If this is a bug then I would be happy to submit a PR.

**Comment by Raggaer** [comment]
I guess that a space character counts as a string... so how can this be a problem?

**Comment by chesedo** [comment]
@Raggaer imagine if a field is required, then just " " would make it pass that validation. Or if a field has a MinSize of 10, then "1234          " can be used to get passed that too.

So it short padding space characters is a problem.
