### ISSUE TITLE
api应用注释路由只能runmode = dev时执行bee run才能生成正确的路由

### ISSUE THREAD

**Issue by ansiz** [astaxie/beego#2369]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : 1.7.2
├── GoVersion : go1.7.4
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /var/lib/jenkins/jobs/hpc-backend/workspace/
├── GOROOT    : /root/go/
├── Compiler  : gc
└── Date      : Saturday, 7 Jan 2017

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/var/lib/jenkins/jobs/hpc-backend/workspace/"
GORACE=""
GOROOT="/root/go"
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build603745758=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
我用beego编写了api应用，采用了注解路由的方式编写代码，在和CI系统对接时发现直接go build出来的程序所有API都出现了404，看起来根本没有生成正确的路由。

4. What did you expect to see?
希望使用bee pack或go build打包出来的程序能正确的运行，我部署的CI需要将build成功的程序拷贝到其他地方以test模式运行，这样在和CI系统对接时处理起来比较麻烦。

5. What did you see instead?
* 使用bee api创建的应用，当runmode = dev时运行bee run/go run main.go能生成正确的路由，其他模式则不行
* 当runmode不为dev时无法生成路由
* 只执行go build/bee pack无法生成路由

**Comment by xiawenji** [comment]
我也遇到相似的问题，在prod下，bee run -gendoc=true 可以产生正确的swagger文档，不能生成路由。在dev下模式下，能够生成正确的路由。奇怪的是当我从dev切换到prod时，prod有可以生成正确的路由了。不明白什么原因

**Comment by ansiz** [comment]
@xiawenji 我提这个issue是因为我们的开发环境和CI系统以及最后的部署环境都是在不同的机器上，在部署的环境上我们不希望有源码，不知道是否和你的问题一样。

造成这个问题的原因是因为注解路由只会在dev模式下被解析，具体代码： https://github.com/astaxie/beego/blob/master/router.go#L217-L243  
比较简单的办法是将dev模式下生产的commentsRouter_controllers.go文件添加到代码仓库中。

该问题可能会在https://github.com/astaxie/beego/issues/2520 中得到解决，可以关注一下

**Comment by hustlihaifeng** [comment]
为什么dev模式下，执行go build不能得到新添加接口的注释路由，这个有结论么？官方的意思，似乎只要是dev模式就能生成新的注释路由

**Comment by maxshine** [comment]
> 为什么dev模式下，执行go build不能得到新添加接口的注释路由，这个有结论么？官方的意思，似乎只要是dev模式就能生成新的注释路由

注解路由是在应用运行过程中生成的。
