### ISSUE TITLE
router setting error

### ISSUE THREAD

**Issue by kevin-lv** [astaxie/beego#2372]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
stable v1.7.1

2. What operating system and processor architecture are you using (`go env`)?
win10,i5

3. What did you do?
beego.Router("/pc/s/:akka([\w]+)", &controllers.QuestionnaireController{}, "get:Show"),
error info:unknow escape sequence

When i used like this:
beego.Router("/pc/s/:akka([A-Za-z0-9_]+)", &controllers.QuestionnaireController{}, "get:Show")
it run successful.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
you need to use 

```
beego.Router(`/pc/s/:akka([\w]+)`, &controllers.QuestionnaireController{}, "get:Show")
```
