### ISSUE TITLE
Swagger, Failed to generate the docs

### ISSUE THREAD

**Issue by stgerrard008** [astaxie/beego#2374]
Beego: v1.7.2
Bee: v1.6.2
Swagger: v2
---------------------------------------------------------------
when I run the command "bee run -downdoc=true -gendoc=true", it failed to generate the docs

2017/01/10 11:53:06 INFO     ▶ 0009 Generating the docs...
2017/01/10 11:53:06 ERROR    ▶ 0010 Failed to generate the docs.

**Comment by amrfaissal** [comment]
@stgerrard008 Did you try this one: `GOGC=off bee generate docs`? Can you copy/paste the output?

**Comment by inu1255** [comment]
maybe you need set GOROOT
```
GOROOT=/path/to/your/goroot
bee run -downdoc=true -gendoc=true
```
this solve my issue

**Comment by stgerrard008** [comment]
@inu1255 thanks for your reply, that works

**Comment by JeanBlackCN** [comment]
you can  Run the CMD 
```bee generate docs```
and run
```bee run watchall true```

try do this, you can   get the docs  of api

**Comment by guodayang999** [comment]
`bee generate docs`
Return directory error, I from go.mod The file matches the directory

**Comment by flycash** [comment]
> `bee generate docs`
> Return directory error, I from go.mod The file matches the directory

Could you share your logs?
