### ISSUE TITLE
Select from postgresql data type "inet" return empty

### ISSUE THREAD

**Issue by unkind2000** [astaxie/beego#2383]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.8RC
beego 1.6.2
Database postgresql 

2. What operating system and processor architecture are you using (`go env`)?
Windows 10
set GOARCH=amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Model:
type InetData struc {
  IP           string   `json:"ip"`
  Country string   `json:"country"`
}
---------------------------------------
|            ip            |     Country          |
|       type inet      |    type string      |
---------------------------------------

In controller:

o := orm.NewOrm()
var result []modesl.InetData
_, err := o.Raw("SELECT * FROM Data WHERE IP && ? AND COUNTRY = ?", InetData.IP, InetData.Country).QueryRows(&result)
beego.Debug("Result: ", result) -> [{ US}, { US}....]

4. What did you expect to see?
boogo.Debug("Result: ", result) -> [{192.168.1.1 US}, {192.168.1.2 US}....]

5. What did you see instead?
beego.Debug("Result: ", result) -> [{ US}, { US}....]

**Comment by astaxie** [comment]
it's not support inet now. If you want to support you own type, you might to define a struct and implement https://godoc.org/github.com/astaxie/beego/orm#Fielder

**Comment by unkind2000** [comment]
Can you give some links or example, how it can be imlemented. A can`t find any examples in google.
Postgresql inet data type is byte (7 or 19), but if i try implement data type []byte, i can`t see any returned data after requset. Sorry for stupid questions:) I try understand how work with beego in real life example.
Thanks!!!

**Comment by astaxie** [comment]
Here have two example in our test case: https://github.com/astaxie/beego/blob/master/orm/models_test.go#L32-L108
