### ISSUE TITLE
Verbose logs in Beego

### ISSUE THREAD

**Issue by shlomitsur** [astaxie/beego#2385]
Hello

I'm running Beego in dev mode, is there a way to make it show more logs then shown in the 'bee run'  console?

Thank you

**Comment by amrfaissal** [comment]
@shlomitsur What do you need exactly? If you have a feature request, please give us more details and we'll make sure to land in the next release. Or you can raise a PR yourself ;).

**Comment by shlomitsur** [comment]
Hi @amrfaissal, 
I want to see some of the internal flow in Beego for debugging purposes, in Rails for example, you have a 'dubeg' log lever which is more verbose than 'info'

**Comment by amrfaissal** [comment]
Currently in the `develop` branch of `bee`, you can use: `DEBUG_ENABLED=1 bee run`. I never used Rails but I will definitly give it a look to see how we can implement something similar in Bee/Beego.
