### ISSUE TITLE
Testing a CRUD api Beego

### ISSUE THREAD

**Issue by shlomitsur** [astaxie/beego#2386]
Hello,

I was assigned of writing tests for a CRUD api, I did not find documentation on how to do it in Beego.
I just need to test a simple create, read, update and delete of a model.

Is there any example of such a thing? or some documentation?

Thank you

**Comment by julienkosinski** [comment]
If it's still useful for you, you have this doc : https://beego.me/docs/mvc/model/object.md

Also, a cool feature, if you already have a database to connect to, bee can create everything for you.
Install bee : https://github.com/beego/bee/blob/master/README.md
For example a database in Postgresql, type in command line (adjust corresponding of your connection) : `bee api test_api -driver="postgres" -conn="postgres://username:password@localhost/database?sslmode=disable"`
