### ISSUE TITLE
can't find templatefile in the path:index.tpl

### ISSUE THREAD

**Issue by qweawdqq** [astaxie/beego#2401]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8

2. What operating system and processor architecture are you using (`go env`)?
环境没问题的

3. What did you do?
用软件编译运行 就会出现找不到模版文件
can't find templatefile in the path:index.tpl
但是我用bee run 语句就能显示出
Welcome to Beego
我不明白我哪里操作错误了

**Comment by astaxie** [comment]
beego默认模式下回去自动找index.tpl模板

**Comment by mei2015** [comment]
> beego默认模式下回去自动找index.tpl模板
大大 我用这种绝对路径 开机启动
/user/bin/nohup /home/webser/sss
这种 就包 index.tpl 错误 还有就是 the request url is  / 

希望大大回复谢谢了 很着急
