### ISSUE TITLE
Why the commentsRouter_controller.go file is not generated when run bee run --gendoc=true?

### ISSUE THREAD

**Issue by iamatsundere** [astaxie/beego#2412]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.2
├── GoVersion : go1.6.2
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/phuctt/Documents/Go
├── GOROOT    : /usr/lib/go-1.6
├── Compiler  : gc
└── Date      : Friday, 3 Feb 2017

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fuzzybear/Documents/Go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
I run the command `bee run --gendoc=true`, but the commentsRouter_controller.go is not generated. I changed my main project to $GOPATH but it did not solve the issue. (Because my project tree is /current_repo/project1, project2,...)

4. What did you expect to see?
A new 'commentsRouter_controller.go' is generated.

5. What did you see instead?
Instead of generating new 'commentsRouter_controller.go' file, there was nothing happened, even when I deleted my current 'commentsRouter_controller.go' file.

**Comment by antony66** [comment]
Make sure you have 

    export GOPATH="..."
    export GOROOT="..."

in your .bash_profile/.bashrc

It is not enough to have them set in `go env`

**Comment by iamatsundere** [comment]
Many thanks, it works, I set the wrong `go env` for beego.
