### ISSUE TITLE
Support for JSON data type in beego orm

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2413]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.0

├── Beego     : 1.7.1
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Saturday, 4 Feb 2017

Since SQL, PostgreSQL,MariaDB supports json data type, it will be great if the beego orm supports it.Will there be any support sooner or later...
Thanks...

**Comment by astaxie** [comment]
it's supported

**Comment by RajeshKumar1990** [comment]
Really....Great.But i couldn't find the info regarding this in the beego documentation.Can  u please direct me to the page where i can learn how to implement JSON type for POSTGRESQL.
One more doubt
Is JSON array is also supported by beego orm??? 
Thanks.

**Comment by astaxie** [comment]
https://github.com/astaxie/beego/blob/master/orm/models_test.go#L142-L143

**Comment by sougannkyou** [comment]
How to solve this bug?

C:\Users\bigbang\go\src\xgksapi>**bee generate appcode -tables="fields"** -conn="root:root@tcp(127.0.0.1:3306)/xxx"
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| **v1.10.0**
2019/05/10 17:02:16 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2019/05/10 17:02:16 INFO     ▶ 0002 Using 'root:zhxg2018@tcp(127.0.0.1:3306)/xgks' as 'SQLConn'
2019/05/10 17:02:16 INFO     ▶ 0003 Using 'fields' as 'Tables'
2019/05/10 17:02:16 INFO     ▶ 0004 Using '3' as 'Level'
2019/05/10 17:02:16 INFO     ▶ 0005 Analyzing database tables...
2019/05/10 17:02:16 FATAL    ▶ **0006 data type 'json' not found**

![image](https://user-images.githubusercontent.com/6318370/57517254-ffebe500-7348-11e9-81ab-f492e3eabe68.png)
