### ISSUE TITLE
Html tags in i18n language file

### ISSUE THREAD

**Issue by chenxee** [astaxie/beego#2414]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.2
├── GoVersion : go1.7.5

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
Try to include html tags in i18n language file, for example `<br>`
`greeting=hello<br>john`

4. What did you expect to see?
```
hello
john
```

5. What did you see instead?
`hello<br>john`

First and foremost thanks for such a great product. I wanted to include some html tags in i18n language files, but I couldn't get it work. Is it supposed to be like this? Any workaround suggestion? thanks in advance.

**Comment by chenxee** [comment]
I have found `str2html` function in beego documentation. Thanks and closing issue.

**Comment by bakanis** [comment]
You should pass it to str2html function in your template, eg.:
{{str2html (i18n "en" "text")}}
