### ISSUE TITLE
Problems getting log to only log to a file and NOT to the console

### ISSUE THREAD

**Issue by goarchit** [astaxie/beego#2420]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.7.4

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/home/kevinc/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kevinc"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build756998437=/tmp/go-build -gno-record-gcc-switches"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Tried both logger.SetLogger("console", "{\"level\":7}")
and logger.SetLogger("console", "{\"level\":1}")

4. What did you expect to see?

Debug messages to NOT be displayed on the console at one level or the other.

5. What did you see instead?

logger.Debug messages being displayed all the time.

**Comment by CJClaude** [comment]
Issues appears to be at line 152 in logs/log.go where a Console session is started as part of the NewLogger() routine.   Just need a way to disable the Console session which would be backward compatible with the existing code.  For now, I've just commented out that line.

**Comment by amrfaissal** [comment]
@CJClaude It works fine. Did you try this?
```go
import "github.com/astaxie/beego/logs"

// Create logger
var log = logs.NewLogger(10000)
// Log errors only to a file
log.SetLogger("file", "{\"filename\":\"test.log\", \"level\": 3}")
log.Error("This is an error")
```

**Comment by CJClaude** [comment]
I'm not using the level parameter, but other than that my code is the same.

**Comment by goarchit** [comment]
Found the issue... had a sequencing problem.
