### ISSUE TITLE
Cannot use XSRF filtering in my  beego project

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2426]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.0

├── Beego     : 1.7.1
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Thursday, 9 Feb 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I m creating a beego api application for my project.
I enabled the XSRF in my config like this 
EnableXSRF = true
XSRFKey = 61oETzKXQAGaYdkL5gEmGeJJFuYh7EQnp2XdTP1o
XSRFExpire = 3600
And included the _xsrf field in my form and included in  the request of the header.

When i try do a post request i m getting the following error 
```
2017/02/09 17:39:42 [C] [asm_amd64.s:472] the request url is  /v1/employee/login
2017/02/09 17:39:42 [C] [asm_amd64.s:472] Handler crashed with error XSRF cookie does not match POST argument
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Go/src/runtime/asm_amd64.s:472
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Go/src/runtime/panic.go:443
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Projects/Go/src/github.com/astaxie/beego/context/context.go:79
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Projects/Go/src/github.com/astaxie/beego/context/context.go:176
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Projects/Go/src/github.com/astaxie/beego/controller.go:593
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Projects/Go/src/github.com/astaxie/beego/router.go:767
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Go/src/net/http/server.go:2081
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Go/src/net/http/server.go:1472
2017/02/09 17:39:42 [C] [asm_amd64.s:472] C:/Go/src/runtime/asm_amd64.s:1998
```

After some research i found that in the context.go file in the function CheckXSRFCookie , comparison is done between the encoded cookie token and the decoded token.
```
if ctx._xsrfToken != token {
		ctx.Abort(403, "XSRF cookie does not match POST argument")
		return false
	}
```
```
When i printed the value of the ctx._xsrfToken   variable  i got this
MUoOyDpT08JlDNDN18BI8SJRAEGCfs57
But when i print the value of the token variable  i got this  
NmNJSjdyZTFOUjRNaVNXUFVTalY1ejZGTmEyWU9RdnY=|1486632499494011900|96371b71fe43bbcb7933ae43da86b20342aae721
```
So i changed the code and  tried to decode the token and then compared, then its working.

One more doubt.When i get the  first post request from the front end application to the api   with the login credentials i dont know the _xsrf value.Since this is set  in the cookie only in the response of this request.
But the next time i can get and  send this value in the header of the request.So how to handle the first request from the front end to the beego api.
Appreciate any help.Thanks

4. What did you expect to see?
Successfully Calling the controller
5. What did you see instead?
Error as stated before

**Comment by ysqi** [comment]
hi @RajeshKumar1990 you need set  xsrf value from post head every time. you can get xsrf value from cookie by javascript. bellow it is my core code for request api in client.

**Get XSRC Token**
```js
getXsrf: function () {
        var xsrf = cookie.get('_xsrf');
        if (xsrf !== null) {
            xsrf = xsrf.split('|')[0];
            return utils.base64_decode(xsrf);
        }
        return "";
    },
```
**Setting Ajax Option**
```js
var defaultOption = {
            method: "POST",
            async: true,
            cache: false, 
            headers:{
               'X-Xsrftoken':this.getXsrf(), 
            }  
        };
        //merge
        options = $.extend(true, options, defaultOption);
```

**util for decode**
```js
base64_decode: function (data) {
        var b64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
        var o1, o2, o3, h1, h2, h3, h4, bits, i = 0,
            ac = 0,
            dec = '',
            tmp_arr = [];
        if (!data) {
            return data;
        }
        data += '';
        do { // unpack four hexets into three octets using index points in b64
            h1 = b64.indexOf(data.charAt(i++));
            h2 = b64.indexOf(data.charAt(i++));
            h3 = b64.indexOf(data.charAt(i++));
            h4 = b64.indexOf(data.charAt(i++));
            bits = h1 << 18 | h2 << 12 | h3 << 6 | h4;
            o1 = bits >> 16 & 0xff;
            o2 = bits >> 8 & 0xff;
            o3 = bits & 0xff;
            if (h3 == 64) {
                tmp_arr[ac++] = String.fromCharCode(o1);
            } else if (h4 == 64) {
                tmp_arr[ac++] = String.fromCharCode(o1, o2);
            } else {
                tmp_arr[ac++] = String.fromCharCode(o1, o2, o3);
            }
        } while (i < data.length);
        dec = tmp_arr.join('');
        return dec.replace(/\0+$/, '');
    }
```
**util for cookie**
```js
var doc=window.document;
var cookie = {
  get: function(name) {
    var cookieName = encodeURIComponent(name) + '=';
    var cookieStart = doc.cookie.indexOf(cookieName);
    var cookieValue = null;
    var cookieEnd;
    if (cookieStart > -1) {
      cookieEnd = doc.cookie.indexOf(';', cookieStart);
      if (cookieEnd == -1) {
        cookieEnd = doc.cookie.length;
      }
      cookieValue = decodeURIComponent(doc.cookie.substring(cookieStart +
      cookieName.length, cookieEnd));
    }
    return cookieValue;
  }
}
```

**Comment by RajeshKumar1990** [comment]
Thanks for your explanation.I think i misunderstood how it works.No i understood based on your comment.Thanks.I will close this issue.Thanks once again//
