### ISSUE TITLE
must have one register DataBase alias named `default`

### ISSUE THREAD

**Issue by loongshaw** [astaxie/beego#2429]
```
type User struct {
	Id          int   	`orm:"pk;auto"`
	Age         int16
	Name        string
}

func init() {
	orm.RegisterDriver("mysql", orm.DRMySQL)

	orm.RegisterModel(new(User))

	orm.RegisterDataBase("default", "mysql", "root:root@123.63.17.199:3306/test?charset=utf8")
}

func main() {
	o := orm.NewOrm()
	o.Using("default") 

	user := new(User)
	user.Age = 30
	user.Name = "slene"

	fmt.Println(o.Insert(&user))
}
```
如上代码，执行提示：

exit status 2
[ORM]2017/02/10 17:01:35 register db Ping `default`, default addr for network '123.63.17.199:3306' unknown
must have one register DataBase alias named `default`

**Comment by astaxie** [comment]
`user := new(User)` is already `*User`. and you still use `o.Insert(&user)`.

**Comment by ZetaChow** [comment]
你没有处理 orm.RegisterDataBase 的error，这个错误消息不一定是没有定义default导致，而是因为orm.RegisterDataBase返回错误，没有注册成功，导致没有发现命名为 default的数据库注册

**Comment by Ljfy** [comment]
怎么解决的

**Comment by iamwlb** [comment]
我也遇到这样的问题，请问怎么解决的？

**Comment by imrenagi** [comment]
why do you guys use Chinese language here?? -_-

**Comment by masjono** [comment]
I experience same thing. I solved the problem by changing connection string to: **"root:root@tcp(123.63.17.199:3306)/test?charset=utf8"**

Hope can help you all

**Comment by jabbawockeez** [comment]
> why do you guys use Chinese language here?? -_-

cause they suck, and you too

**Comment by JacksonTom** [comment]
...

**Comment by diegolovemetal** [comment]
> tcp(123.63.17.199:3306

thanx!

**Comment by wrick198** [comment]
import (
    "fmt"
    "github.com/astaxie/beego/orm"
    _ "github.com/go-sql-driver/mysql"
)

    err:=orm.RegisterDataBase(aliasName, driverName, dbUrl,maxIdle,maxConn)
    if err != nil {
        panic(err)
    }

注意导入和注意判断错误

**Comment by gionchat** [comment]
import (
	"github.com/astaxie/beego/orm"
    _ "github.com/go-sql-driver/mysql"
)
must import  _ "github.com/go-sql-driver/mysql"
