### ISSUE TITLE
How exclude filter ?

### ISSUE THREAD

**Issue by lwhhhh** [astaxie/beego#2434]
I using beego as API server.All API must through an authentication filter, except register and login API.

So I inserted filter like this:

    beego.InsertFilter("/*", beego.BeforeRouter, filter.AuthFilter, false, false)

and in my filter, I hope I can pass some API like this:

    if ctx.Request.RequestURI == "/login" && ctx.Request.Method == "POST" {
            // to login controller  
    }

    // verify below 

How to do this ?

**Comment by astaxie** [comment]
I suppose you have the follow router:

```
beego.Router("/login", &controlls.LoginController{})
beego.Router("/reg", &controlls.RegController{})
```

```
if (ctx.Request.RequestURI == "/login" && ctx.Request.Method == "POST") || 
     (ctx.Request.RequestURI == "/reg"){
      // just do nothing in the filter and complete the logic in controller
       return
}

// verify below 
```
