### ISSUE TITLE
sql: expected 3 destination arguments in Scan, not 1

### ISSUE THREAD

**Issue by loongshaw** [astaxie/beego#2438]
type User struct {
	Id          int
	Age         int16
	Name        string
}

....

var users []User
err := o.Raw("SELECT id, age, name FROM user WHERE enabled = ?",1).QueryRow(&users)
fmt.Println(err)

....
[ORM]2017/02/14 16:57:06  -[Queries/default] - [  OK /    db.Query /    19.8ms] - [SELECT id, age, name FROM user WHERE enabled = ?] - `1`
[]
sql: expected 3 destination arguments in Scan, not 1

**Comment by loongshaw** [comment]
hello, i have solved this issue, modified like following:
    var users [] User
    num,err := o.Raw("SELECT age, id, name FROM user WHERE enabled = ?",1).QueryRows(&users)
    fmt.Println(users)

QueryRows() method outputs two paras.

**Comment by ktsakas** [comment]
I tried this and the compiler complains that QueryRows is undefined.
