### ISSUE TITLE
Flash data doesn't working when assign big data

### ISSUE THREAD

**Issue by pajingko** [astaxie/beego#2439]
When I assing a big data to flash then Read It from Request 'beego.ReadFromRequest'.
I've got an empty data.

1. What version of Go and beego are you using (`bee version`)?
v1.6.2

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/goProjects"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dv/flmkxkzn5sq95vj5gb5q_xlm0000gn/T/go-build722001193=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
flash finally store the data in cookie. If you want to store the big data that maybe would reach to the cookie's limit

**Comment by pajingko** [comment]
Thank you so much. @astaxie
