### ISSUE TITLE
Go1.8 was released yesterday , Is beego support go1.8 ?

### ISSUE THREAD

**Issue by toplinuxsir** [astaxie/beego#2442]
Go1.8 was released yesterday , Is beego support go1.8 ?
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by sergeylanzman** [comment]
yes I use go1.8rc3 2 weeks,
