### ISSUE TITLE
this.input.get() not working beego

### ISSUE THREAD

**Issue by vijayks040** [astaxie/beego#2445]
Please answer these questions before submitting your issue. Thanks!

Beego     : 1.7.2
├── GoVersion : go1.7.4
├── GOOS      : linux
├── GOARCH    : amd64

    package main

    import (
    	"database/sql"

    	"flag"
    	"fmt"

    	"github.com/astaxie/beego"
    )

    type User struct {
    	username string
    	password string
    }type MainController struct {
    	beego.Controller
    }

    func (this *MainController) Post() {
    	this.Ctx.WriteString("hello world")
    	result := this.Input()
    	fmt.Println("eedwedwe", this.Input().Get("username"))
    	fmt.Println("input value is", result)
    	fmt.Println("eedwedwe", result.Get("Username"))
    	send := User{username: "vijay", password: "vk18"}
    	this.Data["json"] = &send
    	this.ServeJSON()
    }

    func main() {
    
    	beego.Router("/", &MainController{})
    	beego.Run()

    }

and request is as follows
curl -X POST http://localhost:8080/ -d '{"username" : "admin", "password":"admin"}'

after request has hit beego server i am trying to access username in the request but its showing empty

and the outpit is::

    2017/02/17 12:56:59 [I] [asm_amd64.s:2086] http server Running on http://:8080
    eedwedwe 
    input value is map[{"username" : "admin", "password":"admin"}:[]]
    eedwedwe

**Comment by ysqi** [comment]
hi , curl test error ,  the parame `-d` need `key`=`value`
e.g
```
curl -X POST http://localhost:8080/ -d username=admin
```

**Comment by vijayks040** [comment]
@ysqi,here i want to get the values of the json in this request i.e '{"username" : "admin", "password":"admin"}'

**Comment by ysqi** [comment]
you need unmarshal json data from request body , more see [here](https://beego.me/docs/mvc/controller/params.md#retrieving-data-from-request-body)
e.g:
```go
u := &user{}
err:= json.Unmarshal(this.Ctx.Input.RequestBody, u)
...
```
