### ISSUE TITLE
DB操作有没有考虑对sharding的支持

### ISSUE THREAD

**Issue by sniperdong** [astaxie/beego#2446]
很多场景都有分库分表需求，在使用beego过程中有以下不方便：
1.orm必须要设定default，这个约束完全没必要，而且有点儿画蛇添足；
2.分库可以通过Using实现，但是table在RegisterModel时就确定了没办法实现分表

**Comment by jinleileiking** [comment]
分库分表太定制化，建议做插件

**Comment by zjjott** [comment]
后面加atlas
专业的时期由专业的来。。

**Comment by zjjott** [comment]
事情

**Comment by zjjott** [comment]
后面加atlas
专业的事情由专业的来。。

**Comment by sniperdong** [comment]
嗯，如果引入代理的确可以。我想表达的是如果beego能提供实现分库分表的可能，也是一种选择

**Comment by zjjott** [comment]
让我想到了django的Database routers 
理论上应该可以，但是网络框架里的orm，做这件事情就太重了。。因为要做的事情太多了。。耦合问题也麻烦

**Comment by mengskysama** [comment]
https://github.com/Meituan-Dianping/DBProxy

**Comment by kerneltravel** [comment]
https://www.oschina.net/p/proxysql

**Comment by astaxie** [comment]
这个不在ORM的考虑之中
