### ISSUE TITLE
api开发时设置http status codes

### ISSUE THREAD

**Issue by Hkesd** [astaxie/beego#2454]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.7.2

2. What operating system and processor architecture are you using (`go env`)?
mac os

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

在开发api时，通过设置http状态码来表达restful格式api的操作状态
在使用beego时，没找到很好的方式来这样做
在Abort后 ，而是跳转到错误页面（可能是我的代码有问题，但我看文档真不知道怎么做到），api在此时应该也是返回一些数据而不是指向了错误页面
请问怎么做呢

**Comment by mengskysama** [comment]
func (c *ErrorController) Error400() {
	// Don't Output and string
}

func (c *BaseController) parma2Int(value string, abort bool) (int, error) {
	r, err := strconv.Atoi(value)
	if err != nil {
		if abort {
			result := map[string]interface{}{
				"errcode": 400,
				"errmsg":  "Value " + value + " is not integer.",
				"data":    nil,
			}
			c.Data["json"] = result
			c.ServeJSON()
			c.Ctx.Abort(400, "400")
		}
		return 0, errors.New("Value " + value + " is not integer.")
	}
	return r, nil
}

**Comment by zjjott** [comment]
```
c.Ctx.Output.SetStatus(400)
c.ServeJSON()
return
```
SetStatus要在ServeJSON之前，因为后者会读取ctx中已经被设置的状态码

**Comment by Hkesd** [comment]
谢谢 
// 设置http状态码 没有做限制
func (base *BaseController) SetHttpStatusCode(code int)  {
	base.Ctx.ResponseWriter.WriteHeader(code)
}

我是这样做的 在基类封装了一下
p.SetHttpStatusCode(403) 
使用的时候这样的
