### ISSUE TITLE
beego retrive http get paramters

### ISSUE THREAD

**Issue by wangping886** [astaxie/beego#2456]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

        beego 1.7  go 1.7
2. What operating system and processor architecture are you using (`go env`)?

        mac
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```go
func (c *DomainManageController) DeleteRecords() {
	//http://192.168.110.178:2080/api/config/deleteRecords?id=1&ol[0]=A&ol[1]=B
	ol := make([]string, 0)
	if err := c.Ctx.Input.Bind(&ol, "ol"); err != nil {
		fmt.Println(err)
	}
	 var id string
	 c.Ctx.Input.Bind(&id, "id")
	 fmt.Println(ol, id) // //ol:[]  id:1
	 c.WriteOK(ol)
}
```

4. What did you expect to see?
//ol:[A,B]  id:1

5. What did you see instead?
//ol:[]  id:1

**Comment by wangping886** [comment]
func (c *DomainManageController) DeleteRecords() {
	//http://192.168.110.178:2080/api/config/deleteRecords?id=1&ol[0]=0&ol[1]=2
	ol := make([]string, 0)
	if err := c.Ctx.Input.Bind(&ol, "ol"); err != nil {
		fmt.Println(err)
	}
	var id string
	c.Ctx.Input.Bind(&id, "id")
	fmt.Println(ol, id) // []  1
	c.WriteOK(ol)
}

**Comment by ysqi** [comment]
@wangping886  this is a bug , bind slice function not check parse form , you can change the code order to reproduce .e.g
```go
func (u *DomainManageController) DeleteRecords() { 
	var id string
	u.Ctx.Input.Bind(&id, "id")

	ol := make([]int, 0, 2)
	if err := u.Ctx.Input.Bind(&ol, "ol"); err != nil {
		u.Data["json"] = "bind failed," + err.Error()
		u.ServeJSON()
		return
	}

	u.Data["json"] = fmt.Sprintf("your input params: o1=%v,id=%s", ol, id)
	u.ServeJSON()
}
```

**Comment by wangping886** [comment]
in my opinion,there is no difference  between your anwser and my . 
  this is just a 'get' request :curl deleteRecords?id=1&ol[0]=A&ol[1]=B

**Comment by ysqi** [comment]
Beego解析时的一个错误，并没有检查Form是否有Parse， 你的代码能重现问题，我的代码能佐证这个Bug。我们的代码是不一样的，我是先解析 id,再 ol, 而你的是 ol,再 id。在我的示例中通过现解析id这样便会触发 parse from 动作，从而可以在解析ol时便有form数据供其解析。

这是Beego的一个bug需要修复。

**Comment by wangping886** [comment]
按你说的先解析id  再解析ol也解析不到数组。  难道是我beego1.7不支持吗？

**Comment by wangping886** [comment]
按你说的真的可以了。 谢谢！

**Comment by wangping886** [comment]
我还有个问题：控制台curl 
localhost:~ ping$ curl http://192.168.110.178:2080/api/config/deleteRecords?id=1&ol[0]=0&ol[1]=2
[1] 15274
[2] 15275
localhost:~ ping$ "your input params: o1=[],id=1"  //未解析  不报错 
把参数顺序变化后  上面id在ol前  下面id在ol后
localhost:~ ping$ curl http://192.168.110.178:2080/api/config/deleteRecords?ol[0]=0&ol[1]=2&id=1
[1] 15277
[2] 15278
[2]+  Done                    ol[1]=2
localhost:~ ping$ curl: (3) [globbing] bad range in column 57  //报错
但是在postman中请求
localhost:~ ping$ curl http://192.168.110.178:2080/api/config/deleteRecords?id=1&ol[0]=0&ol[1]=2
localhost:~ ping$ curl http://192.168.110.178:2080/api/config/deleteRecords?ol[0]=0&ol[1]=2&id=1
没有区别且正常解析"your input params: o1=[1 2],id=1"
我想知道这是为什么。虽然貌似和beego无关

**Comment by wangping886** [comment]
照你所说，如果我只传一个数组，那就悲剧了～

**Comment by astaxie** [comment]
@wangping886 下次解决了麻烦关闭一下issue

**Comment by wangping886** [comment]
@astaxie   最近才加入github，一些github的流程还不是很熟悉，谢谢您的提醒。

**Comment by astaxie** [comment]
@wangping886 没关系，慢慢就熟悉了，欢迎来到开源的世界。:smile:
