### ISSUE TITLE
Use with go-bindata

### ISSUE THREAD

**Issue by Raggaer** [astaxie/beego#2457]
Is it possible to use https://github.com/jteeuwen/go-bindata for the `views` folder?

Since beego loads them at startup I cant see how can I add my custom loading function for templates

Thanks

**Comment by ysqi** [comment]
hi @Raggaer ,beego parse html template with file data `ioutil.ReadFile(fileAbsPath)`, can't use go-bindata to get file content. maybe you can try with `AddTemplateEngine` function,
```go
type templatePreProcessor func(root, path string, funcs template.FuncMap) (*template.Template, error)
func AddTemplateEngine(extension string, fn templatePreProcessor) *App {}
```
but you must do more things.

**Comment by Raggaer** [comment]
Thanks this might work for my case
