### ISSUE TITLE
Zero downtime deploy

### ISSUE THREAD

**Issue by araufdogan** [astaxie/beego#2458]
Hello, how can i deploy my updates with zero downtime using beego?

I found https://github.com/fvbock/endless repo but i need to make changes beego's ListenAndServe to use /fvblock/endless.

Does anyone know another way or did something like that?

ps. I am using websockets in beego app.

**Comment by bakanis** [comment]
You might run 2 instances of beego app behind a proxy, eg. nginx. Then you take down one instance, update an app and take it up. Repeat the process with the other instance.
