### ISSUE TITLE
怎么在启动的时候对controller中的Data值插入一些默认值，便于页面渲染时直接使用

### ISSUE THREAD

**Issue by xurwxj** [astaxie/beego#2460]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.2
├── GoVersion : go1.8

2. What operating system and processor architecture are you using (`go env`)?
darwin

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
希望在启动的时候设置一些全局值，每个路由在请求的时候可以在页面渲染时直接使用

5. What did you see instead?

**Comment by ysqi** [comment]
你可以定义全局模板函数，而不必在Controller中注入，而是在模板中，随需要而获取全局值。
you can register a template function for get global value.
 e.g
```go

var content=`
<html>
	<title>{{global "title"}}</title>
	<body>
		<h1>{{global "site"}}</h1>
	</body>
</html>
`

var globalValues = map[string]interface{}{
	"site":  "yushuangqi.com",
	"title": "my blog",
}

func init() {
	beego.AddFuncMap("global", func(item string)interface{} {
	      return globalValues[item]
        })
}
```

**Comment by xurwxj** [comment]
谢谢
