### ISSUE TITLE
怎么获取当前的运行模式

### ISSUE THREAD

**Issue by xurwxj** [astaxie/beego#2462]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     :1.7.2
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
beego.BConfig.RunMode获取的是配置文件里的，如果配置文件里是dev，而bee run -runmode=prod
用beego.BConfig.RunMode只能获取到配置文件里的dev
4. What did you expect to see?

怎么获取当前真实运行的模式
5. What did you see instead?

**Comment by astaxie** [comment]
`bee run -runmode`会设置一个环境变量`BEEGO_RUNMODE`, 而这个环境变量也是会最后设置到BConfig.RunMode https://github.com/astaxie/beego/blob/master/config.go#L261-L265

**Comment by xurwxj** [comment]
这段代码我看了，但现实是我在bee run 的时候，-runmode设置了prod，配置文件里的runmode是dev，用beego.BConfig.RunMode取的时候并不是prod，而是dev

**Comment by NewbMiao** [comment]
when set:
beego.AppConfig.set("runmode","prod")
beego.BConfig.RunMode get [dev]

when set:
beego.BConfig.RunMode="prod"
beego.AppConfig.string("runmode")  get [prod]

It's comfused me!!!
