### ISSUE TITLE
怎么在模板func中获取用户当前请求的url

### ISSUE THREAD

**Issue by xurwxj** [astaxie/beego#2463]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

最新的
2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
func URLMatch(endpoint string, values ...interface{}) string {
	var targetUrl = beego.BeeApp.Handlers.URLFor(endpoint, values...)
	fmt.Println(targetUrl)
// hope to get current url that user requested
	// fmt.Println(beego.Ctx.Request.RequestURI)
	if targetUrl == "/index.html" {
		return "active"
	}
	return ""
}
```
4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
https://godoc.org/github.com/astaxie/beego/context#BeegoInput.URL

**Comment by xurwxj** [comment]
context.BeegoInput.URL在模板func中获取的话，编译无法通过

**Comment by kxdmichael** [comment]
我也遇到了这个问题，请问解决了吗
