### ISSUE TITLE
Ssdb cache bug

### ISSUE THREAD

**Issue by antony66** [astaxie/beego#2467]
I use latest stable beego and golang as well as ssdb for caching purposes. The following code sometimes gives an error:

    if Cache.IsExist(cacheKeyFor(domain)) {

and error is:

```
2017/02/27 06:20:38 [C] [asm_amd64.s:479] Handler crashed with error runtime error: index out of range
...
2017/02/27 06:20:38 [C] [asm_amd64.s:479] /home/ak/go/src/github.com/astaxie/beego/cache/ssdb/ssdb.go:155
...
```

It happens not every time ofcourse but still a few times a day on our production server. I think the problem is that sometimes ssdb returns something wrong and it needs to be handled properly in beego code.

**Comment by astaxie** [comment]
Thanks
