### ISSUE TITLE
cannot connect the database when  used with pgbouncer

### ISSUE THREAD

**Issue by msean** [astaxie/beego#2471]
Go version:1.8
beego version:1.7.2

Before I use pgbouncer,It connect normally,but I just modify the default port(6543) that pgbouncer used,It occur error:
`[ORM]2017/02/28 14:04:01 register db Ping `default`, pq: Unsupported startup parameter: extra_float_digits
must have one register DataBase alias named `default``

I can connect with the db on Navicat used with the port(6543).

**Comment by astaxie** [comment]
is this the pg driver issue?

**Comment by msean** [comment]
It can connect the database(port 6543),use the code below
```
import (
	"database/sql"
	_ "github.com/lib/pq"
	"fmt"
)

func main() {
	db,err := sql.Open("postgres", "postgres://***:***@192.168.1.170:6543/***?sslmode=disable")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("here",db)
}

```

**Comment by astaxie** [comment]
So are you use the same connection string for the ORM?

**Comment by msean** [comment]
Sorry for that it is not the lib that cause the error. The problem had been solved.
http://lists.pgfoundry.org/pipermail/pgbouncer-general/2008-November/000301.html
It should set `ignore_startup_parameters = extra_float_digits`  in the pgbouncer cofige file....
