### ISSUE TITLE
this.data 全局使用

### ISSUE THREAD

**Issue by Insofan** [astaxie/beego#2475]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go 1.7
beego 1.6.2

2. What operating system and processor architecture are you using (`go env`)?
windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
让this.data["aaa"]可以全局使用

4. What did you expect to see?

5. What did you see instead?

**Comment by xurwxj** [comment]
create a base controller and all other controller inherit it.
