### ISSUE TITLE
主页简介优化建议

### ISSUE THREAD

**Issue by TJRoger** [astaxie/beego#2477]
https://beego.me/ 

> 一个使用 Go 的思维来帮助您构建并开发 Go 应用程序的开源框架

第一眼看成了
一个使用 Go 的思维来帮助您构建并<i><s>_开_</s></i>发 Go 应用程序的开源框架

建议改成顿号或其他介词

**Comment by ysqi** [comment]
TJRoger 可以将建议提交至：https://github.com/beego/beedoc ，这里用于构建官网。
