### ISSUE TITLE
ORM数据库连接池是否支持自动重连？

### ISSUE THREAD

**Issue by nh-live** [astaxie/beego#2483]
ORM数据库连接池是否支持自动重连？

**Comment by astaxie** [comment]
ORM内部用的是database/sql内部的连接池.

The sql package creates and frees connections automatically; it also maintains a free pool of idle connections. If the database has a concept of per-connection state, such state can only be reliably observed within a transaction. Once DB.Begin is called, the returned Tx is bound to a single connection. Once Commit or Rollback is called on the transaction, that transaction's connection is returned to DB's idle connection pool. The pool size can be controlled with SetMaxIdleConns.
