### ISSUE TITLE
About panic and rollback

### ISSUE THREAD

**Issue by alicksnake22** [astaxie/beego#2484]
在每个controller里面我会主动catch错误并且回滚事务，但是一旦有panic而又没有处理，会导致事务无法回滚。目前是否提供controller级别的panic处理？还是说只能在每一个controller method里面进行panic处理？谢谢

**Comment by astaxie** [comment]
panic的原理是一层一层的往上传递，如果你自己有事务在controller里面处理，那么你就需要在controller的method里面自己去catch这个panic，然后回滚

**Comment by alicksnake22** [comment]
好的，谢谢
