### ISSUE TITLE
beego安装不了

### ISSUE THREAD

**Issue by kosmosCosmos** [astaxie/beego#2486]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.8  beego 最新版本？

2. What operating system and processor architecture are you using (`go env`)?
 Ubuntu 14.04.5 LTS  64位

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

root@XXX:/usr/Gopath/src/github.com# go get github.com/astaxie/beego
# github.com/astaxie/beego/utils
astaxie/beego/utils/mail.go:407:20: error: reference to undefined identifier ‘sync.Pool’
 var bufPool = sync.Pool{
                    ^
astaxie/beego/utils/mail.go:407:24: error: expected ‘;’ or newline after top level declaration
 var bufPool = sync.Pool{
                        ^
astaxie/beego/utils/mail.go:410:2: error: expected declaration
  },
  ^
# github.com/astaxie/beego/logs
astaxie/beego/logs/log.go:139:17: error: reference to undefined identifier ‘sync.Pool’
 var logMsgPool *sync.Pool
                 ^
astaxie/beego/logs/log.go:169:21: error: reference to undefined identifier ‘sync.Pool’
  logMsgPool = &sync.Pool{
                     ^
astaxie/beego/logs/log.go:169:25: error: expected ‘;’ or ‘}’ or newline
  logMsgPool = &sync.Pool{
                         ^
astaxie/beego/logs/log.go:170:27: error: expected ‘;’ or newline after top level declaration
   New: func() interface{} {
                           ^
astaxie/beego/logs/log.go:172:3: error: expected declaration
   },
   ^
astaxie/beego/logs/log.go:174:2: error: expected declaration
  bl.wg.Add(1)
  ^
astaxie/beego/logs/log.go:175:2: error: expected declaration
  go bl.startLogger()
  ^
astaxie/beego/logs/log.go:176:2: error: expected declaration
  return bl
  ^
astaxie/beego/logs/log.go:177:1: error: expected declaration
 }
 ^
astaxie/beego/logs/log.go:170:25: error: missing return at end of function
   New: func() interface{} {

4. What did you expect to see?
能够完整的装完
5. What did you see instead?
安装报如3的错误

**Comment by astaxie** [comment]
please update your Go version
