### ISSUE TITLE
AddViewPath panics when beego.TestBeegoInit called twice

### ISSUE THREAD

**Issue by eyalpost** [astaxie/beego#2488]
I don't think it's good practice to call TestBeegoInit twice, but if it does happen we need to decide how best to handle it. I can make a pull request to fix this, and see two options:
1. Don't panic if a viewPath is added that already exists (This will allow TestBeegoInit to be called multiple times)
2. panic if TestBeegoInit is called more than once but with a proper error message (Currently the message is "Can not add new view paths after beego.Run()"

What do you think?

**Comment by astaxie** [comment]
As the viewPath is map, so if we consider the concurrence access map would be a safe problem. Panic maybe is not good. But I have no good idea on it now.

**Comment by eyalpost** [comment]
I don't think it's worth supporting adding viewpaths while the app is running so I won't get the concurrent map way.
Regardless of ViewPath, Do you think it's worth adding panic() if TestBeegoInit is called more than once?

**Comment by eyalpost** [comment]
#2496
