### ISSUE TITLE
postgres "must have one register DataBase alias named `default`"

### ISSUE THREAD

**Issue by makseli** [astaxie/beego#2489]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.2
├── GoVersion : go1.6.2
├── GOOS      : linux ( xubuntu )
├── GOARCH    : amd64

import (
    "fmt"
	"github.com/astaxie/beego"
    _ "github.com/lib/pq"
    "github.com/astaxie/beego/orm"
	//"errors"
)
type Licenses struct {
    Id   int
    Guid string
	License_id string
}

func init() {
	orm.RegisterDriver("postgres", orm.DRPostgres)
	orm.RegisterModel(new(Licenses))
	orm.RegisterDataBase("default", "postgres", "postgres://user:pass@ccc:5432/dbname?sslmode=verify-full")
}

func (c *TempPController) Get() {

    o := orm.NewOrm()
    o.Using("default") // Using default, you can use other database

		ilk := new(Licenses)
		ilk.Guid = "asdassssssss"
		ilk.License_id = "ssssd3"

		fmt.Println(o.Insert(ilk))

		fmt.Println(ilk.Id)
		fmt.Println(ilk.Guid)
		fmt.Println(ilk.License_id)
    	c.Data["json"] = o
}

and 

2017/03/09 06:32:41 INFO     ▶ 0219 Restarting 'tempAuth'...
2017/03/09 06:32:41 SUCCESS  ▶ 0220 './tempAuth' is running...
[ORM]2017/03/09 06:32:41 register db Ping `default`, pq: SSL is not enabled on the server
2017/03/09 06:32:41 [I] [parser.go:91] generate router from comments
2017/03/09 06:32:41 [I] [parser.go:91] generate router from comments
2017/03/09 06:32:41 [I] [asm_amd64.s:1998] http server Running on http://:3434
must have one register DataBase alias named `default`

what is wrong ? thanks.

**Comment by lifei6671** [comment]
```
register db Ping default, pq: SSL is not enabled on the server
```
`default` register failure。

**Comment by makseli** [comment]
thx @lifei6671. now "?sslmode=disable" with ok. 
BUT;
I thought this was the information line. I did not think it was ERROR. Can we give a detailed description of the error here? @astaxie
