### ISSUE TITLE
Redirect response with content in the body.

### ISSUE THREAD

**Issue by l0n3r4n83r** [astaxie/beego#2492]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.2
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/<username>/go-code
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 10 Mar 2017

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
```golang
cc.Ctx.Output.Json(token, true, true)
cc.Ctx.Redirect(302, redirectURI)
```

4. What did you expect to see?
Redirect to redirectURI with token in the response body.

5. What did you see instead?
Redirect does not happen and I see below in console.
`http: multiple response.WriteHeader`

**Comment by astaxie** [comment]
This logic code doesn't make sense. You want to output JSON and redirect. That's conflict.

**Comment by l0n3r4n83r** [comment]
I need to pass the token as URL param in the redirect I am trying to implement implicit grant type for oauth. We can either delete or close this issue.

**Comment by astaxie** [comment]
If you want to pass the implicit param, maybe cookie is a choice.
