### ISSUE TITLE
这个框架支持IOC么

### ISSUE THREAD

**Issue by flashmouse** [astaxie/beego#2503]
controller应该是一个请求生成一次的，那我应该怎样初始化controller里会引用到的一些实例和对象？
比如beego是否支持依赖注入？ 如果没有的话一般是怎么解决这个问题的？
我习惯在controller里放一坨有很多逻辑函数的对象，如果没有依赖注入，我觉得我要不会写代码了← ←
谢谢

**Comment by gloomyzerg** [comment]
定义一个 baseController 比如:
```
type BaseController struct {
	beego.Controller
	loginUser *LoginUser
	isLogin   bool
        ......
}
```
在baseController中的 `Prepare()`方法中初始化你想要的实例
我是这么做的

**Comment by zjjott** [comment]
> controller应该是一个请求生成一次的，那我应该怎样初始化controller里会引用到的一些实例和对象？

控制器方法Init或Prepare

> beego是否支持依赖注入？ 如果没有的话一般是怎么解决这个问题的？我习惯在controller里放一坨有很多逻辑函数的对象，如果没有依赖注入，我觉得我要不会写代码了← ←

设计模式不是这样滥用的
可以写一个控制器的基类，或者直接初始化对应的对象放在c.Data里即可

**Comment by flashmouse** [comment]
虽然感谢你的回复，不过我对你说的“”滥用“一词表示无语。
如果给一个http框架加上ioc功能是滥用的话，你就是在和一大坨java ee工程师宣战咯。

**Comment by zjjott** [comment]
我指的是你说的

> 如果没有依赖注入，我觉得我要不会写代码了

并无敌意

**Comment by clia** [comment]
Go里面Service之间不能直接互调，比如A服务调用B服务里面的方法，B服务又调用A服务里面的方法，会引起循环依赖报错，看一些最佳实践指出，要把这些方法都抽到一个公共的接口包里面去，然后使用依赖注入来操作，Beego里面对这样的依赖注入有没有提供支持呢？
