### ISSUE TITLE
Mysql Session Not working

### ISSUE THREAD

**Issue by veenutanwar** [astaxie/beego#2504]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8

2. What operating system and processor architecture are you using (`go env`)?
Windows 110

3. What did you do? Upgrade to 1.8
 
 Sesseion "File" work but Mysql not working Handler crashed with error interface conversion: interface {} is nil, not string
Session Db not updating data giving only sessionId

thanks

Manish

**Comment by astaxie** [comment]
1. check your mysql connection is correct. 
2. check there's data in mysql with the sessionid

**Comment by veenutanwar** [comment]
after upgrade of 1.8 it happend otherwise mysql work super fine.

**Comment by veenutanwar** [comment]
After removing  defer st.c.Close() in sess_mysql.go work fine

**Comment by astaxie** [comment]
@veenutanwar that's really weird. Let me reproduce it later

**Comment by astaxie** [comment]
fix in beego1.8.1
