### ISSUE TITLE
NewOrmWithDB cause panic: time: missing Location in call to Time.In

### ISSUE THREAD

**Issue by tedli** [astaxie/beego#2515]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee v1.6.2
Beego 1.7.2
GoVersion go1.8

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```golang
o, err = orm.NewOrmWithDB("postgres", "default", GetSqlDB())
count, err = o.QueryTable(new(LynisReport)).Filter(constraint, value).OrderBy("-scanned_at").All(&result);
```

4. What did you expect to see?
no panic like this `panic: time: missing Location in call to Time.In`

5. What did you see instead?
in `func NewOrmWithDB(driverName, aliasName string, db *sql.DB) (Ormer, error)` I added two lines.
```golang
al.Name = aliasName
al.DriverName = driverName
al.DB = db  // here

detectTZ(al)  // and here

o := new(orm)
o.alias = al
```
then no panic

**Comment by tedli** [comment]
I use NewOrmWithDB because I want to reuse a db connection object. I find out that by using
```golang
orm.AddAliasWthDB(DatabaseAlias, "postgres", db)
orm.SetDataBaseTZ(DatabaseAlias, tz)
o := orm.NewOrm()
o.Using(DatabaseAlias)
o.QueryTable(new(LynisReport)).Filter(constraint, value).OrderBy("-scanned_at").All(&result)
```
the panic could be avoid.

**Comment by MahaoAlex** [comment]
@tedli  But the `DatabaseAlias` should be unique in `dataBaseCache`. How did you deal with that?

**Comment by tedli** [comment]
@MahaoAlex The database aliases are indeed unique. The code I've posted is just pseudocode.


In my case, I have to use both mysql and postgres for some reason. The mysql is the `default` that is straightforward just like the beego orm tutorial, then I need to alias the postgres one, the `orm.AddAliasWthDB(DatabaseAlias, "postgres", db)` actually was `orm.AddAliasWthDB("someExpressiveName", "postgres", db)`，I use `DatabaseAlias` to indicate that it can be any string and it's better to define a constant then `o.Using("someExpressiveName")` can use that constant.
