### ISSUE TITLE
auth.Basic second login problem 

### ISSUE THREAD

**Issue by andarm** [astaxie/beego#2519]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
  go  version 1.6,  beego version 1.5  

2. What operating system and processor architecture are you using (`go env`)?

    window
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
main.go ##
	username := beego.AppConfig.String("username")
	password := beego.AppConfig.String("password")

	beego.InsertFilter("*", beego.BeforeRouter , auth.Basic(username, password))
change_usr.go ##
       	username := beego.AppConfig.String("username")
	password := beego.AppConfig.String("password")

	beego.InsertFilter("*", beego.BeforeRouter , auth.Basic(username, password))
       
4. What did you expect to see?

       donot need restart web server ,  login in web by changed password
5. What did you see instead?

**Comment by astaxie** [comment]
From what you said, I can't get it. I guess you want to don't restart the server after change the username and password. But I don't know where did you change the username and password and how did you change that? did you save it to config?

**Comment by andarm** [comment]
yes，
    1.save it to config...
    2.write to new view just change password 
    3. I donot want to kill web task , how the password make sense.
