### ISSUE TITLE
与umeditor整合时遇到的问题

### ISSUE THREAD

**Issue by leozim** [astaxie/beego#2521]
beego的版本是1.8.0
beego端，上传成功后
c.Data["json"] = map[string]interface{}{"originalName": h.Filename, "url": URL, "size": fileSize, "type": ext, "state": "SUCCESS"}
c.ServeJSON()
上传结束后返回json字符串，使用chrome审核元素，返回的json是正常的
可是umeditor的上传成功返回的json是这样的
\<pre style="word-wrap: break-word; white-space: pre-wrap;"\>{
  "originalName": "1.jpg",
  "size": 136971,
  "state": "SUCCESS",
  "type": ".jpg",
  "url": "/static/upload/ueditor/1490106935.jpg"
}<\/pre\>
外面多了Pre的标签
具体是在umeditor/dialogs/image/image.js第185行uploadComplete: function(r){}
我又返回去使用了一下PHP版的umeditor，image.js第185行uploadComplete: function(r){}，这里的r是正常的json
这个要怎么解决？

**Comment by astaxie** [comment]
```
<pre style="word-wrap: break-word; white-space: pre-wrap;">
```
这个看上去是浏览器加上去的。你在chrome里面看看network里面的请求返回的response信息。

**Comment by leozim** [comment]
@astaxie  我用chrome查看network中的response，返回的json是正常的
可是js那边我打印返回值的时候，有pre标签
我对比了golang实现的和他们官方提供的PHP版本
golang返回的json，是格式化以后的，PHP版的，没有格式化
是不是这个原因呢？

**Comment by leozim** [comment]
@astaxie 用其他语音后台的我发现很多人都遇到这种问题，应该是跟beego无关了，我了解一下看看怎么解决

**Comment by astaxie** [comment]
如果你怀疑是格式化了JSON引起的，你还可以试试`c.Ctx.Output.Json(data interface{}, hasIndent bool, coding bool)`

**Comment by leozim** [comment]
@astaxie ,谢谢你，我回去试试

**Comment by astaxie** [comment]
那我先把这个issue关闭了哈，如果有测试出来效果记得更新一下issue

**Comment by leozim** [comment]
@astaxie ,我并没有找到什么特别好的方案，我最后的方案是在js端处理了一下
jQuery.parseJSON(jQuery(r).text());

**Comment by lcp0578** [comment]
umeditor的bug，只能去掉pre标签

**Comment by sinfey69** [comment]
var r = this.contentWindow.document.body.innerHtml;
改为 
var r = this.contentWindow.document.body.innerText;
