### ISSUE TITLE
swagger is not working properly for beego api

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2524]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : 1.7.2
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Friday, 24 Mar 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I created a beego api and run it as 
`bee run -downdoc=true -gendoc=true.`
But in the generated swagger i cant  see any   model definition for the default object model.I havent changed anything.
![swagger](https://cloud.githubusercontent.com/assets/22511293/24282151/bd316fa6-1098-11e7-8231-870c5ec86445.JPG)

4. What did you expect to see?
I would like to see the model of the object.
Thanks.

5. What did you see instead?
Empty model

**Comment by astaxie** [comment]
please update bee to the lastest version. There's an issue in bee in window. Thanks

**Comment by RajeshKumar1990** [comment]
Thanks for your quick reply.
Is there any other latest bee version available after bee v1.6.2.
I could not find in the tags .I even reinstalled the bee.Still the same problem...
Thanks.

**Comment by astaxie** [comment]
you need update the bee with `-u`

```
go get -u github.com/beego/bee

```

**Comment by RajeshKumar1990** [comment]
still i face the same problem...
Thanks.

**Comment by RajeshKumar1990** [comment]
still facing the same problem..
Thanks

**Comment by astaxie** [comment]
> Still facing the same problem..

still use the old bee?

**Comment by sergeylanzman** [comment]
please share your model and controller comments.

**Comment by RajeshKumar1990** [comment]
Model:
```
type Object struct {
	ObjectId   string
	Score      int64
	PlayerName string
}
```
Controller:

// Operations about object
type ObjectController struct {
	beego.Controller
}

```
// @Title Create
// @Description create object
// @Param	body		body 	models.Object	true		"The object content"
// @Success 200 {string} models.Object.Id
// @Failure 403 body is empty
// @router / [post]
func (o *ObjectController) Post() {
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)
	objectid := models.AddOne(ob)
	o.Data["json"] = map[string]string{"ObjectId": objectid}
	o.ServeJSON()
}

// @Title Get
// @Description find object by objectid
// @Param	objectId		path 	string	true		"the objectid you want to get"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [get]
func (o *ObjectController) Get() {
	objectId := o.Ctx.Input.Param(":objectId")
	if objectId != "" {
		ob, err := models.GetOne(objectId)
		if err != nil {
			o.Data["json"] = err.Error()
		} else {
			o.Data["json"] = ob
		}
	}
	o.ServeJSON()
}

// @Title GetAll
// @Description get all objects
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router / [get]
func (o *ObjectController) GetAll() {
	obs := models.GetAll()
	o.Data["json"] = obs
	o.ServeJSON()
}

// @Title Update
// @Description update the object
// @Param	objectId		path 	string	true		"The objectid you want to update"
// @Param	body		body 	models.Object	true		"The body"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [put]
func (o *ObjectController) Put() {
	objectId := o.Ctx.Input.Param(":objectId")
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)

	err := models.Update(objectId, ob.Score)
	if err != nil {
		o.Data["json"] = err.Error()
	} else {
		o.Data["json"] = "update success!"
	}
	o.ServeJSON()
}

// @Title Delete
// @Description delete the object
// @Param	objectId		path 	string	true		"The objectId you want to delete"
// @Success 200 {string} delete success!
// @Failure 403 objectId is empty
// @router /:objectId [delete]
func (o *ObjectController) Delete() {
	objectId := o.Ctx.Input.Param(":objectId")
	models.Delete(objectId)
	o.Data["json"] = "delete success!"
	o.ServeJSON()
}
```
This is the default model created when i create an api....
Thanks...

**Comment by RajeshKumar1990** [comment]
My current bee version is as follows 
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1

├── Beego     : 1.7.2
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Saturday, 25 Mar 2017

Model:
```
type Object struct {
	ObjectId   string
	Score      int64
	PlayerName string
}
```
Controller
```
// Operations about object
type ObjectController struct {
	beego.Controller
}

// @Title Create
// @Description create object
// @Param	body		body 	models.Object	true		"The object content"
// @Success 200 {string} models.Object.Id
// @Failure 403 body is empty
// @router / [post]
func (o *ObjectController) Post() {
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)
	objectid := models.AddOne(ob)
	o.Data["json"] = map[string]string{"ObjectId": objectid}
	o.ServeJSON()
}

// @Title Get
// @Description find object by objectid
// @Param	objectId		path 	string	true		"the objectid you want to get"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [get]
func (o *ObjectController) Get() {
	objectId := o.Ctx.Input.Param(":objectId")
	if objectId != "" {
		ob, err := models.GetOne(objectId)
		if err != nil {
			o.Data["json"] = err.Error()
		} else {
			o.Data["json"] = ob
		}
	}
	o.ServeJSON()
}

// @Title GetAll
// @Description get all objects
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router / [get]
func (o *ObjectController) GetAll() {
	obs := models.GetAll()
	o.Data["json"] = obs
	o.ServeJSON()
}

// @Title Update
// @Description update the object
// @Param	objectId		path 	string	true		"The objectid you want to update"
// @Param	body		body 	models.Object	true		"The body"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [put]
func (o *ObjectController) Put() {
	objectId := o.Ctx.Input.Param(":objectId")
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)

	err := models.Update(objectId, ob.Score)
	if err != nil {
		o.Data["json"] = err.Error()
	} else {
		o.Data["json"] = "update success!"
	}
	o.ServeJSON()
}

// @Title Delete
// @Description delete the object
// @Param	objectId		path 	string	true		"The objectId you want to delete"
// @Success 200 {string} delete success!
// @Failure 403 objectId is empty
// @router /:objectId [delete]
func (o *ObjectController) Delete() {
	objectId := o.Ctx.Input.Param(":objectId")
	models.Delete(objectId)
	o.Data["json"] = "delete success!"
	o.ServeJSON()
}

```
Thanks...

**Comment by RajeshKumar1990** [comment]
Appreciate any help.Thanks.....

**Comment by har07** [comment]
The same happened here even using the latest beego and bee tools version in Windows 10 : 

		λ bee version
		______
		| ___ \
		| |_/ /  ___   ___
		| ___ \ / _ \ / _ \
		| |_/ /|  __/|  __/
		\____/  \___| \___| v1.8.2

		├── Beego     : 1.8.0
		├── GoVersion : go1.8
		├── GOOS      : windows
		├── GOARCH    : amd64
		├── NumCPU    : 8
		├── GOPATH    : D:\GoWorkspace
		├── GOROOT    : C:\Go\
		├── Compiler  : gc
		└── Date      : Monday, 24 Apr 2017

**Comment by astaxie** [comment]
please update to bee 1.8.3. I fixed the issue for windows. The windows Separator always cause many problems.
