### ISSUE TITLE
result of c.Ctx.Request.Form["key"] should equal to c.Ctx.Request.PostForm["key"]

### ISSUE THREAD

**Issue by printfcoder** [astaxie/beego#2527]
when a request posted through form-data/x-www-form-urlencoded or other similar , both of then work ok, but post through url like "url?key=999", only c.Ctx.Request.Form["key"] works.

when url posted like "url?key=999"
v, ok := c.Ctx.Request.Form["key"] 
v=999,ok=true
v, ok = c.Ctx.Request.PostForm["key"]
v="",ok=false

**Comment by zjjott** [comment]
understand this point: `PostForm` is about HTTP request body,`Form` is about body and url
you can see doc in `net/http`:
```golang
// Form contains the parsed form data, including both the URL
	// field's query parameters and the POST or PUT form data.
	// This field is only available after ParseForm is called.
	// The HTTP client ignores Form and uses Body instead.
	Form url.Values

	// PostForm contains the parsed form data from POST, PATCH,
	// or PUT body parameters.
	//
	// This field is only available after ParseForm is called.
	// The HTTP client ignores PostForm and uses Body instead.
	PostForm url.Values
```

**Comment by printfcoder** [comment]
Yes, you are right. thx
