### ISSUE TITLE
How to achieve an increase of HTTP header in the swagger document?

### ISSUE THREAD

**Issue by SchindlerWang** [astaxie/beego#2528]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.0

├── Beego     : 1.8.0
├── GoVersion : go1.6.3
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/schindler/Workspace/Go/
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 24 Mar 2017

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/schindler/Workspace/Go/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I want to achieve the effect similar to the following by the swagger ui：
curl --request GET \
  --url http://127.0.0.1:8080/path_to_your_api \
  --header 'authorization: Bearer token'

4. What did you expect to see?
I except to add http headers in the swagger ui.

5. What did you see instead?
I don't know how to add http headers by the automated API document in the swagger ui.

**Comment by zjjott** [comment]
using `@Param`
https://beego.me/docs/advantage/docs.md
```go
// @Param   authorization     header   string false "Bearer token"   "Auth infomation"
```
