### ISSUE TITLE
使用内置session存储到mysql引擎新版本的sess_mysql.go有问题

### ISSUE THREAD

**Issue by jiangyd** [astaxie/beego#2538]
最新版本的session存储到mysql引擎有问题，观察mysql的执行日志，发现根本就没有执行update session的操作，老版本的是正常的，新版本的多了个defer st.c.Close(),老版本的没有这个就是可以的

session_key，session_expiry都是有内容的，但是session_data没有内容

**Comment by zjjott** [comment]
有可以复现的代码嘛？

**Comment by jiangyd** [comment]
代码地址：https://github.com/jiangyd/village 
你需要创建session表，还有一些依赖的第三方库

**Comment by zjjott** [comment]
你没有调用`session.SessionRelease` 方法以将session写入数据库
session并不是在set时进行写入的(可以想象那样会有太多的冗余写入)

**Comment by jiangyd** [comment]
是set后，再调用session.SessionRelease吗，其它地方有改变吗，比如删除delete session的时候，还要执行什么吗

**Comment by zjjott** [comment]
刚才我没仔细看，`SessionRelease`已经在控制器的生命周期里调用了
defer st.c.Close()是函数执行完之后关闭这个sql连接用的,应该不影响这个问题。。

**Comment by jiangyd** [comment]
那你试试那边能不能写入session_data ,用最新版的session_mysql.go

**Comment by jiangyd** [comment]
这个问题现在是什么状态，是解决中吗？

**Comment by astaxie** [comment]
已经在develop branch解决了，我正在修复一个模板的issue，会尽快发布1.8.1

**Comment by astaxie** [comment]
beego1.8.1 released
