### ISSUE TITLE
Is there size limit of multipart-form upload about 600MB?

### ISSUE THREAD

**Issue by sdaheng** [astaxie/beego#2541]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

`Server: go version go1.6.3 linux/amd64`

`My computer: go version go1.8 darwin/amd64`

beego version: latest, I just updated.
Bee version: 1.5.2

2. What operating system and processor architecture are you using (`go env`)?

```
go env

GOARCH="amd64"

GOBIN=""

GOEXE=""

GOHOSTARCH="amd64"

GOHOSTOS="darwin"

GOOS="darwin"

GOPATH="/Users/sdh/work"

GORACE=""

GOROOT="/usr/local/go"

GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"

GCCGO="gccgo"

CC="clang"

GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xm/r95qntgn0795f3nt08rg0zjr0000gn/T/go-build802293707=/tmp/go-build -gno-record-gcc-switches -fno-common"

CXX="clang++"

CGO_ENABLED="1"

PKG_CONFIG="pkg-config"

CGO_CFLAGS="-g -O2"

CGO_CPPFLAGS=""

CGO_CXXFLAGS="-g -O2"

CGO_FFLAGS="-g -O2"

CGO_LDFLAGS="-g -O2"
```
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I want to upload a large size file, such as video file, to the server from client app(macOS app).
I use Alamofire framework in client app to uploading file by multipart-form request.
Now I encounter a problem, when I upload a file which is size above 600MB, server will be panic.

Here is the server code:
```
func (c *FileController) Upload() {
	filename := c.Ctx.Request.Header.Get("x-upload-filename")

	f, h, err := c.GetFile(filename)

	ret := make(map[string]interface{})

	defer func() {
		if f != nil {
			f.Close()
		}
	}()

	if err != nil {
		fmt.Println("getfile err ", err)
		ret["status"] = 0
	} else {
		if f != nil && h != nil {
			err = c.SaveToFile(filename, models.NASDir.Path+string(os.PathSeparator)+h.Filename) 
		} else {
			ret["status"] = 0
		}
	}

	if err != nil {
		ret["status"] = 0
	} else {
		ret["status"] = 1
	}
	c.Data["json"] = ret
	c.ServeJSON()
}
```
4. What did you expect to see?
If upload success, client can receive `{ "status" = 1 }`
5. What did you see instead?
![wx20170329-131145](https://cloud.githubusercontent.com/assets/1405754/24439531/52458db6-1481-11e7-93ad-c6541638f76e.png)
When client send about 0.5G, server got panic.

```
2017/03/29 12:40:52 [C] [asm_amd64.s:514] the request url is  /upload
2017/03/29 12:40:52 [C] [asm_amd64.s:514] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:514
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/panic.go:489
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/panic.go:63
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/signal_unix.go:290
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /Users/sdh/work/src/HomeNAS/controllers/FileController.go:20
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:514
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/reflect/value.go:434
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/reflect/value.go:302
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /Users/sdh/work/src/github.com/astaxie/beego/router.go:809
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/server.go:2568
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/server.go:3088
2017/03/29 12:40:52 [C] [asm_amd64.s:514] <autogenerated>:312
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/h2_bundle.go:4319
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/h2_bundle.go:4599
2017/03/29 12:40:52 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:2197
```

**Comment by sdaheng** [comment]
client side code in swift:
```
let fileName = path.components(separatedBy: "/").last!
let header = ["x-upload-filename" : fileName]
session.upload(multipartFormData: { (m) in
           let pathURL = URL(fileURLWithPath: path)
            m.append(pathURL, withName: fileName)
        }, to: URL, headers: header) { (encodingResult) in
            switch encodingResult {
            case .success(request: let upload, streamingFromDisk: _, streamFileURL: _):
                upload.responseJSON(completionHandler: { (response) in
                    if response.result.isSuccess {
                        
                    } else if response.result.isFailure {
                        
                    }
                })
            case .failure(let encodingError):
                print(encodingError)
            }
        }
```

**Comment by zjjott** [comment]
`/Users/sdh/work/src/HomeNAS/controllers/FileController.go:20 `
which line is 20th?
BTW. you should not upload big file to server one time,why don't you use `Chunked` HTTP?

**Comment by sdaheng** [comment]
@zjjott 20th line is `f, h, err := c.GetFile(filename)`. Do you mean this ` Transfer-Encoding: chunked`?

**Comment by zjjott** [comment]
@sdaheng 
there have code like this:
```
if r.MultipartForm == nil {
		err := r.ParseMultipartForm(defaultMaxMemory)
		if err != nil {
			return nil, nil, err
		}
	}
```
defaultMaxMemory equal 32MB, it means every 32MB will store in disk,and `Request.PostForm` whill have a file array. but it's not this bug...
`invalid memory address or nil pointer dereference` may cause by using some pointer which is `nil`,you can debug it to ensure this line something is `nil`,`c`? `c.Ctx`? and more


Actually,upload and store big file by yourself is not a good idea,you can choose some store service like AWS S3

**Comment by sdaheng** [comment]
@zjjott 
Thank you for your advise, but I just want to upload file to my another computer, which is use to be a server in my home. It`s running in local network. AWS S3 may not fit to me. 
I got an error from GetFile(), which is `err  multipart: NextPart: stream error: stream ID 1; CANCEL` . It`s same error as I used `io.Copy(/* File writter */, c.Ctx.Request.Body)` yesterday. It may be caused by `bufio.ReadSlice()` ?  Do you know about this error? Is it a server side error? Thank you very much.

**Comment by zjjott** [comment]
@sdaheng some case will raise error here:
1.  Pending
2.  Buffer full
looks like you meet first case
in HTTP request  body, `\n` will end chunked transfer

`CANCEL ` means maybe it is your client cancel this request,cut off request body or disconnect in request process

**Comment by sdaheng** [comment]
Its timeout problem. Request will be cancelled when timeout arrived. Very appreciated for your help!
