### ISSUE TITLE
linux(Red hat): 0002 Failed to create watcher: function not implemented

### ISSUE THREAD

**Issue by Kexuan** [astaxie/beego#2542]
1. What version of Go and beego are you using (`bee version`)?
 go version go1.8 linux/amd64
 Beego: 1.8.0
 bee v1.8.1
===========================================================

2. What operating system and processor architecture are you using (`go env`)?
 [bea1]$ go env
 GOARCH="amd64"
 GOBIN="/home/bea1/go/bin"
 GOEXE=""
 GOHOSTARCH="amd64"
 GOHOSTOS="linux"
 GOOS="linux"
 GOPATH="/home/bea1/go"
 GORACE=""
 GOROOT="/usr/local/go"
 GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
 GCCGO="gccgo"
 CC="gcc"
 GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
 CXX="g++"
 CGO_ENABLED="1"
 PKG_CONFIG="pkg-config"
 CGO_CFLAGS="-g -O2"
 CGO_CPPFLAGS=""
 CGO_CXXFLAGS="-g -O2"
 CGO_FFLAGS="-g -O2"
 CGO_LDFLAGS="-g -O2"
================================================

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
++++++++++++
 step1 bee new demoPro
 step2 cd go/src/demoPro
 step3 bee run
 [bea1]$ bee run
 ______
 | ___ \
 | |_/ /  ___   ___
 | ___ \ / _ \ / _ \
 | |_/ /|  __/|  __/
 \____/  \___| \___| v1.8.1
 2017/03/29 16:18:56 INFO     ▶ 0001 Using 'demoPro' as 'appname'
 2017/03/29 16:18:56 FATAL    ▶ 0002 Failed to create watcher: function not implemented
 
 program:
 [bea1]$ more main.go 
 package main

 import (
         _ "demoPro/routers"
         "github.com/astaxie/beego"
 )

 func main() {
         beego.Run(":9000")
 }
========================
4. What did you expect to see?
 see hello bee go

========================
5. What did you see instead?
 2017/03/29 16:18:56 FATAL    ▶ 0002 Failed to create watcher: function not implemented

**Comment by quanwm** [comment]
yes, it is happening, who can help?

**Comment by zjjott** [comment]
it raise by `fsnotify.NewWatcher()` and it use kqueue
which Red hat version you are using?

**Comment by quanwm** [comment]
Hello
The OS information as follow

many thanks for your supporting
-----------------------------------------------------------------------------------------------
[bea1]$ lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 5.8 (Tikanga)
Release:        5.8
Codename:       Tikanga
-----------------------------------------------------------------------------------------------

**Comment by zjjott** [comment]
some issue of fsnotify like https://github.com/fsnotify/fsnotify/issues/112 have some fix method,try this
```
go get -u golang.org/x/sys/unix
```
I do not know if it is useful, you can try it

**Comment by quanwm** [comment]
thank you very much for your feedback. but it can not be downloaded
------------------------
C:\Users\ab053160>go get -u golang.org/x/sys/unix
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 61.91.161.217:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
-----------------------

**Comment by zjjott** [comment]
@quanwm your network have problom🤣
I can install it
