### ISSUE TITLE
Beego orm 模块理解困惑

### ISSUE THREAD

**Issue by loongshaw** [astaxie/beego#2545]
orm模块是一个持久层框架，它也具有连接池的作用吧

**Comment by zjjott** [comment]
是的，但这是由go标准库`database/sql` 实现的，里面有个`DB`的结构，实现了`SetMaxOpenConns`和`SetMaxIdleConns `等连接池方法

**Comment by linhaibin** [comment]
我在多个线程里面NewOrm，然后分别操作，他们是否会自动使用不同的连接？
