### ISSUE TITLE
bee api -conn error

### ISSUE THREAD

**Issue by ayonsaha2011** [astaxie/beego#2549]
bee api newproject is successful, 
but  bee api newproject -driver=mysql -conn="root:123456@tcp(localhost:3306)/db" > is fail
Cannot generate application code outside of GOPATH 'f:\go'
I already inside %GOPATH%/src

**Comment by astaxie** [comment]
dup in bee issue

**Comment by GeorgeLzq** [comment]
2019/05/11 15:53:56 FATAL    ▶ 0006 Cannot generate application code outside of GOPATH '/home/rec/data1/codespace/golang' compare with CWD '/home/rec/data1/codespace/golang/src/mytest/articles'

**Comment by GeorgeLzq** [comment]
├── Beego     : 1.11.2
├── GoVersion : go1.12.4
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/rec/data1/codespace/golang
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Saturday, 11 May 2019

**Comment by zhaodezhen** [comment]
> Hi @astaxie
> I had the same problem today(2019/05/11).
> 
> bee api articles -conn="bd_test:BDmytest1@tcp(10.0.1.15:3306)/bd_test"
> failed also;
> 
> An error is as follows:
> 
> 2019/05/11 15:53:56 FATAL ▶ 0006 Cannot generate application code outside of GOPATH '/home/rec/data1/codespace/golang' compare with CWD '/home/rec/data1/codespace/golang/src/mytest/articles'
> 
> My development environment is as follows.
> bee version
> v1.10.0
> ├── Beego : 1.11.2
> ├── GoVersion : go1.12.4
> ├── GOOS : linux
> ├── GOARCH : amd64
> ├── NumCPU : 4
> ├── GOPATH : /home/rec/data1/codespace/golang
> ├── GOROOT : /usr/local/go
> ├── Compiler : gc
> └── Date : Saturday, 11 May 2019
> 
> # go env
> GOARCH="amd64"
> GOBIN="/usr/local/go/bin"
> GOCACHE="/root/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/rec/data1/codespace/golang"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build379754637=/tmp/go-build -gno-record-gcc-switches"

Execute commands under the project directory
