### ISSUE TITLE
yaml文件保存问题

### ISSUE THREAD

**Issue by programmingman** [astaxie/beego#2551]
hello，请问beego的config模块支持yaml文件的保存吗？我看了github.com/beego/goyaml2/blob/master/writer.go的源码，为啥只返回了nil，而没有操作？是不是没有实现yaml文件的保存方法？谢谢

**Comment by zjjott** [comment]
try `gopkg.in/yaml.v2`

**Comment by programmingman** [comment]
@zjjott thanks

**Comment by programmingman** [comment]
close
