### ISSUE TITLE
我只设置了一个主键，但是提示one model must have one pk field only

### ISSUE THREAD

**Issue by jiangyd** [astaxie/beego#2553]
type Menu struct {
	Key   string `orm:"pk;"`
	Title string `orm:"unique"`
	Mid   int    `orm:"auto;"`
}
beego编译提示：

field: admin.Menu.Mid, one model must have one pk field only

**Comment by astaxie** [comment]
因为`auto`也是主键

**Comment by jiangyd** [comment]
那我要怎么设置自增键？我参考的文档
https://beego.me/docs/mvc/model/models.md

**auto**

当 Field 类型为 int, int32, int64, uint, uint32, uint64 时，可以设置字段为自增健

    当模型定义里没有主键时，符合上述类型且名称为 Id 的 Field 将被视为自增健。

鉴于 go 目前的设计，即使使用了 uint64，但你也不能存储到他的最大值。依然会作为 int64 处理。

参见 issue 6113
**pk**

设置为主键，适用于自定义其他类型为主键

**Comment by astaxie** [comment]
不支持联合主键啊
