### ISSUE TITLE
utils.Display打印包含interface的struct时，有时候（不是总是）会打印出指针地址的bug

### ISSUE THREAD

**Issue by szyhf** [astaxie/beego#2558]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go1.8
beego1.7.2

2. What operating system and processor architecture are you using (`go env`)?

darwin

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

utils.Display("", mystruct)

4. What did you expect to see?

 SkillsQueue: []demo.BattleSkiller{
                                skill.InitiativeBattleSkill{
                                        Skill: demo.Skill{
                                            Name: "普通攻击（技能名称）",
                                        },
}

5. What did you see instead?

SkillsQueue: []demo.BattleSkiller{
                                0xC4200BD650,
                                0xC4200BD8F0,
                                0xC4200BD650,
                            }

**Comment by szyhf** [comment]
I make a pr for it .

**Comment by Wusuluren** [comment]
这应该是作者有意的，参考`utils/debug.go`文件的188-194行，可以看到当对象的地址之前使用过的话，会只打印地址。

**Comment by szyhf** [comment]
> 这应该是作者有意的，参考`utils/debug.go`文件的188-194行，可以看到当对象的地址之前使用过的话，会只打印地址。

囧……十几年前的东西都被挖坟了……无所谓咯……就这样把……
