### ISSUE TITLE
beego 是否支持 3.0 的swagger 

### ISSUE THREAD

**Issue by golangpkg** [astaxie/beego#2563]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8 beego

2. What operating system and processor architecture are you using (`go env`)?
go 1.8

 
2. What did you expect to see?

swagger 已经升级到了 3.0 了 可以展示对象了。
在2.0 的时候不能单独看到返回对象都有那些属性。

**Comment by CodeJuan** [comment]
对的

**Comment by astaxie** [comment]
bee 1.8.2 已经支持
