### ISSUE TITLE
使用正则路由后 无法正确加载CSS文件

### ISSUE THREAD

**Issue by Insofan** [astaxie/beego#2564]
router.go中设置路由为
   `beego.Router("/admin/articles/view-post/?:id", &controllers.ViewPostController{}, "get:Get")`
css文件路径为
`static/css/admin/view-post.css`
使用正则路由后控制台提示
`127.0.0.1| 404 |          1ms| nomatch| GET      /admin/view-post.css`
View中相关的代码为
`<link rel="stylesheet" href="../../view-post.css">`
请问其中的link要如何写才能正确加载view-post.css文件

**Comment by zjjott** [comment]
你是想要`/admin/articles/view-post/view-post.css` ?
不明白你的困难在哪，写上去就可以啊？
或者你想用urlfor?
参考文档：https://beego.me/docs/quickstart/static.md
和https://beego.me/docs/mvc/controller/urlbuilding.md

**Comment by Insofan** [comment]
@zjjott 普通路由注册后页面可以正常加载，但是用正则后如 `Router("/admin/articles/view-post/?:id"`
网页打开就没有CSS和JS的约束了 terminal显示是找不到正确的CSS文件，我想知道如果我注册路由按照
`beego.Router("/admin/articles/view-post/?:id", &controllers.ViewPostController{}, "get:Get")`
和CSS文件路径已经按
`static/css/admin/view-post.css`放置
那HTML中的代码应该怎么写
`<link rel="stylesheet" href=“这里写什么文件路径？？？”`

**Comment by zjjott** [comment]
你看了我给的第一个文档吗？
注册静态文件路由然后填上去对应的地址就行
静态文件路由和普通的控制器路由Router 这是两部分，前者可以做分发静态文件的作用，后者是动态产生html或者是一个API接口
你一直在说后面这个路由发静态文件，不是你所需要的。。

**Comment by Insofan** [comment]
@zjjott 谢谢已经解决，我阅读了文档按照写了但还是不行，更改CSS文件名后才正确加载，不知道是不是浏览器缓存的问题还是我使用的Gogland的问题会导致无法正确加载，谢谢

**Comment by NewbMiao** [comment]
@Insofan 我也遇到了这个问题，static文件名和路由名开头部分相同了，就会不能正确找到static file
