### ISSUE TITLE
beego redirect跳转问题

### ISSUE THREAD

**Issue by chuanjiesun** [astaxie/beego#2565]
在使用beego的redirect页面跳转，是用户登陆成功后的跳转this.redirect("/index",302)，但是发现页面还是停留在login页面，通过chrome查看，已经有了GET /index请求，但是页面为什么还会停留在login页面，必须刷新一下才会跳转到index页面，请问这是什么问题？我使用的是win10,用了chrome\ff\ie都是这种情况。

**Comment by zjjott** [comment]
没有遇到你这样的情况，可以提供可复现的代码吗？

**Comment by zjjott** [comment]
你是否调用了Redirect后没有StopRun?
重定向的响应不会终止后面的处理过程，并且响应码可能被覆盖，除非调用了StopRun

**Comment by chuanjiesun** [comment]
我的代码：
	err := o.QueryTable("admin").Filter("username",username).Filter("password",Password).One(aa)
	if err == nil{
		this.SetSession("userLogin",username)
		this.Redirect("/index",302)
	}else{
		beego.Debug("authentication wrong, ",err)
		this.Redirect("/login",302)
	}
在chrome里面查看，确实是POST /login 后是302，然后GET /index（请求类型为XHR，不知道是不是这个原因），但是就是页面还停留在login，不清楚什么情况？

**Comment by zjjott** [comment]
curl -v看下具体的http报文是啥

**Comment by chuanjiesun** [comment]
IE浏览器的login的包：
   请求 URL: https://127.0.0.1:8888/login
   请求方法: POST
   状态码: 302 / 
 - 请求标头
   Accept: application/json, text/javascript, */*; q=0.01
   Accept-Encoding: gzip, deflate
   Accept-Language: zh-CN
   Cache-Control: no-cache
   Content-Length: 35
   Content-Type: application/x-www-form-urlencoded; charset=UTF-8
   Cookie: beegosessionID=f6f72bf9749f3aa9720eadac8c9ecd8e
   Host: 127.0.0.1:8888
   Referer: https://127.0.0.1:8888/login
   User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
   X-Requested-With: XMLHttpRequest
 - 响应标头
   content-length: 0
   content-type: text/plain; charset=utf-8
   date: Fri, 14 Apr 2017 09:38:04 GMT
   location: /index
   server: beego



302跳转后的包：

   请求 URL: https://127.0.0.1:8888/index
   请求方法: GET
   状态码: 200 / 
   请求标头
 - 响应标头
   content-length: 5302
   content-type: text/html; charset=utf-8

**Comment by RoshanGH** [comment]
清除一下你的浏览器缓存

**Comment by chuanjiesun** [comment]
清除过了，也还是不行，很奇怪，请求/index页面结果都反悔了，就是页面还停留在login

**Comment by zjjott** [comment]
你的请求是js发起的ajax，所以重定向是对这个ajax进行的重定向。当前页面当然会停在当前
你可能需要理解<form>标签进行提交和ajax的区别

**Comment by chuanjiesun** [comment]
谢谢，我看了下，就是这里问题，加了servejson()就可以了。
