### ISSUE TITLE
bee api 命令无法在第二个GOPATH目录创建项目

### ISSUE THREAD

**Issue by Sezzna** [astaxie/beego#2568]
bee 版本 1.8.1
Win10系统

使用bee api 命令 确定使用命令无误，并且是在第二目录的src下使用，提示 You current workdir is not inside $GOPATH/src 
就算我只设置一个GOPATH 创建的还是要报这个警告；
但是在win7 下就没有问题 已经卡了两天了 请问 我又什么地方没有作对 还是我忽略了什么设置吗

**Comment by zjjott** [comment]
例如GOPATH="/home/zhutou/work/lua/s3cdn/gocode"
的情况下，你的workdir应该在：
/home/zhutou/work/lua/s3cdn/gocode/src/suibianshenme

**Comment by fasei** [comment]
亲 ，我也遇到了这个问题 bee 的版本1.8.1  win7系统
我再使用bee api 命令的时候 也是提示相同的错误，同时提示如下错误，将命令行发出来了：

**Comment by astaxie** [comment]
已经在bee1.8.2修复
