### ISSUE TITLE
在go1.8.1下面 API自动化文档  {object}  不显示

### ISSUE THREAD

**Issue by kevinworkroom** [astaxie/beego#2569]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1

├── Beego     : 1.8.0
├── GoVersion : go1.8.1
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : D:\GO\
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Monday, 17 Apr 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GO\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

3. What did you do?
重装安装操作系统，之前是win10企业版+go1.8.0
现在是win10专业版+go1.8.1
目前api自动化文档中的models映射的struct无法在Swagger上显示

**Comment by fasei** [comment]
出现了相似的问题：

**Comment by astaxie** [comment]
please try the bee develop branch now

```
cd $GOPATH/src/github.com/beego/bee
git checkout develop
git pull
go install github.com/beego/bee
```

**Comment by astaxie** [comment]
bee 1.8.2版本已经修复该问题
