### ISSUE TITLE
How to use beego with authboss

### ISSUE THREAD

**Issue by mytc** [astaxie/beego#2573]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04.2 and AMD64

Due to lack of user authentication in beego, I am looking a way to implement this third party library [authboss](https://github.com/go-authboss/authboss) . But I cannot figure out how to do it. 

Seem this two system not get along well. 

Anyone can guide me how to do this? 

Or,you have other better authentication system recommendation for beego? 
I hope beego can come with the user authentication system out of the box in the future update.

**Comment by astaxie** [comment]
I never use authboss before, but for beego you can use filter. https://beego.me/docs/mvc/controller/filter.md

**Comment by mytc** [comment]
After studied a bit on authboss, I found it indeed not so suitable with beego. 

Anyway, @astaxie , do you plan to create the authentication system embedded in beego in the future? 
As a newbie in web development, although I can create my own, but I am not confident enough it will secure enough to use in a production app. I do hope that you can implement it in the system out of the box, like other framework like Django or Laravel. Or atleast create a package for it?

**Comment by amrfaissal** [comment]
@mytc This project might help you (https://github.com/vmware/harbor). The project is based on Beego and implements authentication, user management, permissions...
