### ISSUE TITLE
bee api  new 项目 提示警告，Api项目无法创建模版内容

### ISSUE THREAD

**Issue by fasei** [astaxie/beego#2578]
使用的环境如下 win7
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1

├── Beego     : 1.8.0
├── GoVersion : go1.8
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Users\WC\go\
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Thursday, 20 Apr 2017

使用如下命令：
bee api feeww -conn="wanc:123456@tcp(192.168.1.254:3306)/golang"

出现下面
2017/04/20 09:46:35 WARN     ▶ 0001 You current workdir is not inside $GOPATH/src.
2017/04/20 09:46:35 INFO     ▶ 0002 Creating API...
        create   C:/Users/WC/go/src/feeww
        create   C:\Users\WC\go\src\feeww\conf
        create   C:\Users\WC\go\src\feeww\controllers
        create   C:\Users\WC\go\src\feeww\tests
        create   C:\Users\WC\go\src\feeww\conf\app.conf
        create   C:\Users\WC\go\src\feeww\main.go
2017/04/20 09:46:35 INFO     ▶ 0003 Using 'mysql' as 'driver'
2017/04/20 09:46:35 INFO     ▶ 0004 Using 'wanc:123456@tcp(192.168.1.254:3306)/g
olang' as 'conn'
2017/04/20 09:46:35 INFO     ▶ 0005 Using '' as 'tables'
2017/04/20 09:46:35 INFO     ▶ 0006 Analyzing database tables...
2017/04/20 09:46:36 FATAL    ▶ 0007 Cannot generate application code outside of
GOPATH 'C:\Users\WC\go\'

导致0007步骤未成功执行.求各位高手看看 环境变量未配置好吗？ 还是别的什么问题

**Comment by lixiangzhong** [comment]
You current workdir is not inside $GOPATH/src.

**Comment by astaxie** [comment]
please update to bee 1.8.2
