### ISSUE TITLE
 file log: os.Chmode is not set in Octal mode

### ISSUE THREAD

**Issue by nkumar15** [astaxie/beego#2579]
I see below issue is already fixed in develop branch. Can it be merged to master branch please?

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
   v1.8.0

2. What operating system and processor architecture are you using (`go env`)?
    Ubuntu 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Program
---------

```
package main

import (
	"github.com/astaxie/beego/logs"
	"os"
	"fmt"
)

func main() {
	oldfile := "/home/user1/oldfile.log"
	newfile := "/home/user1/newfile.log"

	conf := fmt.Sprintf(`{"filename":"%s","perm":"0664"}`, oldfile)
	
	logger := logs.NewLogger(10000)
	logger.SetLogger("file",conf)
	logger.Debug("kljshgll")

	err := os.Rename(oldfile,newfile)
	err = os.Chmod(newfile, os.FileMode(440))
	if err != nil {
		fmt.Println(err)
	}
}
```

4. What did you expect to see?
I expected the permission of new file as
-r--r-----

5. What did you see instead?
-rw-rwx--- 

this same issue is introduced in 
https://github.com/astaxie/beego/blogs/file.go at line 273.
os.FileMode value should be passed as Octal (os.Chmod(0440)) but it is passed as decimal.

**Comment by zjjott** [comment]
fix in devolop branch by me...

**Comment by nkumar15** [comment]
Yes I noticed that in develop branch. Thats why I asked if it can be merged in master soon?

**Comment by astaxie** [comment]
beego 1.8.1 released

**Comment by nkumar15** [comment]
By the I was wondering, shouldn't the permission be 0444 instead of 0440?

As there is no permission for others.
