### ISSUE TITLE
orm auto_now is not working

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2580]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1

├── Beego     : 1.7.2
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Friday, 21 Apr 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
	

```
type StructA struct {
		Id      int64     `orm:"pk;auto;type(smallint);column(id)"`
		Created time.Time `orm:"auto_now_add;column(created);type(datetime)"`
		Updated time.Time `orm:"auto_now;column(updated);type(datetime)"`
	}
```

4. What did you expect to see?
Change of updated struct field whenever update of the row  is done 
5. What did you see instead?
No change in the updated struct  field. It looks same as the created field.

**Comment by zjjott** [comment]
auto_now will not work when you use `Update` method,you can read the orm doc:https://beego.me/docs/mvc/model/models.md

**Comment by RajeshKumar1990** [comment]
Okay.....I saw that.....May i know when the auto_now will get affected...Any situation.....Thanks
