### ISSUE TITLE
[1]    1579 killed     bee run

### ISSUE THREAD

**Issue by jackluo2012** [astaxie/beego#2582]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
刚更新的,go get github.com/beego/bee
系统是mac ,参数了前面几轮的完全不行,升级版本什么的,都不行

2. What operating system and processor architecture are you using (`go env`)?
mac 最新的系统 go的版本是1.8.1
3. What did you do?
➜  xas git:(master) ✗ bee run -gendoc=true -downdoc=true
[1]    1579 killed     bee run -gendoc=true -downdoc=true

**Comment by amrfaissal** [comment]
To update `bee`, you need to run: `go get -u github.com/beego/bee`.

**Comment by jackluo2012** [comment]
神了个奇,刚在公司,弄死不行,回来,就可以了 ,Thanks.
