### ISSUE TITLE
Bee Killed

### ISSUE THREAD

**Issue by gordysc** [astaxie/beego#2584]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go: 1.7.1
Bee: Latest from `go get github.com/beego/bee` (just downloaded it)

2. What operating system and processor architecture are you using (`go env`)?
MacOS 10.12.3 AMD64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I executed `go get github.com/beego/bee` and then ran the command: bee `<insert any command here>`

4. What did you expect to see?
Bee work

5. What did you see instead?
The process is killed.  This looks identical to #2530 .  Since the issue was closed and the mentioned hot fix branch no longer exists, I'm assuming this has been pushed into the latest release for bee and should be working?

**Comment by amrfaissal** [comment]
I was able to reproduce this issue on MacOS 10.12.4 using `go1.7.1`. I think it has to do with the Go distribution (See https://github.com/golang/go/issues/19734). Upgrading to `go1.8.1` solved the problem.

**Comment by gordysc** [comment]
Confirmed this addressed the issue.  Closing this out.

**Comment by obedmr** [comment]
Is this really fixed?

I'm still seeing bee commands killed.
Go version: go1.8.1 darwin/amd64
MacOS 10.12.4

**Comment by linux-mac** [comment]
You shoud reinstall bee

**Comment by obedmr** [comment]
@linux-mac yeah, that worked, thanks
