### ISSUE TITLE
Support oracle

### ISSUE THREAD

**Issue by giorgiootto** [astaxie/beego#2589]
Hi,
When are going to suppport oracle

**Comment by zjjott** [comment]
database support is base on go library `sql/database`
you can write a new database support by implement interface

**Comment by astaxie** [comment]
oracle driver is already support in ORM https://github.com/astaxie/beego/blob/master/orm/db_oracle.go

```
import 	_ "github.com/mattn/go-oci8"

func init(){
    orm.RegisterDriver("oci8", orm.DROracle)
}

```

**Comment by Joyonline** [comment]
hi i have a question , I query the database(oracle) through native SQL, but the attribute values are all default values.
![image](https://user-images.githubusercontent.com/28465958/68461158-8cb62380-0244-11ea-8916-b72604a1b809.png)

**Comment by Joyonline** [comment]
i got it. i query the database (oracle) through native sql, the result of Column names are all capitalized.
but the properties of beego are all lowercase.
