### ISSUE TITLE
Default value "thinkgem" is set in the first text field in a form

### ISSUE THREAD

**Issue by longyg** [astaxie/beego#2592]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.2

├── Beego     : 1.8.0
├── GoVersion : go1.8.1
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : E:\workspace\go
├── GOROOT    : D:\program\Go\
├── Compiler  : gc
└── Date      : Monday, 24 Apr 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\workspace\go
set GORACE=
set GOROOT=D:\program\Go
set GOTOOLDIR=D:\program\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Create a example app using "bee new quickstart", update the index.tpl, just added a form contaning two text <input>, after running the app and open the index page on Browser, there is always a default value "thinkgem" in the first <input> field.

4. What did you expect to see?
There should be no any default value set in the text field.

5. What did you see instead?
There is always a default value "thinkgem" in the first text field.

**Comment by astaxie** [comment]
is that your browser problem?

**Comment by longyg** [comment]
Right, it's my browser problem. I re-installed my browser. Now the problem is disappeared. Thanks for reminding.
