### ISSUE TITLE
Package httplib  delete method with params not work!

### ISSUE THREAD

**Issue by heramerom** [astaxie/beego#2593]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
    lastest 1.8.1

2. What operating system and processor architecture are you using (`go env`)?
```
➜  ~ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xhl/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build150074434=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
➜  ~ 
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

When I use package httplib delete method, I pass a params to the BeegoRequest. but it not work.
I found the source code `buildUrl` it dose not contains `delete` method

```go
func (b *BeegoHTTPRequest) buildURL(paramBody string) {
    if b.req.Method == "GET" && len(paramBody) > 0 {
         .....
    }
    
    if (b.req.Method == "POST" || b.req.Method == "PUT" || b.req.Method == "PATCH") && b.req.Body == nil {
        .....
    }
}
```

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
HTTP Delete does not accept data as an argument.

**Comment by heramerom** [comment]
But sometime I must pass an argument because the third part API not standard.

**Comment by heramerom** [comment]
http://stackoverflow.com/a/4048536

**Comment by astaxie** [comment]
@heramerom Actually it's not RESTful, but I still support it in httplib now.
