### ISSUE TITLE
feature request: support router dynamically delete

### ISSUE THREAD

**Issue by ansiz** [astaxie/beego#2598]
I try to use Beego in my project which has a requirement to establish dozens of proxy handlers dynamically, I use beego.Handler function to create a new proxy handler, it works well:
```
	proxyHandler := websocketproxy.NewProxy(u)
	beego.Handler(wsURL, proxyHandler)
```
But I worry that this will make server performance lower, so I want to delete those handlers after use, I did not find any function or method can do that.

I'm not sure whether everyone has such a requirement, but I think it will make the program more flexible

4. What did you expect to see?
I hope to have a function available or someone can give me some ideas or suggestions. Thanks a lot.

**Comment by zjjott** [comment]
what do you want?how many perfomance will be affect?it seems have no any problem?

**Comment by ansiz** [comment]
Hi @zjjott, thanks for your reply, I establish dozens of proxy handlers dynamically to connect the websocket interface of [GoTTY](https://github.com/yudai/gotty) which ran on nodes of my cluster, whenever the user visits, I create a new handler, so I also hope to destroy them after connection closed.

I read the code,  the ControllerRegister is composed of many trees and leaves, each leaf has it own runObject, I worry that this will consume too much memory , it also has a little affects the speed of the index(can be ignored)

In extreme case, if I have 1000 users, about 10000 available ports and 500 nodes, it may produce up to 50 billion handlers. But the actual situation is not so bad, each user may use this function several times a day to open several nodes, so in one month it may be 1000(users)*5(times)*2(nodes)*30(days)*The probability of not repeating, I guess it may be 150,000 ?

**Comment by astaxie** [comment]
It's not support to delete router node now.

**Comment by ansiz** [comment]
@astaxie  ok, thanks for your reply anyway : )
