### ISSUE TITLE
orm 构造查询 order by 不生效

### ISSUE THREAD

**Issue by yuan-make** [astaxie/beego#2601]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.5.1

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\golangproject
set GORACE=
set GOROOT=D:\Go
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

3. What did you do?
orm 原生查询 order by  不起作用
sw.Select("a.last_seen, b.db_max,sum(b.ts_cnt) ts_cnt ,sum(b.Query_time_sum)/sum(b.ts_cnt) Query_time_avg").From("mysql_slow_query_review a").LeftJoin("mysql_slow_query_review_history b").On("a.checksum=b.checksum").Where("b.user_max=?").And("a.sample not like \"%delete%\"").And("last_seen > ?").And("last_seen<=?").GroupBy("a.checksum").Having("Query_time_avg > ?").And("ts_cnt >= ?").OrderBy("?")
nums, err := o.Raw(sql, Dbname, stime, etime, Overtime, 100, ordertype).ValuesList(&lists)

[ORM]2017/04/26 20:49:16  - 2017-04-26 20:49:16 - [Queries/slow] - [  OK /    db.Query /   422.0ms] - [SELECT a.last_seen, b.db_max,sum(b.ts_cnt) ts_cnt ,sum(b.Query_time_sum)/sum(b.ts_cnt) Query_time_avg FROM mysql_slow_query_review a LEFT JOIN mysql_slow_query_review_history b ON a.checksum=b.checksum WHERE b.user_max=? AND a.sample not like "%delete%" AND last_seen > ? AND last_seen<=? GROUP BY a.checksum HAVING Query_time_avg > ? AND ts_cnt >= ? ORDER BY ?] - `testmake`, `2017-03-01 00:00:00`, `2017-04-22 00:00:00`, `2`, `100`, `ts_cnt`

第二列为ts_cnt  ，但是排序结果不对
[2017-04-13 16:00:18  5427 
[2017-04-13 15:55:19  742 
[2017-04-15 04:45:27  177 
[2017-04-13 10:29:25  10987 
[2017-04-13 16:00:18  8807 
[2017-04-13 11:11:11  285 
[2017-03-03 01:11:16  1806 
[2017-04-13 16:00:15  10391 
[2017-04-13 16:00:18  8660 
[2017-04-13 16:00:15  8570

4. What did you expect to see?
版本问题？？？

5. What did you see instead?

**Comment by zjjott** [comment]
试试 `.OrderBy(ordertype)` ?
OrderBy里面应该不支持`?`的参数形式。。

**Comment by yuan-make** [comment]
谢谢 ，可以了

**Comment by astaxie** [comment]
@yuan-make 当你确定这个可以解决你的问题的时候记得及时的关闭issue
