### ISSUE TITLE
Generate migrations from models?

### ISSUE THREAD

**Issue by osavchenko** [astaxie/beego#2603]
Is it possible to generate migrations automatically from models?

**Comment by zjjott** [comment]
`orm sqlall` can generate migration sql that from empty database
https://beego.me/docs/mvc/model/cmd.md

**Comment by osavchenko** [comment]
Not so pretty solution, but current one also can be used. Thank you!

**Comment by julienkosinski** [comment]
Maybe Bee should have a way to generate all the migration file from the written models with a command like `bee generate migration from-models`. It now seems that we only can generate bee migrations from the command line with field:value (no constraints and not able to analyse existing models).

**Comment by jotavargas** [comment]
I found this https://github.com/drone/sqlgen
