### ISSUE TITLE
beego 1.8.1  SetCookie 失效，GetCookie 取不到值

### ISSUE THREAD

**Issue by uuappli** [astaxie/beego#2605]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.8.1
GoVersion : go1.8.1

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?

升级1.8.1 后 
GetCookie 取不到值

4. What did you expect to see?

5. What did you see instead?

**Comment by zjjott** [comment]
有可复现的代码吗？

**Comment by uuappli** [comment]
<img width="557" alt="a4334914-a7c0-48a4-a0b8-b796cd2ae644" src="https://cloud.githubusercontent.com/assets/6519730/25538198/50989e94-2c74-11e7-8ec8-c4d9acd47882.png">

写了一个简单的例子 和下面的调试信息

**Comment by uuappli** [comment]
<img width="473" alt="56dc8af9-4ffc-4e5b-88c5-37478b5517e9" src="https://cloud.githubusercontent.com/assets/6519730/25538477/6f77665a-2c75-11e7-99d6-a61dc4a7ec4c.png">
1.8 的 结果

**Comment by astaxie** [comment]
@uuappli 下次你最好能搞一个可以复制黏贴的代码，我还需要打一遍你的截图代码。我们可以让调试变得更简单

**Comment by uuappli** [comment]
OK

**Comment by zjjott** [comment]
https://tools.ietf.org/html/rfc6265#section-4.1 RFC6265里要求max-age是非零的数字，但很多其他框架有时候也允许放进去一个0 ，比如django比如tornado
所以尽量按标准来就好，max-age 放0 是个非法行为

**Comment by astaxie** [comment]
目前在Go的Cookie的文档里面写着0就忽略，也就是不设置，我不清楚这个是不是非法行为，目前是参考Go的Cookie的设置来处理

https://golang.org/pkg/net/http/#Cookie

**Comment by zjjott** [comment]
好吧，按golang来就好了。。。。看来RFC的存在感稀薄。。。
