### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by h3idan** [astaxie/beego#2609]
1. throwed error
```bash
panic: runtime error: invalid memory address or nil pointer dereference
```

2. session settings in conf/app.conf
```go
sessionon = true
sessionprovider = redis
sessionproviderconfig = "127.0.0.1:6379"
```

3. init session in controllers/user.go
```go
    sessionConfig := &session.ManagerConfig{
        CookieName:      "sessionid",
        EnableSetCookie: true,
        Gclifetime:      3600,
        Maxlifetime:     3600,
        Secure:          false,
        CookieLifeTime:  3600,
        ProviderConfig:  "",
    }

    globalSessions, _ = session.NewManager("redis", sessionConfig)
    go globalSessions.GC()
```

I saw the doc from beego.me, what wrong in my code?

**Comment by h3idan** [comment]
```go
sessionConfig := &session.ManagerConfig{
        ...
        ProviderConfig:  "127.0.0.1:6379",
}
```
it has worked. But why the session settings of app.conf is invalid？

**Comment by astaxie** [comment]
Where did you init globalSessions? is it init before the app.conf parsed?

**Comment by h3idan** [comment]
Controller directory.

**Comment by astaxie** [comment]
please provide more information if you have issues. It's really so hard to help you to solve the problem

**Comment by h3idan** [comment]
I just anwser you question. I init the globalSession in "controller/user.go". I don't know where one 
 be preferentially parsed.  :(

**Comment by astaxie** [comment]
please read the right docs if you use beego while not the session modules. https://beego.me/docs/mvc/controller/session.md

**Comment by jacentsao** [comment]
@h3idan Have you fixed this problem, I meet this problem too. I'm using mysql inseted of redis and the program have already worked several weeks but it not work since this morning
