### ISSUE TITLE
ORM filter string like

### ISSUE THREAD

**Issue by Raggaer** [astaxie/beego#2610]
Hello,

Is it possible to use a filter to make a %like% search? So far I tried

```
tbl.Filter("title_like", "test")`
tbl.Filter("product__title_like", "test")
```

No success. Thanks

**Comment by bakanis** [comment]
Take a look at the docs
https://beego.me/docs/mvc/model/query.md
qs.Filter("name__contains", "slene")
// WHERE name LIKE BINARY '%slene%'
// Case sensitive, only match name that contains 'slene'
tbl.Filter("title__contains", "test")
