### ISSUE TITLE
Hello, i got this error

### ISSUE THREAD

**Issue by leoxnidas** [astaxie/beego#2617]
Hi im new with beego and im trying to use session cookies, but this error comes in.

0013 Failed to build the application: # github.com/leoxnidas/vonlapin
./main.go:19: cannot use "{\"cookieName\":\"gosessionid\",\"enableSetCookie\":false,\"gclifetime\":3600,\"ProviderConfig\":\"{\\\"cookieName\\\":\\\"gosessionid\\\",\\\"securityKey\\\":\\\"beegocookiehashkey\\\"}\"}" (type string) as type *session.ManagerConfig in argument to session.NewManager

**Comment by RajeshKumar1990** [comment]
i have used session like this in my project.
```
sessionConfig := &session.ManagerConfig{
CookieName: "cookie",
Gclifetime: 3600,
}
GlobalSessions, err = session.NewManager("memory", sessionConfig)
go GlobalSessions.GC()
```

Hope this helps.Thanks
