### ISSUE TITLE
使用sqlite，orm中通过filter后的delete删除不成功

### ISSUE THREAD

**Issue by guanly** [astaxie/beego#2630]
VERSION = "1.8.2"

GoVersion = 1.8
```
orm.RegisterDriver("sqlite", orm.DRSqlite)
orm.RegisterDataBase("default", "sqlite3", "webnote.db")
orm.NewOrm().QueryTable(&models.MarkdownItem{}).Filter("mid", deleteId).Delete()
```
日志：
[ORM]2017/05/09 15:26:09  -[Queries/default] - [  OK /    db.Query /     1.0ms] - 
[SELECT T0.`mid` FROM `wn_markdown_item` T0 WHERE T0.`mid` = ? ] - `d765889b99c6d710e964ed2d59cbb52d`
[ORM]2017/05/09 15:26:09  -[Queries/default] - [  OK /     db.Exec /     0.0ms] - 
[DELETE FROM `wn_markdown_item` WHERE `mid` IN (?)] - `[100 55 54 53 56 56 57 98 57 57 99 54 100 55 49 48 101 57 54 52 101 100 50 100 53 57 99 98 98 53 50 100]`
0

从Query日志里可以看到能查到1条符合的记录，但Exec执行后却没有删除成功

**Comment by zjjott** [comment]
num ,err = qs.Filter("user_name__in", "testing1", "testing2").Delete() 
这个err里有东西吗？

**Comment by guanly** [comment]
@zjjott err里是没有东西的，只是删除时没有匹配参数值没有匹配到。在执行Delete时参数传成了数组，如果在执行delete时将参数转成string是没有问题的

**Comment by astaxie** [comment]
那问题是你传错了参数，这个你打开debug应该可以看到输出的SQL

**Comment by guanly** [comment]
@astaxie 
不是我传错了，这个参数是beego orm里设的

**Comment by guanly** [comment]
@astaxie 
不是我传错了，这个参数是beego orm里设的
db.go  deleteBatch里
```
for rs.Next() {
		if err := rs.Scan(&ref); err != nil {
			return 0, err
		}
		args = append(args, reflect.ValueOf(ref).Interface())
		cnt++
	}
```

改成
```
	for rs.Next() {
		if err := rs.Scan(&ref); err != nil {
			return 0, err
		}
		pkValue, err := d.convertValueFromDB(mi.fields.pk, reflect.ValueOf(ref).Interface(), tz)
		if err != nil {
			panic(fmt.Errorf("get pk value failed:  `%s` ", ref))
		}
		args = append(args, pkValue)
		cnt++
	}
```
这样才没有问题
