### ISSUE TITLE
perm of rotated log is unreasonable 

### ISSUE THREAD

**Issue by zeast** [astaxie/beego#2631]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

just use beego/logs

2. What operating system and processor architecture are you using (`go env`)?

go version go1.8.1 darwin/amd64

[https://github.com/astaxie/beego/blob/master/logs/file.go](https://github.com/astaxie/beego/blob/master/logs/file.go)

`err = os.Chmod(fName, os.FileMode(0440))`  is unreasonable.

In my case. perm of log config is 0644. other can read it. but after rotate,  other can't.
if config is 0600, after rotate,  owner group can read it.

I think just decrease `w` of perm or  set perm of rotated file by config is better.

**Comment by astaxie** [comment]
I would like make it as a config.

**Comment by flycash** [comment]
![image](https://user-images.githubusercontent.com/9923838/92763002-b6405e00-f3c5-11ea-9614-ff6b4c11ef53.png)
