### ISSUE TITLE
"killed 9" while trying to use bee

### ISSUE THREAD

**Issue by Harisam** [astaxie/beego#2641]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go version: go version go1.7.4 darwin/amd64
Bee version: used to use bee 1.8.0(can not use bee now) ,trying to use 1.8.2

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jasper/dev/golang_workspace"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wn/715jnv617z7_tm2dl5ndb0dc0000gn/T/go-build588397922=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.0
2017/05/15 00:20:05 WARN     ▶ 0001 Cannot find the object: models.Delete_tactics_req
2017/05/15 00:20:05 WARN     ▶ 0002 Cannot find the object: models.Modify_tactics_req
2017/05/15 00:20:05 WARN     ▶ 0003 Cannot find the object: models.Result_list_req
2017/05/15 00:20:05 WARN     ▶ 0004 Cannot find the object: models.Change_tactics_req
2017/05/15 00:20:05 WARN     ▶ 0005 Cannot find the object: models.Creat_tactics_req
2017/05/15 00:20:05 WARN     ▶ 0006 Cannot find the object: models.On_tactics_req

trying to solve problems No Model Definition, just like  this one  https://github.com/astaxie/beego/issues/2524,  so I did what u said. But when i trying to run bee, only  printing "**Killed: 9**" on screen.

4. What did you expect to see?
bee & beego version,  and my problem been solved

5. What did you see instead?
sh-3.2# bee 
Killed: 9

**Comment by amrfaissal** [comment]
This issue appeared a few times now, and upgrading to `go1.8.1` seems to help. Please do consider also upgrading bee to `1.8.3`.

**Comment by Harisam** [comment]
@amrfaissal  upgrate go version works, thx.
