### ISSUE TITLE
the func of templatefunc.go parses time string is not strict

### ISSUE THREAD

**Issue by printfcoder** [astaxie/beego#2649]
in https://github.com/astaxie/beego/blob/master/templatefunc.go 
line 363
```
if len(value) >= 25 {
	value = value[:25]
        t, err = time.ParseInLocation(time.RFC3339, value, time.Local)

```

when a time string length is larger than or equal to 25，then the time string will be treated like rfc3339.  But, the below time strings length is less than 25, they are all valid rfc3339 date-times:
```

2002-10-02T10:00:00-05:00  length 25
2002-10-02T15:00:00Z           length 20
2002-10-02T15:00:00.05Z      length 23
2017-05-19T11:00:00.000Z     length 24
```

when I call controller.ParseForm, it printf a error 
`err:parsing time "2017-05-19T11:00:00" as "2006-01-02 15:04:05"`

my html form:

```

var data = new FormData();
data.append("recordId", "15F2FB11-9B4F-BB91-8B4B-E1A110D1F42A-T");
data.append("beginTime", "2017-05-19T11:00:00.000Z");
data.append("remindType", "1");
data.append("participantIds", "2,3,4");
data.append("remindwayIm", "im");
data.append("remindwayEmail", "email");

```

**Comment by astaxie** [comment]
@gouyang please have a look at this issue
