### ISSUE TITLE
logs模块如果输出日志至es中去

### ISSUE THREAD

**Issue by yyf1986** [astaxie/beego#2662]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
GoVersion : go1.7.4

单独使用logs模块
logs.NewLogger(1000)
logs.SetLogger(logs.AdapterEs, `{"dsn":"http://10.11.20.127:9200/","level":7}`)
//logs.SetLogger(logs.AdapterConsole, `{"level":7}`)
logs.Debug("asdasdsads")

如果在es上查找？

**Comment by duramen** [comment]
同问，用beego框架自带的日志模块去发ES好像也失败的，另外，看beego里的日志代码，索引名直接是日期？前缀能否改成项目名？
https://github.com/astaxie/beego/blob/98740fddac7c5c0df83ea31b751a87e317d28163/logs/es/es.go#L60

**Comment by duramen** [comment]
@astaxie

**Comment by stlswm** [comment]
![image](https://user-images.githubusercontent.com/13382733/66693053-27b7ee00-ecd7-11e9-8a4b-afb54b5dbb34.png)
  slake风格的日志为什么不上报日志等级呢，大神@astaxie

**Comment by flycash** [comment]
ES logger example: https://github.com/beego-dev/beego-example/pull/16/files

**Comment by flycash** [comment]
> 索引名直接是日期？前缀能否改成项目名？

我创建了一个issue来追踪这个问题，欢迎关注。#4040
