### ISSUE TITLE
beego的事务传递是怎么做的？

### ISSUE THREAD

**Issue by fuhao715** [astaxie/beego#2664]
请教一下，beego的orm操作数据时事务传递怎么做？例如：
begin
f1()
f2()
err := f3()
if err != nil {
   rollback
}
commit
必须保证f1，f2，f3这三个函数公用一个ormer.
是否有办法f1，f2，f3这三个函数都有各自ormer和事务操作.但3个函数在一个事物操作的时候能实现事务传递

**Comment by RanQiwu** [comment]
这个问题结果吗?

**Comment by RanQiwu** [comment]
#1662

**Comment by flycash** [comment]
在我们新的实现里面，暴露了一个`Begin() TxOrm`的方法。返回的`TxOrm`就是一个在事务上下文内执行sql的`Orm`对象。在这种case之下，需要将`TxOrm`向下传递到 f1, f2, f3里面。Go没有`Thread local`之类的东西，所以只能依赖于向下传递。
