### ISSUE TITLE
在filter中怎样修改requestbody的值

### ISSUE THREAD

**Issue by dreaminglwj** [astaxie/beego#2676]
我在filter中判断用户登陆是否正确，如果正确的话转到具体的api，但是因为在判断登陆的时候已经查过一次表，想把一些信息写入到request中，这样在api中就不用再查表了。

我没有启用session，所以不好用session操作。

**Comment by JessonChan** [comment]
不应该写到request中，定到context.Input.Data中去

**Comment by dreaminglwj** [comment]
非常感谢，context.Input.Data()["yourdatakey"] = "your data"
