### ISSUE TITLE
Why parse a map to js object is unsupported sometimes?

### ISSUE THREAD

**Issue by NewbMiao** [astaxie/beego#2688]
1. **environment**
beego:1.8.3
go:
- local : 1.8.1 (macOs)
- remote: 1.7.5 (centos)

---

2.  `go env`
**local**
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/newbmiao/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m_/hlhv5wl17vg368420bbxszhc0000gn/T/go-build678157003=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2
```
**remote**
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build245845752=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
---

3.**Problem:**
I try to parse a `map[int][string]` to js json object , it's **ok** on local(go 1.8.1 macOs), but **failed** on remote(go1.7.5 linux). And error is `/* json: unsupported type: map[int]string */`.
And something weired is  `map[string]string` is parsed **ok** on both!

And i still test code (see: https://play.golang.org/p/2kR1IZdBlm ) on both, output is ok.

So i am confused why it failed on remote? But local is always ok ?!

(The Way i run beego both is execute the binary file which after bee pack.)
Below is my code screenshots:

![image](https://cloud.githubusercontent.com/assets/10249367/26749976/5e578b98-484a-11e7-8320-0845559c2eda.png)
![image](https://cloud.githubusercontent.com/assets/10249367/26749828/18021428-4846-11e7-9125-011a18e51190.png)
![image](https://cloud.githubusercontent.com/assets/10249367/26749831/1e9b95e8-4846-11e7-843c-4cc3ef18fa1f.png)

**Updated**
I try this code under `golang:1.7.5-alpine` is ok, maybe it's not because go 1.7.5
run test on: https://github.com/NewbMiao/beegoTest

**Comment by NewbMiao** [comment]
@astaxie Wanted help!

**Comment by astaxie** [comment]
please provide reproduct code

**Comment by NewbMiao** [comment]
```
//Router.go
beego.Router("/test", &controllers.TestController{})

//controller/test.go
func (c *TestController) Get() {
	c.Data["TestStr"] = map[string]string{
		"1": "test",
		"2": "test2",
	}
	c.Data["TestInt"] = map[int]string{
		1: "test",
		2: "test2",
	}
	c.LayoutSections = make(map[string]string)
	c.TplName = "test.html"
}

//test.html
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8">title>test</title></head>
<body>
<script>
    var testStr=<<<.TestStr>>>;
    var testInt=<<<.TestInt>>>;
</script>
</body>
</html>

//output on local:
 var testStr={"1":"test","2":"test2"};
 var testInt={"1":"test","2":"test2"};
//output on remote:
  var testStr={"1":"test","2":"test2"};
  var testInt= /* json: unsupported type: map[int]string */null ;
```

@astaxie  I know it far to reproduct the error, if need some info more ,pls tell me

**Comment by cch123** [comment]
according to json rfc, the key of Json must be string:

An object is an unordered collection of zero or more name/value
   pairs, where a name is a string and a value is a string, number,
   boolean, null, object, or array.

If you use int as key, you'll meet encode / decode errors, maybe also in other languages(such as php

**Comment by NewbMiao** [comment]
@cch123 You are right, but why ok in local,and https://play.golang.org/p/2kR1IZdBlm this code also show we can parse code like this

**Comment by cch123** [comment]
@NewbMiao , https://go-review.googlesource.com/c/22060/

**Comment by NewbMiao** [comment]
@cch123  Cool！THKS, The `encoding/json` on remote is not have this update.

So to solve this, i need update it.
Is there some way to update `encoding/json` alone.

**Comment by cch123** [comment]
...I recommend modify your code to satisfy the lower version, and avoid future troubles

**Comment by NewbMiao** [comment]
@cch123 ... yes. It is a pity to can't use it directly.
