### ISSUE TITLE
Cannot get the inputs  from terminal

### ISSUE THREAD

**Issue by RajeshKumar1990** [astaxie/beego#2697]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.3

├── Beego     : 1.8.2
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Wednesday, 7 Jun 2017

2. What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
The following code helps me to get the input and print it in the terminal.
```
package main

import (
	"fmt"
)

func main() {
	var input string
	fmt.Println("Enter the input")
	fmt.Scanf("%s\n", &input)
	fmt.Println(input)
}
```
If i compile as go build sample.go and run as ./sample.exe then there is no problem.Instead if i run bee run then the program is not printing the value in the terminal.
4. What did you expect to see?
Need to print the input value in the terminal
5. What did you see instead?
Allow the user to give the input but not printing.

**Comment by astaxie** [comment]
Does it related to beego?
