### ISSUE TITLE
动态增加task的问题

### ISSUE THREAD

**Issue by yyf1986** [astaxie/beego#2708]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.8.3
GoVersion : go1.8
2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gocode
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

3. What did you do?
提供了一个增加task的api，希望可以动态增加task

4. What did you expect to see?
想要动态增加task，直接就可以生效

5. What did you see instead?
增加完之后不会启动，要先停止所有的，在启动才会执行新增的

**Comment by astaxie** [comment]
增加之后会生效啊，https://github.com/astaxie/beego/blob/master/toolbox/task.go#L429-L431

你有可重现的代码吗？

**Comment by yyf1986** [comment]
package models
func AddTask(name,spec string) {
	f:= func() error { fmt.Println(name,time.Now()); return nil }
        tk := toolbox.NewTask(name, spec, f)
        toolbox.AddTask(name, tk)
	//toolbox.StopTask()
	//toolbox.StartTask()
}
package controllers
// @Title AddTask
// @Description add task
// @Param	project_name		query 	string	true		"project_name"
// @Param	spec		query 	string	true		"task time"
// @Success 200 ***** ***** 
// @Failure 403 body is empty
// @router /add [get]
func (t *TaskController) Add() {
	project_name := t.GetString("project_name")
	spec := t.GetString("spec")
	models.AddTask(project_name,spec)
	t.Data["json"] = map[string]int{"status": 200}
	t.ServeJSON()
}

**Comment by yyf1986** [comment]
我通过监控AdminTaskList的列表，发现新的任务是增加的，但是下一次执行时间是这样：
0001-01-01 00:00:00 +0000 UTC

**Comment by yyf1986** [comment]
动态增加task的时候，需要SetNext（）
