### ISSUE TITLE
Session in mysql

### ISSUE THREAD

**Issue by vikky1993** [astaxie/beego#2709]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.6.2 
bee v1.8.4

2. What operating system and processor architecture are you using (`go env`)?
ubuntu 16.04 LTS

GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
====
I have imported _ "github.com/astaxie/beego/session/mysql"
   	"github.com/astaxie/beego/session"
in my code and trying to use it to create session in my login and logout page. The problem what i am facing is i want to know how can i call the functions in my program which are in beego/session/mysql which uses provider interface like SessionRead, SessionExist, SessionRegenerate,.etc.

i am able to call the functions which are using session store but not the ones which use provider not understanding what exactly i am missing here.

i get this error when i try to use anything related to provider - globalSessions.SessionExist undefined (type *session.Manager has no field or method SessionExist)
====
4. What did you expect to see?
i want to be able to call those functions through my program.

5. What did you see instead?
it gives me error as undefined. yes it is right but not understanding where and how to call the provider thing. Any help will be very much appreciated thank you in advance.

**Comment by caslino** [comment]
Make sure the DB table is created. Run this script if it is not.

```
CREATE TABLE `session` (
	`session_key` char(64) NOT NULL,
	`session_data` blob,
	`session_expiry` int(11) unsigned NOT NULL,
	PRIMARY KEY (`session_key`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

Then in your main.go function import the following
```
import(
_ "github.com/astaxie/beego/session/mysql"
 "github.com/astaxie/beego/session"
)
```

Change your app.conf settings to enable sessions and to use MySQL as the provider. 
SessionOn = true
SessionProvider = mysql
SessionProviderConfig = username:password@tcp(127.0.0.1:3306)/dbname

**Note** that the documentation says to use 
SessionSavePath = username:password@tcp(127.0.0.1:3306)/dbname
which I believe is incorrect. It has to be SessionProviderConfig 

After fixing this it started working for me. 

After that, you should be able to access your session variables using the existing methods.

- SetSession(name string, value interface{})
- GetSession(name string) interface{}
- DelSession(name string)
- SessionRegenerateID()
- DestroySession()
