### ISSUE TITLE
Email validation on empty field

### ISSUE THREAD

**Issue by osavchenko** [astaxie/beego#2713]
Why it doesn't ignore empty field and trying to validate it?

**Comment by miraclesu** [comment]
Because the `Email` validation just valid a field content is an email address or not. An empty field isn't an email address, isn't it?

I think custom function can meet your expectation.
```
import (
	"github.com/astaxie/beego/validation"
)

type user struct {
	Id    int
	Email string `valid:"MyEmail"`
	Age   int    `valid:"Required;Range(1, 140)"`
}

func MyEmail(v *validation.Validation, obj interface{}, key string) {
	name, ok := obj.(string)
	if !ok {
		// wrong use case?
		// set Error?
		return
	}

	// valid true
	if len(name) == 0 {
		return
	}

	v.Email(obj, key)
}

func main() {
	valid := validation.Validation{}
	if err := validation.AddCustomFunc("MyEmail", MyEmail); err != nil {
		// hadle error
	}
	u := user{Email: "", Age: 40}
	b, err := valid.Valid(u)
	if err != nil {
		// handle error
	}
	if !b {
		// validation does not pass
		// blabla...
	}
}
```

**Comment by rfyiamcool** [comment]
+1

**Comment by dmitryt** [comment]
+1. Quite a strange behaviour. If I want to make my email field required, I can type 
``Email     string `valid:"Required;Email"` ``
Does it mean, that for any optional field with predefined validation(like Email, Phone, etc.) I should implement custom function?
