### ISSUE TITLE
关于模板，有没有更详细一点的文档呢？官网的文档看的好吃力，不是很明白。

### ISSUE THREAD

**Issue by nature19862001** [astaxie/beego#2722]
官网的文档看的好吃力，很多地方看不太明白，例子也不够详细。

**Comment by smallfish** [comment]
参考下：
https://astaxie.gitbooks.io/build-web-application-with-golang/content/zh/07.4.html
https://gohugo.io/templates/go-templates/

**Comment by astaxie** [comment]
https://beego.me/docs/mvc/view/tutorial.md
