### ISSUE TITLE
log模块，创建log文件时，perm权限怎么指定。具体的json配置怎么写？

### ISSUE THREAD

**Issue by pyang30** [astaxie/beego#2727]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
![image](https://user-images.githubusercontent.com/9923838/92762754-7b3e2a80-f3c5-11ea-9e3c-87f8addc6b22.png)
