### ISSUE TITLE
AppConfigProvider is undefined.

### ISSUE THREAD

**Issue by takeo-lvgs** [astaxie/beego#2731]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/h-tko/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build703152373=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

---
3. 

I have read the following documents.

https://beego.me/docs/mvc/controller/config.md

AppConfigProvide has already been changed to appConfigProvider. However, your document still states how to use AppConfigProvider.

Is there any other way?

**Comment by takeo-lvgs** [comment]
I'm sorry. I solved it.

```
beego.LoadAppConfig("json", "conf/app.json")
```

**Comment by earlcherry** [comment]
beego.LoadAppConfig("json", "conf/app.json") dont work

**Comment by xmapst** [comment]
Can you tell me your app.json, my app.json doesn't work
@takeo-lvgs
