### ISSUE TITLE
[Proposal] Database Migrations

### ISSUE THREAD

**Issue by gnanakeethan** [astaxie/beego#2743]
I have been inspired by the Migration features in Laravel Framework of PHP. [See here](https://github.com/laravel/laravel/blob/develop/database/migrations/2014_10_12_000000_create_users_table.php)

I have worked out a small script today, that could potentially become a fully fledged DB migration manager for all adapters. You can see the scripts here. [Link to Gist](https://gist.github.com/gnanakeethan/67011926e43963a849385a5ced7ea2a0)

I would like to work further and integrate this into migration package of Beego.

**Comment by astaxie** [comment]
Looks good, But these definition maybe can convert it to struct tags. So it can works with ORM in the future

**Comment by gnanakeethan** [comment]
Sorry,I could not understand what you meant. But I think struct tags can be used to generate migrations, I have improved the methods and created reversibility to an extent.  

Can you provide me suggestions to improve.

**Comment by astaxie** [comment]
Sorry, I forget to paste the link https://gist.github.com/gnanakeethan/67011926e43963a849385a5ced7ea2a0#file-20170704_165247_stores-go-L25-L30

I would like to involve the table struct. Otherwise how can I update two tables once?

```
m.Tables = append(m.Tables, &Stores{}, &Goods{})

type Stores struct{
   id   int    `"orm":auto`
   ....
}

type Goods struct{
 ...
}
```

**Comment by gnanakeethan** [comment]
I think, we just need to instantiate a new Migrate struct and call methods on them.

**Comment by gnanakeethan** [comment]
Thanks.
