### ISSUE TITLE
orm中time.Time类型的数据，JSON输出的时候，怎么格式化time.Time?

### ISSUE THREAD

**Issue by jockchou** [astaxie/beego#2745]
beego的orm字段不支持自定义类型，时间类型字段只能使用time.Time

框架在输出struct的时候，time.Time默认是按RFC3339Nano格化式输出的，如果想要2006-01-02 15:04:05格式输出，要如何处理？

**Comment by astaxie** [comment]
```
type JSONTime time.Time

func (t JSONTime)MarshalJSON() ([]byte, error) {
    //do your serializing here
    stamp := fmt.Sprintf("\"%s\"", time.Time(t).Format("Mon Jan _2"))
    return []byte(stamp), nil
}

type Document struct {
    Name        string
    Content     string
    Stamp       JSONTime
    Author      string
}
```

**Comment by jockchou** [comment]
你这不是自定义类型JSONTime了吗？beego的ORM支持？

**Comment by tonyttz** [comment]
> @jockchou 

type Time time.Time

const (
	timeFormart = "2006-01-02 15:04:05"
)


// UnmarshalJSON ...
func (t *Time) UnmarshalJSON(data []byte) (err error) {
	now, err := time.ParseInLocation(`"`+timeFormart+`"`, string(data), time.Local)
	*t = Time(now)
	return
}

// MarshalJSON ...
func (t Time) MarshalJSON() ([]byte, error) {
	b := make([]byte, 0, len(timeFormart)+2)
	b = append(b, '"')
	b = time.Time(t).AppendFormat(b, timeFormart)
	b = append(b, '"')
	return b, nil
}

// Implement  beego orm Fielder

// Value return the datetime value
func (e Time) Value() time.Time {
	return time.Time(e)
}

// Set set the time.Time to datetime
func (e *Time) Set(d time.Time) {
	*e = Time(d)
}

// String return the time's String
func (e *Time) String() string {
	return e.Value().String()
}

// FieldType return the enum TypeDateTimeField
func (e *Time) FieldType() int {
	return 64
}

// SetRaw convert the string or time.Time to DateTimeField
func (e *Time) SetRaw(value interface{}) error {
	switch d := value.(type) {
	case time.Time:
		e.Set(d)
	case string:
		v, err := time.ParseInLocation(timeFormart, d, time.Local)
		if err == nil {
			e.Set(v)
		}
		return err
	default:
		return fmt.Errorf("<DateTimeField.SetRaw> unknown value `%s`", value)
	}
	return nil
}

// RawValue return the datetime value
func (e *Time) RawValue() interface{} {
	return e.Value()
}
