### ISSUE TITLE
是否可以增加跨域支持

### ISSUE THREAD

**Issue by qzyuanmu** [astaxie/beego#2756]
最好是在conf里配置一下，就可以支持最好了。
        this.Ctx.Output.Header("Access-Control-Allow-Origin", "*")
	this.Ctx.Output.Header("Access-Control-Allow-Methods", "POST,GET,OPTIONS,DELETE")
	this.Ctx.Output.Header("Access-Control-Allow-Headers", "x-requested-with,content-type")
	this.Ctx.Output.Header("Access-Control-Allow-Credentials", "true")
现在用的是如上方法

**Comment by lifei6671** [comment]
这个可以用Filter实现。

**Comment by qzyuanmu** [comment]
@lifei6671 可以贴一下代码吗

**Comment by lifei6671** [comment]
@qzyuanmu 参考这里 [https://github.com/lifei6671/mindoc/blob/master/routers/filter.go](https://github.com/lifei6671/mindoc/blob/master/routers/filter.go) 第 37 至 40 行。

**Comment by astaxie** [comment]
https://github.com/astaxie/beego/tree/master/plugins/cors
