### ISSUE TITLE
https和http同时启用报错了？

### ISSUE THREAD

**Issue by kekemuyu** [astaxie/beego#2767]
2017/07/17 08:41:52 [I] [asm_amd64.s:2197] http server Running on http://:8080
2017/07/17 08:41:52 [I] [asm_amd64.s:2197] https server Running on https://:443
2017/07/17 08:41:52 [C] [asm_amd64.s:2197] ListenAndServeTLS:  listen tcp :443: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

是不是main函数中的设置一下，文档中没看到https和http同时启用的例子。

**Comment by astaxie** [comment]
可以同时启用，已经很明确的指出你的错误是：ListenAndServeTLS: listen tcp :443: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by kekemuyu** [comment]
谢谢，原来是在main中同时启用beego.run()和beego.run(":443")就可以了

**Comment by cappuccino5** [comment]
目前我也有遇到这类问题，请问这个问题是如何解决的呢？
