### ISSUE TITLE
Can I Response JSON At Filter?

### ISSUE THREAD

**Issue by AbooJan** [astaxie/beego#2781]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
beego 1.9.0
```

2. What operating system and processor architecture are you using (`go env`)?
```
macOS 10.12.5
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
no error
```

4. What did you expect to see?

I insert a filter like this
```
eego.InsertFilter("/*", beego.BeforeRouter, authFilter())
```

I want response JSON at the filter, but I can only do with `context.Context`, and the context not support like `Controller` has func `ServerJSON`.

Is there has any solution ?

**Comment by astaxie** [comment]
`ctx.Output.JSON()`

please refer to document http://godoc.org/github.com/astaxie/beego/context#BeegoOutput.JSON

**Comment by AbooJan** [comment]
I found func `ServerJSON ` in `beego.controller` is also use the func `ctx.Output.JSON()` 😁
```
func (c *Controller) ServeJSON(encoding ...bool) {
	var (
		hasIndent   = true
		hasEncoding = false
	)
	if BConfig.RunMode == PROD {
		hasIndent = false
	}
	if len(encoding) > 0 && encoding[0] {
		hasEncoding = true
	}
	c.Ctx.Output.JSON(c.Data["json"], hasIndent, hasEncoding)
}
```
Finally I add a util func like that to solve it.
