### ISSUE TITLE
在项目目录通过vendor管理依赖，bee run运行时报 Fail to watch directory...too many open files

### ISSUE THREAD

**Issue by zhiquan911** [astaxie/beego#2785]
我使用glide来管理依赖库，它在项目文件夹下生成了vendor文件夹，把依赖库都搬到了vendor。
终端执行：bee run，最后报错以下信息：

2017/07/27 09:40:23 [ERRO] Fail to watch directory[open /myspace/workplace/go-workspace/projects/src/aisms_server/vendor/github.com/astaxie/beego/plugins/cors: too many open files]

**Comment by astaxie** [comment]
what's your bee version? The latest bee already exclude the vendor folder by default.

**Comment by zhiquan911** [comment]
我使用的是1.8.3

**Comment by astaxie** [comment]
你看看bee help run输出

**Comment by zhiquan911** [comment]
谢谢，原来版本问题，我update最新版后，已经解决。

**Comment by ansiz** [comment]
I met the same problem on macOS
Here is my solution：
use `ulimit -a` to check your  file descriptors limit, try `ulimit -S -n 2048` to increase it
then run again
check kern.maxfilesperproc and kern.maxfiles if necessary
