### ISSUE TITLE
 请教 session 的问题

### ISSUE THREAD

**Issue by liteck** [astaxie/beego#2787]
环境:mac go 1.8.3  beego 1.8.3
用 beego 搭建了一个项目...后台管理和接口输出作为一个项目使用.
后台有需要登录等..
因为使用了多台服务器做负载..所以启用了 beego session. 并用 redis 作为 session provider.
使用的过程中发现...开启了 session 之后.对 redis 的消耗非常大..
查询原因后.发现.项目所有的接口被调用时.都会产生一个 sessionid 并保存到了 redis 中.
请教:
有没有什么方案..我只针对某些接口使用 session.. 而不是全局使用.

**Comment by liteck** [comment]
补充一点:
因为对外输出的接口使用的频次很高.这些接口也会产生 session. 并存入 redis.. 有没有什么控制的方法.可以仅仅让后台接口使用 session. 对外输出接口不使用..
请教

**Comment by arthur-xie** [comment]
从router.go的source code来看，session完全是全局的配置选项控制的，只有static file能逃脱。所以一个建议是，在你的Controller的Init方法中关闭全局的SessionOn开关（配置文件中必须保持开启）然后根据需要去开启session，然后在Finish方法中去release session。但是这个会有一个问题，如果controller的执行过程中有任何的未处理的panic或者调用了Abort之类的方法，Finish方法是不会被执行的。

**Comment by zhuleilei** [comment]
目前为止,还是不能做到针对部分某些接口使用 session 么?

**Comment by flycash** [comment]
是的。如果你希望我们支持的话，那么你希望我们提供什么样的方式来支持，用户体验会比较好？

**Comment by flycash** [comment]
I close it and please follow #4176
