### ISSUE TITLE
about beego/logs source code: where to close file adapter

### ISSUE THREAD

**Issue by pingbinary** [astaxie/beego#2789]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.8.3 linux/amd64
beego 1.9.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/licc/devel/go/goweb"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build747521677=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by pingbinary** [comment]
I am reading souce code of beego/logs, but I have not find where to close file adapter. please somebody help me out. thanks in advance.

**Comment by astaxie** [comment]
I can't get you. Do you want to restart the file logs?

**Comment by pingbinary** [comment]
sorry for unclear. I mean, if I need `defer log.Close()` in main() function, like seelog does (https://github.com/cihub/seelog). thank you.

**Comment by arthur-xie** [comment]
Why shall you do this? Please describe your scenario. If you just want to close(explicitly close) logger before process exit, ```beego.BeeLogger.Close()``` is what you need, but that is unnecessary.
