### ISSUE TITLE
beego Raw 语句如何使用mysql的SQL_CALC_FOUND_ROWS 和 FOUND_ROWS()?

### ISSUE THREAD

**Issue by funlake** [astaxie/beego#2816]
问题不好描述，反正就是不稳定，同一条语句加了SQL_CALC_FOUND_ROWS,启动beego服务后，一开始是正确的，多刷新几次页面，结果found_rows()就变成1了。。

**Comment by satng** [comment]
我也遇到过，我再哪里看到过，两条sql不同的gorountine里执行了，是不同的mysql连接会话，所有就不正确了。这个还没有找到好的办法，换成了count(*)

**Comment by zav8** [comment]
刚找到了这个问题解决方法，感谢 @satng 的提醒
在使用之前先开启事务：
```go
o := orm.NewOrm()
o.Begin()
// 然后注意回滚 or 关闭事务
```
后面的 sql 都会在一个 session 里面执行了
OK
