### ISSUE TITLE
orm的QueryRows返回结果和数据库不一致，前面两个字段会清0，为什么

### ISSUE THREAD

**Issue by wangzhilin90** [astaxie/beego#2837]
Please answer these questions before submitting your issue. Thanks!

├── Beego     : 1.9.0
├── GoVersion : go1.7.6
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : D:\cht\code\go;D:\cht
├── GOROOT    : C:\Go
├── Compiler  : gc
└── Date      : Tuesday, 29 Aug 2017

实际查数据库结果是
{2705101	5004	1493340308	1493340308	1493395199	0	3	0	0.004	0	50	50000	1,3,6,12,18	1,2,5	满送加息券	单笔投资≤5万可用，投资期限≥1月	春华季活动}
返回的值是
{0 0 1493340308 1493340308 1493395199 0 3 0 0.0040 0.0000 50.00 50000.00 1,3,6,12,18 1,2,5 满送加息券 单笔投资≤5万可用，投资期限≥1月 春华季活动}

package rateroupon

import (
	. "cht/common/logger"
	"fmt"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

type CouponTable struct {
	ID           int32
	UserID       int32
	Addtime      int32
	StartTime    int32
	EndTime      int32
	UseTime      int32
	Status       int16
	TenderID     int32
	Apr          string
	AppAdd       string
	MinTender    string
	MaxTender    string
	TimeLimit    string
	BorrowType   string
	Name         string
	Remark       string
	ActivityName string
}

type CouponRequest struct {
	UserID               int32
	Status               int16
	Limit                int16
	ChengHuiTongTraceLog string
	OrderBy              string
}

func init() {
	orm.Debug = true
	orm.RegisterModel(new(CouponTable))
	orm.RegisterDriver("mysql", orm.DRMySQL)
	user := "root"
	passwd := "1qaz2wsx"
	host := "192.168.8.205"
	port := "3306"
	dbname := "cht_bs"
	orm.RegisterDataBase("default", "mysql", fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8", user, passwd, host, port, dbname))
}

func GetRateRoupon(crs *CouponRequest) (cps []CouponTable, err error) {
	o := orm.NewOrm()
	o.Using("default")
	qb, _ := orm.NewQueryBuilder("mysql")
	qb.Select("*").
		From("jl_apr_coupon").
		Where(fmt.Sprintf("user_id=%d", crs.UserID))

	if crs.Status != 0 {
		qb.And(fmt.Sprintf("status=%d", crs.Status))
	}
	if crs.OrderBy != "" {
		qb.OrderBy(crs.OrderBy)
	}
	if crs.Limit != 0 {
		qb.Limit(int(crs.Limit))
	}

	sql := qb.String()
	Logger.Debugf("GetRateRoupon sql", sql)
	var cs []CouponTable
	o.Raw(sql).QueryRows(&cs)
	Logger.Debugf("GetRateRoupon res", cs)
	return cs, nil
}

**Comment by willxm** [comment]
应该是这两个字段名大小写不对
ID int32
UserID int32

**Comment by wangzhilin90** [comment]
是的，这个没有和数据库做映射 正确的写法应该后面加个映射关系，比如 Username string `orm:column(username)`
