### ISSUE TITLE
beego如何配合分布式框架使用

### ISSUE THREAD

**Issue by dreaminglwj** [astaxie/beego#2841]
你好，使用beego有一段时间了，挺好的一个框架。

最近刚开始在看分布式集群的资料，想了解下用beego如何配合搭建一个高可用的分布式服务器集群？

多谢！

**Comment by Jolly23** [comment]
这ISSUE有意义吗？
想研究就去看Docker Kubernetes之类的。
session，orm，cache 指向一台服务器，其他的爱怎么分布集群的。
还有，啥叫分布式服务器集群？你先弄明白分布式和集群的概念吧
