### ISSUE TITLE
swagger自动化文档model生成错误

### ISSUE THREAD

**Issue by chaegumi** [astaxie/beego#2856]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.9.0
├── GoVersion : go1.6.2

2. What operating system and processor architecture are you using (`go env`)?
ubuntu16.04
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
我在common/common.go里边定义了一个

```go
package common
type ControllerResponse struct{
	Code int `json:"code"`
	Message string `json:"message"`
	Data interface{} `json:"data,omitempty"`
}
```
在models/table_schema.go里边也定义了一个
```go

package models

type ControllerResponse struct{
	Code int64 `json:"code,返回码"`
	Message string `json:"message,返回消息"`
}

```

然后我在controller里边写swagger自动化文档

```php
// @Success 200 {object} models.ControllerResponse

```

编译成功后，用浏览器打开文档，出现解析错误。
Resolver error at paths./o2o/categories/data.post.responses.200.schema.properties.data.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/8395.0xc8201ee060.false does not exist in document
很明显，我本来需要他调用models里边的那个ControllerResponse，但是调用到common里边的那个ControllerResponse了。

4. What did you expect to see?

5. What did you see instead?

**Comment by xhan742** [comment]
这个问题解决了吗@chaegumi？我也遇到了一样的问题

**Comment by chaegumi** [comment]
@xhan742 
在common项目的models目录中单独写个
```go
type DocCommonResponse struct{
	Code int `json:"code" description:"返回码"`
	Message string `json:"msg" description:"返回信息"`
	Record_count int64 `json:"record_count" description:"总记录数"`
	Current_page int64 `json:"current_page" description:"当前页码"`
	Page_size int64 `json:"page_size" description:"每页记录数"`
}

```
然后@Success写成
```go

// @Success 200 {object} models.DocCommonResponse

```

**Comment by ox0spy** [comment]
这个应该还是 bug 吧？应该自动生成才对，否则挺麻烦的
