### ISSUE TITLE
ORM连接PostgreSQL无法使用Schema

### ISSUE THREAD

**Issue by CHCP** [astaxie/beego#2871]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.8.3

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
使用Beego的ORM连接PostgreSQL，无法使用Schema。

4. What did you expect to see?
完善Beego的ORM功能，连接PostgreSQL可以使用Schema。

5. What did you see instead?
NO

**Comment by mailbaoer** [comment]
you can use [go-pg](https://github.com/go-pg) instead

**Comment by lurenjia528** [comment]
func init() {
	orm.RegisterDriver("postgres", orm.DRPostgres) // 注册驱动
	orm.RegisterDataBase("default", "postgres", beego.AppConfig.String("sqlconn"))

	//设置scheme
	o := orm.NewOrm()
	_, e := o.Raw("set search_path to monitor").Exec()
	if e != nil {
		panic(e)
	}

	orm.RunSyncdb("default", false, true)
}

**Comment by lurenjia528** [comment]
``` go
func init() {
	orm.RegisterDriver("postgres", orm.DRPostgres) // 注册驱动
	orm.RegisterDataBase("default", "postgres", beego.AppConfig.String("sqlconn"))

	//设置scheme
	o := orm.NewOrm()
	_, e := o.Raw("set search_path to monitor").Exec()
	if e != nil {
		panic(e)
	}

	orm.RunSyncdb("default", false, true)

	myCors()
}
```

**Comment by sayi65** [comment]
> ```go
> func init() {
> 	orm.RegisterDriver("postgres", orm.DRPostgres) // 注册驱动
> 	orm.RegisterDataBase("default", "postgres", beego.AppConfig.String("sqlconn"))
> 
> 	//设置scheme
> 	o := orm.NewOrm()
> 	_, e := o.Raw("set search_path to monitor").Exec()
> 	if e != nil {
> 		panic(e)
> 	}
> 
> 	orm.RunSyncdb("default", false, true)
> 
> 	myCors()
> }
> ```
it is not working
