### ISSUE TITLE
批量UPDATE怎么操作

### ISSUE THREAD

**Issue by gemeserver** [astaxie/beego#2874]
目前一个需求，需要一次更新1万条数据，即使用了orm事务，还需要10秒，以下是代码，请高手帮我优化下速度
func (oip *IpSli) GetIpToObj() {
	var Ips []Ip
	o:=orm.NewOrm()
	count, err := o.QueryTable("Ip").Limit(10000).OrderBy("Checktime").All(&Ips)//选取6个，从第10个开始
	if err != nil {
		fmt.Println("获取ip数据失败", err)
	}else {
		fmt.Println("获取到数据:", count)
		o.Begin()
		for _, Ip := range Ips {
			Ip.Status="验证中"
			Ip.Checktime=time.Now()
			updateIp(o,Ip)
			oip.Ips=append(oip.Ips,Ip)
		}
		o.Commit()
	}
}
// 在数据库里更新获取到的ip数据的Checktime字段
func updateIp(o orm.Ormer, oip Ip) {
	_, err := o.QueryTable("Ip").Filter("Ip", oip.Ip).Filter("Port",oip.Port).Update(orm.Params{"checktime": oip.Checktime})
	if err != nil {
		fmt.Println("更新获取后ip数据失败", err)
	}
}
func test2()  {
	var IpObj IpSli
	start:=time.Now()
	IpObj.GetIpToObj()
	fmt.Printf("%.4fs 运行时间\n",time.Since(start).Seconds())
}

**Comment by flycash** [comment]
这么久过去了，目测你应该不需要帮助了=。=
