### ISSUE TITLE
Beego上传文件的原理是什么

### ISSUE THREAD

**Issue by ch456hf** [astaxie/beego#2879]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go是1.6.4  Beego是1.8.3

2. What operating system and processor architecture are you using (`go env`)?
Linux和amd64

3.我的问题是：
Beego上传文件的原理是什么？通用的Http上传原理是把上传来的文件全部读取到内存中，然后进入路由函数进行处理，等于文件在处理前一直是在内存中，我想问下Beego是不是也是这个原理？有没有想过如果文件过大将会使得内存消耗很多，性能极具下降，有些文件上传的架构是读取达到一定阈值会写一次，Beego是否有这样的设置？

**Comment by mszhe** [comment]
请移步beego开发文档（https://beego.me/docs/mvc/controller/params.md）：

![20170929123747](https://user-images.githubusercontent.com/29294018/31001031-2095306e-a513-11e7-991f-3e11b129c19b.png)

**Comment by mszhe** [comment]
![20170929123747](https://user-images.githubusercontent.com/29294018/31001060-52bd284e-a513-11e7-97b5-ef817f85ceac.png)

**Comment by ch456hf** [comment]
谢谢，这个我也看到了，我们目前碰到一个问题是，如果上传一个大文件，大概有2个多G，机子的物理内存有2G，MaxMemory设置的是4G，当其上传完后处理时，调用exec开启另一个进程的时候，会报 fork exec
error can not allocate memory，这个错误一直持续了很久才可以新创建进程，像是一直在占用着内存没有释放，我理解不应该写完后调用close就释放掉内存了，怎么现象是占用了很久呢。

**Comment by xiaogan18** [comment]
close应该只是释放了指针，具体内存释放是需要go的垃圾回收来执行的吧

**Comment by jianzhiyao** [comment]
beego 1.X 上传文件利用的是 ** net/http ** 包的 ``Request.ParseMultipartForm(maxMemory)`` 方法：
机制是优先加载到内存，内存不够则放到临时文件目录。
物理内存只有2G不应该设置这么大的内存值。

beego 2.0 后使用``http.MaxBytesReader(MaxUploadSize)``限制上传文件的大小
