### ISSUE TITLE
http,https可以同时开启吗？

### ISSUE THREAD

**Issue by toffstech** [astaxie/beego#2887]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Bee         :  1.8.4
Beego     : 1.9.0
GoVersion : go1.9

2. What operating system and processor architecture are you using (`go env`)?
Macbook, macOSv10.12.6

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

bee run

4. What did you expect to see?
2017/10/08 19:18:54 [I] [asm_amd64.s:2337] https server Running on https://:8888
2017/10/08 19:18:54 [I] [asm_amd64.s:2337] http server Running on http://:8080
2017/10/08 19:18:54 [C] [asm_amd64.s:2337] ListenAndServe:  listen tcp :8888: bind: address already in use

5. What did you see instead?
同时开启http,和https，

app.conf:
httpport = 8080
HTTPSPort = 8888
enablehttp = true
EnableHTTPS = true
EnableHttpTLS = true

运行：
bee run

就出错：
ListenAndServe:  listen tcp :8888: bind: address already in use

单独运行http,或https都没问题，同时开htt和https就报错

**Comment by astaxie** [comment]
可以，你的错误提示你的8888端口已经被占用了啊

**Comment by ywolf** [comment]
mac 一直无法同时启动，linux下一定几率无法同时启动，不知为何，很明确不是其他程序端口占用了。

**Comment by xuange306** [comment]
我想问下, 你这个问题解决了吗? @ywolf

**Comment by DennisMao** [comment]
@ywolf 提示`bind: address already in use`的话是指端口已经占用。可以先用指令检查一下。如果还启动失败，建议把log贴上来分析

**Comment by xuange306** [comment]
问题初步锁定在beego的app.go文件中
`if BConfig.Listen.EnableHTTPS {
		go func() {
			time.Sleep(1000 * time.Microsecond)
			if BConfig.Listen.HTTPSPort != 0 {
				app.Server.Addr = fmt.Sprintf("%s:%d", BConfig.Listen.HTTPSAddr, BConfig.Listen.HTTPSPort)
			} else if BConfig.Listen.EnableHTTP {
				BeeLogger.Info("Start https server error, confict with http.Please reset https port")
				return
			}
			logs.Info("https server Running on https://%s", app.Server.Addr)
			if err := app.Server.ListenAndServeTLS(BConfig.Listen.HTTPSCertFile, BConfig.Listen.HTTPSKeyFile); err != nil {
				logs.Critical("ListenAndServeTLS: ", err)
				time.Sleep(100 * time.Microsecond)
				endRunning <- true
			}
		}()
	}`
这里有一个睡眠时间, 默认为20*Millisecond
这个时间太短了, 我放到200*Millisecond的时候, 报错频率明显下降
我把时间放到 1000* Millisecond,报错频率为0了, (测试样本不足, 大概重启了20遍, 没有出现报错)

**Comment by ywolf** [comment]
@xuange306 https://github.com/astaxie/beego/pull/3102 我们在使用的时候发现了这个问题，通过这个方式可以修复，最新官方版本不知道已经修了没。
