### ISSUE TITLE
Adding IdleTimeout to solve leaking file descriptors issue

### ISSUE THREAD

**Issue by miadabrin** [astaxie/beego#2892]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9
2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/miad/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build132684991=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

3. What did you do?
Ran a bee server and exposed it to the public.

4. What did you expect to see?
Controlled number of open files ( not increasing over time)

5. What did you see instead?
open file descriptors increase over time most of them are sockets.

I think adding the IdleTimeout config to the http server would solve the issue. Do you think I should open a merge request for it?

**Comment by miadabrin** [comment]
this article pretty much covers why. I have set it manually now and it works as expected (meaning that it will keep open sockets to a limited value) 
https://blog.cloudflare.com/exposing-go-on-the-internet/

I did this basically 
```
beego.BeeApp.Server.IdleTimeout = time.Duration(beego.BConfig.Listen.ServerTimeOut) * time.Second
```

**Comment by miadabrin** [comment]
@astaxie any comments?

**Comment by astaxie** [comment]
As the solution you provide, it can solve the issue. what do you want to do? add a new config?

**Comment by miadabrin** [comment]
Update: I don't think it does really solve it. might have just slowed it down a bit. I still have lots of sockets open . on a relatively not busy server. To be honest I am not sure whether there is too many of them . Do you think I should disabled keep alive connections?
The thing is lots of connections stay in Close_wait status and there are also lots of sockets open which increase (although gradually ) over time. It might not be a beego specific problem though

**Comment by miadabrin** [comment]
It might somehow be related to this closed issue. https://github.com/astaxie/beego/issues/2226

**Comment by miadabrin** [comment]
Update : Still growing (1661 sockets open)

**Comment by miadabrin** [comment]
@astaxie Hasn't anyone else reported this?

**Comment by miadabrin** [comment]
Update: The issue was because of my http clients inside the app which were leaking sockets not the http server. Closing the issue
