### ISSUE TITLE
beego orm无法在mysql的表中生成mediumblob类型的字段

### ISSUE THREAD

**Issue by JarreyZhou** [astaxie/beego#2897]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go: 1.7.5
beego: v1.9.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zjw/codes/go/"
GORACE=""
GOROOT="/home/zjw/go-go1.7.5"
GOTOOLDIR="/home/zjw/go-go1.7.5/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build428442328=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
In my model, i set use orm like this 
type r struct {
logo string \`orm:"type(mediumblob)"\`
}
but the column in mysql is vchar(255), not mediumblob, does beego not supprot this type?

**Comment by DennisMao** [comment]
@JarreyZhou  手动创建表,并未支持
