### ISSUE TITLE
beego 日志如何自动切分 （比如一天的日志分成100M 多个文件）

### ISSUE THREAD

**Issue by winworm** [astaxie/beego#2904]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

    1.8.3

2. What operating system and processor architecture are you using (`go env`)?

centos6.5

3. What did you do?

 split one day logs to multiple logs

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
@winworm https://beego.me/docs/module/logs.md#%E6%97%A5%E5%BF%97%E5%A4%84%E7%90%86
