### ISSUE TITLE
Bee runmode option not work

### ISSUE THREAD

**Issue by Rustavil** [astaxie/beego#2916]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.9.0
├── GoVersion : go1.9.1
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/rustavil/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Wednesday, 1 Nov 2017

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rustavil/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build269144435=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

app.conf:
```
appname = server
runmode = dev
Graceful = true
RecoverPanic = true
copyrequestbody = true

[dev]
HTTPAddr = "0.0.0.0"
HTTPPort = 8080

[prod]
HTTPAddr = "0.0.0.0"
HTTPPort = 80
```
I run the application with the command: bee run -runmode=prod <app_path>

I expected the application to work on port 80. But in fact the application uses dev runmode and works on port 8080

**Comment by osavchenko** [comment]
You should use `BEEGO_RUNMODE` environment variable

**Comment by Rustavil** [comment]
Thanks! I tried, it didn't help
in the logs, I see that the **runmode** is changing, but the server runs on the **8080** port

**Comment by osavchenko** [comment]
And what port and why you expect to see?


5 груд. 2017 р. о 22:32 Rustavil <notifications@github.com> пише:

**Comment by Rustavil** [comment]
In the above configuration, the server runs on port **8080**

I have defined `BEEGO_RUNMODE` = PROD
I expect the server to start on **80**

**Comment by osavchenko** [comment]
There is no conditional configuration for port depending on environment https://github.com/astaxie/beego/blob/master/config.go#L200 <https://github.com/astaxie/beego/blob/master/config.go#L200>
It will run on 8080 every time if you will not define port manually.

**Comment by osavchenko** [comment]
didn't see your config above. I'm not sure, but what will happens if you change `[prod]` to `[PROD]`?

**Comment by Rustavil** [comment]
I changed [prod] to [PROD]

```
appname = server
runmode = dev
Graceful = true
RecoverPanic = true
copyrequestbody = true

[DEV]
HTTPAddr = "0.0.0.0"
HTTPPort = 8080

[PROD]
HTTPAddr = "0.0.0.0"
HTTPPort = 80
```
But it not help

2017/12/06 13:18:15 INFO     ▶ 0001 Using 'server' as 'appname'
2017/12/06 13:18:15 WARN     ▶ 0002 Using 'PROD' as 'runmode'
2017/12/06 13:18:15 INFO     ▶ 0003 Initializing watcher...
2017/12/06 13:18:17 SUCCESS  ▶ 0004 Built Successfully!
2017/12/06 13:18:17 INFO     ▶ 0005 Restarting 'server'...
2017/12/06 13:18:17 SUCCESS  ▶ 0006 './server' is running...
[Train] server.go:74: 26733 0.0.0.0:8080

In the logs you can see what is used 'PROD' as 'runmode', but not used prod config

**Comment by kamilgregorczyk** [comment]
I'm having the same issue, I see that logging changes but port is 7000 instead of 9000
```
appname = testProject

[dev]
httpport = 7000

[prod]
httpport = 9000
```

```
➜  testProjectecho $BEEGO_RUNMODE                         
prod
```

**Comment by rodrigodmd** [comment]
You need to create a app.config with the runmode. Fore example if you execute

         bee run -runmode=dev

It will use the file:
         
          dev.app.config
