### ISSUE TITLE
在arm v7上启动就卡死了

### ISSUE THREAD

**Issue by gaorongfu** [astaxie/beego#2917]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version si 1.9.2.
beego version is the newest, just download yestorday
2. What operating system and processor architecture are you using (`go env`)?
centos7.2 amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
我使用bee new 创建了一个空的项目，没有做任何修改，交叉编译了arm v7版本之后，放到arm v7设备上运行。只出现了下面一行信息，就卡住了，8080端口也无法访问。
2017/11/02 13:10:46 [I] [asm_arm.s:971] http server Running on http://:8080

下面是资源占用的信息，./test是用bee new创建的应用
  PID  PPID USER     STAT   VSZ %MEM CPU %CPU COMMAND
  755     1 root     S     117m 23.3   0  1.4 ./edpsmainarm473
 1712   722 root     S     5748  1.1   0  0.1 sshd: root@pts/0
    4     2 root     SW       0  0.0   0  0.1 [kworker/0:0]
16743  1798 root     S     776m154.1   0  0.0 ./test

4. What did you expect to see?

5. What did you see instead?

**Comment by gaorongfu** [comment]
问题解决了，arm设备的swap空间是0，内存也只有500m。设置了ulimit -s 128，才把程序跑起来，汗！
不过虚拟内存占用还是在700多M，从proc/pid/smaps信息来看，有个500m和200m的内存空间分配，不知道是干嘛用的，是golang的http包自行分配的空间？

**Comment by astaxie** [comment]
Go 默认会分配很大的虚拟空间
