### ISSUE TITLE
proposal: orm - add notification message about using transaction 

### ISSUE THREAD

**Issue by lvxiaorun** [astaxie/beego#2918]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
beego orm使用mysql，当引擎为myisam的时候，如果开启一个事务应该给一个友好提示（innodb支持事务，但是myisam不支持）。

Could orm output some information when start a transaction on myisam engine?
5. What did you see instead?

**Comment by jianzhiyao** [comment]
@flycash  
``mysql``每个表的引擎都可能不同，此 proposal 不建议支持

**Comment by flycash** [comment]
We don't want to support this feature since the engine or DB aredifferent. If anyone need this feature, we can reopen this issue to discuss it.
