### ISSUE TITLE
 how to use auto generate doc when add two or more namespaces

### ISSUE THREAD

**Issue by whomm** [astaxie/beego#2923]
my code like this
router.go
`
    //v1api
	ns := beego.NewNamespace("/v1api",
              ********
	)
	beego.AddNamespace(ns)

	//v2api
	ns2 := beego.NewNamespace("/v2api",
              *********
        )
	beego.AddNamespace(ns)
`
but generate doc only hive one base path ---   base url: /v1api
how to make v1api & v2api in one project  or generate two swagger  page

**Comment by cg831344** [comment]
me too

**Comment by ever-cifuentes-globant** [comment]
Why this was closed? Where is the solution?
