### ISSUE TITLE
go get -u github.com/astaxie/beego  安装出错,求解决

### ISSUE THREAD

**Issue by yuandong17** [astaxie/beego#2925]
go get -u github.com/astaxie/beego
# github.com/astaxie/beego/utils
golib/src/github.com/astaxie/beego/utils/mail.go:407:20: error: reference to undefined identifier ‘sync.Pool’
 var bufPool = sync.Pool{
                    ^
golib/src/github.com/astaxie/beego/utils/mail.go:407:24: error: expected ‘;’ or newline after top level declaration
 var bufPool = sync.Pool{
                        ^
golib/src/github.com/astaxie/beego/utils/mail.go:410:2: error: expected declaration
  },
  ^
golib/src/github.com/astaxie/beego/utils/utils.go:13:29: error: reference to undefined identifier ‘strings.Compare’
  if gopath == "" && strings.Compare(runtime.Version(), "go1.8") >= 0 {
                             ^
# github.com/astaxie/beego/logs
golib/src/github.com/astaxie/beego/logs/log.go:139:17: error: reference to undefined identifier ‘sync.Pool’
 var logMsgPool *sync.Pool
                 ^
golib/src/github.com/astaxie/beego/logs/log.go:169:21: error: reference to undefined identifier ‘sync.Pool’
  logMsgPool = &sync.Pool{
                     ^
golib/src/github.com/astaxie/beego/logs/log.go:169:25: error: expected ‘;’ or ‘}’ or newline
  logMsgPool = &sync.Pool{
                         ^
golib/src/github.com/astaxie/beego/logs/log.go:170:27: error: expected ‘;’ or newline after top level declaration
   New: func() interface{} {
                           ^
golib/src/github.com/astaxie/beego/logs/log.go:172:3: error: expected declaration
   },
   ^
golib/src/github.com/astaxie/beego/logs/log.go:174:2: error: expected declaration
  bl.wg.Add(1)
  ^
golib/src/github.com/astaxie/beego/logs/log.go:175:2: error: expected declaration
  go bl.startLogger()
  ^
golib/src/github.com/astaxie/beego/logs/log.go:176:2: error: expected declaration
  return bl
  ^
golib/src/github.com/astaxie/beego/logs/log.go:177:1: error: expected declaration
 }
 ^
golib/src/github.com/astaxie/beego/logs/log.go:170:25: error: missing return at end of function
   New: func() interface{} {
                         ^

出现这个问题 怎么解决呢 有知道的吗

**Comment by astaxie** [comment]
update Go version

**Comment by yuandong17** [comment]
thinks  !!  @astaxie 
已解决,情况是这样的; 
今天在部署服务器,版本Ubuntu14.14的,apt golang  只是1.2  为了保持与本地的go版本1.9.2,选择了源码安装;
出现这个问题 安装的go版本 也是1.9.2  是参照 https://github.com/northbright/Notes/blob/master/Golang/china/install-go1.6-from-source-on-centos7-in-china.md
clone了一个git库  checkout 1.9.2来进行安装的,安装也出现了"ALL TESTS PASSED"字样,安装beego,结果就是上面那样;

后面去https://studygolang.com/  下载了一个 linux的集成包
同样是1.9.2  从新解压 -> ./all.bash -> 配置环境变量 后,安装beego结果成功了...

**Comment by astaxie** [comment]
我估计你源码安装失败了
