### ISSUE TITLE
大神,url中 /?a=lyd&b=27 不支持在get方法中用.GetSting(),或者.Ctx.Input.Param() 吗

### ISSUE THREAD

**Issue by yuandong17** [astaxie/beego#2927]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee 1.9.1
go 1.9.2

2. What operating system and processor architecture are you using (`go env`)?
ubuntu 14.14

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
uri 可以拿到上述的 /?a=lyd&b=27
url  就是/ 没有后面的字符串
现在用 getstring 或者 .Ctx.Input.Param()  拿不到 a 和b的值,有什么办法吗

5. What did you see instead?

**Comment by yuandong17** [comment]
已解决!
参考 https://beego.me/docs/mvc/controller/params.md
用的示例中的数据绑定

支持从用户请求中直接数据 bind 到指定的对象,例如请求地址如下

?id=123&isok=true&ft=1.2&ol[0]=1&ol[1]=2&ul[]=str&ul[]=array&user.Name=astaxie

**Comment by shenzhuo** [comment]
请问, 对于 id=KRj+WwMyavJM4tt770WumA== 怎么处理?

Bind 和 getstring 都会导致 + 没有
