### ISSUE TITLE
从百度编辑器取出来的内容，post到beego获取，会被截断

### ISSUE THREAD

**Issue by alicksnake22** [astaxie/beego#2930]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9.0

2. What operating system and processor architecture are you using (`go env`)?
mac

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Get ueditor content from post request

4. What did you expect to see?
When use [this.GetString("content")] to get the html content,the content is cutted.

5. What did you see instead?
Want to get the whole html content from editor

**Comment by zituocn** [comment]
在代码中输出 this.GetString("content")的值，查看。
