### ISSUE TITLE
sum

### ISSUE THREAD

**Issue by lingwei0604** [astaxie/beego#2931]
how to sum column in beego?

**Comment by vvelikodny** [comment]
@lingwei0604 bad question, community need full detail of issue

**Comment by lingwei0604** [comment]
@vvelikodny  i try to find what about this issue, but seem to be no answer. some links ？ thanks.

**Comment by vvelikodny** [comment]
@lingwei0604 issue is no issue in your description. when you write issue it's needed to provide some code and add good description of the problem.
