### ISSUE TITLE
go get command ( as per documentation )  the command didnt work. 

### ISSUE THREAD

**Issue by jpca999** [astaxie/beego#2935]
![image](https://user-images.githubusercontent.com/1026325/32959751-a5e97510-cb90-11e7-9857-ab623d0cc390.png)

![image](https://user-images.githubusercontent.com/1026325/32959793-c38cc57c-cb90-11e7-9f63-64aa46ca4c66.png)

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
no idea

**Comment by vvelikodny** [comment]
check you $GOPATH, code should be downloaded $GOPATH/src
