### ISSUE TITLE
Beego didnt install on my mac 

### ISSUE THREAD

**Issue by jpca999** [astaxie/beego#2937]
I ran : 
go get -u github.com/astaxie/beego

nothign came up & I can't do anything if i type bee 

![image](https://user-images.githubusercontent.com/1026325/32976241-457438f0-cbe0-11e7-98e1-8be4c7945149.png)

○ go version
go version go1.9.2 darwin/amd64

**Comment by kobehaha** [comment]
Nest step, you should to make and install

**Comment by vvelikodny** [comment]
@jpca999 look at https://github.com/beego/bee, it's separate repo for `bee` command, beego - web framework.
