### ISSUE TITLE
post json RequestBody value always empty

### ISSUE THREAD

**Issue by lornewang** [astaxie/beego#2938]
![image](https://user-images.githubusercontent.com/2064931/32982365-2b6e3b5c-ccbe-11e7-8992-5ef806d207e4.png)

![image](https://user-images.githubusercontent.com/2064931/32982372-5cce58bc-ccbe-11e7-830c-e00780bc3888.png)

![image](https://user-images.githubusercontent.com/2064931/32982379-814d2772-ccbe-11e7-9968-eba753a0b736.png)

bee run ， but the RequestBody value always empty

**Comment by vvelikodny** [comment]
@lornewang Hello! What is `request body` for that controller? Could you, please, show router configuration and request which you push to that controller?

**Comment by chenyangxueHDU** [comment]
set CopyRequestBody = true in app.conf
![image](https://user-images.githubusercontent.com/19216928/33269886-2947c63a-d3bd-11e7-8598-285129d3a8e4.png)

**Comment by DennisMao** [comment]
@lornewang You can find the configuration on  https://beego.me/docs/mvc/controller/config.md#app-config  and the relative tag is 
CopyRequestBody
