### ISSUE TITLE
beego页面发送的请求被修改？url请求不一致

### ISSUE THREAD

**Issue by Candytt** [astaxie/beego#2939]
版本1.9 ，win10 ，i7，golang ，beego 使用 goland 编译器
按照beego博客视频教程，写完用户登录，第一次登录和退出都可以，第二次退出时，发送localhost:8080/login?exit=true的请求，到达服务器就变成了localhost:8080/
![image](https://user-images.githubusercontent.com/33855772/33111956-b057d1f0-cf8b-11e7-843c-9635af8cab1f.png)

![image](https://user-images.githubusercontent.com/33855772/33112061-24cfcfc4-cf8c-11e7-9f7f-c5d4642d230d.png)

**Comment by duanzhichaomy** [comment]
没有重新编译吧，或者服务器做了什么转发
