### ISSUE TITLE
当参数类型为[]*Tag且值为[]时，m2m.add() crash

### ISSUE THREAD

**Issue by huwenbiao** [astaxie/beego#2944]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

> ______
> | ___ \
> | |_/ /  ___   ___
> | ___ \ / _ \ / _ \
> | |_/ /|  __/|  __/
> \____/  \___| \___| v1.9.1
> 
> ├── Beego     : 1.9.0
> ├── GoVersion : go1.9
> ├── GOOS      : darwin
> ├── GOARCH    : amd64
> ├── NumCPU    : 4
> ├── GOPATH    : /Users/huwenbiao/go
> ├── GOROOT    : /usr/local/Cellar/go/1.9/libexec
> ├── Compiler  : gc
> └── Date      : Tuesday, 28 Nov 2017

2. What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/huwenbiao/go"
> GORACE=""
> GOROOT="/usr/local/Cellar/go/1.9/libexec"
> GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yt/ry6bp2r90x96n_337wqpk46m0000gn/T/go-build741392050=/tmp/go-build -gno-record-gcc-switches -fno-common"
> CXX="clang++"
> CGO_ENABLED="1"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"

3. What did you do?
`var tags []*models.Tag`
`// 计算tags，最终tags数组为空`
`plan.Tags = tags`
`m2m := models.O.QueryM2M(&plan, "Tags")`
`fmt.Println(plan.Tags) // result: []`
`_, err = m2m.Add(plan.Tags) // Crash Here`

4. What did you expect to see?

5. What did you see instead?
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] the request url is  /plan_new
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] Handler crashed with error strings: negative Repeat count
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:509
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /usr/local/Cellar/go/1.9/libexec/src/strings/strings.go:587
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /Users/huwenbiao/go/src/github.com/astaxie/beego/orm/db.go:474
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /Users/huwenbiao/go/src/github.com/astaxie/beego/orm/orm_querym2m.go:99
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /Users/huwenbiao/go/src/plan/controllers/plan_new.go:181
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /Users/huwenbiao/go/src/github.com/astaxie/beego/router.go:800
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2619
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1801
> 2017/11/28 16:17:38 [C] [asm_amd64.s:509] /usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337

**Comment by M-Tarasov** [comment]
I have the same problem with custom many-to-many relation table (with an additional column). During a debug session I noticed, that the problem occurs in beego/orm/db.go:471, where `len(values)/len(names)` is equal to 0 due to the additional column (`PlaylistSongs.Added`, see below) in the relation table.

Model:
```go
type Playlist struct {
    ...
    Songs []*Song `orm:"rel(m2m);on_delete(do_nothing);rel_through(.../models.PlaylistSongs)"`
}

type Song struct {
     ...
}

type PlaylistSongs struct {
	Id int
	Playlist *Playlist `orm:"rel(fk)"`
	Song *Song `orm:"rel(fk)"`
	Added time.Time `orm:"auto_now_add;type(datetime);default(now)"`
}

```

**Comment by garenwen** [comment]
me too! help me !

**Comment by Bowenwu1** [comment]
me too! help me!!!!!!
