### ISSUE TITLE
404 静态页面经常404

### ISSUE THREAD

**Issue by lijiansgit** [astaxie/beego#2967]
js css png 页面经常404，重启下服务就好了，没过多久又404了。很尴尬
日志：
2017/12/07 14:25:25 [D] [server.go:2568] |     10.10.0.10| 404 |    144.006µs| nomatch| GET      /static/css/admin.css
2017/12/07 14:25:25 [D] [server.go:2568] |     10.10.0.10| 404 |    154.469µs| nomatch| GET      /static/css/pintuer.css

**Comment by ckahi** [comment]
我也出现了~supervisor  重启的~~请问你解决了吗？

**Comment by lijiansgit** [comment]
暂时没解决，现在用的nginx做的静态文件服务

**Comment by ckahi** [comment]
我找到原因了~原因是用的一个库里面有个os.chdir的代码导致的 你可以看看是否有类似的情况~切换了程序所在目录导致的~
