### ISSUE TITLE
Question about allow header string array 

### ISSUE THREAD

**Issue by jcamilosarmientor** [astaxie/beego#2982]
I have this header array:

```
AllowHeaders: []string{"Origin", "x-requested-with",
			"content-type",
			"accept",
			"origin",
			"authorization",
			"x-csrftoken"},
```

is there any difference between the Origin and origin values?

**Comment by kolesa** [comment]
Where did you find it? 
I think this question is not about beego, it is about http standards. 
Answer: [Field names are case-insensitive. ](https://tools.ietf.org/html/rfc7230#section-3.2)
