### ISSUE TITLE
Error 1205: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by wangzhilin90** [astaxie/beego#2988]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/codis"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build912495663=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

i have a problem that when i use beego/orm module,error like "Error 1205: Lock wait timeout exceeded; try restarting transaction" happened sometimes,when i restart mysql server,it didn't appear for some days,why this happen?

**Comment by okramokol** [comment]
i got this error too. Is there any updates?

**Comment by helloqhq** [comment]
i got this error too.

**Comment by flycash** [comment]
Follow #4238 
Usually, it's not the framework's error but users do not use transaction or DB locks in right way.
