### ISSUE TITLE
同一个客户端使用多协程访问数据库，第一次与数据库建立连接只有一个协程能成功返回数据,怎么解决

### ISSUE THREAD

**Issue by GavinFreedom** [astaxie/beego#2989]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.8.5 windows/amd64
beego v1.9.0

2. What operating system and processor architecture are you using (`go env`)?
window

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
同一个客户端使用多协程访问数据库，第一次建立连接只有一个协程能成功返回数据
A程序：简单的从数据库中查询信息
B程序：产生协程,协程的工作单纯的调用A程序
第一次请求的时候（从来没有和数据库通讯过），只有一个协程能返回数据，其他的都提示：
connection.go:372: invalid connection
这种情况只会出现一次，第二次之后就完全正常了

4. What did you expect to see?
希望多协程查询数据库的时候，不管有没有和数据连接，都能查询到数据

5. What did you see instead?

**Comment by uighurbabbage** [comment]
@GavinFreedom  请问一下 你是处理了这个问题才关闭这个issue的吗 ? 若已解决 你是怎么解决的 ?

**Comment by MrCoderYu** [comment]
@GavinFreedom 请问这个issue解决了吗？我的问题好像是第一次获取连接的时候是invalid connection，后续就正常了
