### ISSUE TITLE
Beego可以把资源编译到包中或exe中么？

### ISSUE THREAD

**Issue by winerQin** [astaxie/beego#301]
比如：我现在有一些图片、JS、样式等各种静态的资源。能不能像Beego的配置文件一样，编译到exe中呢。

之所以有这个需求，是因为开发一个软件的话，想让用户安装到自己的电脑上。会把相关的版权或者广告啊什么的从模板中去掉。非常的不爽啊。

不知道能不能达到这样的要求。

**Comment by lei-cao** [comment]
@winerQin Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by bronze1man** [comment]
I have a private library that can do this job.
I have tried .s file in golang package, base64 encode in golang file, .syso in golang package, fmt.Sprintf("%#v",[]byte{1,2}) in golang package.

I got follow code in the end.
```golang
const lowerhex = "0123456789abcdef"

// 将内存中的字符串输出为golang的字符串,保证二进制安全.
// 目前将二进制数据放在代码里面,效率最高的办法.
// fmt.Sprintf("%#v",s) 这个东西不能保证二进制安全,有 \ufeff bug
func WriteStringToGolang(s string)string{
	if canUseHereDoc(s) {
		return "`"+s+"`"
	}else{
		outBuf:=&bytes.Buffer{}
		outBuf.WriteByte('"')
		l:=len(s)
		i:=0
		for {
			if i>=l{
				outBuf.WriteByte('"')
				return outBuf.String()
			}
			b:=s[i]
			switch b {
			case '\a':
				outBuf.WriteString(`\a`)
			case '\b':
				outBuf.WriteString(`\b`)
			case '\f':
				outBuf.WriteString(`\f`)
			case '\n':
				outBuf.WriteString(`\n`)
			case '\r':
				outBuf.WriteString(`\r`)
			case '\t':
				outBuf.WriteString(`\t`)
			case '\v':
				outBuf.WriteString(`\v`)
			case '\\':
				outBuf.WriteString(`\\`)
			case '"':
				outBuf.WriteString(`\"`)
			default:
				if b>=0x20 && b<=0x7e {
					// TODO 加入更多可以解析的东西,以便提高存储性能,也提高可读性.
					outBuf.WriteByte(b)
				}else {
					outBuf.WriteString(`\x`)
					outBuf.WriteByte(lowerhex[s[i] >> 4])
					outBuf.WriteByte(lowerhex[s[i] & 0xF])
				}
			}
			i++
		}
	}
}

func canUseHereDoc(s string)bool{
	l:=len(s)
	i:=0
	for {
		if i>=l{
			return true
		}
		result,size:=utf8.DecodeRuneInString(s[i:])
		if result==utf8.RuneError{
			return false
		}
		if result=='`'{
			return false
		}
		if result==65279{ // \ufeff
			return false
		}
		i+=size
	}
}
```

**Comment by fuxiaohei** [comment]
@bronze1man 

I think we can learn the way from 

https://github.com/jteeuwen/go-bindata
https://github.com/GeertJohan/go.rice

**Comment by xiewei-wayne** [comment]
期待这个功能。

**Comment by zhangfuwen** [comment]
这个功能的关闭是确定不做了吗？还是已经做完了？

**Comment by astaxie** [comment]
还没有开始做

**Comment by LiHuiWithHope** [comment]
如果beego框架还引用了其他的框架（包含很多静态文件），那么这个框架的静态文件是无法打包进来的（即使是bee pack），请问有什么好的办法吗？

**Comment by Sherlock-Holo** [comment]
Beego use `os.Lstat` `os.Open` to open the static resources and views template, http://godoc.org/code.google.com/p/go.tools/godoc/vfs/mapfs can provide a `vfs.FileSystem` and then supports `Lstat` `Open` `Redir` . I think beego can add `BuildinFileSystem` field in `BConfig` , when call `os.Xxx` , we can check if we set `BuildinFileSystem` field and then use it.

So we need something to enable this feature, we can generate a go file and it has `func init()` to set `BConfig.BuildinFileSystem`

**Comment by Sherlock-Holo** [comment]
[the generated code template](https://github.com/Sherlock-Holo/resources-packer/blob/master/beegoTemplate.go)
