### ISSUE TITLE
beego log doesn't print formatting strings well

### ISSUE THREAD

**Issue by neilzhangy** [astaxie/beego#3011]
beego.Info("Number is %d", 15)
I expect it should print "Number is 15" in stdout.
But it actually prints "2017/12/29 16:37:21.363 [I] Number is %d 15" in stdout.

In the source code of beego/logs/log.go, the function formatLog doesn't pass the right formatting string to fmt.Sprintf.

**Comment by vladvlc** [comment]
I think beego.Info method acts like a fmt.Printl not like fmt.Printf
