### ISSUE TITLE
为什么go get下载找不到这些方法

### ISSUE THREAD

**Issue by jtyoui** [astaxie/beego#3019]
go get -u github.com/astaxie/beego
# github.com/astaxie/beego
D:\ideaCode\src\github.com\astaxie\beego\router.go:704: undefined: http.MethodGet
D:\ideaCode\src\github.com\astaxie\beego\router.go:704: undefined: http.MethodHead
D:\ideaCode\src\github.com\astaxie\beego\router.go:777: undefined: http.MethodPost
D:\ideaCode\src\github.com\astaxie\beego\router.go:778: undefined: http.MethodPut
D:\ideaCode\src\github.com\astaxie\beego\router.go:780: undefined: http.MethodPost
D:\ideaCode\src\github.com\astaxie\beego\router.go:780: undefined: http.MethodDelete
D:\ideaCode\src\github.com\astaxie\beego\router.go:781: undefined: http.MethodDelete
D:\ideaCode\src\github.com\astaxie\beego\router.go:817: undefined: http.MethodPost
D:\ideaCode\src\github.com\astaxie\beego\router.go:817: undefined: http.MethodDelete
D:\ideaCode\src\github.com\astaxie\beego\router.go:817: too many errors

**Comment by 1225358814** [comment]
可以试试 备份当前
D:\ideaCode\src\github.com\astaxie\beego\
这个目录 然后删除这个目录
再用管理员权限go get
