### ISSUE TITLE
[orm]支持事务闭包(回调)

### ISSUE THREAD

**Issue by bronze1man** [astaxie/beego#303]
在ormer里面提供下列接口.
```go
func transactionCallback(f func()error) error
```

**Comment by lei-cao** [comment]
@bronze1man Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  closeable or a new PR? @bronze1man  do you want to have a PR for it?

**Comment by bronze1man** [comment]
It is ok to close, i do not use beego right now.

**Comment by astaxie** [comment]
I will close it as it's not a really requirement
