### ISSUE TITLE
beego应用部署到服务器咨询

### ISSUE THREAD

**Issue by yingyan003** [astaxie/beego#3033]
你好。我看官网文档的独立部署过程是：
1.编译应用成可执行文件。如 go install appname（应用名）
2. 建个文件夹，如beepkg，将编译后的appname(可执行文件)和配置目录conf文件夹copy到beepkg>
然后nohup appname &即可。

我有几个问题：
1.如果我要将应用部署于公司的测试或生产环境，直接这样操作就可以了么？服务器上是否需要安装bee工具等呢？
2.beego有个打包的命令：bee pack，在部署时需要用到打的这个包么？
3.官方文档说的太少了，新手还劳烦指教一下

**Comment by shihp** [comment]
可以参考下我的博客,关于部署方面.
[beego 部署方案](https://www.shihuipengx.com/2018/04/18/go/beego%20%E5%BA%94%E7%94%A8%E9%83%A8%E7%BD%B2/)
