### ISSUE TITLE
beego能不能通过数据库表直接生成models？

### ISSUE THREAD

**Issue by pdeep** [astaxie/beego#3052]
每次都一个一个写models，数据库修改又要改models，能不能快速同步，由数据库表直接生成models？

**Comment by wadelee1986** [comment]
同问 ？？能不能？

**Comment by liasica** [comment]
@pdeep @wadelee1986 https://beego.me/docs/install/bee.md#generate-%E5%91%BD%E4%BB%A4

**Comment by lwhile** [comment]
@liasica  thanks for your help.
