### ISSUE TITLE
app.conf is ignored when exe is called outside of parent dir of conf/app.conf

### ISSUE THREAD

**Issue by jasin** [astaxie/beego#3055]
I was a little confused at first, but finally discovered that when calling my executable outside of of the src directory app.conf was being ignored. Or for that matter any dir the shell was in that did not contain a conf/app.conf file when the executable was called.
IE
this works
`/src/github.com/jasin/beegoApp/$ beegoApp`
this ignores app.conf, because the shell current directory does not contain conf/app.conf
`~/$ beegoApp`

Is this a limitation of go itself or just the beego framework? Seems to me the compiled beego app should search the executable directory, **NOT** the current directory of the shell calling the app.  Am I missing something here?
Edit: removed a conflicting statement

**Comment by bakanis** [comment]
It is not a limitation. It is a feature. It should look for a configuration at the place it is called from because let's say you had several clones of the same compiled application with different configuration files and ALL of them were looking for a config at the same one path it was compiled.

**Comment by jasin** [comment]
That is not what I said, try again

The application should look in directory of the calling application. It makes no sense to look for a config in the shells CWD if one plans to use the shells feature to add an application path to $PATH. This also breaks `go install` . Hardly a feature to the Golang
