### ISSUE TITLE
程序设计 serviceA中一个方法会调用daoA 和 daoB 各一个insert方法  [program design question]

### ISSUE THREAD

**Issue by wangping886** [astaxie/beego#3057]
我对我的程序分成service ,dao层以便代码复用。
serviceA中一个方法会调用daoA 和 daoB 各一个insert方法
method code  eg:
`func InsertMenu(menu models.Menu) (int64, error) {`
	`o := orm.NewOrm()`
	`o.Using("default")`
	`if id, err := o.Insert(&menu); err != nil {`
	`return nil, err`
	`}`
	`return id, nil`
`}`
问题:我如何在serviceA中控制事务？
在serviceA中调用o := orm.NewOrm()
	                     o.Using("default")  ？然后把o分别传递到daoA daoB中？

再如果是serviceA中调用serviceB也传递参数o。  难道这个o要在controller中产生
maybe i can
`func InsertMenu(menu models.Menu,o *orm.Ormer) (int64, error) {`
        `if o==nil{`
              `o:=orm.NewOrm()`
              `o.Using("default")`
        `}`	 
    ` return o.Insert(&menu); `
`}`

**Comment by szyhf** [comment]
我们也踩过这个坑，现在采用的方案是使用context.Context注入ormer。

大致思路：
我们所有涉及的业务、数据流程的代码，第一个参数都是context.Context。
处理http请求时，将ormer注入到context中。
在类似你的dao层中，再把ormer拿出来。
通过context可以很好的在复杂的业务流程中，处理事务。
包括并发场景。

> 当然我们还根据业务需求做了额外的封装，这样便于我们在需要时替换ormer，这个跟实际需求有关。

如果上边看不太明白，请先了解一下context.Context的用法。

代码可以参考一下grpc或者etcd的接口。

**Comment by wangping886** [comment]
我理解的你的意思大致是这样吧
    同一个请求线程将ormer注入到context，将需要在同一个事务的方法执行使用同一个数据路连接。java 的spring事务也是使用了类似这样的思路实现。




在 2018-04-12 11:00:12，"Back Yu" <notifications@github.com> 写道：


我们也踩过这个坑，现在采用的方案是使用context.Context注入ormer。

大致思路：
我们所有涉及的业务、数据流程的代码，第一个参数都是context.Context。
处理http请求时，将ormer注入到context中。
在类似你的dao层中，再把ormer拿出来。
通过context可以很好的在复杂的业务流程中，处理事务。
包括并发场景。

当然我们还根据业务需求做了额外的封装，这样便于我们在需要时替换ormer，这个跟实际需求有关。

如果上边看不太明白，请先了解一下context.Context的用法。

代码可以参考一下grpc或者etcd的接口。

**Comment by flycash** [comment]
这个问题其实要分两方面来讨论，第一个就是在哪里创建这个事务。在controller层面上创建并不是一个很好的做法。对于这种调用多个service实现一个功能的来说，应该有一个aggregate service，这个aggregate service负责创建事务。无法避免的是，这个事务依旧需要向下传递到service a或者service b里面。
