### ISSUE TITLE
命令行生成commentsRouter_controllers.go，debug生成commentsRouter_.go

### ISSUE THREAD

**Issue by yuedun** [astaxie/beego#3058]
使用`bee run`命令生成的是`commentsRouter_controllers.go`文件
使用goland工具调试生成的却是`commentsRouter_.go`文件
这是什么原因？

**Comment by houwenbiao** [comment]
怎么没有回复?

**Comment by maxshine** [comment]
> 使用`bee run`命令生成的是`commentsRouter_controllers.go`文件
> 使用goland工具调试生成的却是`commentsRouter_.go`文件
> 这是什么原因？

请看下你的代码里注解controller所在package路径和你的app可执行文件的路径

beego的逻辑，用的是这两者的相对路径作为后缀。

我猜测，可能goland做debug时候产生的app可执行文件路径和bee run是不一样的
