### ISSUE TITLE
go 1.9版本map并发安全,cache里的memory的锁是不是可以去掉了

### ISSUE THREAD

**Issue by nicle-lin** [astaxie/beego#3059]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by lwhile** [comment]
要考虑到go1.9以下版本的兼容性，目前不可能去掉
