### ISSUE TITLE
如何根据数据库表生成对应的restful风格API?

### ISSUE THREAD

**Issue by V-Zhou** [astaxie/beego#3061]
在知乎上看到作者提到这个问题  已经把生成API工作大部分给自动化了

**Comment by uighurbabbage** [comment]
请你看bee help generator 的帮助信息
在这里给你几个命令  你调整相关信息直接运行看看效果
bee api bgapi -driver="mysql" -conn="root:root@tcp(127.0.0.1:3306)/test" 
bee run -gendoc=true -downdoc=true
第一个以你给的默认数据库信息为主创建一个api 应用 自动生成所有路由 模型 控制器等。
 >  你还可以使用  bee generate appcode -driver="mysql" -conn="root:root@tcp(127.0.0.1:3306)/test" -level=3 的方式达到数据库表自动生成mc和router的目的 

第二个以文档，swagger模式运行你的程序  
访问 localhost:8080/swager 你就知道了

建议你好好看官方文档  文档里这些都有

**Comment by Men-Z** [comment]
E:\2018\GoDev\src>bee generate appcode -driver="mysql" -conn="root:root@tcp(127.
0.0.1:3306)/test" -level=3
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2018/04/26 10:08:54 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2018/04/26 10:08:54 INFO     ▶ 0002 Using 'root:root@tcp(127.0.0.1:3306)/test' a
s 'SQLConn'
2018/04/26 10:08:54 INFO     ▶ 0003 Using '' as 'Tables'
2018/04/26 10:08:54 INFO     ▶ 0004 Using '3' as 'Level'
2018/04/26 10:08:54 INFO     ▶ 0005 Analyzing database tables...
2018/04/26 10:08:54 FATAL    ▶ 0006 Could not show tables: The authentication pl
ugin is not supported.

请问这是什么原因呢

**Comment by uighurbabbage** [comment]
@Men-Z  数据库创建了么 ？ 表呢 ？
你创建个test 库 里面放几个表再试试么 
一般是可以用beego 的migrate功能先把库和表准备好 你可以手动先给它它需要的东西么
啥都不给 它获取不到任何东西 怎么给你生成路由 xxxx 呢

**Comment by Men-Z** [comment]
@uighurbabbage 表已经创建了，这里面不能上图，我用root账号创建了一个test数据库，然后创建了一个非常简单的test1表，但是就是一直报错

**Comment by Men-Z** [comment]
@uighurbabbage 我看官方文档还有个参数tables，
E:\2018\GoDev\src>bee generate appcode  -tables="test1" -driver="mysql" -conn="r
oot:root@tcp(127.0.0.1:3306)/test" -level=3
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2018/04/26 10:50:22 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2018/04/26 10:50:22 INFO     ▶ 0002 Using 'root:root@tcp(127.0.0.1:3306)/test' a
s 'SQLConn'
2018/04/26 10:50:22 INFO     ▶ 0003 Using 'test1' as 'Tables'
2018/04/26 10:50:22 INFO     ▶ 0004 Using '3' as 'Level'
2018/04/26 10:50:22 INFO     ▶ 0005 Analyzing database tables...
2018/04/26 10:50:22 FATAL    ▶ 0006 Could not query INFORMATION_SCHEMA for PK/UK
/FK information

加上了还是报错，是我数据库使用有问题么？我先看看migrate

**Comment by Men-Z** [comment]
@uighurbabbage
mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| test1          |
+----------------+
1 row in set

**Comment by sunnyregion** [comment]
你必须有一个id列

**Comment by GaoGeGIT** [comment]
好像和mysql的版本有关系 我换了个版本
