### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by WuHanMuMu** [astaxie/beego#3068]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go :1.10 

2. What operating system and processor architecture are you using (`go env`)?
win10 

3. What did you do?
 excute '' go get -u github.com/beego/bee '' 

# runtime
C:\Go\src\runtime\mstkbar.go:244:41: undefined: stkbar
C:\Go\src\runtime\utf8.go:16:17: surrogateMin redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:49:17
C:\Go\src\runtime\utf8.go:17:17: surrogateMax redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:50:17
C:\Go\src\runtime\utf8.go:21:7: t1 redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:31:33
C:\Go\src\runtime\utf8.go:22:7: tx redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:32:33
C:\Go\src\runtime\utf8.go:23:7: t2 redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:33:33
C:\Go\src\runtime\utf8.go:24:7: t3 redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:34:33
C:\Go\src\runtime\utf8.go:25:7: t4 redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:35:33
C:\Go\src\runtime\utf8.go:26:7: t5 redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:36:33
C:\Go\src\runtime\utf8.go:28:10: maskx redeclared in this block
        previous declaration at C:\Go\src\runtime\rune.go:43:24
C:\Go\src\runtime\mstkbar.go:244:41: too many errors
get this

**Comment by DennisMao** [comment]
@WuHanMuMu  try to reinstall your goroot ?

**Comment by WuHanMuMu** [comment]
reinstall go , then problem solved
