### ISSUE TITLE
Upgrade to golang 1.10

### ISSUE THREAD

**Issue by miadabrin** [astaxie/beego#3069]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.9.2
GoVersion : go1.10
2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build654371397=/tmp/go-build -gno-record-gcc-switches"
```

3. What did you do?
Tried Using beego with golan version 1.10

4. What did you expect to see?
I expect the integration to be without any problems

5. What did you see instead?
GOPATH not detected by beego and also too many commentsrouter files autogenerated (3)

**Comment by arma7x** [comment]
I'm using beego 1.9.2 on golang 1.10. No issues at all

**Comment by miadabrin** [comment]
@arma7x The gopath was not recognized unless you set it manually through bashrc. The was no issue with 1.9.2

**Comment by arma7x** [comment]
GOROOT ?

**Comment by arma7x** [comment]
So your problem solve ?
