### ISSUE TITLE
`json` tag comment failed for models

### ISSUE THREAD

**Issue by thenlai** [astaxie/beego#3092]
## Environment:

 - Beego: 1.9.2
 - Go: go1.8.3
 - OS: macOs

## Troubles

Here is how I define my model:

```go
type User struct {
	Id       int64 `json:"id"`
	Name     string `json:"name" orm:"unique;size(16)"`
	Nickname string `json:"nickname" orm:"size(64)"`
	Password string `json:"password"`
	Email    string `json:"email" orm:"size(64)"`
	Role     int    `json:"role" orm:"default(1)"`
	Gender   int8   `json:"gender" orm:"default(0)"`
	Profile  string `json:"profile" orm:"size(256)"`

	CreatedAt    time.Time `json:"createdAt"`
	Lastlogin    time.Time `json:"lastLogin" orm:"auto_now_add;type(datetime)"`
	LastLogintIP     string `json:"lastLoginIp" orm:"size(32)"`
	LoginCount int64  `json:"loginCount"`
	Authkey    string `json:"authKey" orm:"size(10)"`
	Active     int8   `json:"active"`
}
```

when I query the user list with:

```go
db.Query().OrderBy("id").Limit(pageSize, offset).Values(&list, "id", "name", "email", "profile")
```

and return it with 	`con.Data["json"] = ...`, I expected to get JSON data with lower case keys. Now I get upper case keys instead.

**Comment by DennisMao** [comment]
it seems no exception on your structure. please post code of [controller] layer . 

// controller/default.go
`package controllers

import (
	"time"

	"github.com/astaxie/beego"
)

type MainController struct {
	beego.Controller
}

type User struct {
	Id       int64  `json:"id"`
	Name     string `json:"name" orm:"unique;size(16)"`
	Nickname string `json:"nickname" orm:"size(64)"`
	Password string `json:"password"`
	Email    string `json:"email" orm:"size(64)"`
	Role     int    `json:"role" orm:"default(1)"`
	Gender   int8   `json:"gender" orm:"default(0)"`
	Profile  string `json:"profile" orm:"size(256)"`

	CreatedAt    time.Time `json:"createdAt"`
	Lastlogin    time.Time `json:"lastLogin" orm:"auto_now_add;type(datetime)"`
	LastLogintIP string    `json:"lastLoginIp" orm:"size(32)"`
	LoginCount   int64     `json:"loginCount"`
	Authkey      string    `json:"authKey" orm:"size(10)"`
	Active       int8      `json:"active"`
}

func (c *MainController) Get() {

	c.Data["json"] = User{Id: 1, Name: "john"}
	c.ServeJSON(false)
}
`

![image](https://user-images.githubusercontent.com/15226239/38235692-94cc0998-3754-11e8-84aa-37ae3adc9ae1.png)
