### ISSUE TITLE
有关于beego的微信群或qq群吗

### ISSUE THREAD

**Issue by mikeweiwei** [astaxie/beego#3096]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by lwhile** [comment]
beego 实战群（QQ）：258969317

问题如果解决的话请关闭 issue
