### ISSUE TITLE
关于路由设置无法访问的一点疑问

### ISSUE THREAD

**Issue by pencilso** [astaxie/beego#3110]
摘自官网试例
beego.Router("/api/list",&RestController{},"*:ListFood")
beego.Router("/api/create",&RestController{},"post:CreateFood")
// 以下是我编写的代码  路由配置
    beego.Router("/", &controllers.MainController{})
    beego.Router("/api/user",&user.UserController{},"get:userInfo")

//下面是 Controller代码
package user
import (
	"github.com/astaxie/beego"
)
type UserController struct {
	beego.Controller
}
func (c *UserController) userInfo() {
	c.Ctx.WriteString("Hello  user")
}
//我不知道我tm哪里写错了...一直运行失败

//第二个问题 使用自动匹配路由
beego.AutoRouter(&user.UserController{}) 
//运行倒没报错，可是，我怎么访问Method????
//该Controller下 有一个userInfo方法

/user/userInfo   //无法访问  返回404
/userController/userInfo  //无法访问 返回404
/UserController/userInfo  //无法访问  返回404

**Comment by oknixus** [comment]
如果这样用`beego.Router("/api/user",&user.UserController{},"get:userInfo")`代码就直接不编译了，这个问题搜了很多地方，都找不到解决方法，着急！！！

**Comment by pencilso** [comment]
我也不知道.....  烦死了

**Comment by smallfish** [comment]
@pencilso 仔细看下错误，里面有描述的。函数名要大写字母开头，`userInfo` 改成 `UserInfo`

**Comment by KeKe-Li** [comment]
有错误，要区分大小写呢！

2018-04-09 10:16 GMT+08:00 陈小玉 <notifications@github.com>:

**Comment by oknixus** [comment]
@smallfish 大哥，帮忙看下我的问题，谢谢！

**Comment by pencilso** [comment]
谢谢楼上两位老哥，搞定了。

**Comment by oknixus** [comment]
是的，`userInfo` 改成 `UserInfo`后， 自定义方法及RESTful规则 这个路由的实现方式OK了
但是这种`beego.Include(&CMSController{})`直接报错：Unresolved type CMSController
真是不知道是怎么回事，官方文档也是这么写的，没看到哪里有问题
详细信息[#3111](https://github.com/astaxie/beego/issues/3111)
