### ISSUE TITLE
注解路由 Unresolved type CMSController，期待您百忙中给看看，谢谢！

### ISSUE THREAD

**Issue by oknixus** [astaxie/beego#3111]
Please answer these questions before submitting your issue. Thanks!

├── Beego     : 1.9.2
├── GoVersion : go1.10.1
├── GOOS      : darwin
├── GOARCH    : amd64

macOS High Sierra 10.13.4

按照官方文档上的[示例代码](https://beego.me/docs/mvc/controller/router.md#%E6%B3%A8%E8%A7%A3%E8%B7%AF%E7%94%B1)controller 是通过命令`bee generate controller CMS`生成的，然后删除了默认的各种方法，只保留了和示例代码一致的内容：
```
package controllers

import (
	"github.com/astaxie/beego"
)

// CMSController operations for CMS
type CMSController struct {
	beego.Controller
}

// URLMapping ...
func (c *CMSController) URLMapping() {
	c.Mapping("StaticBlock", c.StaticBlock)
	c.Mapping("AllBlock", c.AllBlock)
}

// @router /staticblock/:key [get]
func (this *CMSController) StaticBlock() {

}

// @router /all/:key [get]
func (this *CMSController) AllBlock() {

}

```

router.go代码：
```
package routers

import (
	"quickstart/controllers"
	"github.com/astaxie/beego"
)

func init() {
	beego.Router("/", &controllers.MainController{})
	beego.Include(&CMSController{})
}
```
然而GoLand报错了：
![图片](https://i.loli.net/2018/04/08/5aca34c8672fd.jpg)
在`bee run `的时候，也报错了：
```
routers/router.go:23:17: undefined: CMSController
2018/04/08 23:12:08 ERROR    ▶ 0003 Failed to build the application: # quickstart/routers
routers/router.go:23:17: undefined: CMSController
```
搜了很多Google、segmentfault、studygolang，都没有找到我遇到的这个错误，在QQ群里、微信群里，也没有得到解决，所以只好来这里发个issue了
知道您维护beego的框架很辛苦，非常感谢！
希望您能在百忙之中，抽点时间帮忙给看看，也希望文档能够多多完善一些，有些地方真的看不懂
谢谢！

**Comment by willxm** [comment]
&controllers.CMSController{}

**Comment by oknixus** [comment]
暂时不学习beego了
