### ISSUE TITLE
Httplib包缺少PATCH方法

### ISSUE THREAD

**Issue by szhu57** [astaxie/beego#3118]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by szhu57** [comment]
Httplib包缺少PATCH方法

**Comment by szyhf** [comment]
其实get、post等方法都是这样封装一下而已，patch用的人太少了，你可以这样用：
```
patchRequest := httplib.NewBeegoRequest(url, "PATCH")
```
