### ISSUE TITLE
How to use controller custom abort for rest api response? 

### ISSUE THREAD

**Issue by mytc** [astaxie/beego#3123]
Normally when I use controller custom abort, it will only write response body strings. 
How do I use json response for this? 

Right now I writing the response like this:
```
c.Data["json"] = "json struct respon"
c.ServeJSON()
c.Abort("500")
```

But this will give me this warning:

> [HTTP] http: multiple response.WriteHeader calls

Any idea how?

**Comment by BorisBorshevsky** [comment]
This is because both `c.ServeJSON()` and `c.Abort("500")` will call WriteHeader...
Abort is used to stop the execution of the current request.
For setting the error code can use the output object.

**Comment by mytc** [comment]
@BorisBorshevsky , I knew they call WriteHeader on both methods. I did this because so far there are no official way abort the request using json response. 

Sure I can use output object to write the response. But what if I want to exit the execution in Prepare() or Init()? 

However I have come with something like this 

```
func (c *Controller) CustomJsonAbort(status int, res interface{}) {
	c.Ctx.ResponseWriter.WriteHeader(status)
	c.Ctx.Output.JSON(res, true, false)
	panic(errors.New("Json Abort"))
}
```
It does the job, But the panic will output the the log in the server. 

> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] the request url is  /login
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] Handler crashed with error Json Abort
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /home/mypc/.gvm/gos/go1.9.4/src/runtime/asm_amd64.s:509
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /home/mypc/.gvm/gos/go1.9.4/src/runtime/panic.go:491
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /mypc/go/src/vms/controllers/authen.go:151
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /mypc/go/src/vms/controllers/authen.go:71
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /mypc/go/src/github.com/astaxie/beego/router.go:831
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /home/mypc/.gvm/gos/go1.9.4/src/net/http/server.go:2619
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /home/mypc/.gvm/gos/go1.9.4/src/net/http/server.go:1801
> 2018/04/19 01:38:24.751 [C] [asm_amd64.s:509] /home/mypc/.gvm/gos/go1.9.4/src/runtime/asm_amd64.s:2337

This is not a big deal, but I would like it better not output this warning, there are no meaning. 
I have looked into the source codes of CustomAbort. It does use panic() to abort the request, but without the warning. This is what I want to achieve.

**Comment by BorisBorshevsky** [comment]
I think what you are looking for is this: 
https://beego.me/docs/mvc/controller/errors.md

and more specifically, ErrorController

**Comment by mytc** [comment]
@BorisBorshevsky , Look like is what I wanted.

Thanks.
