### ISSUE TITLE
go get 失败

### ISSUE THREAD

**Issue by zzlhr** [astaxie/beego#3125]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
OS:  windows7
git version :  git version 2.16.2.windows.1
go version: go version go1.10.1 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
go get github.com/astaxie/beego
# cd .; git clone https://github.com/astaxie/beego C:\Users\Administrator\go\src\github.com\astaxie\beego
Cloning into 'C:\Users\Administrator\go\src\github.com\astaxie\beego'...
fatal: unable to access 'https://github.com/astaxie/beego/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
建议尝试用代理
