### ISSUE TITLE
启用graceful之后，同一接口访问多次panic了

### ISSUE THREAD

**Issue by nicle-lin** [astaxie/beego#3147]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9.2

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=E:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Go\src\chess008\code\go_server;E:\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build264640291=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
* 在main.go里启用了beego.BConfig.Listen.Graceful = true
* 在一个接口里执行time.sleep(10*time.Second)
* 频繁访问此接口多次
* 然后就看到了如下的painc
2018/05/04 10:32:41 [STOP - Hammer Time] Forcefully shutting down parent
2018/05/04 10:32:41 WaitGroup at 0 sync: negative WaitGroup counter
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 67 [running]:
sync.(*WaitGroup).Wait(0xc0422b8508)
        C:/Go/src/sync/waitgroup.go:133 +0xc2
chess_platform/vendor/github.com/astaxie/beego/grace.(*Server).Serve(0xc0422b84e0, 0x2, 0x2)
        E:/Go/src/chess008/code/go_server/src/chess_platform/vendor/github.com/astaxie/beego/grace/server.go:40 +0x10d
chess_platform/vendor/github.com/astaxie/beego/grace.(*Server).ListenAndServe(0xc0422b84e0, 0x5, 0x10628c0)
        E:/Go/src/chess008/code/go_server/src/chess_platform/vendor/github.com/astaxie/beego/grace/server.go:77 +0x270
chess_platform/vendor/github.com/astaxie/beego.(*App).Run.func2(0xc0424bd598, 0x5, 0xc042035ef0, 0xc04229eaf0)
        E:/Go/src/chess008/code/go_server/src/chess_platform/vendor/github.com/astaxie/beego/app.go:152 +0xd8
created by chess_platform/vendor/github.com/astaxie/beego.(*App).Run
        E:/Go/src/chess008/code/go_server/src/chess_platform/vendor/github.com/astaxie/beego/app.go:145 +0x41b

4. What did you expect to see?

5. What did you see instead?

**Comment by nicle-lin** [comment]
beego现在作者都不维护了吗？

**Comment by DennisMao** [comment]
@nicle-lin  Accepted

**Comment by jianzhiyao** [comment]
在最新版本V2当中已经无法重现。
暂时先关闭此issue，如果有问题可以再次提issue保持联系。
感谢你的参与！
```
package main

import (
	beego "github.com/astaxie/beego/adapter"
	"github.com/astaxie/beego/adapter/context"
	"net/http"
	"time"
)

type MainController struct {
	beego.Controller
}

func (m *MainController) Get() {
	time.Sleep(10 * time.Second)

	data := map[string]interface{}{
		"aa": 1,
		"22": 11,
	}
	m.Ctx.Output.Status = http.StatusForbidden
	m.Ctx.Output.JSON(data, false, false)
}

func main() {
	beego.BConfig.Listen.Graceful = true
	beego.InsertFilter("/ping", beego.BeforeExec, func(context *context.Context) {
	})
	beego.Router("/ping", &MainController{})
	beego.Run(`:8080`)
}
```
