### ISSUE TITLE
mysql connect timeout, then query return "invalid connection"

### ISSUE THREAD

**Issue by cyongxue** [astaxie/beego#3151]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.9.0
├── GoVersion : go1.10.1
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/yongxue/GoglandProjects
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Sunday, 6 May 2018

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yongxue/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yongxue/GoglandProjects"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7h/bv18vsw947l9k9rnxnq5m4xr0000gn/T/go-build610399604=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

import (
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

mysql connect timeout, then query return "invalid connection"

4. What did you expect to see?

5. What did you see instead?

**Comment by fxm5547** [comment]
```
        defaultDB, err := orm.GetDB("default")
	if err != nil {
		beego.Emergency("Get default DB error:" + err.Error())
	}
	defaultDB.SetConnMaxLifetime(3595 * time.Second)
```
help.

**Comment by cyongxue** [comment]
thks

**Comment by fxm5547** [comment]
> > ```
> >         defaultDB, err := orm.GetDB("default")
> > 	if err != nil {
> > 		beego.Emergency("Get default DB error:" + err.Error())
> > 	}
> > 	defaultDB.SetConnMaxLifetime(3595 * time.Second)
> > ```
> > help.
> 
> @fxm5547 Thank you, but why 3595?

welcome, According to your MySQL server wait_timeout setting `SHOW VARIABLES LIKE 'wait_timeout';`
