### ISSUE TITLE
注解路由未生成？

### ISSUE THREAD

**Issue by salamander-mh** [astaxie/beego#3162]
runmode已经设置成了dev，注解也写了，但是未生成commentsRouter.go文件
OS win 10，beego版本 master版本
```
runmode = "dev"
```
router.go
```
func init() {
	ns := beego.NewNamespace("/admin",

		beego.NSNamespace("/contents",
			beego.NSInclude(
				&controllers.ContentController{},
			),
		),
	)
	beego.AddNamespace(ns)
}
```
controllers/content.go
```
type ContentController struct {
	BaseController
}

// @router / [get]
func (this *ContentController) GetContents() {
	defer this.ServeJSON()
        // .....
}
```

**Comment by fulme** [comment]
哥们，解决了么？

**Comment by chenkarl** [comment]
同问，解决了么，补充个细节，我的项目没有放在默认的gopath路径下，放在gopath路径下是可以生成注解路由文件的

**Comment by qxhy123** [comment]
放在gopath之外就不会生成注解路由文件，具体原因还需要看代码

**Comment by qxhy123** [comment]
已经确定如果项目在gopath之外是不会生成注解路由器文件，已经提了pr修复这个问题 #3455 ，坐等谢大merge

**Comment by RanQiwu** [comment]
问题解决周期跨度好大。

**Comment by OneiroXL** [comment]
好吧 原来是没放在GOPATH下的原因

**Comment by Ri773r** [comment]
怎么我项目放在GOPATH下也不能生成的？

**Comment by learnku** [comment]
一年过去了，这个问题都还没有解决？

**Comment by QuincyX** [comment]
同问~

**Comment by 287400117** [comment]
确实是，如果项目不放到GOPATH不会生成commentsRouter.go

**Comment by lx1036** [comment]
用的 go1.13，没在 GOPATH 目录下，怪不得搞了半天都没看到生成 commentsRouter.go，这个问题官方尽早修复啊。

**Comment by chaselen** [comment]
+1 能不能修复一下

**Comment by Jackmrzhou** [comment]
Please check my pull request: #3882

**Comment by sniperxing** [comment]
请尽快修复

**Comment by Herts** [comment]
+1 Go 1.13 Beego 1.12.1 未修复

**Comment by a631807682** [comment]
+1

**Comment by tyzChar** [comment]
+1  Go 1.14 Beego v1.12.1 未修复，go mod使用的 情况下一般不会把项目放在go patch, 啥时候能修复呢

**Comment by flycash** [comment]
人手不足，十分惨淡，有人愿意来搞个PR么？

**Comment by flycash** [comment]
根据大佬说，我们计划在bee v2解决

**Comment by dongfenglong** [comment]
+1 Beego v1.12.2

**Comment by flycash** [comment]
我经过充分实验，在目前bee的版本之下，要生成comment的文件，要满足两个条件：
1. 在GOPATH目录下；
2. 使用go.mod的时候，module不能太复杂。参考我在另外一个issue #4046 下的回答。

**Comment by a631807682** [comment]
这即便不是个bug，也应该是个feat吧。
虽然这个问题确实不好改，尽管都知道问题在哪，但是不好mock不好测，但我认为这起码是未来某个版本应该解决的问题。
 随我个人的观点是，如果自动不好改，是不是可以增加配置文件来操控，而不至于无法生成，大佬觉得呢？ @flycash

**Comment by flycash** [comment]
我重新打开4046这个issue来追踪。我本来是计划在v2版本的web模块重构的时候解决这个问题的。
