### ISSUE TITLE
Orm Ignore Field

### ISSUE THREAD

**Issue by veenutanwar** [astaxie/beego#3163]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9.2

2. What operating system and processor architecture are you using (`go env`)?
Windows 10

3. What did you do?
Create Model
type City struct {
	Id        string    `orm:"column(Id);pk"`
	AName     string    `orm:"column(AName);size(150);null"`
	Alias     string    `orm:"column(Alias);size(50);null"`
	StateId   string    `orm:"column(StateId);size(50);null"`
	Statename string    `orm:"-"`
register it
work fine for insert & update.

If possible, provide a recipe for reproducing the error.

A complete runnable program is good.
qry := " SELECT " +
		"  city.id " +
		", city.aname" +
		", city.alias " +
		", city.stateid " +
		", state.aname as statename " +
		"  from city" +
		" left join state on ( city.stateid = state.id) " +
		" where  city.id  =?"

4. What did you expect to see?
{Id:"0001",AName:"City Name",Alias:"00001",StateId:"10005",Statename:"StateName"}

5. What did you see instead?
{Id:"0001",AName:"City Name",Alias:"00001",StateId:"10005",Statename:""}
Statename field was ignore & not selected in statement each time it return blank.

**Comment by YoungsoonLee** [comment]
Did you solve it? I need it too.

**Comment by DennisMao** [comment]
@veenutanwar According to the docs, you can find `gorm:"-"`  is a setting to tell the orm framework ignore the specified column.
