### ISSUE TITLE
Orm: SQL Query Execution getting wrong.

### ISSUE THREAD

**Issue by fathimashaibal** [astaxie/beego#3167]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`1.9.1`)?

2. What operating system and processor architecture are you using (`Ubuntu 16.04 AMD')?

3. What did you do?
Database used: Postgres
Execution of Alter query came up with an error that too syntatical.
Where in, _ddl.go_ file we could find the end generated SQL Query is not complying with standard queries that of postgresql.

`case "alter":
		{

			sql += fmt.Sprintf("ALTER TABLE `%s` ", m.TableName)
			for index, column := range m.Columns {
				if !column.remove {
					beego.BeeLogger.Info("col")
					sql += fmt.Sprintf("\n ADD `%s` %s %s %s %s %s", column.Name, column.DataType, column.Unsign, column.Null, column.Inc, column.Default)
				} else {
					sql += fmt.Sprintf("\n DROP COLUMN `%s`", column.Name)
				}

				if len(m.Columns) > index {
					sql += ","
				}
			}
			for index, column := range m.Renames {
				sql += fmt.Sprintf("CHANGE COLUMN `%s` `%s` %s %s %s %s %s", column.OldName, column.NewName, column.DataType, column.Unsign, column.Null, column.Inc, column.Default)
				if len(m.Renames) > index+1 {
					sql += ","
				}
			}

			for index, foreign := range m.Foreigns {
				sql += fmt.Sprintf("ADD `%s` %s %s %s %s %s", foreign.Name, foreign.DataType, foreign.Unsign, foreign.Null, foreign.Inc, foreign.Default)
				sql += fmt.Sprintf(",\n ADD KEY  `%s_%s_foreign`(`%s`)", m.TableName, foreign.Column.Name, foreign.Column.Name)
				sql += fmt.Sprintf(",\n ADD CONSTRAINT  `%s_%s_foreign` FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`)  %s %s", m.TableName, foreign.Column.Name, foreign.Column.Name, foreign.ForeignTable, foreign.ForeignColumn, foreign.OnDelete, foreign.OnUpdate)
				if len(m.Foreigns) > index+1 {
					sql += ","
				}
			}
			sql += ";"

			break
		}`

4. What did you expect to see?
Removing the "`" symbol and changing the query as desired served the output.

**Comment by Athul-Raj** [comment]
Yeah, encountered the same issue.
Well, changing the query in ddl.go file helped me.
Hectic syntax issues!!!
