### ISSUE TITLE
goland 开发 beego 开启运行提示Handler crashed with error can't find templatefile in the path:views/index.tpl

### ISSUE THREAD

**Issue by asd12l** [astaxie/beego#3168]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9.3

2. What operating system and processor architecture are you using (`go env`)?
正常

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

2018/05/17 20:19:07.120 [I] http server Running on http://:8080
2018/05/17 20:19:11.694 [C] the request url is  /
2018/05/17 20:19:11.694 [C] Handler crashed with error can't find templatefile in the path:views/index.tpl

4. What did you expect to see?

5. What did you see instead?
beego:can't find templatefile in the path:views/index.tpl

**Comment by asd12l** [comment]
在goland 中“run-》edit configurations”，设置其中的run kind 为file，重点是需要设置output directory目录为自己程序所在目录，例如：go/src/hello 。即可正常运行。

**Comment by guhan121** [comment]
autorender = false  @asd12l  不要让框架帮你渲染

**Comment by flycash** [comment]
提问者没有再反馈，感觉应该是解决了问题，先关闭。
