### ISSUE TITLE
关于多个url进入一个controller处理

### ISSUE THREAD

**Issue by liujianyina** [astaxie/beego#3170]
// @router {'/index','/'} [get]
func (this *CMSController) StaticBlock() {
	this.TplName = "index.html"
}

如果我想要127.0.0.1/index和127.0.0.1/这两个url都进入这个controller处理，这里应该怎样配置？新手上路，请多指教

**Comment by liujianyina** [comment]
另外，注解路由，是需要重启两次应用才能生效吗？还是需要配置？

**Comment by DennisMao** [comment]
https://beego.me/docs/mvc/controller/router.md
