### ISSUE TITLE
希望在orm自动建表中可以添加字段备注

### ISSUE THREAD

**Issue by HWYWL** [astaxie/beego#3172]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego：1.9.2

2. What operating system and processor architecture are you using (`go env`)?
os:Windows 7   cpu：Intel I3-6100

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
数据库自动建表

4. What did you expect to see?
在orm自动建表中可以添加字段备注

5. What did you see instead?
在文档中没看到这个功能

**Comment by NSObjects** [comment]
这个功能在develop分支实现了。 使用 description 标签。

```
Name              string `orm:"column(name);size(255)" description:"用户名称"`
```

**Comment by DennisMao** [comment]
已支持
