### ISSUE TITLE
CopyRequestBody 配置问题

### ISSUE THREAD

**Issue by DoubleWoodH** [astaxie/beego#3176]
配置文件中本来就有 `copyrequestbody = true`，但是不管怎样都无法获取 `RequestBody`，输出 `beego.BConfig.CopyRequestBody` 也是 `false`，而当我在 `main.go` 文件的 `main` 函数中添加一行 `beego.BConfig.CopyRequestBody = true`，就可以获取到 `RequestBody` 了，请问这是什么原因呢？

**Comment by DennisMao** [comment]
1.检查配置文件的目录是否正确。
最便捷排除错误的方式，直接`bee new exampleProject`创建一个新的工程,修改配置文件测试一下。
