### ISSUE TITLE
How to access the session outside of the handler controller function?

### ISSUE THREAD

**Issue by cyantarek** [astaxie/beego#3184]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go: 1.10, Beego: 1.9.2

2. What operating system and processor architecture are you using (`go env`)?
Windows 8.1, 64 Bit

Hello, I want to make a template function that will check if user has certain permissions. In order to do that, I need to access the session value for "user". But I could not find any suitable way to access session outside of the controller handler function in beego.

Please tell me how to do that. Thanks

**Comment by NSObjects** [comment]
```
beego.InsertFilter(pattern string, position int, filter FilterFunc, params ...bool)
```

https://beego.me/docs/mvc/controller/filter.md
