### ISSUE TITLE
controllers\default.go:20:68: cannot use c.Controller.Ctx (type *"github.com/astaxie/beego/context".Context) as type "context".Context in argument to GetApplicationcatalogReleaseStatus:         *"github.com/astaxie/beego/context".Context does not implement "context".Context (missing Deadline method)

### ISSUE THREAD

**Issue by jeffchanjunwei** [astaxie/beego#3186]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.10.1
bee 1.9.2

how can i solve this problem if i want to invoke a func using context.Context in a beego frac

**Comment by jeffchanjunwei** [comment]
@astaxie have any ideas?

**Comment by DennisMao** [comment]
@jeffchanjunwei  it seems that you use different `context` packages.By default, it should be used `github.com/astaxie/beego/context` instead of `context`
