### ISSUE TITLE
orm

### ISSUE THREAD

**Issue by Quieting** [astaxie/beego#3192]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version:1.9 
bee version:1.9

2. What operating system and processor architecture are you using (`go env`)?
mac
经测试 orm 模块， utils.go 202 方法运行结果和预期不符
传入 XxYY将转换成xx_y_y
![image](https://user-images.githubusercontent.com/28435908/41022490-57b38dd6-699c-11e8-9e41-a9e8ca1d2cff.png)

修改方法为，望指正
```
func snakeString(s string) string {
	data := make([]byte, 0, len(s)*2)
	j := true
	num := len(s)
	for i := 0; i < num; i++ {
		d := s[i]
		if i > 0 && d >= 'A' && d <= 'Z' {
			if (s[i-1] >= 'A' && s[i-1] <= 'Z') || (s[i-1] == '_') {
				j = false
			}
			if j {
				data = append(data, '_')
			}
		}
		data = append(data, d)
	}
	return strings.ToLower(string(data[:]))
}

```

![image](https://user-images.githubusercontent.com/28435908/41024236-4240e610-69a1-11e8-95a1-dbbe7979d7e2.png)

**Comment by Quieting** [comment]
@huacnlee

**Comment by DennisMao** [comment]
@Quieting  传入XxYY 正常转为xx_y_y每遇到大写都会增加下划线

**Comment by Quieting** [comment]
@DennisMao 疑惑的是源码内的注释和结果不符
![image](https://user-images.githubusercontent.com/28435908/48535797-71d9f900-e8e7-11e8-90f0-8dc24c0591ea.png)

**Comment by DennisMao** [comment]
@Quieting  好的,我去fix下
