### ISSUE TITLE
Proposal: Wrong use of TrimLeft

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [astaxie/beego#3193]
https://github.com/astaxie/beego/blob/f16688817aa428d10361394015b40d096b680542/parser.go#L183

`func TrimLeft(s string, cutset string) string`
According to the document, `cutset` is a set of runes.
`TrimPrefix` should be better.

**Comment by 360CodeSafe** [comment]
And
https://github.com/astaxie/beego/blob/f16688817aa428d10361394015b40d096b680542/parser.go#L200
