### ISSUE TITLE
how to save an embedded struct as a json string into database

### ISSUE THREAD

**Issue by m3ngyang** [astaxie/beego#3199]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
`1.9.1`

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/usr/local/Cellar/go/gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/Cellar/go/gopath"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.4"
GOTOOLDIR="/usr/local/Cellar/go/1.9.4/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
@m3ngyang  not support!
