### ISSUE TITLE
在win10环境下go install github.com/beego/bee为什么会出这个错误？

### ISSUE THREAD

**Issue by imetroweb** [astaxie/beego#3203]
错误提示：
mkdir C:\Program Files\GO\bin;C:: The filename, directory name, or volume label syntax is incorrect.
是因为C:\Users下中文用户名引起的？求解，谢谢！

**Comment by DennisMao** [comment]
@imetroweb  go install会放在 $GOPATH/bin/bee.exe 下,检查下$GOPATH和$GOROOT是否设置有问题或者放到了中文目录
