### ISSUE TITLE
go get error.

### ISSUE THREAD

**Issue by leeyonglan** [astaxie/beego#3204]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.10.3 

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64  CentOS release 6.6 (Final)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
go get github.com/astaxie/beego

4. What did you expect to see?
no error

5. What did you see instead?
![beego](https://user-images.githubusercontent.com/2076006/41398609-7621cdec-6fea-11e8-8e17-c276ea03b6d6.png)

**Comment by DennisMao** [comment]
@leeyonglan  It seems there're something wrong with your network.
