### ISSUE TITLE
各位大神，请教几个问题 :)

### ISSUE THREAD

**Issue by inhere** [astaxie/beego#3207]
- 怎么获取到请求开始时间，从 ctx 或者 request里
- 在其他地方(非controller、filter里)可以有方法的拿到当前请求的 ctx 吗
- 如果要给每个请求生成一个请求id，放在哪里全局可用呢 
  - 直接放到包的变量里，会不会影响到其他请求上下文

**Comment by AdamGuan** [comment]
1. 请求时间自己记录
2. 没有，要明文传递
3. 可以用golang原本的context，记录id,时间，明文传递

**Comment by inhere** [comment]
哦 :) 感谢

第 3 点，能给点提示代码吗

**Comment by AdamGuan** [comment]
![image](https://user-images.githubusercontent.com/3422160/41886790-7a822b1c-7930-11e8-85f5-63a46485a36d.png)

**Comment by inhere** [comment]
感谢 @AdamGuan
