### ISSUE TITLE
beego swagger如何写多行注释？

### ISSUE THREAD

**Issue by gavin2014** [astaxie/beego#3215]
![image](https://user-images.githubusercontent.com/6220809/42011214-094c1bd8-7ac5-11e8-8b6c-f867c756040b.png)
![image](https://user-images.githubusercontent.com/6220809/42011249-328a03ca-7ac5-11e8-8e13-d422f029dae8.png)
不想使用对象的形式

**Comment by jackywu** [comment]
今天也碰到这个问题了，无解么？ @astaxie
