### ISSUE TITLE
请教一个关于共用session的问题

### ISSUE THREAD

**Issue by ptonlix** [astaxie/beego#3220]
Beego 1.9.2
GoVersion : go1.10.2
GOARCH:amd64

最近在进行一个这样的项目，后台有很多beego框架搭建的APP，而这些APP如果都使用自己的session的话，会造成需要管理很多session的问题。为了方便，我开始设想，如果把这些APP都使用同一个sessionId,那只需要维护一个session就行，但我写了两个测试APP，发现test1去设置，test2去取是取不到相关的session信息的。我使用的是redis去提供session 存储， 我想sessionId是同一个对应相同的redis key，应该是能取到相应的值的。
 所以，想请教一下，有什么方法做到共享session吗？谢谢！

**Comment by aprchen** [comment]
存redis就可以的

**Comment by kxdmichael** [comment]
如果是主域名是同一个，多个二级域名 可以设置cookie共享来共用一个session。 

但是目前beego的session不支持设置session设置的cookie的作用域，需要自己覆盖原cookie值
