### ISSUE TITLE
What's the state of beego?

### ISSUE THREAD

**Issue by kamilgregorczyk** [astaxie/beego#3222]
Hi, What's the state of beego?

- Is it still maintained?
- Do you have any kind of roadmap?
- The issue backlog is growing, are you going to do anything about it ?

**Comment by hxdef2517** [comment]
@kamilgregorczyk seems like it is no longer updating

**Comment by Raggaer** [comment]
To be honest a lot of the issues are not reproducible or provide very little detail.

I been using this framework for quite a long time and the master branch looks stable.

**Comment by kamilgregorczyk** [comment]
Just because it's stable doesn't it mean its is still maintained. There's a big difference between a deprecated or no longer maintained project and still active one. I used beego to for 3 hours just playing with it and I found 3 bugs which were reported long time ago.

**Comment by harkamals** [comment]
Poor documentation is also a big issue.

What are the other good web frameworks, suggestions ?

**Comment by kamilgregorczyk** [comment]
Iris? Although it has a very toxic owner and no one else resolves issues.
Theres also siris but it's not actively maintained.

sob., 21 lip 2018, 16:58 użytkownik Harkamal <notifications@github.com>
napisał:

**Comment by antony66** [comment]
@Raggaer I also thought it is stable but then boom: #3256

**Comment by davleb** [comment]
Could astaxie please give us some comment about it ?

**Comment by DennisMao** [comment]
@astaxie

**Comment by s00500** [comment]
I think there are many duplicate issues, also many that are only in Chinese which makes it really Hard to help...  documentation needs to be updated as well. Overall I really like how complete beego is...

@astaxie What can be done to help?
