### ISSUE TITLE
Validation is required even when you omit the "Required" tag

### ISSUE THREAD

**Issue by pbarnum** [astaxie/beego#3228]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.9.1

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Create a struct with valid tags and set one field without the "Required" tag
```
// The Age field will validate that it is a minimum of 13, but it is not required.
type RegistrationRequest struct {
	Email                string `json:"email" valid:"Required;Email"`
	Password             string `json:"password" valid:"Required;MinSize(8)"`
	FirstName            string `json:"first_name"`
	LastName             string `json:"last_name"`
	Age                  int    `json:"age;omitempty" valid:"Min(13)"`
	TermsOfService       bool   `json:"terms_of_service" valid:"Required;IsTrue"`
}

// Valid will attempt to run validation on the request.
func (r *RegistrationRequest) Valid() bool {
	var valid validation.Validation
	passed, err := valid.Valid(r)
	return passed && err == nil
}
```

4. What did you expect to see?
Validation should pass when the request does not include the age field.

5. What did you see instead?
Validation fails.

**Comment by Raggaer** [comment]
I dont think thats how it works. You are setting a min value of 13 for Age to be valid, so its required

The required field is used for fields that do not have any specific rule but are required, this means your Email field does not need the Required property since `""` wont be a valid email...

**Comment by pbarnum** [comment]
But why would examples then say you should require the field AND ask for a min? It makes more sense that the required field means that it is required in the request body regardless, and then add any refinements afterwards. I, as well as many other apps, have APIs that have multiple request bodies, with multiple request signatures.

**Comment by cxasm** [comment]
有什么更新没 ？
EMAIL 检查，如果我不写Required，应该不检查才对。不然的话，我登录的时候，是不用输入EMAIL字段的，但是还是给我做了检查。

**Comment by pbarnum** [comment]
I haven't heard any updates on this yet. Looking back on this, I'm still curious why it isn't fixed. I have a request where the age field is not required, but I still want it to pass validation if it is provided.

**Comment by pbarnum** [comment]
@DennisMao My request json looks similar to this:
```
{
  "username": "my_user_name",
  "email": "my@email.com",
  "password": "secret",
  "first_name": "First",
  "last_name": "Last",
  "age": "14", // <- This being an optional key/value
  "terms_of_service": "2000-01-01T10:10:10Z"
}
```
I get checking if something is a non-zero value, required has meaning outside of that context alone. I want to check the value only if it has been provided, not "all or nothing".

**Comment by DennisMao** [comment]
@pbarnum It seems you need to write some code for the special validation of those tag you want.
