### ISSUE TITLE
参数配置使用ini格式，怎么能获取到conf/app.conf文件中全部的section名称？

### ISSUE THREAD

**Issue by ha666** [astaxie/beego#3232]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9.0

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
https://beego.me/docs/mvc/controller/config.md
参数配置使用ini格式，怎么能获取到conf/app.conf文件中全部的section名称？

5. What did you see instead?

**Comment by pengan1990** [comment]
同求

**Comment by duffiye** [comment]
maybe `	beego.AppConfig.GetSection()
`, 

#3213
