### ISSUE TITLE
Cors for images file not working

### ISSUE THREAD

**Issue by mytc** [astaxie/beego#3237]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.9.1

2. What operating system and processor architecture are you using (`go env`)?
Linux AMD64

3. What did you do?
Want to display the image from another domain

4. What did you expect to see?
Images can be viewed in another domain

5. What did you see instead?
Image cors problem

> ....has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Here is the filter I use for cors

```
beego.InsertFilter("*", beego.BeforeStatic, cors.Allow(&cors.Options{
		AllowAllOrigins: true,
		AllowMethods:    []string{"*"},
		AllowHeaders:    []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
		ExposeHeaders:   []string{"Content-Length", "Access-Control-Allow-Origin"},
	}))
```

The beego.BeforeStatic not seem to work

**Comment by xuange306** [comment]
我遇到了同样的问题.针对静态文件的cors设置该如何操作?
