### ISSUE TITLE
Different table register for same model

### ISSUE THREAD

**Issue by medyun** [astaxie/beego#3242]
Please answer these questions before submitting your issue. Thanks!

**1. What version of Go and beego are you using (`bee version`)?**
GO: 1.10.1
Beego: 1.9.0

**2. What operating system and processor architecture are you using (`go env`)?**
MacOS
GOARCH="amd64"
GOBIN=""
GOCACHE="Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/User/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/95/sp__d2_j3g53t529fqd6h_rc0000gn/T/go-build126396257=/tmp/go-build -gno-record-gcc-switches -fno-common"

**3. What did you do?**

I want to register model for multiple db table. Because i have multiple language system. So different tables have same structer.

For example: 
```
type User struct {}

func (u * User) TableName() string {
return "user_en"
}

func (u * User) TableName() string {
return "user_fr"
}
```

Can i register model something like that? It is possible?

**4. What did you expect to see?**
I want to register model for different database tables.

5. What did you see instead?

**Comment by antony66** [comment]
Why don't you just write your logic in your `TableName()` func? Like this:

```
func (u * User) TableName() string {
    return "user_" + u.Language
}
```

How beego is supposed to guess table name for a particular User instance?
