### ISSUE TITLE
proposal: Orm增加mysql enum字段支持

### ISSUE THREAD

**Issue by ghost** [astaxie/beego#3246]
官方Issues查到这样的东西
Enum        []interface{}        `json:"enum,omitempty" yaml:"enum,omitempty"`
但是我不知道该如何描述tag来创建 enum字段
MYSQL版本 5.7

**Comment by qq10044375** [comment]
我是真的查阅了文档和ORM Test代码。没有找到可以参考的地方。拜托了。希望闲暇之余能指点下。。。

**Comment by BryantJames** [comment]
解决了嘛？

**Comment by qq10044375** [comment]
还没解决。目前就是不适用enum，用 tinyint来管理各种状态，没有enum那么方便

**Comment by DennisMao** [comment]
@qq10044375  已修改为proposal
