### ISSUE TITLE
grace panic: sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by zzxap** [astaxie/beego#3248]
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 1 [running]:
sync.(*WaitGroup).Wait(0xc4200b30a8)
	/usr/local/go/src/sync/waitgroup.go:131 +0xbb
GateWay/grace.(*Server).Serve(0xc4200b3080, 0x2, 0x2)
/grace/server.go:41 +0xef
GateWay/grace.(*Server).ListenAndServeTLS(0xc4200b3080, 0x0, 0x0, 0x0, 0x0, 0xc4200b3080, 0xc420216810)
/grace/server.go:133 +0x327
GateWay/grace.ListenAndServeTLSCFG(0x92bb76, 0x5, 0x97ee20, 0xc420148930, 0xc4201bc300, 0x1, 0x1)
/grace/grace.go:169 +0x6e

热更新模块有问题？

**Comment by xujunhai** [comment]
> panic: sync: WaitGroup is reused before previous Wait has returned
> 
> goroutine 1 [running]:
> sync.(*WaitGroup).Wait(0xc4200b30a8)
> /usr/local/go/src/sync/waitgroup.go:131 +0xbb
> GateWay/grace.(*Server).Serve(0xc4200b3080, 0x2, 0x2)
> /grace/server.go:41 +0xef
> GateWay/grace.(*Server).ListenAndServeTLS(0xc4200b3080, 0x0, 0x0, 0x0, 0x0, 0xc4200b3080, 0xc420216810)
> /grace/server.go:133 +0x327
> GateWay/grace.ListenAndServeTLSCFG(0x92bb76, 0x5, 0x97ee20, 0xc420148930, 0xc4201bc300, 0x1, 0x1)
> /grace/grace.go:169 +0x6e
> 
> 热更新模块有问题？

我也是遇到这个问题~ 跟申请的是 每次测试效果都不一样
有的时候父进程能正常退出，大部分情况是子进程又会fork子进程

**Comment by net20121222** [comment]
2020/07/03 11:11:51 server.go:232: 21179 Received SIGHUP. forking.
2020/07/03 11:11:51 server.go:321: [0xc002086018 0xc002086010]
2020/07/03 11:11:51 server.go:335: [-graceful -socketorder=:8100,:8101]
2020/07/03 11:11:51 server.go:232: 21179 Received SIGHUP. forking.
2020/07/03 11:11:51 laddr :8100 ptr offset 0
2020/07/03 11:11:51 29705 :8100
2020/07/03 11:11:51 laddr :8101 ptr offset 1
2020/07/03 11:11:51 29705 :8101
2020/07/03 11:11:51 server.go:241: 21179 Received SIGTERM.
2020/07/03 11:11:51 server.go:39: 21179 Waiting for connections to finish...
2020/07/03 11:11:51 server.go:275: 21179 [::]:8100 Listener closed.
2020/07/03 11:11:51 server.go:241: 21179 Received SIGTERM.
2020/07/03 11:11:51 server.go:39: 21179 Waiting for connections to finish...
2020/07/03 11:11:51 server.go:275: 21179 [::]:8101 Listener closed.
2020/07/03 11:12:51 server.go:292: [STOP - Hammer Time] Forcefully shutting down parent
2020/07/03 11:12:51 server.go:285: WaitGroup at 0 sync: negative WaitGroup counter
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 28 [running]:
sync.(*WaitGroup).Wait(0xc0003abe88)
        /usr/local/Cellar/go/1.13.4/libexec/src/sync/waitgroup.go:132 +0xad
github.com/astaxie/beego/grace.(*Server).Serve(0xc0003abe60, 0x2, 0x2)
        /go/pkg/mod/github.com/astaxie/beego@v1.11.1/grace/server.go:40 +0xf5
github.com/astaxie/beego/grace.(*Server).ListenAndServe(0xc0003abe60, 0x5, 0xfa3120)
        /go/pkg/mod/github.com/astaxie/beego@v1.11.1/grace/server.go:77 +0x254
github.com/astaxie/beego.(*App).Run.func2(0xc0003c2f08, 0x5, 0xc00010a170, 0xc000552000)
       /go/pkg/mod/github.com/astaxie/beego@v1.11.1/app.go:161 +0xca
created by github.com/astaxie/beego.(*App).Run
        /go/pkg/mod/github.com/astaxie/beego@v1.11.1/app.go:154 +0x3cf

对呀  我也遇到这个问题了 beego 1.11.1    不知道解决了没

**Comment by flycash** [comment]
热更新模块到1.12.2的时候，已经修复了比较多的问题，你们可以试试新版本
