### ISSUE TITLE
orm.Update() effected entity count always equal to 0

### ISSUE THREAD

**Issue by chenleji** [astaxie/beego#3257]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.9.1

2. What operating system and processor architecture are you using (`go env`)?
GOOS="darwin"
GOARCH="amd64"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

type Service struct {
	Id           int          `orm:"pk auto"`
	Name         string       `orm:"column(name)"`
	Description  string       `orm:"column(description)"`
}

num, err := orm.NewOrm().Update(service, "name", "description")
	if err != nil {
		logs.Error(err)
		return nil, err
	}

4. What did you expect to see?
err == nil 
the variable "num" == 1

5. What did you see instead?
err == nil, but the variable "num" is always 0.

**Comment by nicholas-eden** [comment]
What database are you using?  I don't see any problems with the MySQL implementation.

**Comment by chenleji** [comment]
@nicholas-eden  I am using mariadb DB,  with orm driver name="mysql". 

const (
	DefaultDB  = "default"
	DriverName = "mysql"
)

func init() {
	orm.Debug = false

	conf := helper.GetConfInst().LoadConf()

	dbURL := conf.DBUrl
	dbPort := conf.DBPort
	dbUser := conf.DBUser
	dbPassword := conf.DBPwd
	dbName := beego.AppConfig.String(helper.AppName)

	dataSource := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8", dbUser, dbPassword, dbURL, dbPort, dbName)
	maxIdle := 30
	maxConn := 50
	logs.Debug("dataSource:", dataSource)

	orm.RegisterDriver(DriverName, orm.DRMySQL)
	err := orm.RegisterDataBase(DefaultDB, DriverName, dataSource, maxIdle, maxConn)
	if err != nil {
		logs.Debug(err)
	}

	orm.RegisterModel(new(Model))
	orm.RunSyncdb(DefaultDB, false, true)
}
