### ISSUE TITLE
返回json时，如何返回空数组

### ISSUE THREAD

**Issue by yimiaodaren** [astaxie/beego#3258]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.10.3 beego1.9.2

2. What operating system and processor architecture are you using (`go env`)?
mac 

3. What did you do?
```
{
    success:true,
    date:[...],
}

myController
	...
        l, err := models.GetAllReserve(query, fields, sortby, order, offset, limit)
	if err != nil {
		c.Data["json"] = err.Error()
	} else {
		c.Data["json"] = models.SuccessJson(l)
	}
	c.ServeJSON()

func SuccessJson(data interface{}) map[string]interface{} {
        xMap := make(map[string]interface{})
	xMap["success"] = true
	xMap["data"] = data
	return xMap
}

when list.length > 0, everything is ok;
when list.length == 0, json is
{
      success:true,
      data:null,
}
```

4. What did you expect to see?

I want return json is 
```
{
      success:true,
      data:[],
}
```
5. What did you see instead?

**Comment by DennisMao** [comment]
type YourData struct{
     Success bool `json:"success"` 
     Data interface{} `json:"data"`
}

ret := YourData{
   Success:true,
   Data:[]string{},  //需要分配内存(定义)，否则为null，'string'可以替换成自定义结构体类型
}

b,_:=json.Marshal(ret)

fmt.Println(string(ret)) 
```

output
```
{
      success:true,
      data:[],
}
```

key 核心点: 需要返回空数组的关键是要定义(分配内存).

**Comment by yimiaodaren** [comment]
@DennisMao 谢谢哈 已经成功了 不过我一直很奇怪，为啥会定义errNoRows这个错误。

orm_queryset.go 200行里的方法
func (o *querySet) All(container interface{}, cols ...string) (int64, error) {
	num, err := o.orm.alias.DbBaser.ReadBatch(o.orm.db, o, o.mi, o.cond, container, o.orm.alias.TZ, cols)
	if num == 0 {
		return 0, ErrNoRows
	}
	return num, err
}

查询出来 num 为 0 err 为nil  但是还是返回ErrNoRows 很神奇。每一个查询借口都要判断err是不是等于ErrNoRows.....
