### ISSUE TITLE
Swagger documentation is not generated

### ISSUE THREAD

**Issue by TemaKozyrev** [astaxie/beego#3285]
1. What version of Go and beego are you using (`bee version`)?
Beego        : 1.10.1
GoVersion : go1.10.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

3. What did you do?
`bee api beeapi`
`bee run -downdoc=true -gendoc=true`

```
2018/08/07 14:31:11 INFO     ▶ 0001 Using 'beeapi' as 'appname'
2018/08/07 14:31:11 INFO     ▶ 0002 Downloading 'https://github.com/beego/swagger/archive/v3.zip' to 'swagger.zip'...
2018/08/07 14:31:41 ERROR    ▶ 0003 Error while downloading 'https://github.com/beego/swagger/archive/v3.zip': Get https://github.com/beego/swagger/archive/v3.zip: dial tcp: i/o timeout
2018/08/07 14:31:41 INFO     ▶ 0004 Unzipping 'swagger.zip'...
2018/08/07 14:31:41 INFO     ▶ 0005 Initializing watcher...
2018/08/07 14:31:42 INFO     ▶ 0006 Generating the docs...
2018/08/07 14:31:42 SUCCESS  ▶ 0007 Docs generated!
2018/08/07 14:31:43 SUCCESS  ▶ 0008 Built Successfully!
2018/08/07 14:31:43 INFO     ▶ 0009 Restarting 'beeapi'...
2018/08/07 14:31:43 SUCCESS  ▶ 0010 './beeapi' is running...
```

4. What did you expect to see?

**Files of the generated documentation. Ability to view documentation via `/ swagger` url**

5. What did you see instead?

**The documentation is not generated and does not open properly.**

![image](https://user-images.githubusercontent.com/26088469/43773531-ae020c98-9a4e-11e8-974b-443268b7cba9.png)

![image](https://user-images.githubusercontent.com/26088469/43773649-152f2ea0-9a4f-11e8-9529-b763299d00b7.png)

**Comment by TemaKozyrev** [comment]
I was able to solve the problem, the mistake was that I did not connect to github.com. But why does the `bee run` command not report this?

**Comment by harshit777** [comment]
Can I generate the swagger without using ```bee api beeapi``` command
