### ISSUE TITLE
beego是否有办法实现即时输出？

### ISSUE THREAD

**Issue by ylqjgm** [astaxie/beego#3286]
比如，我要在页面中实现一到一百万的循环，每次循环输出当前的数字。

如果按照正常的来进行，那么等页面显示的时候已经是循环结束了，所有结果都已经显示到了页面中。

有没有办法能够我打开页面开始执行，然后执行一次就直接在页面中输出一次？

PHP有类似的处理方法，但是Golang不太清除。

**Comment by toadzhou** [comment]
beego不清楚，net/http原生的倒是搞过，不知道是不是你想要的。
func xxxxHandler(w http.ResponseWriter, r *http.Request) {
	conn, ok := w.(http.Flusher)
        for xxx() {
		fmt.Fprintf(w, xxxx)
		conn.Flush()
		time.Sleep(time.Second)
	}
