### ISSUE TITLE
QuerySeter.All() set empty slice if parameter is nil and no data returned

### ISSUE THREAD

**Issue by hurisheng** [astaxie/beego#3287]
When using QuerySeter.All() to retrieve multiple data from database, normally we will do it like this: 
```golang
var users []*User
if _, err := o.QueryTable("user").All(&users); err != nil {
  return err
}
```
If there is no data returned from database, users will be set an empty slice instead of stay as it is, which is nil, before passed into the function call.
https://github.com/astaxie/beego/blob/master/orm/db.go#L1082

Do you think it is better to keep user unchanged if no data is returned from database?

**Comment by Raggaer** [comment]
I think its better to make users an empty slice, this way your code will work when there is no resulsts or theres results without needing to check for `!= nil`

You could always just check `len(users) >= 1` is you want to check if the query returned any data
