### ISSUE TITLE
orm_queryset.go why return ErrNoRows

### ISSUE THREAD

**Issue by yimiaodaren** [astaxie/beego#3288]
orm_queryset.go
line 200
```
func (o *querySet) All(container interface{}, cols ...string) (int64, error) {
	num, err := o.orm.alias.DbBaser.ReadBatch(o.orm.db, o, o.mi, o.cond, container, o.orm.alias.TZ, cols)
	if num == 0 {
		return 0, ErrNoRows
	}
	return num, err
}
```

if num == 0 means error?
ignore err?

**Comment by hurisheng** [comment]
I think this will be reverted soon.
https://github.com/astaxie/beego/issues/3256

**Comment by yimiaodaren** [comment]
@NSObjects  yeah, I see.

But i think this code above is not awesome

when num = 0 And Err is not nil maybe other error
it  still return ErrNoRows
