### ISSUE TITLE
orm 更新问题

### ISSUE THREAD

**Issue by web-like** [astaxie/beego#3293]
在我更新struct的时候 如果我没有制定更新的字段, 怎么将字段值为空的过滤出来, 不进行更新, 谢谢!

**Comment by yimiaodaren** [comment]
你可以看下自带的UpdateById方法的实现，里面有个方法

	// update model to database.
	// cols set the columns those want to update.
	// find model by Id(pk) field and update columns specified by fields, if cols is null then update all columns
	// for example:
	// user := User{Id: 2}
	//	user.Langs = append(user.Langs, "zh-CN", "en-US")
	//	user.Extra.Name = "beego"
	//	user.Extra.Data = "orm"
	//	num, err = Ormer.Update(&user, "Langs", "Extra")
	Update(md interface{}, cols ...string) (int64, error)

o := orm.NewOrm()
...
o.Update(m, ... ) 第二个参数就是你要选择更新的字段，默认不传估计是全选

**Comment by aztack** [comment]
按 @yimiaodaren 说的，可以在UpdateModelById里检查某些字段是否符合要求，如果符合要求就把对应字段加入到可更新的数组中：
```go
func UpdateProjectById(m *Project) (err error) {
	o := orm.NewOrm()
	v := Project{ID: m.ID}
	// ascertain id exists in the database
	if err = o.Read(&v); err == nil {
		var num int64
		columns := []string{}
		if len(m.Name) != 0 {
			columns = append(columns, "Name")
		}
		if len(m.Meta) != 0 {
			columns = append(columns, "Meta")
		}
		if len(m.Data) != 0 {
			columns = append(columns, "Data")
		}
		if num, err = o.Update(m, columns...); err == nil {
			fmt.Println("Number of records updated in database:", num)
		}
	}
	return
}
```
