### ISSUE TITLE
this is an error when deployed beego project on centos7

### ISSUE THREAD

**Issue by leomei91** [astaxie/beego#3294]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

[ORM]2018/08/20 16:44:25 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
must have one register DataBase alias named `default`

**Comment by DennisMao** [comment]
@leomei91   `CGO_ENABLED=1` should be manual set when using the sqlite3 database.For more information,you can see https://github.com/mattn/go-sqlite3#installation
