### ISSUE TITLE
post请求获取不到RequestBody参数

### ISSUE THREAD

**Issue by liu2972505** [astaxie/beego#3305]
controller

type BaseController struct {
	beego.Controller
}

func (this *BaseController) TestPost() {
	result := this.Input()
	fmt.Println("input value is", result)
	this.ServeJSON()
}

router
beego.Router("api/testPost",&controllers.BaseController{},"post:TestPost")

request
curl -X "POST" "http://localhost:9090/api/testPost" \
     -H 'Content-Type: text/plain; charset=utf-8' \
     -d $'{
  "cpu": 2,
  "memory": 1024,
  "resourceId": "i-00BvSWbGWn"
}'

代码和请求如上, 显示结果input value is map[]，是我哪里写的有问题吗？

**Comment by peteguan** [comment]
这个issue有解决么
