### ISSUE TITLE
修改app.conf配置文件以后,不重启beego生效最新配置

### ISSUE THREAD

**Issue by shuiche-it** [astaxie/beego#3307]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego: 1.8.0
go: 1.10.2

2. What operating system and processor architecture are you using (`go env`)?
amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by xuange306** [comment]
这个如何操作?

**Comment by l2dy** [comment]
使用 `kill -HUP` 发送 HUP 信号给你的程序。参考 https://github.com/beego/beedoc/blob/87689ae65dc91dc6bb1365a819eabd02358ec5d1/en-US/deploy/supervisor.md#install-beego-application-as-a-service.

**Comment by DennisMao** [comment]
思路:
1.配置结构体需要支持线程安全(读写锁)
配置生效触发
1.动态检查文件的修改时间
2.监听信号量或者api
