### ISSUE TITLE
不能找到can't find templatefile in the path 

### ISSUE THREAD

**Issue by levin9** [astaxie/beego#3309]
beego 1.10.1 ，通过admin后台监控，已添加路由
/member/index  map[*:Index]  controllers.MemberController 
通过liteide，BuildAndRun，报错，提示
block:can't find templatefile in the path:views/member/index.html
在view对应目录有此文件，对应的MemberController 有Index方法。

**Comment by levin9** [comment]
gopath已设置，其他项目能build和run。

**Comment by DennisMao** [comment]
@levin9   考虑是运行路径问题,可以尝试用命令行执行go run或者直接编译执行
