### ISSUE TITLE
beego下载问题

### ISSUE THREAD

**Issue by lazytooo** [astaxie/beego#3312]
beego中的c.Ctx.Output.Download(fileUrl),能否使用循环实现多个文件下载?我使用了for循环进行三个文件的下载,实际只下载了第一个文件

**Comment by Crazy-Geng** [comment]
你这个前端是怎么写的？为什么我post请求之后，他直接response回复文件内容呢？？？

**Comment by CuteLilTwo** [comment]
> 你这个前端是怎么写的？为什么我post请求之后，他直接response回复文件内容呢？？？

我们前后端分离，并且后端直接get请求，能下载的，应该和前端那边没啥关系

**Comment by JessonChan** [comment]
不能实现，需要三次请求。
