### ISSUE TITLE
Can't use https

### ISSUE THREAD

**Issue by xunxinyuan** [astaxie/beego#3321]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
    go version go1.10.4 windows/386
    beego 1.10.1

2. What operating system and processor architecture are you using (`go env`)?
     Windows7 i386

3. What did you do?
Add this statements in app.conf
```
    EnableHTTPS = true
    HTTPSAddr = "127.0.0.1"
    HttpsPort = 10258
    HTTPSCertFile = "tls/server.crt"
    HTTPSKeyFile = "tls/server.key"
```
4. What did you expect to see?
```
    https server Running on https://127.0.0.1:10258
```

5. What did you see instead?
```
https server Running on https://127.0.0.1:10258
ListenAndServeTLS:  listen tcp 127.0.0.1:10258: bind: Only one usage of each socket address 
(protocol/network address/port) is normally permitted.
```

   **I changed the port many times and still can't use https.**

But when I use code like this,it is right.

```go
func Https(ctx *context.Context) {
	//if isProd {
		if ctx.Request.TLS == nil {
			ctx.Redirect(http.StatusTemporaryRedirect, https_baseUrl+ctx.Request.URL.String())
		}
	//}
}

beego.NSBefore(Https)
```

So I think it maybe a bug. 
Do you guys have this problem?

**Comment by cappuccino5** [comment]
I have this kind of problem, how to solve it

**Comment by mrshengzyzy** [comment]
I have this kind of problem too

**Comment by mrshengzyzy** [comment]
@cappuccino5 use code-config instead of config file, it is works for me
```
beego.BConfig.Listen.EnableHTTPS = true
beego.BConfig.Listen.Graceful = true
beego.BConfig.Listen.HTTPSPort = 8228
beego.BConfig.Listen.HTTPSCertFile = "conf/beego.crt"
beego.BConfig.Listen.HTTPSKeyFile = "conf/beego.key"
```
