### ISSUE TITLE
Context 支持 Set 自定义键吗

### ISSUE THREAD

**Issue by zjxpcyc** [astaxie/beego#3324]
不知道是不是 issues 只能提 bug 。如果是，请关闭这个 issue 。

我这边有个场景， 在路由 Filter 的时候 需要将部分内容带入 到  controller 里面，打算使用 context 。但是没有找到带入的方法，不知道是否我没找到的原因。

如果有，请问怎么使用？

**Comment by axetroy** [comment]
duplicate #316

**Comment by zjxpcyc** [comment]
thx
