### ISSUE TITLE
关于beego的配置问题，想请教下。

### ISSUE THREAD

**Issue by xdeng** [astaxie/beego#3327]
1、beego搭建的网站，怎样禁止直接用ip访问啊？
2、beego启用了https，怎样把http的访问重定向到https，不想禁用http。
没看到配置里有这几个选项。。。
不想用nginx。

**Comment by DennisMao** [comment]
1.需要增加Filter中间件过滤Host
2.Nginx代理或者业务中实现重定向的代码
