### ISSUE TITLE
过滤器如何传递新参数到控制器?

### ISSUE THREAD

**Issue by woann** [astaxie/beego#3328]
beego的过滤器如何往目标控制器添加参数或者传递数据?
比如我在过滤器通过解析header获取到用户信息
如何传递下去?

**Comment by xvjialing** [comment]
我也有相同需求，请问有找到处理方法吗

**Comment by flycash** [comment]
Filter里面有一个参数，是Context。可以往这里面塞，而后从别的地方拿出来。Controller里面能够拿到这个Context。你可以参考`route.go`里面的`ServeHTTP`方法
