### ISSUE TITLE
controllers.ServeJSON数据量超过2850出现内存溢出

### ISSUE THREAD

**Issue by hwfy** [astaxie/beego#3336]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
  beego: 1.7.1
  go :      1.9
2. What operating system and processor architecture are you using (`go env`)?
 arch:  amd64
 os  :   linux 
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9baeba, 0x16)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc43e470000, 0x92a0000, 0x411e00, 0xd6f2d8)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0xd55e40, 0x92a0000, 0x7efc877ee0c8)
	/usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0xd55e40, 0x4950, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xd55e40, 0x4950, 0xd6f2e8, 0x7efc84f8fde8)
	/usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xd55e40, 0x4950, 0x410101, 0xc41fbfc6ff)
	/usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xd55e40, 0x4950, 0x7efc84010101, 0x415c7c)
	/usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x929fc00, 0x450101, 0x7efc878a56c8)
	/usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x7efc00000000)
	/usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1175

goroutine 23 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc42046a930 sp=0xc42046a928 pc=0x457440
runtime.mallocgc(0x929fc00, 0x8e5460, 0x1, 0xc42046aa08)
	/usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc42046a9d0 sp=0xc42046a930 pc=0x412252
runtime.makeslice(0x8e5460, 0x929fc00, 0x929fc00, 0xc4200de3d8, 0xc42046aab5, 0x3)
	/usr/local/go/src/runtime/slice.go:61 +0x77 fp=0xc42046aa00 sp=0xc42046a9d0 pc=0x443227
bytes.makeSlice(0x929fc00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:230 +0x6d fp=0xc42046aa40 sp=0xc42046aa00 pc=0x46e0ed
bytes.(*Buffer).grow(0xc4200de370, 0x400, 0x400)
	/usr/local/go/src/bytes/buffer.go:144 +0x151 fp=0xc42046aa90 sp=0xc42046aa40 pc=0x46daa1
bytes.(*Buffer).Write(0xc4200de370, 0xc428072db8, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:174 +0xd9 fp=0xc42046aac0 sp=0xc42046aa90 pc=0x46dd79
encoding/base64.(*encoder).Write(0xc428072d80, 0xc430f3af00, 0x550d, 0x6000, 0x550d, 0x6000, 0x8c1022)
	/usr/local/go/src/encoding/base64/base64.go:217 +0x2f9 fp=0xc42046ab40 sp=0xc42046aac0 pc=0x49f8e9
encoding/json.encodeByteSlice(0xc4200de370, 0x8de480, 0xc4242bf348, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:719 +0x29b fp=0xc42046abc8 sp=0xc42046ab40 pc=0x4f578b
encoding/json.(*structEncoder).encode(0xc42e8ebda0, 0xc4200de370, 0x96be80, 0xc4242bf310, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:639 +0x255 fp=0xc42046ad28 sp=0xc42046abc8 pc=0x4f4a35
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200de370, 0x96be80, 0xc4242bf310, 0x199, 0xc4242b0100)
	/usr/local/go/src/encoding/json/encode.go:653 +0x64 fp=0xc42046ad68 sp=0xc42046ad28 pc=0x4fd4a4
encoding/json.(*ptrEncoder).encode(0xc42216efb8, 0xc4200de370, 0x92f560, 0xc42b15fea8, 0x196, 0x100)
	/usr/local/go/src/encoding/json/encode.go:780 +0xe3 fp=0xc42046ada8 sp=0xc42046ad68 pc=0x4f5df3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200de370, 0x92f560, 0xc42b15fea8, 0x196, 0x920100)
	/usr/local/go/src/encoding/json/encode.go:785 +0x64 fp=0xc42046ade8 sp=0xc42046ada8 pc=0x4fd6a4
encoding/json.(*arrayEncoder).encode(0xc42216efc0, 0xc4200de370, 0x8d83c0, 0xc43162f040, 0x97, 0x100)
	/usr/local/go/src/encoding/json/encode.go:761 +0xdc fp=0xc42046ae40 sp=0xc42046ade8 pc=0x4f5bac
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc4200de370, 0x8d83c0, 0xc43162f040, 0x97, 0xc4200d0100)
	/usr/local/go/src/encoding/json/encode.go:768 +0x64 fp=0xc42046ae80 sp=0xc42046ae40 pc=0x4fd624
encoding/json.(*sliceEncoder).encode(0xc42216efc8, 0xc4200de370, 0x8d83c0, 0xc43162f040, 0x97, 0x8d0100)
	/usr/local/go/src/encoding/json/encode.go:735 +0xc1 fp=0xc42046aec0 sp=0xc42046ae80 pc=0x4f58d1
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc4200de370, 0x8d83c0, 0xc43162f040, 0x97, 0xc431620100)
	/usr/local/go/src/encoding/json/encode.go:747 +0x64 fp=0xc42046af00 sp=0xc42046aec0 pc=0x4fd5a4
encoding/json.(*encodeState).reflectValue(0xc4200de370, 0x8d83c0, 0xc43162f040, 0x97, 0x100)
	/usr/local/go/src/encoding/json/encode.go:325 +0x82 fp=0xc42046af38 sp=0xc42046af00 pc=0x4f2892
encoding/json.(*encodeState).marshal(0xc4200de370, 0x8d83c0, 0xc43162f040, 0x9b0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:298 +0xa5 fp=0xc42046af70 sp=0xc42046af38 pc=0x4f2585
encoding/json.Marshal(0x8d83c0, 0xc43162f040, 0xc420421b00, 0x9b39ca, 0xc, 0x9c07cf, 0x1f)
	/usr/local/go/src/encoding/json/encode.go:161 +0x5f fp=0xc42046afb8 sp=0xc42046af70 pc=0x4f204f
encoding/json.MarshalIndent(0x8d83c0, 0xc43162f040, 0x0, 0x0, 0x9abf78, 0x2, 0xa18850, 0xc42046b101, 0xc42046b0c0, 0x4090f2, ...)
	/usr/local/go/src/encoding/json/encode.go:172 +0x3f fp=0xc42046b038 sp=0xc42046afb8 pc=0x4f212f
github.com/astaxie/beego/context.(*BeegoOutput).JSON(0xc4203a3ca0, 0x8d83c0, 0xc43162f040, 0xc420180001, 0xc42046b120, 0xc42018c361)
	/home/administrator/gocode/src/github.com/astaxie/beego/context/output.go:177 +0xb5 fp=0xc42046b0d0 sp=0xc42046b038 pc=0x79a205
github.com/astaxie/beego.(*Controller).ServeJSON(0xc4203580e0, 0x0, 0x0, 0x0)
	/home/administrator/gocode/src/github.com/astaxie/beego/controller.go:308 +0xf6 fp=0xc42046b130 sp=0xc42046b0d0 pc=0x7c4416
cy/CloudERP/form/controllers.(*FormController).GetAll(0xc4203580e0)
	/home/administrator/gocode/src/cy/CloudERP/form/controllers/form.go:37 +0x1e8 fp=0xc42046b1f0 sp=0xc42046b130 pc=0x88d098
runtime.call32(0xc420421bf0, 0xc42047eec8, 0xc42047eed8, 0x800000008)
	/usr/local/go/src/runtime/asm_amd64.s:573 +0x3b fp=0xc42046b220 sp=0xc42046b1f0 pc=0x45780b
reflect.Value.call(0x9a4ac0, 0xc4203580e0, 0x2213, 0x9acf36, 0x4, 0x0, 0x0, 0x0, 0xc42047eec0, 0x13, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969 fp=0xc42046b4e0 sp=0xc42046b220 pc=0x48a189
reflect.Value.Call(0x9a4ac0, 0xc4203580e0, 0x2213, 0x0, 0x0, 0x0, 0xc4203580e0, 0x2213, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4 fp=0xc42046b548 sp=0xc42046b4e0 pc=0x489704
github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc4200b3220, 0xa208c0, 0xc420358000, 0xc420138700)
	/home/administrator/gocode/src/github.com/astaxie/beego/router.go:796 +0x1efc fp=0xc42046bd58 sp=0xc42046b548 pc=0x7d217c
net/http.serverHandler.ServeHTTP(0xc42014cea0, 0xa208c0, 0xc420358000, 0xc420138700)
	/usr/local/go/src/net/http/server.go:2694 +0xbc fp=0xc42046bd88 sp=0xc42046bd58 pc=0x69469c
net/http.(*conn).serve(0xc4200b2140, 0xa20d40, 0xc4200b1dc0)
	/usr/local/go/src/net/http/server.go:1830 +0x651 fp=0xc42046bfc8 sp=0xc42046bd88 pc=0x690a01
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42046bfd0 sp=0xc42046bfc8 pc=0x459fb1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

goroutine 1 [chan receive, 9 minutes]:
github.com/astaxie/beego.(*App).Run(0xc420093f20)
	/home/administrator/gocode/src/github.com/astaxie/beego/app.go:186 +0x468
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/home/administrator/gocode/src/github.com/astaxie/beego/beego.go:67 +0x51
main.main()
	/home/administrator/gocode/src/cy/CloudERP/form/main.go:14 +0x5e

goroutine 19 [syscall, 9 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 22 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7efc87859f00, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4203de498, 0x72, 0xc4200b0000, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4203de498, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4203de480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4203de480, 0xc4200b21c0, 0xc420057db8, 0x402a68)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42047eea8, 0xc420057de8, 0x4019c7, 0xc4200b21c0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42047eea8, 0xc420057e30, 0xc420057e38, 0x18)
	/usr/local/go/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42047eea8, 0x9d8a30, 0xc4200b2140, 0xa20e00, 0xc420421950)
	/usr/local/go/src/net/http/server.go:3216 +0x2f
net/http.(*Server).Serve(0xc42014cea0, 0xa20b80, 0xc42047eea8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ListenAndServe(0xc42014cea0, 0xa18bb0, 0xc420048780)
	/usr/local/go/src/net/http/server.go:2711 +0xa9
github.com/astaxie/beego.(*App).Run.func4(0xc4200a8068, 0x5, 0xc420093f20, 0xc4202484d0)
	/home/administrator/gocode/src/github.com/astaxie/beego/app.go:178 +0x2a0
created by github.com/astaxie/beego.(*App).Run
	/home/administrator/gocode/src/github.com/astaxie/beego/app.go:160 +0x4b3

goroutine 24 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7efc87859e30, 0x72, 0xc420048658)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4203de518, 0x72, 0xffffffffffffff00, 0xa1c8a0, 0xd0a6a8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4203de518, 0xc420421a00, 0x1, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4203de500, 0xc420421a51, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4203de500, 0xc420421a51, 0x1, 0x1, 0xa18bb0, 0xc420048780, 0x1)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42047eeb8, 0xc420421a51, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc420421a40)
	/usr/local/go/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:664 +0xce

goroutine 2064 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7efc87859af0, 0x72, 0xc42706f9a8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42a602318, 0x72, 0xffffffffffffff00, 0xa1c8a0, 0xd0a6a8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42a602318, 0xc42a608000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42a602300, 0xc42a608000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42a602300, 0xc42a608000, 0x1000, 0x1000, 0x455ec0, 0xc420086900, 0x4)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4287e78a0, 0xc42a608000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*persistConn).Read(0xc42b63c240, 0xc42a608000, 0x1000, 0x1000, 0xc42706fb98, 0x404fa5, 0xc42b3e2480)
	/usr/local/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42a34ac00)
	/usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42a34ac00, 0x1, 0x0, 0x0, 0x0, 0xc4285588a0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc42b63c240)
	/usr/local/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1237 +0x95a

goroutine 2065 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc42b63c240)
	/usr/local/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1238 +0x97f

goroutine 386 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc420360000)
	/usr/local/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1238 +0x97f

goroutine 369 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7efc8777f370, 0x72, 0xc42d9f2760)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4203f4318, 0x72, 0xffffffffffffff00, 0xa1c8a0, 0xd0a6a8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4203f4318, 0xc42bbb5000, 0x800, 0x800)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4203f4300, 0xc42bbb5000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4203f4300, 0xc42bbb5000, 0x800, 0x800, 0xd1, 0xc424848e96, 0x3)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e018, 0xc42bbb5000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42046eb10, 0x7efc8777cca0, 0xc42000e018, 0x5, 0xc42000e018, 0xc)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4200f7880, 0x9d9117, 0xc4200f79a0, 0x455ec0)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4200f7880, 0xc42adf3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
net/http.(*persistConn).Read(0xc420360000, 0xc42adf3000, 0x1000, 0x1000, 0xc42d9f2b98, 0x404fa5, 0xc429386720)
	/usr/local/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc420078660)
	/usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc420078660, 0x1, 0x0, 0x0, 0x0, 0xc428558960, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc420360000)
	/usr/local/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1237 +0x95a

goroutine 2299 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7efc87859540, 0x72, 0xc42706c9a8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4338be098, 0x72, 0xffffffffffffff00, 0xa1c8a0, 0xd0a6a8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4338be098, 0xc42591d000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4338be080, 0xc42591d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4338be080, 0xc42591d000, 0x1000, 0x1000, 0x455ec0, 0xc420086900, 0x4)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4289f46b8, 0xc42591d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*persistConn).Read(0xc428d65320, 0xc42591d000, 0x1000, 0x1000, 0xc42706cb98, 0x404fa5, 0xc428558840)
	/usr/local/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc431299c20)
	/usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc431299c20, 0x1, 0x0, 0x0, 0x0, 0xc425920300, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc428d65320)
	/usr/local/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1237 +0x95a

goroutine 2300 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc428d65320)
	/usr/local/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1238 +0x97f

**Comment by DennisMao** [comment]
@hwfy  方便贴上使用时候的代码？
