### ISSUE TITLE
model中 字段的description 和 auto_now_add, auto_now 不生效

### ISSUE THREAD

**Issue by LiJoah** [astaxie/beego#3337]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by LiJoah** [comment]
然后我看到 description 是使用tag 的方式来声明的，所以我才成了 这样：
   type User struct {
	Id       int32     `orm: "auto;pk;column(id)" json:"id" description:"用户id"`
	Token    string    `orm: "size(64);index;column(token);" json:"token" description:"用户token"`
	Username string    `orm: "size(128);column(user_name);" json:"username" description: "用户昵称"` // default 255 字节
	Password string    `orm: "size(256);column(password);" json:"password" description:"用户密码"`
	Created  time.Time `orm: "column(created);type(datetime);auto_now_add" json:"created"`
	Updated  time.Time `orm: "column(updated);type(datetime);auto_now" json:"updated"`
}

然后重新生成了表，comment 字段还是空的，不知道到为什么

**Comment by kougazhang** [comment]
我也遇到了字段为 `auto_now` 不生效的问题。

结构体：
```
type Category struct {
	Id           int       `orm:"auto"`
	CreatedTime  time.Time `orm:"auto_now_add;type(datetime)"`
	ModifiedTime time.Time `orm:"auto_now;type(datetime)"`
	Name  string `orm:"size(100)"`
	Order int
	// status: 0,删除; 1，使用;
	Status int8
	// 此字段不映射到数据库中
}
```
执行的 orm 代码：
```
o.QueryTable(&Category{}).Filter("id", c.Id).Update(orm.Params{"name": c.Name, "order": c.Order, "status": c.Status})
```
运行的 sql：
```
[UPDATE `blog_category` T0 SET T0.`name` = ?, T0.`order` = ?, T0.`status` = ? WHERE T0.`id` = ? ] - `test_insert`, `0`, `0`, `5`
```
从这个 sql 可见，auto_now 完全不起作用啊 。

**Comment by DennisMao** [comment]
@LiJoah  @kougazhang  是什么数据库？

**Comment by kougazhang** [comment]
mysql 数据库

**Comment by LiJoah** [comment]
> @LiJoah @kougazhang 是什么数据库？
我的也是mysql

**Comment by DennisMao** [comment]
@kougazhang @LiJoah  了解,tks，正在处理
