### ISSUE TITLE
复制文档代码报错

### ISSUE THREAD

**Issue by lightbrotherV** [astaxie/beego#3342]
代码：
beego.Get("/", func(ctx *context.Context) {
})

报错：
cannot use func literal (type func(*"context".Context)) as type beego.FilterFunc in argument to beego.Get
import (context "context")

**Comment by DennisMao** [comment]
@lightbrotherV   
the context package is not `"context"`, instead `"github.com/astaxie/beego/context"`.

```
import (
"github.com/astaxie/beego/context"
)

beego.Get("/", func(ctx *context.Context) { 
 ... your code
})
```
