### ISSUE TITLE
Beego orm not create foreign key.

### ISSUE THREAD

**Issue by frangte** [astaxie/beego#3343]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
- go1.11
- beego 1.10

2. What operating system and processor architecture are you using (`go env`)?
- ubuntu 18 (amd64)

3. What did you do?
- I'm trying to create two table (user, user_type). Table `user` have field `user_type_id` is relate with field `id` of table `user_type`.

- Here is my simple code:
```
type User struct {
	Id        uint `orm:"pk"`
	FullName  string
	UserName  string `orm:"unique"`
	Phone     string `orm:"unique"`
	Email     string `orm:"unique"`
	Password  string
	UserType  *UserType `orm:"rel(fk)"`
	CreatedAt time.Time `orm:"auto_now_add;type(datetime)"`
	UpdatedAt time.Time `orm:"auto_now;type(datetime)"`
}

type UserType struct {
	Id        uint `orm:"pk"`
	TypeName  string
	CountUser uint  `orm:"default(0)"`
	Users     []*User `orm:"reverse(many);on_delete(set_null)"`
}
``` 
- And here is `mysql` code of `orm`:
```
drop table `user_type`
    DROP TABLE IF EXISTS `user_type`

drop table `user`
    DROP TABLE IF EXISTS `user`

create table `user_type` 
    -- --------------------------------------------------
    --  Table Structure for `models.UserType`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `user_type` (
        `id` integer unsigned NOT NULL PRIMARY KEY,
        `type_name` varchar(255) NOT NULL DEFAULT '' ,
        `count_user` integer unsigned NOT NULL DEFAULT 0 
    ) ENGINE=INNODB;

create table `user` 
    -- --------------------------------------------------
    --  Table Structure for `models.User`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `user` (
        `id` integer unsigned NOT NULL PRIMARY KEY,
        `full_name` varchar(255) NOT NULL DEFAULT '' ,
        `user_name` varchar(255) NOT NULL DEFAULT ''  UNIQUE,
        `phone` varchar(255) NOT NULL DEFAULT ''  UNIQUE,
        `email` varchar(255) NOT NULL DEFAULT ''  UNIQUE,
        `password` varchar(255) NOT NULL DEFAULT '' ,
        `user_type_id` integer unsigned NOT NULL,
        `created_at` datetime NOT NULL,
        `updated_at` datetime NOT NULL
    ) ENGINE=INNODB;
    CREATE INDEX `user_user_name_email` ON `user` (`user_name`, `email`);
```

4. What did you expect to see?
- Foreign key of two table.

5. What did you see instead?
- No foreign key.

**Comment by davleb** [comment]
The same with Beego 1.7.1, Go 1.11.2 and Postgresql. No FK at all.
Whatever FK kind is in the orm tag : rel(one), rel(fk) ...

**Comment by frangte** [comment]
Thanks @davleb =)))
In my repo i use orm.Raw

**Comment by davleb** [comment]
Sorry @frangte but your model definition is right.
This issue is open since 2014 ...
#3205 #768
Beego orm seems to be broken. 
I know that some developers replace beego orm by jinzhu/gorm. Gorm has also auto migration features.

**Comment by frangte** [comment]
haha. thanks so much i will give a try with jinzhu/gorm =))).

**Comment by zjsxwc** [comment]
i find that beego orm not create real foreign key in the Database(Mysql, sqlite), 

but when we do delete the Model in beego orm golang code, it will do delete the other related Model(s).

so there is the soft foreign key constraints in its golang code.

see the references of method `deleteRels()` https://github.com/astaxie/beego/blob/v1.12.0/orm/db.go#L805

**Comment by davleb** [comment]
zjsxwc:
I still believe beego orm should implement it in the hard way, because a foreign key is something very standardized in the db world and there is no real reason to avoid it.
But your comment is explaining how the "beego orm thing" works and that is very interesting, thanks a lot!

**Comment by saadfarhan124** [comment]
Hi guys 
Any update on this?
