### ISSUE TITLE
ORM supports MSSQL in future..?

### ISSUE THREAD

**Issue by EOM** [astaxie/beego#3347]
Hi,
ORM Beego, supports MSSQL in future..?
Example ORMs http://gorm.io or http://xorm.io yes support MSSQL.

**Comment by ilovejs** [comment]
> Hi,
> ORM Beego, supports MSSQL in future..?
> Example ORMs http://gorm.io or http://xorm.io yes support MSSQL.

I can do a pull request. It's better to leave a dialect template for better experience.
I use github search to get 'mysql' replace once, but how sure how much involve elsewhere ?
e.g. except string and qb_mysql, session, db_mysql. Is there any other places ?
