### ISSUE TITLE
how to recover in a method when there is panic in go routine 

### ISSUE THREAD

**Issue by kingcr7** [astaxie/beego#3348]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.8.3, beego1.8.0

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
func get(){
  ...
  go handleSomethig()
  ...
}
when handleSomethig() panic, how can i recover it in get method???
4. What did you expect to see?

5. What did you see instead?

**Comment by kingcr7** [comment]
@astaxie ,please help,thank you much

**Comment by mapreal19** [comment]
this answer can give you some help: https://stackoverflow.com/a/50409138/2273578

> You would have to have a deferred recover within the goroutine.

That's what I ended up doing
