### ISSUE TITLE
sqlite3中default日期问题

### ISSUE THREAD

**Issue by freboat** [astaxie/beego#3350]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

lastest code from github

2. What operating system and processor architecture are you using (`go env`)?

win8.1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
---------------------------------------code begin----------------------------------------

package main

import (
    "fmt"
	"time"
    "github.com/astaxie/beego/orm"
    //_ "github.com/go-sql-driver/mysql" // import your required driver
	_ "github.com/mattn/go-sqlite3"
)
/*
//run it with sqlite3.exe cmd
create table user(
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	name text,
	create_time datetime  default (datetime('now', 'localtime'))
);
insert into user(name) value('jim');
*/

// Model Struct
type User struct {
    Id   int
    Name string `orm:"size(100)"`
	CreateTime time.Time `orm:"auto_now_add;type(datetime)"`
}

func init() {
    // register model
    orm.RegisterModel(new(User))

    // set default database
    //orm.RegisterDataBase("default", "mysql", "root:root@/my_db?charset=utf8", 30)
	orm.RegisterDataBase("default", "sqlite3", "test.db")
}

func main() {
    o := orm.NewOrm()

    user := User{Name: "slene"}

    // insert
    id, err := o.Insert(&user)
    fmt.Printf("ID: %d, ERR: %v\n", id, err)
}
-----------------------------------code end-----------------------------------------------------------------------
4. What did you expect to see?
在数据库有default (datetime('now', 'localtime'))情况下（见上面代码注释中的sql）
1. orm可以什么也不做（跳过此字段）， 数据库可以自己生成默认值
2. orm如果auto_now_add， 需要分析分析支持时区问题

5. What did you see instead?

1. 不加auto_now_add，  orm强插入了一个null
2. 加了auto_now_add，  时区落后了8个小时

**Comment by freboat** [comment]
i debug the orm's src code, found that:
comment the db.go 's  line 243, like that:
//d.ins.TimeToDB(&tnow, tz)

auto_now_add works with sqlite3 well,  but maybe failed with other database

**Comment by DennisMao** [comment]
@freboat  how about mysql and postgresql?
