### ISSUE TITLE
import wrong: cannot find package

### ISSUE THREAD

**Issue by lifxue** [astaxie/beego#3351]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
  go : 1.11
  beego: 1.10.1
 bee : 1.10

2. What operating system and processor architecture are you using (`go env`)?
 win 10 home

![importwrong](https://user-images.githubusercontent.com/790790/46709414-360f9c00-cc76-11e8-8328-f2b5b36d7dfc.png)

**These are a part of  the missing address:**
 1. github.com/bradfitz/gomemcache/memcache
 2. github.com/gomodule/redigo/redis
 3. github.com/ssdb/gossdb/ssdb
4. github.com/gogo/protobuf/proto
5. github.com/siddontang/ledisdb/config
6.github.com/siddontang/ledisdb/ledis

**These address is right ,but "cannot find package":**
github.com/beego/x2j
github.com/beego/goyaml2
github.com/cloudflare/golz4
github.com/belogik/goes
github.com/casbin/casbin
github.com/couchbase/go-couchbase
github.com/lib/pq
github.com/go-redis/redis

**Comment by DennisMao** [comment]
@lifxue  Please check GOPATH if it's set correctly
