### ISSUE TITLE
Can't  send response except after controller return.

### ISSUE THREAD

**Issue by ffcactus** [astaxie/beego#3357]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10.1

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/baibin/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/baibin/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build341013083=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
I'm working on an asynchronous API, and I would like to return the response to the client somewhere not in the controller. My solution is to pass the beego.Context down and use it to return the response.
However, this solution seems not work. I'm not sure what's wrong. It looks like the client can get the response only after the controller's method return. My client is Postman. Here is my code:
```
// Get is the default GET method handler.

type IDController struct {
	beego.Controller
}

func (c *IDController) Get() {

        // Generate the response.

	c.Data["json"] = response
	c.Ctx.Output.SetStatus(http.StatusOK)
	c.ServeJSON()

	// Can client get the response at this point?

	time.Sleep(time.Duration(5000) * time.Millisecond)

	c.Data["json"] = response
	c.Ctx.Output.SetStatus(http.StatusOK)
	c.ServeJSON()
}
```

4. What did you expect to see?
In the example above, I would like to see the client got the response before the time.Sleep()

5. What did you see instead?
The client got the response after 5 seconds.

**Comment by lxShaDoWxl** [comment]
you want send 2 response in one requests?
this not work in HTTP protocol
1 request = 1 response
the response  go to the client if you call function ServeJSON()
example send in external function

```
func (c *MainController) Get() {
	test(c)
}
func test(c *MainController){
	var responseToken = &ResponseToken{
		Value: "test",
	}
	c.EnableRender=false
	c.Data["json"] = responseToken
	c.ServeJSON()
}
```
