### ISSUE TITLE
beego orm  ,请求完成后,需要关闭数据库链接吗?

### ISSUE THREAD

**Issue by yangqinjiang** [astaxie/beego#3360]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego orm  ,请求完成后,需要关闭数据库链接吗?

2. What operating system and processor architecture are you using (`go env`)?
beego orm  ,请求完成后,需要关闭数据库链接吗?

3. What did you do?
beego orm  ,请求完成后,需要关闭数据库链接吗?

4. What did you expect to see?
beego orm  ,请求完成后,需要关闭数据库链接吗?

5. What did you see instead?

**Comment by DennisMao** [comment]
无需
