### ISSUE TITLE
Invalid Routing

### ISSUE THREAD

**Issue by dominhtri1995** [astaxie/beego#3361]
Beego doc says it adheres to Sinatra guidelines. However this example on Sinatra website doesn't work in beego.

get '/posts/:format?' do
  # matches "GET /posts/" and any extension "GET /posts/json", "GET /posts/xml" etc
end

Source: http://sinatrarb.com/intro.html
You can't GET /posts/ in beego

**Comment by lxShaDoWxl** [comment]
> Route patterns may have optional parameters
doesn't mean it has to be an analogue Accept, does it ?
and optional parameters in beego this "/posts/?:format"
