### ISSUE TITLE
Problem with `auto_now_add` tag

### ISSUE THREAD

**Issue by ducnt114** [astaxie/beego#3368]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.10.1
├── GoVersion : go1.11.1
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/ducnt114/golang
├── GOROOT    : /usr/local/opt/go/libexec
├── Compiler  : gc
└── Date      : Saturday, 27 Oct 2018

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ducnt114/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ducnt114/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qm/3rnnszkn65v45k36d24791f00000gn/T/go-build098111801=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
I think there was a problem with beego orm tag `auto_now_add`

Model file: models/voucher.go:

```
package models

import "time"

type Voucher struct {
	Id                  int64
	CreatedAt           time.Time `orm:"auto_now_add;type(datetime)"`
	UpdatedAt           time.Time `orm:"auto_now;type(datetime)"`
	Name                string
}
```

Test file:

```
package test

import (
	"testing"
	"github.com/astaxie/beego/orm"
	"fmt"
	"cms-service/models"
	_ "github.com/go-sql-driver/mysql"
	"time"
)

func TestBeegoCreatedAtField(t *testing.T) {
	// Init db
	orm.RegisterDriver("mysql", orm.DRMySQL)
	dataSource := fmt.Sprintf("user:pass@tcp(127.0.0.1:3306)/db?charset=utf8")
	orm.RegisterDataBase("default", "mysql", dataSource)
	orm.RegisterModel(new(models.Voucher))

	var ormHandler = orm.NewOrm()
	ormHandler.Using("default")

	voucher := &models.Voucher{Id: 1}
	err := ormHandler.Read(voucher)
	if err != nil {
		t.Fatal(err)
	}

	fmt.Println("Read CreatedAt: ", voucher.CreatedAt)
	fmt.Println("Read UpdatedAt:", voucher.UpdatedAt)

	voucher.Name = fmt.Sprintf("%v", time.Now().Unix())
	ormHandler.Update(voucher)

	updatedVoucher := &models.Voucher{Id: 1}
	err = ormHandler.Read(updatedVoucher)
	if err != nil {
		t.Fatal(err)
	}

	fmt.Println("*****")
	fmt.Println("Updated CreatedAt: ", updatedVoucher.CreatedAt)
	fmt.Println("Updated UpdatedAt:", updatedVoucher.UpdatedAt)

}
```

4. What did you expect to see?

I expected to see `updatedVoucher.CreatedAt` == `voucher.CreatedAt`

5. What did you see instead?

The test output:

```
Read CreatedAt:  2018-10-18 22:05:49 +0700 +07
Read UpdatedAt: 2018-10-27 05:09:10 +0700 +07
*****
Updated CreatedAt:  2018-10-18 15:05:49 +0700 +07
Updated UpdatedAt: 2018-10-27 05:10:13 +0700 +07
```

I saw CreatedAt field was reduced by 7 hours after update.

I run this test on my laptop at timezone GMT+7, and MySQL server run on timezone GMT+0

**Comment by maya2250** [comment]
I also have the same symptoms.

but setting system timezone to UTC and MySQL system timezone to UTC, I got better.
