### ISSUE TITLE
配置的静态文件路由不支持cors访问的问题

### ISSUE THREAD

**Issue by shuiche-it** [astaxie/beego#3372]
_Originally posted by @astaxie in https://github.com/astaxie/beego/issues/2087#issuecomment-240423121_

**Comment by xuange306** [comment]
`beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers", "Content-Type"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers", "Content-Type"},
		AllowCredentials: true,
	}))`

这是我的配置文件

`//设置静态文件映射
	beego.SetStaticPath("/recordData", "/data/MediaServer")
	beego.SetStaticPath("/hls", "html")
	beego.SetStaticPath("/staticUagin", "staticUagin")
	beego.SetStaticPath("/opt/dvr_rdk/bg_image/", "tmp")
	beego.SetStaticPath("/log/download/", "logDownload")`

我想跨域访问  /data/MediaServer 这个目录下的视频文件,  浏览器里一直提示有跨域问题


`Access to fetch at 'http://192.168.2.195:8080/recordData/123.flv' from origin 'http://192.168.2.188:9001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
这是浏览器里面提示的

**Comment by DennisMao** [comment]
@astaxie
