### ISSUE TITLE
setting HTTP response header in filter has no effect

### ISSUE THREAD

**Issue by Againster** [astaxie/beego#3373]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10.1

2. What operating system and processor architecture are you using (`go env`)?
```sh
GOHOSTARCH="amd64"
GOHOSTOS="linux"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```go
func init() {
	beego.InsertFilter("*", beego.BeforeRouter, CheckAccess, true)
	beego.InsertFilter("*", beego.BeforeRouter, CheckXSRF, true)
	beego.InsertFilter("*", beego.FinishRouter, AddHttpHeader, false, true)
}

func CheckAccess(ctx *context.Context) {
	fmt.Printf("access %p\n", ctx)
}

func CheckXSRF(ctx *context.Context) {
	fmt.Printf("xsrf %p\n", ctx)
}


func AddHttpHeader(ctx *context.Context) {
	ctx.Output.Header("Btoken", "3289649234")
	ctx.ResponseWriter.Header().Set("Qserver", "yeok")
	p := ctx.ResponseWriter.Header()
	fmt.Printf("header %p %p %+v\n", ctx, &p, p)
}
````

4. What did you expect to see?
U'll see command line log output:
```sh
access 0xc420236330
xsrf 0xc420236330
home 0xc420236330 0xc42020b6f0 map[Btoken:[yes]]
header 0xc420236330 0xc42020b738 map[Btoken:[3289649234] Content-Type:[application/json; charset=utf-8] Content-Length:[45] Qserver:[yeok]]
```

and my firefox or postman only receives this header:
```http
HTTP/1.1 200 OK
Content-Length: 45
Content-Type: application/json; charset=utf-8
Date: Tue, 30 Oct 2018 09:48:42 GMT
```
header ```Btoken Qserver``` was gone, I don't know why.

**Comment by lxShaDoWxl** [comment]
Seems like the right behavior, beego.FinishRouter is executed after the router is already called and the response is given to the client
Use beego.BeforeRouter to modify the response

**Comment by Againster** [comment]
@lxShaDoWxl 
Thx, finally I make it by your way.

**Comment by unmurphy** [comment]
@Againster hi aganster, firstly thank your post, but i got anotherr problem that how can i intercept the response? i want to log all response per request.
