### ISSUE TITLE
orm 创建表的时候一个结构体只能存在一次，没法使用同一个结构体创建多张表。

### ISSUE THREAD

**Issue by cxasm** [astaxie/beego#3374]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1,9.2比较新的。

2. What operating system and processor architecture are you using (`go env`)?
linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
我一个结构体 A ,我需要A创建出不同的表A1,A2，A1 A2都是一样的结构，只是数据库表名不同。
这种需求是很常见的。比如我有三张数据库表，三个表结构都是一样的，分别表示不同的版块，比如A1是电影，A2是杂志，A3是网站。当然我可以把A1 A2 A3都只用一个A来表示，但是那样的话我的A表会很大，在不同版块中查询时总是只能操作一个数据库表，这样效率很低。
另外由于GO不支持模板，语言层面我没法从A动态创建结构体A1 A2 ，但是orm创建表时只能存在一个A。再加一个A叫说重复的结构体了。这个设计导致有许多不方便之处。

目前有没有现成的比较好的解决方法。

5. What did you see instead?

**Comment by DennisMao** [comment]
#895  same
