### ISSUE TITLE
httplib的Get/Post..方法是长连接吗？

### ISSUE THREAD

**Issue by t2krew** [astaxie/beego#3375]
beego version: 1.10.1

场景：在并发比较大的情况下用 httplib.Get() 方法。
 
疑问： 看到httplib的DoRequest方法每次都是新new一个http.Client实例，这里是不是没法用到长连接？

**Comment by t2krew** [comment]
@astaxie

**Comment by DennisMao** [comment]
如果按你描述这样使用的话是没法用到.这个跟client实例无关，主要是transport,具体看https://godoc.org/net/http#Transport 
如果需要保持连接，可以设置一个全局的http.Transport  
```
var tp *http.Transport
tp = &http.Transport{}

c:=httplib.R
c. SetTransport(tp) // 复用同一个transport
```

**Comment by guhan121** [comment]
@DennisMao  请教一个问题；并发使用httplib的时候 ；是只设置一个http.Transport 还是每个worker设置一个？

**Comment by alberliu** [comment]
> @DennisMao 请教一个问题；成功使用httplib的时候；是只一个http.Transport还是设置每个worker设置一个？

这个只能设置一个全局的，每次设置一个不会复用的

**Comment by alberliu** [comment]
httplib默认不启动连接池，这个会产生误导，golang原生是启动的
