### ISSUE TITLE
router.go has a bug in 797 line 

### ISSUE THREAD

**Issue by Languege** [astaxie/beego#3380]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
master branch

2. What operating system and processor architecture are you using (`go env`)?
mac os

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

i want to change the router by UrlManager Filter, but meeting a mistake:

code:
```
var UrlManager = func(ctx *context.Context) {
	ctx.Input.RunController = reflect.TypeOf((*controllers.UserController)(nil)).Elem()
	ctx.Input.RunMethod = "Post"
}


func init(){
	beego.InsertFilter("*", beego.BeforeRouter, UrlManager)
}

```

mistake:
```
shokudo/vendor/github.com/astaxie/beego/router.go:798

```

Finally, I found this mistake caused by routerInfo variable is nil and performed initialize() func. I resoved it by add a condition in router.go 798 line, as follows:

```
if routerInfo != nil && routerInfo.initialize != nil {
```

**Comment by astaxie** [comment]
I can't get you idea. why `isRunnable` is true?

**Comment by astaxie** [comment]
Fixed in https://github.com/astaxie/beego/commit/876dce8e548d60cb8d0c8a8a6f37b371d0a9282f
