### ISSUE TITLE
最新版本在centos上长期运行占用内存很大，static文件目录没有处理好

### ISSUE THREAD

**Issue by laymer110** [astaxie/beego#3381]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 version 1.10

2. What operating system and processor architecture are you using (`go env`)?

在windows下长时间运行占用内存不会增加，而在centos下运行超过一天内存就会增加。
3. What did you do?
在centos下运行内存不断增加，直到沾满整个内存，自动退出。
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

经过检查是因为staticfile.go 和writeLevel方法占用的内存不释放。

4. What did you expect to see?

高深的地方看不懂，请大神指教。
5. What did you see instead?
我用最简单的ServerFile替换beego自带的 静态目录后，内存占用不会持续增加了，稳定在100M以内。

**Comment by fatalc** [comment]
@laymer110  我遇见了同样的问题，  版本 `v1.11.1` 。  我认为很有必要将此 issue 重新打开。 

https://github.com/astaxie/beego/blob/de7ce2f9b02dc0f4afe4f7c0a0304cfecb1b62c1/context/acceptencoder.go#L171

此处的处理，在文件为大文件的时候。内存占用极高。

举例：
  当静态文件为

```bash
ls -l -h logging-1.1.8.tgz 
-rw-r--r--  1 fatalc  staff   604M Jul 12 10:32 logging-1.1.8.tgz
```

正常运行：
![image](https://user-images.githubusercontent.com/15731850/61100455-cf374180-a498-11e9-8865-30d42d3db1e3.png)

发送请求后：

```bash
curl 127.0.0.1:8080/logging-1.1.8.tgz >> /dev/null
```

![image](https://user-images.githubusercontent.com/15731850/61100503-09084800-a499-11e9-96ad-8b046cc055c4.png)
