### ISSUE TITLE
beego下载问题

### ISSUE THREAD

**Issue by Crazy-Geng** [astaxie/beego#3385]
下载一个txt的问题，是落在/tmp下面的，发的post请求，这样就会直接乱码response，并不会以文件的方式下载，请问，哪里有问题呢？
func (this *DownloadController) Download() {
	res, _ := models.ParseDownLoadPath(this.Ctx.Input.RequestBody)
	this.Ctx.Output.Download(res.Filename)
}

**Comment by DennisMao** [comment]
@Crazy-Geng 请提供完整的请求信息和响应错误信息

**Comment by JessonChan** [comment]
这个并不是beego的问题，post用来下载需要其它支持，beego只负责后端的处理。你可以想其它的办法。一种策略是post返回新的下载链接，再get下载。
