### ISSUE TITLE
Orm: M2M带前缀查询异常

### ISSUE THREAD

**Issue by aveyuan** [astaxie/beego#3397]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10.1

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
在使用m2m查询的时候，如果注册的模型是使用带前缀的，按照文档上的方法执行，会异常，提示：`panic: unknown field/column name `Tags__Tag__Name`，如果去掉带前缀的模型，就能正常使用，目前使用了载入关系来临时解决这个问题。

```go
package main

import (
	"fmt"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
	"os"
)

func main()  {
	W_data()
	Q_data()
}

func W_data()  {
	o := orm.NewOrm()
	post := &Post{Title:"第一篇文章"}
	o.Insert(post)
	m2m := o.QueryM2M(post,"Tags")
	tag := &Tag{Name:"闲言"}
	o.Insert(tag)
	fmt.Scanln(m2m.Add(tag))
}

func Q_data()  {
	o := orm.NewOrm()
	var posts []*Post
	num, err := o.QueryTable(Post{}).Filter("Tags__Tag__Name", "闲言").All(&posts)
	fmt.Println(num,err)
	fmt.Println(posts[0].Title)
}

type Post struct {
	Id int
	Title string
	Tags []*Tag `orm:"rel(m2m)"`
}

type Tag struct {
	Id int
	Name string
	Posts []*Post `orm:"reverse(many)"`
}

func init()  {
	orm.RegisterDataBase("default","mysql","root:@tcp(127.0.0.1:3306)/beegorm?charset=utf8")
	orm.RegisterDriver("default",orm.DRMySQL)
	//orm.RegisterModelWithPrefix("test_",new(Post),new(Tag)) 使用这个带前缀的，m2m查询会失败
	orm.RegisterModel(new(Post),new(Tag))
	if len(os.Args)>=2&& os.Args[1]=="install"{
		orm.RunSyncdb("default",false,true)
	}

}

```

4. What did you expect to see?

5. What did you see instead?

**Comment by jianzhiyao** [comment]
@aveyuan @flycash 
That bug may be fixed in develop branch(git-hash:788de62b73c4cae26bb9c000e4675da28f7faade).
I can not reproduce that bug.
Could you help me to make sure that fixed bug?

That issue can be closed after making sure that bug fixed
