### ISSUE TITLE
统一验证TOKEN的实现思路

### ISSUE THREAD

**Issue by vipplayerdev** [astaxie/beego#3398]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
客户端请求时，每次都会带上TOKEN，beego服务端会尝试对前端发起的请求做TOKEN验证，目前在CONTROLLER中效验，当有多个控制器的时候，每个控制器都单独效验TOKEN显得很傻很重复。

4. What did you expect to see?
在同一入口处，捕获TOKEN参数，进行效验

5. What did you see instead?

**Comment by DennisMao** [comment]
@vipplayerdev  可以使用过滤器实现认证的中间件 https://beego.me/docs/mvc/controller/filter.md#%E8%BF%87%E6%BB%A4%E5%99%A8

**Comment by vipplayerdev** [comment]
@DennisMao tks!!!
