### ISSUE TITLE
Default value of request parameter doesn't work.

### ISSUE THREAD

**Issue by imrenagi** [astaxie/beego#3404]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.11.1 darwin/amd64
bee version 1.10.1

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/imrenagi/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/imrenagi/Documents/projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d4/4pl3n3z56kq3sdd953vv0_nh0000gp/T/go-build071073646=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
This is from the code generated by `bee api` command. I added `// @Param   brand_id    query   int 5 false  "brand id"` and `	fmt.Println(u.GetInt("brand_id"))` .

```
// @Title Get
// @Description get user by uid
// @Param	uid		path 	string	true		"The key for staticblock"
// @Param   brand_id    query   int 5 false  "brand id"
// @Success 200 {object} models.User
// @Failure 403 :uid is empty
// @router /:uid [get]
func (u *UserController) Get() {
	fmt.Println(u.GetInt("brand_id"))
	uid := u.GetString(":uid")
	if uid != "" {
		user, err := models.GetUser(uid)
		if err != nil {
			u.Data["json"] = err.Error()
		} else {
			u.Data["json"] = user
		}
	}
	u.ServeJSON()
}
```

Then I hit the endpoint by using  (without specifying the `brand_id`),
```
http://localhost:8080/v1/user/user_11111
```

4. What did you expect to see?
I expect `fmt.Println(u.GetInt("brand_id"))` will return `5 <nil>` because the default parameter will fill the missing query parameter.

5. What did you see instead?
`0 strconv.Atoi: parsing "": invalid syntax`

**Comment by luongs3** [comment]
did you resolve this error?
