### ISSUE TITLE
fatal error: 'sys/types.h' file not found

### ISSUE THREAD

**Issue by KingGanZeng** [astaxie/beego#3407]
When i was using vscode to install beego, it occurs that an error named 'fatal error' stopped my operation. Here is the code:
`knightdeMacBook-Pro-2:~ knight$ go get -u github.com/beego/bee
#github.com/beego/bee/vendor/github.com/derekparker/delve/proc
In file included from go/src/github.com/beego/bee/vendor/github.com/derekparker/delve/proc/proc_darwin.go:3:
./proc_darwin.h:1:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.`

**Comment by s00500** [comment]
Please use the correct repository for this issue!
https://github.com/beego/bee

**Comment by KingGanZeng** [comment]
Well, it still happens.
`go get github.com/beego/bee
#github.com/beego/bee/vendor/github.com/derekparker/delve/proc
In file included from go/src/github.com/beego/bee/vendor/github.com/derekparker/delve/proc/proc_darwin.go:3:
./proc_darwin.h:1:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
`

**Comment by KingGanZeng** [comment]
Here is the way to solve the problem.
https://github.com/beego/bee/issues/538#issuecomment-440248928
