### ISSUE TITLE
beego.BConfig.WebConfig.Session.SessionHashKey 设置问题

### ISSUE THREAD

**Issue by aveyuan** [astaxie/beego#3411]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11.0

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
根据文档：https://beego.me/docs/mvc/controller/session.md    里面写的一个`beego.BConfig.WebConfig.Session.SessionHashKey`配置文件，我发现结构里面根本没有这个。
打开路径:beego/config.go  94-107行，没有发现这行数据
```
type SessionConfig struct {
	SessionOn                    bool
	SessionProvider              string
	SessionName                  string
	SessionGCMaxLifetime         int64
	SessionProviderConfig        string
	SessionCookieLifeTime        int
	SessionAutoSetCookie         bool
	SessionDomain                string
	SessionDisableHTTPOnly       bool // used to allow for cross domain cookies/javascript cookies.
	SessionEnableSidInHTTPHeader bool // enable store/get the sessionId into/from http headers
	SessionNameInHTTPHeader      string
	SessionEnableSidInURLQuery   bool // enable get the sessionId from Url Query params
}
```
请问，这个配置是否已经取消，如果取消了请更新一下官网，如果没有取消，请告知一下它现在的作用是什么，在哪里可以找到？谢谢

4. What did you expect to see?

5. What did you see instead?

**Comment by Againster** [comment]
I also found that ```beego.BConfig.WebConfig.Session.SessionHashFunc``` doesn't exist

**Comment by Againster** [comment]
I also found that ```beego.BConfig.WebConfig.Session.SessionHashFunc``` has gone.

**Comment by nianiaJR** [comment]
+1

**Comment by MegaByte875** [comment]
+2

**Comment by flycash** [comment]
这个应该是很古老的东西了，老早就被删了，抱歉，我更新一下文档。

**Comment by flycash** [comment]
https://github.com/beego/beedoc/pull/925

如果后续发现了类似的问题，务必发个issue……我们好纠正过来
