### ISSUE TITLE
beego 项目编译之后，找不到views目录...求教

### ISSUE THREAD

**Issue by Yangk030208** [astaxie/beego#3432]
####
 beego的项目，执行命令 ` bee run`，项目没问题，可以正常渲染页面。
####   go:1.11  beego :1.10,     os: mac
报错截图
 
<img width="799" alt="2018-12-05 10 58 48" src="https://user-images.githubusercontent.com/23301914/49488691-b28fb700-f882-11e8-922d-e218fe84ae8d.png">

项目目录结构：
<img width="215" alt="2018-12-05 11 02 00" src="https://user-images.githubusercontent.com/23301914/49488639-65abe080-f882-11e8-9182-602755b85c59.png">

**Comment by DennisMao** [comment]
@Yangk030208  cd到工程目录,用tree工具贴下目录结构

**Comment by Yangk030208** [comment]
@DennisMao 

 **项目目录：**
<img width="453" alt="2018-12-06 11 46 47" src="https://user-images.githubusercontent.com/23301914/49564670-4b940000-f95f-11e8-8ae1-3b09068fec7f.png">


**编译之后的目录结构：**
<img width="364" alt="2018-12-06 1 59 44" src="https://user-images.githubusercontent.com/23301914/49564680-56e72b80-f95f-11e8-93b4-b1d1c7b811ed.png">

**Comment by DennisMao** [comment]
@Yangk030208 检查controller里面是否正确指定了模板文件的地址和名称
