### ISSUE TITLE
Grace 后 pid会变

### ISSUE THREAD

**Issue by flyhope** [astaxie/beego#3436]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build931563675=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
开启热升级，更新二进制文件，执行 kill -HUP $pid

4. What did you expect to see?
升级完成后，pid不变。
考虑FORK出子进程处理老的连接，父进程exec新程序，接受新的连接，不知能否这样设计？

5. What did you see instead?
升级完成后，pid变了。
这对Docker内（或Supervisor）执行的程序很不友好，会认为程序异常退出，Docker会直接跪掉。

**Comment by smallfish** [comment]
毕竟不是 m/s 结构，而且用 docker 不太建议使用热更新二进制的方式，这还是传统做法，而应该更新镜像（升级版本）
- 程序异常退出的话，可以设置容器 restart always 自动重启，这样升级完毕之后会自动重启
- supervisor 可以在更新完二进制之后，重新 reload/restart service，不需要 HUP

**Comment by flyhope** [comment]
> 毕竟不是 m/s 结构，而且用 docker 不太建议使用热更新二进制的方式，这还是传统做法，而应该更新镜像（升级版本），对外的服务应该需要想办法容忍后端挂掉，不能单点的情况，挂一个负载均衡，后端可以随便轮转灰度升级之类的
> 
> * 程序异常退出的话，可以设置容器 restart always 自动重启，这样升级完毕之后会自动重启
> * supervisor 可以在更新完二进制之后，重新 reload/restart service，不需要 HUP

首先希望还是能使用HUP来热更新，这样可以无缝升级服务，如果通过负载均衡再硬更新的话，如果是几十秒级别的长连接服务，操作起来过于繁索。

如果Beego目前不支持的情况，暂时我在Docker里执行这个脚本临时解决的。


```bash
#!/bin/bash

cmd=$1
$cmd

if [ "$cmd" == "" ]; then
    echo 'product.sh $start_cmd'
    exit 254
fi

while true
do
    pid=`ps aux |grep -F "$cmd" | grep -F -v product.sh | grep -F -v  grep | awk '{print $2}'| head -1`
    if [ "$pid" != "" ]; then
        echo "PID:$pid"
        tail --pid=$pid -f /dev/null
    else
        break
    fi
done
```
