### ISSUE TITLE
快速入门文档中运行的代码有错误

### ISSUE THREAD

**Issue by xkrumeng** [astaxie/beego#3439]
入门文档中 Windows 平台下输入：
`
cd %GOPATH%/src

bee new hello

cd hello

bee run hello
`
最后的bee run hello应改为bee run 才能正常运行哦

**Comment by DennisMao** [comment]
@xkrumeng  具体页面链接方便贴一下吗

**Comment by xkrumeng** [comment]
@DennisMao   https://beego.me/quickstart

**Comment by DennisMao** [comment]
@xkrumeng  谢谢,已修复
