### ISSUE TITLE
c.SetSession()设置完成后，当时有，刷新页面后变为原来值

### ISSUE THREAD

**Issue by xjz9600** [astaxie/beego#3445]
在第一次进入某个页面的时候设置c.SetSession()是成功的，但是再次进入这个页面，并重新设置c.SetSession()，新的值在当前页面是可以取到的，但是刷新当前页面或者跳转到别的页面，再取session值的时候，发现取出来的值是第一次设置的值

**Comment by xjz9600** [comment]
请问下这是个bug么，还是我哪里设置有问题？

**Comment by xjz9600** [comment]
再精炼下就是，第一次启动的时候调用c.SetSession()是成功的，但是在重新设置c.SetSession()后，设置页面取出的值是新值，刷新或跳转到别的页面，取出的session值还是第一次设置的值，c.SetSession()失效

**Comment by crazyIceChen** [comment]
应该在最后还要调用 c.CruSession.SessionRelease(c.Ctx.ResponseWriter)
