### ISSUE TITLE
mac 下 bee run 一直提示需要网络接入

### ISSUE THREAD

**Issue by ZhijianZhang** [astaxie/beego#3447]
![image](https://user-images.githubusercontent.com/11473889/50085919-75d69f00-0236-11e9-9248-343c1279cd68.png)
bee run 之后每次 `ctrl + s` 都会弹出这个框。 不知道是不是我个别原因，搜索了一些相关网络接入的解决办法貌似也不行

**Comment by DennisMao** [comment]
@ZhijianZhang  你的应用使用到网络端口,如果不想提示可以关闭防火墙或者添加到白名单即可。windows也同理。
