### ISSUE TITLE
toolbox/task.go  fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by fromiuan** [astaxie/beego#3448]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.8.0
├── GoVersion : go1.10.3
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : D:\go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Tuesday, 18 Dec 2018

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\
Temp\go-build741179110=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

```
fatal error: concurrent map iteration and map write
goroutine 51 [running]:
runtime.throw(0xa70b31, 0x26)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc000419c30 sp=0xc000419c00 pc=0x42de92
runtime.mapiternext(0xc000419d58)
	/usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc000419cb8 sp=0xc000419c30 pc=0x4108e5
github.com/astaxie/beego/toolbox.NewMapSorter(0xc00007d290, 0x402b29365f72c)
	/root/project/src/github.com/astaxie/beego/toolbox/task.go:475 +0x1b2 fp=0xc000419dc8 sp=0xc000419cb8 pc=0x7a21b2
github.com/astaxie/beego/toolbox.run()
	/root/project/src/github.com/astaxie/beego/toolbox/task.go:407 +0x1e0 fp=0xc000419fe0 sp=0xc000419dc8 pc=0x7a1b10
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000419fe8 sp=0xc000419fe0 pc=0x45bde1
created by github.com/astaxie/beego/toolbox.StartTask
	/root/project/src/github.com/astaxie/beego/toolbox/task.go:397 +0x52

goroutine 1 [chan receive, 18813 minutes]:
github.com/astaxie/beego.(*App).Run(0xc000110230, 0x0, 0x0, 0x0)
	/root/project/src/github.com/astaxie/beego/app.go:221 +0x262
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/root/project/src/github.com/astaxie/beego/beego.go:67 +0x62
main.main()
	/root/project/src/hbroker/main.go:70 +0x2a5
```

**Comment by flycash** [comment]
#4027
