### ISSUE TITLE
Use go mod the router namespace does not work?

### ISSUE THREAD

**Issue by im-here** [astaxie/beego#3450]
1. use ``bee api myproject`` to new a project,
2. then copy it out of the ``GOPATH``
3. ``go mod init myproject ``
4. ``go build``

Use the four steps above, then run it,  all router is 404, look at the  ``http://localhost:8088/listconf?command=router`` , routers is empty 

I just started learning golang

thanks

**Comment by k713927** [comment]
i meet this problum too,`import (
	"controllers"
	"github.com/astaxie/beego"
)`  it dosent work

**Comment by mehranabi** [comment]
Hi, Thanks for this awesome library, I have the similar problem,
I created new project using `bee api sample_beego_api` and then in `sample_beego_api` I started server using `bee run`, Server started successfully but all of routes return `404 Error` page.
Have I done anything wrong?!

**Comment by tvanriper** [comment]
Likewise, using the same steps.  Additional information, in case it's needed:

> PS C:\Users\jvanr\proxy> bee version
> ______
> | ___ \
> | |_/ /  ___   ___
> | ___ \ / _ \ / _ \
> | |_/ /|  __/|  __/
> \____/  \___| \___| v1.10.0
> 
> ├── Beego     : 1.11.1
> ├── GoVersion : go1.11.5
> ├── GOOS      : windows
> ├── GOARCH    : amd64
> ├── NumCPU    : 8
> ├── GOPATH    : C:\Users\jvanr\go
> ├── GOROOT    : C:\Go\
> ├── Compiler  : gc
> └── Date      : Monday, 11 Feb 2019

**Comment by tvanriper** [comment]
For whatever it's worth, my project is a kind of API/webpage hybrid, where I'm using beego.NewNamespace, but I'm also using beego.Get and beego.Router for other pages.

beego.Get and beego.Router works, but beego.NewNamespace appears to fail.

Furthermore, the swagger documentation works for the API, aside from not having the ability to exercise the API.

**Comment by tvanriper** [comment]
For me, the problem was in not importing context from github.com/ataxie/beego/context.  The tool I was using imported it from my project (which surprised me, as I didn't think it had a package with that name).

**Comment by eyasliu** [comment]
我发现了一些东西
在 beego.NSInclude 调用了 ns.Include，然后调用了 [n.handlers.Include](https://github.com/astaxie/beego/blob/develop/router.go#L250)，在这个Include里面做了一些操作，到 GOPATH 中去找include的对应的文件，[解析该文件](https://github.com/astaxie/beego/blob/develop/parser.go#L79)，[生成路由](https://github.com/astaxie/beego/blob/develop/parser.go#L411)，监听文件改动

所以在找controller文件的时候找不到，自然路由就没有注册成功，所以目前用了 go module 就不能用 NSInclude，但是 NSRouter 还是可以用的


---

I found something
In beego.NSInclude call ns.Include, then call n.handlers.Include, do some operations in this Include, go to GOPATH to find the corresponding file of include, parse the file, generate routing, listen for file changes

So when I find the controller file, I can't find it. The natural route is not registered successfully. So I can't use NSInclude with go module, but NSRouter can still work fine.

**Comment by tiptok** [comment]
目前也是用 ns.Router
