### ISSUE TITLE
命令行下连接不上github,如何安装beego

### ISSUE THREAD

**Issue by wbb18129355955** [astaxie/beego#3453]
有大神吗，我这里连接不上github，我能上github是挂了代理，但是我cmd就是连接不上，超时，ping不通，我可以将源码下载到本地吗，再进行编译安装吗?

**Comment by wbb18129355955** [comment]
please help me,please

**Comment by DennisMao** [comment]
@wbb18129355955  可以,github支持http方法下载压缩包,下载后需手动创建目录,把beego放到 $GOPATH/src/github.com/astaxie/  目录中。
