### ISSUE TITLE
orm table字段太多会创建失败

### ISSUE THREAD

**Issue by uf96800** [astaxie/beego#3457]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.9.0
2. What operating system and processor architecture are you using (`go env`)?

win7 64
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
@uf96800  
请提供：  
1.出问题的Models  
2.数据库对应版本  
3.错误信息  
谢谢！
