### ISSUE TITLE
Beego的orm框架支持MySQL中的函数吗？

### ISSUE THREAD

**Issue by hantmac** [astaxie/beego#3461]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego : 1.11.1
├── GoVersion : go1.10.3
├── GOOS : darwin
├── GOARCH : amd64
├── NumCPU : 8
├── GOPATH : /Users/username/go
├── GOROOT : /usr/local/go
├── Compiler : gc
└── Date : Saturday, 29 Dec 2018

What operating system and processor architecture are you using (go env)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?

我想实现这样的查询：
` select sum(cost), vendor from product group by vendor `
4. What did you expect to see?

这条语句可以有对应的orm：
select sum(cost), vendor from product group by vendor

5. What did you see instead?
目前beego貌似没有orm可以实现函数操作

**Comment by DennisMao** [comment]
@hantmac  you can use  `orm.Raw("SELECT count(id) as total FROM XXX")`. [orm.Raw() guide](https://beego.me/docs/mvc/model/orm.md#raw)

**Comment by DennisMao** [comment]
@hantmac  I understand what you want.It does not support all functions on the sql builder module.As function names vary from different databases.It's hard to be compatible.Your issue will be considered as proposal.

**Comment by hantmac** [comment]
> @hantmac I understand what you want.It does not support all functions on the sql builder module.As function names vary from different databases.It's hard to be compatible.Your issue will be considered as proposal.

Got it! Thanks!

**Comment by jeremywu0127** [comment]
> @hantmac I understand what you want.It does not support all functions on the sql builder module.As function names vary from different databases.It's hard to be compatible.Your issue will be considered as proposal.

Hi, as you mentioned above, how many  `mysql` built-in functions does beego orm support? How can I use the `mysql` built-in `date` function in beego orm ?
