### ISSUE TITLE
Can't use beego.AccessLogs now?

### ISSUE THREAD

**Issue by hantmac** [astaxie/beego#3474]
Please answer these questions before submitting your issue. Thanks!

What version of Go and beego are you using (bee version)?
├── Beego : 1.11.1
├── GoVersion : go1.10.3
├── GOOS : darwin
├── GOARCH : amd64
├── NumCPU : 8
├── GOPATH : /Users/username/go
├── GOROOT : /usr/local/go
├── Compiler : gc
└── Date : Saturday, 29 Dec 2018
What operating system and processor architecture are you using (go env)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I want to open access log use the next code:
```
func main() {
    beego.AccessLogs = true
    beego.Run()
}
```

4. What did you expect to see?

5. What did you see instead?
I got unresolved reference AccessLogs.
That seems like beego has no properity called AccessLogs.

**Comment by kotori2** [comment]
https://github.com/astaxie/beego/blob/d6c2a9fd4b7692c9f453fadc6197d3c85aad18d0/router.go#L912
`beego.BConfig.AccessLogs = true`

**Comment by IamCathal** [comment]
A bit late to the party but heres the solution. You can't access the `AccessLogs` field directly from the beego object. It is done like so:

```go
package main

import (
	_ "testapi/routers"

	"github.com/astaxie/beego"
)

func main() {

	beego.BConfig.Log.AccessLogs = true

	beego.Run()
}

```
