### ISSUE TITLE
HTTPlib使用这个设置header不生效

### ISSUE THREAD

**Issue by liuts** [astaxie/beego#3481]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10

2. What operating system and processor architecture are you using (`go env`)?
centos7.2

3. What did you do?
req.Header("Host", "www.baidu.com")不生效，
必须使用req.SetHost("www.baidu.com")才生效

4. What did you expect to see?

req.Header("Host", "www.baidu.com")能够生效

**Comment by DennisMao** [comment]
@liuts  因为这个Host并不仅仅是Header里,在http请求的底层结构中Host也是一个参数需要传入。
