### ISSUE TITLE
8080端口自动关闭

### ISSUE THREAD

**Issue by userQue** [astaxie/beego#3484]
beego程序运行一段时间，老是出现监听8080端口意外关闭的情况，不知道其他朋友有没有遇到过。

**Comment by DennisMao** [comment]
@userQue  可以提供出现问题前后的日志吗

**Comment by jianzhiyao** [comment]
希望可以描述一下端口号关闭的现象之类的情况。
此issue已经太久了，暂时关闭，有需要可以重新提交issue。
感谢支持！
