### ISSUE TITLE
log daily rotate bug

### ISSUE THREAD

**Issue by AllenX2018** [astaxie/beego#3488]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.10.4

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build917721504=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
use the beego log module to log information in my app and observe the log files

4. What did you expect to see?
I create a logger with name test.log and write logs to it since Jan 14th.After 00:00:00 of Jan 15th 2019,it should rotate to test.2019-01-15.001.log and beego will create a new test.log and write new log to it.

5. What did you see instead?
however,I saw that beego create not only a file named test.log but also a file named  test.2019-01-15.002.log.And guess what, the new log will be write to the test.2019-01-15.002.log,not the test.log file.

**Comment by aegsea** [comment]
Yes, I also found the same problem, the time on the log file name and the time in the content are not right.

**Comment by w344701119** [comment]
I found that the log would be clear every date,even if I set the config as "daily":true,"maxdays":30,"rotate":true
