### ISSUE TITLE
为什么dev模式下mac平台生成generate router from comments，但是linux平台却没有执行自动生成router文件

### ISSUE THREAD

**Issue by liangyd1024** [astaxie/beego#3505]
同一份代码，配置文件中runmode都是dev

linux下的配置
![image](https://user-images.githubusercontent.com/5831731/51735407-539c3080-20c2-11e9-824f-b9559f153ad9.png)

mac下的配置
![image](https://user-images.githubusercontent.com/5831731/51735448-6b73b480-20c2-11e9-895c-c55cb78a4ffe.png)

mac平台下可以自动生成routers
![image](https://user-images.githubusercontent.com/5831731/51735305-0ae47780-20c2-11e9-888b-b4e91ff02f48.png)

linux平台下却不执行生成routes的逻辑
![image](https://user-images.githubusercontent.com/5831731/51735347-2c456380-20c2-11e9-9d53-f886f53dd121.png)

请问下这是什么原因呢？

**Comment by mkby** [comment]
检查一下代码位置，目前来看beego只支持源码放在$GOPATH/src 下面才能自动生成注解路由，希望能支持一下go module
