### ISSUE TITLE
beego  request.body is emtpy

### ISSUE THREAD

**Issue by CoolRao** [astaxie/beego#3510]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
VERSION = "1.11.1"

2. What operating system and processor architecture are you using (`go env`)?
linux 64 (arch manjaro)

3. What did you do?

 samplile

html code:
```
<input id="file" name="file" type="file" value="" placeholder="选择文件" />
<input id="thumb" name="thumbPic" type="text" value="" hidden="hidden">
<input type="submit" value="提交" />
```
go code:

```
func (c *UploadController) Post() {
	u, _ := url.Parse("http://127.0.0.1:8091/")
	proxy := httputil.NewSingleHostReverseProxy(u)
	proxy.ServeHTTP(c.Ctx.ResponseWriter,c.Ctx.Request)
}
```
error info: 
```
http: proxy error: net/http: HTTP/1.x transport connection broken: http: ContentLength=32619650 with Body length 0
```

it can successed  by go handler(not contain beego),like this code , however beego have a error, what should  i do?

please give me a Solution

**Comment by CoolRao** [comment]
> <form action="upload" method="post" enctype="multipart/form-data">
    <input id="file" name="file" type="file" value="" placeholder="选择文件" />
    <input id="thumb" name="thumbPic" type="text" value="" hidden="hidden">
    <input type="submit" value="提交" />
</form>

**Comment by DennisMao** [comment]
@CoolRao  I do not know what requirements for your app are.You can try to configurate `copyrequestbody = true`  to your app's `app.conf`

**Comment by mohamadpk** [comment]
1.click F12 on firefox or chrome goto network tab see request and response .on request on form data see what you send to server? 
for sending file to server form must be like this
`
<form method="POST" enctype="multipart/form-data">
`

**Comment by CoolRao** [comment]
no more information, when I run this application, I send a post request, beego print a line error log
Browser does not have a response, all code is show Previous, do you run the code?

**Comment by rffanlab** [comment]
我遇到同样的状况，我用Postman的时候beego能接收到参数，我用axios发送post的时候beego就接收不到了，我看了请求的header 都是用的Content-Type:application/x-www-form-urlencoded，然而并没有什么用。我很奇怪，JS和POSTMAN请求之间有什么区别吗？

**Comment by hlily2005** [comment]
after proxy，multipartForm is nil……

**Comment by suridaddy** [comment]
@hlily2005 @abortrao can i ask you if you have solved the issue? if yes, can you show me your solution?
