### ISSUE TITLE
url重写

### ISSUE THREAD

**Issue by shehuaqigai** [astaxie/beego#3511]
Please answer these questions before submitting your issue. Thanks!

1. 1.11.1
2. redhat7.5
如何在请求还没走到路由的时候也就是过滤器里实现url重写
beego.InsertFilter("/*", beego.BeforeRouter, FilterUrlCity)

举个例子接口请求地址为
http://www.abc.com/guangzhou/gdb?year=2014
过滤器重写为
http://www.abc.com/gdb?year=2014
城市编号作为参数写入input,虽然redirect能实现，会重新跳转请求一次，性能不好，还不够优雅，由于历史原因只能这样做 而不能直接通过参数从请求里传过来，需要重写
试过给 ctx.Request.URL.Path =“gdb?year=2014”赋值，ctx.Request.RequestURI =“gdb?year=2014”赋值都不能进入指定控制器
我是新手，哪个大神能帮忙实现感激不尽

**Comment by hantmac** [comment]
要进入指定控制器的话，试一下这样行不行：
```
func (t *TestController) GetAll() {
beegoRequest := t.Ctx.Request
 beegoRequest.RequestURI = "xxxx"
}
```
