### ISSUE TITLE
请问beego 设置session的时候存的数据是怎样的数据编码

### ISSUE THREAD

**Issue by Hongjinpin** [astaxie/beego#3517]
就比如存储
value如下
\x0E\xFF\x81\x04\x01\x02\xFF\x82\x00\x01\x10\x01\x10\x00\x00\x04\xFF\x82\x00\x00
如何解码，变成可读性强的具体字符串

**Comment by mohamadpk** [comment]
you can decode blob bytes of session by using 
```
var kv map[interface{}]interface{}
v, err = session.DecodeGob([]byte(s["sessiondata"].([]uint8)))
```

**Comment by lizhenlin1** [comment]
...
