### ISSUE TITLE
Orm Create table without  default current_timestamp or on update

### ISSUE THREAD

**Issue by GeorgeXc** [astaxie/beego#3518]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 I didn't use bee

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/.gvm/pkgsets/go1.10.5/global"
GORACE=""
GOROOT="~/.gvm/gos/go1.10.5"
GOTMPDIR=""
GOTOOLDIR="~/gos/go1.10.5/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9t/43fwfvlx3hq4zjb1mzd_p0w40000gn/T/go-build711132233=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
`package main

import (

	"time"

	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

type User struct {
	Id          int    
	Name        string `orm:"unique"` 
	Age         int
	Description string    `orm:"size(100)"` 
	CreateTime  time.Time `orm:"auto_now_add;type(datetime)"`
	UpdateTime  time.Time `orm:"auto_now;type(datetime)"`
	NoUsed      string    `orm:"-"` 
}

func init() {
	orm.RegisterDataBase("default", "mysql", "test:123456@tcp(127.0.0.1:3306)/testdb?parseTime=True&loc=Local&charset=utf8")
	orm.RegisterModel(new(User))
	orm.Debug = true
	orm.RunSyncdb("default", true, true)
}`

4. What did you expect to see?

I expecte got a table named `user` with col `create_time` datetime NOT NULL DEFAULT current_timestamp and `update_time` datetime NOT NULL on update current_timestamp

5. What did you see instead?
`create_time` datetime NOT NULL,
  `update_time` datetime NOT NULL,

**Comment by zl03jsj** [comment]
i meet the same issue,  on mysql 
beego version is v1.12.1
mysql driver version v1.5.0
both are latest..
