### ISSUE TITLE
bee new command fails

### ISSUE THREAD

**Issue by marcoippolito** [astaxie/beego#3520]
Hi,
in my Ubuntu 18.04.01 Server Edition with go version go1.10.4 linux/amd64 installed ,

    marco@pc01:~/go/src$ go env
    GOARCH="amd64"
    GOBIN=""
    GOCACHE="/home/marco/.cache/go-build"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/marco/go"
    GORACE=""
    GOROOT="/usr/lib/go-1.10"
    GOTMPDIR=""
    GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="1"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-    
    build455079039=/tmp/go-build -gno-record-gcc-switches"

 I installed beego through the command:

    go get github.com/astaxie/beego

The hello.go example  : 
    package main

    import "github.com/astaxie/beego"

    func main(){
        beego.Run()
    } 

works fine.
But the command "bee new" doesn't work: 
 
    marco@pc01:~/go/src$ bee new my-first-beego-project

    Command 'bee' not found, did you mean:

      command 'btee' from deb ruby-bcat
      command 'be' from deb bugs-everywhere
      command 'ben' from deb ben
      command 'bel' from deb belier
      command 'beet' from deb beets
      command 'beef' from deb beef
      command 'ree' from deb ree
      command 'beep' from deb beep
      command 'bbe' from deb bbe
      command 'beer' from deb gerstensaft
      command 'tee' from deb coreutils
      command 'see' from deb mime-support
      command 'pee' from deb moreutils

    Try: sudo apt install <deb name>

How to solve the problem? 
Looking forward to your kind help.
Marco

**Comment by amrfaissal** [comment]
Hey Marco, Did you run `go get github.com/beego/bee`?

**Comment by marcoippolito** [comment]
After running  go get github.com/beego/bee
bee new my-first-beego-project works fine:

    bee new my-first-beego-project
    ______
    | ___ \
    | |_/ /  ___   ___
    | ___ \ / _ \ / _ \
    | |_/ /|  __/|  __/
    \____/  \___| \___| v1.10.0
    2019/02/01 10:51:55 WARN     ▶ 0001 You current workdir is not inside $GOPATH/src.
    2019/02/01 10:51:55 INFO     ▶ 0002 Creating application...
            create   /home/marco/go/src/my-first-beego-project/
            create   /home/marco/go/src/my-first-beego-project/conf/
            create   /home/marco/go/src/my-first-beego-project/controllers/
            create   /home/marco/go/src/my-first-beego-project/models/
            create   /home/marco/go/src/my-first-beego-project/routers/
            create   /home/marco/go/src/my-first-beego-project/tests/
            create   /home/marco/go/src/my-first-beego-project/static/
            create   /home/marco/go/src/my-first-beego-project/static/js/
            create   /home/marco/go/src/my-first-beego-project/static/css/
            create   /home/marco/go/src/my-first-beego-project/static/img/
            create   /home/marco/go/src/my-first-beego-project/views/
            create   /home/marco/go/src/my-first-beego-project/conf/app.conf
            create   /home/marco/go/src/my-first-beego-project/controllers/default.go
            create   /home/marco/go/src/my-first-beego-project/views/index.tpl
            create   /home/marco/go/src/my-first-beego-project/routers/router.go
            create   /home/marco/go/src/my-first-beego-project/tests/default_test.go
            create   /home/marco/go/src/my-first-beego-project/main.go
    2019/02/01 10:51:55 SUCCESS  ▶ 0003 New application successfully created!

Thank s a lot @amrfaissal 
Marco
