### ISSUE TITLE
Post 使用JSON发送请求的时候，接收到的为空

### ISSUE THREAD

**Issue by rffanlab** [astaxie/beego#3526]
接收端的代码为：
`loginReq := req.LoginReq{}
	logs.Info(c.GetString("username"))
	if err := json.Unmarshal(c.Ctx.Input.RequestBody, &loginReq); err != nil {
		logs.Error(c.Ctx.Input.RequestBody)
		logs.Error(err)
		loginResp.ParamsError()
	} else {
		logs.Info(loginReq)
		err := loginReq.Validated()
		loginResp.Referer = loginReq.Referer
		if err != nil {
			loginResp.ParamErrorWithMsg(err.Error())
		} else {
			loginResp = class.LoginCheck(loginReq)
			c.SetSession("token", loginResp.Data)
		}
	}`
发送端的代码为：
`var logindata = {
                username:$("input[name=username]").val(),
                passowrd:$("input[name=password]").val(),
                referer:document.referrer
            };
            var data = {
                url:api.login,
                realdata:logindata
            };
            $.ajax({
                url:api.login,
                type:"post",
                headers:{
                    "Content-Type":"application/json"
                },
                data:JSON.stringify(logindata),
                dataType:"json",
                success:function (res) {
                    if (res.status){
                        store.setItem("token",res.data)
                    } else {
                        alert(res.msg)
                    }
                }
            })`
我以为我的发送端代码错了，所以我换了语言，用Java的Spring boot试了，能成功接收到，用Python的Flask也能接收到
`go version go1.11.1 windows/amd64`
latest beego version

**Comment by guhan121** [comment]
@rffanlab 

set `copyrequestbody = true` in your `conf/app.ini`

**Comment by rffanlab** [comment]
@guhan121 
Already set but not work.
I've replace my api framework to gin and it works well as when I using Java and Python.

**Comment by nkjackzhang** [comment]
刚才测试了一下，对象的字段必须用大写开头，无论json的字段是大写还是小写开头，都可以正常获得，如果是对象的字段是小写开头的，则获取不到，你的LoginReq对象字段是怎么写的

**Comment by rffanlab** [comment]
@nkjackzhang 
这肯定的啊，大写是Golang被外部调用的标准啊。肯定会大写的啊。

**Comment by rffanlab** [comment]
@nkjackzhang 
对象在这里，你可以看看
`
type LoginReq struct {
	BaseReq
	Username string `form:"username" valid:"Required"`
	Password string `form:"password" valid:"Required"`
	Referer string `form:"referer"`
}
`

**Comment by rffanlab** [comment]
@nkjackzhang 
```golang
type LoginReq struct {
	BaseReq
	Username string `form:"username" valid:"Required"`
	Password string `form:"password" valid:"Required"`
	Referer string `form:"referer"`
}

```

**Comment by DennisMao** [comment]
@rffanlab   刚刚看了你的发送端代码,是设置Json tag的问题,把LoginReq加上json tag
```
type LoginReq struct {
	BaseReq
	Username string `json:"username" form:"username" valid:"Required"`
	Password string `json:"password" form:"password" valid:"Required"`
	Referer string `json:"referer" form:"referer"`
}
```

**Comment by nkjackzhang** [comment]
> 
> 
> @nkjackzhang
> 
> ```go
> type LoginReq struct {
> 	BaseReq
> 	Username string `form:"username" valid:"Required"`
> 	Password string `form:"password" valid:"Required"`
> 	Referer string `form:"referer"`
> }
> ```

![图片](https://user-images.githubusercontent.com/2102078/54585951-7e698c00-4a56-11e9-94a6-116c45f85354.png)

打了断点之后可以发下，可以解析成对象的，password是空白是因为你代码里post的key写错了

**Comment by nkjackzhang** [comment]
> 
> 
> @rffanlab 刚刚看了你的发送端代码,是设置Json tag的问题,把LoginReq加上json tag
> 
> ```
> type LoginReq struct {
> 	BaseReq
> 	Username string `json:"username" form:"username" valid:"Required"`
> 	Password string `json:"password" form:"password" valid:"Required"`
> 	Referer string `json:"referer" form:"referer"`
> }
> ```
用form甚至不用tag也是可以的

**Comment by rffanlab** [comment]
@nkjackzhang 
感谢大佬，但是我已经改用gin来前端接收数据了。另外。开始的时候我就是连form都接收不了。才改用的json去请求的。然后就发生了这种事情。

**Comment by nkjackzhang** [comment]
> 
> 
> @nkjackzhang
> 感谢大佬，但是我已经改用gin来前端接收数据了。另外。开始的时候我就是连form都接收不了。才改用的json去请求的。然后就发生了这种事情。

文档已经清楚的写了该怎么[解析json数据](https://beego.me/docs/mvc/controller/params.md#%E8%8E%B7%E5%8F%96-request-body-%E9%87%8C%E7%9A%84%E5%86%85%E5%AE%B9)，还是仔细看文档吧

**Comment by DennisMao** [comment]
@rffanlab  这个跟用哪个框架没有什么关系,gin里面也是需要bind tag,这是Go设计的规范。我总结下,遇到这种问题的解决思路:
```
1.首先是请求,确保请求的method和content-type是对的
2.把beego.BConfig.CopyRequestBody = true 打开,然后打印出body的内容 (如果做了这一步,其实这个问题可以更早得到解决)
2.最后确定反序列化的tag设置,前缀是否大写,类型是否正确
```
