### ISSUE TITLE
How too use Chunked to upload file and steam?

### ISSUE THREAD

**Issue by LiveXy7** [astaxie/beego#3531]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

├── Beego     : 1.11.1
├── GoVersion : go1.11.5
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/live/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Wednesday, 13 Feb 2019

2. What did you do?
 
I want to get the upload file with chunked file . but now it doesn't work
suck as when I upload a 1GB file , it can chunked 10MB* 100 to upload.
and  how I can sent steam data?

I use it for upload file
https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads

**Comment by guhan121** [comment]
websocket can do it!
