### ISSUE TITLE
mysql orm 关于description问题

### ISSUE THREAD

**Issue by 19940308cai** [astaxie/beego#3532]
`
Username string `orm:"column(username);size(100)" description:"昵称"`

执行建表后, show create table 
 
`username` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '',

`

**Comment by 19940308cai** [comment]
> `Username string`orm:"column(username);size(100)" description:"昵称"`
> 
> 执行建表后, show create table
> 
> `username` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '',
> 
> `

没有注释

**Comment by NSObjects** [comment]
https://github.com/astaxie/beego/pull/3190#issuecomment-463873908

**Comment by 19940308cai** [comment]
thanks @NSObjects @DennisMao
