### ISSUE TITLE
Can not read config from conf/app.conf after using beego.LoadAppConfig

### ISSUE THREAD

**Issue by xr-hui** [astaxie/beego#3534]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.11 darwin/amd64                    

2. What operating system and processor architecture are you using (`go env`)?
amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I use beego.LoadAppConfig to load personal dev config (conf/dev.conf)

4. What did you expect to see?
![image](https://user-images.githubusercontent.com/19950614/52781164-d4799700-3086-11e9-985a-aaf06e48ec45.png)
I want to read config (beego.AppConfig.String) from `conf/app.conf` after I use beego.LoadAppConfig to load personal dev config `conf/dev.conf`

5. What did you see instead?
I can not read the config (beego.AppConfig.String) from `conf/app.conf` any more after I use beego.LoadAppConfig. I can only get the config content from `conf/dev.conf`.

**Comment by guhan121** [comment]
i think you must only load the beego config for one file.
load default app.conf in `Config.go  -> func init()`.

if you want use  personal config for `conf/dev.conf`,don't use `LoadAppConfig` it will replace configuration for `app.conf`. you can use `github.com/astaxie/beego/config` get your setting.

**Comment by xr-hui** [comment]
I got it! Thanks a lot.
