### ISSUE TITLE
How to host beego api on IIS with AspNetCoreModule?

### ISSUE THREAD

**Issue by baijdzm** [astaxie/beego#3536]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.11.1
├── GoVersion : go1.10.3
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\Go-workspace
├── GOROOT    : C:\Go
├── Compiler  : gc
└── Date      : Friday, 15 Feb 2019
2. What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sgao\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Go-workspace
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\dzm\AppData\Local\Temp\go-build673153222=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Just trying to host beego api on IIS. I always get 404 page, seems like the routing can't work.  
1- Download shorturl sample and it can be run on localhost:8080.
2- Add below codes in main.go
      if port := os.Getenv("ASPNETCORE_PORT"); port != "" { // get enviroment variable that set by ACNM
		if p, err := strconv.Atoi(port); err == nil {
			beego.BConfig.Listen.HTTPPort = p
		}
	}

       beego.Router("/", &controllers.MainController{})
       ...
3- Change the runmode to prod in app.conf, otherwise " panic: you are in dev mode. So please set gopath goroutine " issue will occur.

4- followed by this instruction https://medium.com/@mossila/running-go-behind-iis-ce1a610116df
-----Created a site surl under the default web site 
![default](https://user-images.githubusercontent.com/47667905/52865860-7b8a2b80-3178-11e9-98b9-02f15c1d41ad.png)

![default](https://user-images.githubusercontent.com/47667905/52866022-c7d56b80-3178-11e9-8b0b-b6ec33d7f23a.png)

------Created the NoManagedCode pool

4. What did you expect to see?
When accessing the url http://localhost/surl/v1/expand, the expect result should as below.
![default](https://user-images.githubusercontent.com/47667905/52865091-af645180-3176-11e9-87ce-11807d8632cb.png)

5. What did you see instead?
![default](https://user-images.githubusercontent.com/47667905/52865183-f94d3780-3176-11e9-90e9-dba1898220e4.png)

**Comment by baijdzm** [comment]
content in web.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
        </handlers>
        <aspNetCore processPath=".\shorturl.exe"  stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout"/>
    </system.webServer>
</configuration>


And i got this in the log file: 2019/02/15 23:09:13.855 [I] [asm_amd64.s:2361]  http server Running on http://:22527
[beego]

**Comment by baijdzm** [comment]
With my understanding, because we could see the 404 page, that means, beego should work.
Should be some problems that make the routing can't work correctly?

**Comment by guhan121** [comment]
i think your static dir not in correct path.

**Comment by baijdzm** [comment]
Thanks for your reply!
To run the app only, i can get the correct result. Please see the pic in step 4.
in fact, 'surl' is not a folder in go source code. It's a virtial directory/application folder of IIS.

**Comment by baijdzm** [comment]
I found this, not sure if it is a "Correct" way to handle this question.
to modify the router registration codes like below
`beego.Router("/surl/v1/shorten", &controllers.ShortController{})`
Just add the virtual path as a prefix of the router namespace, in this case, it's "surl".

Also works in below style 

`ns := beego.NewNamespace("/surl/v1",
		beego.NSNamespace("/short",
			beego.NSInclude(
				&controllers.ShortController{},
			),
		),`

I don't know if it is best practice here. 
Will this introduce any issue?

**Comment by baijdzm** [comment]
Seems the beego swagger can't work with this code
`ns := beego.NewNamespace("/surl/v1", beego.NSNamespace("/short", beego.NSInclude( &controllers.ShortController{}, ), ),`

While testing the API, the swagger can not generate the router correctly, the "surl" was missed.

Could anyone please confirm this?

**Comment by baijdzm** [comment]
Closed this issue since the original problem was resolved.
