### ISSUE TITLE
controller怎么支持含数组的json？

### ISSUE THREAD

**Issue by novem999** [astaxie/beego#3537]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.11 , beego 1.11.1

2. What operating system and processor architecture are you using (`go env`)?
win 10 64bit

3. What did you do?
需要返回给浏览器的json的格式为：
{
  "code": 0,
  "msg": "",
  "count": 1000,
  "data": [{}, {}]
} 
其中data是数组。
那么，赋值给c.Data["json']的struct应该是什么样的？data字段用切片来实现吗？还是其他的方式？

4. What did you expect to see?

5. What did you see instead?

**Comment by hantmac** [comment]
data是数组的话，可以将数组内容定义为struct,data存放指向这些struct的指针。

- 举个🌰：
```
type BaseResponse struct {
     code int
    msg string
    count int64
}
type All struct {
	Base BaseResponse
	Data []*DataStruct
}
type DataStruct struct {
name string
user string
xxxx ....
}
```

**Comment by novem999** [comment]
谢谢，按照你的方法成功了。
