### ISSUE TITLE
Cannot return JSON with non-200 status code

### ISSUE THREAD

**Issue by cuongnguyenvirtual** [astaxie/beego#3538]
Already read through https://github.com/astaxie/beego/issues/1208 but cannot fix the issue.

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
├── Beego     : 1.11.1
├── GoVersion : go1.11.5
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 12
├── GOPATH    : E:\Source\golang
├── GOROOT    : C:\Go
├── Compiler  : gc
└── Date      : Sunday, 17 Feb 2019
```

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\NDC\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Source\golang
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\NDC\AppData\Local\Temp\go-build228416530=/tmp/go-build -gno-record-gcc-switches
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I added this on UserController:
```
func NewErrorResponse(code int, message string) interface{} {
	response := BaseResponse{}
	response.Meta = ErrorMeta{
		Code:    code,
		Message: message,
	}
	return response
}

func (c *UserController) GetOne() {
	c.Ctx.Output.SetStatus(404)
	c.Data["json"] = NewErrorResponse(404000, "not found")
	c.ServeJSON()
}
```

Added this in main.go:
```
beego.BConfig.CopyRequestBody = true
```
Run app using bee run

4. What did you expect to see?
API returning status 404 along with json data in response's body.

5. What did you see instead?
API returning status 404 with empty body.
![beego_404_empty_body](https://user-images.githubusercontent.com/47719727/52916264-aeb2f300-330f-11e9-99b3-368f0a278322.PNG)

Edit: using `c.Ctx.Output.JSON(errResponse, false, false)` is not working either.

**Comment by guhan121** [comment]
@cuongnguyenvirtual 
what are definitions of  BaseResponse and ErrorMeta ?

and 404 is a default Error, if you want use 404, must rewrite `Errorhandler`

like

`

func page_not_found(rw http.ResponseWriter, r *http.Request){
    t,_:= template.New("404.html").ParseFiles(beego.ViewsPath+"/404.html")
    data :=make(map[string]interface{})
    data["content"] = `{"code":404000,"message": "not found"}`
    t.Execute(rw, data)
}
 
func main() {
    beego.Errorhandler("404",page_not_found)
    beego.Router("/", &controllers.MainController{})
    beego.Run()
`
if think you can write your json string to `data["content"] `

you can try it!

**Comment by cuongnguyenvirtual** [comment]
> @cuongnguyenvirtual
> what are definitions of BaseResponse and ErrorMeta ?
Here it is:
```
type BaseResponse struct {
	Data interface{} `json:"data,omitempty"`
	Meta interface{} `json:"meta,omitempty"`
}

type ErrorMeta struct {
	Code int `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
```

> and 404 is a default Error, if you want use 404, must rewrite `Errorhandler`
> ...
> you can try it!
Thanks for your response.
Let me try.

**Comment by cuongnguyenvirtual** [comment]
@guhan121 Sorry for late response.
My project is an API service and your guideline seems to be about web server.
Is there any way to return status 404 with API method?

**Comment by Wusuluren** [comment]
@cuongnguyenvirtual Take it easy. 
You can make some change with what @guhan121 has written, just like this:
```
func page_not_found(rw http.ResponseWriter, r *http.Request){
    rw.Write([]byte(`{"code":404000,"message": "not found"}`))
}
 
func main() {
    beego.Errorhandler("404",page_not_found)
    beego.Router("/", &controllers.MainController{})
    beego.Run()
}
```
This is what an API service needed.

**Comment by pedrohff** [comment]
I'm also having this problem. Does not matter if it's a 404, neither if I'm overriding the error handler with a json response. If I get an result, that the type does not belong to the value of the `@Success` tag, it will hide the response body on Swagger (and on Swagger only).

**Comment by flycash** [comment]
Now we has resolved this issue, you can try it. see https://github.com/beego/swagger/pull/9
