### ISSUE TITLE
orm模块使用QueryRows时数据异常，id字段的值全为0了

### ISSUE THREAD

**Issue by novem999** [astaxie/beego#3540]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.11 , beego 1.11.1

2. What operating system and processor architecture are you using (`go env`)?
 win 10 64bit，sqlite3

3. What did you do?
使用orm模块的原生sql方式，通过QueryRows从数据库中获取数据：
type Title struct {
	TitleID   int64
	TitleCode string
	TitleName string
	IsUsing   int64
}

func GetCXList() (int64, []Title) {
	o := orm.NewOrm()
	sql := “select title_id, title_code, title_name, is_using from titles where title_pid=(select title_id from titles where title_code='10')”
	var titles []Title
	num, _ := o.Raw(sql).QueryRows(&titles)
	return num, titles
}

获取到的titles：
{0 1001 数据1 1}
{0 1002 数据2 1}
其中第一个字段，本来数据库中是有值的，可是这里全都变成了0，这是bug还是我使用的有问题？
数据库结构如下：
CREATE TABLE titles (
    title_id   INTEGER         PRIMARY KEY AUTOINCREMENT,
    title_pid  INTEGER,
    title_code TEXT (50),
    title_name TEXT (50)
);

4. What did you expect to see?

5. What did you see instead?

**Comment by guhan121** [comment]
先试一下这个 https://beego.me/docs/mvc/model/models.md 我一般是用mysql设计好表格，生成对应的models ，然后再把mysql的造表sql放到sqlite里面执行。

**Comment by novem999** [comment]
> 先试一下这个 https://beego.me/docs/mvc/model/models.md 我一般是用mysql设计好表格，生成对应的models ，然后再把mysql的造表sql放到sqlite里面执行。

这个是已有的数据库，所以不需建表。
而且我改用Values方法后能得到正确数据，就是要转换数据类型麻烦点。看来还是有bug？

**Comment by nkjackzhang** [comment]
你这个sql写的怎么这么啰嗦，不就是同一个表里查询吗？那直接select title_id, title_code, title_name, is_using from titles where title_code='10'不就可以了？

**Comment by novem999** [comment]
原来是自动名称转换导致的，结构体的TitleID被对应为sql结果集中的title_i_d,所以sql必须改成：
select title_id as title_i_d 才行
