### ISSUE TITLE
Could not show tables

### ISSUE THREAD

**Issue by cyy314** [astaxie/beego#3543]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by cyy314** [comment]
bee api testapi -tables="" -driver=postgres -conn="root:123456@tcp(127.0.0.1:5432)/test"
 FATAL    ▶ 0007 Could not show tables: missing "=" after "postgres:123456@tcp(192.168.100.181:5432)/test" in connection info string"
why?

**Comment by nkjackzhang** [comment]
Would you like use at least one option like "postgres://pqgotest:password@localhost/pqgotest?sslmode=verify-full"，I guess it's github.com/lib/pq which pops this error
