### ISSUE TITLE
get 获取数据丢失

### ISSUE THREAD

**Issue by zhonghuabao** [astaxie/beego#3545]
这是一个url    http://localhost:8099/order?token=4WG6wZIqInYIgjyY0FzJY/rePBE+LqGUPZ4qHxwAGPA=
 token字符有个“ + ”    号
用GetString获取， “+” 会被代替成空白

**Comment by DennisMao** [comment]
@zhonghuabao  这是正常的W3C规范,需要用+号的话建议先转义。

**Comment by nkjackzhang** [comment]
而且是go本身在input.Context.Request.ParseForm()的时候进行了转义，不是beego做的
