### ISSUE TITLE
orm结构的主键可以是string类型的么?

### ISSUE THREAD

**Issue by creamJelly** [astaxie/beego#3546]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.11.1
├── GoVersion : go1.10.1

2. What operating system and processor architecture are you using (`go env`)?
├── GOOS      : windows
├── GOARCH    : amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
自定义orm结构如下
`type Ltv struct {

	Id        string    \`json:"id" orm:"column(id); type(string); size(50); pk"\`
	EventDate time.Time \`json:"eventDate" orm:"column(eventDate); type(date); index"\`
	Ltv60  float64 \`json:"ltv60" orm:"column(ltv60); digits(12);decimals(2);default(0.00)"\`
	Ltv90  float64 \`json:"ltv90" orm:"column(ltv90); digits(12);decimals(2);default(0.00)"\`
	Ltv180 float64 \`json:"ltv180" orm:"column(ltv180); digits(12);decimals(2);default(0.00)"\`
	Ltv360 float64 \`json:"ltv360" orm:"column(ltv360); digits(12);decimals(2);default(0.00)"\`
}`

执行代码如下
`
	user := models.Ltv{Id:utils.GetFormatDateStr(opsTime), EventDate: utils.GetDayBeginTime(opsTime)}
	// 三个返回参数依次为：是否新创建的，对象 Id 值，错误
	created, id, err := tlogOrm.ReadOrCreate(&user, "id")
`

4. What did you expect to see?
没有报错

5. What did you see instead?

reflect: call of reflect.Value.Int on string Value

**Comment by hantmac** [comment]
不知道`beego`支持不支持使用字符串作为主键

**Comment by creamJelly** [comment]
> 貌似`beego`不支持使用字符串作为主键，你把主键的类型换成`int`试一下

之前有试过Id字段为Int类型。
EventDate字段的值实际上的唯一的，也就是一天一条。但是在使用ReadOrCreate方法的时候，不指定Id的值，就会出现多行。比如数据库中已经存在一条Id为10，EventDate为"2019-02-27"的数据，这个时候再使用ReadOrCreate方法的时候，数据库中会出现一条新的数据，Id不为10且EventDate为"2019-02-27"的数据。
想用String类型当主键是企图曲线救国，但是失败惹

**Comment by hantmac** [comment]
> > 貌似`beego`不支持使用字符串作为主键，你把主键的类型换成`int`试一下
> 
> 之前有试过Id字段为Int类型。
> EventDate字段的值实际上的唯一的，也就是一天一条。但是在使用ReadOrCreate方法的时候，不指定Id的值，就会出现多行。比如数据库中已经存在一条Id为10，EventDate为"2019-02-27"的数据，这个时候再使用ReadOrCreate方法的时候，数据库中会出现一条新的数据，Id不为10且EventDate为"2019-02-27"的数据。
> 想用String类型当主键是企图曲线救国，但是失败惹

个人建议不要全家桶都用beego，推荐gin+gorm,灵活性高一些

**Comment by nkjackzhang** [comment]
created, id, err := tlogOrm.ReadOrCreate(&user, "id")是要把主键当int返回给中间的那给返回值的，而你的主键是string，所以才报了reflect: call of reflect.Value.Int on string Value的错误，正确用法是主键使用int类型，调用ReadOrCreate时使用如下代码：
`user := &models.Ltv{EventDate: utils.GetDayBeginTime(opsTime)}`
`created, id, err := tlogOrm.ReadOrCreate(&user, "EventDate")`
因为如果ReadOrCreate指定了后面的可变参数，就会用其作为where里的字段，否则就使用主键

**Comment by creamJelly** [comment]
> > > 貌似`beego`不支持使用字符串作为主键，你把主键的类型换成`int`试一下
> > 
> > 
> > 之前有试过Id字段为Int类型。
> > EventDate字段的值实际上的唯一的，也就是一天一条。但是在使用ReadOrCreate方法的时候，不指定Id的值，就会出现多行。比如数据库中已经存在一条Id为10，EventDate为"2019-02-27"的数据，这个时候再使用ReadOrCreate方法的时候，数据库中会出现一条新的数据，Id不为10且EventDate为"2019-02-27"的数据。
> > 想用String类型当主键是企图曲线救国，但是失败惹
> 
> 个人建议不要全家桶都用beego，推荐gin+gorm,灵活性高一些

已经改用gorm了·· 而且gorm支持联合主键，用着更方便一些

**Comment by nkjackzhang** [comment]
> 
> 
> > 貌似`beego`不支持使用字符串作为主键，你把主键的类型换成`int`试一下
> 
> 之前有试过Id字段为Int类型。
> EventDate字段的值实际上的唯一的，也就是一天一条。但是在使用ReadOrCreate方法的时候，不指定Id的值，就会出现多行。比如数据库中已经存在一条Id为10，EventDate为"2019-02-27"的数据，这个时候再使用ReadOrCreate方法的时候，数据库中会出现一条新的数据，Id不为10且EventDate为"2019-02-27"的数据。
> 想用String类型当主键是企图曲线救国，但是失败惹

因为ReadOrCreate的原理是先Read，没有查到结果就Insert，你没有指定作为Where条件的字段，默认使用Id，而你又没有提供Id，所以才会Insert，你用tlogOrm.ReadOrCreate(&user, "EventDate")查询，只要保证EventDate是唯一的就行

**Comment by creamJelly** [comment]
> Create的原理是先Read，没有查到结果就Insert，你没有指定作为Where条件的字段，默认使用Id，而你又没有提供Id，所以才会Insert，你这种需求用tlogOrm.ReadOrCreate(&user, "EventDate")查询，只要保证EventDate是唯一的就行

可以了！ 多谢!
