### ISSUE TITLE
请求有计划发布 beego2 么？

### ISSUE THREAD

**Issue by runner-mei** [astaxie/beego#3553]
请求有计划发布 beego2 么？ gocn.vip 中有听说， 怎么没下文了？

**Comment by vietlib** [comment]
I hope to see beego2 too

**Comment by Reve-wang** [comment]
me too

**Comment by haytoo1** [comment]
米兔

**Comment by lifei6671** [comment]
me too

**Comment by maxshine** [comment]
Is there a list of features / fixed planned for beego2?

**Comment by JessonChan** [comment]
@astaxie

**Comment by JessonChan** [comment]
希望2.0可以更简单一些，并改进以下：
1、只支持API模式就足够了，不需要再支持网页
2、把log/orm/validation/task/swagger等一并移除beego，有可能只保留最基础的interface，保证beego2.0以下的版本可以改动少量就能兼容。实际上log和orm都有非常优秀的实现（logrus/gorm），比beego的组件更易用
3、重新实现router，尤其关于路由注册的API
4、更好的规划配置文件，现在配置文件在分层设计上并不够全面
5、实现9种最基本的http method（get head post put patch delete connect options trace），尤其options和trace，对于webDAV 不需要支持（现在代码中有很多webDAV定义，但没有对应的实现，完全没有必要）
6、更好的实现bee工具，有可能是以后beego的编译只能由bee来完成，这样的好处是可以实现很多的hijack

**Comment by 5046312** [comment]
同样期待

**Comment by GNURub** [comment]
I'm building from a fork, a series of features that break the compatibility, I hope to merge all those features in beego so we can enjoy them.
You can see them: github.com/goasana/asana. It is a temporary project not for production, merge when you see that it is sufficiently stable.
