### ISSUE TITLE
How to config beego with mongodb

### ISSUE THREAD

**Issue by vietlib** [astaxie/beego#3556]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11 now

2. What operating system and processor architecture are you using (`go env`)?
Window 10

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
I want to intergrade beego and mongodb

5. What did you see instead?

**Comment by DennisMao** [comment]
@vietlib  Hi. Beego/orm  does not  support Mgo in the current version. You can integrate with https://github.com/mongodb/mongo-go-driver or https://github.com/go-mgo/mgo.
