### ISSUE TITLE
How to figure out the root cause of memory leak in beegon application

### ISSUE THREAD

**Issue by Silence2012** [astaxie/beego#3559]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.9.2
Bee         :v1.9.1
go           : v1.10.1
2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

3. What did you do?
systemctl status beego application

4. What did you expect to see?
the used memory should be kept at some number

5. What did you see instead?

the used memory  is up to 1.8G

any better way to figure out the root cause.

**Comment by JessonChan** [comment]
pprof package will help.
