### ISSUE TITLE
ServeJSON方法导致在过滤器中获取不到status

### ISSUE THREAD

**Issue by Cloudzp** [astaxie/beego#3562]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 bee version  v1.10.0

2. What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOCACHE=***
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\cloud_zp\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
设置了c.ServeJSON()之后，在filter中获到status为：0 信息；
代码如下：
```
func init() {
	beego.InsertFilter("/",beego.FinishRouter, func(context *context.Context) {
		beego.Error("status:", context.Output.Status)
	},false)

    beego.Router("/", &controllers.MainController{})
}

func (c *MainController) Get() {
	c.Ctx.Output.SetStatus(http.StatusOK)
	c.ServeJSON()
}
```
![image](https://user-images.githubusercontent.com/25190767/54068094-65f1b880-4283-11e9-94fc-22fdebaaab2c.png)

尝试注释掉<code>c.ServeJSON()</code>,获取到status为200；
![image](https://user-images.githubusercontent.com/25190767/54068083-3e025500-4283-11e9-9989-0d4684258d4b.png)

4. What did you expect to see?

5. What did you see instead?

**Comment by nkjackzhang** [comment]
你看看这几行[代码](https://github.com/astaxie/beego/blob/bc8fffe3477beca03c9f0b8e6b67e1e30c1860dd/context/output.go#L78-L83)，总之，你可以从response里获取httpstatus 200，output.Status里的会给你改成0的，你获取不到
