### ISSUE TITLE
包含 string 和 splat route bug

### ISSUE THREAD

**Issue by vossem** [astaxie/beego#3563]
if using regex route like this 
beego.Router("/:ns:string/*", &controllers.MainController{})
and visit
/hello/a/b/c
shouldn't 404

beego version: 40d653e659caf86e72bcad254a52cc839d347b25

**Comment by nkjackzhang** [comment]
这种写法会转换成一个正则表达式，^/(\\w)/([^/]+)$，所以*无法跨/匹配，不知道为什么会是这样的设计，如果用/abc/*，就不会用正则表达式，直接把后面的都当做:splat
