### ISSUE TITLE
ORM : LoadRelated of a list in beego

### ISSUE THREAD

**Issue by SenaPutra** [astaxie/beego#3564]
I am wondering how the correct approach is to load related fields in beego. The doc explains it like this:

type User struct {
   Id    int
   Name  string
   Posts []*Post `orm:"reverse(many)"`
}

user := User{Id: 1}
err := dORM.Read(&user)
num, err := dORM.LoadRelated(&user, "Posts")
This makes sense as long as I only query one record. What is the correct way to fetch related fields when I query all users?

A possible solution would be like this:

var users []*User
o.QueryTable(new(User)).All(&users)
for _, user := range users {
    o.LoadRelated(controlCategory, "Posts")
}
However, this means I have to loop everytime over the complete list and make for every record a DB query to load all records.

Any suggestions? Thanks!

**Comment by shebinleo** [comment]
You can use relational queries function `RelatedSel` in the QuerySeter to fetch related fields.

`o.QueryTable(new(User)).RelatedSel("Posts").All(&users)`
