### ISSUE TITLE
panic: you are in dev mode. So please set gopath

### ISSUE THREAD

**Issue by yanserliu** [astaxie/beego#3566]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.11.1
├── GoVersion : go1.11
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Users\ucloud\go
├── GOROOT    : D:\go\
├── Compiler  : gc
└── Date      : Wednesday, 13 Mar 2019

2. What operating system and processor architecture are you using (`go env`)?
没有安装go程序，没有配置go环境变量

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
在app.conf中设置：
appname = usage-api
httpport = 12222
**runmode = dev**
autorender = false
copyrequestbody = true
EnableDocs = true
EnableAdmin = true
AdminPort = 12223

4、happen error
![image](https://user-images.githubusercontent.com/26165104/54251655-e9aced00-4582-11e9-8734-0fc2f587c0ad.png)

5、beego报错源码
![image](https://user-images.githubusercontent.com/26165104/54251758-355f9680-4583-11e9-9549-ddf96b8599e6.png)

6、为啥使用beego编译出来的二进制文件不能，使用dev模式不能在非go环境运行？
只能在安装go的机器，且配置了GOPATH的环境才能用dev模式？（因为我这个是在预发布的测试环境运行的，并不是真正的生产环境，PS：非开发环境）。不知道这个设计用意是什么？

**Comment by JessonChan** [comment]
需要在dev模式下生成commentsRouter_*.go的文件，然后再重新编译成二进制就可以发布了。
这个模式的目的在于自动的生成一个路径和方法绑定，并不在实时生成的。

**Comment by YanserLiu** [comment]
dev模式下生成commentsRouter_*.go？这个commentsRouter_*.go不是自动生成的吗 。是需要用命令生成commentsRouter_*.go文件是吗？请问是哪个命令呢，没有查到，前面一直都是编译的时候自动生成的

**Comment by YanserLiu** [comment]
> 需要在dev模式下生成commentsRouter_*.go的文件，然后再重新编译成二进制就可以发布了。
> 这个模式的目的在于自动的生成一个路径和方法绑定，并不在实时生成的。

dev模式下生成commentsRouter_.go？这个commentsRouter_.go不是自动生成的吗 。是需要用命令生成commentsRouter_*.go文件是吗？请问是哪个命令呢，没有查到，前面一直都是编译的时候自动生成的
