### ISSUE TITLE
行号打印的问题

### ISSUE THREAD

**Issue by fengjiansunren** [astaxie/beego#3568]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
  ```
  go version go1.9.7 darwin/amd64
  ```
2. What operating system and processor architecture are you using (`go env`)?
    ```
    GOHOSTARCH="amd64"
    GOHOSTOS="darwin"
    GOOS="darwin"
    ```
3. What did you do?
    ```
    when use log, print the filename and row number
    ```
4. What did you expect to see?
    ```
    2019/03/13 15:36:51.623 [I] [main.go:10]
    ````
5. What did you see instead?
    ```
    2019/03/13 16:13:00.684 [I] [asm_amd64.s:2337]
    ```

**Comment by JessonChan** [comment]
@fengjiansunren 使用 SetLogFuncCallDepth 函数可以设定打印的函数调用深度。
如果能解决，请关闭这个issue

**Comment by fengjiansunren** [comment]
@JessonChan

**Comment by nkjackzhang** [comment]
这些文件是go的库文件吧，和lib.so差不多，没什么必要知道它的行号，只关心go文件就行
