### ISSUE TITLE
请问beego可以解析json吗？

### ISSUE THREAD

**Issue by cappuccino5** [astaxie/beego#3569]
请问beego可以解析json吗？
不使用go原生的序列解析的方法 json.Unmarshal(c.Ctx.Input.RequestBody, &response)，请问beego有方法解析http的post请求json参数吗？谢谢有空的帮助解答

**Comment by JessonChan** [comment]
https://beego.me/docs/mvc/controller/params.md

**Comment by nkjackzhang** [comment]
> 
> 
> 请问beego可以解析json吗？
> 不使用go原生的序列解析的方法 json.Unmarshal(c.Ctx.Input.RequestBody, &response)，请问beego有方法解析http的post请求json参数吗？谢谢有空的帮助解答

看文档上面没有给出另外的方法，看来只有用这个了，不像java一样可以用jackson或者gson

**Comment by cappuccino5** [comment]
解析参数：

	req = struct {
		Score int `json:"score"`
	}{}

	if err := c.ParseForm(&req); err != nil {
		resp.Fail(response.FAIL_PARAM_PARSE)
		logrus.Error(response.FAIL_PARAM_PARSE)
		return
	}
	fmt.Println("1:", req)


http-post 请求参数：
{
	"score":1
}


问题：
使用例子无法解析
Controller 里解析：
func (this *MainController) Post() {
    u := user{}
    if err := this.ParseForm(&u); err != nil {
        //handle error
    }
}

**Comment by DennisMao** [comment]
@cappuccino5  https://beego.me/docs/mvc/controller/params.md#%E8%8E%B7%E5%8F%96-request-body-%E9%87%8C%E7%9A%84%E5%86%85%E5%AE%B9    表单内容和xml/json内容不同

**Comment by cappuccino5** [comment]
> @cappuccino5 https://beego.me/docs/mvc/controller/params.md#%E8%8E%B7%E5%8F%96-request-body-%E9%87%8C%E7%9A%84%E5%86%85%E5%AE%B9 表单内容和xml/json内容不同

**Comment by cappuccino5** [comment]
表示不用go官方的json.umrshal解析body，因为效率慢，就是问下Beego是否支持其它的解析body方法？

**Comment by DennisMao** [comment]
@cappuccino5  了解,可以尝试第三方开源的Json包
