### ISSUE TITLE
gopath一切换终端就不见了，每次都要source一下才出现

### ISSUE THREAD

**Issue by ZClee128** [astaxie/beego#3572]
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 
├── GoVersion : go1.10.1
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : 
├── GOROOT    : /usr/local/Cellar/go/1.10.1/libexec
├── Compiler  : gc
└── Date      : Thursday, 14 Mar 2019

**Comment by ZhangFengPlus** [comment]
你得把 path 添加到全局变量    如果使用了 zsh   应该加入在 .zshrc 文件里

 然后 source ~/.zshrc   成功

**Comment by nkjackzhang** [comment]
> 
> 
> 你得把 path 添加到全局变量 如果使用了 zsh 应该加入在 .zshrc 文件里
> 
> 然后 source ~/.zshrc 成功

你这个设置是和用户有关系吧，因为这个文件是在home目录下面的，不过估计@ZClee128 是在终端上手写了export，那样关闭终端就失效的，你这个方法倒是也能解决，另外真要全局设置的话，得写到/etc/profile里面，这个是对任何用户都生效的。

**Comment by DennisMao** [comment]
问题与框架无关,与bash环境有关。

**Comment by ZClee128** [comment]
> > 你得把路径添加到全局变量如果使用了zsh应该加入在.zshrc文件里
> > 然后source~ / .zshrc成功
> 
> 你这个设置是和用户有关系吧，因为这个文件是在家里目录下面的，不过估计@ ZClee128是在终端上手写了出口，那样关闭终端就失效的，你这个方法倒是也能解决，另外真要全局设置的话，得写到/ etc / profile的里面，这个是对任何用户都生效的。

我试过了，也是一样

**Comment by ZClee128** [comment]
> 你得把路径添加到全局变量如果使用了zsh应该加入在.zshrc文件里
> 
> 然后source~ / .zshrc成功

你这个怎么弄，可以详细一点吗？
