### ISSUE TITLE
How to Add proper dialog (yes/no) terminal in beego ?

### ISSUE THREAD

**Issue by suhardiyan** [astaxie/beego#3577]
**1. What version of Go and beego are you using (`bee version`)?**
├── Beego     : 1.11.1
├── GoVersion : go1.11.2
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : D:\go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Thursday, 21 Mar 2019

**2. What operating system and processor architecture are you using (`go env`)?**
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\rnd\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\rnd\AppData\Local\Temp\go-build759775450=/tmp/go-build -gno-record-gcc-switches

**3. What did you do?**
_If possible, provide a recipe for reproducing the error.
A complete runnable program is good._

I follow this tutor : https://gist.github.com/r0l1/3dcbb0c8f6cfe9c66ab8008f55f8f28b

**4. What did you expect to see?**

I want to add dialog on the terminal when I run beego

**5. What did you see instead?**

Cant type anyting in terminal

**Comment by IamCathal** [comment]
Based on your example this is a simple solution to your problem. 

```go
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
	_ "testapp/routers"

	"github.com/astaxie/beego"
)

func askForConfirmation(s string) bool {
	reader := bufio.NewReader(os.Stdin)

	for {
		fmt.Printf("%s [y/n]: ", s)

		response, err := reader.ReadString('\n')
		if err != nil {
			log.Fatal(err)
		}

		response = strings.ToLower(strings.TrimSpace(response))

		if response == "y" || response == "yes" {
			return true
		} else if response == "n" || response == "no" {
			return false
		}
	}
}

func main() {
	beego.BConfig.Log.AccessLogs = false
	beego.BConfig.Log.AccessLogsFormat = "JSON_FORMAT"

	beego.BConfig.Log.AccessLogs = true
	beego.SetLogger("file", `{"filename":"test.log"}`)
	beego.BeeLogger.DelLogger("console")

	c := askForConfirmation("Do you really want to start your application?")
	if c {
		beego.Run()
	}

}

```

However if this is not what you wanted and you instead wanted this confirmation to pop up after the server starts running for another purpose I don't believe this would be much different. If you wanted to perhaps manually accept requests to an API endpoint you could wrap the return statement of that endpoint in this confirmation. I don't believe this would be a good idea though and an alternative solution would most likely be better
