### ISSUE TITLE
模型过滤字段

### ISSUE THREAD

**Issue by wangle201210** [astaxie/beego#3585]
beego支持过滤模型中的字段不？
比如user表里面的password字段
user表里面有password字段
user结构体中也有
但是我需要返回时不返回password字段
或者password自动重置为空

**Comment by hantmac** [comment]
orm支持的，不需要的字段可以不用写

**Comment by maxshine** [comment]
> beego支持过滤模型中的字段不？
> 比如user表里面的password字段
> user表里面有password字段
> user结构体中也有
> 但是我需要返回时不返回password字段
> 或者password自动重置为空

是希望orm不从数据库读取数据填入field么？read时候可以指定哪些列需要读取。

**Comment by wangle201210** [comment]
> > beego支持过滤模型中的字段不？
> > 比如user表里面的password字段
> > user表里面有password字段
> > user结构体中也有
> > 但是我需要返回时不返回password字段
> > 或者password自动重置为空
> 
> 是希望orm不从数据库读取数据填入field么？read时候可以指定哪些列需要读取。

可以给个列子不?我对你说的理解是下面这样的
if err := orm.NewOrm().Read(reg, "Id","Name"); err != nil {
	return err
}
这样是不对的,field(即id,name)不是被填充的字段,而是查找是的条件
我要的效果是只返回id和name

**Comment by maxshine** [comment]
> > > beego支持过滤模型中的字段不？
> > > 比如user表里面的password字段
> > > user表里面有password字段
> > > user结构体中也有
> > > 但是我需要返回时不返回password字段
> > > 或者password自动重置为空
> > 
> > 
> > 是希望orm不从数据库读取数据填入field么？read时候可以指定哪些列需要读取。
> 
> 可以给个列子不?我对你说的理解是下面这样的
> if err := orm.NewOrm().Read(reg, "Id","Name"); err != nil {
> return err
> }
> 这样是不对的,field(即id,name)不是被填充的字段,而是查找是的条件
> 我要的效果是只返回id和name

应该是通过queryset调用db的ReadBatch方法. 如果读取简单可以直接用queryset的方法。

比如，读取唯一记录
`var user User
err := o.QueryTable("user").Filter("name", "slene").One(&user, "Id", "Name")`

读取满足条件的列表：
`var users []*User
num, err := o.QueryTable("user").Filter("name", "slene").All(&users, "Id", "Name")`

**Comment by wangle201210** [comment]
> > > > beego支持过滤模型中的字段不？
> > > > 比如user表里面的password字段
> > > > user表里面有password字段
> > > > user结构体中也有
> > > > 但是我需要返回时不返回password字段
> > > > 或者password自动重置为空
> > > 
> > > 
> > > 是希望orm不从数据库读取数据填入field么？read时候可以指定哪些列需要读取。
> > 
> > 
> > 可以给个列子不?我对你说的理解是下面这样的
> > if err := orm.NewOrm().Read(reg, "Id","Name"); err != nil {
> > return err
> > }
> > 这样是不对的,field(即id,name)不是被填充的字段,而是查找是的条件
> > 我要的效果是只返回id和name
> 
> 应该是通过queryset调用db的ReadBatch方法. 如果读取简单可以直接用queryset的方法。
> 
> 比如，读取唯一记录
> `var user User`
> `err := o.QueryTable("user").Filter("name", "slene").One(&user, "Id", "Name")`
> 
> 读取满足条件的列表：
> `var users []*User`
> `num, err := o.QueryTable("user").Filter("name", "slene").All(&users, "Id", "Name")`

感谢🙏
