### ISSUE TITLE
beego 配置文件解析 runmode 错误(参考官网教程设置)

### ISSUE THREAD

**Issue by sniperZj** [astaxie/beego#3590]
[beego]
app_name=Beego Web
runmode ="dev"

[dev]
httpport = 8080
[prod]
httpport = 8088
[test]
httpport = 8888

[lang]
types=en-US|zh-CN|ru-RU
names=English|简体中文|Russian

此时我选择的环境为dev 但是启动时运行的端口还是 prod 的
![image](https://user-images.githubusercontent.com/16409106/55314298-72d98480-549c-11e9-89a2-61858753ac36.png)

**Comment by YanserLiu** [comment]
将最上面的[beego]去掉，runmode是全局配置，放在[beego]下，读取不到，就会使用默认的prod
