### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by apollo-go** [astaxie/beego#3594]
log.go 中writeMsg函数的是否考虑支持空的传输，打印日志就可以支持不需要format情况的任意拼接
if len(v) > 0 {
	if msg == "" {
		msg = fmt.Sprint(v...)
	} else {
		msg = fmt.Sprintf(msg, v...)
	}
}

**Comment by Wusuluren** [comment]
感觉可以导出两种风格的打印函数，比如Error和Errorf，类似于fmt.Print和fmt.Printf这样。
