### ISSUE TITLE
请更新一下beego.me的配置文件设定文档

### ISSUE THREAD

**Issue by Colstuwjx** [astaxie/beego#3596]
见 https://beego.me/docs/mvc/controller/config.md#basic-config，

```
beego.AppConfigPath = "conf/app2.conf"
beego.AppConfigProvider = "ini"
```

[代码里](https://github.com/astaxie/beego/blob/master/config.go#L128) 已经改成私有变量，需要通过如下方式进行配置的加载：

```
beego.LoadAppConfig("ini", "conf/app2.conf")
```

烦请帮忙更新一下，以免其他用户受误导，谢谢！

**Comment by DennisMao** [comment]
@Colstuwjx  https://beego.me/docs/mvc/controller/config.md#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

**Comment by Colstuwjx** [comment]
Hi @DennisMao 

我的意思是文档里的设置方式已不可行，代码里是小写开头的私有变量了，所以这块文档需要维护一下。

**Comment by DennisMao** [comment]
@Colstuwjx  已确认,.英文版本没有同步更新。谢谢指出。
