### ISSUE TITLE
beego.Trance()方法报红是怎么回事

### ISSUE THREAD

**Issue by bbi5566** [astaxie/beego#3600]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11.2

2. What operating system and processor architecture are you using (`go env`)?
win10

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

beego.Trace("Loading language: " + lang)这个方法报红，找不到这个方法是怎么回事
4. What did you expect to see?

5. What did you see instead?

**Comment by JessonChan** [comment]
https://github.com/astaxie/beego/pull/3595

**Comment by zhangbo0724** [comment]
@JessonChan 为什么不考虑一下版本兼容！

**Comment by tuoHaiOutDoor** [comment]
> @JessonChan 为什么不考虑一下版本兼容！

master分支可以用，可以切换到master分支

**Comment by JessonChan** [comment]
@zhangbo0724 develop是开发分支
