### ISSUE TITLE
模板中使用配置

### ISSUE THREAD

**Issue by leslie5803** [astaxie/beego#3602]
文档中这句话:
>获取 AppConfig 的值. 使用方法 {{config configType configKey defaultValue}}. 可选的 configType 有 String, Bool, Int, Int64, Float, DIY

比如，要获取appname，我这样写{{config string appname ""}},在bee里看到报错

>function "string" not found。所有请问这里正确的用法是？

**Comment by JessonChan** [comment]
string => String

**Comment by leslie5803** [comment]
> string => String

一样,会报错`function "String" not found`

**Comment by leslie5803** [comment]
@JessonChan 一样,会报错function "String" not found

**Comment by leslie5803** [comment]
@JessonChan 解决了，得全部加上引号

```
{{config "String" "appname" ""}}
```
