### ISSUE TITLE
[task] can't clear "Errlist" in task

### ISSUE THREAD

**Issue by aldo-lzy** [astaxie/beego#3603]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.10.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/home/aldo/go/bin"
GOCACHE="/home/aldo/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aldo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/share/go"
GOTMPDIR=""
GOTOOLDIR="/usr/share/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build444569840=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
a. AddTask in code, return an error in taskfunc
b. Click "Run" in the task in page tasks
c. The ErrList will reach ErrLimit and can't clear err in ErrList

4. What did you expect to see?
ErrList can be clear and ErrLimit can be set

5. What did you see instead?
ErrList will be full and not be update

**Comment by flycash** [comment]
You can update ErrLimit by `t.ErrLimit = 1000`
