### ISSUE TITLE
orm的事务用不了

### ISSUE THREAD

**Issue by t2krew** [astaxie/beego#3610]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

> go: v1.11.2  
> beego. 1.11.1

2. What operating system and processor architecture are you using (`go env`)?

> centos 7.1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

**使用了事务**
```go
o := orm.NewOrm()
o.Using("xxx")

_ = o.Begin()

_, err = o.Raw("insert into aaa (vvv, kkk) values ('xxx', 'bbb')").Exec()
if err != nil {
   // log
}

o.Rollback()

return
```

4. What did you expect to see?

> **数据不会写入数据库** (data should not write to database)

5. What did you see instead?

> **数据写进数据库里了**(but the data  wrote to database actully)

**Comment by maxshine** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What version of Go and beego are you using (`bee version`)?
> 
> > go: v1.11.2
> > beego. 1.11.1
> 
> 1. What operating system and processor architecture are you using (`go env`)?
> 
> > centos 7.1
> 
> 1. What did you do?
>    If possible, provide a recipe for reproducing the error.
>    A complete runnable program is good.
> 
> **使用了事务**
> 
> ```go
> o := orm.NewOrm()
> o.Using("xxx")
> 
> _ = o.Begin()
> 
> _, err = o.Raw("insert into aaa (vvv, kkk) values ('xxx', 'bbb')").Exec()
> if err != nil {
>    // log
> }
> 
> o.Rollback()
> 
> return
> ```
> 
> 1. What did you expect to see?
> 
> > **数据不会写入数据库** (data should not write to database)
> 
> 1. What did you see instead?
> 
> > **数据写进数据库里了**(but the data  wrote to database actully)

Please use `o.Commit()` to persist the transaction change to database.

**Comment by t2krew** [comment]
搞了半天原来是数据库是myisam引擎 :-(
