### ISSUE TITLE
请求是websocket请求,在连接关闭后还是会render template

### ISSUE THREAD

**Issue by xjl662750** [astaxie/beego#3617]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.10.1
├── GoVersion : go1.11

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
例子https://github.com/beego/samples/tree/master/WebIM
如果请求是websocket连接,在连接关闭后还是会render template导致打印了错误

4. What did you expect to see?
如果是websocket连接就不用render template
在render template时判断是否websocket连接来决定是否render template
router.go:859中改成下面这样不知道会不会造成其他错误
	if r.Header.Get("Upgrade") != "websocket" {
			if !context.ResponseWriter.Started && context.Output.Status == 0 {
				if BConfig.WebConfig.AutoRender {
					if err := execController.Render(); err != nil {
						logs.Error(err)
					}
				}
			}

5. What did you see instead?
2019/04/18 23:44:22.299 [I] [chatroom.go:69]  New user: 2 ;WebSocket: true
2019/04/18 23:44:24.976 [E] [chatroom.go:94]  WebSocket closed: 2
2019/04/18 23:44:24.976 [C] [asm_amd64.s:522]  the request url is  /ws/join
2019/04/18 23:44:24.978 [C] [asm_amd64.s:522]  Handler crashed with error can't find templatefile in the path:views/websocketcontroller/join.tpl
2019/04/18 23:44:24.978 [C] [asm_amd64.s:522]  C:/Go/src/runtime/asm_amd64.s:522
2019/04/18 23:44:24.979 [C] [asm_amd64.s:522]  C:/Go/src/runtime/panic.go:513
2019/04/18 23:44:24.980 [C] [asm_amd64.s:522]  C:/Users/84082/go/src/github.com/astaxie/beego/template.go:73
2019/04/18 23:44:24.982 [C] [asm_amd64.s:522]  C:/Users/84082/go/src/github.com/astaxie/beego/controller.go:264
2019/04/18 23:44:24.982 [C] [asm_amd64.s:522]  C:/Users/84082/go/src/github.com/astaxie/beego/controller.go:215
2019/04/18 23:44:24.983 [C] [asm_amd64.s:522]  C:/Users/84082/go/src/github.com/astaxie/beego/controller.go:195
2019/04/18 23:44:24.989 [C] [asm_amd64.s:522]  C:/Users/84082/go/src/github.com/astaxie/beego/router.go:859
2019/04/18 23:44:24.990 [C] [asm_amd64.s:522]  C:/Go/src/net/http/server.go:2741
2019/04/18 23:44:24.991 [C] [asm_amd64.s:522]  C:/Go/src/net/http/server.go:1847
2019/04/18 23:44:24.992 [C] [asm_amd64.s:522]  C:/Go/src/runtime/asm_amd64.s:1333
2019/04/18 23:44:24.993 [server.go:2977]  [HTTP] http: response.WriteHeader on hijacked connection

**Comment by maxshine** [comment]
May you try to override `Render` method in your controller ?

**Comment by xjl662750** [comment]
Why not modify router.go?

**Comment by maxshine** [comment]
it does not make sense to touch the framework instead of handling the special case in your application
