### ISSUE TITLE
ParseForm 不支持默认值，初始化默认值非常麻烦啊

### ISSUE THREAD

**Issue by guanle** [astaxie/beego#3619]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by Wusuluren** [comment]
这样不可以吗？
```
type Obj struct {
	Name string `form:"name" default:"lili"`
}
```
