### ISSUE TITLE
No Model Definition for swagger for beego api 1.11

### ISSUE THREAD

**Issue by abhayaveer** [astaxie/beego#3620]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version: go1.11.4
beego 1.11

2. What operating system and processor architecture are you using (`go env`)?

Windows, amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
When integrated with swagger, no model definition is displayed. Empty braces is displayed
with error icon at the right bottom of the page.

4. What did you expect to see?
Model definition.

5. What did you see instead?
empty curly braces
![Capture](https://user-images.githubusercontent.com/6906038/56464023-b3466700-63a5-11e9-8ff9-778f2707409f.PNG)

**Comment by maxshine** [comment]
Bee utility depends on the @Param annotation to parse the struct type parameters as swagger `Models`. Generally it should be in the form `<package_name>.<struct type name>` in the annotation. please check it.

In my opinion, the **ERROR** link at the right bottom should not indicate any errors in the swagger generated document. you could use other 3rd party tool to double check your json / yaml file.

**Comment by abhayaveer** [comment]
Could you please give an example to def8ne params on model? i.e.@param annotation to parse the struct type parameters as swagger Models in the form <package_name>.<struct type name>
