### ISSUE TITLE
beego时区设置 posetgresql数据库

### ISSUE THREAD

**Issue by chuan-T** [astaxie/beego#3631]
使用beego的orm插入time.Time类型数据的时候总是比当前时间少8小时 插入类型打印出来是UTC时区，，posetgresql数据库，应该怎么操作，使得插入数据与本地时区一致

**Comment by jemygraw** [comment]
对于mysql来讲，可以使用 `charset` 和 `loc` 两个参数，分别指定字符集和时区。
```
datasource := "root:root@(localhost:3306)/test?charset=utf8mb4&loc=Asia%2FShanghai"
```
postgrel 自己看下对应的两个参数是什么，需要指定一下。
