### ISSUE TITLE
undefined: beego.Emergency

### ISSUE THREAD

**Issue by CWaiLeung** [astaxie/beego#3634]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.11.2
├── GoVersion : go1.12.1

2. What operating system and processor architecture are you using (`go env`)?
在使用beego.Emergency("this is emergency")
beego.Alert("this is alert")
beego.Critical("this is critical")
beego.Error("this is error")
beego.Warning("this is warning")
beego.Notice("this is notice")
beego.Informational("this is informational")
beego.Debug("this is debug")
均提示undefined: beego.*
请问什么原因？
怎样解决？

**Comment by JessonChan** [comment]
这个问题主要还是代码没有更新。你看下当前版本，确认是否为1.11.2

package main

import (
	"fmt"

	"github.com/astaxie/beego"
)

func main() {
	fmt.Println(beego.VERSION)
}

**Comment by CWaiLeung** [comment]
C:\Users\Administrator\go\src\testBlog>go run test.go
1.11.2
