### ISSUE TITLE
ORM Query has no data

### ISSUE THREAD

**Issue by ChangWencai** [astaxie/beego#3636]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.11.1
├── GoVersion : go1.12.1
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 2
├── GOPATH    : /home/parallels/GOPATH
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Sunday, 5 May 2019
2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/home/parallels/GOPATH/bin"
GOCACHE="/home/parallels/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/parallels/GOPATH"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/parallels/GOAPTH/src/gitee.com/magus_iot/opapi/linux/x64"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build490037518=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
in database data
![image](https://user-images.githubusercontent.com/15669144/57191655-9a6bb300-6f5a-11e9-9231-7884dcd60300.png)
**used by beego orm**
```go
        var maps []orm.Params
	orm.Debug=true
	num,err :=orm.NewOrm().Raw(`SELECT count(id) as count FROM driver_info where  isHistory=0  and name like '%dasserver%' and type like '%abc%'`).Values(&maps)
	if err==nil && num>0 {
		beego.Debug(maps[0]["count"])
	}
```
debug info 
`
[ORM]2019/05/05 17:27:59  -[Queries/default] - [  OK /    db.Query /     3.3ms] - [SELECT count(id) as count FROM driver_info where  isHistory=0  and name like '%dasserver%' and type like '%abc%']
2019/05/05 17:27:59.869 [D] [driver.go:554]  count: 0 
`
4. What did you expect to see?
**ORM by xorm**
```go
	engine,err:=xorm.NewEngine("mysql","root:root@tcp(127.0.0.1:3306)/iotdriver?charset=utf8")
	defer engine.Close()
	engine.ShowSQL(true)
	has, err := engine.QueryString(`SELECT count(id) as count FROM driver_info where  isHistory=0  and name like '%dasserver%' and type like '%abc%'`)
	beego.Debug("count:",has[0]["count"])
```
debug info 
`
[xorm] [info]  2019/05/05 17:27:59.869330 [SQL] SELECT count(id) as count FROM driver_info where  isHistory=0  and name like '%dasserver%' and type like '%abc%'
2019/05/05 17:27:59.879 [D] [driver.go:567]  count: 2 
`
5. What did you see instead?
I can't get the right data，why？same SQL string
**in beego orm
2019/05/05 17:27:59.869 [D] [driver.go:554]  count: 0 
in xorm
2019/05/05 17:27:59.879 [D] [driver.go:567]  count: 2**

**Comment by jemygraw** [comment]
```
1.11.1
[ORM]2019/05/09 16:32:03  -[Queries/default] - [  OK /    db.Query /     0.2ms] - [SELECT count(id) as count FROM driver_info where  isHistory=0  and name like '%dasserver%' and type like '%abc%']
2019/05/09 16:32:03.979 [D] [main.go:22]  2
```
Cannot recreate the error. Maybe you should check the data in your database first.
