### ISSUE TITLE
orm修改或删除表字段问题

### ISSUE THREAD

**Issue by flyingdown** [astaxie/beego#3637]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11.2

2. What operating system and processor architecture are you using (`go env`)?
windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
type User struct {
	Id       int
	Username string
	Password string
        NickName string
}

4. What did you expect to see?
创建表时添加了nickname字段，将该字段改名后，orm会自动增加一个新字段，而不会删除原字段

5. What did you see instead?
查看文档后没找到相应处理方法

**Comment by jemygraw** [comment]
这个本来就不会去删除字段，需要自己删除。

**Comment by flyingdown** [comment]
好吧，可能用其他的orm习惯了，beego的orm不太了解
