### ISSUE TITLE
beego 如何将appname 添加到router中

### ISSUE THREAD

**Issue by pcaddos** [astaxie/beego#3638]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
详细描述下需求,加入的意思是指加前缀?

**Comment by pcaddos** [comment]
是的
