### ISSUE TITLE
How to create router /api/:id and /api 

### ISSUE THREAD

**Issue by tsoil** [astaxie/beego#3641]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by jemygraw** [comment]
It is supported.

```
// routers
postController := &controllers.PostController{}
beego.Router("/post/:id", postController, "get:Get")
beego.Router("/post", postController, "get:List")
```
---

```
// controllers
package controllers

import "github.com/astaxie/beego"

type PostController struct {
	beego.Controller
}

func (p *PostController) Get() {
	p.Data["json"] = struct {
		Value string
	}{
		Value: "get",
	}
	p.ServeJSON()
}

func (p *PostController) List() {
	p.Data["json"] = struct {
		Value string
	}{
		Value: "list",
	}
	p.ServeJSON()
}
```

**Comment by zhouxnsz** [comment]
如果是注解路由，直接这样写就可以了：
/api/?:id
这样就可以匹配/api/ 和 /api/123 ，不过model里要自己判断是否有传入id
