### ISSUE TITLE
an exception occurred when using httplib to request a third-party api address :Handler crashed with error runtime error: index out of range

### ISSUE THREAD

**Issue by simplephp** [astaxie/beego#3643]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 1.11.2 

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build856671597=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

package controllers

import (
	"fmt"
	//"sync"
	"encoding/json"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/httplib"
)

type AirController struct {
	beego.Controller
}

// 定义 Air Struct
type Resultstruct struct {
	Location Location `json:"location"`
	Now Now`json:"now"`
}

// 定义 Location Struct
type Location struct {

	Id string						`json:"id"`
	Name string						`json:"name"`
	Country string					`json:"country"`
	Path string						`json:"path"`
	Timezone string					`json:"timezone"`
	Timezone_offset string			`json:"timezone_offset"`	
}

// 定义 Now Struct
type Now struct {
	
	Code string						`json:"code"`
	Text string						`json:"text"`
	Temperature string				`json:"temperature"`
	Humidity string					`json:"humidity"`
	Feels_like string				`json:"feels_like"`
	Pressure string					`json:"pressure"`
	Visibility string				`json:"visibility"`
	Wind_direction_degree string	`json:"wind_direction_degree"`
	Wind_speed string				`json:"wind_speed"`
	Wind_scale string				`json:"wind_scale"`
	Wind_direction string			`json:"wind_direction"`
	Precip string					`json:"precip"`

}

type XinZhiAirstruct struct {
	Results []struct {
		Location Location `json:"location"`
		Now Now`json:"now"`
		LastUpdate string `json:"last_update"`
	} `json:"results"`
}

type Responsestruct struct {
    Code int16   		`json:"code"`
	Info string 		`json:"info"`
	Data Resultstruct 	`json:"data"`
}

func (c *AirController) Get() {
	
	
	req := httplib.Get("https://api.seniverse.com/v3/weather/now.json?key=XLDJSEN3X&location=shenzhen")
	
	jsonStr, netErr := req.String()
	LocalAirStruct := Resultstruct{}
	
	if netErr != nil {
		c.Data["json"] = &Responsestruct{0, "请求百度失败1", LocalAirStruct}
		c.ServeJSON()
		return
	}

	
	var XzAirstruct XinZhiAirstruct

	err := json.Unmarshal([]byte(jsonStr), &XzAirstruct)

	if err != nil {
		c.Data["json"] = &Responsestruct{0, "请求百度失败2", LocalAirStruct}
		c.ServeJSON()
		return
	}

	LocalAirStruct.Location = XzAirstruct.Results[0].Location
	LocalAirStruct.Now = XzAirstruct.Results[0].Now

    c.Data["json"] = &Responsestruct{0, "请求成功", LocalAirStruct}
	c.ServeJSON()
}

4. What did you expect to see?
2019/05/09 15:12:04.002 [server.go:3010]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)
2019/05/09 15:12:04.600 [C] [panic.go:522]  the request url is  /air/now
2019/05/09 15:12:04.600 [C] [panic.go:522]  Handler crashed with error runtime error: index out of range
2019/05/09 15:12:04.600 [C] [panic.go:522]  /usr/local/go/src/runtime/panic.go:522
2019/05/09 15:12:04.600 [C] [panic.go:522]  /usr/local/go/src/runtime/panic.go:44
2019/05/09 15:12:04.600 [C] [panic.go:522]  /home/gopath/src/weather/controllers/air.go:90
2019/05/09 15:12:04.600 [C] [panic.go:522]  /home/gopath/src/github.com/astaxie/beego/router.go:833
2019/05/09 15:12:04.600 [C] [panic.go:522]  /usr/local/go/src/net/http/server.go:2774
2019/05/09 15:12:04.601 [C] [panic.go:522]  /usr/local/go/src/net/http/server.go:1878
2019/05/09 15:12:04.601 [C] [panic.go:522]  /usr/local/go/src/runtime/asm_amd64.s:1337
2019/05/09 15:12:04.601 [server.go:3010]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)

5. What did you see instead?
2019/05/09 15:12:04.002 [server.go:3010]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)
2019/05/09 15:12:04.600 [C] [panic.go:522]  the request url is  /air/now
2019/05/09 15:12:04.600 [C] [panic.go:522]  Handler crashed with error runtime error: index out of range
2019/05/09 15:12:04.600 [C] [panic.go:522]  /usr/local/go/src/runtime/panic.go:522
2019/05/09 15:12:04.600 [C] [panic.go:522]  /usr/local/go/src/runtime/panic.go:44
2019/05/09 15:12:04.600 [C] [panic.go:522]  /home/gopath/src/weather/controllers/air.go:90
2019/05/09 15:12:04.600 [C] [panic.go:522]  /home/gopath/src/github.com/astaxie/beego/router.go:833
2019/05/09 15:12:04.600 [C] [panic.go:522]  /usr/local/go/src/net/http/server.go:2774
2019/05/09 15:12:04.601 [C] [panic.go:522]  /usr/local/go/src/net/http/server.go:1878
2019/05/09 15:12:04.601 [C] [panic.go:522]  /usr/local/go/src/runtime/asm_amd64.s:1337
2019/05/09 15:12:04.601 [server.go:3010]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)

**Comment by michael12610** [comment]
[server.go:3010] [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)...

hi,what is the reason caused this problem...how to solve it..
