### ISSUE TITLE
Why can't run migration with bee tool if set a database config file?

### ISSUE THREAD

**Issue by 02040402** [astaxie/beego#3644]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10.0

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/seikyo.cho/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dc/xtcnc9717_5bw69135mvj6y5nlq9kn/T/go-build765943856=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
bee generate scaffold [scaffoldname] [-fields=""] [-driver=mysql] [-conn="root:@tcp(127.0.0.1:3306)/test"]
bee migrate [-driver=mysql] [-conn="root:@tcp(127.0.0.1:3306)/test"]
```

4. What did you expect to see?
Run `bee generate scaffold [scaffoldname] [-fields=""]` or `bee migrate` only without use db connection strings every time.

5. What did you see instead?
It works. But want the feature below.

---

# Rails

`config/database.yml`

# Django

Set database connection in `settings.py`, then can run migration.

Can't beego realize these features?

**Comment by dre2004** [comment]
I am only new to Beego myself and coming from using Django I was hoping to see something similar here as well but as I've also learn't this is not the case. 

In terms of getting that functionality it not actually in this project that this question should be in. Beego (github.com/astaxie/beego) is a different repository to Bee (github.com/beego/bee) I think it is probably more appropriate to post the question there as what you're describing is actually a behavior of the "bee" cli tool and not the Beego framework as a whole.

I had a look around there and found a similar issue, **https://github.com/beego/bee/issues/424** but there doesn't appear to be a fix / work around as yet.

**Comment by 02040402** [comment]
@dre2004 

Thank you for your comment. From your link I found it seems `Beefile` or `bee.json` can do better: https://github.com/beego/bee/issues/424#issuecomment-299853388
