### ISSUE TITLE
使用go mod 时，自带swagger 初始化提示' does not exist in the GOPATH or vendor path

### ISSUE THREAD

**Issue by BNDYH** [astaxie/beego#3647]

**Comment by jeremywu0127** [comment]
我govendor换成go mod后，出现同样的问题，老哥咋解决的呢？我临时在$GOPATH/src下做了了软连接，才跑起来的

**Comment by ppmsgit** [comment]
> 我govendor换成go mod后，出现同样的问题，老哥咋解决的呢？我临时在$GOPATH/src下做了了软连接，才跑起来的

@astaxie 谢大，这个解决了吗😝
