### ISSUE TITLE
I can't change the default template delimiters

### ISSUE THREAD

**Issue by wfelipe99** [astaxie/beego#3648]
1. What version of Go and beego are you using (`bee version`)?
Go: go1.12.4
Beego: 1.11.2

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64

3. What did you do?
I'm using Beego + VueJS2 and I need to change golang's default delimiters to not conflict with VueJS. I already tried to set it in 'app.conf':

I tried this: 
beego.BConfig.WebConfig.TemplateLeft = "[["
beego.BConfig.WebConfig.TemplateRight = "]]"

This:
beego.TemplateLeft="[["
beego.TemplateRight="]]"

And this:

templateleft=[[
templateright=]]

None of them worked.

4. What did you expect to see?
I would expect beego.me

5. What did you see instead?
I see [[.Website]]

It's like the delimiters is not being changed, because when I set "[[" and "]]" in the app.conf file, when I use {{.Website}} I see "beego.me".

**Comment by jerry94test** [comment]
本身就是协程 你想要强制队列处理吗 自己封装个就可以呃了
