### ISSUE TITLE
使用go mod安装beego后没有bee命令

### ISSUE THREAD

**Issue by vperson** [astaxie/beego#3659]
使用 go mod 安装的beego，包已经可以成功倒入了，但是没有bee这个命令，在$GOPATH下没有找到
![image](https://user-images.githubusercontent.com/30188622/57978805-9786bd00-7a46-11e9-8952-1cc159b0d16c.png)

使用```go get github.com/astaxie/beego```安装提示找不到模块
![image](https://user-images.githubusercontent.com/30188622/57978810-b71de580-7a46-11e9-8e23-506d1974b22c.png)

**Comment by vperson** [comment]
GOPATH已经加入到了PATH中
![image](https://user-images.githubusercontent.com/30188622/57978859-68bd1680-7a47-11e9-9586-dc8efe8a03de.png)
就是没找到bee命令

**Comment by JessonChan** [comment]
https://github.com/beego/bee

**Comment by ZhanGuanguan** [comment]
import 里面加上 “github.com/beego/bee”
