### ISSUE TITLE
关联关系，反向查询只能一条一条的来吗？

### ISSUE THREAD

**Issue by marunrun** [astaxie/beego#3661]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.11.2

2. What operating system and processor architecture are you using (`go env`)?
windows7 amd64

3. What did you do?
```
type Category struct {
	Id               int       `orm:"column(id);auto" json:"id"`
	Pid              int       `orm:"column(pid)" json:"pid"`
	Spid             int       `orm:"column(spid)" json:"spid"`
	Level            int       `orm:"column(level)" json:"level"`
	Name             string    `orm:"column(name);size(64)" json:"name"`
	GoodsTax         *GoodsTax `orm:"reverse(one)"`
}
```
```
type GoodsTax struct {
	Id         uint      `orm:"column(id);auto" json:"id"`
	Cate     *Category `orm:"column(cate_id);rel(one)" json:"cate_id"`
}
```
```
ml = []Category{}

if _, err = qs.OrderBy(orders...).All(&ml, fields...); err != nil {
	return nil, err
}
```

4. What did you expect to see?

`o.LoadRelated(&ml,"GoodsTax") // 我想获取所有的category相关联的goods_tax 但失败了`

5. What did you see instead?

我使用for range 循环 然后`LoadRelated`也可以获取到，但我觉得很麻烦，是否有更好的解决方案？

**Comment by yujinxiang** [comment]
反向关联确实只能一个个的来，而且这个LoadRelated这个函数坑特别大，你LoadRelated 这个表，如果你还有其他关系的话，查询语句也把其他无关的表也查询，不知道是不是我配置错了

**Comment by C0deFxxker** [comment]
同问

**Comment by HC-miss** [comment]
请问你现在解决了这个问题吗

**Comment by run6** [comment]
> 请问你现在解决了这个问题吗

hh 并没有，现在也比较少用go了
