### ISSUE TITLE
如何在model中设置非主键字段的自增

### ISSUE THREAD

**Issue by yah0130** [astaxie/beego#3665]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.10

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yanha\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\yanha\go
set GOPROXY=https://goproxy.io
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\yanha\go\src\bbs_api\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\yanha\AppData\Local\Temp\go-build154709982=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
我在非主键的字段上加了orm:"auto"

4. What did you expect to see?
数据库表创建后字段自增

5. What did you see instead?
one model must have one pk field only

**Comment by jianzhiyao** [comment]
mysql5.7.16 不支持非主键自增
```
CREATE TABLE `test`.`aaa`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `num` int NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `aa`(`num`)
)
> 1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key
> 时间: 0s
```

而且自增应该属于数据库层面或者应用层面维护的情况，框架级别不应该做太多的干涉。
此issue已经太久，暂时关闭。
有后续疑问可以继续提issue与我们沟通，感谢支持！
