### ISSUE TITLE
有没有计划支持日志动态修改级别

### ISSUE THREAD

**Issue by walleliu1016** [astaxie/beego#3666]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
latest

2. What operating system and processor architecture are you using (`go env`)?
llinux/arm64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
日志级别动态修改，有时候在生产要排查异常，需要开启debug日志，但是不重启进程

5. What did you see instead?

**Comment by JessonChan** [comment]
本身就是支持的在SetLevel这个函数。可以写入某个配置文件，定时刷新就可以了，不需要框架支持。

**Comment by flycash** [comment]
可以考虑在admin里面提供一个修改日志级别的方法。不过这是一个危险操作，授权和审计方面会依赖于用户自觉，所以我不太想暴露。
