### ISSUE TITLE
QueryRow 和 QueryRows reflect的结果不一致

### ISSUE THREAD

**Issue by aixj1984** [astaxie/beego#3677]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11.2

2. What operating system and processor architecture are you using (`go env`)?
1.12.5

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

同一个自定义的SQL语句，通过QueryRow，只能映射出部分字段，但是通过QueryRows，则可以反射出所有的结果字段。

我的结构体定义：

type Account struct {
	Id         int
	Sex        int
	City       string    `orm:"size(50);"`
	Province   string    `orm:"size(50);"`
	Country    string    `orm:"size(50);"`
}

type AccountDetail struct {
	Account
	UserType     int8
	UserCity     string
	UserProvince string
	UserCountry  string
}

我想查的结果是AccountDetail  结构体的数据

4. What did you expect to see?

5. What did you see instead?

**Comment by jemygraw** [comment]
```
type AccountDetail struct {
Account *Account 
UserType int8
UserCity string
UserProvince string
UserCountry string
}
```
try to use a pointer to reference a struct
