### ISSUE TITLE
Orm QueryTable One not return orm.ErrMultiRows error

### ISSUE THREAD

**Issue by GeorgeXc** [astaxie/beego#3680]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.12.5
beego commitID:206a7ed1fcb754f4294689dd514797c044439e1b

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/x/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/x/.gvm/pkgsets/go1.12.5/global"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/Users/x/.gvm/gos/go1.12.5"
GOTMPDIR=""
GOTOOLDIR="/Users/x/.gvm/gos/go1.12.5/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9t/43fwfvlx3hq4zjb1mzd_p0w40000gn/T/go-build338602887=/tmp/go-build -gno-record-gcc-switches -fno-common"
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

With Beego Orm, I inserted two item which has the same value on field `same`.
then I use `o.QueryTable("infos").Filter("name", "name10").One(&inf)` to try read only one row from table `infos`. I expected got an error with value orm.ErrMultiRows 。

5. What did you see instead?
But got nil error

My code is listed below
`package main

import (
	"log"

	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

func init() {
	log.SetFlags(log.Lshortfile | log.Ldate)
}

type Base struct {
	Name string
	Age  int
	Sex  int
}
type Infos struct {
	Id int
	Base
}

func Log(format string, args ...interface{}) {
	log.Printf(format+"\n", args...)
}
func main() {
	orm.RegisterDriver("mysql", orm.DRMySQL)
	orm.RegisterDataBase("default", "mysql", "test:testpassword@tcp(127.0.0.1:3306)/testdb?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai")
	orm.RegisterModel(new(Infos))
	err := orm.RunSyncdb("default", true, true)
	if err != nil {
		Log("run syncdb error:%+v", err)
		return
	}
	o := orm.NewOrm()
	orm.Debug = true
	o.Using("default")
	id, err := o.Insert(&Infos{
		Base: Base{Name: "nnnnnnname"},
	})
	if err != nil {
		Log("inser error:%+v", err)
	}
	o.Update(&Infos{
		Id:   int(id),
		Base: Base{Name: "testname"},
	})

	i, _ := o.Insert(&Infos{
		Base: Base{Name: "name2"},
	})
	u := &Infos{Id: int(i)}
	o.Read(u)
	Log("get u:%+v", u)
	o.InsertMulti(3, []*Infos{&Infos{Base: Base{Name: "name4"}}, &Infos{Base: Base{Name: "name5"}}, &Infos{Base: Base{Name: "name6"}}, &Infos{Base: Base{Name: "name7"}}, &Infos{Base: Base{Name: "name8"}}, &Infos{Base: Base{Name: "name9"}}, &Infos{Base: Base{Name: "name10"}}, &Infos{Base: Base{Name: "name10"}}, &Infos{Base: Base{Name: "name12"}}})
	w := &Infos{Base: Base{Name: "name10"}}
	err = o.Read(w, "Name")
	if err != nil {
		Log("read meet error:%+v", err)
		return
	}
	Log("u is :%+v", w)
	var res []*Infos
	o.QueryTable(&Infos{}).Filter("name", "name10").All(&res)
	Log("all:%#+v", res)
	var inf Infos
	err = o.QueryTable("infos").Filter("name", "name10").One(&inf)
	if err != nil {
		Log("query one meet error:%+v", err)
	}
	Log("%+v", inf)

}
`

**Comment by jemygraw** [comment]
```
// query one row data and map to containers.
// cols means the columns when querying.
func (o *querySet) One(container interface{}, cols ...string) error {
	o.limit = 1
	num, err := o.orm.alias.DbBaser.ReadBatch(o.orm.db, o, o.mi, o.cond, container, o.orm.alias.TZ, cols)
	if err != nil {
		return err
	}
	if num == 0 {
		return ErrNoRows
	}

	fmt.Println("num:",num)
	if num > 1 {
		return ErrMultiRows
	}
	return nil
}
```

because now the api have a limit set to 1 and the result will only return at most 1 row.

https://github.com/astaxie/beego/blob/develop/orm/orm_queryset.go#L219

**Comment by GeorgeXc** [comment]
> ```
> // query one row data and map to containers.
> // cols means the columns when querying.
> func (o *querySet) One(container interface{}, cols ...string) error {
> 	o.limit = 1
> 	num, err := o.orm.alias.DbBaser.ReadBatch(o.orm.db, o, o.mi, o.cond, container, o.orm.alias.TZ, cols)
> 	if err != nil {
> 		return err
> 	}
> 	if num == 0 {
> 		return ErrNoRows
> 	}
> 
> 	if num > 1 {
> 		return ErrMultiRows
> 	}
> 	return nil
> }
> ```
> 
> because now the api have a limit set to 1 and the result will only return at most 1 row.
> 
> https://github.com/astaxie/beego/blob/develop/orm/orm_queryset.go#L219
我觉得那个函数One应该表达一种只能读取到一条符合条件的记录的意思，多了或者少了 都应该报错，类似QueryRow函数一样。
