### ISSUE TITLE
beego路由如何强制以 / 结尾？或者beego路由怎么设置url后缀？

### ISSUE THREAD

**Issue by tianakong** [astaxie/beego#3682]
如题
beego.Router("/admin/", &admin.UserController{})
注册路由后，xx.com/admin 和 xx.com/admin/ 都可以访问到，如何强制只能使用xx.com/admin/访问呢？

**Comment by ssddffgg7455** [comment]
你做一个/admin的路由呢

**Comment by flycash** [comment]
按照现在业界的规范，在你设置了这种路由以后，两种都访问得到，是比较通行的做法。而且，/admin和/admin/如果http method没有分别的话，的确不需要区别开来。
