### ISSUE TITLE
bee 打包不能直接打包 swagger

### ISSUE THREAD

**Issue by wz2cool** [astaxie/beego#3684]
我们能使用 bee run -gendoc=true -downdoc=true 去生成swagger 
但是我们在 bee pack 命令里面找到类似的参数， 我们想打包的时候也打包swagger，请问如何处理啊

**Comment by wz2cool** [comment]
比如我们有qa 环境 想直接打包可以么

**Comment by lihongchen** [comment]
pack 打包的内容里面有swagger 的内容
