### ISSUE TITLE
go get github.com/beego/bee 遇到问题 

### ISSUE THREAD

**Issue by CandidXD** [astaxie/beego#3690]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN="/Users/yaozekai/go/bin"
GOCACHE="/Users/yaozekai/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yaozekai/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2g/wn8p41gd29v247_nkhtlx40r0000gn/T/go-build211892238=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
通过 go get github.com/beego/bee 安装bee工具
A complete runnable program is good.
![image](https://user-images.githubusercontent.com/30494161/59618602-24fb2100-915b-11e9-8772-c5916531a329.png)

试了很多次都是这样，使用bee的指令都是类似图片中这样的，我不确定是不是系统问题，我装了最新的macOS 10.15
4. What did you expect to see?
希望bee指令能够正常使用

5. What did you see instead?

**Comment by wonderaa** [comment]
go version go1.12.6 
安装bee. 提示
ld: warning: building for macOS, but linking in object file (/var/folders/yj/qtdk78fn63vbw2ss0l5vnml40000gn/T/go-link-709498484/go.o) built for

**Comment by DennisMao** [comment]
@CandidXD 请在https://github.com/beego/bee/issues 重新提一下.Thanks.
