### ISSUE TITLE
InsertOrUpdate返回结果中第一个值（int64）总是为0，实际上有更新数据库。

### ISSUE THREAD

**Issue by zskylark** [astaxie/beego#3691]
beego v1.11.1。
mysql 5.6.37
调用Ormer.InsertOrUpdate时，当数据库已经有该记录，执行update更新操作并按期望进行了更新，但InsertOrUpdate方法返回结果中第一个值（int64）总是为0。

**Comment by jemygraw** [comment]
这个问题的主要原因在于这里 https://github.com/astaxie/beego/blob/develop/orm/db_mysql.go#L161

```
if isMulti || !d.ins.HasReturningID(mi, &query) {
		res, err := q.Exec(query, values...)
		if err == nil {
			if isMulti {
				return res.RowsAffected()
			}
			return res.LastInsertId()
		}
		return 0, err
	}
```

这个id返回的其实是影响的行数或者是上一次插入的id，根据数据库支持的不同，取值也不同。

**Comment by jemygraw** [comment]
为了能让这个值有返回值，对于单个对象，必须满足主键ID是AUTO_INCREMENT。
