### ISSUE TITLE
go version go1.12.6  Mac 10.14安装bee. 提示 ld: warning: building for macOS, but linking in object file (/var/folders/yj/qtdk78fn63vbw2ss0l5vnml40000gn/T/go-link-709498484/go.o) built for

### ISSUE THREAD

**Issue by wonderaa** [astaxie/beego#3692]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go version go1.12.6
2. What operating system and processor architecture are you using (`go env`)?

安装bee. 提示
ld: warning: building for macOS, but linking in object file (/var/folders/yj/qtdk78fn63vbw2ss0l5vnml40000gn/T/go-link-709498484/go.o) built for
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
@wonderaa   请在https://github.com/beego/bee/issues 重新提一下.Thanks.
