### ISSUE TITLE
急急急！联表查询struct设置外键，orm忽略本表外键，在入库时却忽略了本表外键，orm不设置忽略查询又报字段重复

### ISSUE THREAD

**Issue by zjie-zhang** [astaxie/beego#3695]
Beego     : 1.11.2
 GoVersion : go1.12.5

急急急！联表查询struct设置外键，orm忽略本表外键，在入库时却忽略了本表外键，orm不设置忽略查询又报字段重复

![image](https://user-images.githubusercontent.com/10172957/59811337-01430100-933c-11e9-94ba-80632f800106.png)

求解，多谢

**Comment by jemygraw** [comment]
最根本原因就是你把 form，orm，json都混在一个结构体里面，形成了 View 和 Model 层的紧耦合，你分开就好了。
