### ISSUE TITLE
关于beego的toolbox

### ISSUE THREAD

**Issue by Alberthchang** [astaxie/beego#3696]
目前正在使用beego做开发，感觉beego的计划任务这块不如gf的gtimer完善。目前我的主要需求是给定大概几十条定时任务，有的是每秒执行一次，有的是每分钟，这个参数是从数据库读出来的，然后需要执行并获取执行结果写入数据库，需要随时保证能定时任务随时开始和停止，还有定时任务的随时添加和删除，这块感觉beego的toolsbox定时就不如gf的gtimer，目前我们的解决方案是在beego api里面混用了gf的gtimer，但是感觉问题很多，请问后续是否有在开发定时任务这块的想法？

**Comment by DennisMao** [comment]
@Alberthchang  官方toolbox会更考虑在通用场景下的应用。如果不满足业务需求 可以考虑引入其他的第三方cron来实现。

**Comment by Alberthchang** [comment]
@DennisMao 好的，明白了，那我就尝试自己引入cron去解决了
