### ISSUE TITLE
bee new hello 创建项目失败。panic: open /Users/deboer/go/src/hello/static/js/reload.min.js: no such file or directory

### ISSUE THREAD

**Issue by wdbkti** [astaxie/beego#3697]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.11.2
├── GoVersion : go1.12.6
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/deboer/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 21 Jun 2019

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/deboer/go/bin"
GOCACHE="/Users/deboer/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/deboer/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yc/lqqwn6bx3z9gjx4b0lcw0td00000gn/T/go-build857229640=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2019/06/21 21:08:48 INFO     ▶ 0001 Creating application...
	create	 /Users/deboer/go/src/hello/
	create	 /Users/deboer/go/src/hello/conf/
	create	 /Users/deboer/go/src/hello/controllers/
	create	 /Users/deboer/go/src/hello/models/
	create	 /Users/deboer/go/src/hello/routers/
	create	 /Users/deboer/go/src/hello/tests/
	create	 /Users/deboer/go/src/hello/static/
panic: open /Users/deboer/go/src/hello/static/js/reload.min.js: no such file or directory

goroutine 1 [running]:
github.com/beego/bee/utils.MustCheck(...)
	/Users/deboer/go/src/github.com/beego/bee/utils/utils.go:239
github.com/beego/bee/utils.WriteToFile(0xc0001be280, 0x32, 0x46e9a29, 0x160)
	/Users/deboer/go/src/github.com/beego/bee/utils/utils.go:246 +0x140
github.com/beego/bee/cmd/commands/new.CreateApp(0x4bfbee0, 0xc00009c1a0, 0x1, 0x1, 0x1)
	/Users/deboer/go/src/github.com/beego/bee/cmd/commands/new/new.go:287 +0x11e9
main.main()
	/Users/deboer/go/src/github.com/beego/bee/main.go:75 +0x2d4

4. What did you expect to see?

5. What did you see instead?

**Comment by wdbkti** [comment]
已解决 权限问题。最开始没注意权限问题

**Comment by bamianhu** [comment]
> 已解决 权限问题。最开始没注意权限问题

请问你是怎么解决的，在指令前面加了sudo?

**Comment by bamianhu** [comment]
我使用sudo visudo 指令，修改了 Defaults env_reset，将其改为Defaults !env_reset ，意思是修改为不重置环境 ，然后就可以正常使用sudo bee new hello
