### ISSUE TITLE
controller seems stateless, does Beego has a plan to support stateful controller?

### ISSUE THREAD

**Issue by 00arthur00** [astaxie/beego#3704]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.11.2
2. What operating system and processor architecture are you using (`go env`)?
go version go1.12.5 linux/amd64
3. What did you do?
add a counter in controller, but the counter is always be 1.
``` golang
type MainController struct {
	beego.Controller
	counter int
}

func (c *MainController) Get() {
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	c.counter++
	log.Println(c.counter)
	c.TplName = "index.tpl"
}
```

4. What did you expect to see?
the counter can increase every request

5. What did you see instead?
it's always  1

**Comment by whileW** [comment]
你应该在其他地方定义他，而不是在这

**Comment by 00arthur00** [comment]
一个全局对象吗?

> 你应该在其他地方定义他，而不是在这

**Comment by whileW** [comment]
var counter = 0
func (c *MainController) Get() {
	c.Data["Website"] = "beego.me"
	c.Data["Email"] = "astaxie@gmail.com"
	counter++
	log.Println(c.counter)
	c.TplName = "index.tpl"
}
你可以试一试这样

**Comment by whileW** [comment]
> 一个全局对象吗？
> 
> > 你应该在其他地方定义他，而不是在这

var counter = 0 
func（c * MainController）Get（）{ 
c.Data [“Website”] =“beego.me” 
c.Data [“Email”] =“ astaxie@gmail.com ” 
counter ++ 
log.Println（c .counter）
c.TplName =“index.tpl” 
} 
你可以试一试这样

**Comment by 00arthur00** [comment]
我这样这样可以解决,但是每个controller旁边必须配一个全局变量...
PS:用英文吧,对beego的国际化社区发展有好处.

> > 一个全局对象吗？
> > > 你应该在其他地方定义他，而不是在这
> 
> var counter = 0
> func（c * MainController）Get（）{
> c.Data [“Website”] =“beego.me”
> c.Data [“Email”] =“ [astaxie@gmail.com](mailto:astaxie@gmail.com) ”
> counter ++
> log.Println（c .counter）
> c.TplName =“index.tpl”
> }
> 你可以试一试这样

我这样这样可以解决,但是每个controller旁边必须配一个全局变量...
PS:用英文吧,对beego的国际化社区发展有好处.

**Comment by whileW** [comment]
> 我这样这样可以解决，但是每个控制器旁边必须配一个全局变量... 
> PS：用英文吧，对beego的国际化社区发展有好处。
> 
> > > 一个全局对象吗？
> > > > 你应该在其他地方定义他，而不是在这
> > 
> > 
> > var counter = 0 
> > func（c * MainController）Get（）{ 
> > c.Data [“Website”] =“beego.me” 
> > c.Data [“Email”] =“ [astaxie@gmail.com](mailto:astaxie@gmail.com) ” 
> > counter ++ 
> > log.Println （c .counter）
> > c.TplName =“index.tpl” 
> > } 
> > 你可以试一试这样
> 
> 我这样这样可以解决，但是每个控制器旁边必须配一个全局变量... 
> PS：用英文吧，对beego的国际化社区发展有好处。

you can make a struct  to do this

type Count struct{
Controller string
Counter int
}
type CountArray []*Count
var Count = make(CountArray , 0)

and why don't use db？
