### ISSUE TITLE
beego swagger api如何排序

### ISSUE THREAD

**Issue by qqtou** [astaxie/beego#3705]
1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.11.2
├── GoVersion : go1.12.6

2. What operating system and processor architecture are you using (`go env`)?

├── GOOS      : linux
├── GOARCH    : amd64

3. What did you do?
object和user两个接口，如何排序呢？
我要调整object和user的顺序
![image](https://user-images.githubusercontent.com/16641284/60642777-988f7480-9e63-11e9-875e-dc4a57ae81cf.png)

4. What did you expect to see?
如何设置object和user的显示顺序，上下依次显示的顺序

**Comment by hjwlsy** [comment]
去下载最新的swagger-ui，覆盖就好了

**Comment by hjwlsy** [comment]
https://github.com/swagger-api/swagger-ui/tree/master/dist
