### ISSUE TITLE
JSONBody add header  application/json

### ISSUE THREAD

**Issue by luohlRoger** [astaxie/beego#3707]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego : v1.11.1
go :  1.12

2. What operating system and processor architecture are you using (`go env`)?
win10 64 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

使用beego中的BeegoHTTPRequest  请求其他微服务，JSONBody 方式添加 Content-Type :   application/json   , 调用String() 发起请求，微服务接收不到参数；但使用  httplib.Post(url).Header（“key",value）方式添加 Content-Type :   application/json  ， 能正常接收到参数

English: Using beego's BeegoHTTPRequest to invoke other microservice, and add `Content-Type :   application/json` into JSONBody, my microservice doesn't receive parameters. But when I used `httplib.Post(url).Header（“key",value)` and add header `Content-Type :   application/json`, my microservice receive the parameter.

4. What did you expect to see?
  JSONBody using  Content-Type :   application/json  work as expected.

5. What did you see instead?

**Comment by IamCathal** [comment]
Hi, when you're using the `JSONBody` func you're only meant to give an interface that will be unmarshalled into it's JSON representation. The actual func adds on the correct `Content-Type: application/json` header to the request object so it's not necessary for you to add it yourself.

https://github.com/astaxie/beego/blob/7a48fbb69846515d9dc3627096590f2b7b2a1bca/httplib/httplib.go#L358-L370

By setting up two beego servers, the first to send the request using `BeegoHTTPRequest` as you asked and the second to receive and print out the headers of the request we can see that this works fine. 
```go
package main

import (
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/httplib"
)

type exampleData struct {
	Status string `json:"status"`
	Body   string `json:"body"`
}

type MainController struct {
	beego.Controller
}

func main() {
	ctrl := &MainController{}
	beego.Router("/yuppa", ctrl, "get:Yuppa")
	beego.BConfig.Listen.HTTPPort = 8081
	beego.Run()
}

func (ctrl *MainController) Yuppa() {
	example := &exampleData{
		Status: "Success",
		Body:   "Hello world",
	}
	// Simulate calling another beego microservice
	req := httplib.Get("http://localhost:8080/yuppa")
	req, _ = req.JSONBody(example)
	_, _ = req.Response()

	ctrl.Ctx.WriteString("Success")
}
```

And on the other beego microsercive we can accept this request and print out it's headers:
```go
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"

	"github.com/astaxie/beego"
)

type exampleData struct {
	Status string `json:"status"`
	Body   string `json:"body"`
}

func main() {
	ctrl := &MainController{}
	beego.Router("/yuppa", ctrl, "get:Yuppa")
	beego.Run()
}

type MainController struct {
	beego.Controller
}

func (ctrl *MainController) Yuppa() {
	body, _ := ioutil.ReadAll(ctrl.Ctx.Request.Body)

	var req exampleData
	_ = json.Unmarshal(body, &req)

	for key, val := range ctrl.Ctx.Request.Header {
		fmt.Println(key, val)
	}
	ctrl.Ctx.WriteString("Success")
}
```
By using `curl -X GET "http://localhost:8081/yuppa" -d '{"status":"success","body":"hello world"}'` we can ping the first server and the logs of the 2nd server (receiving) will show the headers as expected.
```
cathal@gomei: $ go run main.go
2020/07/23 15:59:16.288 [I]  http server Running on http://:8080
{"status":"Success","body":"Hello world"}
User-Agent [beegoServer]
Content-Length [41]
Content-Type [application/json]
Accept-Encoding [gzip]
```
