### ISSUE TITLE
Relationships  How to Set Foreign Key

### ISSUE THREAD

**Issue by ljhh** [astaxie/beego#3709]
Go Version 1.12.5
BEEGO Version 1.11.2

I define three models like
```
type User struct {
  Id
  Account
  Password
}

type UserDetail struct {
  Id
  UserId
  Nickname
  Avatar
}

type Post struct {
  Id
  Creator *UserDetail `orm:"rel(fk)`
}
```
I do
`o := orm.NewOrm()`
`qs := o.QueryTable(new(Post))`
`var p Post`
`qs.RelatedSel().All(&p)`
But the relationship  is Post.creator_id = UserDetail.Id
How to set UserDetail.UserId to Foreign key?

**Comment by kmilo2622** [comment]
Please does anyone know how to do this?

**Comment by flycash** [comment]
You can not do that. If you want to do this:
type Post struct {
  Id
  Creator *User `orm:"rel(fk)`
}
