### ISSUE TITLE
c.ParseForm() parse data from form error, beego 1.12.0

### ISSUE THREAD

**Issue by sunwenli** [astaxie/beego#3720]
https://github.com/astaxie/beego/blob/de7ce2f9b02dc0f4afe4f7c0a0304cfecb1b62c1/templatefunc.go#L310

这里判断 formValues 长度有问题，如果为 2 的话，那么 value 是空字符，333 行的 strconv.ParseInt() 就报错了。

当发 post 请求时，url 后面拼接一个 key, 然后 form 表单里也有一个同名的 key ,那这时 formValues 的长度就 2 了。

**Comment by sunwenli** [comment]
解决办法： url 里和 form 表单里的同名的 key 只保留一个就行了。

**Comment by cooljl31** [comment]
🤔
