### ISSUE TITLE
redis send select dbnum

### ISSUE THREAD

**Issue by kingfsen** [astaxie/beego#3725]
now, my redis is cluster mode, I will request my redis with proxy。
now，my redis has no dbnum concept, so redis proxy can not support command `SELECT $dbnum`, but  beego cache redis code :
```
func (rc *Cache) connectInit() {
	dialFunc := func() (c redis.Conn, err error) {
		c, err = redis.Dial("tcp", rc.conninfo)
		if err != nil {
			return nil, err
		}

		if rc.password != "" {
			if _, err := c.Do("AUTH", rc.password); err != nil {
				c.Close()
				return nil, err
			}
		}

		_, selecterr := c.Do("SELECT", rc.dbNum)
		if selecterr != nil {
			c.Close()
			return nil, selecterr
		}
		return
	}
	// initialize a new pool
	rc.p = &redis.Pool{
		MaxIdle:     3,
		IdleTimeout: 180 * time.Second,
		Dial:        dialFunc,
	}
}
```

when application init redis, send command `SELECT 0` , my reids proxy will return error。
but go-redis code 
`_, err := conn.Pipelined(func(pipe Pipeliner) error {
		if c.opt.Password != "" {
			pipe.Auth(c.opt.Password)
		}

		if c.opt.DB > 0 {
			pipe.Select(c.opt.DB)
		}

		if c.opt.readOnly {
			pipe.ReadOnly()
		}

		return nil
	})`

**Comment by DennisMao** [comment]
@kingfsen  received.we will support redis cluster as soon as possible.
