### ISSUE TITLE
Fix "fatal error: concurrent map iteration and map write"  on task.go

### ISSUE THREAD

**Issue by WenKun5** [astaxie/beego#3729]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12.0

2. What operating system and processor architecture are you using (`go env`)?
(1) `set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\GoPath
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build502317586=/tmp/go-build -gno-record-gcc-switches
`
(2)`GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build227175712=/tmp/go-build -gno-record-gcc-switches"
`

3. What did you do?
I have build an api program based on beego that used task.go for sending  crond tasks. The api program need a  high concurrency which may creat 100 tasks or more on the same second。

4. What did you expect to see?
I want task.go can run normally, but when if add new task when task.go ready to execute tasks, it crushed.

5. What did you see instead?

`fatal error: concurrent map iteration and map write

goroutine 5 [running]:
runtime.throw(0xab7ed9, 0x26)
        C:/Go/src/runtime/panic.go:617 +0x79 fp=0xc000441d38 sp=0xc000441d08 pc=0x4307a9
runtime.mapiternext(0xc000441ef8)
        C:/Go/src/runtime/map.go:860 +0x59e fp=0xc000441dc0 sp=0xc000441d38 pc=0x40f7be
github.com/astaxie/beego/toolbox.run()
        E:/GoPath/src/github.com/astaxie/beego/toolbox/task.go:435 +0x663 fp=0xc000441fe0 sp=0xc000441dc                                                        0 pc=0x77b7b3
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000441fe8 sp=0xc000441fe0 pc=0x45bec1
created by github.com/astaxie/beego/toolbox.StartTask
        E:/GoPath/src/github.com/astaxie/beego/toolbox/task.go:401 +0x98

goroutine 1 [chan receive, 5 minutes]:
github.com/astaxie/beego.(*App).Run(0xc0001240d0, 0x0, 0x0, 0x0)
        E:/GoPath/src/github.com/astaxie/beego/app.go:239 +0x273
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
        E:/GoPath/src/github.com/astaxie/beego/beego.go:72 +0x69
`

I have fixed the bug, but i don't know how to push my code to develop. so ,how to push my code?

**Comment by IamCathal** [comment]
Hi, 

I assume you're talking about a code fix for the beego source code? If so you can [learn about how to contribute to someone else's project](https://lab.github.com/githubtraining/introduction-to-github) using pull requests. [Heres](https://lab.github.com/githubtraining/reviewing-pull-requests) another free course on how to review pull requests.

**Comment by flycash** [comment]
@WenKun5 You can just create a pull request:
![image](https://user-images.githubusercontent.com/9923838/86781352-590bf180-c090-11ea-8168-78a8b5855625.png)

You can take other pull request as an example.
