### ISSUE TITLE
Assets Management Package

### ISSUE THREAD

**Issue by samhamilton** [astaxie/beego#373]
It would be great if Beego can include an asset management package like https://github.com/shaoshing/train, it would really help production enviroments.

**Comment by runner-mei** [comment]
这个进展如何

**Comment by calvinwyoung** [comment]
Does anyone know whether https://github.com/shaoshing/train can be used with Beego?

**Comment by bakanis** [comment]
There is compression feature alreday for asset compilation/minimization/etc. https://github.com/beego/compress

**Comment by calvinwyoung** [comment]
Can that be used to compile Sass files? I was intereste din Train because Sass support comes out-of-the-box.

**Comment by saturn4er** [comment]
If the issue is still relevant today, I wrote my own library for beego. Rails-style assets for beego. https://github.com/saturn4er/beego-assets

**Comment by astaxie** [comment]
@saturn4er AWESOME

**Comment by saturn4er** [comment]
@astaxie Maybe add this functionality to beego? I can create pull-request

**Comment by astaxie** [comment]
@saturn4er please go for it. thanks
