### ISSUE TITLE
测试用例

### ISSUE THREAD

**Issue by vrggr** [astaxie/beego#3733]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by dongjinxian** [comment]
api 工程的测试用例，到底是怎么运行的？有人说一下吗？

**Comment by dongjinxian** [comment]
go test tests/default_test.go 像这样？
