### ISSUE TITLE
How to use GroupBy?

### ISSUE THREAD

**Issue by sunriquelme** [astaxie/beego#3735]
I don't find the method like max min sum avg,how to use these methods?

**Comment by kispi** [comment]
Mostly the case you need to need sum, max, avg is when you want to make some statistics for dashboard, for example.

And for those cases, pre-defined models usually don't directly fit to what exactly we need.

I think you can use just raw query using Orm.Raw() after you tested some stat queries to see if they're working.

**Comment by sunriquelme** [comment]
> Mostly the case you need to need sum, max, avg is when you want to make some statistics for dashboard, for example.
> 
> And for those cases, pre-defined models usually don't directly fit to what exactly we need.
> 
> I think you can use just raw query using Orm.Raw() after you tested some stat queries to see if they're working.

thanks.
when i find the method GroupBy,I take it for granted that will have the method like sum,max. ok, i will use the raw to complete my work, thank you.

**Comment by B8kingS0ga** [comment]
But without method such as sum, avg, count, the GroupBy method seems not that usefull
