### ISSUE TITLE
why does query.Filter() return a new QuerySeter? if not does like this , filter condition is not work

### ISSUE THREAD

**Issue by fengbenming** [astaxie/beego#3740]
orm := mysql.NewOrm()
	query := orm.QueryTable(constant.TABLE_MagicCategoryProductSale)
	query = query.Filter("website_name", websiteName)
	query = query.Filter("date__gte", start)
	query = query.Filter("date__lte", end)
	query = query.Limit(-1)
	query.All(&categorySales)

**Comment by szyhf** [comment]
just use it like:

```golang
orm.QueryTable(constant.TABLE_MagicCategoryProductSale).
    Filter("website_name", websiteName).
    Filter("date__gte", start).
    Filter("date__lte", end).
    Limit(-1).
    All(&categorySales)
```

**Comment by fengbenming** [comment]
@szyhf    yeah, but I want to judge the param if is empty before add to filter.
