### ISSUE TITLE
json contains `$` symbol(both in key and value field), Ctx.Input.RequestBody omit `$`

### ISSUE THREAD

**Issue by qizhelongdeyang** [astaxie/beego#3741]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.11.1
├── GoVersion : go1.10.3
├── GOOS      : darwin
├── GOARCH    : amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/randy/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Developer/10GoProject"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"

3. What did you do?
request json is `[{"time":1564476389888,"_track_id":4258257584,"event":"$AppClick","_flush_time":1564476392555,"distinct_id":"C2DC870E-FF5F-4F82-B6EB-A43B05D93FF8","properties":{"$app_version":"1.0","$screen_width":414,"$title":"main","$element_content":"Button","$element_type":"UIButton","$is_first_day":true,"$model":"iPhone11,8","$device_id":"553F62F8-3783-4DDF-B46E-A7AC405F250E","$network_type":"WIFI","$os":"iOS"}
}]`
then in the controller i print 
jsonStr := string(this.Ctx.Input.RequestBody)
	beego.Info("enter Track:",jsonStr)

4. What did you expect to see?
I expect the bean  would be the value like JSON in step3, while all the `$` has bean discard

5. What did you see instead?
2019/07/30 19:22:52.623 [I] [EventController.go:32]  enter Track: [{"time":1564476389888,"_track_id":4258257584,"event":"","_flush_time":1564476392555,"distinct_id":"C2DC870E-FF5F-4F82-B6EB-A43B05D93FF8","properties":{"":"1.0","":414,"":"main","":"Button","":"UIButton","":true,"":"iPhone11,8","":"553F62F8-3783-4DDF-B46E-A7AC405F250E","":"WIFI","":"iOS"}}]

**Comment by IamCathal** [comment]
Hi, I've been looking into this issue and I believe that beego is not the cause of the problem. I reproduced your error with the following code:

```go
package main

import (
	"io/ioutil"
	"log"

	"github.com/astaxie/beego"
)

func main() {
	ctrl := &MainController{}
	beego.Router("/yuppa", ctrl, "get:Yuppa")
	beego.Run()
}

type MainController struct {
	beego.Controller
}

func (ctrl *MainController) Yuppa() {
	output := ctrl.Ctx.Output

	body, err := ioutil.ReadAll(ctrl.Ctx.Request.Body)
	if err != nil {
		log.Fatal(err)
	}

	output.Header("Content-Type", "application/json")
	ctrl.Ctx.WriteString(string(body))
}
```

Which when called using this curl command:
```
curl -X GET "http://localhost:8080/yuppa" -d "{\"time\": 1564476389888,\"_track_id\": 4258257584,\"event\": \"$AppClick\",\"_flush_time\": 1564476392555,\"distinct_id\": \"C2DC870E-FF5F-4F82-B6EB-A43B05D93FF8\",\"properties\": {\"$app_version\": \"1.0\",\"$screen_width\": 414,\"$title\": \"main\",\"$element_content\": \"Button\",\"$element_type\": \"UIButton\",\"$is_first_day\": true,\"$model\": \"iPhone11,8\",\"$device_id\": \"553F62F8-3783-4DDF-B46E-A7AC405F250E\",\"$network_type\": \"WIFI\",\"$os\": \"iOS\"}}"
```

Oddly enough it only gave back the last key value pair when the key had a $ in it even though this occurs more than once. It Gives back the even less than your initial incorrect response: 
```json
{
    "time": 1564476389888,
    "_track_id": 4258257584,
    "event": "",
    "_flush_time": 1564476392555,
    "distinct_id": "C2DC870E-FF5F-4F82-B6EB-A43B05D93FF8",
    "properties": {
        "": "iOS"
    }
}
```

I then tried to run the same scenario using another golang web framework [gmux](https://github.com/gorilla/mux) with the following code and command only to get the exact same response.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func HomeHandler(w http.ResponseWriter, req *http.Request) {
	body, err := ioutil.ReadAll(req.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(body))

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, string(body))
}

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/", HomeHandler).Methods("POST")

	log.Println("Starting web server on localhost:8080")
	http.ListenAndServe(":8080", r)
}
```

```go
curl -X POST "http://localhost:8080" -d "{\"time\": 1564476389888,\"_track_id\": 4258257584,\"event\": \"$AppClick\",\"_flush_time\": 1564476392555,\"distinct_id\": \"C2DC870E-FF5F-4F82-B6EB-A43B05D93FF8\",\"properties\": {\"$app_version\": \"1.0\",\"$screen_width\": 414,\"$title\": \"main\",\"$element_content\": \"Button\",\"$element_type\": \"UIButton\",\"$is_first_day\": true,\"$model\": \"iPhone11,8\",\"$device_id\": \"553F62F8-3783-4DDF-B46E-A7AC405F250E\",\"$network_type\": \"WIFI\",\"$os\": \"iOS\"}}"
```

```json
{
    "time": 1564476389888,
    "_track_id": 4258257584,
    "event": "",
    "_flush_time": 1564476392555,
    "distinct_id": "C2DC870E-FF5F-4F82-B6EB-A43B05D93FF8",
    "properties": {
        "": "iOS"
    }
}
```

Then as a last ditch effort I tried to add in a `$` character into a json string and just tried to unmarshal it and low and behold it broke. Remove the $ before the json string and you'll see that it unmarshal without any difficulties

https://play.golang.org/p/-N2nx40kvQi

I'm not sure what's causing this and my googling has come up with nothing but I suspect I just don't know the right term for whatever golang is doing that doesnt allow $ in the key values of JSON even though JSON itself has no problem with it
