### ISSUE TITLE
parent path perm error

### ISSUE THREAD

**Issue by doovemax** [astaxie/beego#3748]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.12.0
├── GoVersion : go1.12.7
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : gohome
├── GOROOT    : /usr/local/Cellar/go/1.12.7/libexec
├── Compiler  : gc
└── Date      : Monday, 5 Aug 2019

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/doovemax/gohome/bin"
GOCACHE="/Users/doovemax/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/doovemax/gohome"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6y/pv2wbzrj2zbgr1fgz1686ncc0000gn/T/go-build876922179=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?

logs module create log dir ,perm error.

4. What did you expect to see?
drw-r----- 2 root root 25 Aug  5 10:49 logs/
5. What did you see instead?

![image](https://user-images.githubusercontent.com/22794109/62442655-1f997a80-b78b-11e9-9169-bd9581e8c024.png)
![image](https://user-images.githubusercontent.com/22794109/62442727-55d6fa00-b78b-11e9-9d86-919dc424aae5.png)

the log file parent path haven't x perm

**Comment by IamCathal** [comment]
Hi, correct me if I'm wrong but I believe that you're using the incorrect file permissions. See [this page](https://chmodcommand.com/chmod-660/) for details on what file perms 660 gives you. If you wanted execute permissions as you said you should use [760](https://chmodcommand.com/chmod-760/) which gives `drwxrw----`


If you're ever stuck with trying to figure out permissions I'd recommend looking at that website.
