### ISSUE TITLE
setLogger permission denied

### ISSUE THREAD

**Issue by zychappy** [astaxie/beego#3751]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

latest master
2. What operating system and processor architecture are you using (`go env`)?
mac OS  10.14

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
logs.SetLogger(logs.AdapterFile, `{"filename":"logs/admin.log","level":7,"daily":true,"maxdays":10,"color":true}`)
```
4. What did you expect to see?
logs can be recorded into logs/admin.log

5. What did you see instead?
logs.BeeLogger.SetLogger: open logs/admin.log: permission denied

**Comment by guhan121** [comment]
@zychappy  add `"perm":"0770"` to josn config,like
 ```
logs.SetLogger(logs.AdapterFile,`{"filename":"logs/admin.log","level":7,"maxlines":0,"maxfiles":10,"MaxSize":104857600,"perm":"0770"}`)
```
