### ISSUE TITLE
请问如何通过过滤器AfterExec把返回的json数据加密后重新输出

### ISSUE THREAD

**Issue by ytd7777** [astaxie/beego#3759]
有个项目需要加密输出结果
ctx.Output.Reset(ctx)
ctx.Output.Body([]byte(bodys)) 并没有生效，还是原来的json数据，请问该如果才能修改输出数据

**Comment by liyilike** [comment]
后台使用ace加密，app用ace解密，最安全方法

**Comment by litterGuy** [comment]
遇见一个类似的问题，想在filter中AfterExec后处理一下所有contriller返回的数据
对所有返回数据做次封装、返回结果统一化
问题是，从何从context中获取body中的数据？

`
beego.InsertFilter("/*", beego.AfterExec, filter.NsJsonFilter,false)

func NsJsonFilter(ctx *context.Context) {

}
`

**Comment by litterGuy** [comment]
也碰见了这个问题，在filter中使用无法修改controller的结果

`beego.InsertFilter("/*", beego.AfterExec, filter.NsJsonFilter,false)`

`ctx.Output.Reset(ctx)
	ctx.Output.JSON(nil, true, false)`

**Comment by litterGuy** [comment]
> 也碰见了这个问题，在filter中使用无法修改controller的结果
> 
> `beego.InsertFilter("/*", beego.AfterExec, filter.NsJsonFilter,false)`
> 
> `ctx.Output.Reset(ctx)`
> `ctx.Output.JSON(nil, true, false)`
原来在output.Body中有这个设置：
output.Context.ResponseWriter.Started = true

调用一次this.ServeJSON()后 output中的值则不再进行修改了。我把controller里的调用去掉，由AfterExec的filter调用即可

**Comment by litterGuy** [comment]
api项目可以如上修改 但是在web项目内不行 怎么处理？

**Comment by zzBeeCoder** [comment]
这个问题最后也没解决吗
