### ISSUE TITLE
如何对使用rom的接口进行单元测试？

### ISSUE THREAD

**Issue by for2B** [astaxie/beego#3761]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.12.6 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hwj\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\go-work
set GOPROXY=https://goproxy.io
set GORACE=
set GOROOT=D:\golang
set GOTMPDIR=
set GOTOOLDIR=D:\golang\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go-work\MinioApi\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\hwj\AppData\Local\Temp\go-build516283654=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
我该如何为我的model和controller进行单元测试？特别是orm，如何进行模拟？

4. What did you expect to see?
能够使用模拟的方法，或者更有效的方式进行单元测试。

**Comment by flycash** [comment]
这算是所有的依赖于数据的通病，我感觉我们需要提供一个基于内存数据库DB的实现，这样可以避免启动真实的服务器。

**Comment by flycash** [comment]
兜了一圈之后，发现启动数据库而后在单测前后清理数据库是最简单的事情……这应该算是golang的通病了，golang不具备类似java那种强大的mock功能。
