### ISSUE TITLE
beego获取经过模版处理后的html

### ISSUE THREAD

**Issue by ghost** [astaxie/beego#3762]
我想beego经过模版处理后的html，生成静态html的文件，问题是我不知道怎么获取beego经过模版处理后的html页面的源码，有没函数可以获得？

**Comment by whileW** [comment]
http request 请求接口，接口通过beego处理模板，将处理后的html放到response中，你可以在写个方法通过http，调用这个接口，然后获取到response 就是处理后的html页面。
