### ISSUE TITLE
JSON_FORMAT access log should only output json without any prefix

### ISSUE THREAD

**Issue by bharat-p** [astaxie/beego#3769]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go  = 1.12
Beego = 1.12.0

4. What did you do?
* Set up a simple api using beego
* enable access log by setting: 
`beego.BConfig.Log.AccessLogs = false`
* set access log format to JSON_FORMAT
`beego.BConfig.Log.AccessLogsFormat = "JSON_FORMAT"`

4. What did you expect to see?
I expected beego to output access log as a valid json string
```
{"remote_addr":"::1","request_time":"2019-08-17T14:19:40.952582-07:00","request_method":"GET","request":"GET /test HTTP/1.1","server_protocol":"HTTP/1.1","host":"localhost:8082","status":200,"body_bytes_sent":0,"elapsed_time":1967,"http_referrer":"","http_user_agent":"PostmanRuntime/7.15.2","remote_user":""}
```

5. What did you see instead?

```
2019/08/17 14:19:41.102  {"remote_addr":"::1","request_time":"2019-08-17T14:19:40.952582-07:00","request_method":"GET","request":"GET /test HTTP/1.1","server_protocol":"HTTP/1.1","host":"localhost:8082","status":200,"body_bytes_sent":0,"elapsed_time":1967,"http_referrer":"","http_user_agent":"PostmanRuntime/7.15.2","remote_user":""}
```
Access log is prefixed with string representing log time, log time should also be put inside the json being outputted

**Comment by IamCathal** [comment]
Working on this at the moment
