### ISSUE TITLE
How to query a table that created by RegisterModelWithSuffix?

### ISSUE THREAD

**Issue by chuanjiesun** [astaxie/beego#3773]
1. What version of Go and beego are you using (`bee version`)?
go version go1.12.1 windows/amd64;  beego 1.12.0
2. What operating system and processor architecture are you using (`go env`)?
windows10/x64 intel

there has already a table that created by RegisterModelWithSuffix,like "user_2019-08-22-14-20-35", struct is like below:
type User struct {
   Id            int
   User       string
   Password  string
}

I connect to database, than want to query the table "user_2019-08-22-14-20-35",if there is an example? 
I used o.QueryTable("user_2019-08-22-14-20-35").Filter("id", id).One(&user), an error occured:"panic: <Ormer.QueryTable> table name: `user_2019-08-22-14-20-35` not exists".

**Comment by danvinhe** [comment]
Used the orm.Raw

**Comment by flycash** [comment]
> Used the orm.Raw

It works but actually this is a bug. I think we should support this query `o.QueryTable("user_2019-08-22-14-20-35").Filter("id", id).One(&user)`

**Comment by flycash** [comment]
related pr #3894

**Comment by flycash** [comment]
Here is an example:
```go
type PrefixUser struct {
	ID   int `orm:"column(id)"`
	Name string
}

	RegisterModelWithPrefix("T_", new(PrefixUser))

	err := RunSyncdb("default", true, false)
	assert.Nil(t, err)

	o := NewOrm()

	pu := &PrefixUser{
		Name: "MyName",
	}

	_, err = o.Insert(pu)
	assert.Nil(t, err)
	res := &PrefixUser{}
	err = o.QueryTable(new(PrefixUser)).One(res)
	assert.Equal(t, "MyName", res.Name)
	assert.Nil(t, err)
```

The key point is that using `new(PrefixUser)` to query data.

The table name is "T_prefix_user"
