### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by Maary** [astaxie/beego#3778]
使用go moudles创建的工程
当执行go build时报错: 
build command-line-arguments: cannot load github.com/astaxie/beego/cache/go_redis: cannot find module providing package github.com/astaxie/beego/cache/go_redis

**Comment by eaglexiang** [comment]
> 使用go moudles创建的工程
> 当执行go build时报错:
> build command-line-arguments: cannot load github.com/astaxie/beego/cache/go_redis: cannot find module providing package github.com/astaxie/beego/cache/go_redis

马哥你怎么解决的
