### ISSUE TITLE
MySQL connections with 'interpolateParams=true' parameter don't work

### ISSUE THREAD

**Issue by yokujin** [astaxie/beego#3786]
On v1.12.0  MySQL connections with `interpolateParams=true` parameter stopped working. I have to use this parameter because I query data from Sphinx Search via its emulated mysql connector (SphinxQL). And Sphinx Search doesn't support prepared statements.

On v1.11.1 that same code works very well.

Looks like the main cause of the problem is `orm.DB` wrapper introduced in new version. Functions implemented on it call `Prepare()` directly on connection and `Prepare()` unconditionally sends packet to MySQL server. Since Sphinx Search doesn't support prepare command it causes error which in turn causes panic. 

1. What version of Go and beego are you using (`bee version`)?
```
Beego     : 1.12.0
GoVersion : go1.12.9
GOOS      : linux
GOARCH    : amd64
NumCPU    : 4
GOPATH    : /home/username/Work/Go
GOROOT    : /snap/go/4301
Compiler  : gc
Date      : Friday, 30 Aug 2019
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/username/Work/Go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/4301"
GOTMPDIR=""
GOTOOLDIR="/snap/go/4301/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build771154417=/tmp/go-build -gno-record-gcc-switches"
```

3. What did you do?
Code to reproduce is very simple:
```go
package main

import (
	"os"
	_ "github.com/go-sql-driver/mysql"
	"github.com/astaxie/beego/orm"
)

func main() {
	sphinxURL := "@tcp(localhost:9306)/fake?interpolateParams=true"

	orm.RegisterDataBase("sphinx", "mysql", sphinxURL, 30) // <= this line causes problem

       // some other code
}
```

4. What did you expect to see?
It is expected to connect successfully and to query data from Sphinx Search even with `?` substitutions and/or via `.Raw()` calls as it happened to be with v1.11.1.

5. What did you see instead?
```
panic: Error 1047: unknown command (code=22)

goroutine 1 [running]:
github.com/astaxie/beego/orm.(*DB).QueryRow(0xc00015d240, 0xa92621, 0x25, 0x0, 0x0, 0x0, 0xc000031020)
        /home/username/Work/Go/src/github.com/astaxie/beego/orm/db_alias.go:182 +0xc3
github.com/astaxie/beego/orm.detectTZ(0xc000100480)
        /home/username/Work/Go/src/github.com/astaxie/beego/orm/db_alias.go:221 +0x2f4
github.com/astaxie/beego/orm.RegisterDataBase(0xa7a965, 0x6, 0xa79594, 0x5, 0xc000030f0b, 0x54, 0xc00014bf48, 0x1, 0x1, 0xa778bd, ...)
        /home/username/Work/Go/src/github.com/astaxie/beego/orm/db_alias.go:322 +0x334
main.init.0()
        /home/username/Work/Go/src/llc/gapi/datasources.go:35 +0x147
```

**Comment by sonyta** [comment]
I have the same question

**Comment by ginruan** [comment]
I have the same problem. Did you guys figure it out? How to open driver prepare-statement for beego?

**Comment by Cbxyf** [comment]
I have the same question

Can't Beego clouse prepare stmt ?
