### ISSUE TITLE
bee run  运行报错

### ISSUE THREAD

**Issue by xiaoxi-note** [astaxie/beego#3787]
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2019/09/01 10:49:55 INFO     ▶ 0001 Using 'helloword' as 'appname'
2019/09/01 10:49:55 INFO     ▶ 0002 Initializing watcher...
can't load package: package .: no Go files in /Users/dumengmeng/go/src
2019/09/01 10:49:55 ERROR    ▶ 0003 Failed to build the application: can't load package: package .: no Go files in /Users/dumengmeng/go/src

**Comment by wushh** [comment]
项目是不是手动更换了位置了? 用命令行建立项目, 在运行试试

**Comment by HoracePeng** [comment]
这么明了的报错😔
