### ISSUE TITLE
How to use MYSQL function in ORM？

### ISSUE THREAD

**Issue by yizhitangtongxue** [astaxie/beego#3788]
version：v1.10.0
os：macos10.14
怎么使用这样的条件去查询 ？DATEDIFF(created,NOW())=0

**Comment by danvinhe** [comment]
使用orm的原生sql查询

**Comment by wushh** [comment]
看手册撒有例子

**Comment by yizhitangtongxue** [comment]
使用原生的解决了，手册里没看到相关例子

**Comment by qinjinze** [comment]
var index []*models.Index
	err = o.Raw("select * from index where datediff(every_day,now())=?", -1).QueryRow(&index)
 以上是查询昨天的所有数据，原生语句在登录mysql中试过是正确的，但把这个语句通过orm试却报语法错误

**Comment by flycash** [comment]
Using Raw Query
