### ISSUE TITLE
How to remove last slash from http://127.0.0.1:8080/v1/articles/?page=1 

### ISSUE THREAD

**Issue by mx4g** [astaxie/beego#3790]
api自动配置的问题：
这样的路由怎么写：http://127.0.0.1:8080/v1/articles?page=1
// @router / [get]  我是写了这样的配置
出来的效果 http://127.0.0.1:8080/v1/articles/?page=1 是这样的
 问号前面多了一个斜杆
导致路由无法解析，求助。

**Comment by mx4g** [comment]
求大神帮忙解决一下问题谢谢

**Comment by mx4g** [comment]
没人吗？没人碰到这个问题？

**Comment by mx4g** [comment]
怎么这么冷清啊

**Comment by danvinhe** [comment]
多一个斜杠有什么问题？就使用带/的路径呀

**Comment by cleverboy32** [comment]
> 多一个斜杠有什么问题？就使用带/的路径呀

不行啊 多带了一个

**Comment by flycash** [comment]
……在这种情况下，可以暂时考虑不是用注解路由。这样应该能够正确被处理。不过看上去这的确是一个bug……
