### ISSUE TITLE
没有释放prepare

### ISSUE THREAD

**Issue by timchine** [astaxie/beego#3791]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
最新版本
2. What operating system and processor architecture are you using (`go env`)?
go version go1.12.6 darwin/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

在每一次重启服务的时候发现mysql的Com_stmt_prepare一直累加，但是Com_stmt_close却很少。
当两个差集太大的时候，就会导致数据库连接不上，最终报错
”Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)“
我的数据库的sql是show global status like 'com_stmt%';
结果是这样的，这个时候差集不大。当他到达一个极限就会报错

![image](https://user-images.githubusercontent.com/33122791/64182400-c7918900-ce9a-11e9-97f1-6b2e3e061fb9.png)

5. What did you see instead?

**Comment by MarksGui** [comment]
我司昨日升级最新版后今日也出现这个问题：Can't create more than max_prepared_stmt_count statements (current value: 16382)
![image](https://user-images.githubusercontent.com/20791901/64220077-ac566600-cefa-11e9-9594-b0c4e52f20a5.png)

1.go version go1.12.9 linux/amd64

2.beego version v1.12.0

Com_stmt_prepare 创建多，Com_stmt_close 少。

**Comment by Danceofdeath** [comment]
Restore to previous versions-v1.11.1

**Comment by nicle-lin** [comment]
@Danceofdeath will it be fixed in next version?

**Comment by Danceofdeath** [comment]
maybe，it depends on the author

**Comment by ikingme** [comment]
beego v1.12.0版本存在这个问题，v1.11.1版本OK

**Comment by DennisMao** [comment]
@echoloveyou   @ikingme   orm里面用了哪些操作.我去查下

**Comment by ikingme** [comment]
@DennisMao 我这边只是用了查询 。Raw().QueryRow()

**Comment by likebeta** [comment]
我们也遇到了， 十一过的可惨了

**Comment by chenstrace** [comment]
1.12.0版本遇到了这个问题，幸运的是，在上线之前发现了。

**Comment by yearm** [comment]
![image](https://user-images.githubusercontent.com/44976685/68356276-ce63a300-014c-11ea-92f4-6eff0b574966.png)
怎么释放这个呢

**Comment by MarksGui** [comment]
> ![image](https://user-images.githubusercontent.com/44976685/68356276-ce63a300-014c-11ea-92f4-6eff0b574966.png)
> 怎么释放这个呢

回退版本！

**Comment by jemygraw** [comment]
今天也遇到了，一旦启动就往上飙。
