### ISSUE TITLE
今天第一次使用beego框架，好像beego不支持MOD

### ISSUE THREAD

**Issue by buguang01** [astaxie/beego#3794]
我使用go mod的方式引用beego发现会自动下载v1.12.0版本，可是怎么也下载不下来，上了你这里看了一下，原来是你们做了tag没做对应的release导致不能下载。
麻烦支持一下go mod 可以吗？

**Comment by DennisMao** [comment]
@buguang01  最近会解决

**Comment by lizhihua0925** [comment]
期待支持

**Comment by DennisMao** [comment]
@buguang01  错误提示是什么。如果直接go mod tidy 或者 go mod vendor无法下载的话 可以尝试用代理  `GOPROXY=https://goproxy.io go mod vendor `

**Comment by flycash** [comment]
已经支持了，最近的版本都有正确的tag。
