### ISSUE TITLE
some probleams here。

### ISSUE THREAD

**Issue by FunkZero** [astaxie/beego#3795]
I use the query like the Fllowing： 
`
timeStart := int(Datetime2Timestamp(time.Now().Format("2006-01-02")+" 00:00:01"))
timeEnd := int(Datetime2Timestamp(time.Now().Format("2006-01-02")+" 23:59:59"))
cnt,err:=o.QueryTable("apiquerylog").Filter("addtime__gte",timeStart).Filter("addtime__lte",timeEnd).Filter("uid",uid).Count()
`

but Why is it so inefficient?

`
[ORM]2019/09/05 12:09:31  -[Queries/default] - [  OK / db.QueryRow /    17.2ms] - [SELECT COUNT(*) FROM `apiquerylog` T0 WHERE T0.`addtime` >= ? AND T0.`addtime` <= ? AND T0.`uid` = ? ] - `1567612801`, `1567699199`, `2`
`

 [  OK / db.QueryRow /    17.2ms]
It scared me !!!
and  
It only takes 0.3 milliseconds to execute it in MYSQL.
so   why ？？？？？
May  i have your explanation please？？？？？

**Comment by DennisMao** [comment]
@FunkZero   pls provide the version of beego.And Where is the source of 0.3ms?

**Comment by flycash** [comment]
Can not reproduce
