### ISSUE TITLE
是否可以支持 ORDER BY FIELD

### ISSUE THREAD

**Issue by baranwang** [astaxie/beego#3804]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12

**Comment by danvinhe** [comment]
// add ORDER expression.
	// "column" means ASC, "-column" means DESC.
	// for example:
	//	qs.OrderBy("-status")
	OrderBy(exprs ...string) QuerySeter

**Comment by baranwang** [comment]
是 `ORDER BY FIELD` 不是 `ORDER BY` 自定义排序

**Comment by danvinhe** [comment]
@baranwang 只能使用原生查询
