### ISSUE TITLE
bee api apps 失败

### ISSUE THREAD

**Issue by mosign** [astaxie/beego#3806]
在运行beego src 目录下运行bee api apps 命令错误日志如下：
2019/09/14 10:34:23 INFO     ▶ 0001 Creating API...
	create	 /Users/xxx/go/src/apps
	create	 /Users/xxx/go/src/apps/conf
	create	 /Users/xxx/go/src/apps/controllers
	create	 /Users/xxx/go/src/apps/tests
	create	 /Users/xxx/go/src/apps/conf/app.conf
panic: open /Users/xxx/go/src/apps/conf/app.conf: no such file or directory

goroutine 1 [running]:
github.com/beego/bee/utils.MustCheck(...)
	/Users/xxx/go/src/github.com/beego/bee/utils/utils.go:239
github.com/beego/bee/utils.WriteToFile(0xc0001a4270, 0x24, 0xc0001e0080, 0x74)
	/Users/xxx/go/src/github.com/beego/bee/utils/utils.go:246 +0x177
github.com/beego/bee/cmd/commands/api.createAPI(0x4bf5620, 0xc0000b0050, 0x1, 0x1, 0x1)
	/Users/xxx/go/src/github.com/beego/bee/cmd/commands/api/apiapp.go:608 +0x170d
main.main()
	/Users/xxx/go/src/github.com/beego/bee/main.go:75 +0x2d4

创建项目失败，不知是什么原因导致的

**Comment by CleverBamboo** [comment]
+1

**Comment by CleverBamboo** [comment]
@mosign mysql数据版本过高

**Comment by flycash** [comment]
`panic: open /Users/xxx/go/src/apps/conf/app.conf` 看起来也可能是文件权限问题。

**Comment by CleverBamboo** [comment]
不是权限问题，把数据库版本降低，肯定能行！

**Comment by flycash** [comment]
> 不是权限问题，把数据库版本降低，肯定能行！

感谢！我先关了这个问题！
