### ISSUE TITLE
如何通过orm查询一个外键为空的单表

### ISSUE THREAD

**Issue by bobos008** [astaxie/beego#3809]
请教一下！
我有两张表：
type Bill struct {
    Id int64
    Name string `orm:"size(60)"`
    Provider *Provider `orm:"rel(fk);default(0)"`
}
type Provider struct {
    id int64
    Pname string `orm:"size(60)"`
    Bill []*Bill `orm:"reverse(many)"`
}
如果我只查询单表bill情况：
    1.bill表有外键为0
    2.Provider表中没有id为0的值
但是查询结果为空，我应该怎么写呢？

我的orm语句是: 
var billSlice []*Bill
o.QueryTable("bill").Filter("Provider", 0).Values(&billSlice)

原生sql语句：select * from bill where provider_id = 0;

**Comment by bobos008** [comment]
its ok

**Comment by flycash** [comment]
> 请教一下！
> 我有两张表：
> type Bill struct {
> Id int64
> Name string `orm:"size(60)"`
> Provider *Provider `orm:"rel(fk);default(0)"`
> }
> type Provider struct {
> id int64
> Pname string `orm:"size(60)"`
> Bill []*Bill `orm:"reverse(many)"`
> }
> 如果我只查询单表bill情况：
> 1.bill表有外键为0
> 2.Provider表中没有id为0的值
> 但是查询结果为空，我应该怎么写呢？
> 
> 我的orm语句是:
> var billSlice []*Bill
> o.QueryTable("bill").Filter("Provider", 0).Values(&billSlice)
> 
> 原生sql语句：select * from bill where provider_id = 0;

我来捋一捋你的问题，看我理解对不对。这里有点绕……
你的意思是，Bill表有外键为0，但是provider显然主键不可能为0，所以你查询的时候，用provider = 0作为条件去查询，理论上应该有Bill返回，但是最终结果是任何Bill返回，对吧？

所以也就是说，在我们的ORM这种机制之下，如果外键指向的是一个不存在的值，那么会导致查询不返回任何结果？
