### ISSUE TITLE
mysql密码中含有@符号，该怎么处理呢？

### ISSUE THREAD

**Issue by chrisfeng0723** [astaxie/beego#3810]
orm.RegisterDataBase中的链接datasource，密码中含有@特殊符号，该如何处理？

**Comment by snippet0809** [comment]
我测试了一下，密码中有@是可以正常链接的，连接串不用特殊处理，例如我的连接串（密码：@123）为：root:@123@/test?charset=utf8&loc=Asia%2FShanghai
