### ISSUE TITLE
请问怎么在控制器外使用context，以便操作cookie,session

### ISSUE THREAD

**Issue by shuiyueqingnong** [astaxie/beego#3812]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego: 1.12.0
os: ubuntu 19 

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hugo/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hugo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build575833074=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
自己创建了一个service,并引入了beego/context,
想在控制器外使用context操作cookie,session
结果无论是 ctx := context.NewContext()，还是ctx := context.Context{}都不能使用ctx.SetCookie()，请问我该如何实现这个功能，不可能所有数据都得在控制器操作啊，刚学golang，找不到其它地方咨询，请帮忙，谢谢

5. What did you see instead?
程序报空指针错误

**Comment by michaelkidpro** [comment]
遇到了同样的问题，想在models里使用context，没有找到对应方法

场景：
启动go程序时候 在main.go调用models里的连接mysql方法 连接数据库
想在models里通过context获取host,  通过host来确定数据库名字

**Comment by shuiyueqingnong** [comment]
最后我还是把context传入到models的方法里面去的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "michael007"<notifications@github.com&gt;; 
发送时间: 2020年1月23日(星期四) 下午2:35
收件人: "astaxie/beego"<beego@noreply.github.com&gt;; 
抄送: "黄岽权"<11572660@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [astaxie/beego] 请问怎么在控制器外使用context，以便操作cookie,session (#3812)




遇到了同样的问题，想在models里使用context，没有找到对应方法
 
场景：
 启动go程序时候 在main.go调用models里的连接mysql方法 连接数据库
 想在models里通过context获取host,  通过host来确定数据库名字

**Comment by flycash** [comment]
本质上来说，这个Context就是在一个http请求周期内存活。也就是说，它本来就只能在`controller`里面使用。如果你们要在别的地方使用，只能考虑从`controller`一路往下传。
