### ISSUE TITLE
能否完善下beego及bee对go module的支持

### ISSUE THREAD

**Issue by nicle-lin** [astaxie/beego#3832]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by DennisMao** [comment]
@nicle-lin 提供下问题表现和版本号

**Comment by nicle-lin** [comment]
> @nicle-lin 提供下问题表现和版本
现有的beego不支持outside of GOPATH的项目生成路由，bee不支持outside of GOPATH的项目没有vendor的情况及go mod里的项目的名字与项目路径名不一样的情况

**Comment by wnanbei** [comment]
+1

**Comment by chaselen** [comment]
+1

**Comment by nashTang** [comment]
+1

**Comment by fengqitudd01** [comment]
+1

**Comment by Aaron630** [comment]
+1

**Comment by wolf-leo** [comment]
+10086

**Comment by yuan-make** [comment]
+1

**Comment by flycash** [comment]
我们试图在v1.12.2的beego里面删除了vendor的文件，你们可以试试。而后bee近期也会发布一个新版本，这些情况会有所改善。

**Comment by flycash** [comment]
最近我们的几个版本对go mod的支持有了很大的改进
