### ISSUE TITLE
mac run bee  error：dyld: malformed mach-o image: segment __DWARF has vmsize < filesize Abort trap: 6

### ISSUE THREAD

**Issue by halleyshx** [astaxie/beego#3833]
> $bee
> dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
> Abort trap: 6

The bee version maybe 1.10.0,because I git clone the master today.
macos catalina  10.15

**Comment by guhan121** [comment]
`
cd $GOPATH/src/github.com/beego/bee

go install -ldflags "-w"
`

enjoy it!

**Comment by ZacZelner** [comment]
Hi Guhan121, I run the command go install -ldflags "-w", 
the issue still does not be fixed

**Comment by elihe2011** [comment]
it works, thanks to guhan121.

**Comment by jianzonggaoshou** [comment]
I run the command go install -ldflags "-w", then does not work and console show the:
`go: cannot find main module, but found vendor/vendor.json in /Users/hannah/go/src/github.com/beego/bee
	to create a module there, run:
	go mod init`

**Comment by guhan121** [comment]
@guhan121 

```
git clone https://github.com/guhan121/bee.git
cd bee
git checkout gomod
go build 
# copy bee into PATH As in the next step
cp ./bee  $GOPATH/bin
```

**Comment by flycash** [comment]
We had supported go mod now
