### ISSUE TITLE
[Proposal] Add configuration to override TLS config 

### ISSUE THREAD

**Issue by mrshengzyzy** [astaxie/beego#3834]
Beego now has supported TLS , but the client authentication is fixed to` RequireAndVerifyClientCert `, we cannot override it by configuration.
```
app.Server.TLSConfig = &tls.Config{
	ClientCAs:  pool,
	ClientAuth: tls.RequireAndVerifyClientCert,
}
```
Support we have an APP that allows both private-client and browser to visit.
We can integration certificates when download the private-client.
But for browser ?
Usually we **DO NOT** need certificates because we should log in the APP.
So we need to override this configuration, allow requests which without certificates to enter the APP, and then use other information , such as account and psssword , to clarify the identity of the visitor.

**Comment by mrshengzyzy** [comment]
I've tried to fix this.
But in the long  term, we may need to be able to customize the `TLS` configuration directly.

**Comment by flycash** [comment]
We had resoled this issue.
