### ISSUE TITLE
166开头手机号验证规则不支持

### ISSUE THREAD

**Issue by jmhjmh** [astaxie/beego#3838]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12.0

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by jianzhiyao** [comment]
https://github.com/astaxie/beego/issues/3746
在此issue已经支持
