### ISSUE TITLE
Beego ORM模块建议

### ISSUE THREAD

**Issue by winerQin** [astaxie/beego#384]
例如，我有如下代码：

var hotCourse []models.VCourse
sql = "SELECT * FROM v_course ORDER BY hits DESC LIMIT 4"
o.Raw(sql).QueryRows(&hotCourse)

传入的hotCourse对应的models.VCourse里面的字段与数据库里面的字段顺序要一致才能将预期的字段值设置到VCourse的字段里面去。

如：
type VCourse struct{
  Id int64
   Name string
}

那么sql语句里面必须SELECT id,name FROM table才能将字段的值绑定上去。这很不方便。

我希望是这样的：
当我的结构体只有两个字段：Id与Name,那么，在结果绑定到结构体上的时候，先遍历结构体的字段，按照Model的定义（即与表字段之间的定义）进行查找SQL里面的字段，然后将该字段的值绑定到结构体的对应字段上。这样就很完善了。

在编写代码的时候，就不用再担心字段顺序的问题了。也不用担心，结构体的字段只有2个，而SQL字段有3个，导致匹配不上而报错了。

能否请设计ORM的大神改善一下原生SQL语句的智能能力呢。谢谢！

**Comment by BlackLee** [comment]
用惯了Rails的ActiveRecord后再看Beego的，感觉相当的不便利。不奢望能在查询时返回ActiveRecord::Relation，但是至少能有ActiveRecord::Base里定义好的那么多便利的方法呀。

**Comment by yanxiyue** [comment]
raw sql的功能建议可以参考一下mybatis的实现方式。

**Comment by xiaoDC** [comment]
func Query(id int64, obj interface{})(interface{}, interface{}){
    oo := orm.NewOrm()
    objtype := reflect.TypeOf(obj).Name()
    fmt.Println(objtype)
    err := oo.Raw("SELECT id, name, password FROM  " + strings.ToLower(objtype) + " WHERE id = ?", id).QueryRow(&obj)
    fmt.Println(obj)
    return  obj, err
}

请问为什么我查找得到的对象是一个interface时就查找不到，必须给具体的struct吗？那我不是每个model中都得写CRUD方法？！

**Comment by wuranbo** [comment]
type User struct {
    Id   int
    Name string
    Profiles []*Profile
}

type Profile struct {
    Id   int
    Age  int
}

var users []*User
err := o.Raw(`SELECT id, name, p.id, p.age FROM user
    LEFT OUTER JOIN profile AS p ON p.id = profile_id WHERE id = ?`, 1).QueryRows(&users, User.Profiles)

怎么能一次select把related也弄到呢？

**Comment by lei-cao** [comment]
@winerQin Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by Joyonline** [comment]
oracle数据库，占位符不是“?” 是 “:序号“
