### ISSUE TITLE
beego.me网站打不开了么？

### ISSUE THREAD

**Issue by dafa168** [astaxie/beego#3848]
这两天不知道是我的网络问题还是beego网站关闭了 ? 你们呢？

**Comment by snippet0809** [comment]
刚试了下，第一次超时，然后刷新了下打开了，不过很慢

**Comment by dafa168** [comment]
> 刚试了下，第一次超时，然后刷新了下打开了，不过很慢

是的， 有时候看文档，看到其中一个文档就挂了，再也打不开了，等第二天又可以打开了。不知道为啥？

**Comment by wuliangxue** [comment]
服务部署在日本，部分机器可能被墙了，多试几次就好了
