### ISSUE TITLE
mac10.15.1 安装不上beego 的工具bee

### ISSUE THREAD

**Issue by flymecode** [astaxie/beego#3853]
显示的错误信息是# github.com/beego/bee/vendor/github.com/derekparker/delve/proc
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by Vanson** [comment]
重新执行一下xcode-select install 试试

**Comment by jmy10241024** [comment]
如果未安装Xcode,需要安装xcode, 如果装了多个xcode,指定其中一个
