### ISSUE TITLE
orm 插入数据 pgsql 字符串类型  数据中有好多空格

### ISSUE THREAD

**Issue by xxz933** [astaxie/beego#3855]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by AllenX2018** [comment]
能给出具体的例子，或者在playground上给个demo吗？只有这个title描述不好复现和定位

**Comment by jianzhiyao** [comment]
Please provide some example code to help us reproduce what you said.
For now, the only one thing we can do is closing this issue.
