### ISSUE TITLE
Migration Skip Table

### ISSUE THREAD

**Issue by sayi65** [astaxie/beego#3859]
Please answer these questions before submitting your issue. Thanks!

### 1. What version of Go and beego are you using (`bee version`)?
go 1.13.4
beego v1.12.0
bee v1.10.0

### 2. What operating system and processor architecture are you using (`go env`)?
我用·bee api创建的REST API

#### A complete runnable program is good.

``` go
model.go
type User struct {
	Id string `orm:"pk"`
	Loginid string `orm:"size(250)"`
	Password string `orm:"size(250)"`
	Email string `orm:"size(250)"`
//	testcolumn string `orm:"size(250)"`
}

main.go
orm.RunSyncdb("default", false, true)
```
创建一次user Table以后，把testcolumn加进去在执行一次的话
Migration 会Skip Table

![add column](https://user-images.githubusercontent.com/8959015/68283098-48008000-00be-11ea-9eeb-dc4ed2211e8a.PNG)

### 5. What did you see instead?

**Comment by marswj** [comment]
是不是小写的原因

**Comment by sayi65** [comment]
> 是不是小写的原因

这个跟Table名字小写 有关系吗？

**Comment by jianzhiyao** [comment]
### 文档
按照文档说明，此命令仅用作创建表，没有做修改表结构的支持，后续开发组会考虑支持相关修改表结构的工具
https://beego.me/docs/mvc/model/cmd.md#%E8%87%AA%E5%8A%A8%E5%BB%BA%E8%A1%A8

### 现象
按照你提供的图片，这里是有相关日志输出告知跳过的原因
![image](https://user-images.githubusercontent.com/6133860/95154664-ead8e700-07c4-11eb-84b1-aa0b2dc02568.png)
