### ISSUE TITLE
/read_:id:int.htm match unexpected request

### ISSUE THREAD

**Issue by zituocn** [astaxie/beego#3865]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.12.10
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/samsong/mygo
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Wednesday, 13 Nov 2019

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/samsong/mygo/bin"
GOCACHE="/Users/samsong/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/samsong/mygo"
GOPROXY="https://goproxy.cn"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/samsong/mygo/src/git.zituo.net/zituocn/gk100/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5r/x31jjvk55278ybxblv9m122w0000gn/T/go-build239828697=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
**Route config**

`beego.Router("/read_:id:int.htm", &handler.ArticleHandler{}, "*:ArticleDetail")`

it both match: /read_222.htm, /read_222htm, /read_222_htm, /read_262shtm

4. What did you expect to see?

Only match /read_222.htm

5. What did you see instead?

bee run logs：
```
2019/11/13 19:13:29.622 [D] [server.go:2774]  |  192.168.0.101| 200 |  17.763543ms|   match| GET      /read_262shtm   r:/read_:id:int.htm
2019/11/13 19:14:53.592 [D] [server.go:2774]  |  192.168.0.101| 200 |  14.859584ms|   match| GET      /read_262_htm   r:/read_:id:int.htm
2019/11/13 19:15:04.433 [D] [server.go:2774]  |  192.168.0.101| 200 |  16.207776ms|   match| GET      /read_262htm   r:/read_:id:int.htm
```

**Comment by zituocn** [comment]
期待修复 。

**Comment by flycash** [comment]
这个你可以暂时使用正则规则匹配来解决问题。

**Comment by jianzhiyao** [comment]
目前需要用此方式来实现你的需求
```
beego.Router("/read_:id:int\.htm", &handler.ArticleHandler{}, "*:ArticleDetail")
```
