### ISSUE TITLE
beego rawSetter queryRow 问题

### ISSUE THREAD

**Issue by cyflhn** [astaxie/beego#3866]
如果是一个嵌套struct，则使用queryRow无法填充struct的属性字段，但是queryRows函数的正常的，我看了下代码，queryRows有如下逻辑;

                                                if fe.Type.Kind() == reflect.Struct {
							recursiveSetField(f)
						}
但是queryRow函数没有这段逻辑

**Comment by qida** [comment]
附议

**Comment by nicle-lin** [comment]
附议,当初为什么会这样设计
