### ISSUE TITLE
InsertOrUpdate没有透传主键id导致变成全新的Insert

### ISSUE THREAD

**Issue by keminar** [astaxie/beego#3870]
Insert代码
```
n := Test{
	Id    :1,
	Ctime: time.Now().Unix() ,
}
o := orm.NewOrm()
id, err := o.Insert(&n)
```
当使用上面进行Insert时报错
[Queries/default] - [FAIL /     db.Exec /     1.1ms] - [INSERT INTO `test` (`id`, `ctime`) VALUES (?, ?)] - `1`, `1574215340` - Error 1062:
 Duplicate entry '1' for key 'PRIMARY'
此时是正常的报错。

当我需要根据主键进行InsertOrUpdate时
```
n := Test{
	Id    :1,
	Ctime: time.Now().Unix() ,
}
o := orm.NewOrm()
id, err := o.InsertOrUpdate(&n)
```
执行效果变成了
INSERT INTO `test` (`ctime`) VALUES (?) ON DUPLICATE KEY UPDATE `ctime`=?] - `15742
15605`, `1574215605`
没有把主键Id透传，导致数据新增加了一条，和预期不相符

**Comment by keminar** [comment]
在db_mysql.go中找到
values, _, err := d.collectValues(mi, ind, mi.fields.dbcols, true, true, &names, a.TZ)
改为
values, _, err := d.collectValues(mi, ind, mi.fields.dbcols, false, true, &names, a.TZ)
能达到预期值。这里个人认为写死skipAuto为true不合适，给用户埋坑

**Comment by jianzhiyao** [comment]
### 验证结果
用法错误，应该使用第二个参数去限定唯一索引
例如：``o.InsertOrUpdate(profile2, `id`)``

### 结论
暂时关闭此 issue

### 验证代码（含数输出结果）
```
package main

import (
	"fmt"
	"github.com/astaxie/beego/pkg/orm"
	_ "github.com/lib/pq"
)



type Profile struct {
	Id   int `orm:"column(id);size(64);pk"`
	Age  int16
}


func init() {
	_ = orm.RegisterDataBase("default", "postgres", "postgresql://postgres:@127.0.0.1:5432/postgres?sslmode=disable")
	orm.RegisterModel(new(Profile))
	name := "default"
	force := true
	verbose := true
	err := orm.RunSyncdb(name, force, verbose)
	fmt.Println(err)//output: nil
}

func main() {
	o := orm.NewOrm()

	profile1 := new(Profile)
	profile1.Age, profile1.Id = 34, 1
	_, err := o.Insert(profile1)
	fmt.Println(err)//output: nil

	profile2  := new(Profile)
	profile2.Age, profile2.Id = 555, 1
	_, err = o.InsertOrUpdate(profile2, `id`)
	fmt.Println(err)//output: nil

	profile3 := new(Profile)
	profile3.Id = 1
	err = o.Read(profile3)
	fmt.Println(err)//output: nil
	fmt.Println(profile3.Age)//output: 555

}
```
