### ISSUE TITLE
使用go module包管理，运行时beego没有生成路由文件的问题

### ISSUE THREAD

**Issue by junzizhao8** [astaxie/beego#3871]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 go version: 1.12.4
beego version : 1.12.0

2. What operating system and processor architecture are you using (`go env`)?
system: windows
architecture: amd64

根目录的router.go文件
Include(cList ...ControllerInterface)函数写死了路径
for _, wg := range wgopath {   
　　wg, _ = filepath.EvalSymlinks(filepath.Join(wg, "src", t.PkgPath()))   
　　if utils.FileExists(wg) {   
　　　　pkgpath = wg   
　　　　break   
　　}   
}
希望支持go module配置

**Comment by Hareis** [comment]
Hello, I ran into a similar problem today. All of a sudden, the normal API interface suddenly went wrong, console output. ```failed to  generate  the doc```

**Comment by Hareis** [comment]
> Hello, I ran into a similar problem today. All of a sudden, the normal API interface suddenly went wrong, console output. `failed to generate the doc`

I solved this problem because I changed the root directory file name of the project so that the module could not be found

**Comment by avtion** [comment]
如果目录命名中包含“_”这个字符好像会出问题

**Comment by Jackmrzhou** [comment]
Same here, I try every possible ways I could found but the router file just can't be generated, which is really annoying. I used gin before, and I really love the way beego managing routers by adding annotations in comments. Hoping support go module soon.

**Comment by Jackmrzhou** [comment]
#3882 Please check my pull request for solving router generation problems.

**Comment by danvinhe** [comment]
1. 注解路由必须设置runmode = dev开发模式
2. 注解路由的项目必须在gopath目录下
