### ISSUE TITLE
The cache behavior of `stmts` for `func getStmt(query string)` may case `memory leak` unexpectedly.

### ISSUE THREAD

**Issue by szyhf** [astaxie/beego#3873]
https://github.com/astaxie/beego/blob/1923b8c7677ad80e47f93fe1a0d2cd4118fa82c3/orm/db_alias.go#L121-L137

In most cases, I agree that cache the query make a better performance,  but in our case, the query is very long and build dynamically (even with placeholder its different), the memory keep increase unexpectedly and `go pprof` only can told me the variable of query string is leaking. I spent a lot of  time to find out the final reason and fix it with `RawPrepare`.

Cache is useful to save time for repeatedly query but not every query is repeatedly.

Please considering add a comment on document to warning user like me to use `RawPrepare` instead or add some params to orm to close the cache.

**Comment by flycash** [comment]
#4022 we resolved this problem
