### ISSUE TITLE
beego orm不支持不同数据库相同表名

### ISSUE THREAD

**Issue by SamuelXu** [astaxie/beego#3874]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.12.0

2. What operating system and processor architecture are you using (`go env`)?
linux

项目中在不同数据库下，有两个表有相同的表名，使用beego orm注册时，会报repeat register 的错误，查看代码 github.com/astaxie/beego/orm/models_boot.go 中注册的逻辑：
modelCache.set(table, mi)
这里用了table name，会导致这样的情况，是否有其他方法避免这个问题的发生？

**Comment by haijun568** [comment]
我也遇到过这个问题，只能改表名，希望官网解决

**Comment by danvinhe** [comment]
改表名吧，没有办法

**Comment by flycash** [comment]
这种限制是有道理的。因为虽然名字是相同的数据库名，但是因为它里面字段会不一样，所以本质上是两个model，因此使用。我们在Register方法里面，说明的这是`model`而不是`table`。
而如果两个表在两个数据里面，它们有一样的结构，那么就应当被看做是同一个model。
从这个角度来说，我认为没必要增加这种DB级别的model隔离机制。

而且，本身Orm是支持这种不同模型设置相同表明的。在`getTableName`方法里面：
```go
func getTableName(val reflect.Value) string {
	if fun := val.MethodByName("TableName"); fun.IsValid() {
		vals := fun.Call([]reflect.Value{})
		// has return and the first val is string
		if len(vals) > 0 && vals[0].Kind() == reflect.String {
			return vals[0].String()
		}
	}
	return snakeString(reflect.Indirect(val).Type().Name())
}
```
即你们的model可以通过实现`TableName`方法来返回不同的表名。

又或者使用不同的前缀、后缀：
```go
func RegisterModelWithPrefix(prefix string, models ...interface{}) {}

func RegisterModelWithSuffix(suffix string, models ...interface{}) {}
```

**Comment by flycash** [comment]
see #4105
