### ISSUE TITLE
get请求带参数请求, 到控制器的接受的时候, 发现参数全变成小写了

### ISSUE THREAD

**Issue by ishwy** [astaxie/beego#3880]
bee version
```
├── Beego     : 1.12.0
├── GoVersion : go1.13
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : D:\project\me\mygo
├── GOROOT    : c:\go
├── Compiler  : gc
└── Date      : Tuesday, 3 Dec 2019

```

首先Route文件定义:
Router: `/:objectIdTest`, 这里后面有大写字母,
```
    beego.GlobalControllerRouter["what_to_eat_go/controllers:ObjectController"] = append(beego.GlobalControllerRouter["what_to_eat_go/controllers:ObjectController"],
        beego.ControllerComments{
            Method: "Get",
            **Router: `/:objectIdTest`,**
            AllowHTTPMethods: []string{"get"},
            MethodParams: param.Make(),
            Filters: nil,
            Params: nil})
```
 但是, 在Controller里打印的时候发现, 参数全部变成了小写了, 不知道是什么用意
```
func (o *ObjectController) Get() {
	fmt.Print(o.Ctx.Input)
}

**[:objectidtest]** [hjkhsbnmn123] map[RouterPattern:/v1/object/:objectIdTest] {{0 0} 0 0 0 0} []  <nil>}2019/12/03 15:24:50.205 [D] [server.go:2802]  |            ::1| 200 |           0s|   match| GET      /v1/object/hjkhsbnmn123   r:/v1/object/:objectIdTest

```

**Comment by AllenX2018** [comment]
> bee version
> 
> ```
> ├── Beego     : 1.12.0
> ├── GoVersion : go1.13
> ├── GOOS      : windows
> ├── GOARCH    : amd64
> ├── NumCPU    : 8
> ├── GOPATH    : D:\project\me\mygo
> ├── GOROOT    : c:\go
> ├── Compiler  : gc
> └── Date      : Tuesday, 3 Dec 2019
> ```
> 
> 首先Route文件定义:
> Router: `/:objectIdTest`, 这里后面有大写字母,
> 
> ```
>     beego.GlobalControllerRouter["what_to_eat_go/controllers:ObjectController"] = append(beego.GlobalControllerRouter["what_to_eat_go/controllers:ObjectController"],
>         beego.ControllerComments{
>             Method: "Get",
>             **Router: `/:objectIdTest`,**
>             AllowHTTPMethods: []string{"get"},
>             MethodParams: param.Make(),
>             Filters: nil,
>             Params: nil})
> ```
> 
> 但是, 在Controller里打印的时候发现, 参数全部变成了小写了, 不知道是什么用意
> 
> ```
> func (o *ObjectController) Get() {
> 	fmt.Print(o.Ctx.Input)
> }
> 
> **[:objectidtest]** [hjkhsbnmn123] map[RouterPattern:/v1/object/:objectIdTest] {{0 0} 0 0 0 0} []  <nil>}2019/12/03 15:24:50.205 [D] [server.go:2802]  |            ::1| 200 |           0s|   match| GET      /v1/object/hjkhsbnmn123   r:/v1/object/:objectIdTest
> ```

@ishwy 你好，可以提供下完整的demo及测试用的URL吗？我尝试根据你提供的片段去复现，并未能复现变成小写的问题

**Comment by flycash** [comment]
我先关了吧，这种积年问题=。=等提问者回复了我再打开……
