### ISSUE TITLE
为什么 我Goland里面使用 beego.Error() 方法会提示不推荐使用呢？

### ISSUE THREAD

**Issue by fanpei0121** [astaxie/beego#3881]
提示 : ‘Error’ is deprecated

**Comment by Jackmrzhou** [comment]
Actually you can navigate to the definition, and you will find the reason is in the comment. It is deprecated.

**Comment by nicle-lin** [comment]
这也要提issue?

**Comment by Kuri-su** [comment]
@flycash this issue can be closed
