### ISSUE TITLE
Beego  现在有没有好的docker打包项目方法

### ISSUE THREAD

**Issue by ZacZelner** [astaxie/beego#3886]
bee dockerize 命令生成的dockerfile里大量使用了godep，这个现在在中国支持的很不好，运行会报各种错误。

错误包括:
运行自动生成的dockfile打包时：
Step 8/9 : RUN cd $APP_DIR && CGO_ENABLED=0 godep go build -ldflags '-d -w -s'
 ---> Running in bf4586147493
godep: No Godeps found (or in any parent directory)
The command '/bin/sh -c cd $APP_DIR && CGO_ENABLED=0 godep go build -ldflags '-d -w -s'' returned a non-zero code: 1

查询这个错误，google出来的结果是 要运行godep save,但是又会引发各类依赖包找不到的现象。
已经举步维艰。

**Comment by lhdboy** [comment]
我跟你遇到了同样的问题，也是使用bee dockerize 命令生成的dockerfile文件
go version go1.13.8 windows/amd64
