### ISSUE TITLE
Proposal：QuerySeter开放强制索引或忽略索引功能给开发者

### ISSUE THREAD

**Issue by SleepwalkerCh** [astaxie/beego#3891]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 go1.13  & Beego 1.12.0

2. What operating system and processor architecture are you using (`go env`)?
 arm64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
Expect to see: orm QuerySeter  provide a function like IgnoreIndex() or ForceIndex(). Do not have to use Raw SQL to achieve the goal。 

5. What did you see instead?

**Comment by jianzhiyao** [comment]
https://github.com/astaxie/beego/pull/4147 is merged to v2 develop branch
