### ISSUE TITLE
/root/go/pkg/mod/github.com/astaxie/beego@v1.12.0/logs/es/es.go:24:2: undefined: goes.Client

### ISSUE THREAD

**Issue by achilsh** [astaxie/beego#3893]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
          go version go1.13.5 linux/amd64
           beego v1.12.0

2. What operating system and processor architecture are you using (`go env`)?
     goarch =amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
-   I use go.mod manage my project, and go build my src.  error result happen like this:

github.com/astaxie/beego/logs/es
# github.com/astaxie/beego/logs/es
/root/go/pkg/mod/github.com/astaxie/beego@v1.12.0/logs/es/es.go:24:2: undefined: goes.Client

and my go.mod file content like this:

module demoTest

go 1.13

require (
	github.com/Masterminds/goutils v1.1.0
	github.com/Masterminds/semver v1.5.0
	github.com/Masterminds/sprig v2.22.0+incompatible // indirect
	github.com/OwnLocal/goes v1.0.0
	github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
	github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d
	github.com/araddon/gou v0.0.0-20190110011759-c797efecbb61
	github.com/astaxie/beego v1.12.0
	github.com/aws/aws-sdk-go v1.26.5
	github.com/cespare/xxhash v1.1.0
	github.com/edwingeng/doublejump v0.0.0-20190102103700-461a0155c7be // indirect
	github.com/go-kit/kit v0.9.0
	github.com/go-logfmt/logfmt v0.4.0
	github.com/go-sql-driver/mysql v1.4.1
	github.com/go-stack/stack v1.8.0 // indirect
	github.com/golang/protobuf v1.3.2
	github.com/google/uuid v1.1.1
	github.com/huandu/xstrings v1.2.1
	github.com/imdario/mergo v0.3.8
	github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
	github.com/juju/ratelimit v1.0.1 // indirect
	github.com/lytics/confl v0.0.0-20180527004241-9b876add7d3e
	github.com/mitchellh/copystructure v1.0.0
)

   

4. What did you expect to see?
      go build main.go can work succ.

5. What did you see instead?

**Comment by achilsh** [comment]
and i find OwnLocal in dir /root/go/pkg/mod/github.com. result is not exist. (/root/go is my gopath)

**Comment by br1ght3n** [comment]
Be attention to this dependency: github.com/OwnLocal/goes v1.0.0 ,it's not the right version which beego uses.Beego uses  the last commit version but go module uses the Tag:1.0.0.You can compare the file:github.com/OwnLocal/goes/structs.go between these two version.Just go get the right version like: go get github.com/OwnLocal/goes@d25b7ff8314bedc2cad40919e5158e22ba69d7c0

**Comment by flycash** [comment]
Now we fix the problem by using official client library.
