### ISSUE TITLE
Missing feature of Struct Embedding, Need architectural improvement

### ISSUE THREAD

**Issue by prakashsharmacs24** [astaxie/beego#3895]
1. What version of Go and beego are you using (`bee version`)?
Go: go1.13.4 linux/amd64
beego: VERSION = "1.12.0"
2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
I have two apps auth and payment
**models/auth/main.go**
```
package models

type User struct {
	Id      int64
	Name    string   `orm:"size(100)"`
	Profile *Profile `orm:"rel(one)"` // OneToOne relation
}

func (u *User) TableName() string {
	return "user"
}

type Profile struct {
	Id    int
	Age   int16
	Email string `orm:"size(100)"`
	User  *User  `orm:"reverse(one)"` // Reverse relationship (optional)
}
```

**models/payment/main.go**
```
`package models

import (
	auth "shop/models/auth"
)

type PaymentUser struct {
	auth.User//Struct Embedding
	StripeUserID string `orm:"size(100);column(stripe_uid)"`
	Token        *Token `orm:"rel(fk)"` 
}
func (u *PaymentUser) TableName() string {
	return "user"
}

type Token struct {
	Id   int
	Name string `orm:"size(100)"`
	Desc string `orm:"size(100)"`
}
`
```

4. What did you expect to see?
PaymentUser and User both should be linked.
In database, we should have only one table **user** with these fields:
 ```
 id integer NOT NULL DEFAULT nextval('user_id_seq'::regclass),
  name character varying(100) NOT NULL DEFAULT ''::character varying,
  profile_id integer NOT NULL,
  stripe_uid character varying(100) NOT NULL DEFAULT ''::character varying,
  token_id integer NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id),
  CONSTRAINT user_profile_id_key UNIQUE (profile_id)
```
Here stripe_uid and token_id are the part of **PaymentUser**

5. What did you see instead?
Due to same TableName, Getting error:
<orm.RegisterModel> table name `user` repeat register, must be unique.
I don't want to create a new table.
@astaxie , @Wusuluren please let me know if you need PR.
We only need to change two files:
models_boot.go:
https://github.com/astaxie/beego/blob/develop/orm/models_boot.go#L52
```
if _, ok := modelCache.getByFullName(name); ok {
ind := reflect.Indirect(val)
// ADD PaymentUser fields
addModelFields(mi, ind, "", []int{})
return
}
```
models_info_m.go:
https://github.com/astaxie/beego/blob/develop/orm/models_info_m.go#L82 
```
if !mi.fields.Add(fi) {
// In case PaymentUser fields continue the loop
continue
}
```

**Comment by Wusuluren** [comment]
the User  type don't need to implement TableName method
