### ISSUE TITLE
是否可以在不删除数据的前提下，更新表结构？

### ISSUE THREAD

**Issue by zhangjunjiebixin** [astaxie/beego#3899]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.12.10
beego1.12.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
通过orm.RunSyncdb("default", false, true)，修改表的字段长度

4. What did you expect to see?
修改某一个字段长度

5. What did you see instead?
table is existed,skip

**Comment by wmh404860242** [comment]
附议

**Comment by flycash** [comment]
这是一个复杂的问题……就是如果自己执行SQL修改语句，很简单；但是框架要支持这种东西，就很复杂了。但是我觉得这个可以作为一个插件功能来提供。

**Comment by flycash** [comment]
想来想去还是觉得，通过DBA会更加简单一点……我们目前不会提供这个功能，但是如果你们有谁愿意提供这个支持，我们可以提供帮助。
