### ISSUE TITLE
beego 框架中如何实现登录验证码的生成和校验

### ISSUE THREAD

**Issue by ruixule** [astaxie/beego#3901]
beego 框架中如何实现登录验证码的生成和校验，我查看了https://beego.me/quickstart并未找到该实例子 ，有实现的大神可告诉我下吗

**Comment by danvinhe** [comment]
这是业务的逻辑，简单来说就是 生成->存储->查询->校验

**Comment by 2017RXL** [comment]
> 这是业务的逻辑，简单来说就是 生成->存储->查询->校验

谢谢
