### ISSUE TITLE
orm 如何清空整张表数据，包括自增键置0

### ISSUE THREAD

**Issue by SyAtlantis** [astaxie/beego#3904]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by AllenX2018** [comment]
@flycash 我的想法是：用户调o.Delect（&md）；
1：没有任何附加条件情况下调用：query := fmt.Sprintf("truncate %s%s%s ", Q, mi.table, Q, )；
（清空表数据和重置PK）res, err = q.Exec(query)；
2：有限制条件情况下调用：query := fmt.Sprintf("DELETE FROM %s%s%s WHERE %s%s%s = ?", Q, mi.table, Q, Q, wheres, Q)
res, err = q.Exec(query, args...)

**Comment by AllenX2018** [comment]
@flycash 我的想法是：用户调o.Delect（&md）；
1：没有任何附加条件情况下调用：query := fmt.Sprintf("truncate %s%s%s ", Q, mi.table, Q, )；
（清空表数据和重置PK）res, err = q.Exec(query)；
2：有限制条件情况下调用：query := fmt.Sprintf("DELETE FROM %s%s%s WHERE %s%s%s = ?", Q, mi.table, Q, Q, wheres, Q)
res, err = q.Exec(query, args...)
是否可行?

**Comment by AllenX2018** [comment]
@flycash 我的想法是：用户调o.Delete（&md）；
1：没有任何附加条件情况下调用：query := fmt.Sprintf("truncate %s%s%s ", Q, mi.table, Q, )；
（清空表数据和重置PK）res, err = q.Exec(query)；
2：有限制条件情况下调用：query := fmt.Sprintf("DELETE FROM %s%s%s WHERE %s%s%s = ?", Q, mi.table, Q, Q, wheres, Q)
res, err = q.Exec(query, args...)
是否可行?

**Comment by flycash** [comment]
我觉得我们不需要提供这个功能。这种应该在线下通过DBA来完成。这个需求看起来就有点诡异。

**Comment by AllenX2018** [comment]
ok
