### ISSUE TITLE
使用注解路由如果路由发生更新能否在当前运行时生效

### ISSUE THREAD

**Issue by treeyh** [astaxie/beego#3908]
在使用注解路由的时候，如果路由发生了更新，在下一次启动的时候应该需要重新生成路由代码文件，能否在生成的运行时，同时使生成的路由策略生效。

**Comment by danvinhe** [comment]
1. 注解路由必须设置runmode = dev开发模式
2. 注解路由的项目必须在gopath目录下

**Comment by flycash** [comment]
这是一个安全策略。我们强制要求注解路由生成只能在dev模式下，是希望，运行时候的代码必然是经过充分测试的代码。即保证包的不可变性。
而在dev模式下，如果重新启动，就会重新生成。
