### ISSUE TITLE
orm不支持多段sql

### ISSUE THREAD

**Issue by TomLiu-GitHub** [astaxie/beego#3910]
![image](https://user-images.githubusercontent.com/32833966/72515676-448e2f80-388b-11ea-8747-eac383eae345.png)

**Comment by flycash** [comment]
求给个代码示例好复现问题~~

**Comment by jianzhiyao** [comment]
感谢支持！但此问题已太久远，暂时关闭此issue。
方便的话可以提供相关复现代码协助我们排查问题，我们也很乐意提供帮助。
