### ISSUE TITLE
[Proposal] 验证增加字段的label

### ISSUE THREAD

**Issue by liuzhang** [astaxie/beego#3912]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go1.13 & Beego 1.12.0

2. What operating system and processor architecture are you using (`go env`)?

windows

现在验证提示要想显示xxx 不能为空，必须手动自定义message， 一行一行写比较麻烦， 建议 增加 label

type AddTagForm struct {
	Id       string `form:"id" json:"id" valid:"Required;"`
	Name     string `form:"name" json:"name" valid:"Required;" label:"标签名称"`
}

error message 自动加上提示 “标签名称不能为空”

**Comment by guhan121** [comment]
现在的版本好像就是这样
```
	Sex string `valid:"Required;" label:"性别"`

```
2020/06/01 14:59:10 Sex.Required.性别 性别 Can not be empty
