### ISSUE TITLE
路由自动匹配是否可以区分http method ?

### ISSUE THREAD

**Issue by zyxun** [astaxie/beego#3913]
自动匹配很好用！
 后期会支持 post: user/login 路由到 func LoginPost() 吗

**Comment by flycash** [comment]
这应该算是一个语法糖，所以，这个需求本质上是希望通过遵循一定的规范命名来完成路由的匹配。目前来看，短期内不太会考虑。我强力推荐你使用我们的注解路由！很好用，谁用谁知道！
