### ISSUE TITLE
How to use Beego with React-router together?

### ISSUE THREAD

**Issue by hsluoyz** [astaxie/beego#3914]
My application is Beego + React. Beego will also serve the React static files.

React-router will handle routing for URLs in the front-end. So we need to have a "default route" for Beego. For example, all URLs starting with "/api" like "api/xxx" will go to Beego backend and all other URLs (like "/view", "/admin") should go through Beego and go into static files and let React-router serve it.

Of course I can implement such a functionality with a custom filter and determine whether a URL is starting with "/api" by myself. But I'm still looking for an elegant way to do this. For example, a default route, so any URL that doesn't match any other "/api" routes will go into this default route, and let Beego serve static files -- the entry point of React.

Any suggestion?

**Comment by flycash** [comment]
Beego REST API + node + React is a good solution.
But if you want to use beego serve react files, you need to build the react application and then copy the dist directory to beego static resource directory.

I think you won't want to do that. It's not a good practice.
