### ISSUE TITLE
Beego doesnt detect GOPATH

### ISSUE THREAD

**Issue by mamahnxarya201** [astaxie/beego#3915]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
> go version go1.13.4 linux/amd64
> bee v1.10.0

2. What operating system and processor architecture are you using (`go env`)?
> GOARCH="amd64"
> GOOS="linux"

3. What did you do?
iam creating new beego API project with command 

> bee api [name]

4. What did you expect to see?
a new project folder is created

5. What did you see instead?
![Screenshot_20200120_120220](https://user-images.githubusercontent.com/55610290/72700203-c200bb00-3b7d-11ea-99c2-51440f75416a.png)

and i already setup my GOPATH but bee doesnt detect it

![2020-01-20_12-14](https://user-images.githubusercontent.com/55610290/72700467-7d295400-3b7e-11ea-91b4-131c461e104b.png)

if iam missing someting? please let me know

**Comment by guhan121** [comment]
```
export GOPATH=/home/devel/go
```

**Comment by flycash** [comment]
Could you run follow commands in Terminal and then provide result?
```
export GOPATH=/path/to/your/go
bee version
```

**Comment by mamahnxarya201** [comment]
First of all sorry for my late reply and thank you for your response I can't reproduce or try the workaround since I don't have the machines anymore so should I close it? or let it open?

**Comment by flycash** [comment]
I closed it. And if you find it again, you can reopen this issue. 😄
