### ISSUE TITLE
请问我想要将多个model保存在不同的数据库中,怎么样注册

### ISSUE THREAD

**Issue by chenjzcj** [astaxie/beego#3916]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by qiujiahong** [comment]
RegisterDataBase的时候可以注册多个数据库

**Comment by chenjzcj** [comment]
> RegisterDataBase的时候可以注册多个数据库

但是我要怎么指定A Model保存在数据库A,B Model保存在数据库B呢?

**Comment by AllenX2018** [comment]
@chenjzcj 
Using
切换为其他数据库

orm.RegisterDataBase("db1", "mysql", "root:root@/orm_db2?charset=utf8")
orm.RegisterDataBase("db2", "sqlite3", "data.db")

o1 := orm.NewOrm()
o1.Using("db1")

o2 := orm.NewOrm()
o2.Using("db2")

**Comment by flycash** [comment]
我们暂时不支持这个功能。目前来说，我们认为model是和DB无关的。你会在什么场景之下需要这样隔离呢?

**Comment by flycash** [comment]
see #4105
