### ISSUE TITLE
请问我要跨数据库联查应该怎么做？

### ISSUE THREAD

**Issue by chenlixiang0430** [astaxie/beego#3925]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
不支持……跨数据库查询的话，你可能需要的是分库分表的中间件。
