### ISSUE TITLE
Orm可以通过关联实现递归查询吗？

### ISSUE THREAD

**Issue by funjobs** [astaxie/beego#3926]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
什么叫做通过关联实现递归查询？

**Comment by jianzhiyao** [comment]
个人理解：你说的意思类似是省市区放到一张表里面递归一棵树出来吗？
这种业务强相关逻辑，逻辑也不复杂，暂时不考虑放到框架内。

此issue暂时关闭，如果有问题欢迎提出，我们也很乐意为你提供帮助。
