### ISSUE TITLE
beego 现在支持 go module 不？

### ISSUE THREAD

**Issue by iziyang** [astaxie/beego#3935]
安装 bee 工具不成功，另外看问题列表里似乎 bee 工具有些功能不能用？所以使用 beego 的话只能用 GOPATH？

**Comment by jiftle** [comment]
安装bee工具时，关闭GO111MODULE=off。开发时可以使用go mod，当时工程需要在GO PATH /src目录下

**Comment by gxin0426** [comment]
我一般都是先生成项目 然后换个目录 再用go mod命令 不方便

**Comment by flycash** [comment]
beego目前是支持go mod。
