### ISSUE TITLE
文档需修正

### ISSUE THREAD

**Issue by dem0ns** [astaxie/beego#3939]
https://beego.me/docs/mvc/controller/xsrf.md

其中”Usage in javascript“的代码，```callback(eval("(" + response + ")"));```，使用eval函数存在安全风险。

注：使用XSRF口令本来属于安全防护，结果给的示例代码存在安全风险，建议修正！

**Comment by liuhaogui** [comment]
去除`eval`,避免歧义。
[https://github.com/beego/beedoc/pull/850](https://github.com/beego/beedoc/pull/850)
