### ISSUE TITLE
GetSection panic when use json as config file

### ISSUE THREAD

**Issue by qyyouming** [astaxie/beego#3940]
beego version：1.12.1

/ GetSection returns map for the given section
func (c *JSONConfigContainer) GetSection(section string) (map[string]string, error) {
	if v, ok := c.data[section]; ok {
		return v.(map[string]string), nil 
	}
	return nil, errors.New("nonexist section " + section)
}

v.(map[string]string) panic

**Comment by flycash** [comment]
你使用的配置是什么？

**Comment by flycash** [comment]
We will reopen it if needed
