### ISSUE TITLE
beego删除注解路由，第一次重启工程会发生panic

### ISSUE THREAD

**Issue by gofavor** [astaxie/beego#3946]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
F:\workspace\src\container>bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.0

├── Beego     : 1.12.1
├── GoVersion : go1.9.2
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : F:\workspace
├── GOROOT    : D:\Go
├── Compiler  : gc
└── Date      : Wednesday, 11 Mar `2020`
```

2. What operating system and processor architecture are you using (`go env`)?
```
F:\workspace\src\container>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\workspace
set GORACE=
set GOROOT=D:\Go
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
在dev模式下，使用beego注解路由的时候，删除controller里面的一个注解路由，**第一次重启**beego工程，会发生以下panic，其中Test方法是被删除的注解路由。
```
2020/03/11 09:51:24.165 [I] [parser.go:112]  generate router from comments
panic: 'Test' method doesn't exist in the controller LoginController

goroutine 1 [running]:
github.com/astaxie/beego.(*ControllerRegister).addWithMethodParams(0xc0420ac4d0, 0xb91f68, 0x11, 0xf4a2a0, 0xc042094000, 0x0, 0x0, 0x0, 0xc042575a38, 0x1, ...)
	F:/workspace/src/github.com/astaxie/beego/router.go:178 +0x941
github.com/astaxie/beego.(*ControllerRegister).Include(0xc0420ac4d0, 0xc042575f00, 0x2, 0x2)
	F:/workspace/src/github.com/astaxie/beego/router.go:285 +0x2b1
github.com/astaxie/beego.Include(0xc042575f00, 0x2, 0x2, 0xc042179560)
	F:/workspace/src/github.com/astaxie/beego/app.go:369 +0x55
container/routers.init.1()
	F:/workspace/src/container/routers/router.go:13 +0x155
container/routers.init()
	<autogenerated>:1 +0x5f
main.init()
	<autogenerated>:1 +0x59
```

看源码分析了一下，导致这个问题的原因是：
github.com/astaxie/beego/router.go文件中：
```
for _, c := range cList {
		reflectVal := reflect.ValueOf(c)
		t := reflect.Indirect(reflectVal).Type()
		key := t.PkgPath() + ":" + t.Name()
		if comm, ok := GlobalControllerRouter[key]; ok {
			for _, a := range comm {
				for _, f := range a.Filters {
					p.InsertFilter(f.Pattern, f.Pos, f.Filter, f.ReturnOnOutput, f.ResetParams)
				}

				p.addWithMethodParams(a.Router, c, a.MethodParams, strings.Join(a.AllowHTTPMethods, ",")+":"+a.Method)
			}
		}
	}
```
代码中要从GlobalControllerRouter中取出所有的注解路由，为其添加参数addWithMethodParams。
而GlobalControllerRouter这个map是从commentsRouter_.go文件中init()方法初始化的，而这个commentsRouter_.go文件是beego工程自动生成的注解路由文件。
```
beego.GlobalControllerRouter["container/controllers:LoginController"] = append(beego.GlobalControllerRouter["container/controllers:LoginController"],
        beego.ControllerComments{
            Method: "Login",
            Router: `/manage/user/login`,
            AllowHTTPMethods: []string{"GET","POST"},
            MethodParams: param.Make(),
            Filters: nil,
            Params: nil})
```
因此问题就出现了：
当删除controller里面的一个注解路由时，第一次重启工程时，由于commentsRouter_.go文件里面的注解路由信息还没有更新，里面还包含被删除路由的信息，因此被删除的路由就会初始化到GlobalControllerRouter中，上面又从GlobalControllerRouter中取出路由添加参数，因此会发生panic，而第二次再重启时，由于commentsRouter_.go已经更新，就不会有问题了。

出现这个问题的根本原因，在于golang同一个package中，有多个init()方法，这些init()方法的执行顺序问题。beego工程会自动在routes目录下生成一个commentsRouter_.go文件（文件就是用于初始化GlobalControllerRouter的）：
![image](https://user-images.githubusercontent.com/62041640/76375000-b365a180-637f-11ea-905a-156d0f3910e4.png)
上面两个文件中都有init()方法，golang在执行的过程中，由于commentsRouter_.go文件名的排序顺序在router.go文件前，因此会先运行commentsRouter_.go文件中init()方法，从而导致上面的问题。

假如说让router.go文件中的init()方法先运行，而commentsRouter_.go又是根据router.go里面注册controller生成的，这样commentsRouter_.go里面的注解路由就是最新的，在初始化GlobalControllerRouter的时候，GlobalControllerRouter里面保存的就是最新的路由，就不会导致上面的问题了。

因此解决上面的问题，只需要让beego生成的路由文件commentsRouter_.go，让这个文件名称的排序，排在router.go文件之后，也就是说让router.go文件中的init()方法先运行就可以了。

同上面一样，使用注解路由时，在controller里面添加一个注解路由，第一次重启beego工程时，访问该路由，会报404，其原因也是上面分析的问题导致的。

4. What did you expect to see?

5. What did you see instead?

**Comment by AllenX2018** [comment]
> 假如说让router.go文件中的init()方法先运行，而commentsRouter_.go又是根据router.go里面注册controller生成的，这样commentsRouter_.go里面的注解路由就是最新的，在初始化GlobalControllerRouter的时候，GlobalControllerRouter里面保存的就是最新的路由，就不会导致上面的问题了。

按我的理解，这个分析还是有问题的。即使router.go中的init()先执行，它只是重新生成新的commentsRouter_.go。但是这个时候已经是运行时了，老的commentsRouter_.go中的init()函数都已经加载了。如果不重新编译重启工程，怎么都不会执行新生成的init()函数的。

如果有错误，欢迎指出。
