### ISSUE TITLE
How to specify path param in beego router

### ISSUE THREAD

**Issue by omhingmire** [astaxie/beego#3947]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?  stable v1.10.0

2. What operating system and processor architecture are you using (`go env`)?  RHEL Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I've just started with Go and I'm using beego + react for my project. Here are the steps used to run the application.

1.  npm run build to build the React app. 
2. Specifying the build directory for ViewPath in beego app.conf 
3. Adding static path with beego.SetStaticPath("/static", "build/static") 
4. Creating a go binary and starting it. The issue I'm facing is that, if I specify path like /test then the page refresh works fine however if I specify /test/:id then the redirection with link works but when I refresh the page it fails to load. The error on the browser shows that on refresh it's trying to load resources from /test/static instead of /static. Here is the sample code for react router.

```
 .
      .
      .
      <Switch>
                <Route path="/" render={() => <Redirect to="/login" />} exact></Route>
                <Route path="/login" component={Login} />
                <Route path="/test" component={TestComponent} />
                <Route path="/test/:id" component={TestIdComponent} />
      </Switch>
      .
      .
```

And here's the code snippet for beego

```

func init() {
    beego.SetStaticPath("/static", "build/static")
    beego.Router("/", &controllers.MainController{})
    beego.Router("/login", &controllers.MainController{})
    beego.Router("/test", &controllers.MainController{})
    // this doesn't work, gives 404 on reload
    beego.Router("/test/:id", &controllers.MainController{})

    // these are API paths to get/post the data with axios
    beego.Router("/api/v1/login", &controllers.LoginController{})
    beego.Router("/api/v1/testData", &controllers.TestController{})

}
.
.
.

// and Main Controller

package controllers

import (
    "github.com/astaxie/beego"
)

type MainController struct {
    beego.Controller
}

func (c *MainController) Get() {
    c.TplName = "index.html"
}

```

4. What did you expect to see?

What I expect is when we reload a page with different paths on client like /test or /test/abc then the page should load normally.

5. What did you see instead?

Reload page fails.

**Comment by omhingmire** [comment]
Can anyone guide here?

**Comment by guhan121** [comment]
https://beego.me/docs/quickstart/view.md

**Comment by flycash** [comment]
I close this since I think the document shows the resolution.
