### ISSUE TITLE
beego orm不支持字段为 中文 默认值

### ISSUE THREAD

**Issue by qshuai** [astaxie/beego#3948]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
按照道理来说，中文默认值和英文默认值只是编码方式不同，应该都是支持的。除非是程序的编码，或者数据库的编码不支持中文，才有可能出现中文的默认值不被支持。
你可以提供简单的例子再现这个问题吗？

**Comment by flycash** [comment]
Please follow #4090. I will close similar issue.
