### ISSUE TITLE
Cannot get RouterPattern in BeforeExec filter

### ISSUE THREAD

**Issue by gorexlv** [astaxie/beego#3949]
4. What did you expect to see?

Some filters may want to access the RouterPattern, but now the `ctx.SetData("RouterPattern", routerInfo)` is executed after `BeforeExec`. So that we expect to move this statement to be before `BeforeExec` executed.

**Comment by gorexlv** [comment]
@astaxie Hi, 一些限流或者监控的过滤器需要获取RouterPattern，以便实现统计或者拦截功能。但是ctx.SetData("RouterPattern", routerInfo) 是在BeforeExec之后的，也就是说我在BeforeRouter, BeforeExec等filter里无法取到RouterPattern。这个能否优化一下，将ctx.SetData("RouterPattern", routerInfo) 提到BeforeExec之前？

**Comment by flycash** [comment]
如果你有兴趣，你可以提一个PR :)
