### ISSUE TITLE
Use session as the login judgment. The browser session does not expire for a period of time but you need to login again.

### ISSUE THREAD

**Issue by lyb-Q** [astaxie/beego#3951]
#### conf/app.conf

```code
sessionon = true
sessionprovider = redis
sessionproviderconfig = "xxx"
sessiongcmaxlifetime = 31536000
sessioncookielifetime = 31536000

```

**Comment by flycash** [comment]
Could you provide some codes to reproduce this problem? I cannot understand the problem from this simple descrption.

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by flycash** [comment]
@gdhameeja Thank you! Now we are working on v2.0.x. And we copy session to pkg/session. We want to remove session in future. So please checkout new branch from develop-2.0 and put your changes in pkg/session.

**Comment by flycash** [comment]
No further information, I closed it
