### ISSUE TITLE
grace 热更新模块

### ISSUE THREAD

**Issue by woshihaomei** [astaxie/beego#3957]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12.0

2. What operating system and processor architecture are you using (`go env`)?
win10

大佬，我发现grace热更新模块 启动的新进程 但是就进程 会一直在运行（虽然不接收请求了），这样是不是老进程还是会浪费系统资源。不知道是不是我什么地方用得不对？

**Comment by SandKing123** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What version of Go and beego are you using (`bee version`)?
>    1.12.0
> 2. What operating system and processor architecture are you using (`go env`)?
>    win10
> 
> 大佬，我发现grace热更新模块 启动的新进程 但是就进程 会一直在运行（虽然不接收请求了），这样是不是老进程还是会浪费系统资源。不知道是不是我什么地方用得不对？

我也遇到同样的问题，这个bug有解决掉么.

go version go1.13.1 linux/amd64

**Comment by flycash** [comment]
我们热更新的机制是，原进程启动一个新进程，而后新进程使用老进程打开的资源。我们并不能关掉原本的进程，因为这些进程是父子关系。老进程留着会消耗一定的资源，这些资源可以理解为是维系一个进程存在所必须的进程。你可以通过linux的命令来找到这个老进程消耗的内存，CPU使用等信息。

**Comment by flycash** [comment]
@woshihaomei 目前我们关闭父进程是使用了SIGTERM信号量。所以在windows上是没有效果的。

**Comment by flycash** [comment]
@SandKing123 我试了一下，我这边都能关闭父进程。你使用的beego版本是哪个？
