### ISSUE TITLE
Beego Hangs when build with Go v1.14 and under heavy traffic

### ISSUE THREAD

**Issue by gadelkareem** [astaxie/beego#3958]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego v1.12.1
golang v1.14.1 
2. What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gadelkareem/Library/Caches/go-build"
GOENV="/Users/gadelkareem/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/gadelkareem/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

3. What did you do?
I am running a high traffic service built on Beego. Recently I build the binary using Golang 1.14.1 and it worked on the server for few mins then it hangs. No logs or response and the CPU is 100 for the program.
It runs normally again after a restart but only for few mins then gets stuck again.

I think using Golang v1.13 should fix it ~but I am still testing...~ tested and working fine with 1.13

**Comment by guhan121** [comment]
So, problem solved?

**Comment by gadelkareem** [comment]
Not with Golang v1.14 so the problem still exists

**Comment by flycash** [comment]
Could you find out which codes make it hangs? I think there may be some deadlock.

**Comment by flycash** [comment]
No feedback for a long time. I closed it.
