### ISSUE TITLE
GetString获取方法页面参数区分大小写

### ISSUE THREAD

**Issue by zsy619** [astaxie/beego#3960]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
github.com/astaxie/beego v1.12.1

2. What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/zsy/Library/Caches/go-build"
GOENV="/Users/zsy/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

3. What did you do?
use GetString Parameter names are case sensitive

4. What did you expect to see?
Parameter names should not be case sensitive

5. What did you see instead?

**Comment by zsy619** [comment]
如果走如下分支：
![image](https://user-images.githubusercontent.com/6278792/77891202-32753800-72a3-11ea-97ee-f73390f7d7f6.png)
则还要修订go源码类库，如下图：
![image](https://user-images.githubusercontent.com/6278792/77891303-55075100-72a3-11ea-9a44-42063cd2e7b0.png)

**Comment by zsy619** [comment]
官网
![image](https://user-images.githubusercontent.com/6278792/77893024-fb545600-72a5-11ea-95c5-8d6fc1504e7a.png)
注释里面是区分大小写的，针对url里面的key、value是不应该区分大小写的吧
@astaxie

**Comment by snippet0809** [comment]
> 官网
> ![image](https://user-images.githubusercontent.com/6278792/77893024-fb545600-72a5-11ea-95c5-8d6fc1504e7a.png)
> 注释里面是区分大小写的，针对url里面的key、value是不应该区分大小写的吧
> @astaxie

Values map代表性的使用在qeruy参数和表单参数中，不像在http.Header map中那样，Values map中的key值是大小写敏感的
