### ISSUE TITLE
beego的ParseForm无法获取前端传输的Blob数据

### ISSUE THREAD

**Issue by xll970211** [astaxie/beego#3964]
$ go version
go version go1.13.4 windows/amd64

$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

beego中通过ParseForm获取表单中的数据，其他变量都是可以获取，但是data无法获取，打印为空
![image](https://user-images.githubusercontent.com/43258690/78997664-963c1280-7b79-11ea-888f-af6611573f7d.png)
前端的js部分代码
![image](https://user-images.githubusercontent.com/43258690/78997686-9fc57a80-7b79-11ea-845a-0198e03e61aa.png)
浏览器中查看Formdata的数据
![image](https://user-images.githubusercontent.com/43258690/78997720-ad7b0000-7b79-11ea-8485-084141070921.png)

我是上传大文件，想在后端进行拼接，这样不用一次性传一个很大的文件。但是现在获取不到文件的信息，无法进行下去，在这里卡了很久，十分感谢能帮助我的人，我是一个运维，刚接触go不是很久，希望解答的大神能说的简浅一点，十分感谢大家的帮助，谢谢

**Comment by Paxa** [comment]
What is a problem? May be I can help

**Comment by xll970211** [comment]
> What is a problem? May be I can help

thank you, I found a solution。I pass the handle of the file through Ajax, and the back-end can get the BLOB data through beego  c.GetString() method
