### ISSUE TITLE
Is there a way to generate Swagger API document for UI project of beego.

### ISSUE THREAD

**Issue by omhingmire** [astaxie/beego#3965]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)? Latest

2. What operating system and processor architecture are you using (`go env`)? Linux

3. What did you do? 
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see? NA

5. What did you see instead?  NA

Hi ,
I am using beego for one of the web project based on React. beego server serves all the static pages of react. In beego I have multiple APIs written which React UI uses. But I dont have any models or ORM in place in beego. My APIs in beego just calls other endpoint and gets the data. My router looks like :

```
beego.Router("/api/v1/passwordCheck", &controllers.PasswordCheck{})
beego.Router("/api/v1/version", &controllers.VersionController{})
beego.Router("/api/v1/getClusterCPUUsage", &controllers.CPUUsageController{})
beego.Router("/api/v1/getClusterPVCs", &controllers.OCPClusterPVCController{})
```
and controllers just calls REST calls. Is there a way to generate a Swagger API document for this type of project?

**Comment by zillani** [comment]
Simple, you just need to add annotations to the methods inside the controllers you have mentioned. (PasswordCheck, VersionController etc..)

**Comment by flycash** [comment]
if you can read Chinese, please refer https://beego.me/docs/advantage/docs.md
