### ISSUE TITLE
用StructTag数据验证可以输出中文错误吗？或者自定义错误？

### ISSUE THREAD

**Issue by ZJXAWC** [astaxie/beego#3966]
用StructTag数据验证可以输出中文错误吗？或者自定义错误？

**Comment by guhan121** [comment]
![image](https://user-images.githubusercontent.com/5517369/85374717-c0da1c80-b567-11ea-93ec-71d65cb19b79.png)
你想要的是这个么？

**Comment by flycash** [comment]
关键在于调用`SetDefaultMsg`
