### ISSUE TITLE
如何实现版本打印？

### ISSUE THREAD

**Issue by timchenxiaoyu** [astaxie/beego#3967]
对应一个beego程序如何实现
./hello --version
从而能够实现打印当前git的tag

**Comment by guhan121** [comment]
构建的时候把 tag 传进去

**Comment by guhan121** [comment]
https://colobu.com/2016/04/06/golang-auto-build-versioning/

**Comment by timchenxiaoyu** [comment]
原生的go肯定可以，但beego项目怎么搞

**Comment by guhan121** [comment]
一样的啊  打包的时候打包进去就是了

**Comment by timchenxiaoyu** [comment]
你测试过吗？bee run停不下来的

**Comment by guhan121** [comment]
https://github.com/guhan121/bee/tree/gomod
我加了命令你可以试一下

`bee run -ldflags "-X main.buildstamp=`date '+%Y-%m-%d_%I:%M:%S'` -X main.githash=`git rev-parse HEAD`"
`

**Comment by flycash** [comment]
参考 scripts/gobuild.sh

**Comment by flycash** [comment]
如果你使用了gobuild.sh来编译，并且启动了admin, 那么你能够通过Prometheus的端口来查看，比如本地是localhost:8088/metrics，搜索build_info
