### ISSUE TITLE
Swagger auth is not generated in request header

### ISSUE THREAD

**Issue by yangmingbai** [astaxie/beego#3968]
![1586772917(1)](https://user-images.githubusercontent.com/51049448/79113131-c3bfd080-7db2-11ea-870d-7bdc12a2e7a7.png)
hello:
I added a comment to the router like this:
`@SecurityDefinition token apiKey Authorization header`

 also configured  Authorization  on the swagger page
However, no Authorization  is generated in the header of the request 
` curl -X GET "http://...../...../v1/home/" -H  "accept: application/json"`

**Comment by autsakorn** [comment]
Can you try?
@SecurityDefinition apiKeyName apiKey Authorization header token

Also you need to add apiKeyName to the configured at controller, Example

`// Post adds a new category
// @Title Post
// @Description create Category
// @Param	body		body 	types.InputAddCategory	true		"body for Category content"
// @Success 201 {int}
// @Failure 400 {message: "string"}
// @router / [post]
// @Security apiKeyName
`

**Comment by yangmingbai** [comment]
add apiKeyName to the configured at controller,
it's ok ! thank you
