### ISSUE TITLE
logs/conn.go

### ISSUE THREAD

**Issue by souliot** [astaxie/beego#3971]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go:1.14
bee:v1.10.0
beego:v1.12.1

2. What operating system and processor architecture are you using (`go env`)?
linux_amd64

3. What did you do?
```golang
logs.Async()
logs.SetPrefix("test")
logs.SetLogger(logs.AdapterConn, `{"net":"tcp","reconnect":true,"level":6,"addr":":6002"}`)
```
I set the reconnect to be true,but it seems not useful.  
And I see the source code in logs/conn.go, it does nothing when reconnect is true.

4. What did you expect to see?

5. What did you see instead?

**Comment by gmelodie** [comment]
Hey! I could give this a go if that's ok :)
