### ISSUE TITLE
Sleep for a short time when httplib try to re-connect

### ISSUE THREAD

**Issue by tianhanfangyan** [astaxie/beego#3972]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

        // retries default value is 0, it will run once.
	// retries equal to -1, it will run forever until success
	// retries is setted, it will retries fixed times.
	for i := 0; b.setting.Retries == -1 || i <= b.setting.Retries; i++ {
		resp, err = client.Do(b.req)
		if err == nil {
			break
		}
                 time.sleep(b.setting.RetriesTimes)
	}

5. What did you see instead?

**Comment by gmelodie** [comment]
Hey there! Me and @IamCathal will be giving this a go if that's ok :)
