### ISSUE TITLE
beego 自动建表时不能忽略指定字段

### ISSUE THREAD

**Issue by Mrbuffoon** [astaxie/beego#3973]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.12.0
├── GoVersion : go1.12.9
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/gyq/project/go
├── GOROOT    : /usr/local/Cellar/go/1.12.9/libexec
├── Compiler  : gc
└── Date      : Monday, 20 Apr 2020

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gyq/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gyq/project/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.9/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sd/hw35tgv955d8s7dszn33bd6h0000gp/T/go-build541630559=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
定义如下结构体，自动建表时想忽略NewPwd字段，但是运行时提示：[ORM]2020/04/20 16:49:13 unsupport orm tag _ ，并且数据表中依然创建了这个字段。
type User struct {
	Id       int       `pk:"auto;column(id)";json:"id"`
	Name     string    `orm:"size(40);column(name);unique";json:"name"`
	NickName string    `orm:"size(40);column(nickname);default(admin)";json:"nickname"`
	Password string    `orm:"size(100);column(password);default(admin)";json:"password"`
	Date     time.Time `orm:"column(date);auto_now_add;null;type(date)";json:"date"`
	NewPwd   string    `orm:"_";json:"newpwd"`
}

**Comment by flycash** [comment]
you should use "-" rather than "_"
