### ISSUE TITLE
quick question in validator

### ISSUE THREAD

**Issue by wfystx** [astaxie/beego#3976]
I'm a beginner of Golang and have got a question when was reading the code of validator. 

```go
func (v *Validation) apply(chk Validator, obj interface{}) *Result {
	if nil == obj {
		if chk.IsSatisfied(obj) {
			return &Result{Ok: true}
		}
	} else if reflect.TypeOf(obj).Kind() == reflect.Ptr {
```

The first step here if `nil == obj` chk.IsSatisfied would be called, and the first step in IsSatisfied is this:

```go
func (r Required) IsSatisfied(obj interface{}) bool {
	if obj == nil {
		return false
	}
```

I'm wondering if `obj` is `nil`, will IsSatisfied ever return true here?

**Comment by guhan121** [comment]
`IsSatisfied` is a interface func, need to see its implementation.

**Comment by flycash** [comment]
As @guhan121 mentioned, there are many implemetations of `IsSatisfied` method.
