### ISSUE TITLE
beego框架连接阿里云的AnalyticDB数据报错！

### ISSUE THREAD

**Issue by wshcoding** [astaxie/beego#3978]
beego框架连接AnalyticDB数据报错panic: Error 1815: [15022, 2020042417233717201821601803151225972] statement type: class com.alibaba.fastsql.sql.ast.statement.SQLSelectStatement is NOT supported!  

连接地址：xxx:xxxxxx@tcp(am-xxx.ads.aliyuncs.com:3306)/xxx?charset=utf8&loc=Local&autocommit=true&interpolateParams=true

有解决办法吗？

**Comment by tianhanfangyan** [comment]
ADB你用什么那种实例了？

**Comment by flycash** [comment]
可以提供一下复现代码？包括你使用的配置，以及ADB的基本信息
