### ISSUE TITLE
Routing issues with modules

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [astaxie/beego#3979]
Please answer these questions before submitting your issue. Thanks!

1.  v1.12.1
2. amd64, windows
3.  
I am new in golang, correct me if I did something wrong. I had experience with other languages/API frameworks. 
I have been trying to create API project with bee, but I found that all new projects have to use the modules approach released in go 1.11. 
I used `bee api api-name` command to scaffold the new project. It appeared in GOPATH. I moved out it from GOPATH path to another directory. Then I did `go mod init mod` ,  then I was able to run `bee run` and API was successfully started but routing didn't work. I did some comparing and found out that `commentsRouter` file wasn't generated. 
I found a few similar issues here, it looks like this should have been fixed already but it still doesn't work for me. 
What am I do wrong?

I tried to do `set GO111MODULE=on` and then `go get -u github.com/beego/bee` but this wasn't helped as well. 
Now I can't even run bee API, I see 
` 0004 Failed to build the application: main.go:4:2: package api-name/routers is not in GOROOT (c:\go\src\api-name\routers)
`
What's happens? I am confused. Official go documentation says that I should prefer modules approach with new projects but I can't find somewhere in docs anything about how to scaffold and use bee with modules system. 
Thanks for any advice

**Comment by guhan121** [comment]
还不支持go module

要改beego的一点点代码

**Comment by flycash** [comment]
Now beego's routing doesn't work if the project is out of the GOPATH. We have tried to fix it but it still has some problems. Maybe you should create the project inside the GOPATH.
