### ISSUE TITLE
一个致命的内存泄漏BUG

### ISSUE THREAD

**Issue by zeropool** [astaxie/beego#3980]
我认为下面代码有潜在的问题

https://github.com/astaxie/beego/blob/8f3d1c5f42fce57e83e1c3f7d180477595db7cca/staticfile.go#L106-L139

- 缓存至少也要用LRU吧，也要限制数量与大小
- beego用于静态服务，文件小还行, 文件大就是个灾难
- 如果单文件过大，直接内存就OOM了
- 如果我随机模拟acceptEncoding, 一小时不到就能DDOS掉一个用beego的服务器

https://github.com/astaxie/beego/issues/1980

这是个老问题，不知道作者为什么非得拒绝这是个BUG

**Comment by jianzhiyao** [comment]
Hahaaa，talk is cheap , show me the code

**Comment by zeropool** [comment]
开启gzip压缩后而且当前文件支持压缩， 用python写个http请求，随机Accept-Encoding的值会导致staticFileMap一直塞满内存OOM




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jianzhiyao"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 下午3:11
收件人: "astaxie/beego"<beego@noreply.github.com&gt;; 
抄送: "Zero"<1285055670@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [astaxie/beego] 一个致命的内存泄漏BUG (#3980)





 
Hahaaa，talk is cheap , show me the code

**Comment by jianzhiyao** [comment]
已提出优化pr https://github.com/astaxie/beego/pull/3984
