### ISSUE TITLE
把错误吐出来

### ISSUE THREAD

**Issue by zuzuviewer** [astaxie/beego#3988]
用了beego的session，发现很多地方beego库把错误吞掉了，让我们找问题找了好一阵，这不是一个好的处理方式。希望用在产品里的一个库还是把错误吐出来，让上层逻辑处理

**Comment by flycash** [comment]
好建议。
已有的代码可能不太好改，我们会尝试一下。因为困难是，修改public方法的返回参数，可能导致一些用户的代码不可用。如果原本公共方法就返回了error，那我们可以考虑将内部实现的并且原本被吞掉的具体error返回出来。
