### ISSUE TITLE
Comments_controllers..... is not updated 

### ISSUE THREAD

**Issue by publicocean0** [astaxie/beego#3989]
├── Beego     : 1.12.1
├── GoVersion : go1.14
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /data/develop/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Tuesday, 12 May 2020

Comments are not update correctly. 
I seems to be a lock inside took. Sometimes works , sometimes no. Normally it is not working if you open the page fastly after you launched bee run . In other moments it is completely not working

**Comment by flycash** [comment]
What do you mean?
