### ISSUE TITLE
Flash messages - Can't display HTML in them

### ISSUE THREAD

**Issue by IvRRimum** [astaxie/beego#3990]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.14.2

2. What operating system and processor architecture are you using (`go env`)?
OSX catalina

3. What did you do?
Just do a basic flash message, and try to display it in template. It doesn't render HTML!

4. What did you expect to see?
A flash message with HTML in it!

5. What did you see instead?
A escaped HTML

**Comment by guhan121** [comment]
i think you need https://beego.me/docs/mvc/controller/flash.md

you can give some codes for this issue?
