### ISSUE TITLE
beego的log日志如何在不修改源码包的情况下自定义[D][I][W][E]这些错误等级前缀

### ISSUE THREAD

**Issue by yizhidaozuihou** [astaxie/beego#3997]
![image](https://user-images.githubusercontent.com/13058420/82281776-c66ea080-99c4-11ea-91d0-30b427264998.png)
不太喜欢这种大写的错误等级[D][I][W][E]，想自定义改成类似[Info][Error]之类的，但是看了官方没提供参数，自己看了源码需要修改源码的定义参数才行，有木有其他方法可以不修改源码的情况下实现俺要的效果的？

**Comment by flycash** [comment]
我感觉这是一个很小众的需求，并且是个人偏好的问题。如果你能提供PR来支持这种自定义，我们将表示非常欢迎。

我个人不太建议投入精力去实现。

**Comment by flycash** [comment]
https://github.com/astaxie/beego/blob/develop/logs/README.md
`md
log.Trace("trace")
log.Info("info")
log.Warn("warning")
log.Debug("debug")
log.Critical("critical")
`
