### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by emmeair** [astaxie/beego#4000]
`func SetDefaultMessage(msg map[string]string) {
	if len(msg) == 0 {
		return
	}

	for name := range msg {
		MessageTmpls[name] = msg[name]
	}
}
`
验证器设置回复信息这里map的写没加锁确定可以用？
项目实测报错：concurrent map writes

**Comment by guhan121** [comment]
是时候上 `sync.Map`

**Comment by flycash** [comment]
> 是时候上 `sync.Map`

是时候来个PR了，怎样？

**Comment by flycash** [comment]
可以提供一个简单的例子，复现这个bug么？

**Comment by guhan121** [comment]
@flycash 你们复活了  准备1.12.2了么

**Comment by guhan121** [comment]
@emmeair 能给个例子看看怎么出错么，我本机测了一下没法重现，看代码确实会出现你生活的协程冲突问题。

**Comment by flycash** [comment]
> @flycash 你们复活了 准备1.12.2了么

是的，要来一起么？

**Comment by guhan121** [comment]
@flycash 可以啊  别干掉我的PR就可以了
