### ISSUE TITLE
Empty field in validator.Error when label struct tag is not declared

### ISSUE THREAD

**Issue by Pc6** [astaxie/beego#4001]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version: 1.14
beego: 1.12.1

2. What operating system and processor architecture are you using (`go env`)?
windows

3. What did you do?
using validator but errors with empty field when validating failed.
It seems that the bug is caused when `label` struct tag is empty.

https://github.com/astaxie/beego/blob/8f3d1c5f42fce57e83e1c3f7d180477595db7cca/validation/validation.go#L272

What's more, there is no introduction about the new `label` tag, and tells me it's a must to declare it.

4. What did you expect to see?
When validating failed, non-empty field should be return no matter label is declared or not.

5. What did you see instead?
empty field in validator error

**Comment by guhan121** [comment]
you means:
if len(label) ==0 ,should print  `field name`

**Comment by guhan121** [comment]
you means:
```
	parts := strings.Split(key, ".")
	if len(parts) == 3 {
		Field = parts[0]
		Name = parts[1]
		Label = parts[2]
		if len(Label) == 0 {
			Label = Field
		}
	}

```

**Comment by Pc6** [comment]
@guhan121 yes.

**Comment by guhan121** [comment]
> @guhan121 yes.

replace github.com/astaxie/beego v1.12.1 => github.com/guhan121/beego v1.12.2-0.20200601070649-c2771397be67

**Comment by Pc6** [comment]
@guhan121 Got it. Thank you. I will have a try :)

**Comment by flycash** [comment]
So, @Pc6 does it work? If it works well, could @guhan121 issue a PR? That would be helpful
