### ISSUE TITLE
How to define the log file name and log msg pattern?

### ISSUE THREAD

**Issue by zhuayi** [astaxie/beego#4002]
We want to print some log like:
`|2018-09-07 11:22:44.023|INFO|ad0e1a90-f929-4948-82cd-1b2aa12e6966|...`

And how to make log file name looks like  XXXX.log.2020.06.01 ?

**Comment by flycash** [comment]
https://github.com/astaxie/beego/blob/develop/logs/README.md
你可以看看这个，不过我初略一看，貌似也不能解决你的问题。

**Comment by flycash** [comment]
如果没找到方案，我们非常欢迎你提PR，并且提供协助。:)

**Comment by Junjunya1995** [comment]
我的方案是， 复制了一份  beego log包的 日志logger文件， 然后改成 自己需要的功能。

比如 用文件日志的话，可以复制  日志包的 `file.go`,  然后改成自己的   `selffile.go`, 找到日志格式那块，然后改成自己需要的格式。
然后   `log.SetLogger("selffile", `{"filename":"test.log"}`)`

**Comment by JessonChan** [comment]
依赖golang log包的话，都无法完全定制

**Comment by flycash** [comment]
复制文件，只能算是临时方案。我觉得还是需要抽象一些API来，然后把当前的实现作为这些API的默认实现。而后允许用户扩展不同的实现。比如说，我们可以定义一个Format的顶级接口作为日志格式的顶级接口。
日志这一块我们其实想参考一下Gin，echo之类的框架，看能否提供更加丰富的自定义功能。
