### ISSUE TITLE
Using official elasticsearch client

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4008]
Beego use [goes](https://github.com/OwnLocal/goes/tree/v1.0.0) as ES client library since there is not any official library.

But now, the official library was provided: [go-elasticsearch](https://github.com/elastic/go-elasticsearch)

We are considering replacing goes with go-elasticsearch. 

For now, the ES is only used in logging, so the goals are:
1. replacing goes with go-elasticsearch;
2. Support ES v5.x, v6.x, v7.x;
3. Beego users can choose the ES version by providing some config

To fix CI problem, I had removed goes library and use ES v6.x official client. But it's a temporary solution. see #4006

**Comment by guhan121** [comment]
@flycash  PR has a bug

in `es.go` `LogDocument` must be blow.
```
type LogDocument struct {
	Timestamp string `json:"timestamp"`
	Msg       string `json:"msg"`
}

```

Otherwise, 
```
body, err := json.Marshal(idx)
	if err != nil {
		return err
	}
fmt.Println(`body:`,string(body))   // {}
```
nothing put to es-server

**Comment by guhan121** [comment]
![image](https://user-images.githubusercontent.com/5517369/85404472-8c7b5600-b591-11ea-9913-debe8483c97d.png)
感觉index自己设置比较好，不然的话岂不是每天都在变 @flycash

**Comment by flycash** [comment]
@lg1024

**Comment by flycash** [comment]
@741369
