### ISSUE TITLE
新版本可以增加对微服务功能的实现么

### ISSUE THREAD

**Issue by ayamzh** [astaxie/beego#4009]
如JSON RPC 服务、gRPC 服务、服务注册、服务熔断降级、限流、配置中心、调用链追踪、监控这些。
因为现在企业都引入微服务的设计理念，框架层面如果能提供这些服务的实现，或者客户端。能大大提高开发效率。可以参考PHP的SWOFT EASYSWOOLE之类的框架，都有相关的支持。成为了全栈框架。

**Comment by flycash** [comment]
它的问题在于，我们是提供适配层，以方便使用别的RPC框架，还是实现一个完整的RPC框架。如果是后者，这个工作量就非常可怕了。

**Comment by WenyXu** [comment]
> 它的问题在于，我们是提供适配层，以方便使用别的RPC框架，还是实现一个完整的RPC框架。如果是后者，这个工作量就非常可怕了。

我觉得可以参考 go-kit ，grpc 也好 http 也好，都只是 transport 层。服务熔断降级，限流，链路，监控拥抱 istio sidecar 模式也是很好的解决方案。

**Comment by deadly-poison** [comment]
直接用k8s生态什么都解决了

**Comment by flycash** [comment]
好消息是我们打算支持RPC，目前的计划是支持gRPC。我们下半年将会实现这个功能。
与此同时，我们也会积极拥抱云原生时代，不过这方面还没有非常具体的方案，只能说是一个意向。欢迎大家提proposal！！
也希望大家关注我们的重构计划 #4035
