### ISSUE TITLE
orm连接池通过 SetMaxOpenConns 设置最大连接数无效

### ISSUE THREAD

**Issue by insistent** [astaxie/beego#4011]
orm/db_alias.go:374

```
// SetMaxOpenConns Change the max open conns for *sql.DB, use specify database alias name
func SetMaxOpenConns(aliasName string, maxOpenConns int) {
	al := getDbAlias(aliasName)
	al.MaxOpenConns = maxOpenConns
	// for tip go 1.2
	if fun := reflect.ValueOf(al.DB).MethodByName("SetMaxOpenConns"); fun.IsValid() {
		fun.Call([]reflect.Value{reflect.ValueOf(maxOpenConns)})
	}
}
```

reflect.ValueOf(al.DB) ，通过反射al.DB的方法"SetMaxOpenConns"是错误的，因为al.DB是orm.alias struct 并非 sql.DB,没有实现 "SetMaxOpenConns"方法。
`fun := reflect.ValueOf(al.DB).MethodByName("SetMaxOpenConns"); `

应该修改为：
`fun := reflect.ValueOf(al.DB.DB).MethodByName("SetMaxOpenConns"); `

临时处理方法，直接获取sql.DB进行设置：
```
db, _ := orm.GetDB("default")

db.SetMaxIdleConns(maxIdle)
db.SetMaxOpenConns(maxConn)
db.SetConnMaxLifetime(time.Second * time.Duration(maxLifetime))
```

**Comment by flycash** [comment]
这里有一个PR #3985，已经合并过去develop，你可以看看，是否解决了你的问题。我看上去这是同一个问题。

**Comment by insistent** [comment]
> 这里有一个PR #3985，已经合并过去develop，你可以看看，是否解决了你的问题。我看上去这是同一个问题。

谢谢，确实是同一个问题
