### ISSUE TITLE
SetMaxOpenConns does not work for beego/orm, while it works for the native database/sql

### ISSUE THREAD

**Issue by yfhk** [astaxie/beego#4012]
Env:
$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.12.1
├── GoVersion : go1.14.2
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 6

Code which not work:

`
package main

import (
	"fmt"
	"sync"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

type User struct {
	Id   int
	Name string
	Age  int
}

func init() {
	orm.RegisterDataBase("default", "mysql", "root:123456@tcp(localhost:3306)/sqlx_db?charset=utf8mb4", 2, 2)
	orm.RegisterModel(new(User))
}

func insertData(o *orm.Ormer, wg *sync.WaitGroup) {
	user := new(User)
	user.Name = "slene"
	user.Age = 55

	fmt.Println((*o).Insert(user))
	wg.Add(-1)
}

func main() {
	orm.Debug = true
	orm.SetMaxOpenConns("default", 0)
	orm.SetMaxIdleConns("default", 2)
	orm.RunSyncdb("default", false, true)

	var wg sync.WaitGroup
	o := orm.NewOrm()
	o.Using("default")
	wg.Add(200)
	for i := 0; i < 200; i++ {
		go insertData(&o, &wg)
	}
	wg.Wait()
}

`

Errors show up:
[ORM]2020/06/11 09:41:49  -[Queries/default] - [FAIL /     db.Exec /    12.9ms] - [INSERT INTO `user` (`name`, `age`) VALUES (?, ?)] - `slene`, `55` - Error 1040: Too many connections
0 Error 1040: Too many connections
[ORM]2020/06/11 09:41:49  -[Queries/default] - [FAIL /     db.Exec /    12.9ms] - [INSERT INTO `user` (`name`, `age`) VALUES (?, ?)] - `slene`, `55` - Error 1040: Too many connections
0 Error 1040: Too many connections

However code below works( no "Error 1040: Too many connections" show up ):
`
package main

import (
	"database/sql"
	"fmt"
	"sync"

	_ "github.com/go-sql-driver/mysql"
)

type DbWorker struct {
	Dsn      string
	Db       *sql.DB
	UserInfo userTB
}
type userTB struct {
	Id   int
	Name sql.NullString
	Age  sql.NullInt64
}

func mainTest() {
	var err error
	var wg sync.WaitGroup
	dbw := DbWorker{
		Dsn: "root:123456@tcp(localhost:3306)/test_db?charset=utf8mb4",
	}
	dbw.Db, err = sql.Open("mysql", dbw.Dsn)
	dbw.Db.SetMaxOpenConns(1)
	if err != nil {
		panic(err)
		return
	}
	defer dbw.Db.Close()
	wg.Add(1000)
	for i := 0; i < 1000; i++ {
		go dbw.InsertData(&wg)
	}
	dbw.queryData()
	wg.Wait()
}

func (dbw *DbWorker) InsertData(wg *sync.WaitGroup) {
	stmt, _ := dbw.Db.Prepare(`INSERT INTO user (name, age) VALUES (?, ?)`)
	defer stmt.Close()

	ret, err := stmt.Exec("abc", 123)
	if err != nil {
		fmt.Printf("insert data error: %v\n", err)
		wg.Add(-1)
		return
	}
	if LastInsertId, err := ret.LastInsertId(); nil == err {
		fmt.Println("LastInsertId:", LastInsertId)
	}
	if RowsAffected, err := ret.RowsAffected(); nil == err {
		fmt.Println("RowsAffected:", RowsAffected)
	}
	wg.Add(-1)
}

func (dbw *DbWorker) QueryDataPre() {
	dbw.UserInfo = userTB{}
}
func (dbw *DbWorker) queryData() {
	stmt, _ := dbw.Db.Prepare(`SELECT * From user where age >= ? AND age < ?`)
	defer stmt.Close()

	dbw.QueryDataPre()

	rows, err := stmt.Query(20, 30)
	defer rows.Close()
	if err != nil {
		fmt.Printf("query data error: %v\n", err)
		return
	}
	for rows.Next() {
		rows.Scan(&dbw.UserInfo.Id, &dbw.UserInfo.Name, &dbw.UserInfo.Age)
		if err != nil {
			fmt.Printf(err.Error())
			continue
		}
		if !dbw.UserInfo.Name.Valid {
			dbw.UserInfo.Name.String = ""
		}
		if !dbw.UserInfo.Age.Valid {
			dbw.UserInfo.Age.Int64 = 0
		}
		fmt.Println("get data, id: ", dbw.UserInfo.Id, " name: ", dbw.UserInfo.Name.String, " age: ", int(dbw.UserInfo.Age.Int64))
	}

	err = rows.Err()
	if err != nil {
		fmt.Printf(err.Error())
	}
}

`

**Comment by yfhk** [comment]
@astaxie  thank you in advance

**Comment by flycash** [comment]
Here is an PR #3985 , it may resolve your problem, please take a look.
