### ISSUE TITLE
V2 RoadMap (Draft)

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4035]
**I think I made a mistake. If you can't read Chinese, we can discuss it in google doc.**

English: 

https://docs.google.com/document/d/1eA47QN3vkBS4fj7PZQJVBeYiSO73ceelzRSRiTc8Em4/edit?usp=sharing

Chinese:

# 版本维护计划
## 1.x 版本
我们将持续维护 1.x 版本。这种维护是指：
1. 如果用户提交了 PR，无论是修复 BUG 还是提供新的特性的支持，我们都会将其合并进来，并且在一段时间后发版本；
2. 某些影响重大的 BUG，我们会考虑自己修复。但是不提供任何新功能的支持；
当我们认为2.x版本已经足够稳定之后（通常意味着 2.1.0 版本发布），我们会彻底放弃维护这个版本。
## 2.0.x 版本 （暂定截止2020年底）
这一系列的版本可以看做是过渡版本，即从 1.x 过渡到 2.x 的版本。同时也可以看做我们持续重构的中间版本。在这些版本中，每完成一个部分的重构，我们就会发布一个小版本。
该版本还有一个特性，就是这个版本里面会有很多兼容性的代码，即为了兼容 1.x 版本的遗留代码。

**该版本的另外一个重要特性是，我们会新支持很多近两年出来的框架，特别是云相关的框架，以方便用户引领云原生时代浪潮。**

目前规划中的版本：
### 2.0.0
2.0.0 作为第一个重构的版本，它的主要任务在于：
1. 为后续的版本提供支持，如支持context.Context，重新设计web的中间件机制；
2. 增加对新的框架（中间件）的支持，以吸引用户逐步切换到v2版本。首要目标是完成对可观测性中间件的支持，即metrics和tracing两个方面的支持；
3. 设计模块化API。我们将这一次预备支持的metrics和tracing设计为一个可插拔的模块。

### 2.0.1
1. grpc支持，方案待确定；
2. 拆分日志组件。设计一套API作为统一的日志API（或者使用开源的API），而后将已有的日志组件作为默认实现，拆分成单独的项目。同时，提供主流日志框架的adapter实现，如zap。这部分将鼓励社区贡献对不同日志框架的适配；
3. 优化web路由。设计路由API，并且提供两种默认实现；一种是支持各种复杂匹配的，以易用性为主要目标的实现；一种是以性能为主要目标，支持复杂度有限的路由匹配；
4. 设计ORM API，将已有的ORM作为默认实现，提供对gorm的适配。

### 2.0.2-2.0.3
待定。逐步将所有的模块转化可插拔的模块。

### 2.0.4——拆分兼容性代码
在这个版本之前，我们会在Beego里面保留所有的兼容1.x的代码。而在这个版本之后，所有的兼容性代码都被拆分到了 Beego-1.x-adapter。
以上所有版本，都会穿插支持更多的中间件或者第三方库。这些新支持的东西，将不会提供 1.x 版本的兼容性代码。意味着，新功能 1.x 版本将完全无法使用。我们将通过这种做法，引导用户逐步切换到 2.x 版本。

## 2.1.x 版本
2.1.0 版本可以看做是完成重构之后的第一个大版本。这个版本我们将达成以下目标：
1. 完成了模块化的改造。这个阶段的产物有：
    - Beego 项目。作为用户主要使用的项目。它集成了各个模块的默认实现，可以做到开箱即用。
    - 各个模块。我们将各个模块都单独拆出去了，每个模块都含有一套标准 API，和多个默认实现。即便用户不选择使用 Beego，但是这些模块他们依旧可以拿去他自己的项目里面使用
    - Beego-1.x-adapter。实际上这个东西应该是 2.0.x 最后一个版本的产物，用户可以引入这个模块以兼容 1.x 版本。我们在 2.1.x 的时候还会保留一小段时间。
2. 完全的云原生支持，Beego 将具备构建基于 HTTP 协议或者 RPC 协议的大型系统的能力；

**Comment by runner-mei** [comment]
1. 考虑一下泛型对 web 框架的的影响。s
    如  Context 可以加上 泛型参数， 让用户可以在 Context 中添加自已业务相关的数据

2. 考虑一下像 revel 一样向控制器上的函数自动绑定参数
      首先我不是 revel 很好，但自已读参数很麻烦。
      revel 的自动绑定参数的方式很不好， 因为它像 magic，出错时不好调试。
      我认为你可以将这个功能做成可选的。然后借助一个工具生成中间读参数的代码。
      如 

    ````go
	// @http.GET(path="/test/:id/:b")
	Test(id int64, b int64) error
    ````
    生成下列代码
   ````go

	mux.Get("/test_query_args1/:id", func(ctx *beecontext.Context) {
		id, err := strconv.ParseInt(ctx.Input.Param("id"), 10, 64)
		if err != nil {
			ctx.Output.SetStatus(http.StatusBadRequest)
			ctx.WriteString(fmt.Errorf("argument %q is invalid - %q", id, ctx.Input.Param("id"), err).Error())
			return
		}

		b, err := strconv.ParseInt(ctx.Input.Param("b"), 10, 64)
		if err != nil {
			ctx.Output.SetStatus(http.StatusBadRequest)
			ctx.WriteString(fmt.Errorf("argument %q is invalid - %q", id, ctx.Input.Param("b"), err).Error())
			return
		}

                // svc 是一个控制器实例
		err = svc.Test(id, b)
		if err != nil {
			ctx.Output.SetStatus(httpCodeWith(err))
			ctx.WriteString(err.Error())
			return
		}
		ctx.Output.SetStatus(http.StatusOK)
		ctx.Output.JSON("OK", false, false)
		return
	})
   ````

**Comment by JessonChan** [comment]
可改进为，通过声明直接绑定。如上面的例子，完全可以以改成
```go
 mux.Get("/test/:id/:b", func(ctx *beecontext.Context) {
        // svc 是一个控制器实例，这个调用由框架完成，不需要手动实现
        // 如果绑定出错，则由框架进入出错流程
 	err = svc.Invoke("Test")
 	if err != nil {
 		ctx.Output.SetStatus(httpCodeWith(err))
 		ctx.WriteString(err.Error())
 		return
 	}
 	ctx.Output.SetStatus(http.StatusOK)
 	ctx.Output.JSON("OK", false, false)
 	return
 })
```

**Comment by lwx3i** [comment]
希望把go mod模式完美支持一下。
希望orm中，再加入一些常用的统计函数。
希望 Orm得到的返回值，能够直接返回某基础类型的数组。

**Comment by buexplain** [comment]
希望改善模板这块，大致实现如下效果：
**layout.html**
````html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>{{template "title" .}}</title>
    {{template "css" .}}
</head>
<body>
{{template "content" .}}
{{template "js" .}}
</body>
</html>
````
**index.html**
```html
{{define "extend"}}
    layout.html
{{end}}

{{define "title"}}
    {{.title}}
{{end}}

{{define "css"}}
    <link rel="stylesheet" type="text/css" href="">
{{end}}

{{define "content"}}
    {{.content}}
{{end}}

{{define "js"}}
    <script type="text/javascript">
        alert(1);
    </script>
{{end}}
```
**golang控制器**
```golang
w.With("title", "标题")
w.With("content", "内容")
w.View(http.StatusOK, "index.html")
```

**Comment by runner-mei** [comment]
@JessonChan 你的说法我不是很理解， 你是不是没有理我的意思

现在j 

我希望这样写控制器

  ````go

type MyController {}
func (this *MyController ) Test() {      
       /////////////////
       // 我不想写这块代码， 我希望框架帮我做
	id := this.Ctx.Input.Param(":id")
	intid, _ := strconv.ParseInt(id, 10, 64)
	b:= this.Ctx.Input.Param(":b")
	intb, _ := strconv.ParseInt(b, 10, 64)
       /////////////////

       // 我的业务代码

	this.ServeJSON()
}


我希望这样写控制器

  ````go
type MyController {}

   // @http.GET(path="/test/:id/:b")
  func (*MyController ) Test(id int64, b int64) error {
       // 我的业务代码
  }
  ````

  现在 revel 是这么做的， 但是做的不好， 我问题多， 我希望以代码生成的方式，帮我生成下列代码。

 ````go
mux.Get("/test/:id/:b", func(ctx *beecontext.Context) {
 	id, err := strconv.ParseInt(ctx.Input.Param("id"), 10, 64)
 	if err != nil {
 		ctx.Output.SetStatus(http.StatusBadRequest)
 		ctx.WriteString(fmt.Errorf("argument %q is invalid - %q", id, ctx.Input.Param("id"), err).Error())
 		return
 	}

 	b, err := strconv.ParseInt(ctx.Input.Param("b"), 10, 64)
 	if err != nil {
 		ctx.Output.SetStatus(http.StatusBadRequest)
 		ctx.WriteString(fmt.Errorf("argument %q is invalid - %q", id, ctx.Input.Param("b"), err).Error())
 		return
 	}

             // svc 是一个控制器实例
 	err = svc.Test(id, b)
 	if err != nil {
 		ctx.Output.SetStatus(httpCodeWith(err))
 		ctx.WriteString(err.Error())
 		return
 	}
 	ctx.Output.SetStatus(http.StatusOK)
 	ctx.Output.JSON("OK", false, false)
 	return
 })
 ````

为什么 revel 不好呢
   1. 不好扩展
   2. 出错不易调试
   3. 缺少可选， 必选之类的控制
 
我想是不是可以用类似于 Java 的 Annotation 技术再加上代码生成的方式避免它的缺点
这段生成的代码， 我想法是框架生成，在特定情况下时我手工写。

**Comment by runner-mei** [comment]
ORM 方面我希望可以自由的用任何 orm ， 因为现在 golang 没有一个好用的 orm, 现有的 orm 各有特点， 希望不要绑死某一个 orm.


orm 我喜欢类似 mybatis 风格的， 我有一个自已的  https://github.com/runner-mei/gobatis

**Comment by JessonChan** [comment]
@runner-mei 我赞成提供可选、必选的控制，不赞成自动生成代码，这种侵入式的方式会带来维护上的成本。
```go
type MyController {}

 // @http.GET(path="/test/:id/:b")
func (*MyController ) Test(id int64, b int64) error {
     // 我的业务代码
}
```
go本身并不支持注解，得借助编译工具才能理解这种写法。

**Comment by runner-mei** [comment]
@JessonChan 我只是提供一个想法， 也指出 revel 的缺点， 希望你们能避免，你有更好的方式当然好。

在没有泛型时提供可选、必选的控制， 那必须用 Annotation 
有泛型后可以有新选择，如下

type Option( T ) struct {
    value T
    InQuery bool 
    InBody  bool 
}

Test(id int64, b int64,  optArg  Option(int64)) error

这样我们就不侵入

**Comment by flycash** [comment]
Revel的这种方式挺好的，有点类似java的参数绑定机制。我觉得这可以考虑。具体如何设计，达成什么效果，我们后面可以进一步讨论。

**Comment by flycash** [comment]
> 1. 考虑一下泛型对 web 框架的的影响。

泛型的难点在于，不知道golang什么时候会真的推出。

**Comment by flycash** [comment]
> ORM 方面我希望可以自由的用任何 orm ， 因为现在 golang 没有一个好用的 orm, 现有的 orm 各有特点， 希望不要绑死某一个 orm.

我们会设计API并且提供主要的实现，例如基于gorm的实现。但是基于orm的实现，我们可能会鼓励社区提供。

另外一个在于，如果打算支持多种 orm 在一个项目里面混用，这恐怕是比较难的。

**Comment by JessonChan** [comment]
```go
package main

import "github.com/JessonChan/cango"

type Ctrl struct {
	cango.URI `value:"/hello"`
}

// 路由定义为 receiver中的URI tag和 参数列表中的 URI和tag的相加，
// 这个示例为 /hello/world.html
func (c *Ctrl) World(ps struct {
	cango.URI `value:"/world.html"`
}) interface{} {
	return cango.Content{String: "Hello,Cango!"}
}

func main() {
	cango.
		NewCan().
		Route(&Ctrl{}).
		Run()
}
```

> @JessonChan 我只是提供一个想法， 也指出 revel 的缺点， 希望你们能避免，你有更好的方式当然好。
> 
> 在没有泛型时提供可选、必选的控制， 那必须用 Annotation
> 有泛型后可以有新选择，如下
> 
> type Option( T ) struct {
> value T
> }
> 
> Test(id int64, b int64, optArg Option(int64)) error
> 
> 这样我们就不侵入了， 另外生成代码可以生成在一个独立的文件中， 它是不维护的， 随时可以重生成，在实际项目中甚至不将它放入源码管理中， 在 CI 上编译时重生成代码。

@runner-mei  go支持使用tag的写法，可以满足部分的场景，在我用的框架中有对应实现。
```go
func Ping(ps struct {
	cango.URI `value:"/ping/{year}/{car_age}/{Color}.json"`
	cango.PostMethod
	Year   int
	CarAge int
	Color  string
}) interface{} {
	return map[string]interface{}{
		"Pong":  "ok",
		"Year":  ps.Year,
		"Age":  ps.CarAge,
		"Color": ps.Color,
	}
}
```

**Comment by runner-mei** [comment]
@JessonChan  你的这个方法也挺好， 缺点是不干净， 有洁癖的人可能不喜欢。

**Comment by FelixSeptem** [comment]
graphql有计划支持吗？

**Comment by runner-mei** [comment]
@FelixSeptem 要考虑泛型的支持，不一定要做，  别想支持时有冲突

**Comment by zituocn** [comment]
希望新版本能走向企业化

**Comment by emenwin** [comment]
不知道这个问题有没有被提到：也是关于orm的

定义model的时候，专有单词ID、HTML，如果不手动制定orm的column name，table中的字段名会生成为i_d,h_t_m_l.

如果直接定义名称为Id，Html，会报lint警告。

希望优化

**Comment by 1032231418** [comment]
go mod 支持一下撒
