### ISSUE TITLE
Mobile的验证正则，可以更新不

### ISSUE THREAD

**Issue by ysp198910** [astaxie/beego#4037]
bee v1.10.0
├── Beego     : 1.12.1
├── GoVersion : go1.12.1
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\MyCode\GoLangLearn
├── GOROOT    : C:\MyServer\GoLang\v1.12.1
├── Compiler  : gc
└── Date      : Sunday, 28 Jun 2020

其 github.com/astaxie/beego/validation 类中的
Mobile 验证的正则是不是应该更新下了，
中国电信号段
133、bai149、153、du173、177、180、zhi181、189、199
中国联通号段
130、131、132、145、155、156、166、171、175、176、185、186、166
中国移动号段
134(0-8)、135、136、137、138、139、147、150、151、152、157、158、159、172、178、182、183、184、187、188、198
有些号码验证不通过啊！

**Comment by flycash** [comment]
我们已经合并过去了develop。你可以看一下 #4027

**Comment by flycash** [comment]
你可以看一下我们的测试里面有没有漏掉什么，我瞧了一下应该没有。

目前我们计划是7.1正式发布版本~~
