### ISSUE TITLE
support user-define ES index name 

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4040]
Please answer these questions before submitting your issue. Thanks!

#2662 

1. What version of Go and beego are you using (`bee version`)?
Any version

2. What operating system and processor architecture are you using (`go env`)?
Any

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

When we use ES as the logger, the index name looks like "2018-01-12",

but I think we should allow users to custom their own index name.

4. What did you expect to see?

User can define their index name

5. What did you see instead?

Index name looks like "2019-01-23"

**Comment by 741369** [comment]
I will fix this issue later and  [issue4008](https://github.com/astaxie/beego/issues/4008).
