### ISSUE TITLE
beego

### ISSUE THREAD

**Issue by waiting0729** [astaxie/beego#4041]
beego有没有考虑也加入类似django那样的用户管理的模块

**Comment by flycash** [comment]
你说的是那种通用业务模块是吧？诸如用户管理权限控制这种在多数项目都会使用的？这种的话，目前我们没有这个计划。我个人思考过这个问题，暂时不想做的原因是：1. 难以做到通用，有限的通用会在项目发展过程中很容易变得不适用；2. 目前我们精力集中在重构beego和追赶时代潮流上。

在将来，我觉得是可以考虑的问题。中短期来看，应该不会涉及这种。
