### ISSUE TITLE
注解路由无法自动生成

### ISSUE THREAD

**Issue by QQ794763733** [astaxie/beego#4046]
我已确保我是dev模式，一开始项目是可以自动生成的，后来就不会给我自动生成了。

**Comment by flycash** [comment]
……大哥可以提供错误信息和demo代码么？

**Comment by QQ794763733** [comment]
`func init() {
	beego.InsertFilter("*", beego.BeforeRouter, filter.CORS())
	beego.Include(&controllers.LoginController{})
	admin := beego.NewNamespace("/Admin", beego.NSInclude(&controllers.AdminController{}))
	beego.AddNamespace(admin)
}`
这是路由代码，没有报错信息，运行后没有生成路由文件，所有全部都是访问都是Not match。

**Comment by liuhaogui** [comment]
经验所得：路由修改后可以运行成功后，再次重启解决，原因未知，路由文件会刷新生成后就不会404了

**Comment by flycash** [comment]
和#3946 一样么

**Comment by QQ794763733** [comment]
> 经验所得：路由修改后，可以在服务运行成功后，再次重启解决，原因未知，路由文件会刷新生成新的后就不会404了

似乎没有作用，我重启几次了，就是不给我生成，并且我新建项目都不会给我生成了。

**Comment by uuappli** [comment]
我也出现同样情况

**Comment by flycash** [comment]
有输出什么错误日志么？

**Comment by flycash** [comment]
commentsRouter_.go这个文件找到了么

**Comment by yitenghao** [comment]
把原先生成的删了重新运行

**Comment by uuappli** [comment]
> 有输出什么错误日志么？

没有错误日志，之前是好的，最近不知道更新了什么就不行了，原来的 commentsRouter_.go 文件删除后， 也不会重新生成，目前只能手动添加路由了

**Comment by uuappli** [comment]
![image](https://user-images.githubusercontent.com/6519730/86691052-110eaf80-c03b-11ea-9fc6-2118c15af0c1.png)

**Comment by flycash** [comment]
可以把复现代码提供一下？我这边试试。从这个日志上看，的确没什么问题的样子

**Comment by QQ794763733** [comment]
> 把原先生成的删了重新运行

没有用的哦

**Comment by QQ794763733** [comment]
> 可以把复现代码提供一下？我这边试试。从这个日志上看，的确没什么问题的样子

代码应该没什么问题，这个东西也许是Bee工具的Bug？因为自从遇到这个问题以后，我重新生成的项目一行代码也还没写的，都不会再给我生成注解路由了。

**Comment by liuhaogui** [comment]
这两天也遇到这问题了。
beego v1.12.2存在这问题，路由删掉后无法自动生成。
go mod降级使用beego v1.12.1，删除路由生成文件后重启可以自动再次生成。路由加载成功。

**Comment by flycash** [comment]
@liuhaogui 可以提供一个demo吗？或者能否提供错误日志？

**Comment by flycash** [comment]
@QQ794763733 可以把你的controller去掉敏感信息提供一下么？

**Comment by flycash** [comment]
@QQ794763733 @liuhaogui 如果可以的话，麻烦两位提供一下自己的controller的定义，把方法体清空。我这边使用了文档里面的例子的controller来生成路由，并未遇到问题。这是我使用的信息:
```go
// Cms_ctrlController operations for Cms_ctrl
type Cms_ctrlController struct {
	beego.Controller
}

// URLMapping ...
func (c *Cms_ctrlController) URLMapping() {
	c.Mapping("Post", c.Post)
	c.Mapping("GetTwo", c.GetTwo)
	c.Mapping("GetAll", c.GetAll)
	c.Mapping("Put", c.Put)
	c.Mapping("Delete", c.Delete)
}

// Post ...
// @Title Create
// @Description create Cms_ctrl
// @Param	body		body 	models.Cms_ctrl	true		"body for Cms_ctrl content"
// @Success 201 {object} models.Cms_ctrl
// @Failure 403 body is empty
// @router / [post]
func (c *Cms_ctrlController) Post() {

}

// GetTwo ...
// @Title GetTwo
// @Description get Cms_ctrl by id
// @Param	id		path 	string	true		"The key for staticblock"
// @Success 200 {object} models.Cms_ctrl
// @Failure 403 :id is empty
// @router /:id [get]
func (c *Cms_ctrlController) GetTwo() {

}

// GetAll ...
// @Title GetAll
// @Description get Cms_ctrl
// @Param	query	query	string	false	"Filter. e.g. col1:v1,col2:v2 ..."
// @Param	fields	query	string	false	"Fields returned. e.g. col1,col2 ..."
// @Param	sortby	query	string	false	"Sorted-by fields. e.g. col1,col2 ..."
// @Param	order	query	string	false	"Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ..."
// @Param	limit	query	string	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
// @Success 200 {object} models.Cms_ctrl
// @Failure 403
// @router / [get]
func (c *Cms_ctrlController) GetAll() {

}

// Put ...
// @Title Put
// @Description update the Cms_ctrl
// @Param	id		path 	string	true		"The id you want to update"
// @Param	body		body 	models.Cms_ctrl	true		"body for Cms_ctrl content"
// @Success 200 {object} models.Cms_ctrl
// @Failure 403 :id is not int
// @router /:id [put]
func (c *Cms_ctrlController) Put() {

}

// Delete ...
// @Title Delete
// @Description delete the Cms_ctrl
// @Param	id		path 	string	true		"The id you want to delete"
// @Success 200 {string} delete success!
// @Failure 403 id is empty
// @router /:id [delete]
func (c *Cms_ctrlController) Delete() {

}
```
中间我的修改是把GetOne改成了GetTwo，都正确生成了。这是我使用的版本信息：
```
├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.13.10
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 12
├── GOPATH    : /Users/mindeng/go-workspace
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Wednesday, 8 Jul 2020
```
其中 beego 版本是 1.12.2。

盼回复。

**Comment by liuhaogui** [comment]
@flycash 

`➜  beegoDemo git:(master) ✗ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.11.0

├── Beego     : 1.10.1
├── GoVersion : go1.13.4
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Applications/XAMPP/htdocs/GOPATH
├── GOROOT    : /usr/local/Cellar/go/1.13.4/libexec
├── Compiler  : gc
└── Date      : Thursday, 9 Jul 2020
➜  beegoDemo git:(master) ✗ go version
go version go1.13.4 darwin/amd64`

- 示例代码参见项目：可以clone后make run 测试。beego 1.12.1可以生成路由，1.12.2不行。
https://github.com/liuhaogui/beegoDemo/blob/5aa1f8b7bb5a0f22fb0a6876344f34cc97774505/routers/router.go#L14

**Comment by flycash** [comment]
……已经复现……我用1.12.1也没能生成……我用你截图里面的1.10.1也没能生成……

**Comment by flycash** [comment]
我知道了……还是go module的问题……
我拉下代码之后，在go.mod里面的配置是：
`module github.com/liuhaogui/beegoDemo`
在这个配置之下，我用什么版本都无法生成，而后我改成了
`module beegoDemo`就生成了，1.12.1和1.12.2都生成了。

**Comment by flycash** [comment]
目前我的感觉是，module设置为github/xxx/它就会去gopath/src/github.com/xxx之后的路径去找controller来生成路由=。=两位试试效果。

**Comment by AllenX2018** [comment]
看了下代码

https://github.com/astaxie/beego/blob/7a48fbb69846515d9dc3627096590f2b7b2a1bca/router.go#L263-L273

在使用go mod的时候，这种方式来查找注解路由定义的包所在的路径感觉不合适啊。我觉得是不是加一个配置，专门用来配置注解路由的Controller所在的文件路径比较好？thoughts?

**Comment by flycash** [comment]
> 看了下代码
> 
> https://github.com/astaxie/beego/blob/7a48fbb69846515d9dc3627096590f2b7b2a1bca/router.go#L263-L273
> 
> 在使用go mod的时候，这种方式来查找注解路由定义的包所在的路径感觉不合适啊。我觉得是不是加一个配置，专门用来配置注解路由的Controller所在的文件路径比较好？thoughts?

这是一个比较好的建议。我其实倾向于提供一个查找这种controller和生产route的抽象。整个过程可以看做三步，查找controller，读取controller信息并生成路由内容，将路由写入文件。而第二步，是稳定且不易变更的。只有第一步和第三步。而基本上第一步和第三步又是相关的，所以这里可以暴露一个接口。
默认情况下，我们认为controller就是在项目下的controller文件夹。
在go.mod开启的条件下，我们认为controller的目录就是include进来的controller的路径与module名字之间的差值。例如如果一个module叫做`gihub.com/xxx/app1`， `Include`进来的`controller`在`github.com/xxx/app1/path/to/controller`，那么我们就认为controller所在位置相对于项目来说是`path/to/controller`。

本质上，我们要解决是否在GOPATH下和是否启动gomod交叉得到四种情况下的路由生成问题。

进一步考虑到路由初始化顺序的问题，我认为我们还应该允许用户自定义自己生成的路由文件的名字。

这是我的初步想法，你觉得呢。

我计划创建一个支持go mod的project来追踪所有跟go mod  GOPATH有关的问题。

**Comment by AllenX2018** [comment]
> 在go.mod开启的条件下，我们认为controller的目录就是include进来的controller的路径与module名字之间的差值。例如如果一个module叫做gihub.com/xxx/app1， Include进来的controller在github.com/xxx/app1/path/to/controller，那么我们就认为controller所在位置相对于项目来说是path/to/controller。

module 名字准备怎么获取呢？通过go.mod文件？

我是觉得如果加一个配置来指定注解路由所在的目录的话，不管是GOPATH还是go mod，都可以统一解决如何找到注解路由的定义文件所在目录的问题。

> 进一步考虑到路由初始化顺序的问题，我认为我们还应该允许用户自定义自己生成的路由文件的名字。

这个是在考虑 #3946 所指的问题吗？

**Comment by flycash** [comment]
> > 进一步考虑到路由初始化顺序的问题，我认为我们还应该允许用户自定义自己生成的路由文件的名字。
> 
> 这个是在考虑 #3946 所指的问题吗？

是的。本质上这是一个不恰当使用的问题。因为本身这种路由信息不应该互相依赖。

加一个配置来指定的确是最简单的方法。

**Comment by lishuu** [comment]
> 我知道了……还是go module的问题……
> 我拉下代码之后，在go.mod里面的配置是：
> `module github.com/liuhaogui/beegoDemo`
> 在这个配置之下，我用什么版本都无法生成，而后我改成了
> `module beegoDemo`就生成了，1.12.1和1.12.2都生成了。

依此方法路由可以生成了，但是 swagger doc 无法生成。
