### ISSUE TITLE
bee安装成功，却显示未安装beego

### ISSUE THREAD

**Issue by WangYinFeng123** [astaxie/beego#4049]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

使用 go1.14.4 ，bee版本为v1.11.0
2. What operating system and processor architecture are you using (`go env`)?
使用Mac OS 10.15, 4core-amd64 处理器
<img width="565" alt="截屏2020-07-0123 18 04" src="https://user-images.githubusercontent.com/15115451/86261431-1f9b3800-bbf1-11ea-81df-488d36a0d2e2.png">

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

设置好GOROOT和GOPATH以后，使用 go get gihub.com/astaxie/beego 安装beego，然后安装bee
4. What did you expect to see?

beego成功安装
5. What did you see instead?
查看bee版本时，显示beego未安装

**Comment by liuhaogui** [comment]
建议参照快速上手文档解决。
https://beego.me/quickstart

**Comment by flycash** [comment]
这个问题，我们预计将在下一个版本修复。本月就有望发布新版本，到时候你可以试试。不过……这个看不到也并不影响你使用项目:)

**Comment by flycash** [comment]
终于发现bee检测beego的版本的机制有点蠢，它只会找GOPATH/src/github.com/astaxie/xxx 是否存在，读里面的一个配置项。
在go mod之下，没有太大意义。我不打算修复这个问题，并且会在将来从bee中移除掉这个功能——的确是有点略蠢。
