### ISSUE TITLE
Orm Refactor Plan, Features and Design (Continuously updating)

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4050]
Now, we start to develop the [v2.0.0](https://github.com/astaxie/beego/milestone/12).

[Refactoring ORM](https://github.com/astaxie/beego/projects/3) is the most important job in v2.0.0. 

Targets:

1. support tracing and metrics. The options are [opentracing](https://opentracing.io/), [prometheus](https://prometheus.io/),  [opentelemetry](https://github.com/open-telemetry/opentelemetry-go);

2. support `context.Context`, we introduce break changes which adding `context.Context` to most of API.

3. Introduce new API for ORM lifecycle. Users are allowed to destroy the ORM instance to release the DB connection...

4. Introduce new API for transaction.  #919 

5. Define AOP API. In fact, "real AOP" is hard to design and implement, so we will introduce new interface, Interceptor. We plan to use this interface to trace SQL. #4069 

6. Read/Write Splitting. We want to use decorator pattern to support them. In order to support this feature, we may introduce `Hint` interface. 

We want to collect features that you want us to provide in v2.0.0. It'll be helpful if you can provide demo.

**Comment by chenxianqi** [comment]
模型定义能自定义枚举类型就好了，自动创建数据库枚举类型，不然操作起来比较不友好，存的是字符串的话比较容易写错

**Comment by curvesoft** [comment]
Beego的orm没用过，用过xorm和gorm，最早用了xorm，发现对于空数据的更新处理实在是麻烦，0数值和空字符串必须得单独处理，后来换gorm主要也是因为它可以把struct的字段类型定义成指针，根据指针的空和非空决定要不要更新，但是指针多了程序写和读都很费劲也容易错，希望beego orm能有更优雅方案
