### ISSUE TITLE
How to serve attachment?

### ISSUE THREAD

**Issue by Paxa** [astaxie/beego#4052]
How to serve attachment to customer from string?

Sorry, I tried to find same question here, but for most of issues I don't understand the language

I found `this.Ctx.Output.Download()` - no docs, but I assume it reads file from disk. Is there function to serve content from memory?

I found manual way:
```go
	this.Ctx.Output.Header("Content-Disposition", "attachment; filename=result.xlsx")
	this.Ctx.Output.Header("Content-Description", "File Transfer")
	this.Ctx.Output.Header("Content-Type", "application/application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	this.Ctx.Output.Body([]byte("my content"))
```

**Comment by flycash** [comment]
What do you mean `serve attachment to customer from string`. Do you mean cutomer download something which is string in memory?

**Comment by Paxa** [comment]
Yes

**Comment by flycash** [comment]
It would be a little bit complicated since beego doesn't support download content from memory. But we can take `BeegoOutput.Download` function as reference. I just try a simple sample, it works as expected:
```go
func main() {
	ctrl := &MainController{}
	beego.Router("/download", ctrl, "get:Download")
	beego.Run()
}

type MainController struct {
	beego.Controller
}

func (ctrl *MainController) Download()  {
	output := ctrl.Ctx.Output
	output.Header("Content-Disposition", "attachment;filename=mytest.txt;")
	output.Header("Content-Description", "File Transfer")
	output.Header("Content-Type", "application/octet-stream")
	output.Header("Content-Transfer-Encoding", "binary")
	output.Header("Expires", "0")
	output.Header("Cache-Control", "must-revalidate")
	output.Header("Pragma", "public")
	ctrl.Ctx.WriteString("Hello")
	ctrl.Ctx.Output.Download()
}
```
You can try it.

**Comment by flycash** [comment]
Here is the sample:
https://github.com/beego-dev/beego-example/pull/17

**Comment by Paxa** [comment]
Thank you
