### ISSUE TITLE
我想把数据库中的数据部分拿到script标签中使用，但是我想了很多办法都没有实现，请问beego支持吗

### ISSUE THREAD

**Issue by 265525** [astaxie/beego#4062]
我想把数据库中的数据部分拿到script标签中使用，但是我想了很多办法都没有实现，请问beego支持吗

**Comment by flycash** [comment]
抱歉，我没看懂你说的是什么？可以详细说一下么？最好提供点demo的代码，这样会更好。

**Comment by 265525** [comment]
django中能把模板数据用到js里面，请问beego怎么样实现呢，还是说没有提供这样的方法

**Comment by 265525** [comment]
例如
beego 控制器:
this.Data["datas"] = "sqwsqyus"

view:
<script>
var datas = {{ .datas }}
</script>

但是上面view下会报错，是不支持吗

**Comment by 265525** [comment]
我从iris受到django模板启发已经解决了这个问题'{{ .data }}'
