### ISSUE TITLE
Only one http server but we need multiple http servers

### ISSUE THREAD

**Issue by zuzuviewer** [astaxie/beego#4067]
We need to run multiple http servers in one process.
Gin can deal with this situation
We hope Beego can deal too

**Comment by flycash** [comment]
We plan to do it.

**Comment by gdhameeja** [comment]
I'd like to work on it.

**Comment by flycash** [comment]
@gdhameeja Thank you. Please checkout new branch from develop-2.0 and put your codes in pkg/... because we want to adjust the project to the [standard project layout](https://github.com/golang-standards/project-layout)

**Comment by flycash** [comment]
@gdhameeja are you still working on this issue?

**Comment by gdhameeja** [comment]
@flycash Yes. I was working on an issue in caddy which got done last night. Will start work on this today.

**Comment by gdhameeja** [comment]
Hello All, I have started looking into this. This is my first time working on beego and I am fairly new to Go as well, so it would be great if I could get some input on this. So far I understand that `Router()` returns a BeegoApp, which we call `Run()` on which does all the listening on port, controller binding and stuff. This is the user interface I'm proposing to have multiple services run in the same process:
```
func main() {
	app1 := beego.App()
	app1.Router("/", &MainController{})
	app1.Router("/login", &LoginController{})
	app1.ListenAndServe(":8080")

	app2 := beego.App()
	app2.Router("/", &MainController{})
	app2.Router("/login", &LoginController{})
	app1.ListenAndServe(":8000")

	beego.Run()
}
```
Note: I undertand `App` is already defined in the `beego` namespace so we'll probably need to have something else there. But using it just as a placeholder for now. We probably need another abstraction around a service?
Inputs are needed and well appreciated.

Is there a real time communication channel or something that I can use to communicate in case of issues?
Thanks.

**Comment by flycash** [comment]
If you use wechat, we can discuss this on wechat. And if you use slack, pleas join beego's slack and @me in general channel. And you can send me an email, we have dev-email google group. 
If you think necessary, we can have an online meeting by using zoom. 

Feel free to send me an email if you have any questions.

**Comment by gdhameeja** [comment]
@flycash Any comments on the above user api?

**Comment by flycash** [comment]
> @flycash Any comments on the above user api?

That looks good. I think `app1.Run(), app2.Run()` is better than `beego.Run()`

**Comment by flycash** [comment]
Just kindly remind, the difficult thing is decoupling `App` and `Listener`. I find that `BeeApp` depends on global `BeeConfig`, and it contains `Listener`.

I prefer that each App instance has its' own `Listener` and `WebConfig`. 

![image](https://user-images.githubusercontent.com/9923838/90787498-5e1eba80-e337-11ea-9264-994110e78795.png)

![image](https://user-images.githubusercontent.com/9923838/90787563-6f67c700-e337-11ea-858f-b84ffa466ba0.png)

**Comment by flycash** [comment]
If you don't mind, you can create a draft PR with your demo. The API, the mock implementation, in a word, the best way you think. I will be the first user to use your design and I can give you more advice.

**Comment by gdhameeja** [comment]
> If you don't mind, you can create a draft PR with your demo. The API, the mock implementation, in a word, the best way you think. I will be the first user to use your design and I can give you more advice.

Didn't understand. I planned I will open up a new branch and it will be in small parts so the team has visibility on what is being done and how its being done. So if needed we can revert changes immediately. Maybe we can have another branch for this and I can make PR's to that branch, and once its completed we can merge it to master?

**Comment by flycash** [comment]
>  Maybe we can have another branch for this and I can make PR's to that branch, and once its completed we can merge it to master?

You can use `ftr/multi-server`. I just created it.

**Comment by flycash** [comment]
@gdhameeja I am free now, so I will support this by myself and do this based on our discussion.
