### ISSUE TITLE
Proposal: Interceptor for Ormer

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4069]
This is part of ORM refactor plan.

The key point is that orm module is lack of mechanism that allows users to do some AOP job, like logging sql, metrics, tracing...

Now we want to introduce an Interface API looks like
```go
type Invocation struct {


}

type Interceptor interface {
	Before(ctx context.Context, inv *Invocation)
	After(ctx context.Context, inv *Invocation)
}

```
And this interface will be used in `Ormer` interface.
For example, when we implement `Read` method of `Ormer` interface:

```go
// read data to model
func (o *orm) Read(ctx context.Context, md interface{}, cols ...string) error {

	interceptors := o.interceptors

	for _, i := range o.interceptors {
		i.Before()
	}

	mi, ind := o.getMiInd(md, true)
	res := o.alias.DbBaser.Read(o.db, mi, ind, o.alias.TZ, cols, false)

	for _, i := range o.interceptors {
		i.After()
	}
	return res 
}
```
These codes are demo codes, you can redesign them.

Here are some tips:
1. the implementation of interceptor should be pluggable, so we should think about how users register their impletation;
2. the interceptors should have two types:
    - global: Every instance of `Ormer` interface will use them
    - instance only: some instance use them but other not.
3. How to pass parameter among `Before` method and `After` method. For example:
```go
func (m *MetricsInterceptor) Before(ctx context.Context, inv *Invocation) {
	startTime := time.Now()
	// ...
}

func (m *MetricsInterceptor) After(ctx context.Context, inv *Invocation) {
	endTime := time.Now()
	
	// dur := endTime - startTime how to get startTime in this method?
}
```
4. The `Invocation` structure(or interface) should be scalable.

If you have any question, please leave a comment, or we could have some meeting to have further discussion.

**Please provide an implementation using Prometheus of this interface.**

**Comment by pro-jango** [comment]
I want to try this, please assign it to me.

**Comment by flycash** [comment]
Thank you. Please checkout new branch from develop-2.0.
