### ISSUE TITLE
bee run failure,undefined: proto.ProtoPackageIsVersion3

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4071]
bee run failure, report this error:

../github.com/prometheus/client_model/go/metrics.pb.go:22:11: undefined: proto.ProtoPackageIsVersion3

**Comment by helloqhq** [comment]
<img width="1104" alt="图片" src="https://user-images.githubusercontent.com/7424819/87522622-6e98a100-c6b8-11ea-9c86-a422d3520e4b.png">

**Comment by flycash** [comment]
What's the version of Prometheus client? It seems that you are using an incompatible version.
Here is my module:
![image](https://user-images.githubusercontent.com/9923838/87541913-ab729100-c6d4-11ea-95ed-39a74de0c61a.png)

Please check it.
