### ISSUE TITLE
only filename in log but we need full path

### ISSUE THREAD

**Issue by zuzuviewer** [astaxie/beego#4073]
We have some file that have the same name,we need log with full path to seperate them.Maybe beego can have a function to set it.

For example, we have two file /config/test.go and /service/test.go. The logs are output short file name "test.go", so it's confused for us.

I think we need the full path.

**Comment by flycash** [comment]
Please provide more details. I can't understand what you want. =.=

**Comment by flycash** [comment]
> > Please provide more details. I can't understand what you want. =.=
> > 额，这样的话还是说中文吧。
> > 在项目中用beego的日志输出，现阶段beego只有调用日志输出的文件名和行号，而我们是想要路径+ 文件名和行号。有可能项目中不同路径有相同文件名的文件，这时没有路径会造成混乱。
> > 如 /config/test.go和/service/test.go都有打印日志的话，只有文件名就不好立即定位到哪个文件输出

这里有几个issue都是类似的需求，本质上是允许自定义日志输出格式。这里有一个pr #4063 ,有一个外国小伙伴目前正在处理。我先看他的效果，如果不满足，我再自己来。

**Comment by AllenX2018** [comment]
@flycash 这个问题在develop-2.0已实现了，为何不关闭？

**Comment by flycash** [comment]
> @flycash 这个问题在develop-2.0已实现了，但是有点问题,在`log`包级别实现的话，用户调用`log:=logs.NewLogger`返回`log`对象的属性`enableFullFilePath`默认值是false，因此并没有生效：
> 
> https://github.com/astaxie/beego/blob/6612bc4c2ad3cc2d8fe7fd9d4e76e24913e82447/pkg/infrastructure/logs/log.go#L668-L672
> 
> 
> 我认为比较理想做法是：在返回对象后再调用此方法，例如：
> `log := logs.NewLogger(100)`
> `log.EnableFullFilePath(true)`

有一位社区成员正在重构log模块，到时候会完整的支持自定义日志格式，不仅仅是全路径。
