### ISSUE TITLE
Enhance: Make cache PrepareStatement Configurable 

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4079]
Now, #4025 using LRU to cache the `Prepare Statement`. But the max size of this PR is a fixed value 1000.

Now we should enhance this in beego V2.0

We want to define a structure named `OrmConfig` in `pkg/orm` package, and it contains one config item: `orm.stmt.cache.max.size`

if the value <=0, it means that we don't cache the stmt;
or the value is the max size of LRU.

**Comment by jianzhiyao** [comment]
Close https://github.com/astaxie/beego/issues/3786
