### ISSUE TITLE
Fragile ORM Tests

### ISSUE THREAD

**Issue by tayoogunbiyi** [astaxie/beego#4081]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
   go version 1.14.3
   I'm working straight off the `develop` branch.

2. What operating system and processor architecture are you using (`go env`)?
    Linux/amd64

3. What did you do?
  Currently, if you run all the tests in `orm_test.go` they pass but the problem comes when you add a new test in between any of the existing tests that perhaps create a user (or any other model).
![image](https://user-images.githubusercontent.com/29612423/87952980-5ce14000-caa2-11ea-96d2-81d292ef0e07.png)

There are multiple lines of the sort of `throwFail(t, AssertIs(id, 2))` that have the expected `id` hardcoded and this becomes a problem when a new model is created above where the id is expected as all ids below shift by `1` We need some kind of way to know which id comes next, without hardcoding the `id`.

4. What did you expect to see?
All tests pass.

5. What did you see instead?
Tests failing.

**Comment by tayoogunbiyi** [comment]
@flycash would you like this refactored? Asides the mentioned issue above, I feel that the tests could be broken down into a way where tests don't depend on each other.

Right now, running certain tests alone fail because they depend on results from previous tests.

**Comment by flycash** [comment]
@tayoogunbiyi This is a big problem. I want to rewrite most of the unit tests in ORM module. I think those unit tests should be isolated from each other. And we need to provide more tests to improve our code coverage.

**Comment by tayoogunbiyi** [comment]
@flycash I'm wondering if this would be left for version 2.0 or should be integrated with the existing develop branch. I realized there's no orm_test.go file in the develop-2.0 branch

**Comment by tayoogunbiyi** [comment]
I'd be joining your call with @IamCathal tomorrow so we can talk more about this
