### ISSUE TITLE
How to access nest config item? 如何根据runmode切换或访问多级配置？

### ISSUE THREAD

**Issue by gy0624ww** [astaxie/beego#4086]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.11.0

2. What operating system and processor architecture are you using (`go env`)?
mac
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/guanyue/Library/Caches/go-build"
GOENV="/Users/guanyue/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/guanyue/mytest/gogogo"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/guanyue/workflow/360/mdsp-openapi/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h_/y6xdzjf57d17z715n_ndcth80000gn/T/go-build648493681=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

access the nest config item by change runmode
访问多层级配置值
the config example below:
配置文件如下：
(how to access? if write like this,return nothing ,dbhost := beego.AppConfig.String("db1::dbhost") )
（这么写如何访问？dbhost := beego.AppConfig.String("db1::dbhost") 这么访问访问不到值）
runmode = "${ProRunMode||dev}"
[dev::db1]
dbhost = 127.0.0.1
[prod::db2]
dbhost = xxx.xxx.xxx.x

there are mulitple database config,i want to switch config in according to the env variable.
how to write nest config, like this below?
数据库有多个，我想根据环境变量来区分测试环境和线上环境配置。默认的ini配置是这么写吗？
还是这么写（这种写法dbhost := beego.AppConfig.String("db1::dbhost") 会总是返回prod的值,应该被覆盖了）
[dev]
   [db1]
   dbhost = 127.0.0.1
   [db2]
    ...
[prod]
   [db1]
   dbhost = xxx.xxx.xx.x
  [db2]
    ...
4. What did you expect to see?
能正确的根据runmode取到指定db的值
access the config item by change runmode correctlly

5. What did you see instead?

一直是访问的是prod的配置（也就是先配置的选项被后配置的选项覆盖了）

**Comment by gy0624ww** [comment]
@markstory @tmc @kioopi @huacnlee @astaxie

**Comment by flycash** [comment]
其实你应该考虑在线上线下使用不同的配置文件……

**Comment by gy0624ww** [comment]
> 其实你应该考虑在线上线下使用不同的配置文件……

可以是可以，关键beego不是有这个runmode的功能吗。

就算我线上单独弄线上环境的配置文件，也会遇到其他的共同类型的不同细分的配置，那这种嵌套的配置该如何访问？

**Comment by gy0624ww** [comment]
> 其实你应该考虑在线上线下使用不同的配置文件……

我想用viper，但是beego初始化的时候就强制加载内置配置了。改动太大了

**Comment by flycash** [comment]
我印象里面，beego没有加载配置而后区分是什么runmode的功能。也就是它只会读全部配置。这就是导致后面配置覆盖前面配置的根源。

至于强制加载配置，这应该是指它会默认加载“confg”目录下的配置？你可以通过指定配置文件名来显式加载：
```go
err := beego.LoadAppConfig("ini", ConfigFile)
```

**Comment by gy0624ww** [comment]
> 我印象里面，beego没有加载配置而后区分是什么runmode的功能。也就是它只会读全部配置。这就是导致后面配置覆盖前面配置的根源。
> 
> 至于强制加载配置，这应该是指它会默认加载“confg”目录下的配置？你可以通过指定配置文件名来显式加载：
> 
> ```go
> err := beego.LoadAppConfig("ini", ConfigFile)
> ```

有的区分的runmode的功能的。https://beego.me/docs/mvc/controller/config.md#%E4%B8%8D%E5%90%8C%E7%BA%A7%E5%88%AB%E7%9A%84%E9%85%8D%E7%BD%AE

runmode = "dev"
[dev]
dbhost = 127.0.0.1

[prod]
dbhost = 192.167.1.1

打印dbhost := beego.AppConfig.String("dbhost") 结果就是127.0.0.1

**Comment by flycash** [comment]
看来这是一个BUG……

**Comment by flycash** [comment]
我怀疑是这种写法
```
[dev]
[db1]
host....
```
造成的。
你可以考虑使用
```
[dev]
db1.host...
```
来使用。

**Comment by gy0624ww** [comment]
> 我怀疑是这种写法
> 
> ```
> [dev]
> [db1]
> host....
> ```
> 
> 造成的。
> 你可以考虑使用
> 
> ```
> [dev]
> db1.host...
> ```
> 
> 来使用。

这样是可以db1.host整个当个字符串作为key了，但是感觉怪怪的。如果要获取db1下所有参数就不行了。
就是这种嵌套的配置beego，不支持吗

**Comment by gy0624ww** [comment]
@astaxie 权威解释下呗

**Comment by acrossOcean** [comment]
这个好像是解析配置文件的时候就不支持吧? 
我看ini文件的解析就是 每个 [] 作为一个section 的开始和上一个section的结束
考虑换个配置文件格式?

**Comment by gy0624ww** [comment]
> 这个好像是解析配置文件的时候就不支持吧?
> 我看ini文件的解析就是 每个 [] 作为一个section 的开始和上一个section的结束
> 考虑换个配置文件格式?

换成什么呢？toml beego又不支持，yaml还得自己写一遍结构体，搞不清楚为什么要用框架了

**Comment by acrossOcean** [comment]
要不试试 通过环境变量的方式在启动时 分别 load 不同的 ini (beego.LoadAppConfig() 这个方法)? 
这样能解决你说的那个开发生成不同配置文件的问题, 但是多级的配置还是没解决,感觉 要ini 支持的话, 需要改下框架 提 pr了

**Comment by gy0624ww** [comment]
通过环境变量，就一层的配置信息是可以的。这个已经试过了。就像文档那样
但是那样没啥意义，真正项目哪有几个一级的

**Comment by gy0624ww** [comment]
> 要不试试 通过环境变量的方式在启动时 分别 load 不同的 ini (beego.LoadAppConfig() 这个方法)?
> 这样能解决你说的那个开发生成不同配置文件的问题, 但是多级的配置还是没解决,感觉 要ini 支持的话, 需要改下框架 提 pr了

通过环境变量，就一层的配置信息是可以的。这个已经试过了。就像文档那样
但是那样没啥意义，真正项目哪有几个一级的

**Comment by flycash** [comment]
这种限制其实不是beego自身的缺陷，而是ini文件格式所限制的。应该考虑支持更多的配置文件格式，不过目前看来，ini文件格式是无法做到你所需要的了。
