### ISSUE TITLE
The RoadMap and if you want to do something...

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4089]
Plan:  https://github.com/astaxie/beego/wiki/RoadMap

RoadMap project: https://github.com/astaxie/beego/projects/4

Now we are refactoring ORM module:  https://github.com/astaxie/beego/projects/3

Web module: https://github.com/astaxie/beego/projects/7

Support go module: https://github.com/astaxie/beego/projects/6

Better testing support: https://github.com/astaxie/beego/projects/8

Feel free to create issue to tell us what you want.

**Comment by mnrce** [comment]
I don't see this in the roadmap, but can we do better for testing, like generating API test, mocking models, integration testing for models, ...? I have been using beego for a long time now but never been able to write tests for it.

**Comment by flycash** [comment]
> I don't see this in the roadmap, but can we do better for testing, like generating API test, mocking models, integration testing for models, ...? I have been using beego for a long time now but never been able to write tests for it.

We won't support those features in v2.0.0. But I think this is a good idea and want to put them into v2.0.1 or v2.0.2.

I will create a project for this proposal.
