### ISSUE TITLE
Proposal: Generate routers based on annotations

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4093]
Generating routers like
```go
// CMS API
type CMSController struct {
    beego.Controller
}

func (c *CMSController) URLMapping() {
    c.Mapping("StaticBlock", c.StaticBlock)
    c.Mapping("AllBlock", c.AllBlock)
}

// @router /staticblock/:key [get]
func (this *CMSController) StaticBlock() {

}

// @router /all/:key [get]
func (this *CMSController) AllBlock() {
}
```
is very useful. 

But this feature has many problems. #3624 #3162 #4046 #3908 #3946 #3871 #3505 #3058 (most of them were reported by Chinese users, so those issues are written by Chinese).

This feature is affected by:
1. module name. The short name "module1" works but "xx.xxxx.xxx.module" don't;
2. Project is under GOPATH;
3. Using go mod

In fact, the root cause is that Beego looks up the controller path incorrectly.

Inspired by @AllenX2018 in #4046, we think we can add some configuration, for example, named "WebConfig.ControllerPath = path/to/controller", we will generate the routers in this path.

The default value is "./controller".

I think it's very simple and easy to implement.

**Comment by AllenX2018** [comment]
I think I can try to create a pr to solve this issue : )

**Comment by flycash** [comment]
@AllenX2018 Hi, now you own this. :)

**Comment by flycash** [comment]
@AllenX2018 Please checkout a new branch from develop-2.0

**Comment by AllenX2018** [comment]
@flycash OK
