### ISSUE TITLE
内存泄露的问题困扰我很久有人帮忙看一下吗

### ISSUE THREAD

**Issue by jiekexuan** [astaxie/beego#4094]
![image](https://user-images.githubusercontent.com/10591249/88285532-da66b380-cd21-11ea-8533-bc1df5ce5830.png)
红框的位置内存不断在增长 我是在是不知道问题出现在哪里

**Comment by jiekexuan** [comment]
这个应该是beego里面的源代码导致的增长 有没有高手帮我看看

**Comment by flycash** [comment]
你在社区群里面吗？微信的

**Comment by flycash** [comment]
从你图里面看，好像内存占用并不大啊……11467.78kB = 11.5 MB???

**Comment by jiekexuan** [comment]
他会慢慢的增长
