### ISSUE TITLE
beego 1.12.2 does not generat commentsRouter file in router

### ISSUE THREAD

**Issue by A1311981684** [astaxie/beego#4097]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.14.4

2. What operating system and processor architecture are you using (`go env`)?
ubuntu18.04

3. What did you do?
My project is in gomod, I manually changed the beego version in go.mod from 1.12.1 to 1.12.2.
When I try to add some new controllers or api and run "bee run -gendoc=true" command int the terminal, it didnt generate new files or modify existing files in /routers.
This is not expected.But when I only change the version to 1.12.1, it successfully generated those commentsRouter codes.

**Comment by flycash** [comment]
#4093
