### ISSUE TITLE
How to capture http response status code？

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4100]
How to capture http response status code？

**Comment by flycash** [comment]
You can refer PrometheusMiddleWare. But it's complicated and you can write your own middleware.
We are designing the new interceptor API.

**Comment by helloqhq** [comment]
> You can refer PrometheusMiddleWare. But it's complicated and you can write your own middleware.
> We are designing the new interceptor API.

How long will the new interceptor API be released？

**Comment by flycash** [comment]
End of August

**Comment by helloqhq** [comment]
> End of August

OK, I'm looking forward to it,Thank you！
