### ISSUE TITLE
Capture panic, custom recover does not take effect

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4102]
Capture panic, custom recover does not take effect

filter：
`beego.InsertFilter("/*", beego.BeforeRouter, middleware.FilterRecover)`

FilterRecover：
`var FilterRecover = func(ctx *context.Context) {
	if r := recover(); r != nil {
		common.Log.Error(beego.Controller{}, fmt.Sprintf("[Recovery] %s panic:\n%s",
			time.Now().Format("2006/01/02 - 15:04:05"), r))
	}
}`

**Comment by flycash** [comment]
What do you mean, I can't get your point from this simple description.

**Comment by helloqhq** [comment]
> What do you mean, I can't get your point from this simple description.

Ignore it. It's solved. Thank you.
