### ISSUE TITLE
app.conf能否增加一个环境变量配置参数

### ISSUE THREAD

**Issue by liuhaogui** [astaxie/beego#4106]
[https://github.com/astaxie/beego/blob/7a48fbb69846515d9dc3627096590f2b7b2a1bca/config.go#L152](https://github.com/astaxie/beego/blob/7a48fbb69846515d9dc3627096590f2b7b2a1bca/config.go#L152)
这里的appConfigPath能否增加一个环境变量优先读取，如果没有获取到再用默认配置。

测试用例tests目录没什么好的方法传入配置文件地址。
项目中如果有用`beego.AppConfig.xx`方法的时候，测试文件启动入口不同导致配置文件地址不对，参数都需要单独init 提前set上，很不方便。

**Comment by flycash** [comment]
我感觉这个是可以考虑的。你目前可以考虑通过命令行参数来传递：
```
if AppPath, err = filepath.Abs(filepath.Dir(os.Args[0])); err != nil {
		panic(err)
	}
```

**Comment by liuhaogui** [comment]
增加：如果设置了配置文件路径的环境变量优先使用，否则使用默认拼接的配置文件路径。
解决：测试入口或其他项目引用入口不同却不能设置配置文件路径问题。

使用方式:  
`export BEEGO_CONFIG_PATH=/app.conf && go test -count=1 -v github.com/xxx/xxx/tests`
或(相对路径）
`export BEEGO_CONFIG_PATH=../conf/app.conf && go test -count=1 -v github.com/xxx/xxx/tests`
