### ISSUE TITLE
In the function RecoverFunc ，How to get the value of context aaa set in the controller？

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4108]
Set the context aaa in the controller
`	this.Ctx.Input.SetData("aaaa", 11111)
`

How to get the value of aaa in function RecoverFunc？

`

        beego.BConfig.RecoverFunc = func(c *context.Context) {

		if r := recover(); r != nil {

			//How to get the value of context aaa ？

		}

	}
`

**Comment by flycash** [comment]
Do you try:
```go
c.Input.Query(key)
c.Input.Param(key)
```

**Comment by helloqhq** [comment]
> Do you try:
> 
> ```go
> c.Input.Query(key)
> c.Input.Param(key)
> ```

Solved it, thank you very much！
