### ISSUE TITLE
In goroutine, how to judge in the context that the http request has ended prematurely？

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4109]
In goroutine, how to judge in the context that the http request has ended prematurely（such as timeout）,I want to close the goroutine in time.

For example the following “c.Done()”
`  

    func createWorker(c *context.Context, seeds chan string, results chan *ImgInfo) {
	go func() {
		for imgUrl := range seeds {
			picReq := httplib.Get(url)
			result, err := picReq.Bytes()
			if err != nil {
				Log.Error(c, err.Error())
			}

			select {
			case <-c.Done():
				//fmt.Println("createWorker done...")
				return
			case results <- &result:

			}
		}
	}()
    }

`

**Comment by flycash** [comment]
So, you want to check whether the request is timeout?? You can check the response's http status.

**Comment by helloqhq** [comment]
> So, you want to check whether the request is timeout?? You can check the response's http status.

How can I get the response's http status？

**Comment by flycash** [comment]
looks like:
```go
result.Status
```
