### ISSUE TITLE
'commentsRouter_controller.go' file not being generated

### ISSUE THREAD

**Issue by zaj-e** [astaxie/beego#4115]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.12.2
├── GoVersion : go1.14.1

2. What operating system and processor architecture are you using (`go env`)?
├── GOOS      : windows
├── GOARCH    : amd64

3. What did you do?
There is this file called ‘commentsRouter_controllers.go’ that generates automatically when you create a web project using the bee tool. It appears to me that it should also be generated when you execute the project in dev mode, [as these lines of code show](https://github.com/astaxie/beego/blob/master/router.go#L254-L293). I tried moving this file out of the project directory, then i executed the command 'bee run' inside the project directory (on dev mode).

4. What did you expect to see?
I expected the file to be generated again.

5. What did you see instead?
The file was not generated.

[I've found another issue in which they've fixed this by changing the GOPATH and GOROOT variables](https://github.com/astaxie/beego/issues/2412), however, my beego project is based on go modules so I’m not sure how that would work out.

**Comment by flycash** [comment]
We are working on it. Please follow #4093
