### ISSUE TITLE
Cannot get session after login, we use vue as front-end framework

### ISSUE THREAD

**Issue by legolas-zeng** [astaxie/beego#4133]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.14
beego 1.10.1

2. What operating system and processor architecture are you using (`go env`)?
system ：win10
 processor ：I5

3. What did you do?
我用vue做前端，登录之后，用`this.SetSession("username",username)`设置session，然后在`username := this.GetSession("username")`获取session信息，可是获取到的为nil，通过redis可以确认session生成正常。请大佬指教

Translated: We use vue as front-end framework, and when user logins, we use `this.SetSession("username",username)` setup session, but when we use `username := this.GetSession("username")` the nil was returned. 

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
所以，首先你们能够确认redis里面，使用key去搜索的时候，是能够检索到这个用户名，并且不会为`nil` 是吧？
其次你们能不能写一个简单的单测，什么都不干，就是直接调用`SetSession`，并且确认`GetSession`不会返回值。

**Comment by legolas-zeng** [comment]
> 所以，首先你们能够确认redis里面，使用key去搜索的时候，是能够检索到这个用户名，并且不会为`nil` 是吧？
> 其次你们能不能写一个简单的单测，什么都不干，就是直接调用`SetSession`，并且确认`GetSession`不会返回值。

已经找到问题了，是vue的问题。多谢
