### ISSUE TITLE
unable to WriteMsg to adapter:slack,error:Post webhook failed 400 Bad Request 400

### ISSUE THREAD

**Issue by hamidabdul1994** [astaxie/beego#4138]
I am getting error While logging in Slack. Below is error to log in slack.
 **Scrip Master Err rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4045: connect: connection refused"**

**Comment by IamCathal** [comment]
Have you done this before without an error or is this your first time encountering this? If possible could you give a minimal code example to reproduce this. Thanks

**Comment by damien-nd** [comment]
It is maybe not related, but I do have the exact same error:
**unable to WriteMsg to adapter:slack,error:Post webhook failed 400 Bad Request 400**

In my case, both use of logs won't work:
```
logs.Alert(`{"infos":"test","another":"test"}`)
```
```
bytes, _ := json.Marshal(datas)
logs.Alert(string(bytes))
```

**Comment by flycash** [comment]
It seems that the provided webhook is wrong.
```go
// SLACKWriter implements beego LoggerInterface and is used to send jiaoliao webhook
type SLACKWriter struct {
	WebhookURL string `json:"webhookurl"`
	Level      int    `json:"level"`
}
```
Could you check the webhook?

**Comment by damien-nd** [comment]
```
func slackConfig() {
	logs.SetLogger(logs.AdapterSlack, `{"webhookurl":"https://hooks.slack.com/services/.../.../...","level":`+strconv.Itoa(logs.LevelError+1)+`}`)
}
```
If I remember good, I add `+1` because matching level wasn't print.
Like here I expect `LevelError` and upper to be print, and it wasn't.

Everything is working well for me until I try to log a json string on Slack.
