### ISSUE TITLE
Could orm support mongodb redis? And providing useful and consistent API

### ISSUE THREAD

**Issue by tangzuqiang** [astaxie/beego#4152]
建议在orm加上mongodb 可以像操作mysql数据库一样简易快捷操作查询
redis ,meche
elasticsearch 
mq  操作,感谢您们的辛苦付出

**Comment by flycash** [comment]
更宽泛的来说，这应该被问题是支持NoSQL的一部分。

I thing we need to take supporting NoSQL into consideration. But I'm not sure when we do this. We don't have any plan yet.
