### ISSUE TITLE
Refactor Session module's `SessionInit` method

### ISSUE THREAD

**Issue by flycash** [astaxie/beego#4153]
In session module, there is a method call `SessionInit`,

we call this function to initialize the session.
```go
err := provider.SessionInit(cf.Maxlifetime, cf.ProviderConfig)
//...

// SessionInit init redis session
// savepath like redis server addr,pool size,password,dbnum,IdleTimeout second
// e.g. 127.0.0.1:6379,100,astaxie,0,30
func (rp *Provider) SessionInit(maxlifetime int64, savePath string) error {
	rp.maxlifetime = maxlifetime
	configs := strings.Split(savePath, ",")
	if len(configs) > 0 {
		rp.savePath = configs[0]
	}
	if len(configs) > 1 {
		poolsize, err := strconv.Atoi(configs[1])
		if err != nil || poolsize < 0 {
			rp.poolsize = MaxPoolSize
		} else {
			rp.poolsize = poolsize
		}
	} else {
		rp.poolsize = MaxPoolSize
	}
	if len(configs) > 2 {
		rp.password = configs[2]
	}
```
We need to check the length of `configs`. It's not a good practice. 

We need to provide new implementation:
1. check whether `savePath` is in json format...
2. Declare new structure named `ProviderConfig`
3. Unmarshal the `savePath` to `ProviderConfig` instance

This need to be supported in v2.0.1. And checkout branch from develop-2.0.

**Comment by flycash** [comment]
More generally,  the `ProviderConfig` could be unmarshaled from not only json string but also other formats. Supporting json string is mandatory.

**Comment by AllenX2018** [comment]
I can help with this enhancement. You can assign it to me. @flycash
