### ISSUE TITLE
[Feature] Support drop table column in ORM

### ISSUE THREAD

**Issue by gmelodie** [astaxie/beego#4154]
According to the documentation in [Generate Tables](https://beego.me/docs/mvc/model/orm.md#generate-tables):

> The default behavior for Beego is to add additional columns when the model is updated.
You will need to manually handle dropping your columns if they are removed from your model.

Also according to [this comment](https://github.com/astaxie/beego/issues/2469#issuecomment-439625043):

> By default, it can only add or update columns.For the security to tables, most orm frameworks do not delete the column when updating.

I'm not sure why is that. If it makes sense, could we implement some kind of migration to support dropping tables in the ORM?

**Comment by flycash** [comment]
I think that dropping tables or deleting columns are very dangerous. It's not easy to recover from accidentally deleting columns or dropping tables.

> could we implement some kind of migration to support dropping tables in the ORM?

It's not very necessary. Someone suggested that we could provide some migration API that users are able to run some SQL during migration. It may look like:
```go
migration.ExecuteSQL("xxxx")...
```
In fact, this is not a good way to do the migration.

I think running SQL offline manually is a good way.

Here are two similar questions #3637 #3899. The first question said that if the column name is changed from A to B, and then the table contains both A and B columns; The second question said that should we support updating column definition.
