### ISSUE TITLE
beego orm can't support decimal.Decimal?

### ISSUE THREAD

**Issue by 1486327116** [astaxie/beego#4161]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.14

2. What operating system and processor architecture are you using (`go env`)?
mac

3. What did you do?
nothing, i just want to know how to deal with the type decimal in the orm 
like
type A struct {
 Amount decimal.Decimal `orm:"how to write in here"`
}

**Comment by flycash** [comment]
I check docs, we don't support this yet. The docs mentioned `TypeDecimalField` but I don't find this implementation.

But you can use `Fielder` to support `Decimal`.

It's necessary for us to support it.

**Comment by kotori2** [comment]
> Fielder

Fielder looks like something that have never been documented before...
Is there any instruction on how to use it properly?
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/17663689/216853551-b85bd7b5-c6e2-4f79-b800-5cc11ea8379a.png">

**Comment by kotori2** [comment]
Alright. Got it working from #3776

```go

type Decimal struct {
	decimal.Decimal
}

var _ orm.Fielder = new(Decimal)

func (e *Decimal) FieldType() int {
	return orm.TypeTextField
}

func (e *Decimal) SetRaw(value interface{}) error {
	var err error
	switch d := value.(type) {
	case string:
		e.Decimal, err = decimal.NewFromString(d)
	default:
		err = fmt.Errorf("<Decimal.SetRaw> unknown value `%v`", value)
	}
	return err
}

func (e *Decimal) RawValue() interface{} {
	return e.String()
}
```
