### ISSUE TITLE
Consider making it easier to get ControllerInfo

### ISSUE THREAD

**Issue by reggiemcdonald** [astaxie/beego#4162]
1. What version of Go and beego are you using (`bee version`)?
Go: 1.14
Beego: 1.12.2

To get the path template for a particular URL request, one can use `beego.BeeApp.Handlers.FindRouter(*Context)` to get the `ControllerInfo`, and from that, the pattern for the route using `ControllerInfo.GetPattern()`.

While this works, from the perspective of a MiddleWare which isn't working directly with beego `*Context`s, it requires quite a few steps. It would be helpful to have a function along the lines of `PatternFromRequest(*http.Request)` that returns the pattern for a particular route, given an `*http.Request`. It think this is possible because it appears that `FindRouter` only uses the `http.Request` stored in the context.

**Comment by flycash** [comment]
Please check #4125 and #4130. I think it may solve your problem.
