### ISSUE TITLE
Could support situation that using orm without prepare stmt cache

### ISSUE THREAD

**Issue by jiaweizhou** [astaxie/beego#4164]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego: 1.12.2
Go: 1.14

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
I use beego orm visit postgres. In beego 1.12.2, orm use prepare stmt cache, but I can not switch if using cache. 
I find a bug when using cache.
https://stackoverflow.com/questions/60622034/index-is-not-used-when-using-exposed-with-datasource-with-postgres
so I want use beego orm without cache. Can you support this situation?

**Comment by flycash** [comment]
we support this in develop-2.0 #4079. It will be released in v2.0.

**Comment by jiaweizhou** [comment]
thx for your reply.
