### ISSUE TITLE
session 问题

### ISSUE THREAD

**Issue by zhuleilei** [astaxie/beego#4169]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego 1.12.2
go 1.14 - 1.15

2. What operating system and processor architecture are you using (`go env`)?
macos 

3. What did you do?
当我设置了 SessionOn = true 之后,app 下所有的 api(除了静态资源),在请求中没有 session id 的情况下,响应中都会返回一个 session id

4. What did you expect to see?
当请求的处理方法中没有使用任何的 session 操作时,即使请求中没有 session id,也不要去生成一个 session 和响应一个 session id. 只有当请求的处理方法操作了 session 时且请求中没有 session id时,才去生成一个 session 和响应 session id.

5. What did you see instead?

**Comment by flycash** [comment]
`当请求的处理方法中没有使用任何的 session 操作时`——这是一个很难判断的事情。而且，我比较困惑的是，带上session id，对你有很大影响吗？如果我们在A请求里面没有带上session id, 而之后请求B的时候，因为B要操作session id, 用户就无法再找到session ID了。这也是一重顾虑。

**Comment by flycash** [comment]
我把类似的问题暂时关了，新建了一个issue来追踪这个问题。计划在2.0里面提供这一类的支持。

**Comment by zhuleilei** [comment]
> `当请求的处理方法中没有使用任何的 session 操作时`——这是一个很难判断的事情。而且，我比较困惑的是，带上session id，对你有很大影响吗？如果我们在A请求里面没有带上session id, 而之后请求B的时候，因为B要操作session id, 用户就无法再找到session ID了。这也是一重顾虑。

这个,网站下访问量很大的页面和请求都是无状态的,广告投放页和请求也是无状态的.只有几个特殊场景需要用到 session ,没有必要每个人来了都给他开启一个 session, 绝大部分的访问用户到这个 session 过期,他都访问不到需要 session 的业务. 我知道用 cookie+存储我可以实现这个控制,这样的话,我就自己实现了一个 session.     而且你说的那个问题,一般的判断就是如果用户请求过 A,cookie 中有 session id,那么 B业务可以拿到 session id,就能取到 session,就可以访问,如果 B取不到 session,那么要么 session 过期,要么他根本就没有经过请求 A,那么B 业务就不允许他访问..  这个也是很正常的逻辑吧.
