### ISSUE TITLE
 Does the community have plans to add support for postgresql querybuilder？

### ISSUE THREAD

**Issue by hw2018** [astaxie/beego#4171]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

beego:1.12.1
go:1.14

2. What operating system and processor architecture are you using (`go env`)?

Linux amd64

3. What did you do?

In our project , we used postgresql and querybuilder. We had to make corresponding changes based on the community version, and we also needed to maintain it all the time. We hope to see that the community also supports postgresql querybuilder, we don’t need to make any changes

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
As I known, query builder is a tool? So, I don't understand how to support that.

**Comment by hw2018** [comment]
Sorry, I am a little vague. query builder is a tool, but currently only supports mysql and tidb, but in our scenario, we use postgresql, and also use querybuilder, we made corresponding changes to beego orm, my thought is whether the community Support more databases, so we can use it without any modification

https://github.com/astaxie/beego/blob/310161f9d4ff8f68d204217d7495c683a93c86df/orm/qb.go#L49

**Comment by flycash** [comment]
Yes, this is a good idea. 

And I am thinking about merging `QueryBuilder` and `QuerySeter`. They are similar.

I think we need something like "consistent query builder abstraction". We and user use the same abstraction to build the query.

Now, we use string concat to build SQL, it looks not scalable.
