### ISSUE TITLE
In Beego ORM, 'exact' operator is not able to distinguish letter case when working with MySQL

### ISSUE THREAD

**Issue by CadenGuo** [astaxie/beego#4182]
**1. What version of Go and beego are you using (`bee version`)?**
**go version**: go1.13.14
**beego version**: v1.12.1
**MySQL version**: 8.0.15

**2. What operating system and processor architecture are you using (`go env`)?**
**OS**: Mac OS High Sierra v10.13.4
**Processor Architecture**: amd64

**3. What did you do?**
I have a beego app working with **MySQL-8.0.15**. In the database, I have only 1 table called user. The model definition is as following:
```golang
// User model
type User struct {
	Id       int    `orm:"auto;pk" json:"id"`
	Name     string `orm:"size(40)" json:"name"`
	Email    string `orm:"size(40)" json:"email"`
	Username string `orm:"size(70);unique" json:"username"`
	Password string `orm:"size(70)" json:"-"`
}
```
I have the following 2 rows in this table:
<img width="555" alt="Screen Shot 2020-08-23 at 12 23 31 PM" src="https://user-images.githubusercontent.com/37730142/90970783-8f67d800-e53b-11ea-9672-32f4c6990ead.png">

Then I was using the following code snippet to query this table(use beego orm):
```golang
import (
    "models" // model definition package
    "github.com/astaxie/beego/orm"
    "encoding/json"
)
OrmInstance := orm.NewOrm()
var users []*models.User
qs := OrmInstance.QueryTable("user").Filter("username__exact", "sam")
qs.All(&users)
jsonstring, _ := json.Marshal(users)
println(string(jsonstring))
```

**4. What did you expect to see?**
By using "exact" to query, I intended to get only 1 row where `username = sam`. The expected output would be:
```
[{"id":5,"name":"CadenGuoKaitong","email":"123@123.com","username":"sam"}]
```

**5. What did you see instead?**
Instead, I got 2 rows in the querying result where `username = sam` and `username = Sam`:

![Screen Shot 2020-08-23 at 12 46 34 PM](https://user-images.githubusercontent.com/37730142/90971071-ba076000-e53e-11ea-8065-19836ead23bb.png)

**6. What in my mind could be a solution**
I found the `exact` operator defined for MySQL is `= ?`. I think sql like
```sql
select * from dev_db.user where username = binary 'sam';
```
should work. So maybe we change `= ?` to `= BINARY ?` should fix this problem.

_I am a beginner in both Golang and Beego. Please advise on my proposal and correct me anytime should I make any mistake._

**Comment by AllenX2018** [comment]
@flycash 
Need to implement this function?

**Comment by flycash** [comment]
I am not sure whether we should change this to `binary =` because users could change their DB config so that it could be case sensitive.

**Comment by flycash** [comment]
I think we could keep this implementation because users could change their table's config to make case sensitive.

**Comment by flycash** [comment]
@CadenGuo why not use case sensitive configuration for this table?

**Comment by CadenGuo** [comment]
> @CadenGuo why not use case sensitive configuration for this table?

I think you mean changing the collation of the table. For example we apply this sql:
```sql
alter table user convert to character set utf8mb4 collate utf8mb4_0900_as_cs;
```
This will make the `exact` operator case sensitive but will also make `iexact` operator case sensitive in the mean time. Since
```sql
select * from user where username like 'somename'
```
should also follow the collation of the table(or column).

So basically the behaviour of these two operators depends on the table or column's collation. Given the default collation shipped from MySQL is accent insensitive and case insensitive, I still think the behaviour of `exact` operator should by default be case sensitive. And the related information should be provided in the documentation.

**Comment by CadenGuo** [comment]
If you guys decide to adopt this proposal, I'm gonna be happy to help.

**Comment by flycash** [comment]
So, some sqls should be case sensitive but some sqls should not be case sensitive? 
@AllenX2018 it will be very appreciated if you could help to support this.

**Comment by CadenGuo** [comment]
[Here](https://github.com/astaxie/beego/blob/f946a35acd6fa002da765cfbdcda9c393b2f30ee/orm/db_mysql.go#L37) I also found that these four operators: `startswith`, `endswith`, `istartswith`, `iendswith` are not implemented correctly. They just simply employed the `LIKE` expression in the comparison between string like values.

**Comment by CadenGuo** [comment]
Hi, Regarding this thread, it seems no one is working on it, so I have created a PR here #4198

**Comment by jianzhiyao** [comment]
https://github.com/astaxie/beego/pull/4198 was merged, this issue seems should be closed.
