### ISSUE TITLE
beego orm does not support postgresql comment syntax when create table

### ISSUE THREAD

**Issue by bysph** [astaxie/beego#4184]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

beego version 1.12.0
2. What operating system and processor architecture are you using (`go env`)?

linux amd64
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I add "description" in "orm" filed when creating table by beego orm, then I get this error :

"pq: syntax error at or near \"COMMENT\"

it seems like postgresql does not support **COMMENT** syntax in this situation.

4. What did you expect to see?

5. What did you see instead?

**Comment by bysph** [comment]
@DennisMao 
你好，请问这个问题可以帮忙看一下吗？当前beego orm使用的comment语法是不是不支持postgresql呢

**Comment by AllenX2018** [comment]
@bysph 目前是不支持，postgres 使用comment 与其他DB区别还是挺大的，当下如有需要，建议建表后手动添加，
具体操作可以在此查阅：https://postgrespro.com/docs/postgresql/10/sql-comment
