### ISSUE TITLE
How to limit http request rate?

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4206]
How to limit http request rate?

**Comment by flycash** [comment]
We don't support this. It's easy to use `Filter` to do rate limit.

**Comment by helloqhq** [comment]
> We don't support this. It's easy to use `Filter` to do rate limit.

Ok, thank you

**Comment by helloqhq** [comment]
How to respond to the data in the Filter with HTTP status code 200 and json format?

**Comment by flycash** [comment]
There are many methods in `Controller.Ctx.Output`, please try.

**Comment by flycash** [comment]
#4213 similar issue

**Comment by helloqhq** [comment]
> There are many methods in `Controller.Ctx.Output`, please try.

Ok, thank you very much
