### ISSUE TITLE
How to use aggregated function, sum, count...

### ISSUE THREAD

**Issue by Just-Like** [astaxie/beego#4209]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
We don't have aggregation methods, like count(*), sum(*). So you can use "QueryRaw"

**Comment by Just-Like** [comment]
建议在高级查询中拓展一下聚合函数的使用   再使用高级查询中 遇到聚合查询就只能写原生sql了  失去了高级查询的意义

**Comment by Just-Like** [comment]
之前的代码是用的高级查询的，后面产品要我关联一张表后求和，然后我发现我整个代码都要重写了，还是只能用原生sql的那种，
使用高级查询有很多弊端啊。。。

**Comment by flycash** [comment]
道理我都懂=。=就是木有人力啊！

**Comment by AllenX2018** [comment]
@flycash 我尝试去实现的时候，发现`QuerySeter`赋值方法不是那么灵活，例如：

`type Result struct {
	Name string,
	Total int
}`
`var M Result `
`db.QueryTable("users").Aggregates("dept_name,sum(salary) as total").GroupBy("deot_name").All(&M)`

则会：`panic: wrong object type `*main.Result` for rows scan, need *main.Users`

临时产生的数据`sum(salary) as total`并不需要注册 `*modelInfo`，我看了`QuerySeter`所有赋值方法(One、All、Values...)都是需要用到` *modelInfo`获取字段信息，如果是基于`QuerySeter`要实现sum、max、avg等聚合函数，则需一个更灵活地方法去保存临时产生的数据。

**Comment by flycash** [comment]
我看到，`QuerySeter`里面有一个类似的方法`Count`，仿照这个来实现`Sum`呢？我发现已有的`Count`方法也不能满足你这个例子。
应该说，Group by + Count or Sum，并且不仅仅是返回count或者sum的结果，也返回分组的列，貌似都会崩掉。

**Comment by AllenX2018** [comment]
是的，所以需要再实现一个更加灵活地赋值方法，去保存一些临时产生数据，用户可以自定义所需 model，然后赋值到 model，类似`QueryRows`和`QueryRow`那样。

**Comment by flycash** [comment]
> 是的，所以需要再实现一个更加灵活地赋值方法，去保存一些临时产生数据，用户可以自定义所需 model，然后赋值到 model，类似`QueryRows`和`QueryRow`那样。

我大概理解你的意思了。我觉得我们应该考虑重新设计一个model的机制。#4105 讨论了model的隔离机制。这两个问题本质上都是因为我们的Model机制不够灵活引起的。或许我们可以统一考虑这个问题。

就目前的机制下，orm要求在使用之前，一定要初始化Model，我也觉得这个点是值得商榷的。但是因为model涉及到在启动的时候往数据库里面创建数据库表，这方面耦合非常强，所以有点困难。

@jianzhiyao 在这方面做了一些前期调研工作，可以一起交流。

**Comment by AllenX2018** [comment]
我看了`orm`源码，目前的实现逻辑是用`modelInfo`保存所有model字段信息，再把信息注册到数据库，查询的时候也是从`modelInfo`对标所有字段信息，这样做确实有些好处，就是减少`reflect`包调用，从而提升性能，但是，临时产生的数据就无法赋值，我建议是：可以改造一下`QuerySeter`接口所有方法赋值逻辑，或者提供一个新的方法支持自定义model赋值。

**Comment by flycash** [comment]
我觉得可以考虑，如果一个model没有出现，就走解析modelInfo的逻辑。不过这样，代码会很琐碎。

**Comment by AllenX2018** [comment]
@flycash ok,我尝试实现聚合函数功能，并改造一下`QuerySeter`里面`All`、`One`赋值方法。对了，请问一下社区还欢迎新的维护者吗？可以的话，把我带上，我很乐意为社区贡献，也是我的荣幸~！

**Comment by flycash** [comment]
> @flycash ok,我尝试实现聚合函数功能，并改造一下`QuerySeter`里面`All`、`One`赋值方法。对了，请问一下社区还欢迎新的维护者吗？可以的话，把我带上，我很乐意为社区贡献，也是我的荣幸~！

非常欢迎啊！你可以考虑加我微信，dm549042379。我跟你详细说。

**Comment by AllenX2018** [comment]
ok,已经添加~~
