### ISSUE TITLE
installing fatal with bee, thanks!

### ISSUE THREAD

**Issue by lyk1905** [astaxie/beego#4213]
![image](https://user-images.githubusercontent.com/5794483/92454068-b2101700-f1f2-11ea-8214-e65a790e1490.png)

**Comment by flycash** [comment]
It's version conflicts. Please check the version of `gadelkareem/delve`. I think if you reinstall this dependency with the same version that `bee` uses, the issue should be resolved.

**Comment by lyk1905** [comment]
solve by 
go env -w GOPROXY=https://goproxy.io,direct

 go env -w GO111MODULE=on
