### ISSUE TITLE
beego redis interface forgot to add Scan

### ISSUE THREAD

**Issue by targetoyes** [astaxie/beego#4215]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

v1.12.2 latest stable
2. What operating system and processor architecture are you using (`go env`)?
docker ubuntu v16.14 4 process

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I want to use redis scan, and I saw the source that method scan was in beego/cache/redis.go，but was not in beego/cache/cache.go(type Cache interface) 

4. What did you expect to see?
I want to use redis scan to match more keys

5. What did you see instead?
no scan method

**Comment by targetoyes** [comment]
I find solution in test case.
`Redis, err = cache.NewCache("redis", `{"conn": "127.0.0.1:6379"}`)
if err != nil {
	logs.Error("New redis cache error: ", err)
	os.Exit(-1)
}

keys, err := Redis.(*redis.Cache).Scan("beecacheRedis:*")`

why not set it in interface?

**Comment by flycash** [comment]
> I find solution in test case.
> 
> ```
> Redis, err = cache.NewCache("redis", `{"conn": "127.0.0.1:6379"}`)
> if err != nil {
> 	logs.Error("New redis cache error: ", err)
> 	os.Exit(-1)
> }
> 
> keys, err := Redis.(*redis.Cache).Scan("beecacheRedis:*")
> ```
> 
> why not set it in interface?

We have many implementations of this API. Some of them don't support this operation.
