### ISSUE TITLE
怎么查看静态网站下载的zip的原始hash值呢？

### ISSUE THREAD

**Issue by chenyu3050** [astaxie/beego#4217]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
这个问题貌似跟beego没什么关系？要查看zip的hash值，你是指md5吧？你可以考虑使用命令行工具。
