### ISSUE TITLE
memory session provider SessionExists shall use SessionRead to trigger mem provider's SessionUpdate

### ISSUE THREAD

**Issue by ws6** [astaxie/beego#4218]
https://github.com/astaxie/beego/blob/f6519b29a846bdf59a2b86baa011c242f78387d5/session/sess_mem.go#L115

**Comment by flycash** [comment]
You mean we should use `pder.Read(sid)` ?

**Comment by flycash** [comment]
We cannot use `SessionRead` here.
The `SessionRead` will create a new session if not exist.
