### ISSUE TITLE
is it possible to provide dependency injection mode?

### ISSUE THREAD

**Issue by nevernet** [astaxie/beego#4228]
for now, we cannot custom the http request/response, context module. 

for example,  we can't get context outside from controller life circle,  currently the ugly way as below: 
```go
func RegisterBeforeRouterInit() {
	var setContext = func(ctx *context.Context) {

		// we have to register this filter at beginning
		factoryDefault := di.GetDefault()

		factoryDefault.SetShared("context", ctx)
		factoryDefault.SetShared("request", "")
		factoryDefault.SetShared("response", "")

	}

	beego.InsertFilter("*", beego.BeforeRouter, setContext)
}
```

**Comment by flycash** [comment]
Yes, we discussed it several times. We decided to support DI, but we don't have any proposal.

**Comment by nevernet** [comment]
Can i help?

**Comment by flycash** [comment]
If you have any proposals, feel free to make an issue. We can discuss it on that issue. But I think that there are several DI frameworks such as [Google wire](https://github.com/google/wire), so can we build a better DI framework?

**Comment by nevernet** [comment]
Yes, google wire is good framework, i have ideas which inspired by PhalconPHP :)
