### ISSUE TITLE
Error 1205: Lock wait timeout exceeded; try restarting transaction 

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4238]
I encountered this error when using the orm transaction

`Error 1205: Lock wait timeout exceeded; try restarting transaction `

**Comment by flycash** [comment]
[innodb_lock_wait_timeout](https://severalnines.com/database-blog/how-fix-lock-wait-timeout-exceeded-error-mysql). 

I think you should check your codes whether there are SQLs or transactions holding a lock for a long time.

**Comment by helloqhq** [comment]
> [innodb_lock_wait_timeout](https://severalnines.com/database-blog/how-fix-lock-wait-timeout-exceeded-error-mysql).
> 
> I think you should check your codes whether there are SQLs or transactions holding a lock for a long time.

Solved, the transaction was not submitted when the exception occurred, thank you very much
