### ISSUE TITLE
error when migrate with ssl verification

### ISSUE THREAD

**Issue by gianmegantara** [astaxie/beego#4241]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go 1.15 
Bee 1.11

2. What operating system and processor architecture are you using (`go env`)?
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wednesdaaay/.cache/go-build"
GOENV="/home/wednesdaaay/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/wednesdaaay/Documents/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wednesdaaay/Documents/Go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go1.15/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.15/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/wednesdaaay/Documents/Go/src/github.com/socialmethod/kerry-api-v2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build116673747=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
i want to migrate my migration file, the connection string seem work on the app i have test and query for somenthing, but when i try migrate using the connection string that i have used in connection it doesnt work on migration script, this is my migrate script :
bee migrate -driver=postgres -conn="host=host_name port=port dbname=db_name user=user_name password=password sslmode=verify-full sslrootcert=conf/cert.pem"

4. What did you expect to see?
i want to migrate succesfully

5. What did you see instead?
here iam try to migrate the db on the cloud using the migration script, the error come like this:
2020/09/30 11:08:48 INFO     ▶ 0004 |> [ORM]2020/09/30 11:08:48 register db Ping `default`, open conf/cert.pem: no such file or directory
2020/09/30 11:08:48 INFO     ▶ 0005 |> must have one register DataBase alias named `default`

**Comment by flycash** [comment]
When you use SSL, we will look up the certification files in the directory `config`. This error means that we do not find out the files.

**Comment by gianmegantara** [comment]
iam sure that cert file on conf/cert.pem directory, the wirdness that i found is, the connection string is work when i run the app and connect to the db, but when i try migrate the table the error come,

**Comment by flycash** [comment]
I think I made a mistake.
Could you use full path of `cert.perm` in your script?

**Comment by flycash** [comment]
I think using full path will resolve this problem. The root cause is that `sql` lib can not find the file `sslrootcert=conf/cert.pem`.

The error is not from beego.
