### ISSUE TITLE
bee工具安装报错

### ISSUE THREAD

**Issue by JeremyHash** [astaxie/beego#4242]
go 1.15.2
bee 工具在Windows下和Linux下安装都会报相同的错误
![image](https://user-images.githubusercontent.com/46062436/94647434-048cb100-0323-11eb-8931-56117576deb9.png)

**Comment by flycash** [comment]
看起来是版本冲突问题，你检查一下本地的依赖和bee所期望的依赖版本是否一致

**Comment by JeremyHash** [comment]
可能是bee工具没有更新，无法在最新的golang版本上使用

**Comment by HHHHscody** [comment]
打开go module，go env -w GO111MODULE=on，然后安装补丁 go get github.com/gadelkareem/bee@fix-mod 就可以了
