### ISSUE TITLE
升级后，路由参数 转义了，这对程序极度不友好。

### ISSUE THREAD

**Issue by wjcgo** [astaxie/beego#4258]
升级到  1.12.1、1.12.2 升级后，路由参数 转义了，这对程序极度不友好。也是就input 的 url 全部转义了，参数为中文就惨了。

**Comment by flycash** [comment]
在develop里面已经还原回去了。
#4221
这是一个很坑的问题。在不转义的时候，会出现路由匹配不准确问题，在转义之后还出现参数读取问题。你可以看这个PR link过去的两个issue。
要彻底解决非ASC字符路径的问题，有点复杂。
