### ISSUE TITLE
入库时怎么将特殊字符转义处理，比如\t \n等，类似php那样入库时处理下

### ISSUE THREAD

**Issue by helloqhq** [astaxie/beego#4263]
入库时怎么将特殊字符转义处理，比如\t \n等，类似php那样入库时处理下

beego的orm好像不支持转义处理

**Comment by flycash** [comment]
我个人看法是这种其实是业务场景下的需求了。特殊字符的转义，编码和解码是配对的，可能不同的人会有不同的方案。当然在2.0以后，可以通过我们提供的`orm.Filter`功能来扩展这种逻辑。

**Comment by helloqhq** [comment]
> 我个人看法是这种其实是业务场景下的需求了。特殊字符的转义，编码和解码是配对的，可能不同的人会有不同的方案。当然在2.0以后，可以通过我们提供的`orm.Filter`功能来扩展这种逻辑。

了解了，多谢
