### ISSUE TITLE
change levelPrefix to be used universally

### ISSUE THREAD

**Issue by hhstu** [astaxie/beego#4267]
here is beego log  levelPrefix :

var levelPrefix = [LevelDebug + 1]string{"[M]", "[A]", "[C]", "[E]", "[W]", "[N]", "[I]", "[D]"}

example beego log:

{2020/10/15 13:25:27.312 [I] [api.go:37]  REST service listening on 0.0.0.0:8000}

what i want ：

var levelPrefix = [LevelDebug + 1]string{"[WWARN]", "[INFO]", "[DEBUG]"....}

why:
when  i use grafana+loki to  show logs，grafana could  not   get  the log level because levelPrefix of beego  not   universally.

grafana dont support:

{2020/10/15 13:25:27.312 [I] [api.go:37]  REST service listening on 0.0.0.0:8000}       
   
grafana support:

{2020/10/15 13:25:27.312 [INFO] [api.go:37]  REST service listening on 0.0.0.0:8000}     it is  ok!

https://github.com/grafana/grafana/blob/v6.7.0/packages/grafana-data/src/types/logs.ts

**Comment by hhstu** [comment]
一句话，不要用 levelPrefix

**Comment by flycash** [comment]
In v2.0, we support custom log format. The interface is `LogFormatter`. 
Please check [formatter.go](https://github.com/astaxie/beego/blob/develop-2.0/core/logs/formatter.go)
You can implement this interface.

For v1.x, we don't want to support this.

V2.0.0 will be released soon
