### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by osmanmakal** [astaxie/beego#4269]
Hello,

When will the new version be released?

There are some features I need, these are develop branch. When using beego projects, I don't want to choose develop branch.

It would be nice if he had a new version these days

@flycash @astaxie

**Comment by flycash** [comment]
We plan to release v2.0 and v1.12.3 next month.

**Comment by osmanmakal** [comment]
@flycash @astaxie Is there an estimated time? We are considering quitting beego due to the Samesite cookie problem. Would you recommend using develop brach instead of leaving beego?

Framework is very old now.

**Comment by flycash** [comment]
https://github.com/astaxie/beego/releases/tag/v1.12.3 @osmanmakal
