### ISSUE TITLE
main函数中beego.run()函数后面写的语句不执行 这是特性还是bug呢 

### ISSUE THREAD

**Issue by GodGavin** [astaxie/beego#4270]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego v1.11.0
go version go1.15.2 
2. What operating system and processor architecture are you using (`go env`)?
windows/amd64

**Comment by flycash** [comment]
`Run` 是同步的，意味着直到返回才会执行后面的代码。你可以考虑使用
```
go beego.Run()
```
