### ISSUE TITLE
log support print package name

### ISSUE THREAD

**Issue by hhstu** [astaxie/beego#4273]
希望打印日志时支持打印包名。目前beego支持打印文件名和行号，但在多个文件名重复的情况下定位日志在哪个文件不是很方便！

**Comment by flycash** [comment]
你可以设置打印全路径文件名。
```go
	logs.EnableFullFilePath(true)
```
目前我认为这个足以满足你的需求了。只不过因为全路径名实在是太长太长了，可能看起来有点不太方便。我们正在考虑的是，如何简写这种路径名。即便使用包名也有类似的问题。现有的一种考虑是，只输出全路径上的第一个字符，例如/aaaa/bbbb输出成为/a/b。
