### ISSUE TITLE
orm.RunSyncdb 问题

### ISSUE THREAD

**Issue by scauxiaoxu** [astaxie/beego#4288]
beego 版本：v1.12.2

使用orm.RunSyncdb()创建mysql数据表的时候 可以指定ENGINE和CHARSET吗

项目中想使用orm.RunSyncdb自动创建表，同时ENGINE和CHARSET不是我想要的（默认库编码问题），查看了文档 ，没有发现相关功能描述

**Comment by AllenX2018** [comment]
目前不支持，当前逻辑是使用数据库默认的ENGINE和CHARSET。

**Comment by scauxiaoxu** [comment]
ok thanks

**Comment by scauxiaoxu** [comment]
看了下文档 ENGINE 可以通过自定义 TableEngine() 方法设置对应引擎，但是  CHARSET 还是没找到对应设置的方法。。。。。

**Comment by flycash** [comment]
> 看了下文档 ENGINE 可以通过自定义 TableEngine() 方法设置对应引擎，但是 CHARSET 还是没找到对应设置的方法。。。。。

哈哈哈，被你发现了。ENGINE是有的。然后CHARSET是没有的。你可以考虑给我们提一个PR，支持一下。感觉不是特别难。

**Comment by scauxiaoxu** [comment]
下午为此又看了下源码 确实没有的 有机会一定支持  thanks
