### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by ndcinfra** [astaxie/beego#4307]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.15.4
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 2
├── GOPATH    : /root/work
├── GOROOT    : /snap/go/5646
├── Compiler  : gc
└── Date      : Wednesday, 11 Nov 2020

2. What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/work/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6715"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6715/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build366477903=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

nothing. just  run go build. it was all good til Yesterday. But Today, the error happen

and I got these errors..

main.go:14:2: cannot find package "github.com/astaxie/beego/logs" in any of:
	/snap/go/6715/src/github.com/astaxie/beego/logs (from $GOROOT)
	/root/work/src/github.com/astaxie/beego/logs (from $GOPATH)
main.go:15:2: cannot find package "github.com/astaxie/beego/orm" in any of:
	/snap/go/6715/src/github.com/astaxie/beego/orm (from $GOROOT)
	/root/work/src/github.com/astaxie/beego/orm (from $GOPATH)
main.go:16:2: cannot find package "github.com/astaxie/beego/plugins/cors" in any of:
	/snap/go/6715/src/github.com/astaxie/beego/plugins/cors (from $GOROOT)
	/root/work/src/github.com/astaxie/beego/plugins/cors (from $GOPATH)
../github.com/ndcinfra/platform-gl/controllers/base.go:13:2: cannot find package "github.com/astaxie/beego/validation" in any of:
	/snap/go/6715/src/github.com/astaxie/beego/validation (from $GOROOT)
	/root/work/src/github.com/astaxie/beego/validation (from $GOPATH)

please help me

**Comment by flycash** [comment]
I guess that you update beego's version. Could you show me the beego's structures?
We had release v2.0.0-beta and the structure has big update. So if you are using beego 2.0.0, old project will failed.

**Comment by flycash** [comment]
Or you can try `go get github.com/astaxie/beego@v1.12.3`.

**Comment by ndcinfra** [comment]
@flycash 
Thank you. first I turn on the GO111MODULE="on", and solve this issue urgently.

this is my beego sttucture.
<img width="715" alt="Screen Shot 2020-11-11 at 10 11 36 AM" src="https://user-images.githubusercontent.com/47907018/98848408-871a8d00-2406-11eb-8d2d-95c433eb6a2c.png">
<img width="633" alt="Screen Shot 2020-11-11 at 10 12 03 AM" src="https://user-images.githubusercontent.com/47907018/98848409-8a157d80-2406-11eb-8e94-74e5f3201988.png">

**Comment by flycash** [comment]
This is the beego v2.0. And `github.com/astaxie/beego/logs` belongs to v1.x. 
If you want to use v1.x, just run `go get github.com/astaxie/beego@v1.12.3`, `1.12.3` is the newest stable version for 1.x. 
And if you want to use v2.0.0, feel free to create issues, I hope to get some feedbacks about v2.x

**Comment by flycash** [comment]
similar issue #4308

**Comment by YoungsoonLee** [comment]
Thank you ~! @flycash

**Comment by flycash** [comment]
I closed it and please follow #4308
