### ISSUE TITLE
Problem of Cache.GetMulti: Why does the function append error message to returned result

### ISSUE THREAD

**Issue by AllenX2018** [astaxie/beego#4311]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Branch: develop

2. What operating system and processor architecture are you using (`go env`)?
--

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Code URL: https://github.com/astaxie/beego/blob/26bc9e72645344d65dc79fd39f2ec0dddeb3d617/client/cache/memory.go#L81
```go
// client/cache/memory.go
func (bc *MemoryCache) GetMulti(ctx context.Context, keys []string) ([]interface{}, error) {
	var rc []interface{}
	for _, name := range keys {
		val, err := bc.Get(context.Background(), name)
		if err != nil {
			rc = append(rc, err)
		} else {
			rc = append(rc, val)
		}
	}
	return rc, nil
}
```

Code URL:
https://github.com/astaxie/beego/blob/26bc9e72645344d65dc79fd39f2ec0dddeb3d617/client/cache/ssdb/ssdb.go#L59
```go
// client/cache/ssdb/ssdb.go
func (rc *Cache) GetMulti(ctx context.Context, keys []string) ([]interface{}, error) {
	// ...
	for i := 0; i < size; i++ {
		values = append(values, err)
	}
	return values, nil
}
```

In memory cache, file cache and ssdb cache, the error will be appended to returned result. The caller will mistakenly consider the execution as normal and use the error message in returned slice as acquired value.

4. What did you expect to see?
I think the `GetMulti` of `memory` , `file` and `ssdb` should add `nil` to returned result when there is error.

In addition, I think `GetMulti` should return error message instead of `nil` to caller to let the caller know it when there is something unexpected happend.

5. What did you see instead?
See "3. What did you do?"

**Comment by AllenX2018** [comment]
In addtion, I see `GetMulti` of file, memory, ssdb cache will return a **nonempty** slice such as `[val1, nil, val2]`, `[val1, val2, nil]` or `[nil, nil, nil]` when there is something wrong happend.  However,  the `GetMulti` of redis and memcache will return an **empty** slice possibly.

Should we unify their return ?

**Comment by flycash** [comment]
> Should we unify their return ?
Yes.

I think when we got some errors, returning an empty array and error is the best solution.

**Comment by flycash** [comment]
> Should we unify their return ?
Yes.

I think when we got some errors, returning an empty array and error is the best solution.

**Comment by AllenX2018** [comment]
> I think when we got some errors, returning an empty array and error is the best solution.

But how about handle the error of "the key is expired" ? Consider a situation, there are three keys in cache and only one key is expired.  Returning empty array if theres is an error will make we can't get other two valid key-value.

**Comment by flycash** [comment]
> But how about handle the error of "the key is expired" ? Consider a situation, there are three keys in cache and only one key is expired. Returning empty array if theres is an error will make we can't get other two valid key-value.

If this is a tolerable error, like expired error, or key is invalid (we can not find the key-value pair in cache), we return other valid key-value pair. 

Or we could keep "try-best" logic. 

But the question is that, for example, if we fetch data from (k1, k2, k3) and got result (v1, error1, error2).

What should we return? [v1], error1 ?

**Comment by AllenX2018** [comment]
> But the question is that, for example, if we fetch data from (k1, k2, k3) and got result (v1, error1, error2).

I think we can keep "try-best"logic. The funciton return `(v1, nil, nil)` and error message like `fmt.Sprintf("%s; %s", error1, error2)`, 
because caller really can't get the `v2`, `v3` from cache so he gets `nil` and should use `nil` as a result.
In addtion, returnend error message including `error1` and `error2` can tell the caller there's some problems with `k2` and `k3`, though users can use `[v1, nil, nil]` as a result.

**Comment by flycash** [comment]
> > But the question is that, for example, if we fetch data from (k1, k2, k3) and got result (v1, error1, error2).
> 
> I think we can keep "try-best"logic. The funciton return `(v1, nil, nil)` and error message like `fmt.Sprintf("%s; %s", error1, error2)`,
> because caller really can't get the `v2`, `v3` from cache so he gets `nil` and should use `nil` as a result.
> In addtion, returnend error message including `error1` and `error2` can tell the caller there's some problems with `k2` and `k3`, though users can use `[v1, nil, nil]` as a result.

Ok, you can do it.
