### ISSUE TITLE
beego v1.12.4 annotations router bug

### ISSUE THREAD

**Issue by weirubo** [astaxie/beego#4320]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go v1.15.5
beego v1.12.4

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

bee new web
cd web
go get github.com/astaxie/beego@develop
bee run
Warning：[W]  init global config instance failed. If you donot use this, just ignore it.  open config/app.conf: no such file or directory
mv conf config
bee run
Warning is missing, but miss this step([I] [parser.go:413]  generate router from comments).

4. What did you expect to see?
beego can not generate router from comments.

5. What did you see instead?
generate router from comments.

**Comment by flycash** [comment]
#4323
