### ISSUE TITLE
SessionRegenerateID just ignored errors, this may cause program panic

### ISSUE THREAD

**Issue by lixianyang** [astaxie/beego#4321]
session.go Manager.SessionRegenerateID not return error information. And in Controller.SessionRegenerateID method, the c.CruSession may nil. Any method call of c.CruSession may cause `panic: runtime error: invalid memory address or nil pointer dereference`, and can't get exact error information.

https://github.com/goharbor/harbor/issues/9841#issuecomment-729058629

**Comment by flycash** [comment]
It will be released in v1.12.4 in Jan 2021.

**Comment by lixianyang** [comment]
Any plan for v1.12.4 release ?

**Comment by flycash** [comment]
you could use branch develop-1.x .
Now all bug fixed are merged into it.
