### ISSUE TITLE
bee run 提示我找不到“github.com/astaxie/beego/server/web”这个包

### ISSUE THREAD

**Issue by wilde-1206** [astaxie/beego#4322]
大家好，新手一枚，bee run的时候提示我找不到“github.com/astaxie/beego/server/web”这个包，但我明明已经安装了。
请问是什么问题？谢谢

**Comment by wilde-1206** [comment]
已解决，安装的时候不要按照教程的来
安装命令：go get -u github.com/astaxie/beego@develop

**Comment by flycash** [comment]
https://github.com/beego/bee/pull/741
我更新了一下bee里面的beego版本，使用了develop最新的commit id
