### ISSUE TITLE
the method of Distinct could not work

### ISSUE THREAD

**Issue by weirubo** [astaxie/beego#4333]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.15.5
beego v1.12.4-0.20201201035253-54ab211f00d9

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I use Distinct method of the QuerySeter interface cannot work.

4. What did you expect to see? 

5. What did you see instead?

**Comment by AllenX2018** [comment]
@weirubo Hi~
Can you provide a code to reproduce the error?

**Comment by AllenX2018** [comment]
Please provide `models.User` data

**Comment by weirubo** [comment]
> Please provide `models.User` data
you can see this sql.
```
/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80019
 Source Host           : localhost:3306
 Source Schema         : beego_web

 Target Server Type    : MySQL
 Target Server Version : 80019
 File Encoding         : 65001

 Date: 02/12/2020 21:08:15
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for beego_user
-- ----------------------------
DROP TABLE IF EXISTS `beego_user`;
CREATE TABLE `beego_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `name` varchar(30) NOT NULL DEFAULT '',
  `age` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '年龄',
  `created` datetime NOT NULL,
  `updated` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `beego_user_age` (`age`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of beego_user
-- ----------------------------
BEGIN;
INSERT INTO `beego_user` VALUES (1, 'frank', 29, '2020-11-30 10:27:10', '2020-11-30 10:27:10');
INSERT INTO `beego_user` VALUES (2, 'Lucy', 15, '2020-11-30 10:42:29', '2020-11-30 10:42:29');
INSERT INTO `beego_user` VALUES (3, 'hanmeimei', 14, '2020-11-30 18:56:56', '2020-11-30 18:56:56');
INSERT INTO `beego_user` VALUES (4, 'ruby', 16, '2020-11-30 19:06:30', '2020-11-30 19:06:30');
INSERT INTO `beego_user` VALUES (5, 'hunt', 0, '2020-11-30 19:07:39', '2020-11-30 20:32:34');
INSERT INTO `beego_user` VALUES (8, 'kitty', 20, '2020-11-30 20:11:10', '2020-11-30 20:11:10');
INSERT INTO `beego_user` VALUES (9, 'phper', 30, '2020-11-30 20:18:56', '2020-11-30 20:18:56');
INSERT INTO `beego_user` VALUES (10, 'gopher', 31, '2020-11-30 20:18:56', '2020-11-30 20:18:56');
INSERT INTO `beego_user` VALUES (11, 'Alan', 37, '2020-12-01 16:51:50', '2020-12-01 16:51:50');
INSERT INTO `beego_user` VALUES (13, 'Frank2', 18, '2020-12-02 14:44:57', '2020-12-02 14:44:57');
INSERT INTO `beego_user` VALUES (14, 'Frank3', 18, '2020-12-02 15:55:24', '2020-12-02 15:55:24');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by AllenX2018** [comment]
@weirubo 
Get the sql statement according to the code you provide
```sql
SELECT DISTINCT T0.`id`, T0.`name`, T0.`age`, T0.`created`, T0.`updated` FROM `beego_user` T0 WHERE T0.`id` > 9
```

These T0.`id`, T0.`name`, T0.`age`, T0.`created`, T0.`updated` field data must all be the same to exclude

**Comment by weirubo** [comment]
> @weirubo
> Get the sql statement according to the code you provide
> 
> ```sql
> SELECT DISTINCT T0.`id`, T0.`name`, T0.`age`, T0.`created`, T0.`updated` FROM `beego_user` T0 WHERE T0.`id` > 9
> ```
> 
> These T0.`id`, T0.`name`, T0.`age`, T0.`created`, T0.`updated` field data must all be the same to exclude

so how can I to appoint the field of Distinct method？

**Comment by flycash** [comment]
@AllenX2018 I think the SQL looks not right. It should be 
```sql
SELECT DISTINCT (T0.`id`, T0.`name`, T0.`age`, T0.`created`, T0.`updated`) FROM `beego_user` T0 WHERE T0.`id` > 9
```

And I don't know how to use `DISTINCT` to generate SQL like:
```
SELECT DISTINCT (T0.`id`) FROM `beego_user` T0 WHERE T0.`id` > 9
```

**Comment by AllenX2018** [comment]
@flycash  This sql statement will report an error, you can try it in DB.
```sql
SELECT DISTINCT (T0.`id`, T0.`name`, T0.`age`, T0.`created`, T0.`updated`) FROM `beego_user` T0 WHERE T0.`id` > 9
```
PRIMARY KEY (`id`),no need to distinguish.
```sql
SELECT DISTINCT (T0.`id`) FROM `beego_user` T0 WHERE T0.`id` > 9
```

**Comment by AllenX2018** [comment]
@weirubo  
It is recommended to filter the data after querying.

**Comment by weirubo** [comment]
Yesterday，I use this code get the right result.
`num, err := o.QueryTable(new(models.User)).Filter("id__gt", 9).Distinct().All(&users, "Age")`
The method of DIstinct should with the method of All use together.
