### ISSUE TITLE
MaxUploadSize missing in BConfig but is mentioned in docs

### ISSUE THREAD

**Issue by welblaud** [astaxie/beego#4343]
I would be happy to improve the docs' part associated with file uploads but I need to clear one thing: 

`MaxUploadSize` is mentioned as a setting for the overall size of the batch of files uploaded but it apparently does not work, it is not a valid option (it seems `beego.BConfig.MaxUploadSizie` simply does not exist); how's that with this setting?

I have also just figured out there is a great function, `GetFiles`, which works perfectly, is documented per se but is not mentioned in the docs. I would add it too.

**Comment by welblaud** [comment]
Closing, the setting is for version 2+...

**Comment by flycash** [comment]
It was added into beego v2.x. If you are using beego v1.x, you can not find that. And good news is that we will release v2.0.0 in few days.
Here is the PR: https://github.com/astaxie/beego/pull/4275/files
And I found it in my computer:
![image](https://user-images.githubusercontent.com/9923838/101924937-3c11b680-3c0c-11eb-9c53-fecae4329f45.png)

**Comment by welblaud** [comment]
Great, thanks a lot, that makes sense :) I am looking forward to the new version!
