### ISSUE TITLE
[orm] 支持[]byte定义出mysql的blob字段

### ISSUE THREAD

**Issue by bronze1man** [astaxie/beego#483]
需要一种方法向数据库里面储存二进制数据,(图片,bson序列化后的字符串,等等...)
mysql数据库的longtext类型会进行编码处理...

**Comment by lei-cao** [comment]
@bronze1man Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  closeable

**Comment by bronze1man** [comment]
It is ok to close, i do not use beego right now.

**Comment by astaxie** [comment]
I will close it as it's not a really requirement
