### ISSUE TITLE
数据库建表字段大小写问题

### ISSUE THREAD

**Issue by mylady** [astaxie/beego#514]
不好意思我翻了半天ISSUE里面也没有看到问这个的，不知道是不是大家都默认这个规则，如果说的不对请见谅。
数据库postgres，数据表的表结构如下
表名：Test_User
字段：
Id  serial NOT NULL
Age int NOT NULL
....

如果我要在beego中声明一个类型对应这张表的话
type User struct{
    Id int 
    Age int 
}
在注册模型的时候使用prefix可以解决表名的问题
但是数据库中的字段首字母都是大写的，当通过QuerySeter执行All的时候，beego底层的sql语句执行的是如t0.id,t0.age，最后的结果就是t0.id不存在
如果使用orm:"column(Age)"，sql语句仍然会被全部转换为小写，源代码里也是直接tolower的，想问一下这个是已知的bug还是有其他原因导致必须这样处理，改数据库列名也是个办法但是如果不能改怎么办

**Comment by vincent3i** [comment]
@slene 
建议orm.go的QueryTable方法(line399)也一起修正一下，如果传入参数本身就是string的，完全没有必要再为其转换，否则在mysql等大小写敏感的环境下，对于查询字段还是''这种大小写敏感的方式的SQL，就会带来极大的困惑和问题

**Comment by lei-cao** [comment]
@mylady Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  can be closed or new ticket for @vincent3i 's suggestion.
