### ISSUE TITLE
form render中 可以对value设数值吗

### ISSUE THREAD

**Issue by yaotian** [astaxie/beego#543]
比如，struct中有int类型，如果为它设置数值的话，默认值是0，可前端展示的时候并不想让0显示出来，而是空白。

<input type=text name=points value="0" placeholder="please input the points">

并不想将0现实出来，否则用户看不到placeholder的信息 

所以想对value设为""

**Comment by lei-cao** [comment]
@yaotian Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
