### ISSUE TITLE
[bug][orm] Update一个struct,其中的id指向不存在的id时,不报错,请修改为报错.以便进行错误处理

### ISSUE THREAD

**Issue by bronze1man** [astaxie/beego#556]

**Comment by lei-cao** [comment]
@bronze1man Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by bronze1man** [comment]
I do not use beego right now.@lei-cao you can close this issue,if you do not understand it.

**Comment by astaxie** [comment]
I will close it as it's not a really requirement
