### ISSUE TITLE
[orm] 关联查询是否必须设置外键？

### ISSUE THREAD

**Issue by lubia** [astaxie/beego#579]
想要实现关联查询，但又不想使用外键造成表间耦合

```
type Item struct{
    ItemID string
    AccountID string
    Name string
}

type Order struct{
    OrderID string
    Year string
    ItemID string
}
```
这两个struct会映射到数据库，ItemID这个字段在两个字段有关联关系，现在已知Item中的AccountID，想查到Order中的Year字段。

不使用外键的情况下，请问怎样查询到想要的结果?

**Comment by lei-cao** [comment]
@lubia Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  can close
