### ISSUE TITLE
validation能否在model的tag上增加自定义message输出

### ISSUE THREAD

**Issue by panderman** [astaxie/beego#604]
现在使用tag只能类似valid:"Required"，不能写入message，导致现在实体验证失败全是e文出错信息，如果修改validation.MessageTmpls也不灵活，因为他的信息是写死的

**Comment by lei-cao** [comment]
@panderman Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by miraclesu** [comment]
@panderman you can set the notice messages like by replace the [validation.MessageTmpls](https://github.com/astaxie/beego/blob/master/validation/validators.go#L25), just like:
```
validation.MessageTmpls["Required"] = "不能为空"
validation.MessageTmpls["Min"] = "最小值为 %d"
...
```

or you can wait the next version, use the [SetDefaultMessage](https://github.com/astaxie/beego/blob/develop/validation/validators.go#L71) to rest the notice messages.

@astaxie close?
