### ISSUE TITLE
[Proposal] Layout sections in single template file

### ISSUE THREAD

**Issue by Lafriks** [astaxie/beego#619]
Would be nice if sections in TplNames template file could be written like this:
{{LayoutSection 'HtmlHead'}}
<style>
     h1 { color: red; }
</style>
{{EndLayoutSection}}
and everything between LayoutSection and EndLayoutSection would be rendered in layouts ex. {{.HtmlHead}}.

Everything else that is outside LayoutSection and EndLayoutSection block would go into {{.LayoutContent}} just as it is now. Of course it would still need to be backward compatible with how it is now.

It would make layouts a lot more flexible, otherwise even if script/style/etc is used only in single page you still need to place it in separate file and that makes a lot of mess in view folder.

**Comment by lishuhao** [comment]
> Why we defined the LayoutSection? I think it's should reuse in other template.
个人认为，能重用的代码基本上已经放到layout里了，比如jquery和bootstrap; 而内联的css和js 大多是针对单个页面的，很难重用吧

**Comment by mrtwenty** [comment]
个人觉得楼主提的很好啊，一个子模板页面可以有单独需要的js、css，这样需要单独引入，太麻烦了。
