### ISSUE TITLE
The same table name in different database while register models

### ISSUE THREAD

**Issue by xujinzheng** [astaxie/beego#623]
while I register the table with the same name in different database, the orm will throw the panic to tell me the model must be unique, I think beego could improve orm for support this.

``` go
o:=orm.NewOrm("database")

func NewOrmWithDatabase(databaseName string)

or 

func NewOrm(databaseName ...string)

orm.RegisterModels("database", models)
```

**Comment by lishuu** [comment]
Same problem

**Comment by DennisMao** [comment]
@xujinzheng  you can register the model by using prefix-name.  ```
orm.RegisterModelWithPrefix("prefix_", new(User))
```
https://beego.me/docs/mvc/model/orm.md#registermodelwithprefix

**Comment by ehovel** [comment]
> @xujinzheng you can register the model by using prefix-name.
> 
> ```
> orm.RegisterModelWithPrefix("prefix_", new(User))
> ```
> 
> https://beego.me/docs/mvc/model/orm.md#registermodelwithprefix

must change database tablename ?

**Comment by flycash** [comment]
follow #4105
