### ISSUE TITLE
[Proposal] Add a function for limiting the max number of connections in a service

### ISSUE THREAD

**Issue by cloudaice** [astaxie/beego#651]
### 中文

一个Web服务为了实现自我保护，可以设置一个最大同时连接数，当服务器当前的连接数超过某一个值的时候，对于后来的连接进行拒绝连接。这个功能可以在TCP接受连接的时候做。大家Beego是否需要添加一个这样的功能呢？

### English
A web service should protect itself, do you think this framework should support a number for max connections, if the connections is over this number , this service will reject this request.

**Comment by AsGz** [comment]
https://godoc.org/golang.org/x/net/netutil

**Comment by lei-cao** [comment]
@cloudaice Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by cloudaice** [comment]
@lei-cao OK,  I have updated my issue, but my english is pool,  do you think it is enough.

**Comment by lei-cao** [comment]
@cloudaice  hey thank. It's very good actually~ Also better to use English in the title as well

**Comment by liganggit** [comment]
@work-jlsun 小部分请求在秒级别了6，7s， 不像是gc 造成的问题 这个问题有解么？

**Comment by leiboo** [comment]
请问当前版本中，是否已经添加了这个功能？
如果要在beego中使用LimitListener或者ConnState回调函数，应该怎么做？
