### ISSUE TITLE
orm 转json 自动处理时间格式

### ISSUE THREAD

**Issue by zihuxinyu** [astaxie/beego#686]
type Portal_user struct{
Id int
User_code string orm:"pk"
Opdate time.Time
Updatedat time.Time orm:"auto_now_add;type(datetime)"

}
var pulist []*Portal_user
o := orm.NewOrm()
o.QueryTable("portal_user").All(&pulist)

能否从Portal_user 的struct 上设置时间格式呢？
this.ServeJson() 转换时间结果默认是{"Updatedat":"2014-07-07T23:58:28+08:00"}
我想要orm 自动 转换结果为{"Updatedat":"2014-07-07 23:58:28"} 这样能否实现呢

**Comment by MatrixYuri** [comment]
@athurg  orm里好像不认自定义的类型，会报错
`field: models.Repost.Time, unsupport field type <*models.JSONTime Value>, may be miss setting tag`

其中`JSONTime`是这样的
```
type JSONTime time.Time
```

如果beego能支持这样的自定义type，通过tag告诉orm这个类型其实就是time.Time，也许可以解决这个问题。
比如
```
type Post struct {
    time JsonTime `orm:"realtype(time.Time)"`
}
```
但是研究了一下orm的源码，`getFieldType()`那里不太懂如何下手...不是很熟反射的用法....

**Comment by lei-cao** [comment]
@zihuxinyu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by Orefa** [comment]
@astaxie 关闭是找到解决办法了吗？怎么用呢

**Comment by zhujiarong** [comment]
meet the same problem

**Comment by satng** [comment]
this's a very serious problem, we need it

**Comment by satng** [comment]
now i hava to do  this 

modify the go source  "/usr/local/go/src/time/time.go"


// MarshalJSON implements the json.Marshaler interface.
// The time is a quoted string in RFC 3339 format, with sub-second precision added if present.
func (t Time) MarshalJSON2() ([]byte, error) {
	if y := t.Year(); y < 0 || y >= 10000 {
		// RFC 3339 is clear that years are 4 digits exactly.
		// See golang.org/issue/4556#c15 for more discussion.
		return nil, errors.New("Time.MarshalJSON: year outside of range [0,9999]")
	}

	b := make([]byte, 0, len(RFC3339Nano)+2)
	b = append(b, '"')
	b = t.AppendFormat(b, RFC3339Nano)
	b = append(b, '"')
	return b, nil
}
func (t Time) MarshalJSON() ([]byte, error) {
	if y := t.Year(); y < 0 || y >= 10000 {
		// RFC 3339 is clear that years are 4 digits exactly.
		// See golang.org/issue/4556#c15 for more discussion.
		return nil, errors.New("Time.MarshalJSON: year outside of range [0,9999]")
	}

	b := make([]byte, 0, len("2006-01-02 15:04:05")+2)
	b = append(b, '"')
	b = t.AppendFormat(b, "2006-01-02 15:04:05")
	b = append(b, '"')
	return b, nil
}

**Comment by jockchou** [comment]
好蛋疼的问题，我现在只能把数据库里面的datetime类型，改成用int。然后所有接口里面都是整数来表示时间。
