### ISSUE TITLE
[orm]pqsql对uuid数据格式的支持

### ISSUE THREAD

**Issue by tossp** [astaxie/beego#695]
pqsql原生支持uuid，能否做支持？
现在在自动建表的时候，uuid为字符串格式，有点影响性能

**Comment by silviucm** [comment]
Hello,

Just following up on this one:

Is it possible to add: "uuid" : "uuid" inside 
https://github.com/astaxie/beego/blob/master/orm/db_postgres.go

Inside this map:
// postgresql column field types.
var postgresTypes = map[string]string{

This way, the table gets autogenerated with uuit when using this tag example:
Guid string `orm:"type(uuid)" form:"-"`

I manually changed varchar to uuid inside db, and string variable works, but maybe ORM can automatically create uuid field inside database

Thank you and regards,
Sil

**Comment by lei-cao** [comment]
@tossp Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
