### ISSUE TITLE
postgresql 关键字转义字符应该是 双引号

### ISSUE THREAD

**Issue by xming4321** [astaxie/beego#711]
github.com/astaxie/beego/orm/orm.go 370
所以 

postgresql 查询会导致 报biao 存在的错误

var table_name = "user_info"
o.QueryTable(table_name).Filter("user_name", name).Filter("user_pass", pass).One(&user)

下面报错
<Ormer.QueryTable> table name: ``user_info`` not exists （注意 这里user_info 用了mysql对关键字的转义 上漂 那个字符）

**Comment by lei-cao** [comment]
@xming4321 Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@xming4321  is your issues solved? @astaxie is this a issue from beego?
