### ISSUE TITLE
自定义主键后manytomany的中间表长度变成0了

### ISSUE THREAD

**Issue by cnych** [astaxie/beego#726]
![image](https://cloud.githubusercontent.com/assets/3094973/3824999/ea5cf2a6-1d4e-11e4-9386-b7c9be5189f9.png)

由于role和user表的主键是我自定义的一个字段，没用自增长的，结果中间表自动生成的长度变成0了

> role和user里面主键是:varchar(36)

**Comment by micln** [comment]
请问何解？？

**Comment by lei-cao** [comment]
@cnych Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
