### ISSUE TITLE
Controllers and ORMs cannot unit test

### ISSUE THREAD

**Issue by AnthonyTsang** [astaxie/beego#731]
The very basic idea of unit testing is to only execute the testing subject and every other struct, object passed as params are injected with a mock object. Since we need to have a `beego.Controller` in our controller and it is not an interface (there is a `beego.ControllerInterface` but seems it is not serving this purpose) we cannot inject a mock struct as `beego.Controller`. Unit testing cannot apply on controllers. The easy way to make unit test possible, is to wrap every non method actions (like adding a variable to `Controller.Data` with a method. So that `beego.Controller` itself can turn to an interface. (Actually there is a naming convention  issue on `beego.Controller`. Every `er` should be an interface)

The similar concept on ORMs. Despite we have a very good interface for ORMs `Ormer`, `dbQuerier` is not public. We cannot make a mock struct to implement `Ormer`

**Comment by kyurdakok** [comment]
any updates?

**Comment by xiangxian** [comment]
ORMS unittest i used **"gopkg.in/testfixtures.v2"** init a test db all data is load by yml, and reload db in very Test func
