### ISSUE TITLE
beego 有没有权限处理的模块

### ISSUE THREAD

**Issue by zihuxinyu** [astaxie/beego#740]
RBAC？

**Comment by lei-cao** [comment]
@zihuxinyu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie  close?
duplicated https://github.com/astaxie/beego/issues/432

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like MAC, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

In fact, a light-weight project named [pybbs-go](https://github.com/tomoya92/pybbs-go) which is based on Beego already integrates casbin.

So please consider using casbin when beego implements RBAC security. Also let me know if there's any question:)

**Comment by astaxie** [comment]
👍  I will add casbin to https://beego.me/docs/contributed/

**Comment by hsluoyz** [comment]
I have submitted a PR here: https://github.com/astaxie/beego/pull/2620. It adds an authorization plugin, which
 supports ACL, RBAC, ABAC. Test is also included.

The interface is similar to the built-in HTTP basic authentication plugin and very easy to use. Welcome review!
