### ISSUE TITLE
mysql insert 插入 bug `2014-08-19 21:46:18 +0800 +0800`

### ISSUE THREAD

**Issue by zihuxinyu** [astaxie/beego#755]
当Struct设置为时间时 {  2014-08-19 21:46:18 +0800 CST} 
看打印的sql日志：
[ORM] - 2014-08-19 21:46:21 - [Queries/default] - [  OK /     db.Exec /     8.4ms] - [INSERT INTO `portal_user` (`guid`, `user_code`, `user_name`, `dpt_name`, `msgexpdate`) VALUES (?, ?, ?, ?, ?)] - `0`, ``, `x`, ``, `2014-08-19 21:46:18 +0800 +0800`

生成的语句中竟然多了一个+0800 没有找到这个转换是在哪个地方进行的。但我觉得是个bug
数据库配置为mysql

**Comment by lei-cao** [comment]
@zihuxinyu Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
