### ISSUE TITLE
自动生成API功能ParseInt问题

### ISSUE THREAD

**Issue by ustczen** [astaxie/beego#756]
试用狂抓酷霸炫的bee根据数据库自动生成api功能时，遇到了这样一个报错：
convert to `*int` failed, field: bcloud/models.Gameinfo.Id err: strconv.ParseInt: parsing "4100060581": value out of range
应该是ParseInt越界了，具体在StackOverflow上有讨论：
http://stackoverflow.com/questions/10747411/using-big-integer-values-in-go-parseint-only-coverts-up-to-2147483647

**Comment by webwlsong** [comment]
我也遇到这样的问题，还没有改进啊

**Comment by webwlsong** [comment]
api:Raw value: `[53 48 49 50 48 49 55 57 57 56 51 49 54 49 55 53 51 54]` convert to `*int` failed, field: api/models.Users.Id err: strconv.ParseInt: parsing "501201799831617536": value out of range

**Comment by lei-cao** [comment]
@ustczen Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by haroldTlan** [comment]
@astaxie 求解决方案
