### ISSUE TITLE
Beego ORM expects auto-increment column when creating new model

### ISSUE THREAD

**Issue by owentran** [astaxie/beego#815]
My model is using UUID as the primary key. This doesn't play well with the Insert method.

Two ways to handle this.

1. Use raw SQL (probably the right way for now)

2. Or just handle the error that comes back

Here's the code I use since I'm too lazy to write the raw SQL:

	func (u *User) Create() (error) {
		u.Uid = GetUUID().String()
		u.Password = EncryptPassword(u.Password)
		if _, err := orm.NewOrm().Insert(u); err != nil {
			if err.Error() != "no LastInsertId available" {
				return err
			}
		}
		return nil
        }

The orm schema definition doesn't support UUID so I define it as a string size(100) and then run a manual SQL command to change the definition:

	alter table users alter column uid type UUID using uid::uuid;

**Comment by derElektrobesen** [comment]
To solve this (still existed) problem you can call InsertMulti with 2 as the first argument =)
In this case LastInsertId() will not be called.

**Comment by Rychanfox** [comment]
ehy
