### ISSUE TITLE
ORM的模型内如果存在多个同类型的rel(fk)字段，则reverse(many)无法确定是根据哪个rel(fk)来查询。

### ISSUE THREAD

**Issue by kevinzheng** [astaxie/beego#874]
首先感谢谢Sir的聪明才智与辛勤工作！

实践中发现ORM的模型内如果存在多个同类型的rel(fk)字段，则reverse(many)无法确定是根据哪个rel(fk)来查询，reverse是不是应该提供指定通过哪个字段关联的方式？

比如我的模型，Replies应该通过ReplyToPost字段反向关联，由于reverse(many)无法指定关联的字段，因此 LoadRelated 查询会获取第一个*Post rel(fk)类型(即Topic)的值。
type Post struct {
	Id                     int64      `orm:"column(id);auto"`
	Topic               *Post      `orm:"rel(fk);on_delete(cascade);null"`
	ReplyToPost   *Post     `orm:"rel(fk);on_delete(cascade);null"`
	Replies            []*Post   `orm:"reverse(many);null"` 
	LastReply        *Post     `orm:"rel(fk);on_delete(set_null);null"`
}

**Comment by lei-cao** [comment]
@kevinzheng Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by baiyuang** [comment]
> 首先感谢谢Sir的聪明才智与辛勤工作！
> 
> 实践中发现ORM的模型内如果存在多个同类型的rel(fk)字段，则reverse(many)无法确定是根据哪个rel(fk)来查询，reverse是不是应该提供指定通过哪个字段关联的方式？
> 
> 比如我的模型，Replies应该通过ReplyToPost字段反向关联，由于reverse(many)无法指定关联的字段，因此 LoadRelated 查询会获取第一个_Post rel(fk)类型(即Topic)的值。
> type Post struct {
> Id int64 `orm:"column(id);auto"`
> Topic *Post `orm:"rel(fk);on_delete(cascade);null"`
> ReplyToPost *Post `orm:"rel(fk);on_delete(cascade);null"`
> Replies []_Post `orm:"reverse(many);null"`
> LastReply *Post `orm:"rel(fk);on_delete(set_null);null"`
> }

这个问题有解决方案吗？
