### ISSUE TITLE
How can I put diffent models into diffent databases?

### ISSUE THREAD

**Issue by xtheo** [astaxie/beego#895]
How can i put diffent models into diffent databases?

For example:
My models are:

``` golang
type Student struct {
    Id   int64
    Name string `orm:"size(10);index"`
    Age  int
}

type Teacher struct {
    Id   int64
    Name string `orm:"size(10);index"`
    Age  int
}

type Worker struct {
    Id   int64
    Name string `orm:"size(10);index"`
    Age  int
}
```

My databases are:

```
err:= orm.RegisterDataBase("default", "mysql", "user:pass@/tcp(localhost:3306)/testwebapp_default?charset=utf8&loc=Asia%2FShanghai")
err = orm.RegisterDataBase("db1", "mysql", "user:pass@/tcp(localhost:3306)/testwebapp_db1?charset=utf8&loc=Asia%2FShanghai")
err = orm.RegisterDataBase("db2", "mysql", "user:pass@/tcp(localhost:3306)/testwebapp_db2?charset=utf8&loc=Asia%2FShanghai")
```

register models:

```
orm.RegisterModel(new(Student), new(Teacher), new(Worker))
```

sync database:

```
orm.RunSyncdb("default", true, true)
orm.RunSyncdb("db1", true, true)
orm.RunSyncdb("db2", true, true)
```

now,all the databases contains  Student/Teacher/Worker.

orm.RunSyncdb do not have more parameters.

But I need the Student table in database default ,Teacher in db1,Worker in db2.
How can i do?

**Comment by feuvan** [comment]
I'm having the same difficult, we are placing user system in another db from business logic db.
I would suggest allow registering model from different database into the same modelcache, as @xtheo suggested.

**Comment by miadabrin** [comment]
@astaxie any news on this?

**Comment by Bowenwu1** [comment]
Any update?

**Comment by cxasm** [comment]
解决了吗？

func RegisterModelWithPrefix(prefix string, models ...interface{}) {

我觉得作者可以扩展这类函数。因为这个地方可以加一个前缀生成表。
那么对于的，操作表的函数，都应该有类似的WithPrefix函数。
这样就可以用同一个结构，但是不同的前缀或者后缀，去操作不同的表，但是表都是同样的结构。

**Comment by lipengg** [comment]
we resolve this question by this way:

1. register driver call "orm.RegisterDriver".
2. register database and models, create tables by call "orm.RunSyncdb"
3. reset model cache call "orm.ResetModelCache".
4. register another database and it's models, create tables by call "orm.RunSyncdb"
5. ...  repeat step 3 and 4 to create other tables for different database.
6. reset model cache by call "orm.ResetModelCache", and register all model again.

the code is :
```
	// register driver.
	orm.RegisterDriver(dbDriver, orm.DRMySQL)
	//  create table 'tree' for database 'plant'.
	orm.RegisterDataBase(dbAliasPlant, dbDriver, datasourcePlant)
	orm.RegisterModel(new(Tree))
	orm.RunSyncdb(dbAliasPlant, true, false)

	// we must clear the mode cache before create another database table.
	orm.ResetModelCache()
	//  create table 'bird' for database 'animal'.
	orm.RegisterDataBase(datasourceAnimal, dbDriver, datasourceAnimal)
	orm.RegisterModel(new(Bird))
	orm.RunSyncdb(datasourceAnimal, true, false)

	// we need register model again.
	orm.ResetModelCache()
	orm.RegisterModel(new(Bird), new(Tree))
	db, _ := orm.GetDB(dbAliasPlant)
	OrmObjPlant, _ = orm.NewOrmWithDB(dbDriver, dbAliasPlant, db)
	db, _ = orm.GetDB(datasourceAnimal)
	OrmObjAnimal, _ = orm.NewOrmWithDB(dbDriver, datasourceAnimal, db)
```

**Comment by sumaninster** [comment]
package ejabberd

import (
	"github.com/astaxie/beego/orm"
)

func (u *Users) TableName() string {
    return "users"
}

func (u *Users) NewOrm() orm.Ormer {
	orm.RegisterModel(new(Users))
	eorm := orm.NewOrm()
    eorm.Using("default")
	return eorm
}

func (u *Users) Clear() {
	orm.ResetModelCache()
}

func (u *Users) Insert() error {
	eorm := u.NewOrm()
	if _, err := eorm.Insert(u); err != nil {
		u.Clear()
		return err
	}
	u.Clear()
	return nil
}

func (u *Users) Read(fields ...string) error {
	eorm := u.NewOrm()
	if err := eorm.Read(u, fields...); err != nil {
		u.Clear()
		return err
	}
	u.Clear()
	return nil
}

func (u *Users) ReadOrCreate(field string, fields ...string) (bool, int64, error) {
	eorm := u.NewOrm()
	done, id, err := eorm.ReadOrCreate(u, field, fields...)
	u.Clear()
	return done, id, err
}

func (u *Users) Update(fields ...string) error {
	eorm := u.NewOrm()
	if _, err := eorm.Update(u, fields...); err != nil {
		u.Clear()
		return err
	}
	u.Clear()
	return nil
}

func (u *Users) Delete(fields ...string) error {
	eorm := u.NewOrm()
	if _, err := eorm.Delete(u, fields ...); err != nil {
		u.Clear()
		return err
	}
	u.Clear()
	return nil
}

func (u *Users) ListUsers() (int64, []Users, error) {
	var table Users
	var users []Users
	eorm := u.NewOrm()
	num, err := eorm.QueryTable(table).OrderBy("username").All(&users)
	u.Clear()
	return num, users, err
}

func init() {
}

-------------------------

package ejabberd

import (
    "github.com/astaxie/beego"
    "github.com/astaxie/beego/orm"
    "time"
    "fmt"
    _ "github.com/lib/pq"
)

var (
    DB_PREFIX string
    DB_USER string
    DB_PASSWORD string
    DB_HOST string
    DB_NAME string
    DB_PORT string
    Runmode string
)

type Users struct {
    Username            string      `orm:"pk"`
    ServerHost          string      //`orm:"pk"`
    Password            string
    Serverkey           string
    Salt                string
    iterationcount      int32
    CreatedAt           time.Time   `orm:"auto_now_add;type(datetime)"`
}

func init() {
    DB_PREFIX = beego.AppConfig.String("DB_PREFIX")
    DB_USER = beego.AppConfig.String("DB_USER")
    DB_PASSWORD = beego.AppConfig.String("DB_PASSWORD")
    DB_HOST = beego.AppConfig.String("DB_HOST")
    DB_NAME = beego.AppConfig.String("DB_NAME_EJABBERD")
    DB_PORT = beego.AppConfig.String("DB_PORT")
    Runmode = beego.AppConfig.String("runmode")
    
    switch Runmode {
    case "dev":
        orm.RegisterDriver("postgres", orm.DRPostgres)
        orm.RegisterDataBase("default", "postgres", fmt.Sprintf("postgres://%s:%s@%s/%s?port=%i&sslmode=disable",
        DB_USER, DB_PASSWORD, DB_HOST, DB_NAME, DB_PORT), 30)
        //orm.Debug = true
    }
}

**Comment by flycash** [comment]
follow #4105
