### ISSUE TITLE
Handling Error and Exceptional cases

### ISSUE THREAD

**Issue by chrisport** [astaxie/beego#898]
The way exceptional cases such as ```panic```, ```controller.Abort``` and ```middleware.Exception``` are handled, confuses me a bit. Mainly I have two **problems**: 

1. WriteHeader is already called, when my handler is reached and I cannot change the headers or the status code in my custom handler.
2. Custom handlers are not always called, e.g. in current develop-branch I cannot handle a ```panic("RANDOM_TEXT")``` or a ```controller.Abort("RANDOM_TEXT")```

Also confusing for me is the additional map of HTTPExceptions in [middleware](https://github.com/astaxie/beego/blob/develop/middleware/exceptions.go) which are treated separately.

I would prefer one way of treating errors, where custom handlers are always used if found and a (also configurable) default handler is used otherwise. Plus the custom handler should have the ability to change the headers and status code.  [(here a possible solution for the second point)](https://github.com/maidan-co/beego/blob/develop/httplib/SyncedResponseWriter.go).

I made a visualisation of the flow. It is not 100% valid anymore, since there were changes 3 days ago :), I will correct it asap. 
![](https://cloud.githubusercontent.com/assets/6203829/4862458/c5142bb6-610c-11e4-9567-b3ba59d11586.png)

PS: I'm also willing to write code, as soon as I understand the concept. :)

**Comment by someone1** [comment]
Any update on this? I'm running into issues where a panic responds with a 200 status, which make development that much harder to continue with.

**Comment by lukashes** [comment]
I can't customize errors too. Is doing any work by this problem?

**Comment by astaxie** [comment]
beego1.7 should works fix this
