### ISSUE TITLE
QuerySeter.All方法的fields参数能否支持“属性的属性”过滤查询？

### ISSUE THREAD

**Issue by kevinzheng** [astaxie/beego#901]
比如有User和Post两个struct，Post对象内含有一个User，既发布者。能否通过QuerySeter.All函数的fields参数来嵌套地过滤查询需用的字段，比如只需要Post的Title和Content字段，以及Post.Poster的Name和Email字段：QuerySeter.All("Post",  "Title", "Content", "Poster.Name", "Poster.Email")。因为在API构建中，需要根据请求的fields来查询指定的字段，请问能添加此功能支持吗？谢谢！

type User struct {
    Id         int
    Name  string
    Email   string
}
type Post struct {
    Id            int
    Title        string
    Content  string
    Poster    *User
}

**Comment by lei-cao** [comment]
@kevinzheng Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.
