### ISSUE TITLE
session各值过期时间不同而引起程序出错

### ISSUE THREAD

**Issue by meilihao** [astaxie/beego#924]
beego : 1.2.0

```go
this.SetSession("uid", user.Uid)
this.SetSession("level", user.Level)

 _, ok := ctx.Input.Session("uid").(int)
    if !ok && ctx.Request.RequestURI != "/login" {
        ctx.Redirect(302, "/login")
}
```
uid经常使用,同时用于过滤中间件检查uid判断用户是否已登录;level只是偶尔使用.
今天访问一个网页发现uid检查通过,而程序却因无法获取level而出错.

请问session中的各值的过期时间不是应该一样的吗?如果不一样,有什么办法避免这种问题?

**Comment by lei-cao** [comment]
@meilihao Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie should be closeable. @meilihao  is your issue solved ?
