### ISSUE TITLE
log file won't be re-created or re-opened after it had been deleted

### ISSUE THREAD

**Issue by missdeer** [astaxie/beego#970]
When the log target is file, if the log file is deleted by other applications, beego won't re-create this log file and write logs, even if other application creates a file with the same name, beego won't re-open that one. No logs any more.

-----------------------------

Added at 2015/1/13:
I know beego's log file can be rotated, but that's not I want.
I hope beego could re-create or re-open the log file if the fd is unavaible when it writes logs. No need to check the log file every time when it is written, just retry if writing failed, that is what I wanted.
But it really not so useful or common case, beego author may make the decision according to his perfer. As @astaxie replied below, make sure other applications won't delete the log file, it is acceptable.

**Comment by luw2007** [comment]
@missdeer 
1.  https://github.com/astaxie/beego/blob/master/logs/file.go#104 本身提供了多种分割日志文件的规则. 
//	{
//	"filename":"logs/beego.log",
//	"maxlines":10000,
//	"maxsize":1<<30,
//	"daily":true,
//	"maxdays":15,
//	"rotate":true
设置``"rotate": true`` 开启自动分割. 可以按照最大行, 文件大小, 按日分割, 最长保留天数,

2. "如果该log文件被其他程序删掉，之后beego不会再次创建该log文件并输出" 这个应该是操作系统的行为, windows 下有文件的读写锁,  不会出现此类问题; linux 下其他进程删除了文件, 当前程序(beego)并不知道, 对beego来说一切和删除文件之前一样(文件句柄还在).

**Comment by lei-cao** [comment]
@missdeer Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable?
