### ISSUE TITLE
CGI模式退出进程后Socket文件没有删除

### ISSUE THREAD

**Issue by athurg** [astaxie/beego#978]
不管是通过bee run运行，还是直接运行。如果是监听的Unix Socket，退出进程后不会自动删除这个Socket文件。导致下一次启动的时候报错，提示Socket已经存在。配置如下

`
usefcgi  = true
httpaddr = myapp.sock
httpport = 0
`

另有一个问题就是App启动的时候可否自定义Unix Socket的权限？比如打开为777权限？

**Comment by astaxie** [comment]
这个如果是非正常退出的话，没办法删除啊？只能每次在启动之前判断一下这个文件，然后删除再次去处理
