### ISSUE TITLE
timezone and registering alias

### ISSUE THREAD

**Issue by dfilipovic39** [astaxie/beego#979]
call to function addAliasWthDB should call detectTZ(al) to resolve timezone

func addAliasWthDB(aliasName, driverName string, db _sql.DB) (_alias, error) {
    al := new(alias)
    al.Name = aliasName
    al.DriverName = driverName
    al.DB = db
    detectTZ(al)
    if dr, ok := drivers[driverName]; ok {
        al.DbBaser = dbBasers[dr]
        al.Driver = dr
    } else {
        return nil, fmt.Errorf("driver name `%s` have not registered", driverName)
    }

```
err := db.Ping()
if err != nil {
    return nil, fmt.Errorf("register db Ping `%s`, %s", aliasName, err.Error())
}

if dataBaseCache.add(aliasName, al) == false {
    return nil, fmt.Errorf("DataBase alias name `%s` already registered, cannot reuse", aliasName)
}

return al, nil
```

}

**Comment by flycash** [comment]
We resolved this problem
