### ISSUE TITLE
api自动化文档

### ISSUE THREAD

**Issue by yanlinpu** [astaxie/beego#980]
一、跨域post问题

添加Ctx.Output.Header("Access-Control-Allow-Origin", "*")之后，localhost是能进行访问了，但是如果post（增）body带上参数之后，提示no content错误

二、swagger post参数

例如models中有一个 Users
  
    type Users struct {
	  Id        int       `orm:"column(id);auto"`
	  Username  string    `orm:"column(username);size(255);null"`
	  Password  string    `orm:"column(password);size(255);null"`
	  Email     string    `orm:"column(email);size(255);null"`
	  CreatedAt time.Time `orm:"column(created_at);type(datetime);auto_now_add"`
	  UpdatedAt time.Time `orm:"column(updated_at);type(datetime);auto_now"`
    }

id是主键  CreatedAt 和 UpdatedAt是系统时间  这三个字段不需要在swagger post接口中出现，应该怎么设置

**Comment by astaxie** [comment]
1. 你添加到哪里？

2. 不支持

**Comment by yanlinpu** [comment]
我忘了修改swagger中的 地址 sorry for troubling 

![g iwgiygfg q7xod2 i](https://cloud.githubusercontent.com/assets/3785079/5604572/bac3558a-93ff-11e4-85b5-b5515b45f143.jpg)

至于 第二个 我暂时 是修改了js文件  将这三个字段忽略了

    if (propertyName=="Id"||propertyName=="CreatedAt"||propertyName=="UpdatedAt")
        continue;

谢谢

**Comment by astaxie** [comment]
第二个问题，我昨天也修改了bee generate，你只要在struct里面增加tag就可以：

```
type Users struct {
  Id        int       `orm:"column(id);auto"  ignore:"yes"`
  Username  string    `orm:"column(username);size(255);null"`
  Password  string    `orm:"column(password);size(255);null"`
  Email     string    `orm:"column(email);size(255);null"`
  CreatedAt time.Time `orm:"column(created_at);type(datetime);auto_now_add" ignore:"yes"`
  UpdatedAt time.Time `orm:"column(updated_at);type(datetime);auto_now" ignore:"yes"`
}
```

**Comment by yanlinpu** [comment]
@astaxie 恩恩 thx

**Comment by Jinxiansen** [comment]
![1](https://user-images.githubusercontent.com/16829428/56786367-54f90880-682b-11e9-88fe-df78fab56aa3.png)
![2](https://user-images.githubusercontent.com/16829428/56786446-9093d280-682b-11e9-8847-c658e1ca51f0.png)

![WX20190426-135842](https://user-images.githubusercontent.com/16829428/56786408-6cd08c80-682b-11e9-8d01-9262a760a085.png)


@astaxie  我在 Struct 里忽略了这3个字段，但是在接口返回这个表的时候，依然返回了这3个字段以及 Password 字段。
