### ISSUE TITLE
Namespace support was not working as it should for me. Help needed.

### ISSUE THREAD

**Issue by anidotnet** [astaxie/beego#982]
Hi while playing around with this excellent framework, I found some problem in namespace support of beego. The problem is at a very basic configuration step, urls are not matching. So I suspect, I must have setup something wrong here. Could you please help me pointing it out?

Here goes my controller+router: https://gist.github.com/anidotnet/ac117922038aa987322d
While running it I am getting in the log -> ``[D] | GET        | /v1/user/    | 0     | notmatch   |`` 

Then I tweaked my controller+router a bit: https://gist.github.com/anidotnet/a575d176ceaadbe9e112
I got the same result as above. No match.

In next attempt, I configured in old-school way: https://gist.github.com/anidotnet/24432c3305050516ef1d
And it worked!

And here is the env details:
OS - Windows 7 32-bit
bee   :1.2.3
beego :1.4.2
Go    :go version go1.3.3 windows/386

Can you please let me know what is wrong here?

**Comment by astaxie** [comment]
do your project generate the `commentsRouter_user_controllers.go` in the router dir?

**Comment by anidotnet** [comment]
Nope! Nothing is getting generated while building it. So what could be the reason for it then?

**Comment by astaxie** [comment]
what's your runmode?

**Comment by anidotnet** [comment]
Dev only.. I read the doc, that it will be generated in dev mode, so I checked it alright..

**Comment by anidotnet** [comment]
One more update, when I tried on ubuntu 64bit with go1.4, the file got generated in router dir. But when I ran it, still I am getting nomatch. `[router.go:845] [D] | GET  | /v1/user/      | 1.179892ms   | notmatch   |`

I created the project using bee tool now. `bee api apidemo`. Then  build it and run it straight way with out modifying a single bit.

**Comment by astaxie** [comment]
can you share your code in dropbox. then I can debug for you. from your desciption I can't find the problem.

**Comment by anidotnet** [comment]
Here is the code. I uploaded it with compiled binary also. - https://www.dropbox.com/s/3km3ozeyfk4ho9f/course.7z?dl=0

**Comment by anidotnet** [comment]
@astaxie any update please?

**Comment by astaxie** [comment]
I can't download the code. and I have test your gist code. I can match the url.

**Comment by astaxie** [comment]
@anidotnet do you still have the problem now?
