### ISSUE TITLE
template path problem

### ISSUE THREAD

**Issue by sundy-li** [astaxie/beego#986]
In web project, I would like to create bin folder in the project, so I change the beego.ViewsPath = "../myviewpath" to fix it, but in the production env, I use supervisor to start the server like "command=/data/www/go_proj/src/myproj/bin/server", then beego cannot find the template path cause beego think / is the project path, and cannot find the template path /../myviewpath, how to fix it?

**Comment by astaxie** [comment]
you can set the `ViewsPath` in your `app.conf`. So when you deploy the application change the value to absolute path

**Comment by sundy-li** [comment]
Our company's project conf all controlled in json, I wonder is that a possiable way to solve this problem without app.conf?

**Comment by sundy-li** [comment]
I see, thanks xie da
