### ISSUE TITLE
阿里云服务器：不能监听 0.0.0.0 地址

### ISSUE THREAD

**Issue by phpqinsir** [astaxie/beego#988]
beego通过nginx代理可以正常被外网访问。但是，直接做为服务器，阿里云服务器要求必须监听 0.0.0.0 IP。否则，防火墙开了端口外网也访问不进去请求。

所以，想问 beego怎样才能监听 0.0.0.0 ip。

附服务器监听列表：

tcp        0      0 127.0.0.1:8080              0.0.0.0:*                   LISTEN      3061/./main
tcp        0      0 0.0.0.0:80                  0.0.0.0:*                   LISTEN      1367/nginx
tcp        0      0 0.0.0.0:21                  0.0.0.0:*                   LISTEN      1399/vsftpd
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      884/sshd

可以看出我的80、21、22都是监听在0.0.0.0 IP上的。我的beego没办法监听 0.0.0.0。就算把httpaddr设置为0.0.0.0无计于事。

各位有遇到过这种情况吗？望解决之！！！

**Comment by athurg** [comment]
直接不设置httpaddr试试看。像这样：
```ApacheConf
runmode = dev
#httpaddr = emp.sock
httpport = 9000
```

**Comment by rockdean** [comment]
我也遇到了，但后面没搞肯定，求解决方法。

**Comment by phpqinsir** [comment]
虽然没办法监听0.0.0.0 IP也没关系。阿里云的工程师已经解决了在其他IP上监听外网访问的问题。

**Comment by W-B-S** [comment]
如何做到其它IP上监听外网访问的问题
