### ISSUE TITLE
Prepare 方法中 执行 XsrfFormHtml 为空

### ISSUE THREAD

**Issue by fengcen** [astaxie/beego#995]
在 Prepare() 中执行 XsrfFormHtml，xsrf 会为空，只有在 controller method 中执行才不会为空。能否设置一个共同的在 controller 中执行的方法，这样我不需要每一个方法都加一个函数？

**Comment by astaxie** [comment]
没明白你的描述的含义

**Comment by fengcen** [comment]
如果在 Prepare 方法中执行 this.XsrfFormHtml()，生成的html中 xsrf 是空的，没有值。但是我想控制的是：只有一个 controller 需要使用 xsrf ，另一个不需要，我怎么在 controller 中启用 xsrf ？
