### ISSUE TITLE
GetCookie问题

### ISSUE THREAD

**Issue by jilili** [astaxie/beego#996]
Ubuntu中GetCookie有问题，

如果保存的Cookie中保存的内容中包含","就不能取出来
 例如 ReturnUrlKey=http://127.0.0.1:8000/csrs?status=new,processing不能读出
 如果 ReturnUrlKey=http://127.0.0.1:8000/csrs?status=new 就可以读出

Mac系统中正常

**Comment by astaxie** [comment]
空格 ； ， \ " <> 这六个字符不可以，尽管可以写入，但无法读取。这是各个浏览器的限制

**Comment by astaxie** [comment]
https://github.com/golang/go/issues/7243

http://stackoverflow.com/questions/2227576/cannot-get-value-from-cookie-in-java-value-contains-commas

**Comment by lei-cao** [comment]
@jilili Thank you for supporting beego. please update or submit your issue in English for a better international user friendly communication.

**Comment by lei-cao** [comment]
@astaxie closeable?

**Comment by ysqi** [comment]
@astaxie  close it ?
