### ISSUE TITLE
ParseForm and checkbox

### ISSUE THREAD

**Issue by Nemo08** [astaxie/beego#998]
If checkbox in *.tpl have attribute "value", even empty, when value of checkbox after ParseForm always setted to false
minimal example: https://github.com/Nemo08/checkbox_error

bee   :1.2.3
beego :1.4.2
Go    :go version go1.4 windows/386
Windows 7 x32

**Comment by ysqi** [comment]
@Nemo08  can't find url :https://github.com/Nemo08/checkbox_error

**Comment by astaxie** [comment]
bool default is false
